### ISSUE TITLE
Regression in 0.22.1: varying length of array index on case-by-case basis no longer works

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1600] opened 2016-01-05 13:37 UTC
The following code:

```python
from numba import jit
import numpy as np

@jit(nopython=True)
def f(a, i):
    if i == 0:
        a[1] = 1
    else:
        a[1,1] = 1


a1 = np.zeros(6)
a2 = np.zeros((6,6))

f(a1, 0)
f(a2, 1)
```

executes correctly in 0.21.0 but in 0.22.1 produces the following traceback:

```
$ python mixed_index.py 

Traceback (most recent call last):
  File "mixed_index.py", line 15, in <module>
    f(a1, 0)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 172, in _compile_for_args
    return self.compile(sig)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 350, in compile
    flags=flags, locals=self.locals)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 644, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 361, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 370, in compile_bytecode
    return self._compile_bytecode()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 631, in _compile_bytecode
    return pm.run(self.status)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/home/gmarkall/work/numba/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 458, in stage_nopython_frontend
    self.locals)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 759, in type_inference_stage
    infer.propagate()
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 510, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.SetItemConstraint object at 0x7f6d0bc47a90>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 377, in __call__
    index=it, value=vt):
  File "/home/gmarkall/work/numba/numba/typing/context.py", line 149, in resolve_setitem
    return self.resolve_function_type("setitem", args, kws)
  File "/home/gmarkall/work/numba/numba/typing/context.py", line 97, in resolve_function_type
    res = defn.apply(args, kws)
  File "/home/gmarkall/work/numba/numba/typing/templates.py", line 155, in apply
    sig = generic(args, kws)
  File "/home/gmarkall/work/numba/numba/typing/arraydecl.py", line 159, in generic
    out = get_array_index_type(ary, idx)
  File "/home/gmarkall/work/numba/numba/typing/arraydecl.py", line 76, in get_array_index_type
    % (ary, n_indices, idx))
TypeError: cannot index array(float64, 1d, C) with 2 indices: (int64 x 2)
--%<-----------------------------------------------------------------

File "mixed_index.py", line 9
```

It looks to me that the only reason that this worked before was because the "erroneous" indexing of a 1D array with a 2D index and vice-versa in each call was sneaking past the typing phase, but this isn't something that was explicitly intended to be supported.

Any thoughts on whether this can be made to work again?

**Comment by sklam** [comment] 2016-01-05 16:27
I am a bit surprised that it worked once.  The type error is expected.

**Comment by sklam** [comment] 2016-01-05 16:38
I wonder if we can make the typing phase replace the certain erroneous operation with a raise statement instead of failing the typing phase.  This would mean greater flexibility.

**Comment by pitrou** [comment] 2016-01-05 16:50
> I wonder if we can make the typing phase replace certain erroneous operations with raise statements instead of failing the typing phase. This would mean greater flexibility.

For consistency, we would need to do it for all typing errors, which would end up very expensive in terms of added complexity in the code, and arguably for little gain.

**Comment by pitrou** [comment] 2016-01-05 16:51
Though perhaps a "smart" way (read: not too awful) would be to have some kind of "Poison" type that gets propagated by operations whose typing fails...

**Comment by sklam** [comment] 2016-01-05 16:52
@pitrou you read my mind
I was thinking of a Poison type as well

**Comment by pitrou** [comment] 2016-01-05 19:56
By the way, I agree this issue is not a bug, just a strengthening of our typing. I'm closing.

**Closed by pitrou** 2016-01-05 19:56 UTC
