### ISSUE TITLE
hpat error with master

### ISSUE THREAD

**Issue by sklam** [numba/numba#4533] opened 2019-09-07 04:13 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

hpat branch https://github.com/IntelPython/hpat/compare/pandas_series_operators is failing against latest master. The failling test is: `python -m hpat.runtests hpat.tests.test_series.TestSeries.test_series_copy_str1`.

<details>
<summary>traceback</summary>

```
======================================================================
ERROR: test_series_copy_str1 (hpat.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/siu/dev/numba/numba/inline_closurecall.py", line 338, in inline_closure_call
    typingctx, callee_ir, arg_typs, None)
  File "/Users/siu/dev/numba/numba/compiler.py", line 1118, in type_inference_stage
    infer.build_constraint()
  File "/Users/siu/dev/numba/numba/typeinfer.py", line 871, in build_constraint
    self.constrain_statement(inst)
  File "/Users/siu/dev/numba/numba/typeinfer.py", line 1150, in constrain_statement
    self.typeof_assign(inst)
  File "/Users/siu/dev/numba/numba/typeinfer.py", line 1221, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/Users/siu/dev/numba/numba/typeinfer.py", line 1318, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/Users/siu/dev/numba/numba/typeinfer.py", line 1242, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.errors.TypingError: Untyped global name 'hpat': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

File "<string>", line 2:
<source missing, REPL/exec in use?>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/siu/dev/hpat/hpat/tests/test_series.py", line 256, in test_series_copy_str1
    np.testing.assert_array_equal(hpat_func(S), test_impl(S))
  File "/Users/siu/dev/numba/numba/dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/siu/dev/numba/numba/dispatcher.py", line 318, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/siu/dev/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in hpat mode pipeline (step: typed hiframes pass)
Untyped global name 'hpat': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

File "<string>", line 2:
<source missing, REPL/exec in use?>
```

</details>

First failing commit is 1809a026eb2c14a302ee9f529d505c849b95148f

**Comment by stuartarchibald** [comment] 2019-09-13 11:40
The issue is that the inliner now expects that an object that is an instance of a `types.FunctionType` type to be self consistent/valid. This means that if the function object `.__code__` needs globals to execute then they should be self consistently defined in the function object `.__globals__` attr.

A Numba only reproducer would be:
```python
from numba import njit
import numpy as np

def gen():
    source = """
def myfunc(i):
    return np.arange(i)
"""
    l = {}
    exec(source, {}, l) # bad, invalid globals, the function needs NumPy
    return l['myfunc']

bad = njit(gen())

@njit
def call():
    bad(10)

call()

```

**Comment by stuartarchibald** [comment] 2019-09-16 10:58
Downstream PR was merged https://github.com/IntelPython/hpat/pull/135 assume worked around/fixed?

**Comment by stuartarchibald** [comment] 2020-04-14 11:39
@sklam presume we can close this now? IIRC SDC has no use of `inline_closure_call` any more?

**Comment by stuartarchibald** [comment] 2020-05-12 12:00
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-05-12 12:00 UTC
Labels: bug
