### ISSUE TITLE
guvectorize with target='parallel' does not stop threads

### ISSUE THREAD

**Issue by jfpuget** [numba/numba#1630] opened 2016-01-18 09:01 UTC
Hi,

the following code ran on Anaconda with Python 3.5 leaves a Python process running at nearly 100% of cpu.  Seems the threads created are still running.  I am using Numba 0.23.0

    import numpy as np
    from numba import jit, vectorize, guvectorize, float64, complex64, int32, float32
    
    @jit(int32(complex64, int32))
    def mandelbrot(c,maxiter):
        nreal = 0
        real = 0
        imag = 0
        for n in range(maxiter):
            nreal = real*real - imag*imag + c.real
            imag = 2* real*imag + c.imag
            real = nreal;
            if real * real + imag * imag > 4.0:
                return n
        return 0
    
    @guvectorize([(complex64[:], int32[:], int32[:])], '(n),()->(n)', target='parallel')
    def mandelbrot_numpy(c, maxit, output):
        maxiter = maxit[0]
        for i in range(c.shape[0]):
            output[i] = mandelbrot(c[i],maxiter)
            
    def mandelbrot_set2(xmin,xmax,ymin,ymax,width,height,maxiter):
        r1 = np.linspace(xmin, xmax, width, dtype=np.float32)
        r2 = np.linspace(ymin, ymax, height, dtype=np.float32)
        c = r1 + r2[:,None]*1j
        n3 = mandelbrot_numpy(c,maxiter)
        return (r1,r2,n3.T) 
    
    %timeit mandelbrot_set2(-2.0,0.5,-1.25,1.25,1000,1000,80)

**Comment by pitrou** [comment] 2016-01-18 12:30
Are you under Windows? I can't reproduce on Linux.

**Comment by jfpuget** [comment] 2016-01-18 13:41
Yes, Windows 7, Anaconda 64 bits, Python 3.5.

**Comment by seibert** [comment] 2016-01-18 14:41
This sounds similar to a bug that @sklam fixed once before...

**Closed** 2016-01-18 17:32 UTC

**Comment by jfpuget** [comment] 2016-02-13 10:51
Just for confirmaition, this is indeed fixed with latest Numba.
