### ISSUE TITLE
PicklingError while returning typed list of jitclass objects from njit function

### ISSUE THREAD

**Issue by rpopovici** [numba/numba#6138] opened 2020-08-17 11:03 UTC
This error is related to #6032

```
import numba as nb
from numba import jit, njit, types, typed
from numba.experimental import jitclass
from numba import int64, float64

@jitclass([('x', float64), ('y', float64), ('z', float64)])
class Vector(object):
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def clone(self):
        return Vector(self.x, self.y, self.z)

VectorType = Vector.class_type.instance_type

@njit
def load_mesh():
    vertices = typed.List.empty_list(VectorType)

    for idx in range(0, 10):
        vertices.append(Vector(idx, idx, idx))
    return vertices

vertices = load_mesh()

```

Same behaviour, if we comment out clone method or make it to return a value other a Vector object it will work. The function load_mesh with return the newly created list

**Comment by rpopovici** [comment] 2020-08-17 11:06
Workaround I found here is to pass the empty list as a parameter to the load function. then it will  work
```
@njit
def load_mesh(vertices):
    # vertices = typed.List.empty_list(VectorType)
    for idx in range(0, 10):
        vertices.append(Vector(idx, idx, idx))
    # return vertices

vertices = typed.List.empty_list(VectorType)
load_mesh(vertices)
```

**Comment by stuartarchibald** [comment] 2020-08-17 11:35
Thanks for the report. Think that this is due to the problem described here: https://github.com/numba/numba/issues/6032#issuecomment-674827250 am going to close this as I believe it's the same thing (and also a duplicate of https://github.com/numba/numba/issues/1846), please reopen if you think it's something different, many thanks.

**Closed by stuartarchibald** 2020-08-17 11:35 UTC
