### ISSUE TITLE
Use of unsupported opcode (LIST_EXTEND) found

### ISSUE THREAD

**Issue by louisabraham** [numba/numba#6614] opened 2021-01-03 22:49 UTC
## Reporting a bug

I tried to run this example from the documentation:
```
from numba import njit
from numba.typed import List

@njit
def foo():
    # Instantiate a typed-list
    l = List()
    # Append a value to it, this will set the type to int32/int64
    # (depending on platform)
    l.append(42)
    # The usual list operations, getitem, pop and length are
    # supported
    print(l[0])   # 42
    l[0] = 23
    print(l[0])   # 23
    print(len(l)) # 1
    l.pop()
    print(len(l)) # 0
    return l

foo()
```

I get
```
UnsupportedError                          Traceback (most recent call last)
<ipython-input-10-bf2ac9c9766e> in <module>
     19     return l
     20 
---> 21 foo()

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info                                                                    
--> 418             error_rewrite(e, 'unsupported_error')
    419         except (errors.NotDefinedError, errors.RedefinedError,
    420                 errors.VerificationError) as e:

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~/.local/lib/python3.9/site-packages/numba/core/utils.py in reraise(tp, value, tb)                                                                        
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

UnsupportedError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (LIST_EXTEND) found

File "../../../.local/lib/python3.9/site-packages/numba/cpython/builtins.py", line 569:
    def call_ctor(cls, *args):
        return numba_typeref_ctor(cls, *args)
        ^

During: lowering "$4call_function.1 = call $2load_global.0(func=$2load_global.0, args=[], kws=(), vararg=None)" at <ipython-input-10-bf2ac9c9766e> (7)
```

## Version

- aarch64
- Python 3.9.1
- numba 0.51.2
- llvmlite 0.34.0
- llvm: tested with versions 9 to 11. I know only 9 is supported but currently on arm stable only llvm 10 and 11 are present. I still had llvm9 but it did not install files for python 3.9. I get the exact same error on all 3 versions. I can execute other njit numba code fine with all versions.

**Comment by louisabraham** [comment] 2021-01-03 22:56
There is definitely something wrong in my installation:

```
from numba import njit
import numpy as np

@njit
def f(l):
    return np.argsort(l)
    
f(np.arange(10))
```

```
TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function make_quicksort_impl.<locals>.run_quicksort at 0xffff9fb82310>) found for signature:
 
 >>> run_quicksort(array(int64, 1d, C))
 
There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
      With argument(s): '(array(int64, 1d, C))':
     Rejected as the implementation raised a specific error:
       UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
     Use of unsupported opcode (LOAD_ASSERTION_ERROR) found
     
     File "../../../.local/lib/python3.9/site-packages/numba/misc/quicksort.py", line 180:
         def run_quicksort(A):
             <source elided>
                 while high - low >= SMALL_QUICKSORT:
                     assert n < MAX_STACK
                     ^
     
  raised from /home/louisabraham/.local/lib/python3.9/site-packages/numba/core/byteflow.py:269

During: resolving callee type: Function(<function make_quicksort_impl.<locals>.run_quicksort at 0xffff9fb82310>)
During: typing of call at /home/louisabraham/.local/lib/python3.9/site-packages/numba/np/arrayobj.py (5032)


File "../../../.local/lib/python3.9/site-packages/numba/np/arrayobj.py", line 5032:
    def array_argsort_impl(arr):
        return sort_func(arr)
        ^

During: lowering "$8call_method.3 = call $4load_method.1(l, func=$4load_method.1, args=[Var(l, <ipython-input-2-2fb691d45df3>:3)], kws=(), vararg=None)" at <ipython-input-2-2fb691d45df3> (3)
```

**Comment by louisabraham** [comment] 2021-01-03 23:00
AH! Trying to compile/install from master tells me 3.9 is not supported, is that the reason?

**Comment by seibert** [comment] 2021-01-04 00:44
Correct, Python 3.9 is not supported yet.  See #6345.

We haven't found a reliable way to convince pip not to install Numba on unsupported Python versions yet...

**Comment by stuartarchibald** [comment] 2021-01-04 10:29
Closing as duplicate of https://github.com/numba/numba/issues/6345. Thanks for reporting.

To follow 3.9 support progress please subscribe to https://github.com/numba/numba/pull/6579.

**Closed by stuartarchibald** 2021-01-04 10:29 UTC

**Comment by alobbs** [comment] 2021-01-05 18:06
Hitting `Use of unsupported opcode (LOAD_ASSERTION_ERROR) found`; also with Python 3.9.

**Comment by esc** [comment] 2021-01-05 19:03
@alobbs thank you for adding to this, this is the result of Python 3.9 currently not being supported by Numba.
