### ISSUE TITLE
using numba with "from collections import Counter"

### ISSUE THREAD

**Issue by oussamabnr** [numba/numba#5535] opened 2020-04-09 11:59 UTC
Hi, could you help me please to run this function using numba .

`from collections import Counter
@njit(nopython=True)
def TE(C):
        pxxy = Counter(literal_unroll(map(tuple,C)))
        pxy = Counter(map(tuple,C[:,1:]))
        pxx = Counter(map(tuple,C[:,:2]))
        px = Counter(map(tuple,C[:,1:2]))
        
        A = pxxy.keys()
        
        tot = float(sum(pxxy.values()))
    
        return sum((pxxy[k]/tot)* np.log2( (pxxy[k]/float(pxy[k[1:]])) / (pxx[k[:2]]/float(px[k[1:2]])) ) for k in A)`

It generates an error C is a matrix of 0 and 1 with 3 columns

**Comment by gmarkall** [comment] 2020-04-09 19:49
Thanks for the question - a few remarks on the above:

- You can write blocks of code in Markdown using three backticks on a line, instead of just the one - see e.g. https://github.github.com/gfm/#example-89
- Using `nopython=True` with `njit` is redundant - `njit` is just a shorthand for `@jit(nopython=True)`
- It would be a bit easier to look into if the code provided were executable to demonstrate the issue, with some explanation of the expected outcome from running it.

I've had a guess at what the executable reproducer might be:

```python
from numba import njit, literal_unroll
from collections import Counter
import numpy as np


@njit
def TE(C):
    pxxy = Counter(literal_unroll(map(tuple, C)))
    pxy = Counter(map(tuple, C[:, 1:]))
    pxx = Counter(map(tuple, C[:, :2]))
    px = Counter(map(tuple, C[:, 1:2]))

    A = pxxy.keys()

    tot = float(sum(pxxy.values()))

    return sum(
        (pxxy[k] / tot) * np.log2((pxxy[k] / float(pxy[k[1:]])) /
                                  (pxx[k[:2]] / float(px[k[1:2]])))
        for k in A
    )

c = np.random.rand(5,5,5)

TE(c)
```

There are some difficulties with using this with Numba directly:

- The generator expression (`(... for k in A`) is not supported in nopython mode - this would need to be converted to a loop. See the list of supported Python language features: http://numba.pydata.org/numba-doc/dev/reference/pysupported.html?highlight=generator%20expression#language
- `Collections.counter` is probably also not supported in nopython mode. Standard library features that are supported are listed here: http://numba.pydata.org/numba-doc/dev/reference/pysupported.html?highlight=generator%20expression#standard-library-modules

**Comment by stuartarchibald** [comment] 2020-05-01 16:33
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-05-01 16:33 UTC
Labels: question
