### ISSUE TITLE
 NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode)

### ISSUE THREAD

**Issue by Galadriel0** [numba/numba#3764] opened 2019-02-14 01:27 UTC
anyone helps?
Thank you very much.
the errors:
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    161         try:
--> 162             return self._con[name]
    163         except KeyError:

KeyError: '$34.2'

During handling of the above exception, another exception occurred:

NotDefinedError                           Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get_exact(self, name)
    801         try:
--> 802             return self.localvars.get(name)
    803         except NotDefinedError:

~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    163         except KeyError:
--> 164             raise NotDefinedError(name)
    165 

NotDefinedError: Variable '$34.2' is not defined.

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    161         try:
--> 162             return self._con[name]
    163         except KeyError:

KeyError: '$34.2'

During handling of the above exception, another exception occurred:

NotDefinedError                           Traceback (most recent call last)
<ipython-input-37-bd9942bb1fe1> in <module>
     45                 columns[39] = b[index_2,1]
     46                 return [columns[15],columns[16],columns[38],columns[39]]
---> 47             data = main("S655kHCRHits.dat")
     48             print(data)
     49 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    354             # These errors are probably from an issue with either the code supplied
    355             # being syntactically or otherwise invalid
--> 356             error_rewrite(e, 'interpreter')
    357         except errors.ConstantInferenceError as e:
    358             # this is from trying to infer something as constant when it isn't

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode)
Variable '$34.2' is not defined.
Unsupported Python functionality was found in the code Numba was trying to
compile. This error could be due to invalid code, does the code work
without Numba? (To temporarily disable Numba JIT, set the `NUMBA_DISABLE_JIT`
environment variable to non-zero, and then rerun the code).

If the code is valid and the unsupported functionality is important to you
please file a feature request at: https://github.com/numba/numba/issues/new

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

**Comment by stuartarchibald** [comment] 2019-02-14 10:37
Thanks for the report. I presume this is a duplicate of https://github.com/numba/numba/issues/3765? so am going to close it, if this is not the case, please reopen it and paste in the code that is causing the error to appear.

**Closed by stuartarchibald** 2019-02-14 10:37 UTC
