### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>     from numba.core.typeconv import _typeconv ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Sud1123456** [numba/numba#5636] opened 2020-04-27 21:33 UTC
Can anyone help!!!

PS C:\Users\dell\Desktop\Drum Covers\Bindis and Bangles> spleeter separate -i 'Take 1.wav' -p spleeter:4stems -o splits
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.5.1', 'console_scripts', 'spleeter')()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\spleeter\separator.py", line 23, in <module>
    from librosa.core import stft, istft
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\dell\AppData\Local\Programs\Python\Python36\python.exe

**Comment by seibert** [comment] 2020-04-27 21:55
this is likely duplicate of #5600.  There is a workaround in that thread until we push out a new release this week.

**Closed** 2020-04-28 08:59 UTC

**Comment by Fngg** [comment] 2021-11-07 14:06
python -m pip uninstall numba
python -m pip install numba==0.47.0

**Comment by gar456** [comment] 2023-04-09 04:32
how to solve error

**Comment by Suhailjan809** [comment] 2024-09-20 00:10
ModuleNotFoundError                       Traceback (most recent call last)
File c:\Users\Abu Dawood\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\compat\_optional.py:135, in import_optional_dependency(name, extra, errors, min_version)
    [134](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:134) try:
--> [135](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:135)     module = importlib.import_module(name)
    [136](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:136) except ImportError:

File c:\Users\Abu Dawood\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90, in import_module(name, package)
     [89](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/importlib/__init__.py:89)         level += 1
---> [90](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/importlib/__init__.py:90) return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1387, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1360, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1324, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[4], [line 3](vscode-notebook-cell:?execution_count=4&line=3)
      [1](vscode-notebook-cell:?execution_count=4&line=1) # step [2](vscode-notebook-cell:?execution_count=4&line=2)
      2 # readin/ importing data
...
--> [138](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:138)         raise ImportError(msg)
    [139](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:139)     return None
    [141](file:///C:/Users/Abu%20Dawood/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/compat/_optional.py:141) # Handle submodules: if we have submodule, grab parent module from sys.modules

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?5d7bc822-5c20-41d2-9283-2c2cec076e1a) or open in a [text editor](command:workbench.action.openLargeOutput?5d7bc822-5c20-41d2-9283-2c2cec076e1a). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 1
----> 1 import openpyxl as xl

ModuleNotFoundError: No module named 'openpyxl'

**Comment by abdosamy2008** [comment] 2024-11-01 17:59
Traceback (most recent call last):
  File "c:\Users\abdeo\Desktop\cc\check_accounts.py", line 129, in <module>
    send_data_thread(user)
  File "c:\Users\abdeo\Desktop\cc\check_accounts.py", line 122, in send_data_thread
    send_data(user, server[0], 1)
  File "c:\Users\abdeo\Desktop\cc\check_accounts.py", line 63, in send_data
    ws = websocket.create_connection(url, header=headers, sslopt={"cert_reqs": ssl.CERT_NONE})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 646, in create_connection
    websock.connect(url, **options)
  File "C:\Users\abdeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "C:\Users\abdeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket    
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1104, in _create       
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1382, in do_handshake  
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
