### ISSUE TITLE
[bug] "AssertionError: Failed at object (object mode frontend)" exception from simple code

### ISSUE THREAD

**Issue by smosesli** [numba/numba#3057] opened 2018-06-26 16:08 UTC
Minimal repro code:

```python
import numpy as np
from numba import jit
import numba


@jit
def foo():
    my_num = 10
    my_dict = {}

    nodes = [i for i in range(my_num)]

    my_list = [0]
    for node in nodes:
        if node in my_list:
            my_dict.update({node: 0})
        else:
            my_dict.update({node: 1})

    """ Post processing """
    res = np.zeros((my_num, 1))
    for node in my_dict:
        res[node] = my_dict[node]
    return res


print(numba.__version__)
mat = foo()
print(mat)
```

**Comment by stuartarchibald** [comment] 2018-06-26 17:07
updated comment to use valid markdown

**Comment by stuartarchibald** [comment] 2018-06-26 17:10
Thanks for the report, this is a known issue due to a bug in the interaction between looplifting and inlining. See also: https://github.com/numba/numba/issues/2955.

**Comment by stuartarchibald** [comment] 2019-09-11 14:06
Cannot reproduce on 0.45. Closing assumed fixed.

**Closed by stuartarchibald** 2019-09-11 14:06 UTC
Labels: bug
