### ISSUE TITLE
Portable numba-cudatoolkit installation

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3970] opened 2019-04-13 08:19 UTC
I am trying to install cudatoolkit on winpython (since it is the only way to run python portable), but I am running into this issue https://github.com/numba/conda-recipe-cudatoolkit/issues/17
Could it be possible to generate a specific numba cudatoolkit distribution, with all the necessary dependencies to be installed via pip, in order to run it from winpython?

**Comment by stuartarchibald** [comment] 2019-04-15 07:56
Thanks for the request. I'm closing this ticket as it is a duplicate of https://github.com/numba/conda-recipe-cudatoolkit/issues/17 which is part of the distributable package set under the Numba organisation already. I'll post a reply there.

**Closed by stuartarchibald** 2019-04-15 07:56 UTC
