### ISSUE TITLE
Wrong results with prange+parallel=True

### ISSUE THREAD

**Issue by zephyr111** [numba/numba#8184] opened 2022-06-22 21:10 UTC
## Reporting a bug

We found a bug with `prange` in the last version of Numba (0.55.2) while discussing in the StackOverflow post: https://stackoverflow.com/questions/72717489/numba-slows-down-the-loop-with-independent-iterations/72721818 .

Here is the reproducible code:

```python
import numba

@numba.jit(nopython=True)
def power_method(A, v):
    u = v.copy()
    for i in range(3 * 10**3):
        u = A @ u
        u /= np.linalg.norm(u)
    return u

@numba.jit(nopython=True, parallel=True)
def iterate_grid_seq(A, scale, sz):
    assert A.shape[0] == A.shape[1] == 3
    n = A.shape[0]

    results = np.empty((sz**3, n))
    tmp = np.linspace(-scale, scale, sz)
    
    for i1 in range(sz):
        v = np.empty(n, dtype=np.float64)
        v1 = tmp[i1]
        for i2, v2 in enumerate(tmp):
            for i3, v3 in enumerate(tmp):
                v[0] = v1
                v[1] = v2
                v[2] = v3

                u = power_method(A, v)

                idx = i1 * sz**2 + i2 * sz + i3
                results[idx] = u.copy()
    
    return results

@numba.jit(nopython=True, parallel=True)
def iterate_grid_par(A, scale, sz):
    assert A.shape[0] == A.shape[1] == 3
    n = A.shape[0]

    results = np.empty((sz**3, n))
    tmp = np.linspace(-scale, scale, sz)
    
    for i1 in numba.prange(sz):
        v = np.empty(n, dtype=np.float64)
        v1 = tmp[i1]
        for i2, v2 in enumerate(tmp):
            for i3, v3 in enumerate(tmp):
                v[0] = v1
                v[1] = v2
                v[2] = v3

                u = power_method(A, v)

                idx = i1 * sz**2 + i2 * sz + i3
                results[idx] = u.copy()
    
    return results

n = 3
np.random.seed(0)
A = np.random.randn(n, n)

res_seq = iterate_grid_seq(A, 5.0, 20)
res_par = iterate_grid_par(A, 5.0, 20)

print(res_seq.sum())
print(res_par.sum())
print(np.abs(res_seq - res_par).sum())
```

Here is the result:

```
9.094947017729282e-13
-6076.054452706904
6076.054452706905
```

One can see that the parallel result is completely wrong (very different from the sequential one) while the code seems correct. Moving `tmp` in the parallel loop strangely impact the result of the parallel version (not the sequential one). It also happen on the code of the provided answer which barely use arrays in the inner loops (nor any advanced feature except unpacking). The most surprizing thing is that the code is embarrassingly parallel and each thread basically write in independent unique cells.

Reproduced on CPython 3.8.1 on Windows.

**Comment by gmarkall** [comment] 2022-06-23 12:03
I can reproduce this (Linux, CPython 3.10.4, Numba `main`). A slightly shorter reproducer:

```python
from numba import njit, prange
import numpy as np


@njit
def power_method(A, v):
    u = v.copy()
    for i in range(3 * 10**3):
        u = A @ u
        u /= np.linalg.norm(u)
    return u


def iterate_grid(A, scale, sz):
    assert A.shape[0] == A.shape[1] == 3
    n = A.shape[0]

    results = np.empty((sz**3, n))
    tmp = np.linspace(-scale, scale, sz)

    for i1 in prange(sz):
        v = np.empty(n, dtype=np.float64)
        v1 = tmp[i1]
        for i2, v2 in enumerate(tmp):
            for i3, v3 in enumerate(tmp):
                v[0] = v1
                v[1] = v2
                v[2] = v3

                u = power_method(A, v)

                idx = i1 * sz**2 + i2 * sz + i3
                results[idx] = u.copy()

    return results


n = 3
np.random.seed(0)
A = np.random.randn(n, n)

res_seq = njit(parallel=False)(iterate_grid)(A, 5.0, 20)
res_par = njit(parallel=True)(iterate_grid)(A, 5.0, 20)

print(res_seq.sum())
print(res_par.sum())
print(np.abs(res_seq - res_par).sum())
```

cc @DrTodd13 for info.

**Comment by jpn--** [comment] 2022-09-10 00:14
I am observing similar issues in my code.  Perhaps of interest in diagnosing this: in my code (too large to reproduce here) I find that all the work assigned to some of the threads fails, but some threads do all their work fine.

**Comment by DrTodd13** [comment] 2022-09-11 02:58
I am unable to reproduce this on Python 3.8 and Linux with the latest Numba.

**Comment by jpn--** [comment] 2022-09-11 14:00
Looks like it's fixed (at least using the reproducer above) in 0.56 (Python 3.10, macOS).  Alas, 0.56 isn't available in the conda-forge channel yet, but I see activity on that so it looks like the main solution is patience.

**Comment by esc** [comment] 2022-09-14 10:02
I tried this today on the current `HEAD of Numba and received the following output on the reproducer:

```
0.0
0.0
0.0
```

I supposed this indicates, that this is no longer reproducible on `main`?

**Comment by esc** [comment] 2022-09-14 10:03
Thank you everyone for debugging this, I will close it now as it appears resolved. If this issue does resurface, please don't hesitate to ask to re-open this issue or open a new one, thank you again!

**Closed by esc** 2022-09-14 10:03 UTC
Labels: ParallelAccelerator, bug - incorrect behavior
