### ISSUE TITLE
"Overwrite of parallel loop index" with inlined functions and `numba.prange`

### ISSUE THREAD

**Issue by sk1p** [numba/numba#7652] opened 2021-12-13 22:08 UTC
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The following script triggers this problem:

```python
import numba

@numba.njit(inline="always")
def inner(x):
    for i in range(1):  # NOTE: loop variable is called "i"
        pass

@numba.njit(parallel=True)
def outer():
    for i in numba.prange(1024):
        inner(i)
 
outer()
```

Error message:

```
UnsupportedRewriteError: Failed in nopython mode pipeline (step: convert to parfors)
Overwrite of parallel loop index

File "../../tmp/ipykernel_1920981/4067323902.py", line 5:
<source missing, REPL/exec in use?>
```

Expected behavior: the implementation details (in this case: local/loop variable names) of functions called in a prange loop should not conflict with the outer `prange` loop variable. Please do let me know if this is expected and documented somewhere!

Changing the outer `prange` loop variable name works around this issue:

```python
import numba

@numba.njit(inline="always")
def inner(x):
    for i in range(1):
        pass

@numba.njit(parallel=True)
def outer():
    for y in numba.prange(1024):
        inner(y)
 
outer()
```

**Comment by stuartarchibald** [comment] 2021-12-14 10:56
Thanks for the report. Think this is a duplicate of https://github.com/numba/numba/issues/7380 and related https://github.com/numba/numba/issues/7365. Fixed by https://github.com/numba/numba/pull/7552 which is in the upcoming 0.55 release. This does not reproduce on mainline. Closing.

**Closed by stuartarchibald** 2021-12-14 10:56 UTC
