### ISSUE TITLE
Typo in Python demonstration on the web

### ISSUE THREAD

**Issue by marioroy** [numba/numba#8281] opened 2022-07-26 00:18 UTC
URL: [https://numba.pydata.org/](https://numba.pydata.org/)

Replace line `from numba import jit` with `from numba import njit`.

```python
from numba import njit
import random

@njit
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples
```

**Comment by stuartarchibald** [comment] 2022-07-26 09:30
Thanks for the report. That does indeed look like a typo!

**Comment by esc** [comment] 2022-07-26 11:21
duplicate of https://github.com/numba/numba.github.com/issues/8

**Comment by esc** [comment] 2022-07-26 11:22
fix is here: https://github.com/numba/numba.github.com/pull/9

**Comment by esc** [comment] 2022-07-26 11:29
Fix is merged.

**Closed by esc** 2022-07-26 11:29 UTC
Labels: bug - documentation incorrect
