### ISSUE TITLE
docs chapter cross-comparison of the most useful decorators with timing

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3286] opened 2018-09-03 13:09 UTC
## Feature request

It would be helpful to have a cross-comparison of the most useful decorators (`vectorize`, `guvectorize `& `jit`)
 somewhere in the documentation.
Based on my findings in #3206 , `guvectorize `for `parallel `/ `cuda `are the same / slower as for `cpu`.
jit is still better than guvectorize, but nowhere near theoretical speed.
I would recommend to do a single comparison as in #3206 for maybe matrix sum, and use gflops measurement of ops/time for various grids. 

This would be helpful for:
- having an overview of various decorators
- having something to compare against when deciding to use one of the decorators
- history log for numba versions to see if there are improvements or something got broken
- measuring gflops against gpu or cpu to see if theoretical peak can be reached

**Comment by stuartarchibald** [comment] 2018-09-03 15:11
Thanks for the request. To compare something criteria for comparison are needed, what do you think would be useful in this "cross-comparison"?

As to the bullet points, thanks for making these. http://numba.pydata.org/numba-benchmark/ is the result of running the suite at https://github.com/numba/numba-benchmark, is that the sort of thing you were thinking about for performance regression?

I'd be very wary of measuring the performance of a single kernel and a low number of datasets as the results typically would not apply to other kernels/datasets. There is a CPU performance guide here: http://numba.pydata.org/numba-doc/dev/user/performance-tips.html that already in part does what you suggest for the CPU target. It is written however with the large note at the top:
> A reasonably effective approach to achieving high performance code is to profile the code running with real data and use that to guide performance tuning. The information presented here is to demonstrate features, not to act as canonical guidance!

It is also worth noting that a practical peak for e.g. BLAS kernels (like those used in e.g. `np.dot`) will unlikely ever be achieved by a JIT. This is because hardware vendors put a huge amount of resources into writing, tuning and micro-optimising libraries that perform BLAS operations as they are immensely important for numerical work. As a result, some trivial JIT kernel is not going to beat it, a relatively advanced implementation may get closer, but again, is unlikely to beat it. Where Numba JIT can win on CPU is that for the `@njit(parallel=True)` ParallelAccelerator target some of the BLAS L1 and L2 kernels are written in terms of `parfors` (an internal parallel loop implementation detail).  In some circumstances because of this design decision, the loop fusion algorithms (these try and fuse parallel regions together) can fuse e.g. a BLAS L2 kernel with some surrounding compute on the kernel elements, this may reduces memory pressure through improved locality and as a result perform better, something that could not be achieved from a pre-compiled BLAS call.  As for something like `np.sum()`, the performance of this will be down the the implementation choice given that `NumPy` elects to use a pairwise sum for improved accuracy (Numba is moving to a similar-but-not-the-same method too https://github.com/numba/numba/pull/3046), otherwise it is just racing one low compute and probably memory bound kernel against another, in which case again, `BLAS` L1 functions will likely outperform them.

**Comment by cristipurdel** [comment] 2018-10-10 20:30
I will close this since it should get a doc in #3312 and more details are in https://github.com/cristipurdel/python/commit/fb56f9af829d010eac9d19f26adb5169b18b8ae5#diff-d3f78fca89d8684d9632044c41f98439

**Closed** 2018-10-10 20:30 UTC
