### ISSUE TITLE
Performance regression with string processing

### ISSUE THREAD

**Issue by apisarenco** [numba/numba#2585] opened 2017-11-02 11:59 UTC
Using numba 0.35.0 on Debian Stretch on Intel Core i7-6820HQ

The running time is around 1.1 seconds if I comment out the `@numba.jit` annotation, and 1.4 seconds if I run it like this.

On Python2 it's faster, but still slower with `@numba.jit` than without.

This is ripped from a working example (which explains the otherwise senseless code)
```python
import numba
from time import sleep, time

line = '2201709090000000009	4583xxxxx90781900		2017-09-08 22:01:31.000000	20170909	219550375664	300769342193				obfuscated.de@cpc@google@obfuscated@category_l1==888&+category_l2==5613&+category_l3==899&+category_l4==2534@(not set)	mobile	Windows Phone	8.1	Safari	537	403x671	Germany	obfuscated		/obfuscated	www.obfuscated.de		2	40	/obfuscated'

@numba.jit
def worker(line):
    for i in range(1, 1000000):
        fields = line.split("\t")

        fields[3] += " UTC"

        if fields[8]:
            fields[8] = str(10 ** 17 + int(fields[8]))

        if fields[9]:
            fields[9] = str(2 * (10 ** 17) + int(fields[9]))

ts = time()
worker(line)
te = time()
print(numba.__version__)
print('%2.4f sec' % (te-ts))
```

Is it supposed to be slower for these kinds of applications?

**Comment by TheCraftsmen** [comment] 2017-11-02 14:15
for me the problem is that numba not support string processing.
https://stackoverflow.com/questions/32056337/python-can-numba-work-with-arrays-of-strings-in-nopython-mode

**Comment by seibert** [comment] 2017-11-02 14:21
Numba is not a good choice for string processing right now.  Your code is going to compile in object mode, which has very limited optimizations at this point.  After Numba 1.0, we will look to address the string use cases better.

**Comment by TheCraftsmen** [comment] 2017-11-02 14:32
maybe can use regex for this case

**Comment by apisarenco** [comment] 2017-11-02 14:50
My expectation was that with `@jit`, it would be at least as fast as without in any scenario. I didn't expect it to be much faster, because of string manipulation. But I did expect a very slight boost from faster arithmetic.

But thanks a lot for clearing this up. I'll definitely follow related issues for any updates on this.

**Comment by stuartarchibald** [comment] 2018-04-11 15:34
Closing as I think this is resolved as "object mode uses the interpreter" and we can open specific string related tickets post 1.0. Thanks.

**Closed by stuartarchibald** 2018-04-11 15:34 UTC
