### ISSUE TITLE
prange leaky?

### ISSUE THREAD

**Issue by SumNeuron** [numba/numba#4293] opened 2019-07-09 08:56 UTC
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

# TL;DR

I have:
- `njit`-ed cached function `_heavy_comp`
- `_heavy_comp` uses `prange`
- a `jit`-ed cached `forceobj=true` wrapper function (converts python objects to input numba likes) `heavy_comp`
- a wrapper function over `heavy_comp` for use with `multiprocessing`
- a Pool from the `multiprocessing` library which `starmaps` over `heavy_comp`

The above set-up results in leakage, where all my computer's memory is eaten up. 

the code looks something like this:

```python
@njit(cache=True)
_heavy_comp(...):
    # ....
    for i in prange(...):
         # ....
    return results

@jit(forceobj=True, cache=True)
heavy_comp(...):
     # ...
     # covert to numba friendly input
     _heavy_comp(...)
    # covert from numba input back to what was passed in


def process_shard_file(file):
    output_file = output_filename_from_shard_filename(file)
    # "stream" each line of the shard file into the heavy function and the result into another file
    with open(file, 'r') as fi, open(output_file, 'w') as fo:
        heavy_comp(fi.readline()) 
        # result = fi.readline() # this does not leak
        fo.write(result)




shard_files = [...] # list of filesnames

with Pool(processes=os.cpu_count()) as pool:
    sargs = [(fname,) for fname in shard_files]
    pool.starmap(process_shard_file, sargs)
```

The above setup leaks like no other and in some instances gives different results than if run without multiprocessing.

# More context

I have pestered @stuartarchibald  and @esc  on gitter as I was exploring `numba` with an toy-ish example of handling "labeled" ranges i.e. a range (start, stop) with a type (label).

A detailed breakdown of what that looks like can be found [here](https://codereview.stackexchange.com/questions/222978/coalescing-ranges-that-have-the-same-label) in addition to a [repo](https://gitlab.com/SumNeuron/lrng/)  with all the code and jupyter notebooks to play round with.

The `heavy_comp` function eluded too above, corresponds to the function:

```python
@jit(forceobj=True, cache=True)
def relevant_labels(start, stop, reference_ranges, labels_order):
    '''
    Filter a set of reference ranges for those relevant to the range spaned by
    `[start, stop]`

    Arguments:
        start (int): start of range to test against
        stop (int): stop of range to test against
        reference_ranges (np.array): an integer array of shape (-1, 3)
            indicating the type of range as well as its start and stop
        labels_order (list): a list of the types of ranges which might appear
            in reference_ranges.

    Returns:
        relevant_ranges (np.array): an integer array of shape (-1, 3)
        indicating the type of range as well as its start and stop that all
        overlap with the passed arguments start and stop
    '''
    # ensure np as input
    np_labels = np.array(labels_order)
    np_ranges = np.array(reference_ranges)
    # convert string labels to integers
    np_ranges = _ranges_np_to_nb(np_ranges, np_labels)
    # filtered and simplified
    np_result = __coalesce(_relevant_labels(start, stop, np_ranges))
    np_result = _ranges_nb_to_np(np_result, np_labels)
    return _ranges_np_to_py(np_result)
```

the `_heavy_comp` function is accordingly:

```python
@njit(cache=True)
def _relevant_labels(start, stop, reference_ranges):
    '''
    Filter a set of reference ranges for those relevant to the range spaned by
    `[start, stop]`

    Arguments:
        start (int): start of range to test against
        stop (int): stop of range to test against
        reference_ranges (np.array): an integer array of shape (-1, 3)
            indicating the type of range as well as its start and stop

    Returns:
        relevant_ranges (np.array): an integer array of shape (-1, 3)
            indicating the type of range as well as its start and stop that all
            overlap with the passed arguments start and stop
    '''
    results = np.array([0][:0]).reshape(-1, 3)
    for i in prange(len(reference_ranges)):
        _type, start_b, stop_b = reference_ranges[i]
        if keep_q(start, stop, start_b, stop_b):
            results = np.concatenate(
                (results, np.array([[_type, start_b, stop_b]]))
            )
    return results
```

with the semantic helper function `keep_q` being:

```python
@njit(cache=True)
def keep_q(start_a, stop_a, start_b, stop_b):
    '''
    Determines whether or not to keep the second range for labeling the first
    i.e. whether or not the range indicated by [start_b, stop_b] overlaps with
    the range designated by [start_a, stop_a]

    Notes:
        assumes start < stop

    Arguments:
        start_a (int): start of range to test against
        stop_a (int): stop of range to test against
        start_b (int): start of range in question
        stop_b (int): stop of range in question

    Returns:
        (bool): whether or not the second range overlaps the first
    '''
    if stop_b < start_a: return False
    if start_b > stop_a: return False
    return True
```

That aside the code for evoking the multiprocessing is essentially what is shown above under the tl;dr. The only difference being that I have tried the following three approaches:

- using a global `reference_ranges`
- passing `reference_ranges` via `sargs` 
- loading `reference_ranges` from a file in `process_shard_file`

regardless of the approach, memory leaks and some of the results differ from running sequentially. 

That means the leakage happens somewhere in one of the above 3 functions (`relevant_labels`, `_relevant_labels`, `keep_q`). 

I also have tried adding `maxtasksperchild=1` to `Pool(...)` so that new processes would be spawned after processing one file each (and hopefully garbage collect / release unneeded memory) to no available.

Since just the returned object from `relevant_labels` (a list of lists), for what I am running is expected to be on average of length 3-5. I do not know where or why the leak is happening. Especially since streaming the input to the output file does not leak.

**Comment by stuartarchibald** [comment] 2019-07-09 09:19
Thanks for the report. Without a concrete **minimal** working reproducer this is going to be more challenging to diagnose. Few initial questions:

1. If you disable the JIT, (quickest way is with [this environment variable](http://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_DISABLE_JIT)) does the code appear to leak? (Am basically looking to see if the code is valid under pure NumPy).
2. Are you sure it is leaking opposed to just memory fragmentation?
3. Does it leak if the code is single process?
4. What is the rate of leaking?

Thanks.

**Comment by SumNeuron** [comment] 2019-07-09 09:29
I'll check `JIT` now. what exactly do you mean by point 2? I'll double check 3, but I believe it doesn't or that if it does, it is far less severe.

**Comment by stuartarchibald** [comment] 2019-07-09 09:33
Thanks. 2. See: https://en.wikipedia.org/wiki/Fragmentation_(computing)

**Comment by SumNeuron** [comment] 2019-07-09 10:01
Re no jit. Memory does increase, but no where near as fast an no where near as extreme. To give a bit more context, I am running with 40 cores and 100GB Ram and 100Gb swap. With jit after ~ 10 minutes, unless I manually terminate the process my system will crash as it has eaten through 100Gb ram and swap. Without Jit, not only does it ~appear~ to be running faster, the memory growth is from after 15 minutes is from 7GB to 7.82Gb as of right now with all cores maxed out. 

Re fragmentation. It is ubuntu so ext3 file format from reading the wiki and some googles seems like framentation is a non-issue. Also, I have used this technique (be it good or bad) a bunch with out encountering this issue (calling functions with numpy, scipy, calling out with subprocess, etc), so either I was just lucky because my system is a bit more than the average consumer (and I never ran into the issue) or it is jit related?

Will now re-enable jit and re-check single thread leakage.

Rate of leakage is described above

**Comment by stuartarchibald** [comment] 2019-07-09 10:08
Thanks for the info.

* With no jit working ok that means the code itself is likely valid, thanks for confirming.
* RE Fragmentation, am thinking about memory fragmentation, `ext3` is file system format. That your code seems ok without JIT suggests it might not be related.
* Are you oversubscribing your system? I.e. N-cores multiprocess processes all running N-cores of Numba threads under `prange`?

**Comment by SumNeuron** [comment] 2019-07-09 10:16
no, I am leaving a bit more than half free so do some other things while this runs. The estimated time to complete the call is ~4 hours with Jit, 45 minutes without. In addition I tried with and without the prange above, leakage happens regardless. Also note that `parallel`  is not set to True and from the docs:

> # Without "parallel=True" in the jit-decorator the prange statement is equivalent to range

**Comment by stuartarchibald** [comment] 2019-07-09 11:05
I'm wondering if, for some reason, Numba is having to keep on recompiling your functions, this would explain the larger run time and also explain the "leak" as Numba never forgets a function.

**Comment by SumNeuron** [comment] 2019-07-09 11:30
@stuartarchibald so I let single threaded with jit run for the last hour or so. It leaks. much slower (less threads) but already at 20Gb. That might be the case... but I `cached=True` in the `njit` / `jit` calls and I call the functions once prior to the threading to make sure they are compiled and ready to go

**Comment by stuartarchibald** [comment] 2019-07-09 11:45
ok, I've taken a look at your code. You really don't need to use `forceobj=True`, chances are it's creating slower code. All that flag does is compile some code that calls into the CPython API, which is often worse than using the CPython interpreter itself.

Do you have an actual reproducer somewhere for the problem you are seeing?

**Comment by SumNeuron** [comment] 2019-07-09 11:49
I use the `forceobj=True` to not get a warning message every time its called. 

Slower code than python or slower code than it could be with jit?

It is a bit complicated... these functions depend on something called `reference_labels` which is a large file. It can be created, but doing that is also quite involved. I am not sure if using random values would yield the same effect as having non-random values. I will try and modify the stress test notebook to see if same behavior is observed

**Comment by stuartarchibald** [comment] 2019-07-09 12:30
> Slower code than python or slower code than it could be with jit?

Slower than Python running in the interpreter. Unless you need to `@jit(forceobj=True)` a function for other reasons/have measured it and are sure it is giving benefit, don't use it!

> It is a bit complicated... these functions depend on something called reference_labels which is a large file. It can be created, but doing that is also quite involved. I am not sure if using random values would yield the same effect as having non-random values. I will try and modify the stress test notebook to see if same behavior is observed

If you can create a reproducer it will make it possible for a core developer to look at it so I'd strongly suggest spending time trying to do this if it is something you want to pursue.

**Comment by SumNeuron** [comment] 2019-07-09 12:41
I think it is worth while. If I can't use numba with python multiprocessing then that would be an issue :P 

quick follow-up is your above statment true even when `@jit(forceobj=True, cache=True)`? Eitherway then maybe an optional `(n)jit(silent=True)` would be nice so I can have no messages in logs :D

**Comment by stuartarchibald** [comment] 2020-09-10 19:59
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-09-10 19:59 UTC
Labels: needtriage
