### ISSUE TITLE
error installing numba

### ISSUE THREAD

**Issue by bloodlast69** [numba/numba#6747] opened 2021-02-23 17:40 UTC
[message (1).txt](https://github.com/numba/numba/files/6030836/message.1.txt)

**Comment by esc** [comment] 2021-02-23 21:51
@bloodlast69 thank you for submitting this traceback to the Numba issue tracker. In order to diagnose this further, please also add the command that you issued originally. Thank you.

**Comment by sklam** [comment] 2021-02-23 22:28
i'm guessing this might be part of `python setup.py install` or a `pip install numba`. The error is likely caused by missing `cmake` needed to build llvmlite.

**Comment by esc** [comment] 2021-02-24 07:49
@sklam yes, I would agree with that guess. In that case, it may be that the Windows wheels for 3.9 aren't being located (as they are not available yet) So this is perhaps another, slightly different incantation of https://numba.discourse.group/t/fixing-filenotfounderror-errno-2-no-such-file-or-directory-llvm-config/510/6 -- two suggestions come to mind as workarounds:

a) Install the release candidate wheels that have support for 3.9
b) Downgrade to Python 3.8

**Comment by esc** [comment] 2021-03-01 15:32
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by esc** 2021-03-01 15:32 UTC
Labels: more info needed, needtriage
