### ISSUE TITLE
Faulty Loop Unrolling for CUDA device functions

### ISSUE THREAD

**Issue by p3732** [numba/numba#4052] opened 2019-05-04 14:08 UTC
Hi!
I am parallelizing code with Numba CUDA support. To allow loop unrolling I have several global variables set. When I call a device function that loops over arrays of the size defined in the global variable, then the results are off. I can not exactly pin point what goes wrong, but if I manually inline the loop of the device function, everything works as expected. I think the loop unrolling on the device function must somehow ignore the arrays passed as parameters, since it also comes with a significant speedup, indicating that no reads were performed.

The device function is calculating a Reduced Euclidean distance, my code looks like this:
```
N_DIMS = 2

@cuda.jit("f4(f4[:],f4[:])", device=True,)
def rdist(x, y):
    result = 0.0
    for i in range(N_DIMS):
        tmp = x[i] - y[i]
        result += tmp * tmp

    return result
```
(Numba 43.1, Python 3.7.3, Linux)

**Comment by stuartarchibald** [comment] 2019-05-06 11:13
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.

Thanks.

**Comment by p3732** [comment] 2019-05-09 04:04
So I created a script of what seems to reproduce this, it can be found here: https://github.com/p3732/various/blob/master/numba_device_function_loop_unrolling.py

The script runs a CUDA kernel with three different options:

*using a device funciton with a fixed loop length

*using a device funciton with a dynamic loop length

*using an inlined version with a fixed loop length

Running the script gives the following output:
```
>>> from min_example import *
>>> a,b,c = test()
starting kernels with 256 threads in 8 blocks.
kernel using device function with fixed iterator completed in 0.000190
kernel using device function without fixed iterator completed in 0.000170
kernel without device function completed in 0.000175
>>> a  
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
>>> b
array([1.000000e+00, 1.000000e+00, 1.000000e+00, ..., 9.847585e+09,
       9.898260e+09, 9.949065e+09], dtype=float32)
>>> c
array([1.000000e+00, 1.000000e+00, 1.000000e+00, ..., 9.847585e+09,
       9.898260e+09, 9.949065e+09], dtype=float32)
>>> 

```
Since no distances are calculated when using a fixed loop size on a device function, I suppose that the device function is somehow precompiled and working with initially set length of zero, as changing the initial value to creates the correct output.

**Comment by stuartarchibald** [comment] 2019-05-09 08:16
Thanks for the updated script, much appreciated. The issue you are seeing is because of this: http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable and your diagnosis is correct.

Essentially, what is happening is:
```python
# This is a global, so is considered as a constant value at compile time and
# baked into the compiled code
N_DIMENSIONS = 0

<snip>

# This function is compiled as it is encountered on module import, it takes
# the value of `N_DIMENSIONS` as constant, so in this case, 0.
@cuda.jit("f4(f4[:],f4[:])", device=True)
def rdist_fixed(array_a, array_b):
    result = 0.0
    for i in range(N_DIMENSIONS):
        tmp = array_a[i] - array_b[i]
        result += tmp * tmp
    
    return result
```
could you perhaps use factory function(s) or wrappers to delay the compilation until the global is updated?

**Comment by p3732** [comment] 2019-05-09 13:32
Well, I solved it by simply inlining the function, I just assumed that compilation of device functions also happens upon JIT compilation of another function requiring them and this therefore actually being a bug. Since it is intentional, maybe adding some info to http://numba.pydata.org/numba-doc/latest/cuda/device-functions.html would be nice.

**Comment by stuartarchibald** [comment] 2019-05-09 13:44
@p3732 I've opened https://github.com/numba/numba/issues/4052 to track your suggestion, seems good and will be applicable to all `@cuda.jit*` calls, if you should feel so inclined, a pull request clarifying this item would be welcomed. I'm going to close this ticket as I think this is resolve, thanks for using Numba.

**Closed by stuartarchibald** 2019-05-09 13:44 UTC
Labels: CUDA, no action required

**Comment by p3732** [comment] 2019-05-09 14:20
Thank you!
