### ISSUE TITLE
Segfault with cfunc and Python 3.7.4

### ISSUE THREAD

**Issue by garth-wells** [numba/numba#4313] opened 2019-07-12 12:34 UTC
Upgrading from Python 3.7.3 to 3.7.4 (macOS, homebrew), with numba 0.44.1 the following segfaults:
```python
import numba
@numba.cfunc("float64(float64, float64)")
def add(x, y):
    return x + y
``` 
See 
https://gitter.im/numba/numba?at=5d282ca8d14e297762b8c09f 
https://gitter.im/numba/numba?at=5d285ecb4d7505324130a5a5
https://gitter.im/numba/numba?at=5d286499c3740260bb0aedaa

**Comment by stuartarchibald** [comment] 2019-07-12 16:26
Thanks for the report. It will take a bit of time to look into this as it requires building up 3.7.4 Python for OSX.

**Comment by stuartarchibald** [comment] 2019-07-12 19:06
I can reproduce this, one of the core devs will take a look.

**Comment by Juanlu001** [comment] 2019-07-14 10:13
Perhaps related: https://github.com/numba/numba/issues/4323

**Comment by stuartarchibald** [comment] 2019-07-15 11:15
Recompiling Numba against Python 3.7.4 seems to fix the above, I'm suspicious that the pair https://github.com/python/cpython/commit/1b85f4ec45a5d63188ee3866bd55eb29fdec7fbf and https://github.com/python/cpython/commit/8766cb74e186d3820db0a855ccd780d6d84461f7 are the cause.

**Comment by stuartarchibald** [comment] 2019-07-15 11:18
Also, as another data point, taking a Numba module built against 3.7.4 and running that with <3.7.4 also segfaults.

**Comment by stuartarchibald** [comment] 2019-07-18 10:16
Fixed by https://github.com/numba/numba/pull/4328 which is now on mainline, the upcoming 0.45.0 release will contain this fix.

**Closed** 2019-07-18 10:16 UTC
Labels: bug
