### ISSUE TITLE
Incorrect conversion by elements of the float array to string data

### ISSUE THREAD

**Issue by 1e-to** [numba/numba#5186] opened 2020-02-03 11:17 UTC
Hi, I noticed that when we try to translate a string array into a float array in the jit region, the data is received with the wrong accuracy, all with 6 decimal places.
```python
@jit
def test():
    a = np.array([4., 5.6, 1.234567890, np.nan])
    for i in range(len(a)):
        print(str(a[i]))

test()
```
Output:
> 4.000000
> 5.600000
> 1.234568
> nan

When we translate the whole array, then everything is fine
```python
@jit
def test():
    a = np.array([4., 5.6, 1.234567890, np.nan])
    print(str(a))

test()
```
Output:
> [4.         5.6        1.23456789        nan]

**Comment by esc** [comment] 2020-02-03 13:17
@1e-to thanks for submitting this to the Numba issue tracker. Unfortunately, I am unable to reproduce this. Instead, I get the following:

```
4.0
5.6
1.23456789
nan
```

And 

```
[4.         5.6        1.23456789        nan]
```

This may be something operating system or CPU architecture specific. Can you please list your Numba and llvmlite versions, your Numpy version, your Python version and place of origin (Miniconda/System Package/Compiled from Source/...) and your operating system and CPU model, thanks!

**Comment by stuartarchibald** [comment] 2021-08-17 13:28
The behaviour seems consistent on 0.54, so will close this.

Demo:
```
$ cat issue5186.py 
from numba import jit
import numpy as np

@jit
def test():
    a = np.array([4., 5.6, 1.234567890, np.nan])
    for i in range(len(a)):
        print(str(a[i]))

    print(str(a))

test()

$ python issue5186.py
<snip>
4.0
5.6
1.23456789
nan
[4.         5.6        1.23456789        nan]

$ NUMBA_DISABLE_JIT=1 python issue5186.py 
4.0
5.6
1.23456789
nan
[4.         5.6        1.23456789        nan]
```

**Closed by stuartarchibald** 2021-08-17 13:28 UTC
Labels: lowpriority, bug - incorrect behavior
