### ISSUE TITLE
Parallel =True issue with 0.56.0

### ISSUE THREAD

**Issue by untucked** [numba/numba#8362] opened 2022-08-17 17:03 UTC
## Reporting a bug

- [ x ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [  ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I have a script I run that works in version 0.55.2 but fails in the new 0.56.0 version. Here's what it looks like:
@numba.jit(nopython=True, parallel=True)
def optimizedCalc(x_array,y_array,e_array,theta,phi,const):    
    wave_final=np.zeros(phi.shape)*1j   
    S1=np.sin(theta)*np.cos(phi)
    S2=np.sin(theta)*np.sin(phi)
    output=np.zeros(phi.shape)*1j
    for ii in range(len(e_array)):
        output+=excitation[ii]*np.exp(1j*const*(x_array[ii]*S1+y_array[ii]*S2))    
    return output

If I mark parallel = False it works, it's only when it's true that it does not work.

Also if you're wondering why I use range() instead of prange() - it's because prange() does the calculation incorrectly.

**Comment by gmarkall** [comment] 2022-08-18 09:18
Can you post a complete sample of the code that reproduces the issue please? Also note that you can format code correctly by enclosing it in triple backticks (see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by stuartarchibald** [comment] 2022-09-09 16:11
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2022-09-09 16:11 UTC
Labels: needtriage, question
