### ISSUE TITLE
Heap Allocation Error at parallel execution

### ISSUE THREAD

**Issue by fingoldo** [numba/numba#3326] opened 2018-09-20 01:18 UTC
Hello Numba team, first of all thank you so much for your beautiful package! It has literally changed my way of thinking about Python to a better side.

While trying to create a counting-based argsort procedure, I found a possible bug.

As I need to traverse a list of integers and store indices of same integers into separate buckets (function BinByUniqueValues), I decided to go with a list of lists. 
_**[I had to use artificial construction  [i for i in range(0)] instead of just [] to let numba know it will be used as a list of INTEGERS, otherwise it was throwing errors. Please let me know if there is a better way of providing list's type hint to Numba...
Also, it there any better way to store lists of variable length other than a list of lists?]**_

@njit(fastmath=True)
```
def emptyListOfInts():
    return [i for i in range(0)]
```
@njit(fastmath=True)
```
def BinByUniqueValues(array,l,r,m,mask):        
    groupedIndices=[emptyListOfInts() for k in range(m)]
    if len(mask)>0:
        i=l
        while i<r:        
            ind=mask[i]
            groupedIndices[array[ind]].append(ind)
            i+=1
    else:
        i=l
        while i<r:
            groupedIndices[array[i]].append(i)
            i+=1
    return groupedIndices
```
@njit(fastmath=True)
```
def counting_argsort_list(array,maxval,mask=np.array([],np.int32)):        
    m=maxval+1    
    
    #Allocate output array
    if len(mask)>0:
        arrayLen=len(mask)
    else:
        arrayLen=len(array)        
    argsorted=np.empty(arrayLen,np.int32)    
    
    #Group indices of same values
    groupedIndices=BinByUniqueValues(array,0,arrayLen,m,mask)
    
    position = 0
    for k in range(m):
        if len(groupedIndices[k])>0:
            for index in groupedIndices[k]:
                argsorted[position] = index
                position+= 1            
    return argsorted
```

Validity check:

```
data=np.array([1, 4, 7, 2, 1, 3, 2, 1, 4, 7, 2, 1, 3, 2, 3, 2, 1]*5)
print((data[np.argsort(data)]==data[counting_argsort_list(data,7)]).all())
```
> True

I was able to prove that Numba-supported counting_argsort_list outperforms numpy's np.argsort by a factor of 2 while producing similar correct results (note that I do not care about argsorting being stable, ie returning exactly same results each time as long as resulting array will be sorted). 

```
bigdata=np.random.randint(1,100,50000)
%timeit np.argsort(bigdata)
%timeit counting_argsort_list(bigdata,100)
```

> 2.32 ms ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.49 ms ± 3.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

But clearly my binning procedure can be parallelized if we process contingent chunks of data in separate threads and then merge results in the main procedure. **[Please confirm that Numba's parallelization uses threads indeed and can access memory of main process directly and without need of duplicating it.. I am not sure...]** The best I was able to come up with was appending to a list inside of a **prange** loop:

@njit(fastmath=True,parallel=True)
```
def counting_argsort_list_threaded(array,maxval,mask=np.array([],np.int32)):        
    m=maxval+1    
    
    #Allocate output array
    if len(mask)>0:
        arrayLen=len(mask)
    else:
        arrayLen=len(array)        
    argsorted=np.empty(arrayLen,np.int32)    
    
    #Group indices of same values
    groups=[]
    effectiveSize=int(m*3)        
    if arrayLen<=effectiveSize: 
        groups.append(BinByUniqueValues(array,0,arrayLen,m,mask))
    else:
        nThreads=min(max(arrayLen//effectiveSize,1),8)            
        effectiveSize=arrayLen//nThreads
        #print("nThreads=",nThreads)
        for k in prange(nThreads):
            lBound=effectiveSize*k;rBound=effectiveSize*(k+1)
            if k==nThreads-1:
                rBound=arrayLen
            groups.append(BinByUniqueValues(array,lBound,rBound,m,mask))
    position = 0
    for k in range(m):
        for groupedIndices in groups:
            if len(groupedIndices)>0:
                if len(groupedIndices[k])>0:
                    for index in groupedIndices[k]:
                        argsorted[position] = index
                        position+= 1   
    return argsorted
```
Validation:

```
print((data[np.argsort(data)]==data[counting_argsort_list_threaded(data,7)]).all())
```
> Parallel for-loop #0 is produced from pattern '('prange', 'user')' at <ipython-input-3-84432365d5c1> (60)
After fusion, function counting_argsort_list_threaded has 1 parallel for-loop(s) #{0}.
True

As you can see, parallel execution gets activated and produces correct outcome on a toy example.
However, calling ` %timeit counting_argsort_list(bigdata,100)` fails on Windows [indicating heap allocation or freeing error](https://github.com/fingoldo/CountingArgsortParallel/blob/master/BuggyCallStack.png?raw=true)

Is my approach (ie, using lists, using prange to call a function, allocating lists inside parallel functions) officially appropriate? Note that I tried playing with config.THREADING_LAYER = 'safe', 'threadsafe' etc - to no avail. To summarize, for short arrays or short operations sometimes it works, but soon starts failing.
I have also tried running the same code with njit decorators commented out, no errors were encountered. So this is clearly an issue of parallel execution, and most likely of Numba.

My system:

> 
> Python version: ['3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]'] 
> platform: AMD64 
> system: Windows-10-10.0.14393-SP0 
> Numba version: 0.40.0rc1

For convenience, [IPython Notebook is here](https://github.com/fingoldo/CountingArgsortParallel/blob/master/Numba%20threading%20bug.ipynb)

Regards,
Anatoly

**Comment by fingoldo** [comment] 2018-09-21 09:36
Oh.. I should have searched this forum before posting. Can you recommend other type than list which would work in nopython mode and serve same purpose (be able to host  indices arrays of varying length)?

**Comment by stuartarchibald** [comment] 2018-09-21 09:41
As to your other questions:

> [I had to use artificial construction [i for i in range(0)] instead of just [] to let numba know it will be used as a list of INTEGERS, otherwise it was throwing errors. Please let me know if there is a better way of providing list's type hint to Numba...

This is probably as good a way as any under the current type inference mechanism. 

> Also, it there any better way to store lists of variable length other than a list of lists?]

Perhaps implement a sparse array like structure if all you want is a ragged array with known bounds?

>  [Please confirm that Numba's parallelization uses threads indeed and can access memory of main process directly and without need of duplicating it.. I am not sure...] 

Correct.


Also, from your code... do you need to the list-of-lists `groups` as it seems like you are interested in the argsort behaviour. If this is the case could you push the computation of `BinByUniqueValues` into the loop `for k in range(m)` this eliminating the need for a parallel list append and a list-of-lists?

**Comment by fingoldo** [comment] 2018-09-21 20:41
Thank you for the explanation Stuart.
To be sure, problem is in using list as accumulator of results inside prange, not in returning list of lists from prange-d function?
In theory, BinByUniqueValues can also return 2 arrays of integers, although of varying size.
Update:
To be able to use 2-dimensional int array as an accumulator, I modified BinByUniqueValues so that it now receives 2 arrays of length m to store offsets and length of bins and one array to store argsorted indices of the data chunk for respective thread (all 3 are allocated in the parent procedure).
Multi-threaded version now works without issues and produces correct results, but necessity to flush data from list of lists into kills performance and it's 5 times slower than single-threaded version.

Is there any roadmap on making appending to list thread-safe?

**Comment by stuartarchibald** [comment] 2018-09-24 11:09
> To be sure, problem is in using list as accumulator of results inside prange, not in returning list of lists from prange-d function?

Returning list-of-list should be ok, its just the concurrent access pattern to `list.append` that's causing issues. For example (I'm running ~v0.40.0):
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def foo(x):
    l = list()
    for i in range(x):
        tmp = list()
        for j in range(x):
            tmp.append(i + j)
        l.append(tmp)

    res = np.zeros((x,))
    for i in prange(x):
        for j in range(x):
            res[i] += l[i][j]

    return l, res

print(foo(3))
```
produces:
```
([[0, 1, 2], [1, 2, 3], [2, 3, 4]], array([3., 6., 9.]))
```
the `np.zeros()` and the `prange` loop get fused and then execute as a parallel operation.

I'd expect using an array would be ok, this seemed to do about the same/better for me:
```python
@njit
def fixup(counts, argsorted, tmp):
    idx = 0
    for i, x in enumerate(counts):
        argsorted[idx:idx + x] = tmp[i, :x]
        idx += x

@njit(parallel=True)
def foo(array, maxval):
    m = len(array) + 1
    argsorted = np.empty_like(array, np.int32)
    tmp = np.empty((maxval, m), np.int32)
    counts = np.zeros(m, np.int32)

    for i in prange(len(array)):
        bin_no = array[i]
        tmp[bin_no, counts[bin_no]] = i
        counts[bin_no] += 1

    return fixup(counts, argsorted, tmp)
```

I'm afraid I don't have a scheduled date for making list append threadsafe but will raise it at the next core developer meeting. CC @seibert as a reminder for reminding me to raise it :)

**Comment by stuartarchibald** [comment] 2018-09-26 08:59
No problem.
> Actually i was going to report some good news: while appending to a list is not thread safe (yet), seems like saving into already allocated list IS! :-)

It is safe in terms of data structure but writes can still race.

> And it's giving me expected speed increase up to 5 times (compared to np.argsort) while staying robust and correct.

Great to hear you have managed to write something that works for you.

> But now that you have published your version, I must test it )

The version I have written is threadsafe in terms of data structure but will probably have race conditions by nature of potential repeated input values in the `array` argument, this is an omission, apologies (the code also has the odd mistake as I guess you noticed :)). To fix it, the allocation of the `tmp` array (and `counts`) could be done in the parallel loop, stored based on an list indexed in `i` and then merged outside the parallel region, or just a 3D array or list-of-list-of-list could be used, first index in `i`, and then merge outside the parallel region. Think that'd work?

>  I did not know it's possible or feasible to prange whole array which can be quite large, millions of points?

The onus is on the programmer to make sure access is safe, otherwise prange works like range.

> Won't Numba be attempting to start millions threads then (or at least maxCores threads then which also can be indesirable)?

Numba has a thread pool that is the size of the number of CPU cores on the machine. Whilst there may be hundreds of items of work from `prange` only a few (corresponding to the threadpool size) will be running at a time.

>  Won't that threads be competing for the same cells in countsarray?

 Yes, noted above, this needs fixing!

> Is there any setting at all to control the number of threads Numba can spawn?

Yes, http://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_NUM_THREADS

> When I compare performance of np.argsort and njit-ted np.argsort, latter appears to be 1.5 times.. slower! Let me know if I should post that as a separate issue. Also flag parallel=True does nothing for it but it's probably a known fact.

http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html?highlight=sort#other-methods (warning at the bottom, `argsort()` uses Numba internal sort algs, which should explain it, the kwarg `kind` will also allow swapping between `quicksort` and `mergesort`, seems like this isn't documented... will fix!).

**Comment by stuartarchibald** [comment] 2018-09-26 09:10
https://github.com/numba/numba/pull/3343

**Comment by stuartarchibald** [comment] 2021-04-14 16:16
List thread-safety issue is documented here https://numba.readthedocs.io/en/latest/user/parallel.html#unsupported-operations

Closing as a duplicate of #2408

**Closed by stuartarchibald** 2021-04-14 16:16 UTC
Labels: bug, duplicate, feature_request
