### ISSUE TITLE
numba.errors.NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode) Variable '$6.2' is not defined.

### ISSUE THREAD

**Issue by PADMAG6** [numba/numba#4406] opened 2019-08-05 09:47 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment] 2019-08-05 09:52
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

**Comment by PADMAG6** [comment] 2019-08-05 10:08
sorry, I can't send the code. I am trying to convert the evtx file to json using python code. my input file size 500gb. Simple using python code (without numba, with multiprocessing) the scripts taking more than 5hours. So, I trying that whether the numba will slove my problem. while using numba i got the error 'numba.errors.NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode)
Variable '$6.2' is not defined.

**Comment by PADMAG6** [comment] 2019-08-05 10:25
here my input file name is in string formate with the full path.

**Comment by bhavanikallam** [comment] 2019-08-05 10:53
import contextlib
import mmap
import traceback
import json
import argparse
from collections import OrderedDict
from datetime import datetime
import os
import Evtx
from multiprocessing import Pool 

from Evtx.Evtx import FileHeader
from Evtx.Views import evtx_file_xml_view
import xmltodict
import sys
#import glob
import shutil
import time
from numba import jit


class EvtxToElk:

	def write_evtxtojson(input_file_path, json_string):
		w=input_file_path.split('/input')[0]
		w1=os.path.join(w,"output")
		try:
		   os.mkdir(w1)
		except OSError:
		   pass
		file_name = os.path.basename(input_file_path)
		base_file_name = os.path.splitext(file_name)[0]
		output_path=os.path.join(w1,base_file_name)
		try:
		   os.mkdir(output_path)  #this try and exception create seperate folders for each output
		except OSError:
		   pass
		  
		output_file_path = os.path.join(output_path, base_file_name+ ".json")
		with open(output_file_path, 'a') as file:
			json.dump(json_string, file)
			file.write("\n")

	def check_out_file(input_file_path):
		global base_file_name
		base_output_path = os.path.join(os.path.dirname(os.path.dirname(input_file_path)), "output")
		if not os.path.exists(base_output_path):
			os.makedirs(base_output_path)
		else:
			file_name = os.path.basename(input_file_path)
			base_file_name = os.path.splitext(file_name)
			output_json_path = os.path.join(base_output_path,base_file_name+ ".json")
			output_xml_path = os.path.join(base_output_path,base_file_name+ ".xml")
			if os.path.exists(output_json_path):
				print("Removing the file ....")
				os.remove(output_json_path)
			if os.path.exists(output_xml_path):
				os.remove(output_xml_path)


	@jit
	def evtx_to_json(filename):
		with open(filename) as infile:
			data_list = []
			with contextlib.closing(mmap.mmap(infile.fileno(), 0, access=mmap.ACCESS_READ)) as buf:
				fh = FileHeader(buf, 0x0)
				data = ""
				for xml, record in evtx_file_xml_view(fh):
					contains_event_data = False
					log_line = xmltodict.parse(xml)
					# Format the date field
					date = log_line.get("Event").get("System").get("TimeCreated").get("@SystemTime")
					if "." not in str(date):
						date = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
					else:
						date = datetime.strptime(date, "%Y-%m-%d %H:%M:%S.%f")
					log_line['@timestamp'] = str(date.isoformat())
					log_line["Event"]["System"]["TimeCreated"]["@SystemTime"] = str(date.isoformat())
	
					# Process the data field to be searchable
					data = ""
					if log_line.get("Event") is not None:
						data = log_line.get("Event")
						if log_line.get("Event").get("EventData") is not None:
							data = log_line.get("Event").get("EventData")
							if log_line.get("Event").get("EventData").get("Data") is not None:
								data = log_line.get("Event").get("EventData").get("Data")
								if isinstance(data, list):
									contains_event_data = True
									data_vals = {}
									for dataitem in data:
										if dataitem.get("@Name") is not None:
										    data_vals[str(dataitem.get("@Name"))] = str(
											str(dataitem.get("#text")))
										
									
									log_line["Event"]["EventData"]["Data"] = data_vals
								else:
									if isinstance(data, OrderedDict):
										log_line["Event"]["EventData"]["RawData"] = json.dumps(data)
									else:
										log_line["Event"]["EventData"]["RawData"] = str(data)
									del log_line["Event"]["EventData"]["Data"]
							else:
								if isinstance(data, OrderedDict):
									log_line["Event"]["RawData"] = json.dumps(data)
								else:
									log_line["Event"]["RawData"] = str(data)
								del log_line["Event"]["EventData"]
						else:
							if isinstance(data, OrderedDict):
								log_line = dict(data)
							else:
								log_line["RawData"] = str(data)
								del log_line["Event"]
					else:
						pass
					EvtxToElk.write_evtxtojson(filename, log_line)
					data_list.append(json.dumps(log_line))
		
					print("***********")
					print("Parsing Exception")
					print(traceback.print_exc())
					print("***********")
		# shutil.move(filename,dst)  
		# print(data_list)

def recursivefiles(filepath,dst):
	lis=[]
	for root, dirnames, filenames in os.walk(filepath):
		for filename in filenames:
			if filename.endswith('.evtx'):
				fname = os.path.join(root, filename)
				lis.append(fname)
	print(lis)
	for i in lis:
		EvtxToElk.evtx_to_json(i)
		shutil.move(i,dst)      

if __name__ == "__main__":
	#recursivefiles("/root/desk/data/input","/root/desk/data/rk") 
        recursivefiles("/root/Downloads/data/input/","/root/Downloads/data/archive")


While executing this above code i'm also getting same error

**Comment by stuartarchibald** [comment] 2019-08-05 10:58
Given the above I'd say that Numba probably isn't a good solution to the problem presented. Numba is numerically focussed and works very well with NumPy and numerical code. It looks like you are parsing a large file and converting from one text based format to another, you may be better off using Cython or PyPy to speed this up.

If you are new to Numba and want to see the sort of things it is good at, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment] 2019-09-11 14:53
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:53 UTC
Labels: no action required
