### ISSUE TITLE
cache missed for str arguments

### ISSUE THREAD

**Issue by auderson** [numba/numba#7575] opened 2021-11-17 08:35 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

First define a function with str type argument, and save it to `mymod.py`
```python
from numba import njit
import numpy as np


@njit(cache=True)
def foo(array, method='abc'):
    pass

```
Then run this script:
```python
from mymod import foo, np

foo(np.arange(10))

index = foo._cache._cache_file._load_index()
keys = list(index.keys())
# print(index)
print(foo._cache_misses)
print(foo._cache_hits)

print(foo.signatures)
print(foo.signatures[0] == keys[0][0])
print(foo.signatures[0][1].key)
print(keys[0][0][1].key)

```
run the script for at least 2 times to let it cached
```
Counter({(array(int64, 1d, C), omitted(default='abc')): 1})
Counter()
[(array(int64, 1d, C), omitted(default='abc'))]
False
(<class 'str'>, 140574134474608)
(<class 'str'>, 140565616270704)

Process finished with exit code 0
```
I found cache is not working here, because str argument get the hash key from its `__id__` method. And it's often the case that the 'abc' from cache and from call_signature don't share the same id. This leads to cache misses.

**Comment by gmarkall** [comment] 2021-11-17 11:21
Many thanks for the report - I can reproduce this behavior, and will bring up a discussion about it in the next triage meeting.

**Comment by stuartarchibald** [comment] 2021-11-17 12:43
Duplicate of https://github.com/numba/numba/issues/6957 ? Closed by https://github.com/numba/numba/pull/7422 ?

**Comment by stuartarchibald** [comment] 2021-11-24 12:57
Using current mainline 714c0c44ec64e01e8de52c3906e947d10421f420 which has https://github.com/numba/numba/pull/7422 merged. The above reproducer gives this on second invocation:
```
Counter()
Counter({(array(int64, 1d, C), omitted(default='abc')): 1})
[(array(int64, 1d, C), omitted(default='abc'))]
True
(<class 'str'>, 'abc')
(<class 'str'>, 'abc')
```
#7422 fixed. Closing.

**Closed by stuartarchibald** 2021-11-24 12:57 UTC
Labels: needtriage, caching
