### ISSUE TITLE
numba.errors.LoweringError with @njit(parallel=True)

### ISSUE THREAD

**Issue by tjorda01** [numba/numba#5167] opened 2020-01-29 22:24 UTC
When using the `@njit(parallel=True)` annotation, Numba reports a `numba.errors.LoweringError` with the message `... a problem has occurred in Numba's internals.`

Here is the code (also included in the attached Python file) that results in the error:
```python
import numpy as np
from matplotlib import pyplot as plt
from numba import njit, prange

@njit(parallel=True)
def ndvi_njit(img_nir:np.ndarray, img_red:np.ndarray) -> np.ndarray:
    fillvalue = 0
    out_img = np.full(img_nir.shape, fillvalue, dtype=img_nir.dtype)
    
    dims = img_nir.shape
    for y in prange(dims[0]):
        for x in prange(dims[1]):
            out_img[y, x] = (img_nir[y, x] - img_red[y, x]) / (img_nir[y, x] + img_red[y, x])
    return out_img

if __name__ == '__main__':
    tile_shape = (4096, 4096)
    array1 = np.random.default_rng().uniform(low=0.0, high=10000.0, size=tile_shape)
    array2 = np.random.default_rng().uniform(low=0.0, high=10000.0, size=tile_shape)
    
    ndvi_array = ndvi_njit(array1, array2)

    plt.imshow(ndvi_array, cmap='jet')
    plt.title("NDVI via njit")
    plt.tight_layout()
    plt.colorbar()
    plt.show()
```
It works perfectly fine when `@njit(parallel=True)` is replaced with `@njit`.

The attached Python file reproduces the error:
[numba_parallel.py.txt](https://github.com/numba/numba/files/4130899/numba_parallel.py.txt)

Here is the stacktrace:
```
> Traceback (most recent call last):
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\errors.py", line 661, in new_error_context
    yield
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 410, in lower_inst
    func(self, inst)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\parfor.py", line 283, in _lower_parfor_parallel
    parfor.races)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\parfor.py", line 1174, in call_parallel_gufunc
    sout, {})
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\parallel.py", line 219, in build_gufunc_wrapper
    py_func, cres, sin, sout, cache=cache)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\wrappers.py", line 462, in build_gufunc_wrapper
    return wrapcls(py_func, cres, sin, sout, cache).build()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\wrappers.py", line 414, in build
    self._build_wrapper(wrapperlib, wrapper_name)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\wrappers.py", line 375, in _build_wrapper
    arg_steps, i, step_offset, typ, sym, sym_dim)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\wrappers.py", line 616, in __init__
    "argument #{1}".format(typ, i + 1))
TypeError: scalar type tuple(int64 x 2) given for non scalar argument #2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\data\dev\git_gpa\src\examples\numba_parallel.py", line 44, in <module>
    ndvi_array = ndvi_njit(array1, array2)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\dispatcher.py", line 370, in _compile_for_args
    raise e
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 747, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 674, in backend_nopython_mode
    self.metadata)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\compiler.py", line 1124, in native_lowering_stage
    lower.lower()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
[1m[1mscalar type tuple(int64 x 2) given for non scalar argument #2
[1m
File "numba_parallel.py", line 33:[0m
[1mdef ndvi_njit(img_nir:np.ndarray, img_red:np.ndarray) -> np.ndarray:
    <source elided>
    dims = img_nir.shape
[1m    for y in prange(dims[0]):
[0m    [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "id=1[LoopNest(index_variable = parfor_index.23, range = (0, $32.4, 1))]{46: <ir.Block at C:\data\dev\git_gpa\src\examples\numba_parallel.py (33)>}Var(parfor_index.23, C:\data\dev\git_gpa\src\examples\numba_parallel.py (33))" at C:\data\dev\git_gpa\src\examples\numba_parallel.py (33)[0m

> -------------------------------------------------------------------------------
> This should not have happened, a problem has occurred in Numba's internals.

> Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

> If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

> Thanks in advance for your help in improving Numba!

```

**Comment by esc** [comment] 2020-01-30 10:07
@tjorda01 thanks for submitting this to the Numba issue tracker. I can reproduce locally and will label this as needing triage.

**Comment by esc** [comment] 2020-01-30 10:25
I have looked into this and my analysis goes as follows: I think something is wrong with the type-inference, and `dims[0]` isn't being inferred as an integer? If we change the example to assign the dimensions to variables before using them in the `prange` statement:

```
    a = dims[0]
    b = dims[1]
    for y in prange(a):
        for x in prange(b):
```

The code will compile and run and display the plot. Maybe you can use that as temporary workaround?

**Comment by stuartarchibald** [comment] 2020-01-30 11:01
This is another case of "gufunc's don't accept tuples", which is what this error message is for `scalar type tuple(int64 x 2) given for non scalar argument #2`, but there's a load of transforms that go on ahead of lowering the gufunc that make this non-obvious.

**Comment by esc** [comment] 2020-01-30 11:14
@stuartarchibald thanks for the analysis, I'll label it as a bug now.

**Comment by tjorda01** [comment] 2020-01-30 19:26
@esc Thanks for your analysis. Yes the temporary workaround that you suggested, of assigning a variable to each of the tuple's values before the first loop, works.

**Comment by esc** [comment] 2020-01-31 11:07
@tjorda01 thanks for reporting back and confirming this! FYI: I think we will leave this issue open, since it does appear to be a genuine bug that does need fixing.

**Comment by stuartarchibald** [comment] 2020-02-19 16:23
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:23 UTC
Labels: ParallelAccelerator, bug
