### ISSUE TITLE
Strange/wrong Error message when giving list of function pointers to jitted function

### ISSUE THREAD

**Issue by mha-py** [numba/numba#5930] opened 2020-06-29 01:13 UTC
Hi!

I had an issue with a function which didnt work, and the error message is kind of wrong... (sorry for long code, the function throwing an error is FF, other function are helper functions which are arguments in FF).
```python

@njit("float64[:](float64[:])")
def rho1_grad(x):
    return np.array([2*x[0], 2*x[1], 0., 0.])

@njit("float64[:,:](float64[:])")
def rho1_hesse(x):
    return np.array([
        [2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]
    ])

@njit("float64[:](float64[:])")
def rho2_grad(x):
    return np.array([2*(x[0]-x[2]), 2*(x[1]-x[3]), 2*(x[2]-x[0]), 2*(x[3]-x[1])])

@njit("float64[:,:](float64[:])")
def rho2_hesse(x):
    return np.array([
        [ 2.,  0., -2.,  0.],
        [ 0.,  2.,  0., -2.],
        [-2.,  0.,  2.,  0.],
        [ 0., -2.,  0.,  2.]
    ])



@jit(nopython=False)
def FF(x, v, fs_grad, fs_hesse):
    n = len(x)
    m = len(fs_grad) 
    grads = np.empty((n,m))
    vHv = np.empty(m)
    for k in range(m):
        grads[:,k] = fs_grad[k](x)
        hesse = fs_hesse[k](x)
        vHv[k] = v@hesse@v
    lmbds = -np.linalg.solve(grads.T @ grads, vHv)
    a = grads @ lmbds
    return v, a


# Throwing the error:
FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[rho1_hesse, rho2_hesse])
# Variation:
# FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[0, 0])
```
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-908887c274c2> in <module>()
     44 
     45 
---> 46 FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[rho1_hesse, rho2_hesse])
     47 #FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[0, 0])

TypeError: can't unbox heterogeneous list: type(CPUDispatcher(<function rho1_grad at 0x000000002C1F86A8>)) != type(CPUDispatcher(<function rho2_grad at 0x000000002C5F4730>))
```

So it says that the list of function `fs_grad = [rho1_grad, rho2_grad]` is making problems, ok... But the funny thing is, if i turn on the "Variation" of the call (last line in the code), which changes the argument of fs_hesse (and not fs_grad), the actual error is gone (there is an error because the subfunction was replaced by a 0 which is not callable):
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-208c3d236307> in <module>()
     45 
     46 #FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[rho1_hesse, rho2_hesse])
---> 47 FF(np.array([1.,1.,1.,0.]), np.array([1.,1.,1.,0.]), fs_grad=[rho1_grad, rho2_grad], fs_hesse=[0, 0])

TypeError: 'int' object is not callable
```

For the actual problem I have a workaround by using a function wrapper, but I thought I post this error message because it looks like a wrong error attribution

**Comment by esc** [comment] 2020-06-30 10:14
@mha-py thanks for submitting this. I have reduced this to smaller reproducer:

```python
from numba import njit


@njit
def one():
    return 1


@njit
def two():
    return 2


@njit
def test(f1):
    return f1[0]() + f1[1]()


print(test([one, two]))
```

Effectively, what this points too, is that lists of function pointers as arguments are not yet supported. A workaround in this case would be:

```python
from numba import njit


@njit
def one():
    return 1


@njit
def two():
    return 2


@njit
def test(f1, f2):
    return f1() + f2()


print(test(one, two))
```

The reason, the error goes away when using ints, is because the error with the ints is detected before the issue with the list can be detected.

**Comment by esc** [comment] 2020-06-30 10:19
I am marking this as a feature_request, although I am not even sure it can be done.

**Comment by esc** [comment] 2020-06-30 10:26
Another workaround would be to use tuples:

```
print(test(f1=(one, two), f2=(three, four)))
```

**Comment by esc** [comment] 2020-06-30 13:08
Note: I have updates the issue title to reflect it's current state as a feature request.

**Comment by mha-py** [comment] 2020-07-02 23:11
Thank you for answering! Atm I am putting both functions results into one function and stack their outputs to an array, that worked for me

**Closed** 2020-07-02 23:11 UTC
Labels: R&D, feature_request

**Comment by esc** [comment] 2020-07-03 11:40
@mha-py thanks for following up!
