### ISSUE TITLE
Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by TobyCello** [numba/numba#6269] opened 2020-09-21 21:24 UTC
Hi, genius. Thanks for helping.
I'm trying to run below code 
(pip install umap-learn first for sure)

```
import umap.umap_ as umap
reducer = umap.UMAP(random_state = 10)
reducer.fit(df)
umap_pro = reducer.transform(df) 
```

and observe error as below 

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7fb2bf31e1d0>.
Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32
File "../../../../../../usr/local/lib/python3.5/dist-packages/umap/utils.py", line 160:
def make_heap(n_points, size):
    <source elided>
    result = np.zeros(
        (np.int64(3), np.int64(n_points), np.int64(size)), dtype=np.float64
        ^
[1] During: lowering "$0.19 = call $0.2($0.15, func=$0.2, kws=[('dtype', Var($0.18, /usr/local/lib/python3.5/dist-packages/umap/utils.py (160)))], args=[Var($0.15, /usr/local/lib/python3.5/dist-packages/umap/utils.py (160))], vararg=None)" at /usr/local/lib/python3.5/dist-packages/umap/utils.py (160)
[2] During: resolving callee type: type(CPUDispatcher(<function make_heap at 0x7fb2c8436ea0>))
[3] During: typing of call at /usr/local/lib/python3.5/dist-packages/umap/nndescent.py (188)
Enable logging at debug level for details.
File "../../../../../../usr/local/lib/python3.5/dist-packages/umap/nndescent.py", line 188:
def nn_descent(
    <source elided>
    current_graph = make_heap(data.shape[0], n_neighbors)
    ^
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
​```

**Comment by esc** [comment] 2020-09-22 09:14
@TobyCello hi and thanks for reporting this. In the example  you list, it seems that `df` isn't defined? Would you be able to submit a definition for it so that I can try to reproduce this at home?

**Comment by TobyCello** [comment] 2020-09-22 13:40
Thanks very much for helping @esc 
The whole file is too big to share and we can just make a random one. It pop out the same error message 
d = {'col1': [1, 2], 'col2': [3, 4]}
dfr = pd.DataFrame(data=d)

**Comment by stuartarchibald** [comment] 2020-09-28 09:19
@TobyCello this:
```
Type of #4 arg mismatch: i1 != i32
File "../../../../../../usr/local/lib/python3.5/dist-packages/umap/utils.py", line 160:
def make_heap(n_points, size):
    <source elided>
    result = np.zeros(
        (np.int64(3), np.int64(n_points), np.int64(size)), dtype=np.float64
```
suggests that the Numba and llvmlite versions in use are incompatible. It looks like the call to `memset` is probably failing due an ABI change, the symptom of which is this message and the most common reason is having an `llvmlite` that is too old for the installed Numba version. I suggest using the latest Numba and llvmlite and then seeing if the problem is still there. For reference these are versions Numba=0.51.2 and llvmlite=0.34.0.

**Comment by stuartarchibald** [comment] 2020-10-06 22:07
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-10-06 22:07 UTC
Labels: more info needed, needtriage
