### ISSUE TITLE
candlestick2_ohlc

### ISSUE THREAD

**Issue by keita1111** [numba/numba#3865] opened 2019-03-14 12:46 UTC
NotImplementedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode DELETE_FAST at line

**Comment by stuartarchibald** [comment] 2019-03-14 12:49
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.


Without this, I'd guess that your code contains `del` which is unsupported.

**Comment by stuartarchibald** [comment] 2019-03-21 15:50
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-03-21 15:50 UTC
Labels: needtriage
