### ISSUE TITLE
python312 什么时候可以用

### ISSUE THREAD

**Issue by Franklyn1987** [numba/numba#9225] opened 2023-10-05 01:49 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment] 2023-10-05 07:44
duplicate of #9197

**Closed** 2023-10-05 07:44 UTC
Labels: duplicate
