### ISSUE TITLE
sum(list())

### ISSUE THREAD

**Issue by justinblaber** [numba/numba#6902] opened 2021-04-08 00:44 UTC
```
# export
@numba.jit(nopython=True)
def foo1():
    return max([1,2,3])

# export
@numba.jit(nopython=True)
def foo2():
    return sum([1,2,3])

foo1()
foo2()
```
`foo1()` works but `foo2()` fails. Would be nice if `sum()` was implemented.

**Comment by justinblaber** [comment] 2021-04-08 00:45
Sorry, meant to make this a feature request but don't know how to edit it...

**Comment by stuartarchibald** [comment] 2021-04-08 09:01
Thanks for the request. PR https://github.com/numba/numba/pull/6869 will fix once merged. This is a duplicate of https://github.com/numba/numba/issues/5088 so will close.

**Closed by stuartarchibald** 2021-04-08 09:01 UTC
