### ISSUE TITLE
Bug? Expected behaviour? np.sum vs explicit loop

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#4006] opened 2019-04-22 16:24 UTC
I was comparing the performance of `np.sum` and a straight loop and I was wondering if `np.sum` being slower is the expected behaviour. Maybe the result of `test2`not being able to assume that `a.shape==b.shape`?

Test code:

```python
from datetime import datetime as dt
import pandas as pd
from numba import njit
import numpy as np

@njit
def test1(a, b):
    c = 0.
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            c += a[i, j]*b[i, j]
    return c

@njit
def test2(a, b):
    return np.sum(a*b)

timing = []
for size in (20, 10), (100,48), (480,1000), (2000,1000), (5000,5000):
    for rep in range(50):
        a = np.ones(size, 'f8')
        b = np.ones(size, 'f8')
        now_ = dt.now()
        test1(a, b)
        timing.append([size, 'loop', dt.now()-now_])
        now_ = dt.now()
        test2(a, b)
        timing.append([size, 'np.sum', dt.now()-now_])
    
timing_df = pd.DataFrame(timing, columns=['size', 'version', 'time']).set_index(['size', 'version'])
(timing_df.groupby(level=['size', 'version']).sum()/50).unstack('version')
```

results:

|             | time            |                 |
|-------------|-----------------|-----------------|
| size        | loop            | np.sum          |
| (20,10)     | 00:00:00.000001 | 00:00:00.000001 |
| (100,48)    | 00:00:00.000005 | 00:00:00.000009 |
| (480,1000)  | 00:00:00.000434 | 00:00:00.000989 |
| (2000,1000) | 00:00:00.001769 | 00:00:00.004160 |
| (5000,5000) | 00:00:00.027925 | 00:00:00.114153 |

**Comment by seibert** [comment] 2019-04-22 19:41
I can reproduce these benchmarks.  After staring for a bit, I realized the problem is that the basic array expression analysis does not fuse the multiply operation and the `np.sum call`:
```
test2 (array(float64, 2d, C), array(float64, 2d, C))
--------------------------------------------------------------------------------
# File: <ipython-input-1-6883050886d3>
# --- LINE 14 --- 
# label 0

@njit

# --- LINE 15 --- 

def test2(a, b):

    # --- LINE 16 --- 
    #   a = arg(0, name=a)  :: array(float64, 2d, C)
    #   b = arg(1, name=b)  :: array(float64, 2d, C)
    #   $0.1 = global(np: <module 'numpy' from '/Users/sseibert/anaconda/envs/numba_dev/lib/python3.6/site-packages/numpy/__init__.py'>)  :: Module(<module 'numpy' from '/Users/sseibert/anaconda/envs/numba_dev/lib/python3.6/site-packages/numpy/__init__.py'>)
    #   $0.2 = getattr(value=$0.1, attr=sum)  :: Function(<function sum at 0x111fc46a8>)
    #   del $0.1
    #   $0.5 = arrayexpr(expr=(<built-in function mul>, [Var(a, <ipython-input-1-6883050886d3> (16)), Var(b, <ipython-input-1-6883050886d3> (16))]), ty=array(float64, 2d, C))  :: array(float64, 2d, C)
    #   del b
    #   del a
    #   $0.6 = call $0.2($0.5, func=$0.2, args=[Var($0.5, <ipython-input-1-6883050886d3> (16))], kws=(), vararg=None)  :: (array(float64, 2d, C),) -> float64
    #   del $0.5
    #   del $0.2
    #   $0.7 = cast(value=$0.6)  :: float64
    #   del $0.6
    #   return $0.7

    return np.sum(a*b)
```
It is hard to trace this all the way through codegen, but I think that the loop that computes `$0.5` as the result of the array expression is not fused with the loop that computes `sum()`.  The `test1()` implementation does this by construction, whereas `test2()` has to create a temporary array for storage.  I do see a call to `NRT_MemInfo_alloc_safe_aligned()` in the LLVM IR for `test2()` that does not appear in `test1()`.

ParallelAccelerator can do this fusion of reductions and array operations, but we need to do some work to enable those passes in sequential code (see #3092)

**Comment by luk-f-a** [comment] 2019-04-23 17:19
I guess my question as a user would be: would you like people to be able use numpy operations without having to worry about these things (nice but ambitious I guess) or should there be a reference to this potential issue in the performance tips section of the documentation? Something along the lines: use explicit loops for best results?

**Comment by seibert** [comment] 2019-04-23 17:22
I think the answer is both.  We have the ability to do the compiler analysis required to make this go as fast as a hand-written loop, but those compiler passes are currently stuck inside the larger parallelization compiler pass.  We need to extract them for several reasons, but I don't have an ETA about when we can tackle that.  In the mean time, a note in the FAQ would be useful.

**Comment by esc** [comment] 2020-09-25 08:51
I'll close this now, as this issue has had the 'no action required' label for over a year now. If there is interest in invigorating this discussion, please do open a new thread on the Numba discourse. Thanks!

**Closed by esc** 2020-09-25 08:51 UTC
Labels: no action required, question
