### ISSUE TITLE
connot create array types inside jitted functions

### ISSUE THREAD

**Issue by auderson** [numba/numba#7683] opened 2021-12-22 08:00 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

as title

```python
import numba
from numba.typed.typedlist import List


@numba.njit
def test_typing_1():
    ls = List.empty_list(numba.float64[:])


f8_1d_type = numba.float64[:]


@numba.njit
def test_typing_2():
    ls = List.empty_list(f8_1d_type)


test_typing_1()
test_typing_2()
```
```
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(class(float64), slice<a:b>)
 
There are 22 candidate implementations:
    - Of which 22 did not match due to:
    Overload of function 'getitem': File: <numerous>: Line N/A.
      With argument(s): '(class(float64), slice<a:b>)':
     No match.
During: typing of intrinsic-call at <ipython-input-3-88edda07e39d> (3)
During: typing of static-get-item at <ipython-input-3-88edda07e39d> (3)
File "<ipython-input-3-88edda07e39d>", line 3:
def test_typing_1():
    ls = List.empty_list(numba.float64[:])
```
a MWE would be:
```python
@numba.njit
def test_typing():
    numba.float64[:]
```

**Comment by gmarkall** [comment] 2021-12-29 14:45
Many thanks for the report. This is a bit of an annoying omission.

**Comment by gmarkall** [comment] 2021-12-29 14:46
The next triage meeting is in a couple of weeks due to the holiday period, and I've marked this for discussion then.

**Comment by stuartarchibald** [comment] 2022-01-04 14:49
Duplicate of https://github.com/numba/numba/issues/5748 ?

**Comment by stuartarchibald** [comment] 2022-01-05 15:34
There's likely a better way to do this, but this patch makes it work:
```diff
diff --git a/numba/core/typing/builtins.py b/numba/core/typing/builtins.py
index 420dd0b..460c1cc 100644
--- a/numba/core/typing/builtins.py
+++ b/numba/core/typing/builtins.py
@@ -618,6 +618,18 @@ class StaticGetItemTuple(AbstractTemplate):
             sig = signature(ret, *args)
             return sig
 
+@infer
+class StaticGetItemClass(AbstractTemplate):
+    key = "static_getitem"
+
+    def generic(self, args, kws):
+        clazz, idx = args
+        ret = None
+        if not isinstance(clazz, types.NumberClass):
+            return
+        ret = clazz.dtype[idx]
+        sig = signature(ret, *args)
+        return sig
 
 @infer
 class StaticGetItemLiteralList(AbstractTemplate):
diff --git a/numba/np/arrayobj.py b/numba/np/arrayobj.py
index a7046a4..2aaeab1 100644
--- a/numba/np/arrayobj.py
+++ b/numba/np/arrayobj.py
@@ -2544,6 +2544,11 @@ def array_record_getitem(context, builder, sig, args):
         raise NotImplementedError
     return array_record_getattr(context, builder, sig.args[0], args[0], index)
 
+@lower_builtin('static_getitem', types.NumberClass, types.SliceType)
+def static_getitem_number_clazz(context, builder, sig, args):
+    arr = np.ones(1, dtype=as_dtype(sig.return_type.dtype))
+    res = context.make_constant_array(builder, sig.return_type, arr)
+    return impl_ret_untracked(context, builder, sig.return_type, res)
 
 @lower_getattr_generic(types.Record)
 def record_getattr(context, builder, typ, value, attr):
```
this lets this compile:
```python
from numba.typed.typedlist import List
from numba import njit, float64
import numpy as np

@njit
def test_typing_1():
    ls = List.empty_list(float64[:])
    ls.append(np.ones(2))
    ls.append(np.ones(4))
    return ls

print(test_typing_1())
```
which produces:
```
[[1. 1.], [1. 1. 1. 1.]]
```

**Closed** 2023-03-27 22:41 UTC
Labels: feature_request
