### ISSUE TITLE
TypingError: Failed in nopython mode pipeline (step: nopython frontend) non-precise type pyobject

### ISSUE THREAD

**Issue by aEgoist** [numba/numba#5401] opened 2020-03-19 04:47 UTC
I'm trying to rewrite a bar aggregation function, which loads np.recarray comes from df.to_record(),
keeps some initial values, change them, append a record when cond comes to Ture. This is how my pythonic solution is:

```
def bar_aggregator(dr, i_):
    """open_time(np.datetime64),open,high,low,close,volume"""
    x = []
    o, h, l, c, v = list(dr[0])[1:6]
    pc, i = c, 0
    for r in dr:
        if i>=i_:
            x.append([r['open_time'], o, h, l, c, v])
            o, h, l, c, v = list(r)[1:6]
            pc = r['close']
            i = 0
        o = r['open']
        if r['high'] > h:
            h = r['high']
        if r['low'] < l:
            l = r['low']
        c = r['close']
        v += r['volume']
        i += 1
        tr = np.max((h - l, abs(pc - h), abs(pc - l)))
    return x
```

@njit it directly turns out that list()/ dr.tolist() is not supported. So I changed to np.array form, like this, where dr is now an ndarray:
```
@njit
def bar_aggregator(dr, i_):
    """open_time(np.datetime64),open,high,low,close,volume"""
    # x =[]
    _x =[np.float64(x) for x in range(0)] 
    x = [_x for _x in range(0)]
    o, h, l, c, v = dr[0,1:6]
    pc, i = c, 0
    for j in np.arange(dr.shape[0]):
        r=dr[j]
        if i >= i_:
            x.append([r[0], o, h, l, c, v])
            o, h, l, c, v = r[0,1:6]
            pc = r[4]
            i = 0
        o = r[1]
        if r[2] > h:
            h = r[2]
        if r[3] < l:
            l = r[3]
        c = r[4]
        v += r[5]
        i += 1
    return x
```
Tried different implementation of x, different assignments for ohlcv, any attemption fails with TypingError. Where was I missing?

**Comment by stuartarchibald** [comment] 2020-03-19 11:29
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

**Comment by stuartarchibald** [comment] 2020-03-30 11:24
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-03-30 11:24 UTC
Labels: needtriage
