### ISSUE TITLE
Reshape fails when nested in loop

### ISSUE THREAD

**Issue by geauzzaife** [numba/numba#3931] opened 2019-04-02 21:09 UTC
Assume a function that takes an array and reshape it back and forth:
```python
import numpy as np
from numba import jit

arr = np.zeros((3,2), dtype=np.float64)

@jit(nopython=True)
def my_fun(arr):
         
    arr = arr.reshape(3*2)
    # do something on arr
    arr = arr.reshape(3,2)
    
    return(arr)

my_fun(arr)
```

This works correctly. However, it fails if I put the two `reshape` instructions into a loop:
```python
import numpy as np
from numba import jit

arr = np.zeros((3,2), dtype=np.float64)

@jit(nopython=True)
def my_fun(arr):
    
    for i in range(1):  
        arr = arr.reshape(3*2)
        arr = arr.reshape(3,2)
    
    return(arr)

my_fun(arr)
```
The error:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'arr', defined at <ipython-input-25-256f07e6f45d> (9)
```
Is that a bug, or a behavior of `reshape` that I don't understand within numba?

I'm using numba `0.43.1`.

**Comment by luk-f-a** [comment] 2019-04-06 11:10
@geauzzaife, I don't know if your original code should work (ie if there's a bug), but in case you want a quick solution, this avoids that problem

```python
@njit
def my_fun(arr):
    
    for i in range(1):  
        arr1 = arr.reshape(3*2)
        arr2 = arr.reshape(3,2)
    
    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```

**Comment by esc** [comment] 2019-04-06 17:34
@geauzzaife thank you very much for your report. We appreciate you using Numba and taking the time to report any snags.

In this case, apparently the problem is that you are trying to change the dimensionality of the array inside the loop. When you call the function, you are passing a `2d` array as argument as evidenced by the error message: `array(float64, 2d, C)`. You are then using `arr.reshape(3*2)` in an attempt to change `arr` to a `1d` array as seen again in the error as: `array(float64, 1d, C)`. For example, you will see the same error if you try:

```python
@njit
def my_fun(arr):    
    for i in range(1):  
        arr = arr.reshape(3*2)        
    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```
Which essentially demonstrates that it has nothing to do with using reshape twice, for example the following will work fine:

```python
@njit
def my_fun(arr):    
    for i in range(1):  
        arr = arr.reshape(2,3)
        arr = arr.reshape(3,2)
    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```

A possible workaround to get something you might be able to treat like a 1d array, might be:

```python
@njit
def my_fun(arr):    
    for i in range(1):  
        arr = arr.reshape(1,6)        
    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```

But this depends on what it is you are trying to accomplish. 

The solution that luk-f-a  proposed, creates two new variables `arr1` and `arr2` so can be anything you like, which is why that works.

I am still looking into why dimensionality of numpy array can not be changed inside the loop, but I hope the above already provides some additional insights.

**Comment by stuartarchibald** [comment] 2019-04-08 11:53
@esc this sample:
```python
import numpy as np
from numba import njit

@njit
def my_fun(arr):
    for i in range(1):
        arr = arr.reshape(3 * 2)
    return arr

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```
reports:
```
Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'arr', defined at issue3931.py (6)
```
because type inference assumes the loop executes (which in this case it does) and so at the function terminator `arr` could be 1D or 2D, hence unification problem.

The original problem is a bug in type inference. I've removed the loop and made the code look like this:
```python
import numpy as np
from numba import njit


@njit
def my_fun(arr):
    # add = 2d
    if arr.ravel()[0] > 0:
        arr = arr.reshape(3 * 2) # arr in = 2D, arr out = 1D
        arr = arr.reshape((3, 2)) # arr in = 1D, arr out = 2D

    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```
This is the IR and first round of propagation:
```
--------------------------------IR DUMP: my_fun---------------------------------
label 0:
    arr = arg(0, name=arr)                   ['arr']
    $0.2 = getattr(value=arr, attr=ravel)    ['$0.2', 'arr']
    $0.3 = call $0.2(func=$0.2, args=[], kws=(), vararg=None) ['$0.2', '$0.3']
    del $0.2                                 []
    $const0.4 = const(int, 0)                ['$const0.4']
    $0.5 = static_getitem(value=$0.3, index=0, index_var=$const0.4) ['$0.3', '$0.5', '$const0.4']
    del $const0.4                            []
    del $0.3                                 []
    $const0.6 = const(int, 0)                ['$const0.6']
    $0.7 = $0.5 > $const0.6                  ['$0.5', '$0.7', '$const0.6']
    del $const0.6                            []
    del $0.5                                 []
    branch $0.7, 16, 36                      ['$0.7']
label 16:
    del $0.7                                 []
    $16.2 = getattr(value=arr, attr=reshape) ['$16.2', 'arr']
    $const16.3 = const(int, 6)               ['$const16.3']
    $16.4 = call $16.2($const16.3, func=$16.2, args=[Var($const16.3, issue3931.py (9))], kws=(), vararg=None) ['$16.2', '$16.4', '$const16.3']
    del $const16.3                           []
    del $16.2                                []
    arr = $16.4                              ['$16.4', 'arr']
    del $16.4                                []
    $16.6 = getattr(value=arr, attr=reshape) ['$16.6', 'arr']
    $const16.7 = const(tuple, (3, 2))        ['$const16.7']
    $16.8 = call $16.6($const16.7, func=$16.6, args=[Var($const16.7, issue3931.py (10))], kws=(), vararg=None) ['$16.6', '$16.8', '$const16.7']
    del $const16.7                           []
    del $16.6                                []
    arr = $16.8                              ['$16.8', 'arr']
    del $16.8                                []
    jump 36                                  []
label 36:
    del $0.7                                 []
    $36.2 = cast(value=arr)                  ['$36.2', 'arr']
    del arr                                  []
    return $36.2                             ['$36.2']
-----------------------------------propagate------------------------------------
---- type variables ----
[$0.2 := BoundFunction(array.ravel for array(float64, 2d, C)),
 $0.3 := array(float64, 1d, C),
 $0.5 := float64,
 $0.7 := bool,
 $16.2 := BoundFunction(array.reshape for array(float64, 2d, C)),
 $16.4 := array(float64, 1d, C),
 $16.6 := BoundFunction(array.reshape for array(float64, 2d, C)),
 $16.8 := array(float64, 2d, C),
 $36.2 := array(float64, 2d, C),
 $const0.4 := Literal[int](0),
 $const0.6 := Literal[int](0),
 $const16.3 := Literal[int](6),
 $const16.7 := tuple(int64 x 2),
 arg.arr := array(float64, 2d, C),
 arr := array(float64, 2d, C)]
-----------------------------------propagate------------------------------------
```
In the type variables `$16.6` is referring to a `.reshape` on a 2d array which is by virtue of the IR `1d`. I expect the use of a temporary variable would sort this out:
```python
import numpy as np
from numba import njit


@njit
def my_fun(arr):
    # add = 2d
    if arr.ravel()[0] > 0:
        tmp = arr.reshape(3 * 2) # arr in = 2D, arr out = 1D
        arr = tmp.reshape((3, 2)) # arr in = 1D, arr out = 2D

    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```

**Comment by geauzzaife** [comment] 2019-04-08 15:26
Thanks a lot for these explanations. The solution of using a temporary variable:
```python
import numpy as np
from numba import njit

@njit
def my_fun(arr):
    
    for i in range(1):  
        tmp = arr.reshape(3*2)
        # do something on arr
        arr = tmp.reshape(3,2)
    
    return(arr)

arr = np.zeros((3,2), dtype=np.float64)
my_fun(arr)
```
works fine for what I want do. 
Thanks you!

**Comment by esc** [comment] 2019-04-18 15:58
@stuartarchibald can we close this?

**Comment by stuartarchibald** [comment] 2019-04-18 20:20
@esc would rather keep it open, tagged with SSA to see if that yields anything to help.

**Closed** 2020-03-24 16:27 UTC
Labels: SSA, bug
