### ISSUE TITLE
Can I recursively call a function?

### ISSUE THREAD

**Issue by jsphon** [numba/numba#991] opened 2015-02-11 22:33 UTC
Hello,

I am trying to jit the quicksort algo from:

    http://rosettacode.org/wiki/Sorting_algorithms/Quicksort#Python

My code is

    def quicksort(array):
        _quicksort(array, 0, len(array) - 1)

    @nb.autojit( nopython=True )
    def _quicksort(array, start, stop):
        if stop - start > 0:
            pivot, left, right = array[start], start, stop
            while left <= right:
                while array[left] < pivot:
                    left += 1
                while array[right] > pivot:
                    right -= 1
                if left <= right:
                    array[left], array[right] = array[right], array[left]
                    left += 1
                    right -= 1
            _quicksort(array, start, right)
            _quicksort(array, left, stop)
Unfortunately, when I run it with:

    x = np.random.randn( 1e3 )
    quicksort( x )

I get this error:

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-144-1921e998abf9> in <module>()
      1 x = np.random.randn( 1e3 )
----> 2 quicksort( x )

<ipython-input-143-372c7e5392ce> in quicksort(array)
      1 def quicksort(array):
----> 2     _quicksort(array, 0, len(array) - 1)
      3 
      4 @nb.autojit( nopython=True )
      5 def _quicksort(array, start, stop):

C:\Anaconda\envs\py33\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    155         assert not kws
    156         sig = tuple([self.typeof_pyval(a) for a in args])
--> 157         return self.compile(sig)
    158 
    159     def inspect_types(self, file=None):

C:\Anaconda\envs\py33\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    275                                           self.py_func,
    276                                           args=args, return_type=return_type,
--> 277                                           flags=flags, locals=self.locals)
    278 
    279             # Check typing error if object mode is used

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    545     pipeline = Pipeline(typingctx, targetctx, library,
    546                         args, return_type, flags, locals)
--> 547     return pipeline.compile_extra(func)
    548 
    549 

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    291                 raise e
    292 
--> 293         return self.compile_bytecode(bc, func_attr=self.func_attr)
    294 
    295     def compile_bytecode(self, bc, lifted=(),

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in compile_bytecode(self, bc, lifted, func_attr)
    299         self.lifted = lifted
    300         self.func_attr = func_attr
--> 301         return self._compile_bytecode()
    302 
    303     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    532 
    533         pm.finalize()
--> 534         return pm.run(self.status)
    535 
    536 

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in run(self, status)
    189                     # No more fallback pipelines?
    190                     if is_final_pipeline:
--> 191                         raise patched_exception
    192                     # Go to next fallback pipeline
    193                     else:

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in run(self, status)
    181             for stage, stage_name in self.pipeline_stages[pipeline_name]:
    182                 try:
--> 183                     res = stage()
    184                 except _EarlyPipelineCompletion as e:
    185                     return e.result

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in stage_nopython_frontend(self)
    387                 self.args,
    388                 self.return_type,
--> 389                 self.locals)
    390 
    391         with self.fallback_context('Function "%s" has invalid return type'

C:\Anaconda\envs\py33\lib\site-packages\numba\compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    663 
    664     infer.build_constrain()
--> 665     infer.propagate()
    666     typemap, restype, calltypes = infer.unify()
    667 

C:\Anaconda\envs\py33\lib\site-packages\numba\typeinfer.py in propagate(self)
    388                 print("propagate".center(80, '-'))
    389             oldtoken = newtoken
--> 390             self.constrains.propagate(self.context, self.typevars)
    391             newtoken = self.get_state_token()
    392             if config.DEBUG:

C:\Anaconda\envs\py33\lib\site-packages\numba\typeinfer.py in propagate(self, context, typevars)
    116                 msg = "Internal error at {con}:\n{err}"
    117                 raise TypingError(msg.format(con=constrain, err=e),
--> 118                                   loc=constrain.loc)
    119 
    120 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstrain object at 0x0000000007C89B00>:

File "<ipython-input-143-372c7e5392ce>", line 17

The error looks different from the more common nopython=True error where one of the variables is a Python object. And I can't work out which of the variables is a Python object.

What is wrong?

**Comment by seibert** [comment] 2015-02-11 23:14
Numba does not currently support recursion in nopython mode.  We eventually want to support it, but it is not a high priority because the only use cases we've seen are people implementing the Fibonacci sequence or quicksort exclusively for benchmarking purposes.  :)

Closing this as a duplicate of #507.  If you have situations where recursion would be helpful, please add them to that issue.  Thanks!

**Closed by seibert** 2015-02-11 23:14 UTC

**Comment by jsphon** [comment] 2015-02-12 21:36
Thanks for the response.

I actually wanted it so that I could use it in nopython mode, but have found an iterative (rather than recursive) algorithm and will so use that instead.

Speaking of priorities, how high is the priority to allow creation of numpy ndarrays in nopython mode?

**Comment by seibert** [comment] 2015-02-12 21:43
Memory allocation is high priority, but reasonably high difficulty (in terms of making sure the solution works in all cases and doesn't have unintended consequences) so we have been waiting to make sure we have a robust solution before plowing ahead.

Loop-lifting in object mode handles a lot of the use cases where memory allocation in nopython mode would normally be required, so that has helped people work around the limitation.

**Comment by seibert** [comment] 2015-05-18 16:42
As a side note on this PR: We have now implemented creation of numpy ndarrays in nopython mode.  Memory allocation will be in the Numba release at the end of May.

**Comment by jsphon** [comment] 2015-05-18 17:19
Nice. I look forward to trying it!
