### ISSUE TITLE
ImportError: Numba could not be imported

### ISSUE THREAD

**Issue by Elelwani** [numba/numba#5286] opened 2020-02-20 11:08 UTC
I'm currently experiencing an issue when trying to import numba. 

```
_The original error was: '/scratch/verification/anaconda/lib/python2.7/site-packages/numba/typeconv/_typeconv.so: undefined symbol: _Znam, version GLIBCXX_3.4'
[FAIL] app_wrapper plot_ver_profiles.py --plot_dir $PLOT_DIR --start $START_DATE --end $END_DATE --model_names $MODEL_NAMES --ards $ARDS --expids $EXP_IDS --case_studies $CASE_STUDIES --areas $AREA_CODE --vts $VALIDITY_TIMES --diurnal_vts $VALIDITY_TIMES --fcrs $LEAD_TIMES --diurnal_fcrs $LEAD_TIMES --levels $LEVELS --web_dir $WEB_DIR # return-code=1
2020-02-20T10:42:29Z CRITICAL - failed/EXIT_
```
Thank you inadvance

**Comment by esc** [comment] 2020-02-20 13:32
@Elelwani thanks for submitting this to the Numba issue tracker. Would it be possible to share the code you are trying to run, the operating system you are on and how you obtained Numba? That would potentially allow us to reproduce the error in order to diagnose and debug it.

**Comment by stuartarchibald** [comment] 2020-02-20 14:09
Think this root cause here is a `libstdc++` which is too old/missing.

**Comment by stuartarchibald** [comment] 2020-03-02 18:26
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-03-02 18:26 UTC
Labels: more info needed
