### ISSUE TITLE
Unification failure with NaT

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5105] opened 2020-01-19 10:19 UTC
Numba 0.48dev0 has problems unifying `NaT` (i.e. `datetime[]`) with `datetime[D]`:

```python
import numpy as np
from numba import njit

a = np.datetime64("NaT")
b = np.datetime64("2000-01-01")


@njit
def test_NaT_typing(a, b):
    if a > b:
        return a
    else:
        return b


test_NaT_typing(a, b)
```

Results in:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Can't unify return type from the following types: datetime64[D], datetime64[]
Return of: IR name '$12return_value.1', type 'datetime64[]', location: 
File "", line 11:
def test_NaT_typing(a, b):
    
    if a > b:
        return a
        ^
Return of: IR name '$16return_value.1', type 'datetime64[D]', location: 
File "", line 13:
def test_NaT_typing(a, b):
    
    else:
        return b
        ^
```

**Comment by ARF1** [comment] 2020-01-19 10:26
BTW: If one further specifies the type of `NaT` everything works as expected. I.e. with:

```
a = np.datetime64("NaT", "D")
```

**Comment by esc** [comment] 2020-01-20 08:39
@ARF1 thanks for reporting this, I can reproduce the behavior on current master (40fb2d06859a782db9463ac6d7eae8405eb6a81d).

**Comment by stuartarchibald** [comment] 2020-01-20 09:47
I'm not sure how this can be resolved? Is there a `dtype` that would safely hold `<M8` and `<M8[D]` ?
```
In [8]: np.find_common_type([], ['<M8','<M8[D]'])                                                                               
Out[8]: dtype('O')
```
suggests not?

**Comment by stuartarchibald** [comment] 2020-02-06 09:37
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-02-06 09:37 UTC
Labels: needtriage
