### ISSUE TITLE
Disabled JIT compilation and direct construction of typed list yields empty list

### ISSUE THREAD

**Issue by polakowo** [numba/numba#6651] opened 2021-01-19 20:33 UTC
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import os
os.environ['NUMBA_DISABLE_JIT'] = '1'

from numba.typed import List
List([1, 2, 3])
```

```
[]
```

While adding items via `append` still works.

**Comment by esc** [comment] 2021-01-19 21:31
@polakowo thank you for reporting this. I believe this is a duplicate of https://github.com/numba/numba/issues/6001

**Closed** 2021-01-25 15:25 UTC
Labels: bug - incorrect behavior, duplicate
