### ISSUE TITLE
llvmlite 0.31 breaks numba 0.46

### ISSUE THREAD

**Issue by leezu** [numba/numba#5035] opened 2020-01-06 10:27 UTC
llvmlite 0.31 seems incompatible with numba 0.46.

If this is "intended" (ie no forward compatibility), please pin numba's dependency to llvmlite to a supported version.

Background:

```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32
```
https://ci.mxnet.io/blue/rest/organizations/jenkins/pipelines/GluonNLP-py3-master-gpu-integration/branches/master/runs/212/nodes/84/steps/128/log/?start=0

In this case, GluonNLP CI server installed numba 0.46, which depends on the most recent llvmlite release. But as the new llvmlite release is incompatible, tests started failing.

**Comment by stuartarchibald** [comment] 2020-01-06 10:42
Thanks for the report. I guess this is an issue with `pip install numba==0.46` as there's no pin here https://github.com/numba/numba/blob/release0.46/requirements.txt#L2, conda is correct https://github.com/numba/numba/blob/release0.46/buildscripts/condarecipe.local/meta.yaml#L34

**Comment by stuartarchibald** [comment] 2020-01-06 10:46
Reproducer + output:
```
$ pip install numba==0.46
Collecting numba==0.46
<snip>
Successfully installed llvmlite-0.31.0 numba-0.46.0 numpy-1.18.0
```

the memset/memcpy signature change for 0.30->0.31 is the cause of the lowering error above, Numba adopted the backwards incompatible change in 0.31 for version 0.47.0.

**Comment by sklam** [comment] 2020-01-06 13:58
maybe we should always llvmlite to the minor version number.

**Comment by seibert** [comment] 2020-01-06 13:59
yeah, we need to make the `setup.py` reflect the same version pinning as the conda package does.

**Comment by Juanlu001** [comment] 2020-01-07 09:05
We're observing similar failures with llvmlite 0.31 and numba 0.45.

**Comment by YuehChuan** [comment] 2020-01-18 01:54
3Q ORZ!

**Comment by esc** [comment] 2020-01-20 08:34
For anyone else stumbling upon this. As of Numba 0.47.0 the minimum version of llvmlite is 0.31.0. This requirement had not been enforced in 0.47.0 so you may need to update your dependencies manually for this version. A fix for 0.48.0 has been merged however and should resolve the issue:

https://github.com/numba/numba/pull/5046

**Comment by fizwit** [comment] 2020-04-14 07:05
OSError: Could not load shared object file: libllvmlite.so

environment: Ubuntu 18.04 numba 0.47.0  llvmlite 0.31.0

Explictly add libllvmlite.so to LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/llvmlite/binding:$LD_LIBRARY_PATH
/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/llvmlite/binding/libllvmlite.so

```
 numba --version
Traceback (most recent call last):
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/bin/numba", line 5, in <module>
    from numba.numba_entry import main
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/numba/__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/numba/config.py", line 18, in <module>
    import llvmlite.binding as ll
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/app/software/numba/0.47.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/llvmlite/binding/ffi.py", line 154, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so
```

**Comment by esc** [comment] 2020-04-14 07:49
@fizwit thanks for reporting this! Could you perhaps try to update `llvmlite` and check if the issue persists? Thanks!

**Comment by fizwit** [comment] 2020-04-14 08:04
llvmlite version 0.31.0 is latest version

John Dey
john@fuzzdog.com

**Comment by esc** [comment] 2020-04-14 08:17
@fizwit ah, in that case please try a development version of llvmlite from:

```
conda install  -c numba/label/dev llvmlite
```

**Comment by esc** [comment] 2020-04-14 11:59
@fizwit on second thought, the error you are seeing may not, in fact, be related to a version or dependency mismatch. Numba 0.47.0 and llvmlite 0.31.0 are almost certainly compatible with one another.

**Comment by fizwit** [comment] 2020-04-15 18:22
The issue was resolved - my environment overwrote the path to a different LLVM. So critical that LLVM used to build numba stays in the LD_LIBRARY_PATH.

**Comment by louisabraham** [comment] 2020-04-20 22:22
I have the same problem:
- LLVM version 9.0.1
- llvmlite==0.31.0.dev0+1.g7c14ef0 (because of the above)
- numba==0.49.0

**Comment by esc** [comment] 2020-04-21 06:48
@louisabraham thank you for asking about this on the llvmlite issue tracker. Can you try to use llvmlite 0.32.0 and check if the problem persists?

**Comment by louisabraham** [comment] 2020-04-21 07:32
I installed llvm7, llvmlite 0.32.0 and the issue disappeared 😀

**Comment by esc** [comment] 2020-04-21 08:38
@louisabraham thanks for reporting back and thanks for using Numba!

**Comment by louisabraham** [comment] 2020-04-21 08:44
Come on, I don't deserve that much. Thank **you** for making numba!

**Comment by esc** [comment] 2020-12-02 10:26
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by esc** 2020-12-02 10:26 UTC
Labels: bug, wheels
