### ISSUE TITLE
Catch incompatible cudart arch

### ISSUE THREAD

**Issue by uchytilc** [numba/numba#6893] opened 2021-04-05 20:24 UTC
On line 420 of nvvm.py, within get_arch_option(), after find_closest_arch() is called there should probably be a check if arch is empty and if it is an error should be raised related to cudart not being found/supported with the current driver version. Currently if find_closest_arch() returns an empty tuple an error will be raised when trying to construct the "compute_" string as arch doesn't contain 2 entries.

**Comment by guilhermeleobas** [comment] 2021-04-06 00:14
Hi @uchytilc, thanks for reporting this. I could not reproduce the bug you described. There is a check in [`find_closest_arch`](https://github.com/numba/numba/blob/3497fb205e15cb2123ef18053ca2206c0393794b/numba/cuda/cudadrv/nvvm.py#L388-L393) that verifies if the output of [`get_supported_ccs`](https://github.com/numba/numba/blob/3497fb205e15cb2123ef18053ca2206c0393794b/numba/cuda/cudadrv/nvvm.py#L340) is an empty tuple or not. If the tuple is empty, an error ought to be raised.

Can you post the output of `get_supported_ccs`? In my system I have the following:

```python
>>> from numba.cuda.cudadrv import nvvm
>>> nvvm.get_supported_ccs()
((3, 5), (5, 0), (5, 2), (5, 3), (6, 0), (6, 1), (6, 2), (7, 0), (7, 2), (7, 5), (8, 0))
```

**Comment by uchytilc** [comment] 2021-04-06 00:33
No problem. I actually can't reproduce it either lol. It was a student I was working with that encountered the error and they have since updated their driver version and everything works fine. They had a GTX 1050 and a very out of date driver. I believe what was happening was get_supported_ccs() was entering the cudart_version_major == 0 conditional (this is a guess as there were no warnings raised and the other conditionals that contain empty tuples all have warnings) so when Numba tried to generate "compute_%d%d" python exited with a ValueError related to the string manipulation as arch was an empty tuple. I know that arch was an empty as I had them print it out but I didn't have the foresight to ask them what their value for cudart_version_major was so I can't tell you which conditional they actually hit within get_supported_ccs(). I only bring up the bug as it was a little more involved trying to figure out what the problem was because they were getting a ValueError as opposed to a driver/runtime related error.

**Comment by uchytilc** [comment] 2021-04-06 00:47
![error](https://user-images.githubusercontent.com/55564119/113643339-ef2c7280-9636-11eb-9ac1-fe0ab0ba43e0.jpg)

**Comment by gmarkall** [comment] 2021-04-06 17:20
@uchytilc What version of Numba was this? The stack trace shows line 345 of nvvm.py, which suggests some difference between the current version of Numba and the version that the student was using. This may have already been fixed by https://github.com/numba/numba/pull/6227.

**Comment by uchytilc** [comment] 2021-04-06 18:03
@gmarkall I just took a look at the fix you posted and the code for find_closest_arch() is definitely different than what I was looking at so you are definitely correct. Go ahead and mark this as resolved. I didn't even think to check the version as the student downloaded Anaconda two days ago and I kind of just assumed it would come with the latest version of everything.

**Closed** 2021-04-06 20:44 UTC
Labels: CUDA, more info needed
