### ISSUE TITLE
Numerical differences when using numpy.linalg.norm

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#4701] opened 2019-10-13 15:14 UTC
Python 3.7.4, numba 0.46.0, numpy 1.17.1 installed with pip in pyenv.

```
$ pip list | grep num
numba              0.46.0
numpy              1.17.1
$ ipython
Python 3.7.4 (default, Aug 26 2019, 17:42:54) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from numba import njit                                                                                                          

In [2]: from numpy.linalg import norm                                                                                                   

In [3]: import numpy as np                                                                                                              

In [4]: @njit 
   ...: def test_norm(v): 
   ...:     return norm(v) 
   ...:                                                                                                                                 

In [5]: @njit 
   ...: def norm2(vec): 
   ...:     vec = 1.0 * vec  # Cast to float 
   ...:     return np.sqrt(vec.dot(vec)) 
   ...:                                                                                                                                 

In [6]: @njit 
   ...: def test_norm2(v): 
   ...:     return norm2(v) 
   ...:                                                                                                                                 

In [7]: v = np.array([-3.457, 6.618, 2.533])                                                                                            

In [8]: print(test_norm(v))                                                                                                             
7.884469671449057

In [9]: print(test_norm.py_func(v))                                                                                                     
7.8844696714490565

In [10]: print(test_norm2(v))                                                                                                           
7.8844696714490565

In [11]: print(test_norm2.py_func(v))                                                                                                   
7.8844696714490565
```

The only call that gives a different result is `test_norm(v)`, which uses `numpy.linalg.norm` and has `njit` enabled.

**Comment by stuartarchibald** [comment] 2019-10-14 09:49
Thanks for the report.

1. The error noted is a difference near the last position of the floating point value, I cannot reproduce what you see locally.
2. Numba uses BLAS to perform 2-norm operations on 1d arrays https://github.com/numba/numba/blob/bdd8e312a24c5b76ee4fe480abe553cff349aa51/numba/targets/linalg.py#L2131-L2163 whereas NumPy does not: https://github.com/numpy/numpy/blob/e2c75d94ee1ea4dd0eb0ab0a394f984c968d9237/numpy/linalg/linalg.py#L2475-L2477

I'm not sure that this is of huge concern? Using BigNum-like precision gives the value as `7.884469671449056947028....` so the Numba-BLAS value closest to this I think? Is this causing a problem for some application?

**Comment by Juanlu001** [comment] 2019-10-14 10:16
Thanks a lot for your quick response @stuartarchibald! Surprisingly this ended up making my image-comparison tests fail, but that can perhaps be attributed to the fact that matplotlib is very sensitive maybe? :)

I mostly wanted to reach out to know whether the reasons for the discrepancy where understood or not. Also the NumPy source code explains why my `norm2` functions gets the same results.

**Comment by stuartarchibald** [comment] 2019-10-14 10:34
hmmm, I worry a bit about things that are that sensitive to last-place values in floating point, any chance you could point to the code in question please?

I wonder if Numba should replicate exactly what NumPy is doing? I suspect their choice may be informed by performance concerns?

**Comment by Juanlu001** [comment] 2019-10-14 11:30
I observed small differences in numerical results:

https://github.com/poliastro/poliastro/pull/771/commits/7c6b541808a0e97f4bf65ec57457655d64bd237b

Which ended up translating to small but noticeable differences in some plots

https://github.com/poliastro/poliastro/pull/771/commits/9a06bb2b4fdb457436a0694d210704e32f02b9ac#diff-55775dd62aedd99ab27569cf49904dd8

(you can use the "onion skin" feature to see the differences)

The culprit ended up being this single line:

https://github.com/poliastro/poliastro/blob/c3f4f5f3f0e72aa6e852ee61f9051c3407ad42d3/src/poliastro/core/elements.py#L349

**Comment by stuartarchibald** [comment] 2019-10-14 11:47
> I observed small differences in numerical results:
> 
> [poliastro/poliastro@7c6b541](https://github.com/poliastro/poliastro/commit/7c6b541808a0e97f4bf65ec57457655d64bd237b)
> 
> Which ended up translating to small but noticeable differences in some plots
> 
> [poliastro/poliastro@9a06bb2#diff-55775dd62aedd99ab27569cf49904dd8](https://github.com/poliastro/poliastro/commit/9a06bb2b4fdb457436a0694d210704e32f02b9ac#diff-55775dd62aedd99ab27569cf49904dd8)
> 
> (you can use the "onion skin" feature to see the differences)
> 
> The culprit ended up being this single line:
> 
> https://github.com/poliastro/poliastro/blob/c3f4f5f3f0e72aa6e852ee61f9051c3407ad42d3/src/poliastro/core/elements.py#L349

I see, thanks, perhaps we should "fix" this then so Numba mirrors NumPy.


Does replacing
```
e_ce = norm(r) * (norm(v) ** 2) / k - 1
```
with
```
e_ce = norm(r) * dot(v, v) / k - 1
```
help? I'm not sure of the scale of the values present, but the latter may be more stable and likely quicker.

**Comment by Juanlu001** [comment] 2019-11-04 10:11
Sorry for the delay! Your suggestion was spot on and it fixed my small annoyance. Thanks!

**Comment by esc** [comment] 2019-11-04 12:29
@Juanlu001 thanks for reporting back on this. I will close this issue now as I believe it is resolved. If this isn't the case, please don't hesitate to re-open it.

**Closed by esc** 2019-11-04 12:29 UTC
Labels: needtriage
