### ISSUE TITLE
Weird multiprocessing block importing Numba function

### ISSUE THREAD

**Issue by Peque** [numba/numba#2431] opened 2017-06-26 17:03 UTC
# Environment

- GNU/Linux (Fedora 25). Can't reproduce with Windows it seems.
- Conda environment.
- Python 3.6.1.
- Numba 0.33.0 (np112py36_0).

# Initial setup (works fine)

Two files `main.py` and `numbamodule.py`:

## `main.py`

Which spawns 2 processes to run the `execute_numba` function.

    import time
    from importlib import import_module
    from multiprocessing import Process
    
    
    def execute_numba(name):
        # Import the function
        importfunction = 'numbamodule.numba_function'
        module = import_module(importfunction.split('.')[0])
        function = getattr(module, importfunction.split('.')[-1])
        while True:
            print(str(name) + ' - executing Numba function...')
            # Execute the function
            function(10)
            time.sleep(0.1)
    
    
    if __name__ == '__main__':
        processes = [Process(target=execute_numba, args=(i,)) for i in range(2)]
        [p.start() for p in processes]
        time.sleep(1)
        [p.terminate() for p in processes]

## `numbamodule.py`

Which defines a simple function `numba_function`:

    import numba
    
    
    @numba.jit()
    def numba_function(x):
        total = 0
        for i in range(x):
            total += i
        return total

I can run the `main.py` script and see both processes printing:

    $ python main.py
    0 - executing Numba function...
    1 - executing Numba function...
    0 - executing Numba function...
    1 - executing Numba function...
    0 - executing Numba function...
    1 - executing Numba function...
    [...]

# Breaking it

The way I break it is a bit weird, but this is what I stumbled upon when trying to minimize a reproducible test case. Please, tell me if you can reproduce the same behavior too.

In `main.py` I just add one of the proposed (bellow) imports after the last `Process` import (i.e.: uncomment one line and try):

    import time
    from importlib import import_module
    from multiprocessing import Process
    
    #
    # Adding one of the import lines bellow results in a block...
    # (you may need to install the packages first in the virtual environment)
    #
    #import matplotlib
    #import Pyro4
    #import scipy
    #import dill
    
    
    def execute_numba(name):
    # [...]

Then one process may block at `execute_numba` function (in particular at the `import_module()` call):

    $ python main.py 
    1 - executing Numba function...
    1 - executing Numba function...
    1 - executing Numba function...
    1 - executing Numba function...
    1 - executing Numba function...
    [...]

For me, `matplotlib` and `Pyro4` imports "work" best (AKA: a process, if not both, gets blocked). I cannot even get the block a 100% of the runs... :-/

Note that I am simply adding a single import line, not actually using the package. Some other external imports result in a block as well, but I have found the ones proposed above "work" best (block the most).

# What is happening?

First of all, can you reproduce the same behavior? (specially interested in non-virtualized GNU/Linux machines)

I don't know how to debug this or why could this be happening. Any ideas?

The fact that adding one random `import xxx` triggers the block scares me and makes little sense to me. Could this be dependent on timing/delays and that is why some imports break it and some others do not?

# Notes

- As you can see there is no traceback, the process just blocks.
- If I remove the `import numba` and `@numba.jit` from `numbamodule.py`, then it will always work, so I guess this has something to do with Numba?

**Comment by Peque** [comment] 2017-06-27 08:29
Tried with Numba 0.25.0 and 0.22.1 (with Python 3.5) and I can reproduce the same behavior (just to make sure it is not only the most recent Numba version).

**Comment by Peque** [comment] 2017-07-10 07:59
@sklam Friendly "ping". :innocent:

I am willing to help debugging to discover what the issue is in case it is a Numba bug (and if you give me some instructions/hints on how to proceed with a case like this). However, I will lose access to the machine where I found this problem in a couple of days, and I may not be able to reproduce it easily anymore, so I may not be able to help in the future. :wink:

**Comment by stuartarchibald** [comment] 2017-07-11 14:22
I can replicate (sometimes) so no hurry with regards to hardware access. Would guess it is pycache related, `importlib.invalidate_caches()` might help? The `(sometimes)` is also suspicious in that there's likely some sort of race going on.

**Comment by Peque** [comment] 2017-07-11 14:59
@stuartarchibald That is actually a relief. :blush: I even [posted the question in SO](https://stackoverflow.com/questions/44764520/weird-multiprocessing-block-importing-numba-function) but nobody seemed to be able to replicate the same. Thought I was alone with this one. :stuck_out_tongue_winking_eye: 

Yeah, for me it is the same, not always. Sometimes one process gets stuck, sometimes two, sometimes none...

Executing `importlib.invalidate_caches()` just before the `import_module()` call (where it gets stuck) does not help. I get the same results.

**Comment by Peque** [comment] 2017-07-11 15:10
Executing `importlib.invalidate_caches()` before the external `matplotlib`/`dill`/`Pyro4` imports helps if there is only `matplotlib` import, for example. But does not help if I import `Pyro4` instead. So I guess it does not really fix the issue (it only alters the result a bit randomly as well, just like almost any other subtle change you may do in the code).

**Comment by Peque** [comment] 2017-08-04 11:46
Any updates on this matter? :innocent:

**Comment by Peque** [comment] 2017-10-02 16:02
@stuartarchibald Any news about this? Is there any way I could help?

**Comment by stuartarchibald** [comment] 2018-01-09 12:36
I've looked at this a bit more and think it's actually a threading issue. The reason it looks like one processed is blocked is because it has in actual fact segfaulted, (add `print(processes)` just before the `p.terminate()` list comp and you'll see:
```python
[<Process(Process-1, started)>, <Process(Process-2, stopped[SIGSEGV])>]
```

Tracing the segfault gives this:
```bash
Current thread 0x00007fd1024f1740 (most recent call first):
  File "<path>/lib/python3.6/site-packages/llvmlite/binding/executionengine.py", line 95 in finalize_object
  File "<path>/lib/python3.6/site-packages/numba/targets/codegen.py", line 546 in wrapper
  File "<path>/lib/python3.6/site-packages/numba/targets/codegen.py", line 483 in _finalize_specific
  File "<path>/lib/python3.6/site-packages/numba/llvmthreadsafe.py", line 30 in wrapped
  File "<path>/lib/python3.6/site-packages/numba/targets/codegen.py", line 253 in _finalize_final_module
  File "<path>/lib/python3.6/site-packages/numba/llvmthreadsafe.py", line 30 in wrapped
  File "<path>/lib/python3.6/site-packages/numba/targets/codegen.py", line 237 in finalize
  File "<path>/lib/python3.6/site-packages/numba/llvmthreadsafe.py", line 30 in wrapped
  File "<path>/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 202 in compile_nrt_functions
  File "<path>/lib/python3.6/site-packages/numba/runtime/nrt.py", line 37 in initialize
  File "<path>/lib/python3.6/site-packages/numba/llvmthreadsafe.py", line 30 in wrapped
  File "<path>/lib/python3.6/site-packages/numba/targets/cpu.py", line 48 in init
  File "<path>/lib/python3.6/site-packages/numba/targets/base.py", line 245 in __init__
  File "<path>/lib/python3.6/site-packages/numba/targets/registry.py", line 38 in _toplevel_target_context
  File "<path>/lib/python3.6/site-packages/numba/utils.py", line 283 in __get__
  File "<path>/lib/python3.6/site-packages/numba/targets/registry.py", line 54 in target_context
  File "<path>/lib/python3.6/site-packages/numba/dispatcher.py", line 467 in __init__
  File "<path>/lib/python3.6/site-packages/numba/decorators.py", line 191 in wrapper
  File "<path>/numba/issue2431/numbamodule.py", line 3 in <module>
```

Segfaults appearing from this location are almost always due to threads performing concurrent operations inside LLVM, or some issue to do with installing functions during Numba's initialisation sequence. Much work has been done on threadsafety of late, however, even with applying https://github.com/numba/numba/pull/2627 and https://github.com/numba/llvmlite/pull/318 the segfault still appears. This made me think about threading models.

As noted here: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
there are a number of ways to start processes from `multiprocessing` and the default method is platform dependent. On Windows `spawn` is the default and very little is inherited from the parent process. On Linux `fork` is the default and the child inherits (almost) all from the parent process. So by default, your program will be using `fork(3)` to create new processes.

Updating your `main.py` to use `spawn` or `forkserver` as follows does not have the segfault problem:
```python
import time
from importlib import import_module
from multiprocessing import Process
import multiprocessing  as mp # <---- Add this line here

import scipy

def execute_numba(name):
    # Import the function
    importfunction = 'numbamodule.numba_function'
    module = import_module(importfunction.split('.')[0])
    function = getattr(module, importfunction.split('.')[-1])
    while True:
        print(str(name) + ' - executing Numba function...')
        # Execute the function
        function(10)
        time.sleep(0.1)


if __name__ == '__main__':
    mp.set_start_method('spawn') # <---- Add this line here
    processes = [Process(target=execute_numba, args=("Process %s"%i,)) for i in range(2)]
    [p.start() for p in processes]
    time.sleep(1)
    print(processes)
    [p.terminate() for p in processes]
```

The outstanding question is why?! I'm suspicious that the Numba init sequence is not `fork(3)` safe and the import of some other module happens to either trigger something in cpython (or the standard modules) that makes the issue appear *or* it is simply timing attack like behaviour, or indeed something else. I briefly investigated the notion of it being a timing delay that happened to hit an unlucky sequence but couldn't make it occur, which makes me think it is in fact something else. Investigation will continue, but I thought I'd post this so you could try the fix.

**Comment by Peque** [comment] 2018-01-10 08:40
@stuartarchibald Thanks for taking the time to have a look at it. I will probably be able to try the `spawn` workaround next week and I will report back. :+1:

**Comment by Peque** [comment] 2018-01-30 16:48
@stuartarchibald Tried the workaround and it seems I can no longer reproduce the error when using "forkserver" or "spawn" methods with the toy example I provided.

Unfortunately I cannot reproduce the error with the default "fork" method upstream (i.e.: in the real code project). So changing it to "forkserver" or "spawn" might or might not be solving the problem. Will update here if I am able to make it fail upstream again with the default "fork" method.

**Comment by stuartarchibald** [comment] 2018-02-07 09:48
@Peque I also cannot reproduce any more with `llvmlite==0.22.0dev0` and `numba==0.37.0.dev`, perhaps there was some issue in my debugging env that meant the threadsafety patches didn't go in quite right. I think my analysis of the issue is still largely valid and it ties in with numerous other issues of the same ilk that I've debugged and fixed. I would still like to check a couple of things surrounding `fork(3)` behaviour but think for now we can probably say that this is fixed until demonstrated otherwise. Thanks for your help.

**Comment by stuartarchibald** [comment] 2018-04-10 16:51
Closing this as I don't think the reproducer reproduces any more! If this becomes an issue again please reopen. Thanks.

**Closed by stuartarchibald** 2018-04-10 16:51 UTC
Labels: bug
