### ISSUE TITLE
jitclass throws NameError: name shadowing

### ISSUE THREAD

**Issue by priyatharsan** [numba/numba#4073] opened 2019-05-09 14:48 UTC
Example:

```
spec = OrderedDict()
for k in list("xy"):
    spec[k] = double
@jitclass(spec)
class CustomArray(np.ndarray):
    def __new__(cls, x, y):
        # Create ndarray and cast to our class type
        obj = np.asarray(np.hstack([x, y])).view(cls)

        # Return the object
        return obj

    @classmethod
    def from_array(cls, array):
        return cls(array[0], array[1])

    @property
    def x(self):
        return self[0]

    @x.setter
    def x(self, value):
        self[0] = value

    @property
    def y(self):
        return self[1]

    @y.setter
    def y(self, value):
        self[1] = value
```

Throws an error like this:

```
  File "....\numba\jitclass\decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "....\numba\jitclass\base.py", line 193, in register_class_type
    raise NameError("name shadowing: {0}".format(', '.join(shadowed)))
NameError: name shadowing: x, y
```

Not sure if the implementation was correct. Appreciate the help. Thanks!

**Comment by stuartarchibald** [comment] 2019-05-09 15:29
Thanks for the report. I think the problem is that 'x' and 'y' are specified in the specification as class members, and then there also exists methods (`@property`) named 'x' and 'y', hence one shadowing the other. Further, inheriting from `np.ndarray` is not going to work as it will have a huge number of unsupported and uncompilable class members. I'm also fairly sure that the use of `__new__` is unlikely to work. In general jitclass is fairly experimental and only relatively simple things work, perhaps have a look at the documentation https://numba.pydata.org/numba-doc/dev/user/jitclass.html and there's some examples here:

* Simple: https://github.com/numba/numba/blob/000fbcfba7dd4a0d646217e2426dcd7743a78833/examples/jitclass.py
* Stack: https://github.com/numba/numba/blob/000fbcfba7dd4a0d646217e2426dcd7743a78833/examples/stack.py
* Binary Tree: https://github.com/numba/numba/blob/000fbcfba7dd4a0d646217e2426dcd7743a78833/examples/binarytree.py
* Linked List: https://github.com/numba/numba/blob/000fbcfba7dd4a0d646217e2426dcd7743a78833/examples/linkedlist.py

**Comment by seibert** [comment] 2019-05-09 17:40
It took me a moment to figure out how this code would even work in the Python interpreter, but then I realized that in this idiom, the first implementation (the getter) of `x` is replaced by the second (the setter), but the decorator retains the reference to the first implementation so it doesn't disappear.

But yes, to Stuart's point, the current jitclass implementation is very limited and won't work for this kind of code.

**Comment by stuartarchibald** [comment] 2019-09-11 14:51
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:51 UTC
Labels: jitclass, no action required
