### ISSUE TITLE
Try/except blocks not working in numba

### ISSUE THREAD

**Issue by asaakius** [numba/numba#764] opened 2014-09-14 07:07 UTC
I just found out that try/except blocks don't work because SETUP_EXCEPT is not in the list of supported opcodes:
http://expertsoverflow.com/questions/25821596/raising-an-exception-while-using-numba
Could this be added please?

**Comment by seibert** [comment] 2017-11-02 14:01
Closing this as duplicate of #2097

**Closed by seibert** 2017-11-02 14:01 UTC
