### ISSUE TITLE
numba.jit does not work with static class methods?

### ISSUE THREAD

**Issue by JonasRSV** [numba/numba#5409] opened 2020-03-23 16:45 UTC
I am using numba 0.48 in python3.6 on ubuntu 18.04.3

The following code can be used to reproduce the error. When i run with the hmm function everything works. But when i run with A.p directly I get the stack trace provided after the code. 

```python

import numba


class A:

    @staticmethod
    @numba.jit(nopython=True)
    def p(x):
        return x



hmm = A.p

@numba.jit(nopython=True)
def l(x):
    return A.p(x) + 2 * A.p(x)
    #return hmm(x) + 2 * hmm(x)


print(l(3))

```bash
Traceback (most recent call last):
  File "error.py", line 21, in <module>
    print(l(3))
  File "/home/jonas/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/jonas/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/jonas/.local/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'A': cannot determine Numba type of <class 'type'>

File "error.py", line 17:
def l(x):
    return A.p(x) + 2 * A.p(x)
    ^
```

**Comment by sklam** [comment] 2020-03-23 21:08
The problem is that numba doesn't know what `A` is. Numba cannot work with arbitrary class instances.

**Comment by JonasRSV** [comment] 2020-03-24 06:54
But it works when I first assign that class function to a generic variable? It would make sense to me if hmm did not work.. but now hmm works and A.p does not.. Why does one work but not the other?

**Comment by sklam** [comment] 2020-03-31 14:56
```python

In [1]: 
import numba


class A:

    @staticmethod
    @numba.jit(nopython=True)
    def p(x):
        return x



hmm = A.p
 
In [2]: type(hmm)
Out[2]: numba.core.registry.CPUDispatcher

In [3]: type(A)
Out[3]: type
```

Type of `hmm` is a numba `CPUDispatcher` type. So, Numba can understand.

Type of `A` is a `type` (the type of a Python class). Numba does not know what it is. Because attribute access can have arbitrary side-effect (i.e. `@property` can have side-effect), Numba cannot check the attribute `A.p` at compile-time. If `A` is however a Python module, Numba can read the `.p` to check it's type to learn that it is a `CPUDispatcher` knowing that it would not cause side-effect at compile-time.

**Comment by stuartarchibald** [comment] 2020-09-11 18:36
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-09-11 18:36 UTC
Labels: no action required, question

**Comment by victor-zou** [comment] 2024-11-08 07:06
> ```python
> In [1]: 
> import numba
> 
> 
> class A:
> 
>     @staticmethod
>     @numba.jit(nopython=True)
>     def p(x):
>         return x
> 
> 
> 
> hmm = A.p
>  
> In [2]: type(hmm)
> Out[2]: numba.core.registry.CPUDispatcher
> 
> In [3]: type(A)
> Out[3]: type
> ```
> 
> Type of `hmm` is a numba `CPUDispatcher` type. So, Numba can understand.
> 
> Type of `A` is a `type` (the type of a Python class). Numba does not know what it is. Because attribute access can have arbitrary side-effect (i.e. `@property` can have side-effect), Numba cannot check the attribute `A.p` at compile-time. If `A` is however a Python module, Numba can read the `.p` to check it's type to learn that it is a `CPUDispatcher` knowing that it would not cause side-effect at compile-time.

@sklam On this issue, I think there is a very simple solution: just interpret `A.p` as `A.__dict__["p"]` :)
So the resolution order for `A.p` can goes as follows:
1. current numba resolution order, like check whether A is a module or other supported types.
2. check if "p" in `A.__dict__`, and whether `A.__dict__["p"]` is of types that are supported by numba.
3. if "p" is not in `A.__dict__`, no longer further checks dicts from `__class__`/`__mro__`..., just raise an AttributeError.

Although it introduces some restriction, this solution has covered most of the use case of class static methods/const variables. It even supports compile-time const python-object attribute. No side effect of `.p` will be triggered.

The restriction it introduces (restricted is better than not :)
1. `@property`, or other behaviors involving magic methods like `__get__`, `__getattribute__`, `__getattr__`
2. `A` from pyd/so
3. `A.p` from its (base) classes. As the user may change his code resolving to them directly.  
 (which also means that `@property` or other magics involving `__get__`, `__getattr__`, `__getattribute__` are not supported).
