### ISSUE TITLE
Type inference for integers is odd

### ISSUE THREAD

**Issue by the-kiel** [numba/numba#5365] opened 2020-03-09 12:22 UTC
Hi there, 

I ran into a problem when I wanted to use a lookup-array to check if I've seen some integer previously, and be faster than using a set or something like that. 
The basic idea is to have a iteration counter. If some item with index idx has been seen, I memorize this by setting array[idx] to the current iteration counter. 

In this test, I call checkAndSet twice: The first call will set array[idx] = iteration, and in the second call, the function should always return "False". 

```python
@jit(nopython=True)
def checkAndSet(array, idx, value): 
    if array[idx] == value: 
        return False
    array[idx] = value
    return True

@jit(nopython=True)
def runTest(n, lookupArray):
    iteration = 0
    for i in range(n): 
        for j in range(n): 
            iteration += 1
            if not checkAndSet(lookupArray, 0, iteration): 
                continue
            if not checkAndSet(lookupArray, 0, iteration): 
                continue
            return True, iteration
                
    return False, iteration

def main(): 
    arr = np.full((1), 0, dtype=np.int32)
    n = 100000
    
    ret = runTest(n, arr)
    print(ret)
    print(arr)
```

However, it seems like the types used by numba are a little inconsistent. If I use a 32bit-integer and an overflow occurs, and I can pass the second "checkAndSet"-call: 

```
(True, 2147483648)
[-2147483648]
```

My understanding would be that the type should be chosen in a way such that after setting a[i]=x, a[i]==x should evaluate to "True".

**Comment by esc** [comment] 2020-03-09 12:33
@the-kiel thanks very much for submitting this to the Numba issue tracker. I have marked it for triage now. For future reference, if you could make the reproducer a self-contained program, that would be much appreciated since it will allow us to reproduce and debug your issue quicker since we don't have to manually fix up the imports, thanks!

**Comment by esc** [comment] 2020-03-09 13:12
@the-kiel I am not sure what you are asking about here. I reduced your example to the following reproducer.:

```
from numba import jit
import numpy as np

@jit(nopython=True)
def checkAndSet(array, idx, value):
    print(idx, value)
    if array[idx] == value:
        return False
    array[idx] = value
    return True

@jit(nopython=True)
def runTest(lookupArray):
    for iteration in range(2147483648-3, 2147483648+3):
        if not checkAndSet(lookupArray, 0, iteration):
            continue
        if not checkAndSet(lookupArray, 0, iteration):
            continue
        return True, iteration

    return False, iteration

def main():
    arr = np.zeros((1, ), dtype=np.int32)
    ret = runTest(arr)
    print(ret)
    print(arr)

main()
```

When I run this, it prints:

```
0 2147483645
0 2147483645
0 2147483646
0 2147483646
0 2147483647
0 2147483647
0 2147483648
0 2147483648
(True, 2147483648)
[-2147483648]
```

Maybe you could explain a little more why you are expecting? Do you want Numba to raise an exception when the overflow occurs? As for the type, from what I can tell the caller is in control of the type of `arr`. Would you expect Numba to change that type to accommodate the large value?

**Comment by the-kiel** [comment] 2020-03-09 13:55
@esc: Thanks for the quick response. 
I "inlined" the function calls, maybe this makes it more clear: 
``` python
@jit(nopython=True)
def runTest(n, lookupArray):
    iteration = 0
    for i in range(n): 
        for j in range(n): 
            iteration += 1
            if lookupArray[0] == iteration: 
                continue
            else: 
                lookupArray[0] = iteration
            # okay, let's do this again: 
            if lookupArray[0] == iteration: 
                continue
            else: 
                lookupArray[0] = iteration
            # This line should be unreachable: 
            return True, iteration
                
    return False, iteration
```
So I set 
``` python
lookupArray[0]=iteration
```
, and afterwards the condition 
``` python
lookupArray[0] == iteration
```
is evaluated as false. This is a behaviour which I would expect for floating point variables, but not for integers.

**Comment by esc** [comment] 2020-03-09 14:54
@the-kiel thank you for reporting back. I'm still not sure as to what you want Numba to do in this case? You setup an `int32` Numpy array and then attempt to assign a value which is too large to an index and this doesn't work properly. There isn't much that Numba can do about this. For example, if you remove the `jit` decorator and run this as pure python and Numpy it will yield the same behavior. Does that make sense?

**Comment by the-kiel** [comment] 2020-03-10 08:43
@esc My expectation was that numba would chose a type for the "iteration"-variable which would either give a warning, as you get it when you compile without the decorator, or yield a behaviour which respects the "read-over-write-axiom". 

I played with it a lot before I posted it here, so maybe the example I chose was not the very best one. If you consider the following case, where variables are initialized as np.int32 explicitly, the behaviour is actually different with and without the decorator: 

``` python
@jit(nopython=True)
def runTest(n, iteration, lookupArray):   
    for i in range(n): 
        iteration += 1
        lookupArray[0] = iteration
        # okay, let's do this again: 
        if lookupArray[0] == iteration: 
            continue

        return True, iteration

    return False, iteration
    
    
def main(): 
    arr = np.zeros((1, ),  dtype=np.int32)
    n = 100
    startingValue = np.int32(2**31-10)
    ret = runTest(n, startingValue, arr)
    print(ret)
    print(arr)

```

Output without the decorator: 
```
testOverflow2.py:21: RuntimeWarning: overflow encountered in long_scalars
  iteration += 1
(False, -2147483558)
[-2147483558]
```
but if the decorator is used, the output changes to 
```
(True, 2147483648)
[-2147483648]
```

That's why I was a little confused.

**Comment by esc** [comment] 2020-03-10 10:20
@the-kiel interesting, I don't seem to get that warning when I comment out the decorator and run without it.

**Comment by stuartarchibald** [comment] 2020-03-10 10:21
@the-kiel are you using windows?

**Comment by the-kiel** [comment] 2020-03-10 15:18
@esc : Do you also get different results with and without the decorator? 

@stuartarchibald : Yes, it's Windows 7 actually.

**Comment by esc** [comment] 2020-03-10 15:23
@the-kiel no, I get the same results, regardless of decorator.

**Comment by the-kiel** [comment] 2020-03-11 07:44
@esc : That's interesting, I just tried it on a linux machine, and there I also get the same output with and without the decorator.

**Comment by esc** [comment] 2020-03-11 07:50
@the-kiel interesting indeed. BTW, is there a specific use-case that you are blocked on or something you are trying to achieve that we might be able to provide a workaround for?

**Comment by the-kiel** [comment] 2020-03-12 17:26
@esc: No, I'm not blocked, I can get the information I need in another way. I mainly wanted to share this with you.

**Comment by stuartarchibald** [comment] 2020-03-12 17:51
I would guess this is down to Numba's typing system and that compiled versions are doing upcasting to `int64` and avoiding the overflow. e.g. `iteration += 1`, if `iteration` is an `int32` doing `operator.iadd` on it will yield an `int64` type as it's "safest", further the literal `1` will likely be an `int64` again compounding to the conversion to `int64`.  Unix and the compiled versions behave in the same way, but windows uncompiled version is different, which suggests there's something special about that. Would suggest looking at the output of `runTest.inspect_types()` and comparing that to the types found in the uncompiled version.

**Comment by stuartarchibald** [comment] 2020-09-02 10:27
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-02 10:27 UTC
Labels: more info needed
