### ISSUE TITLE
Parallel is two times slower in LIF neuron model

### ISSUE THREAD

**Issue by chaoming0625** [numba/numba#6796] opened 2021-03-05 03:46 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I run a LIF neuron model with numba. 

```python
import numpy as np
import time
import numba as nb

V_rest = 0.
V_reset = -5.
V_th = 20.
R = 1.
tau = 10.
t_refractory = 5.
noise = 0.
dt = 0.02

num_neu = 10000
times = np.arange(0, 10000, dt)
```

When I use a single thread to run the neuron group, 

```python

@nb.njit
def lif2_1(ST, _t):
    for i in range(ST.shape[1]):
        t_last_spike = ST[0, i]
        I_ext = ST[1, i]
        V = ST[2, i]

        V += (- (V - V_rest) + R * I_ext) / tau * dt 
        if V >= V_th:
            V = V_reset
            spike = 1
            t_last_spike = _t
        else:
            spike = 0.

        ST[0, i] = t_last_spike
        ST[2, i] = V
        ST[3, i] = spike

np_state1 = np.zeros((4, num_neu))
np_state1[0] = -1e4
np_state1[1] = 20
np_state1[2] = 0

t0 = time.time()
for t in times:
    lif2_1(np_state1, t)
print(f'Used {time.time() - t0} s')

```
It used 7.67903 s to run this script. 

However, when I use multiple threads (i.e., parallel mode) to run the model. 

```python

@nb.njit(parallel=True, nogil=True)
def lif2_2(ST, _t):
    for i in nb.prange(ST.shape[1]):
        t_last_spike = ST[0, i]
        I_ext = ST[1, i]
        V = ST[2, i]

        V += (- (V - V_rest) + R * I_ext) / tau * dt 
        if V >= V_th:
            V = V_reset
            spike = 1
            t_last_spike = _t
        else:
            t_last_spike = t_last_spike
            spike = 0.
            V = V

        ST[0, i] = t_last_spike
        ST[2, i] = V
        ST[3, i] = spike

np_state2 = np.zeros((4, num_neu))
np_state2[0] = -1e4
np_state2[1] = 20
np_state2[2] = 0

t0 = time.time()
for t in times:
    lif2_2(np_state2, t)
print(f'Used {time.time() - t0} s')

```

It got 14.027968 s. 

That is to say, in this case, the parallel mode is two times slower than the single thread. Why? I am very confused. I hope to got the developer's rely. Thanks!

**Comment by esc** [comment] 2021-03-05 10:15
@chaoming0625 thank you for reporting this on the Numba issue tracker. I tried to reproduce, but it seems like `dt` is not defined. I tried anyway with a value of 0.1 and can confirm that using parallel takes about twice as long. My personal guess would be that there is enough to compute and the overhead of handling threads is the bottleneck. But this is just a guess and maybe someone else has a different or better guess.

**Comment by chaoming0625** [comment] 2021-03-05 11:50
@esc  Thanks for your reply. My confusion is that when I code LIF neuron model with `if ... else ...` condition judgement, the parallel mode is slower than the single thread; while when I code a HH neuron model without condition control, the parallel mode is much faster. Obviously, "the `for` loop + `if-else` condition" slow down the Numba performance. But this is why?

**Comment by esc** [comment] 2021-03-05 15:37
@chaoming0625 w/o having seen the code, this sounds like something didn't vectorize properly.

**Comment by esc** [comment] 2021-03-05 15:44
@chaoming0625 it may also be a typing issue:

```
        if V >= V_th:
            V = V_reset
            spike = 1  # trying changing this to 1.0
            t_last_spike = _t
        else:
            t_last_spike = t_last_spike
            spike = 0.
            V = V

**Comment by MatthieuDartiailh** [comment] 2021-03-05 15:59
Running on Windows 10 with the following packages installed through conda:
```
blas                      1.0                         mkl
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py38haa95532_0
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2020.2                      254
llvmlite                  0.35.0           py38h34b8924_4
mkl                       2020.2                      256
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
numba                     0.52.0           py38hf11a4ad_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
openssl                   1.1.1j               h2bbff1b_0
python                    3.8.8                hdbf39b2_4
scipy                     1.6.1            py38h14eb087_0
setuptools                52.0.0           py38haa95532_0
six                       1.15.0             pyhd3eb1b0_0
sqlite                    3.33.0               h2a8f88b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4
```

and the slightly modified code to also time compilation separately:

```python
import numba as nb
import numpy as np
import time

V_rest = 0.0
V_reset = -5.0
V_th = 20.0
R = 1.0
tau = 10.0
t_refractory = 5.0
noise = 0.0
dt = 0.02

num_neu = 10000
times = np.arange(0, 10000, dt)


@nb.njit(parallel=True, nogil=True)
def lif2_2(ST, _t):
    for i in nb.prange(ST.shape[1]):
        t_last_spike = ST[0, i]
        I_ext = ST[1, i]
        V = ST[2, i]

        V += (-(V - V_rest) + R * I_ext) / tau * dt
        if V >= V_th:
            V = V_reset
            spike = 1.0
            t_last_spike = _t
        else:
            t_last_spike = t_last_spike
            spike = 0.0
            V = V

        ST[0, i] = t_last_spike
        ST[2, i] = V
        ST[3, i] = spike

np_state2 = np.zeros((4, num_neu))
np_state2[0] = -1e4
np_state2[1] = 20
np_state2[2] = 0

print("Compiling")
t0 = time.time()
lif2_2(np_state2, 0.0)
print(f"Used {time.time() - t0} s")

np_state2 = np.zeros((4, num_neu))
np_state2[0] = -1e4
np_state2[1] = 20
np_state2[2] = 0

print("Running")
t0 = time.time()
for t in times:
    lif2_2(np_state2, t)
print(f"Used {time.time() - t0} s")
```

I get similar results for both (with or without the last suggestion from @esc) but the parallel version is marginally faster (but its compilation is a bit longer). So it may be due to the scheduler overhead.
Parallel case:
Compiling
Used 0.509185791015625 s
Running
Used 9.504520654678345 s

Single Threaded:
Compiling
Used 0.21687531471252441 s
Running
Used 11.756223440170288 s

**Comment by sklam** [comment] 2021-03-05 16:59
Looks like the loop body is not doing enough work to justify the multithreading. Looks like you can move the `for t in times:` loop inside the `prange` to make it the work more intensive.

**Comment by chaoming0625** [comment] 2021-03-06 02:37
@sklam Thanks for your suggestion. I did see the changes. But when coding the `times` in `parange` loop slows down the running speed. The following is my code:

```python

import numpy as np
import time
import numba as nb

V_rest = 0.
V_reset = -5.
V_th = 20.
R = 1.
tau = 10.
t_refractory = 5.
noise = 0.
dt = 0.02

num_neu = 10000
times = np.arange(0, 10000, dt)


def lif1(ST, _t):
    for i in nb.prange(ST.shape[1]):
        I_ext = ST[0, i]
        V = ST[1, i]

        V += (- (V - V_rest) + R * I_ext) / tau * dt
        if V >= V_th:
            V = V_reset
            spike = 1.
        else:
            spike = 0.
            V = V

        ST[1, i] = V
        ST[2, i] = spike


def lif2(ST):
    for i in nb.prange(ST.shape[1]):
        for _t in times:
            I_ext = ST[0, i]
            V = ST[1, i]

            V += (- (V - V_rest) + R * I_ext) / tau * dt
            if V >= V_th:
                V = V_reset
                spike = 1.
            else:
                spike = 0.
                V = V

            ST[1, i] = V
            ST[2, i] = spike


parallel_time_not_in_prange = nb.njit(parallel=True, nogil=True)(lif1)
single_time_not_in_prange = nb.njit(lif1)
parallel_time_in_prange = nb.njit(parallel=True, nogil=True)(lif2)
single_time_in_prange = nb.njit(lif2)

for n, f in [('single_time_not_in_prange', single_time_not_in_prange),
             ('parallel_time_not_in_prange', parallel_time_not_in_prange)]:
    np_state = np.zeros((3, num_neu))
    np_state[0] = np.random.RandomState(1).random(num_neu) * 5 + 17  # Iext
    np_state[1] = 0  # initial V

    t0 = time.time()
    f(np_state, 0.)
    print(f'{n} compilation used {time.time() - t0} s')
    t0 = time.time()
    for _t in times:
        f(np_state, _t)
    print(f'{n} running used {time.time() - t0} s')

for n, f in [('single_time_in_prange', single_time_in_prange),
             ('parallel_time_in_prange', parallel_time_in_prange)]:
    np_state = np.zeros((3, num_neu))
    np_state[0] = np.random.RandomState(1).random(num_neu) * 5 + 17  # Iext
    np_state[1] = 0  # initial V

    t0 = time.time()
    f(np_state)
    print(f'{n} running used {time.time() - t0} s')

```

It produces the results:

single_time_not_in_prange compilation used 0.39000844955444336 s
single_time_not_in_prange running used 4.219401597976685 s
parallel_time_not_in_prange compilation used 0.4772834777832031 s
parallel_time_not_in_prange running used 8.700023651123047 s

single_time_in_prange running used 61.681923151016235 s
parallel_time_in_prange running used 16.599974393844604 s

**Comment by chaoming0625** [comment] 2021-03-06 02:45
Here, I would like to share with you my another expriment on HH neuron model. 

```python


import numpy as np
import time
import numba as nb

dt = 0.01
E_Na = 50.
g_Na = 120.
E_K = -77.
g_K = 36.
E_Leak = -54.387
g_Leak = 0.03
C = 1.0
Vth = 20.
Iext = 10.


@nb.njit
def _step(state):
    V = state[0]
    m = state[1]
    h = state[2]
    n = state[3]
    Isyn = state[5]

    alpha = 0.1 * (V + 40) / (1 - np.exp(-(V + 40) / 10))
    beta = 4.0 * np.exp(-(V + 65) / 18)
    dm = alpha * (1 - m) - beta * m

    alpha = 0.07 * np.exp(-(V + 65) / 20.)
    beta = 1 / (1 + np.exp(-(V + 35) / 10))
    dh = alpha * (1 - h) - beta * h

    alpha = 0.01 * (V + 55) / (1 - np.exp(-(V + 55) / 10))
    beta = 0.125 * np.exp(-(V + 65) / 80)
    dn = alpha * (1 - n) - beta * n

    INa = g_Na * m ** 3 * h * (V - E_Na)
    IK = g_K * n ** 4 * (V - E_K)
    IL = g_Leak * (V - E_Leak)
    dv = (- INa - IK - IL + Isyn) / C

    m += dm * dt
    h += dh * dt
    n += dn * dt
    V2 = V + dv * dt
    sp = np.logical_and((V < Vth), (V2 >= Vth))
    return V2, m, h, n, sp


def hh(state, t):
    for i in nb.prange(state.shape[1]):
        V, m, h, n, sp = _step(state[:, i])
        state[4, i] = sp
        state[0, i] = V
        state[1, i] = m
        state[2, i] = h
        state[3, i] = n


parallel = nb.njit(parallel=True, nogil=True)(hh)
single = nb.njit(hh)


num_neu = 1000
times = np.arange(0, 1000, dt)

for n, f in [('single', single), ('parallel', parallel)]:
    np_state = np.zeros((6, num_neu))
    np_state[-1] = 10.

    t0 = time.time()
    f(np_state, 0.)
    print(f'{n} compilation used {time.time() - t0} s')

    t0 = time.time()
    for t in times:
        f(np_state, t)
    print(f'{n} running used {time.time() - t0} s')
```

For this case (with much `exp` and `power`), the parallel mode is better than the single threaded mode:

single compilation used 0.71000075340271 s
single running used 8.759531736373901 s
parallel compilation used 0.47001171112060547 s
parallel running used 4.719951152801514 s

**Comment by esc** [comment] 2021-03-11 11:45
@chaoming0625 would it be OK to close this issue and move the discussion to our discourse at: https://numba.discourse.group/ -- The Numba issue tracker should track only active bugs and feature requests and this issue doesn't classify as either. Thank you!

**Comment by chaoming0625** [comment] 2021-03-11 12:56
@esc It's okay, but I am also wondering how to solve the parallel issue when we use Numba to accelarate the LIF neuron model. Or,  what can we to customize the parallel performance? Thanks.

**Comment by esc** [comment] 2021-03-15 12:28
@chaoming0625 I am hoping that you may get some more useful feedback via Discourse. In general, the Numba issue tracker  tracks only bugs and features. On Discourse, the community is somewhat larger and there are several discussions about domain specific algorithms and use-cases. Good luck!

**Closed by esc** 2021-03-15 12:28 UTC
Labels: needtriage, performance, performance - run time
