### ISSUE TITLE
NumPy 2.1 Support

### ISSUE THREAD

**Issue by jorenham** [numba/numba#9708] opened 2024-08-19 05:02 UTC
[NumPy 2.1.0](https://github.com/numpy/numpy/releases/tag/v2.1.0) was released today.
When I wanted to try it out in one of my projects, I noticed that `numba==0.60.0` currently pins it as `numpy<2.1` (and raises an `ImportError` if I sneakily ignore this 😇).

Anyway, I think that having NumPy 2.1 support would be really nice; hence this feature request.

**Comment by esc** [comment] 2024-08-19 17:48
@connortann yes, that is unfortunate. We have seen this before with the Python upper bound too. Metadata on PyPI for older releases can not be fixed or patched, so there is no solution to this issue. Does the order of the arguments on the command line make any difference?

**Comment by connortann** [comment] 2024-08-19 18:44
Yep, the order does seem to affect the resolution with `uv`, so this issue only occurs if numba is specified first.

```
~$ uv pip install --dry-run numba numpy
Would install 3 packages
 + llvmlite==0.43.0
 + numba==0.60.0
 + numpy==2.0.1

~$ uv pip install --dry-run numpy numba
Would install 3 packages
 + llvmlite==0.34.0
 + numba==0.51.2
 + numpy==2.1.0
```

> there is no solution to this issue

Makes sense, and no problem: specifying a numba lower bound works fine.

**Comment by esc** [comment] 2024-08-20 07:38
Note: the above issues appears to exist only in `uv`, from what we can tell `pip` does the right thing:

```
❯ pip install --dry-run numba numpy
Collecting numba
  Downloading numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 26.2 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-2.1.0-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 40.4 MB/s eta 0:00:00
Collecting llvmlite<0.44,>=0.43.0dev0
  Downloading llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl (28.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 44.6 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-2.0.1-cp311-cp311-macosx_14_0_arm64.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 38.3 MB/s eta 0:00:00
Would install llvmlite-0.43.0 numba-0.60.0 numpy-2.0.1

~ via 🐍 v3.11.1 took 5s
❯ pip install --dry-run numpy numba
Collecting numpy
  Using cached numpy-2.1.0-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
Collecting numba
  Using cached numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl (2.6 MB)
Collecting llvmlite<0.44,>=0.43.0dev0
  Using cached llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl (28.8 MB)
Collecting numpy
  Using cached numpy-2.0.1-cp311-cp311-macosx_14_0_arm64.whl (5.3 MB)
Would install llvmlite-0.43.0 numba-0.60.0 numpy-2.0.1
```

**Comment by esc** [comment] 2024-08-20 09:59
@connortann which version of Python did you use to generate the examples above?

**Comment by connortann** [comment] 2024-08-20 10:00
In the examples above, I used a clean python 3.12 conda environment.

**Comment by esc** [comment] 2024-08-20 10:09
@connortann but does the installation from `uv` actually succeed? 0.51.2 isn't compatible with Python 3.12.. I'm somewhat surprised here.

**Comment by esc** [comment] 2024-08-20 10:10
I see:

```
130 vhaenel@cyberdeck [test_pip] ~
 💣 zsh» python --version                                                                                                                                                                                :(
Python 3.12.4
vhaenel@cyberdeck [test_pip] ~
 💣 zsh» pip install --dry-run numba numpy==2.1
Collecting numba
  Using cached numba-0.60.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting numpy==2.1
  Using cached numpy-2.1.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba)
  Using cached llvmlite-0.43.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
INFO: pip is looking at multiple versions of numba to determine which version is compatible with other requirements. This could take a while.
Collecting numba
  Using cached numba-0.59.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting llvmlite<0.43,>=0.42.0dev0 (from numba)
  Using cached llvmlite-0.42.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting numba
  Using cached numba-0.59.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gq/T/pip-install-9vf52qd3/numba_b167a224d59e4b9bac733b33137eb437/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gq/T/pip-install-9vf52qd3/numba_b167a224d59e4b9bac733b33137eb437/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.4; only versions >=3.8,<3.12 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by connortann** [comment] 2024-08-20 11:02
The install fails when installing with `uv`, although it looks like the error is different:

```
$ uv pip install numpy numba
Resolved 4 packages in 11ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: llvmlite==0.34.0
  Caused by: Failed to build: `llvmlite==0.34.0`
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
/home/connor/.cache/uv/builds-v0/.tmpPJ6AF6/bin/python /home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py
LLVM version...
--- stderr:
Traceback (most recent call last):
  File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 105, in main_posix
    out = subprocess.check_output([llvm_config, '--version'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 191, in <module>
    main()
  File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 181, in main
    main_posix('linux', '.so')
  File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 107, in main_posix
    raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
error: command '/home/connor/.cache/uv/builds-v0/.tmpPJ6AF6/bin/python' failed with exit code 1
---
```

**Comment by esc** [comment] 2024-08-20 13:40
> The install fails when installing with `uv`, although it looks like the error is different:
> 
> ```
> $ uv pip install numpy numba
> Resolved 4 packages in 11ms
> error: Failed to prepare distributions
>   Caused by: Failed to fetch wheel: llvmlite==0.34.0
>   Caused by: Failed to build: `llvmlite==0.34.0`
>   Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
> --- stdout:
> running bdist_wheel
> /home/connor/.cache/uv/builds-v0/.tmpPJ6AF6/bin/python /home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py
> LLVM version...
> --- stderr:
> Traceback (most recent call last):
>   File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 105, in main_posix
>     out = subprocess.check_output([llvm_config, '--version'])
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/home/connor/miniforge3/envs/temp-shap-llvm/lib/python3.12/subprocess.py", line 1955, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 191, in <module>
>     main()
>   File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 181, in main
>     main_posix('linux', '.so')
>   File "/home/connor/.cache/uv/built-wheels-v3/pypi/llvmlite/0.34.0/ToLSATY4d9xsrCr5uO4Ez/llvmlite-0.34.0.tar.gz/ffi/build.py", line 107, in main_posix
>     raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
> RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
> error: command '/home/connor/.cache/uv/builds-v0/.tmpPJ6AF6/bin/python' failed with exit code 1
> ---
> ```

Yeah, that error means, that it couldn't find a binary wheel and is trying to install `llvmlite` from source, but without an LLVM installed on the system (hence the error about missing `llvm-config`).

**Comment by doronbehar** [comment] 2024-08-21 13:32
I'll report that I managed to compile numba from the master branch with the latest numpy 2.1, on NixOS. However it wasn't comfortable - I had to manually edit `numba/_version.py` such that the version metadata file won't be `0+unknown`... It'd be nice if you had git tagged the current `0.61.1dev` to spare me this small inconvenience.

**Comment by esc** [comment] 2024-08-22 09:51
> I'll report that I managed to compile numba from the master branch with the latest numpy 2.1, on NixOS. However it wasn't comfortable - I had to manually edit `numba/_version.py` such that the version metadata file won't be `0+unknown`... It'd be nice if you had git tagged the current `0.61.1dev` to spare me this small inconvenience.

@doronbehar thank you for this info. Can you elaborate more on the versioning issue? Since we did tag a new dev version:

https://github.com/numba/numba/releases/tag/0.61.0dev0

**Comment by esc** [comment] 2024-08-22 10:44
Also, note that there are some issues with Numpy 2.1 which cause the Numba test suite to fail:

https://dev.azure.com/numba/numba/_build/results?buildId=17660&view=logs&j=5ac7dbda-0274-52a7-2be6-066fc01d5d9f&t=620d9c0c-9421-523c-f41b-31cbd49184cc&l=12497

please use current `main` of Numba with NumPy 2.1 with caution.

**Comment by doronbehar** [comment] 2024-08-22 15:07
> > I'll report that I managed to compile numba from the master branch with the latest numpy 2.1, on NixOS. However it wasn't comfortable - I had to manually edit `numba/_version.py` such that the version metadata file won't be `0+unknown`... It'd be nice if you had git tagged the current `0.61.1dev` to spare me this small inconvenience.
> 
> @doronbehar thank you for this info. Can you elaborate more on the versioning issue? Since we did tag a new dev version:
> 
> [`0.61.0dev0` (release)](https://github.com/numba/numba/releases/tag/0.61.0dev0)

Isn't that tag too old (May 15)? Even [Numpy 2.0.0 was released in June 16](https://github.com/numpy/numpy/releases/tag/v2.0.0)...

> Also, note that there are some issues with Numpy 2.1 which cause the Numba test suite to fail:
> 
> [dev.azure.com/numba/numba/_build/results?buildId=17660&view=logs&j=5ac7dbda-0274-52a7-2be6-066fc01d5d9f&t=620d9c0c-9421-523c-f41b-31cbd49184cc&l=12497](https://dev.azure.com/numba/numba/_build/results?buildId=17660&view=logs&j=5ac7dbda-0274-52a7-2be6-066fc01d5d9f&t=620d9c0c-9421-523c-f41b-31cbd49184cc&l=12497)
> 
> please use current `main` of Numba with NumPy 2.1 with caution.

Thanks for the warning. I noticed many more tests failing on our platform, and it takes a lot of time to run them all, so I don't have a complete list available yet. Some failures could be due to our build environment (GPU based tests are not allowed on this environment), so when I'll find time to run all the tests, I'll provide you with a complete list of failures, and full log. Current progress is at https://github.com/NixOS/nixpkgs/pull/336284 (don't have a lot of time now to put effort in this).

**Comment by esc** [comment] 2024-08-22 16:38
> > > I'll report that I managed to compile numba from the master branch with the latest numpy 2.1, on NixOS. However it wasn't comfortable - I had to manually edit `numba/_version.py` such that the version metadata file won't be `0+unknown`... It'd be nice if you had git tagged the current `0.61.1dev` to spare me this small inconvenience.
> > 
> > 
> > @doronbehar thank you for this info. Can you elaborate more on the versioning issue? Since we did tag a new dev version:
> > [`0.61.0dev0` (release)](https://github.com/numba/numba/releases/tag/0.61.0dev0)
> 
> Isn't that tag too old (May 15)? Even [Numpy 2.0.0 was released in June 16](https://github.com/numpy/numpy/releases/tag/v2.0.0)...

I'm sorry but I don't understand your comment and I think I misunderstood what you are asking about. What kind of tag were you expecting and within what time-frame?

We always tag a new dev release, when a new release branch for a minor version is created. This means, on current `main`:

```
 💣 zsh» git describe --always --tags --dirty
0.61.0dev0-198-g4fc11d4169
```

**Comment by esc** [comment] 2024-08-22 16:41
> Thanks for the warning. I noticed many more tests failing on our platform, and it takes a lot of time to run them all, so I don't have a complete list available yet. Some failures could be due to our build environment (GPU based tests are not allowed on this environment), so when I'll find time to run all the tests, I'll provide you with a complete list of failures, and full log. Current progress is at [NixOS/nixpkgs#336284](https://github.com/NixOS/nixpkgs/pull/336284) (don't have a lot of time now to put effort in this).

@doronbehar thank you for this effort, I think @sklam is also looking into this too.

**Comment by doronbehar** [comment] 2024-08-24 20:47
> > > @doronbehar thank you for this info. Can you elaborate more on the versioning issue? Since we did tag a new dev version:
> > > [`0.61.0dev0` (release)](https://github.com/numba/numba/releases/tag/0.61.0dev0)
> > 
> > 
> > Isn't that tag too old (May 15)? Even [Numpy 2.0.0 was released in June 16](https://github.com/numpy/numpy/releases/tag/v2.0.0)...
> 
> I'm sorry but I don't understand your comment and I think I misunderstood what you are asking about. What kind of tag were you expecting and within what time-frame?

 When I wrote that message I thought it is impossible that the `0.61.0dev` commit from May 15 will support Numpy 2.0.0 or 2.1.0, since it was tagged in May 15, but surprisingly somehow it is :). However, I still had to perform a small substitution to `numba/_version.py`, because dependent packages failed to build like this (e.g `librosa`):

```
Checking runtime dependencies for librosa-0.10.2.post1-py3-none-any.whl
  - numba>=0.51.0 not satisfied by version 0.61.0.dev0
```

But I'm not sure this is easily fixable... Your `_version.py` and `.gitattributes` setup is pretty complex.

> @doronbehar thank you for this effort, I think @sklam is also looking into this too.

Don't have these results yet :) - the last attempt failed once more due to something related to the `.gitattributes` setup - with the `0.61.0dev0` tag I am hopeful the same failure won't happen.

**Comment by esc** [comment] 2024-08-26 12:45
> > > > @doronbehar thank you for this info. Can you elaborate more on the versioning issue? Since we did tag a new dev version:
> > > > [`0.61.0dev0` (release)](https://github.com/numba/numba/releases/tag/0.61.0dev0)
> > > 
> > > 
> > > Isn't that tag too old (May 15)? Even [Numpy 2.0.0 was released in June 16](https://github.com/numpy/numpy/releases/tag/v2.0.0)...
> > 
> > 
> > I'm sorry but I don't understand your comment and I think I misunderstood what you are asking about. What kind of tag were you expecting and within what time-frame?
> 
> When I wrote that message I thought it is impossible that the `0.61.0dev` commit from May 15 will support Numpy 2.0.0 or 2.1.0, since it was tagged in May 15, but surprisingly somehow it is :). However, I still had to perform a small substitution to `numba/_version.py`, because dependent packages failed to build like this (e.g `librosa`):
> 
> ```
> Checking runtime dependencies for librosa-0.10.2.post1-py3-none-any.whl
>   - numba>=0.51.0 not satisfied by version 0.61.0.dev0
> ```
> 
> But I'm not sure this is easily fixable... Your `_version.py` and `.gitattributes` setup is pretty complex.

Oh, we are misunderstanding each other here. I don't know how yo are building Numa. Can you explain how you are trying to build it? I think you might be doing something unusual, I have never heard of anyone having to mess with `_version.py` and/or `.gitattrubutes`.

I would recommend to build and test from `main` -- Numba uses the `versioneer` tool, we did not implement that ourselves. You should not need to touch `_version.py ` and `.gitattributes`. Versioneer makes sure to setup and configure the version number from the latest tag, so you don't have to mess around with this stuff.

```
$ python -m pip install -vv -e .
...
$ pip list | grep numba
numba                         0.61.0.dev0+198.g4fc11d4169 /Users/esc/git/numba
```

If you need inspiration on how to build Numba you can also look at my personal makefile for the project:

https://github.com/esc/numba-dev-files/blob/master/Makefile

**Comment by doronbehar** [comment] 2024-08-26 15:05
OK I need to explain a bit of Nix specific details to explain why I need to edit `numba/_version.py` (for sure if I use an untagged commit). I don't know though how to explain why `librosa` isn't satisfied with numba `0.61.0dev0`, and hence why do I need to edit `numba/_version.py` to return `0.61.0` and not `0.61.0dev0`.

Nix is a functional package manager. Every package has only pure inputs and "returns" a single tree of files per package. The inputs of a package can be another package, or something downloaded from the internet. To ensure the purity of inputs downloaded from the internet, our ecosystem forces us to specify a hash for such inputs, based on the contents of the inputs. So for example Git checkouts will change their contents and therefor their hash, if their `.git` directory will all of a sudden contain commits committed after the hash was originally retrieved. This is discussed [here](https://github.com/NixOS/nixpkgs/issues/8567).

That's why we almost always prefer GitHub tarballs, and even if we have to use a Git server, we `rm -rf .git` before we calculate the hash. Hence I'm not sure any tool ([versionneer](https://github.com/NixOS/nixpkgs/issues/8567) for instance), will be able to return us a proper version, if the `.git` directory is missing.

As for `librosa`'s failure with `0.61.0dev0`, I wonder what will happen to you if you'll try to build `librosa` against the Git `0.61.0dev0` checkout of `numba`.

**Comment by esc** [comment] 2024-08-26 15:59
@doronbehar ok, that makes sense. I thought that `versioneer` would insert the correct version number when creating the tarball using the `export-subst` in the `.gitattributes` file. But it seems like that info isn't being recorded and you may end up with the following instead:

```
 💣 zsh» pip list
Package    Version                  Editable project location
---------- ------------------------ -------------------------
llvmlite   0.44.0.dev0+110.gca123c3
numba      0+unknown                /private/tmp/numba
numpy      2.1.0
pip        24.2
setuptools 72.1.0
wheel      0.43.0
```

Is this what you are seeing too?

**Comment by notatallshaw** [comment] 2024-08-27 00:22
To comment briefly on the issues tools have with resolving here (i.e. why they pick a new numpy and an old numba), resolution algorithms are looking for a solution, and generally don't understand if a has an upper bound on b then I should look for older versions of b not older versions of a.

pip is doing the right thing in @esc case because it prioritizes [depth](https://pip.pypa.io/en/stable/topics/more-dependency-resolution/#the-resolver-algorithm) when picking what to backtrack on, so the fact that numpy is a dependency of numba, and the resolution graph wasn't more complicated, means that pip is more likely to backtrack on numpy. However, while this helped here, there are plenty of other resolutions where pip makes the same "mistake".

I'm not aware of any SAT solvers that take this kind of nuance into account, and generally modifying them to do so is non-trivial, and you need to be careful you're not breaking their soundness. I do have a long term plan to try to improve pip's resolver here though, but there is other stuff that needs to be improved first.

It would technically be possible to publish post releases to PyPI of older releases with just the metadata changed to include upper bounds on numpy, and yank the previous releases, but I imagine it would be a PIA.

**Comment by doronbehar** [comment] 2024-08-27 09:50
> Is this what you are seeing too?

The Nix Python ecosystem doesn't display that information the same way, but I think the answer is yes. To reproduce the issue I experienced with `librosa` you'd have to try to build it in the same virtual environment you took that `pip list`.

**Comment by alanwilter** [comment] 2024-09-06 07:28
Do we have a schedule for numba release compatible with numpy 2.x?

**Comment by esc** [comment] 2024-09-06 09:59
> Do we have a schedule for numba release compatible with numpy 2.1?

Yes, the chart here https://github.com/numba/numba/issues/9540 states it was supposed to be released already. 😅 I will try to bring this up during the developer meet next Tuesday 10th Sept and perhaps an ETA can be established then.

**Comment by esc** [comment] 2024-09-10 14:20
> Do we have a schedule for numba release compatible with numpy 2.1?

Next release, Numba 0.61, currently expected for mid October.

**Comment by bluppfisk** [comment] 2024-09-12 17:36
hello! Glad to hear that this release is imminent so we can future-proof our packages and get rid of the myriad of deprecationwarnings :)

What I really worry about is: should I heed this `RuntimeWarning` about binary incompatibility, or can I safely ignore it? I'm not sure about the fundamentals, but it does sound like potentially problematic?

**Comment by esc** [comment] 2024-09-17 08:52
> What I really worry about is: should I heed this `RuntimeWarning` about binary incompatibility, or can I safely ignore it? I'm not sure about the fundamentals, but it does sound potentially problematic?

Which warning is this? Can you list it please and say where it is coming from.

**Comment by bluppfisk** [comment] 2024-09-17 08:59
The warning:

```
RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
```

**Comment by bnavigator** [comment] 2024-09-18 14:42
I have seen this before in Linux packages. It usually comes down to a mismatch modules compiled with different numpy headers. Since numba 0.60 was compiled with numpy 2.0(rc) it should be fine. @bluppfisk, what's your installed numpy version?)

**Closed** 2024-10-22 14:51 UTC
Labels: feature_request

**Comment by filbranden** [comment] 2024-10-22 23:54
Very nice! Any word on whether we can expect a numba 0.61 release pinning numpy to 2.1 any time soon? Thanks!

**Comment by kmuehlbauer** [comment] 2024-11-08 08:18
> Any word on whether we can expect a numba 0.61 release pinning numpy to 2.1 any time soon? Thanks!

Are there any blockers to release numba 0.61?

**Comment by esc** [comment] 2024-11-17 17:12
> > Any word on whether we can expect a numba 0.61 release pinning numpy to 2.1 any time soon? Thanks!
> 
> Are there any blockers to release numba 0.61?

Please subscribe to the release checklist for more information and updates: https://github.com/numba/numba/issues/9777
