### ISSUE TITLE
NumbaIRAssumptionWarning: variable '_i8_impl_v4_cur_2' is not in scope

### ISSUE THREAD

**Issue by auderson** [numba/numba#8130] opened 2022-06-04 07:45 UTC
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I'm not sure if this is the same as #7802, but I'm posting the codes here anyway:

```python
from numba import *
import numpy as np
from numba.extending import overload


def _f8_impl(arr):
    cur = 0.0
    for i, x in enumerate(arr):
        cur += x


def _i8_impl(arr):
    cur = 0
    for i, x in enumerate(arr):
        cur += x


def _f_hook(arr):
    pass


@overload(_f_hook, inline="always")
def _f_impl(arr):
    if arr.dtype == f8:
        return _f8_impl
    elif arr.dtype == i8:
        return _i8_impl


@njit
def f(arr):
    return _f_hook(arr)


f(np.arange(10))
```
```
/home/auderson/miniconda3/lib/python3.8/site-packages/numba/core/ssa.py:272: NumbaIRAssumptionWarning: variable '_i8_impl_v4_cur_2' is not in scope.
This warning came from an internal pedantic check. Please report the warning
message and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new?template=bug_report.md
  warnings.warn(errors.NumbaIRAssumptionWarning(wmsg,
```

Turning off `inline="always"` will disable the warning.

**Comment by stuartarchibald** [comment] 2022-06-06 09:57
Thanks for the report. This is indeed caused by the same underlying issue as in #7802. Patch https://github.com/numba/numba/pull/7823 fixes. Closing this as it's a duplicate of the same problem but accessed via different code paths. Thanks again for reporting it as requested by the message, much appreciated.

**Closed by stuartarchibald** 2022-06-06 09:57 UTC
