### ISSUE TITLE
Add support for range as argument to `contains`

### ISSUE THREAD

**Issue by DerWeh** [numba/numba#4109] opened 2019-05-21 17:03 UTC
The documentation states 

> range: semantics are similar to those of Python 3 even in Python 2: a range object is returned instead of an array of values. The only permitted use of range is as a callable function (cannot pass range as an argument to a jitted function or return a range from a jitted function)

Thus, I would assume I can use `range` just like in python. A simple example shows that this is wrong:

```python
In [1]: import numba

In [2]: @numba.jit(nopython=True)
   ...: def test(i):
   ...:     return i in range(1, 8, 3)
   ...: 
   ...: 

In [3]: test(2)
```

Yields the error:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function contains>) with argument(s) of type(s): (range_state_int64, int64)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-2-3e00fb68c4e2> (3)

File "<ipython-input-2-3e00fb68c4e2>", line 3:
def test(i):
    return i in range(1, 8, 3)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```

I would welcome the implementation of `range` in Numba. If this is not planned, it should be stated in the documentation. That this feature is not available.

**Comment by synapticarbors** [comment] 2019-05-21 17:10
@DerWeh the issue is not due to `range` not being implemented in numba. What does not appear to be supported is the `contains` method for a range type and an integer. So you can't check if `i` is in `range(1, 8, 3)`, but you can certainly iterate over that range and operate on its elements. For example:

```python
@nb.njit
def test(i):
    s = i
    for k in range(1, 8, 3):
        s += k
    return s
```

**Comment by stuartarchibald** [comment] 2019-05-21 17:11
Thanks @synapticarbors, good diagnosis.

**Comment by synapticarbors** [comment] 2019-05-21 17:19
And just as a side note, you could code the functionality yourself as something like:

```python
@nb.njit
def test(i):
    found = False
    for k in range(1, 8, 3):
        if i == k:
            found = True
            break
    return found
```

**Comment by stuartarchibald** [comment] 2019-05-22 14:33
@synapticarbors wondering if you would be interested in fixing this? I think it's a question of `@overload`ing `operator.contains` with an impl for `types.RangeType`. I've added https://github.com/numba/numba/pull/4110 to help with some shortcutting cases/general maths.

**Comment by stuartarchibald** [comment] 2019-05-22 19:37
@synapticarbors brilliant, thanks very much!

**Comment by DerWeh** [comment] 2019-05-23 21:05
Thanks for the clarification, for me it simply belonged to the functionality of the range object.
But please keep in mind that the implementation you gave is not good. After all, if I wouldn't care about performance I wouldn't bother with numba. Something of the like 
```
@numba.jit(nopython=True)
def in_kind(number):
    return number < stop and not (number-start) % step
```
should be used instead, we want O(1) not O(N) for a simple `in`.

I would appreciate an implementation, as I found replacing generator relatively often takes such constructs.

**Comment by stuartarchibald** [comment] 2019-05-23 22:15
@DerWeh indeed, that's similar to the CPython implementation mentioned by @synapticarbors [here](https://github.com/numba/numba/issues/4109#issuecomment-494854573), however, it's not possible to write that at present because `range.{start, stop, step}` isn't implemented in Numba and so the workaround mentioned was literally all that was available to users. A couple of days back I wrote https://github.com/numba/numba/pull/4110 to expose these attributes on `range` and an implementation for `operator.contains` with arguments of type `range` and `<anything else>` will be written in due course, rest assured it'll be `O(1)` complexity.

**Comment by DerWeh** [comment] 2019-05-26 19:14
I didn't doubt that the implementation will be right, I just think a suitable workaround should be found for people with the same problem ending in this thread.
Thus, a O(1) solution should be stated. But thanks for all the good work.

**Comment by stuartarchibald** [comment] 2019-05-31 07:51
@synapticarbors https://github.com/numba/numba/pull/4110 is now in master, if you are still interested in implementing a fix for this, a PR would be most welcome :) Thanks!

**Comment by synapticarbors** [comment] 2019-05-31 12:39
@stuartarchibald I actually started working on it last night and just pushed a preliminary PR in #4129

**Comment by stuartarchibald** [comment] 2019-05-31 12:57
@synapticarbors brilliant, thanks :)

**Comment by stuartarchibald** [comment] 2019-06-10 22:09
Closing this issue as it seems to be resolved by https://github.com/numba/numba/pull/4129 (thanks @synapticarbors :)). If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-06-10 22:09 UTC
Labels: feature_request
