### ISSUE TITLE
jitclass with ListType doesn't work

### ISSUE THREAD

**Issue by abdullahkavakli** [numba/numba#7672] opened 2021-12-19 18:05 UTC
i got this error:
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x000001B7EB79ABB0>.
Failed in nopython mode pipeline (step: native lowering)
Cannot cast list(instance.jitclass.Node_for_sample#1b7eb7b2f70<data:int32>)<iv=None> to ListType[instance.jitclass.Node_for_sample#1b7eb7b2f70<data:int32>]: %".165" = load {i8*, i8*}, {i8*, i8*}* %".62"

File "xxxxx.py", line 56:
    def __init__(self,key):
        <source elided>
        self.data=key
        self.children=[]
        ^

During: lowering "(self).children = $12build_list.4" at xxxxx.py (56)
During: resolving callee type: jitclass.Node#1b7eb7b2550<data:int32,children:ListType[instance.jitclass.Node_for_sample#1b7eb7b2f70<data:int32>],rep:int32>
During: typing of call at xxxxxx.py (84)

Enable logging at debug level for details.

File "xxxx.py", line 84:
    def __init__(self):
        self.root=Node(-1)
        ^

During: resolving callee type: jitclass.Tree#1b7eb7b2430<root:instance.jitclass.Node#1b7eb7b2550<data:int32,children:ListType[instance.jitclass.Node_for_sample#1b7eb7b2f70<data:int32>],rep:int32>,pair:DictType[int64,int64]<iv=None>>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.Tree#1b7eb7b2430<root:instance.jitclass.Node#1b7eb7b2550<data:int32,children:ListType[instance.jitclass.Node_for_sample#1b7eb7b2f70<data:int32>],rep:int32>,pair:DictType[int64,int64]<iv=None>>
During: typing of call at <string> (3)

```python

@jitclass([('data', int32)])
class Node_for_sample():    
    def __init__(self):
        data=0


@jitclass([('data', int32), ('children', types.ListType(Node_for_sample.class_type.instance_type))])
class Node():    
    def __init__(self,key):
        self.data=key
        self.children=[Node_for_sample()]
        
    
kv_ty = (types.int64, types.int64)
@jitclass([ ('root', Node.class_type.instance_type),
            ('pair', types.DictType(*kv_ty))])      
class Tree():
    
    def __init__(self):
        self.root=Node(-1)
        self.pair= {}


new_tree=Tree()
 ```

**Comment by gmarkall** [comment] 2021-12-20 11:48
This simplified reproducer exhibits a similar problem:

```python
from numba.experimental import jitclass
from numba.types import int32
import typing as pt


@jitclass([('data', int32)])
class Node_for_sample():
    def __init__(self):
        self.data = 0


@jitclass
class Node():
    children: pt.List[Node_for_sample]

    def __init__(self):
        self.children = [Node_for_sample()]


new_node = Node()
```

which produces

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: native lowering)
Cannot cast list(instance.jitclass.Node_for_sample#7f33a7176910<data:int32>)<iv=None> to ListType[instance.jitclass.Node_for_sample#7f33a7176910<data:int32>]: %".153" = load {i8*, i8*}, {i8*, i8*}* %".50"
During: lowering "(self).children = $6build_list.2" at /home/gmarkall/numbadev/issues/7672/repro.py (17)
During: resolving callee type: jitclass.Node#7f33a70bf700<children:ListType[instance.jitclass.Node_for_sample#7f33a7176910<data:int32>]>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.Node#7f33a70bf700<children:ListType[instance.jitclass.Node_for_sample#7f33a7176910<data:int32>]>
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>
```

This is using a [reflected list](https://numba.readthedocs.io/en/latest/reference/pysupported.html?highlight=list#list-reflection) (because of the `[Node_for_sample()]` expression). Reflected lists are deprecated and the [Typed List](https://numba.readthedocs.io/en/latest/reference/pysupported.html?highlight=list#typed-list) should be used instead. If we use one (by changing the expression to `self.children = List([Node_for_sample()])`):

```python
from numba.experimental import jitclass
from numba.types import int32
from numba.typed import List
import typing as pt


@jitclass([('data', int32)])
class Node_for_sample():
    def __init__(self):
        self.data = 0


@jitclass
class Node():
    children: pt.List[Node_for_sample]

    def __init__(self):
        self.children = List([Node_for_sample()])


new_node = Node()
```

then the simplified example runs without error.

Your full example can then be modified with this change and one other, to run without error:

```python
from numba.experimental import jitclass
from numba.types import int32
from numba.typed import List
from numba import types


@jitclass([('data', int32)])
class Node_for_sample():
    def __init__(self):
        self.data = 0


@jitclass([('data', int32),
           ('children',
            types.ListType(Node_for_sample.class_type.instance_type))])
class Node():
    def __init__(self, key):
        self.data = key
        self.children = List([Node_for_sample()])


kv_ty = (types.int64, types.int64)


@jitclass([('root', Node.class_type.instance_type),
           ('pair', types.DictType(*kv_ty))])
class Tree():
    def __init__(self):
        self.root = Node(-1)
        self.pair = {1: 1}


new_tree = Tree()
```

The second change I made is to initialize the dict in `self.pair` with something (`self.pair = {1: 1}`) - without this, Numba can't determine the type of the RHS expression so it raises an error.

**Comment by gmarkall** [comment] 2021-12-20 11:58
I've created #7678 to record the reflected list issue without mixing it in with this discussion. I'll keep this issue as question / needtriage, but I think it can be closed - @abdullahkavakli Are you able to get the solution above to work for you? If so, would you be happy to close this issue please?

**Closed** 2021-12-21 10:13 UTC
Labels: needtriage, question

**Comment by gmarkall** [comment] 2021-12-21 10:24
Many thanks @abdullahkavakli !

**Comment by abdullahkavakli** [comment] 2021-12-28 09:33
I thank you @gmarkall
