### ISSUE TITLE
Weird warnings when using @jit on version 0.50

### ISSUE THREAD

**Issue by JivanRoquet** [numba/numba#5891] opened 2020-06-19 17:32 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When using Numba version 0.38:

```python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import numba
>>> numba.__version__
'0.38.0'
>>> from numba import jit
>>> @jit
... def _ndiff(x):
...     s = x.size
...     r = np.empty(s, dtype=np.bool) 
...     for i in range(1, s): 
...         r[i] = x[i] - x[i-1] 
...     return r
... 
>>> arr = np.random.choice([0, 1], size=1000000).astype(np.bool)
>>> %timeit _ndiff(arr)
5.32 microseconds
```

Now the *exact same code* with version 0.50:

```
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import numba
>>> numba.__version__
'0.50.0'
>>> from numba import jit
>>> @jit
... def _ndiff(x):
...     s = x.size
...     r = np.empty(s, dtype=np.bool) 
...     for i in range(1, s): 
...         r[i] = x[i] - x[i-1] 
...     return r
... 
>>> arr = np.random.choice([0, 1], size=1000000).astype(np.bool)
>>> %timeit _ndiff(arr)
5.32 microseconds
<stdin>:1: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "_ndiff" failed type inference due to: No implementation of function Function(<built-in function empty>) found for signature:
 
 >>> empty(int64, dtype=Function(<class 'bool'>))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'empty': File: <built-in>: Line <N/A>.
    With argument(s): '(int64, dtype=Function(<class 'bool'>))':
   No match.

During: resolving callee type: Function(<built-in function empty>)
During: typing of call at <stdin> (4)


File "<stdin>", line 4:
<source missing, REPL/exec in use?>

<stdin>:1: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_ndiff" failed type inference due to: cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>

File "<stdin>", line 5:
<source missing, REPL/exec in use?>

/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/object_mode_passes.py:177: NumbaWarning: Function "_ndiff" was compiled in object mode without forceobj=True, but has lifted loops.

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/object_mode_passes.py:187: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg,
(again, a few microseconds)
```

Given the performance of the @jit version in both 0.38 and 0.50, it is ABSOLUTELY AND DEFINITELY not running in object mode. Removing `@jit` on a 1,000,000-long array makes the Python version take forever, while the version with `@jit` runs in a few microseconds for the same array size.

Why so many warnings claiming that the function is running in object mode, if this is manifestly not the case?

**Comment by JivanRoquet** [comment] 2020-06-19 18:39
I get that the warnings might "warn" about this function "possibly" able to silently run in object-mode, so that might actually be a good thing.

However, these exact same warnings also appear when using `@njit` or `@jit(nopython=True)`, which, this time, makes no sense to me (as these warnings are specifically there to incite the user not to use plain `@jit`).

**Comment by stuartarchibald** [comment] 2020-06-22 14:00
Thanks for the report. The code above won't compiled with `nopython=True` because `np.bool` is not supported as a dtype (`np.bool` is `bool` whereas  `np.bool_` is the dtype). The code runs at about the same speed because under `@jit` because Numba spots that the loop can be compiled and so compiles it and swaps out the interpreted loop for an compiled one (`Compilation is falling back to object mode WITH looplifting enabled...`). See also http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode

**Comment by JivanRoquet** [comment] 2020-06-24 19:53
@stuartarchibald thanks for the detailed and useful response — however it might be useful to note that the function **also** compiles with `@jit(nopython=True)` but with warnings. I was under the impression that using `nopython=True` would prevent the function to compile **at all** if any part of it can't be compiled, even if looplifting is still enabled.

**Comment by stuartarchibald** [comment] 2020-06-24 20:05
@JivanRoquet no problem. I'm afraid I can't reproduce what you describe:
```python
$ cat issue5891.py
import numpy as np
import numba
print(numba.__version__)

from numba import jit, njit
@jit(nopython=True)
def _ndiff(x):
    s = x.size
    r = np.empty(s, dtype=np.bool)
    for i in range(1, s): 
        r[i] = x[i] - x[i-1] 
    return r

arr = np.random.choice([0, 1], size=1000000).astype(np.bool)
_ndiff(arr)

$ python issue5891.py
0.50.0
Traceback (most recent call last):
  File "issue5891.py", line 15, in <module>
    _ndiff(arr)
  File "<path>numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<path>numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "<path>numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function empty>) found for signature:
 
 >>> empty(int64, dtype=Function(<class 'bool'>))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'empty': File: <built-in>: Line <N/A>.
    With argument(s): '(int64, dtype=Function(<class 'bool'>))':
   No match.

During: resolving callee type: Function(<built-in function empty>)
During: typing of call at issue5891.py (9)


File "issue5891.py", line 9:
def _ndiff(x):
    <source elided>
    s = x.size
    r = np.empty(s, dtype=np.bool)
    ^

```

**Comment by stuartarchibald** [comment] 2020-09-02 09:55
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-02 09:55 UTC
Labels: needtriage
