### ISSUE TITLE
support axis argument for np.roll()

### ISSUE THREAD

**Issue by ziofil** [numba/numba#5211] opened 2020-02-07 10:18 UTC
`np.roll()` is supported, except the third argument (`axis`). Would it be possible to support it?

I need to roll along different axes of a rank-4 tensor and the only option I have is to transpose the axis to the 1st dimension, roll and transpose back.

**Comment by esc** [comment] 2020-02-07 10:38
@ziofil thanks for asking about this on the Numba issue tracker. The lack of `axis` support is known issue for several NumPy functions. In fact if you serach for `axis` on the issue tracker, you will find several references:

https://github.com/numba/numba/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+axis+

In fact there is already an issue asking for `axis` support in `roll` here, so this is likely a duplicate of that.

While waiting for the implementation to arrive in Numba, you may be able to implement the a rank-4 specific `roll` yourself using `for` loops over your NumPy arrays. Numba is excellent at optimizing Python code with `for` loops so the performance will most probably be quite acceptable.

**Comment by esc** [comment] 2020-02-07 10:39
The earlier feature request is here: https://github.com/numba/numba/issues/4805

**Comment by esc** [comment] 2020-02-07 10:40
@ziofil if you agree with this being a duplicate, please feel free to close this issue. If not, please let me know and I will update the labels accordingly, thanks!

**Closed** 2020-02-08 07:44 UTC
Labels: duplicate, feature_request
