### ISSUE TITLE
no more numba.testmod?

### ISSUE THREAD

**Issue by chengs** [numba/numba#2468] opened 2017-07-17 15:46 UTC
I am trying to let doctest work in numba wrappered functions. But now numba.testmod no longer exists and no document talks about it.

What happened?

**Comment by seibert** [comment] 2017-07-17 18:03
We're going to take a look at the doctest issue you raised in #190, but testmod was removed a long time ago when Numba stopped using nose to run doctests.  (And in general, we've moved away from doctests as we find them not good for documentation or testing of Numba.)

**Comment by chengs** [comment] 2017-07-18 13:41
Hello @seibert 

Thank you for the response. I understand that it's hard to make Numba compatible with doctest (by doctest.testmod()) as the latter uses inspect.isfunction to detect if one is a function and should be tested.

In my opinion, it is better to add a section into the document describing this compatibility problem and how to solve it. Such a description appeared before (http://numba.pydata.org/numba-doc/0.12.1/doctest.html) but disappeared now.

According to https://docs.python.org/2/library/doctest.html
> In addition, if M.__test__ exists and “is true”, it must be a dict, and each entry maps a (string) name to a function object, class object, or string. Function and class object docstrings found from M.__test__ are searched, and strings are treated as if they were docstrings. In output, a key K in M.__test__ appears with name

So the solution is simple. Since a Numba-wrappered function still has __doc__. One just needs to make a dict named __test__ and add a function's name as key and its __doc__ as value. Then doctest module can understand there are more functions to test. 

This solution can simply be described in the document. Even no need to fall back and use *numba.testmod* (which is, in my humble opinion, ugly and confusing).

**Comment by seibert** [comment] 2017-07-18 14:40
Would it make sense to create a default `__test__` automatically for every Numba function that has a docstring?  The user could still override it after defining the function.

**Comment by seibert** [comment] 2017-07-18 14:56
Actually, more information: It appears that Python 3.6 does discover doctests on Numba-decorated functions, but Python 2.7 does not.  (I have not checked any versions between those two.)

**Comment by chengs** [comment] 2017-07-18 16:18
@seibert to create a default __test__ automatically for every Numba function seems a very nice idea to me!

**Comment by tobiasraabe** [comment] 2019-03-16 16:24
Maybe it is worth a separate issue, but I wanted to comment here first as it is related.

I noticed that doctest discovers functions wrapped with ``njit``, but none with ``guvectorize``. Do you know why?

**Comment by stuartarchibald** [comment] 2020-02-06 12:53
[Python 2.7 reached EOL on January 1st, 2020](https://github.com/python/devguide/pull/344) and [Numba 0.47 was the last release to support Python 2.7](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/g6wF8D-jV_o). Closing this issue as it is Python 2.7 specific, if this problem is reproducible on Python 3 with Numba >= 0.48 then please reopen it. Many thanks!

**Closed by stuartarchibald** 2020-02-06 12:53 UTC
Labels: doc, wontfix

**Comment by guilhermeleobas** [comment] 2020-10-05 18:08
Hi @stuartarchibald, it seems that the underlying problem is still present in newer versions of Numba. Doctest discovers functions wrapped with `@njit` but fails with `@guvectorize`.

```python
from numba import guvectorize, int64, njit

@guvectorize([(int64[:], int64, int64[:])], '(n),()->(n)')
def bar(x, y, res):
    """
    Examples
    --------
    >>> x = 1
    """
    for i in range(x.shape[0]):
            res[i] = x[i] + y

@njit
def foo():
    """
    Examples
    --------
    >>> x = 1
    """
    pass
```

`pytest -rs -sv -v --doctest-modules test_foo.py`

**Comment by stuartarchibald** [comment] 2020-10-06 09:42
@guilhermeleobas please could you open a new ticket as this issue seems to be specific to `@guvectorize`? Thanks.
