### ISSUE TITLE
Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED

### ISSUE THREAD

**Issue by mazzalab** [numba/numba#3788] opened 2019-02-21 09:25 UTC
Hi,
I'm trying to execute this code:

```
@cuda.jit('void(uint16[:, :])')
def mymethod(adjmat: np.ndarray):
    i = cuda.grid(1)
    graph_size = adjmat.shape[0]
    if i < graph_size:  # Check array boundaries
        for k in range(0, graph_size):
            for j in range(0, graph_size):
                posIJ = adjmat[i, j]
                if posIJ <= 2:
                    continue

                posIK = adjmat[i, k]
                posKY = adjmat[k, j]
                if posIJ > posIK + posKY:
                    adjmat[i, j] = posIK + posKY  # <<<<< If I comment this line the error disappears
```

on a numpy array (5000,5000) filled by uint16:

```
threadsperblock = 32
sps = np.array(adjmat, copy=True, dtype=np.uint16)
blockspergrid = ceil(adjmat.shape[0] / threadsperblock )
mymethod[blockspergrid, threadsperblock](sps)
```

but I get these error messages (Windows 10):

```
2019-02-21 10:15:18,210 - ERROR - Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED
Traceback (most recent call last):
  File "myfile.py", line 106, in mymethod
    mymethod[blockspergrid, threadsperblock](sps)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\compiler.py", line 497, in __call__
    sharedmem=self.sharedmem)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\compiler.py", line 608, in _kernel_call
    wb()
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\args.py", line 65, in <lambda>
    retr.append(lambda: devary.copy_to_host(self.value, stream=stream))
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\cudadrv\devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 232, in copy_to_host
    _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1849, in device_to_host
    fn(host_pointer(dst), device_pointer(src), size, *varargs)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\cudadrv\driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\Programs\miniconda3\envs\my_env\lib\site-packages\numba\cuda\cudadrv\driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED
```

Can you help me understand where is the problem with this?

Info1: This same code seems to work for arrays smaller than 3000x3000
Info2: The error disappears if I reduce the number of iterations of the double for:

```
        for k in range(0, graph_size):  # works if at least k ranges from 0 to 2000 or equally between 1500 and 3500
            for j in range(0, graph_size): # or it works if at least j ranges from 0 to 2000 or equally between 1500 and 3500
```

Info3: My graphics card is an NVIDIA Quatro K2200

**Comment by stuartarchibald** [comment] 2020-09-11 08:11
Thanks for the report. Does this reproduce on a CUDA card with more memory?

**Comment by gmarkall** [comment] 2020-09-16 21:28
Closing this issue due to lack of further information.

**Closed by gmarkall** 2020-09-16 21:28 UTC
Labels: CUDA, needtriage
