### ISSUE TITLE
Measuring and Reducing Compilation Time

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6705] opened 2021-02-09 01:38 UTC
---

## Feature request

My request is for increased support for accurately measuring compilation time, especially with recursive compilation. Ideally then this support can promote exploration into optimizing/resolving some of the most time intensive compilation steps.

For context, I work on Bodo, which extends Numba with additional compiler passes, so that may have some impact on the results/structure. We have an example workload with a particularly long compilation time (about 840 seconds). This workload is recursive, so 1 jit function is called from Python (which then calls other functions/overloads).

When measuring the compilation time with the `get_metadata ` API, I consistently find that this reports nearly all of the time was spent in a single compilation step. In this particular example, the timing suggested about 812 seconds were all in one step. I believe this happens because of recursive compilation.

I wrote some code (that doesn't integrate well with Numba APIs) that measured the time spent in the innermost stage using a stack. I then got the following output (I omitted Bodo stages because I assume they aren't helpful for you):

```
[('native_lowering', 314.57641077041626),
 ('inline_overloads', 176.63214421272278),
 ('nopython_type_inference', 137.8588182926178),
 ('parfor_pass', 52.09694981575012),
 ('with_lifting', 11.543930768966675),
 ('translate_bytecode', 10.809510707855225),
 ('inline_closure_likes', 7.639027833938599),
 ('generic_rewrites', 6.4921369552612305),
 ('nopython_rewrites', 4.642915725708008),
 ('reconstruct_ssa', 2.3017282485961914),
 ('ir_legalization', 2.038928508758545),
 ('ir_processing', 1.9977760314941406),
 ('annotate_types', 1.214860200881958),
 ('strip_phis', 0.7356917858123779),
 ('extract_bytecode', 0.6492612361907959),
 ('dead_branch_prune', 0.5428316593170166),
 ('inline_inlinables', 0.4541161060333252),
 ('nopython_backend', 0.3151834011077881),
 ('find_literally', 0.27577829360961914),
 ('rewrite_semantic_constants', 0.25364184379577637),
 ('pre_parfor_pass', 0.23002982139587402),
 ('make_function_op_code_to_jit_function', 0.06714582443237305),
 ('literal_unroll', 0.06616687774658203),
 ('dump_parfor_diagnostics', 0.010275840759277344),
 ('object_mode_back_end', 0.00785374641418457),
 ('fixup_args', 0.006414651870727539),
 ('canonicalize_loop_entry', 0.0021800994873046875),
 ('canonicalize_loop_exit', 0.0015506744384765625),
 ('inline_pass', 0.001224517822265625),
 ('object_mode_front_end', 0.0003883838653564453),
 ```
 
 My feature request is to increase the monitoring tools for compilation time. I'm not sure how to best integrate a timing solution that can give more accurate results with recursive compilation (or some existing APIs can be repurposed), but I think this is an area that needs more intention.
 
In general, I feel this feature is important because I believe Numba could benefit from a focus on reducing compilation time. This data is from a fairly complex customer use case, so hopefully it offers some useful information about which compiler passes deserve attention for reducing compilation time.

**Comment by gmarkall** [comment] 2021-02-09 10:24
HI @njriasan,

Many thanks for the description of your situation and the feature request.

Does the recently-added Event API (https://numba.readthedocs.io/en/latest/developer/event_api.html) help towards building appropriate monitoring tools to satisfy the request?

> My feature request is to increase the monitoring tools for compilation time. I'm not sure how to best integrate a timing solution that can give more accurate results with recursive compilation (or some existing APIs can be repurposed), but I think this is an area that needs more intention.

It sounds like there is some design work to done to hammer out the details of this feature request. Although you're not sure how best to integrate a timing solution to meet your needs, did you have any options in mind that could be considered / compared?

> This data is from a fairly complex customer use case, so hopefully it offers some useful information about which compiler passes deserve attention for reducing compilation time.

Whilst the timing of the stages provides a data point, it's difficult to determine what might be done about these timings without some sort of reproducing workloads. Can you share any examples that result in long compilation times in these stages?

**Comment by esc** [comment] 2021-05-28 08:09
@njriasan we never heard back from you regarding this feature request. Is it still up to date? Should we relabel it?

**Comment by njriasan** [comment] 2021-06-15 16:20
> @njriasan we never heard back from you regarding this feature request. Is it still up to date? Should we relabel it?

Hi @esc I'm so sorry for the delay. Let me attempt to answer all of these question. I promise to be much more responsive in the future.


> Does the recently-added Event API (https://numba.readthedocs.io/en/latest/developer/event_api.html) help towards building appropriate monitoring tools to satisfy the request?

It may, but I wasn't able to get it to determine how to properly utilize it. Instead I have been measuring compilation time with this branch I have in my fork of Numba.  https://github.com/njriasan/numba/commit/647cd511e7781a76f38ab248bb0b90cf0b53ea94

This approach attempts to measure just the code that executes most often (using a stack), not why or how, so I suspect these measure different things.

> It sounds like there is some design work to done to hammer out the details of this feature request. Although you're not sure how best to integrate a timing solution to meet your needs, did you have any options in mind that could be considered / compared?

In general, I am interested in which pass/stages actually take the majority of the compilation time based solely on execution time. To clarify, this means I care for example if Typing Pass takes the most execution time, not if something is repeatedly calling typing pass. While there is definitely a benefit to a more holistic perspective, I am most interesting in determining which operations could benefit heavily from optimizing small code sections for performance (i.e. Cython, more efficient lookups, etc). Since I work primarily on Bodo, I believe this focus will benefit everyone (Numba users and Numba extenders). Of course there will be some differences depending on how various systems extend Numba, but hopefully we can find common performance bottlenecks that will benefit all parties.

> Whilst the timing of the stages provides a data point, it's difficult to determine what might be done about these timings without some sort of reproducing workloads. Can you share any examples that result in long compilation times in these stages?

I can't share this particular example, but I will work on getting an open source example that we can measure and share. I will post an update once I have that workload. My use cases thus far are used in the context of Bodo (where I omit the timing for Bodo specific stages), but I'm happy to measure any entirely Numba examples that you would like me to look into.

**Comment by njriasan** [comment] 2021-06-15 17:06
While I work on getting you an open source example, here are the most recent numbers (on 0.53) from the previous example as a data point.

```python
[('native_lowering', 317.36560754999954),
2 ('inline_overloads', 58.80339191200005),
3 ('nopython_type_inference', 55.03850852400054),
4 ('parfor_pass', 23.784161222000133),
5 ('with_lifting', 16.120010197997495),
6 ('generic_rewrites', 6.224673418999933),
7 ('translate_bytecode', 4.861178477001117),
8 ('nopython_rewrites', 4.561195371001502),
9 ('reconstruct_ssa', 3.2992141819996212),
10 ('inline_closure_likes', 2.6615422209982884),
11 ('ir_legalization', 1.864845463000154),
12 ('object_mode_back_end', 1.7452293039997344),
13 ('annotate_types', 1.4941058520000223),
14 ('strip_phis', 1.2683525030002243),
15 ('ir_processing', 0.9601891440012928),
16 ('nopython_backend', 0.7436169680005738),
17 ('dead_branch_prune', 0.39011038000104437),
18 ('extract_bytecode', 0.3317051069987871),
19 ('pre_parfor_pass', 0.30471266999995095),
20 ('inline_inlinables', 0.23817040900011888),
21 ('rewrite_semantic_constants', 0.13746499500021825),
22 ('find_literally', 0.1367563360001749),
23 ('make_function_op_code_to_jit_function', 0.046920967999709795),
24 ('literal_unroll', 0.036441746999404945),
25 ('dump_parfor_diagnostics', 0.021880738998544924),
26 ('fixup_args', 0.008968003000406455),
27 ('canonicalize_loop_entry', 0.00085593499986647),
28 ('canonicalize_loop_exit', 0.0006288149998656678),
29 ('inline_pass', 0.0003442299999392162),
30 ('object_mode_front_end', 0.00014755600003324432)]
```

**Comment by stuartarchibald** [comment] 2022-07-08 17:19
@njriasan can this be closed or should this be kept open with an example of what is a challenge to trace with the existing event API etc?

**Comment by stuartarchibald** [comment] 2022-08-15 14:26
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2022-08-15 14:26 UTC
Labels: feature_request, more info needed
