### ISSUE TITLE
BUG: enumerate over 2d numpy array

### ISSUE THREAD

**Issue by devonkinghorn** [numba/numba#3300] opened 2018-09-10 14:46 UTC
I have a jupyter notebook with a knn to predict the iris dataset. I get an error. That told me to post an issue here.
```
File "<ipython-input-31-092d45d72efa>", line 18:
def get_distances(x, train_data):
    <source elided>
    distances = np.zeros(train_data.shape[0], dtype=np.float64)
    for i, row in enumerate(train_data):
    ^
[1] During: lowering "$32.2 = iternext(value=$phi32.1)" at <ipython-input-31-092d45d72efa> (18)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

Here is all of the code in different cells

```bash
%%bash
mkdir -p ../.data
cd ../.data
if [ ! -f iris.data.txt ]; then
    echo "File not found. Downloading from github"
    wget -q https://raw.githubusercontent.com/WinVector/Logistic/master/iris.data.txt
else
    echo "File exists, not downloading form github"
fi
```

```python
import numpy as np
import pandas as pd
import random

def read_iris_data():
    data = pd.read_csv('../.data/iris.data.txt').values
    np.random.shuffle(data)
    return data[:,0:4], data[:,4]

X, Y = read_iris_data()
X = X.astype('float64')
x_train = X[:120]
y_train = Y[:120]
x_test = X[120:]
y_test = Y[120:]
```

```python
class Runner():
    def __init__(self, model):
        self.model = model
        model.train(x_train, y_train)

    def test(self):
        correct = 0
        incorrect = 0
        for x, y in zip(x_test, y_test):
            if self.model.predict(x) == y:
                correct += 1
            else:
                incorrect += 1
        return correct, incorrect
```

```python
from collections import Counter
from heapq import nsmallest

import numpy as np
from numba import njit


@njit
def sum(x):
    s = 0
    for i in range(x.shape[0]):
        s += x[i]
    return s

@njit
def get_distances(x, train_data):
    distances = np.zeros(train_data.shape[0], dtype=np.float64)
    for i, row in enumerate(train_data):
        s = 0
        for j in range(row.shape[0]):
            s += (x[j] - row[j])**2
        distances[i] = s
    return distances


class KNN_Numba:
    def __init__(self, k=5):
        self.k = k
        self.train_data = None
        self.labels = None
        self.label_conversion = None


    def _transform_labels_to_int(self, labels):
        self.label_conversion = { 
           i: label for i, label in enumerate(set(labels))
        }
        label_to_index = {label: index for index, label in self.label_conversion.items()}
        self.labels = np.array([label_to_index[l] for l in labels], dtype=np.float32)


    def train(self, train_data, labels):
        self.train_data = train_data
        self._transform_labels_to_int(labels)
        self.max_values = np.amax(np.absolute(self.train_data), axis=0)

    
    def _get_distances(self, data):
        distances = data - self.train_data
        absolute_distances = distances**2
        return np.sum(absolute_distances, axis=1)
    
    def predict(self, data):
#         distances = self._get_distances(data)
        distances = get_distances(data, self.train_data)
        
        partition = np.argpartition(distances, 5)
        kclosest = self.labels[partition[0 : self.k]]
        return self.label_conversion[Counter(kclosest).most_common(1)[0][0]]
```

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    576     try:
--> 577         yield
    578     except NumbaError as e:

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_inst(self, inst)
    302             ty = self.typeof(inst.target.name)
--> 303             val = self.lower_assign(ty, inst)
    304             self.storevar(val, inst.target.name)

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_assign(self, ty, inst)
    448         elif isinstance(value, ir.Expr):
--> 449             return self.lower_expr(ty, value)
    450 

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_expr(self, resty, expr)
    804             castval = self.context.cast(self.builder, val, ty, fty)
--> 805             res = impl(self.builder, (castval,))
    806             res = self.context.cast(self.builder, res, signature.return_type,

/usr/local/lib/python3.6/site-packages/numba/targets/base.py in __call__(self, builder, args)
   1078     def __call__(self, builder, args):
-> 1079         return self._imp(self._context, builder, self._sig, args)
   1080 

/usr/local/lib/python3.6/site-packages/numba/targets/imputils.py in wrapper(context, builder, sig, args)
    310         func(context, builder, sig, args,
--> 311              _IternextResult(context, builder, pairobj))
    312         return impl_ret_borrowed(context, builder,

/usr/local/lib/python3.6/site-packages/numba/targets/iterators.py in iternext_enumerate(context, builder, sig, args, result)
     57 
---> 58     srcres = call_iternext(context, builder, enumty.source_type, enum.iter)
     59     is_valid = srcres.is_valid()

/usr/local/lib/python3.6/site-packages/numba/targets/imputils.py in call_iternext(context, builder, iterator_type, val)
    336     iternext_impl = context.get_function('iternext', iternext_sig)
--> 337     val = iternext_impl(builder, (val,))
    338     pairobj = context.make_helper(builder, pair_type, val)

/usr/local/lib/python3.6/site-packages/numba/targets/base.py in __call__(self, builder, args)
   1078     def __call__(self, builder, args):
-> 1079         return self._imp(self._context, builder, self._sig, args)
   1080 

/usr/local/lib/python3.6/site-packages/numba/targets/imputils.py in wrapper(context, builder, sig, args)
    310         func(context, builder, sig, args,
--> 311              _IternextResult(context, builder, pairobj))
    312         return impl_ret_borrowed(context, builder,

/usr/local/lib/python3.6/site-packages/numba/targets/arrayobj.py in iternext_array(context, builder, sig, args, result)
    286         # TODO
--> 287         raise NotImplementedError("iterating over %dD array" % arrayty.ndim)
    288 

NotImplementedError: iterating over 2D array

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-32-d6c178c3b4af> in <module>()
      1 knn = KNN_Numba()
      2 runner = Runner(knn)
----> 3 correct, incorrect = runner.test()
      4 print(correct, incorrect)
      5 get_ipython().run_line_magic('timeit', 'runner.test()')

<ipython-input-3-82dce329cbe9> in test(self)
      8         incorrect = 0
      9         for x, y in zip(x_test, y_test):
---> 10             if self.model.predict(x) == y:
     11                 correct += 1
     12             else:

<ipython-input-31-092d45d72efa> in predict(self, data)
     53     def predict(self, data):
     54 #         distances = self._get_distances(data)
---> 55         distances = get_distances(data, self.train_data)
     56 
     57         partition = np.argpartition(distances, 5)

/usr/local/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    366                     e.patch_message(''.join(e.args) + help_msg)
    367             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 368             raise e
    369 
    370     def inspect_llvm(self, signature=None):

/usr/local/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    323                 argtypes.append(self.typeof_pyval(a))
    324         try:
--> 325             return self.compile(tuple(argtypes))
    326         except errors.TypingError as e:
    327             # Intercept typing error that may be due to an argument

/usr/local/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    651 
    652                 self._cache_misses[sig] += 1
--> 653                 cres = self._compiler.compile(args, return_type)
    654                 self.add_overload(cres)
    655                 self._cache.save_overload(sig, cres)

/usr/local/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

/usr/local/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    871     pipeline = pipeline_class(typingctx, targetctx, library,
    872                               args, return_type, flags, locals)
--> 873     return pipeline.compile_extra(func)
    874 
    875 

/usr/local/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    365         self.lifted = ()
    366         self.lifted_from = None
--> 367         return self._compile_bytecode()
    368 
    369     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/usr/local/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    802         """
    803         assert self.func_ir is None
--> 804         return self._compile_core()
    805 
    806     def _compile_ir(self):

/usr/local/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    789         self.define_pipelines(pm)
    790         pm.finalize()
--> 791         res = pm.run(self.status)
    792         if res is not None:
    793             # Early pipeline completion

/usr/local/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

/usr/local/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event(stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

/usr/local/lib/python3.6/site-packages/numba/compiler.py in stage_nopython_backend(self)
    676         """
    677         lowerfn = self.backend_nopython_mode
--> 678         self._backend(lowerfn, objectmode=False)
    679 
    680     def stage_compile_interp_mode(self):

/usr/local/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    626             self.library.enable_object_caching()
    627 
--> 628         lowered = lowerfn()
    629         signature = typing.signature(self.return_type, *self.args)
    630         self.cr = compile_result(

/usr/local/lib/python3.6/site-packages/numba/compiler.py in backend_nopython_mode(self)
    613                 self.return_type,
    614                 self.calltypes,
--> 615                 self.flags)
    616 
    617     def _backend(self, lowerfn, objectmode):

/usr/local/lib/python3.6/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags)
    990 
    991     lower = lowering.Lower(targetctx, library, fndesc, interp)
--> 992     lower.lower()
    993     if not flags.no_cpython_wrapper:
    994         lower.create_cpython_wrapper(flags.release_gil)

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215 
    216         # Close tail of entry block

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240 
    241         self.post_lower()

/usr/local/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 
    256     def create_cpython_wrapper(self, release_gil=False):

/usr/local/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/usr/local/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    583         from numba import config
    584         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 585         six.reraise(type(newerr), newerr, tb)
    586 
    587 

/usr/local/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed at nopython (nopython mode backend)
iterating over 2D array

File "<ipython-input-31-092d45d72efa>", line 18:
def get_distances(x, train_data):
    <source elided>
    distances = np.zeros(train_data.shape[0], dtype=np.float64)
    for i, row in enumerate(train_data):
    ^
[1] During: lowering "$32.2 = iternext(value=$phi32.1)" at <ipython-input-31-092d45d72efa> (18)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment] 2018-09-28 08:58
Thanks for the report, this is a minimal reproducer:
```python
from numba import njit
import numpy as np
@njit
def foo(a):
    for i, l in enumerate(a):
        z = np.cos(l) + i
    return z
x = np.arange(20.).reshape((5, 4))
print(foo(x))
```
As the error suggests, iterating by dimension over N-D arrays is not implemented yet, this is a duplicate of the issue https://github.com/numba/numba/issues/3111, the comments there have a couple of suggestions for workarounds.

**Comment by user2589** [comment] 2018-10-09 19:57
@devonkinghorn,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: 
https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/numba/numba/issues/3300

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!

**Comment by stuartarchibald** [comment] 2021-12-15 14:06
Closing as per: https://github.com/numba/numba/issues/3111#issuecomment-994811642

**Closed by stuartarchibald** 2021-12-15 14:06 UTC
Labels: duplicate, feature_request
