### ISSUE TITLE
Numba 0.53.0rc2 function-as-argument caching fails some of the time

### ISSUE THREAD

**Issue by CalebBell** [numba/numba#6772] opened 2021-02-27 19:54 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba
- [x] I have included a self contained code sample to reproduce the problem.

I really love the function specialization new feature in numba 0.53! The performance gains for me are unreal, and it also offers an insane level of flexibility compared to the previous versions of numba.

I have found a case where it appears to fail for mysterious reasons however. The following case is brenth's method on a basic objective function, and the caching does not work:

```
import numba

@numba.njit(cache=True)
def brenth(f, xa, xb, args=()):
    xpre = xa
    xcur = xb
    xblk = 0.0
    fblk = 0.0
    spre = 0.0
    scur = 0.0

    fpre = f(xpre, *args)
    fcur = f(xcur, *args)

    if fpre*fcur > 0.0:
        return 0.0

    for i in range(100):
        if fpre*fcur < 0.0:
            xblk = xpre
            fblk = fpre
            spre = scur = xcur - xpre
        if abs(fblk) < abs(fcur):
            xpre = xcur
            xcur = xblk
            xblk = xpre

            fpre = fcur
            fcur = fblk
            fblk = fpre

        delta = 0.5*(1e-12 + 4.440892098500626e-16*abs(xcur))
        sbis = 0.5*(xblk - xcur)

        if fcur == 0.0 or ((abs(sbis) < delta) and abs(fcur) < 1e100):
            return xcur

        if (abs(spre) > delta and abs(fcur) < abs(fpre)):
            if xpre == xblk:
                # interpolate
                stry = -fcur*(xcur - xpre)/(fcur - fpre)
            else:
                # extrapolate
                dpre = (fpre - fcur)/(xpre - xcur)
                dblk = (fblk - fcur)/(xblk - xcur)
                stry = -fcur*(fblk - fpre)/(fblk*dpre - fpre*dblk)
            
            
            lval = abs(spre) if abs(spre) < 3.0*abs(sbis) - delta else 3.0*abs(sbis) - delta
            if (abs(stry + stry) < lval):
                # accept step
                spre = scur
                scur = stry
            else:
                # bisect
                spre = sbis
                scur = sbis
        else:
            # bisect
            spre = sbis
            scur = sbis

        xpre = xcur
        fpre = fcur
        if abs(scur) > delta:
            xcur += scur
        else:
            if sbis > 0.0:
                xcur += delta
            else:
                xcur -= delta

        fcur = f(xcur, *args)
    return 0.0

@numba.njit(cache=True)
def to_solve(x, y):
    return 10.001*x*x - 2.2*x - y

@numba.njit(cache=True)
def my_solve(y):
    return brenth(to_solve, -1.0, 1.0, args=(y,))

print(my_solve(10.0))
```

I apologize for the lengthiness of the example, but there isn't much that can be taken away. I didn't run into any problems with bisection, and I also noticed that if following two lines are moved the function is cached.

```
    if fpre*fcur > 0.0:
        return 0.0
```

If the following statement is also removed, the function is cached: ```and abs(fcur) < 1e100```

I compared the debug output between the case with ```and abs(fcur) < 1e100``` and without it and the output was almost identical. I also did tried using cProfile to trace the function calls, and the output was also almost identical between the two cases. Thank you all for all of your extremely hard work on numba. Compilers are really hard!

The [full debug output](https://github.com/numba/numba/files/6055275/full_output.txt) is attached as it was too long to be part of this comment.

**Comment by CalebBell** [comment] 2021-02-27 21:06
The following code ([full output](https://github.com/numba/numba/files/6055387/full_output.txt)  also too long) is slightly more concise and demonstrate the secant method and also has the error, which I'm guessing is the same root cause:

```
import numba

@numba.njit(cache=True)
def secant(func, x0, args=()):
    p0 = x0
    p1 = x0*0.9999

    q0 = func(p0, *args)
    q1 = func(p1, *args)

    for i in range(100):
        # Calculate new point
        p = p1 - q1*(p1 - p0)/(q1 - q0)

        # Check the exit conditions
        if (abs(p0 - p1) <= abs(1e-9*p0)):
            return p
        # Swap the points around
        p0 = p1
        q0 = q1
        p1 = p
        q1 = func(p1, *args)
    return 0.0

@numba.njit(cache=True)
def to_solve(x, y):
    # The following two lines exist explicitly to prevent the compiler from inling the function
    # They have a negligible impact on the result
    for i in range(100): 
        x += 1e-15*x
    return 10.001*x*x - 2.2*x - y

@numba.njit(cache=True)
def my_solve(y):
    return secant(to_solve, 5.0, args=(y,))

print(my_solve(10.0))


```

**Comment by stuartarchibald** [comment] 2021-03-01 13:34
Thanks for the report @CalebBell. Is this a regression? It seems like 0.52 did the same thing (it's because a function is being passed as an argument).

**Comment by CalebBell** [comment] 2021-03-01 14:20
@stuartarchibald This is not a regression! However, it was my understanding that there was a PR to make this functionality work in 0.53 - https://github.com/numba/numba/issues/6251 - and I am reporting the bug because it seems the feature isn't complete.

**Comment by CalebBell** [comment] 2021-03-02 04:29
I have kept trying to find some solution here, debugging with several tools, and I really don't think the difference is happening at the numba level; the Python source code being ran is identical until it turns out there are global references and so the function cannot be cached. My suspicion is that because such small changes lead to the caching failing, and the change is always making the function more complex, *the difference is whether LLVM is inlining a function or not*. Here is a screenshot of the comparison (I was looking at everything Numba was doing with a tool called [pysnooper](https://github.com/cool-RR/PySnooper)):
![image](https://user-images.githubusercontent.com/16520296/109597084-c4e61300-7ad4-11eb-8915-5934690242a5.png)

Also seeming to confirm this is that if I add inline='always' to the numerical solver routines, 'brenth' or 'secant', there is no problem caching no matter how complex the case. Unfortunately I find that providing any value to the 'inline' argument results in very compilation/setup, regardless of whether the function is cached or not, well outweighing any benefits from the caching.
It is nice to look at numba's internals though!

**Comment by stuartarchibald** [comment] 2021-03-02 14:33
@CalebBell do you have an example of something that caches with the behaviour you want, and then you modify the function and it now won't cache?

**Comment by CalebBell** [comment] 2021-03-02 14:38
I have been able to slightly tweak the objective function in the secant example such that adding/removing a single multiplication is the difference between caching working and not. Change `x*y*x` to `x*y` to make this function successfully cache!

```
import numba
from math import sqrt

@numba.njit(cache=True)
def secant(func, x0, args=()):
    p0 = x0
    p1 = x0*0.9999

    q0 = func(p0, *args)
    q1 = func(p1, *args)

    for i in range(100):
        # Calculate new point
        p = p1 - q1*(p1 - p0)/(q1 - q0)

        # Check the exit conditions
        if (abs(p0 - p1) <= abs(1e-9*p0)):
            return p
        # Swap the points around
        p0 = p1
        q0 = q1
        p1 = p
        q1 = func(p1, *args)
    return 0.0

@numba.njit(cache=True)
def to_solve(x, y):
    sln = 0.0
    sln += 10.001*x*x - 2.2*x - y 
    # Change x*y*x to x*y to make this function cache
    sln -= (x*y*x - sqrt(x))*1e-40/x**2.5/sqrt(x**2.5)
    return sln

@numba.njit(cache=True)
def my_solve(y):
    return secant(to_solve, 5.0, args=(y,))

print((my_solve(10.0)))

```

**Comment by stuartarchibald** [comment] 2021-03-02 15:11
@CalebBell thanks. Yes, this is the LLVM level inliner. You can watch what it's up to by setting this:
```
from llvmlite import binding as llvm
llvm.set_option('','--debug-only=inline')
```
in the one that caches, there's this:
```
Inliner visiting SCC: _ZN8__main__12my_solve$241Ed: 1 call sites.
    Inlining (cost=260, threshold=275), Call:   %.36 = call i32 @"_ZN8__main__10secant$242E76type$28CPUDispatcher$28$3cfunction$20to_solve$20at$200x7f24b852c4c0$3e$29$29d8UniTupleIdLi1EE"(double* nonnull %.31, { i8*, i32, i8* }** nonnull %excinfo.1, i8* %.12, double 5.000000e+00, double %arg.y)
```
i.e. cost of inlining the secant function into the solve itself is under the threshold, so it does it.
Whereas in the one that refuses to cache, there's this:
```
Inliner visiting SCC: _ZN8__main__12my_solve$241Ed: 1 call sites.
    NOT Inlining (cost=275, threshold=275), Call:   %.36 = call i32 @"_ZN8__main__10secant$242E76type$28CPUDispatcher$28$3cfunction$20to_solve$20at$200x7facf29bd4c0$3e$29$29d8UniTupleIdLi1EE"(double* nonnull %.31, { i8*, i32, i8* }** nonnull %excinfo.1, i8* %.12, double 5.000000e+00, double %arg.y)
```
i.e. cost >= threshold so don't inline.

I'm not sure there's much that can be done to force caching for this case at present.

**Comment by CalebBell** [comment] 2021-03-03 05:51
Thank you for looking into this! I found the constants numba uses at https://github.com/numba/llvmlite/blob/e146c676a9f840dbdf65d73c52fcf810d830bb98/llvmlite/llvmpy/passes.py#L17 for different levels and confirmed that more functions can be inlined by changing those constants.

Would the numba project be open to exposing this parameter, maybe as an environmental variable like  NUMBA_LOOP_VECTORIZE? The code is pretty simple e.g. in https://github.com/numba/numba/blob/1976c664afeb3251bc1246957c4735b1694f84f4/numba/core/codegen.py#L1181 and llvmlite and I would be very happy to write a PR.

**Comment by stuartarchibald** [comment] 2021-03-03 10:11
> Thank you for looking into this!

No problem, glad it's resolved.

RE:
> environmental variable like NUMBA_LOOP_VECTORIZE?

I think this particular env var is a historical artifact to work around https://github.com/numba/numba/issues/649, which I'm not even sure would be a bug any more given it's related to LLVM < 3.5!


RE: 
> Would the numba project be open to exposing this parameter

I think that exposing more configuration for optimisation is something Numba needs to do. The main issues with it are the giant number of flags and options on these flags, the combinations of these flags and options, and then further that LLVM passes can be run in any order and that being another set of configurable things. Environment variables might struggle to capture this, so it might need to be a combination of environment variables and a way to customise compiler options programmatically. Perhaps open an issue to discuss?

**Comment by hgrecco** [comment] 2021-04-13 02:01
@stuartarchibald Would it be posible to tell the compiler to never inline functions when an explicit `FunctionType` signature is provided? For example:

```python
import numba as nb
from numba import float64, types

func_sig = types.FunctionType(float64(float64))

@nb.njit(float64(func_sig, float64))
def step(func, x):
    # I keep it simple here for demonstration purposes
    # but this function could be as complex as required
    # by the algorithm.
    return func(x)
```

`func` will never be inlined inside `step` therefore allowing to compile and cache `step`.

**Comment by stuartarchibald** [comment] 2022-07-08 17:16
Am going to close this as #6972 contains a broader discussion on this along with examples. Thanks for the input @CalebBell @hgrecco.

**Closed by stuartarchibald** 2022-07-08 17:16 UTC
Labels: no action required
