### ISSUE TITLE
JIT Error: Cannot determine Numba type of... Taking screenshots with GPU.

### ISSUE THREAD

**Issue by Enebz** [numba/numba#6509] opened 2020-11-19 22:59 UTC
I want to take screenshots in a while True loop which is threaded extremely fast using GPU.
I am sending the data to all clients with WebSockets.

When I am using numba jit, I get an error: Untyped global name 'BytesIO': cannot determine Numba type of <class 'type'>
The same with all other functions I am using inside the loop. How can I accomplish what I want?

```python
@jit(nopython=True)
def Update():
    global clients
    sct = mss()
    while True:
        try:
            buffered = BytesIO()
            image = sct.grab(sct.monitors[0])
            img = Image.frombytes("RGB", image.size, image.bgra, "raw", "BGRX")
            img.save(buffered, format="JPEG")
            for client in clients:
                client.sendMessage(buffered.getvalue())
        except OSError:
            pass
```

**Comment by esc** [comment] 2020-11-20 08:38
@Enebz thank you for asking about this on the Numba issue tracker. Unfortunately you have not included a fully runnable reproducer as the imports are missing. So, for example I don't know what `mss` is in this case. Anyway, my guess is that you are trying to jit-compile objects that Numba does not understand. For example, there is currently no support for `BytesIO` -- which is probably why you are seeing the error message above.

**Comment by Enebz** [comment] 2020-11-22 01:10
Where can I find what is supported with Numba?

**Comment by gmarkall** [comment] 2020-11-23 10:15
In the documentation:

- [Supported Python features](https://numba.readthedocs.io/en/stable/reference/pysupported.html)
- [Supported NumPy features](https://numba.readthedocs.io/en/stable/reference/numpysupported.html)
- [Deviations from Python semantics](https://numba.readthedocs.io/en/stable/reference/pysemantics.html)

**Comment by esc** [comment] 2020-11-23 15:18
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. @Enebz many thanks again for using Numba.

**Closed by esc** 2020-11-23 15:18 UTC
Labels: needtriage
