### ISSUE TITLE
LoweringError in nopython mode pipeline from `[[y], [0]]`

### ISSUE THREAD

**Issue by 1fish2** [numba/numba#4082] opened 2019-05-13 22:57 UTC
Numba is very useful and impressive but it raises a `LoweringError` in some cases.

**Goal:** Numba-compile a matrix expression.

We're using Sympy to construct a symbolic matrix and in some cases compute a Jacobian of the matrix, then using that to construct and `eval` code that looks like  

    lambda y, t: np.array([[-100000000.0*y[6]**1.0, …], …, […]])

then calling `numba.njit()` on the lambda value. This lambda doesn't close over any local variables. It's built via `eval(code, {'np': np}, {})`, given the conventional `import numpy as np`.

I boiled it down to a simple non-matrix failure case, below, and commented on a small variation that doesn't raise an exception but in practice I can't use that as a workaround without somehow replaces integer literals with floats in matrix elements but not in array indexes.

Also, calling `numba.jit()` on the actual matrix expression gets stuck, running longer than I was willing to wait for it, so that won't work as a workaround, either.

Thanks!

**Operating system:** macOS Mojave 10.14.4.
**Python:** 2.7.16
**pip numba:** 0.43.1
**pip llvmlite:** 0.28.0

**Minimal reproducible test case:**

```
from __future__ import absolute_import
from numba import njit

def numba_stress(y):
	return [[y], [0]]  # will cause LoweringError
	# return [[y], [0.0]]  # won't cause LoweringError

def test():
	y = 100.0
	numba_stress_jit = njit(numba_stress)
	r1 = numba_stress(y)
	r2 = numba_stress_jit(y)  # <-- raises LoweringError
	assert r1 == r2

test()
```

**Stack traceback and error message:**

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/wcEcoli2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-765ea0969bed>", line 1, in <module>
    runfile('user.numba_test', wdir='/Users/jerry/dev/wcEcoli', is_module=True)
  File "/Users/jerry/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 210, in runfile
    runpy._run_module_as_main(module_name)
  File "/usr/local/var/pyenv/versions/2.7.16/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/var/pyenv/versions/2.7.16/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jerry/dev/wcEcoli/user/numba_test.py", line 15, in <module>
    test()
  File "/Users/jerry/dev/wcEcoli/user/numba_test.py", line 12, in test
    r2 = numba_stress_jit(y)  # <-- raises LoweringError
  File "/usr/local/var/pyenv/versions/2.7.16/envs/wcEcoli2/lib/python2.7/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "user/numba_test.py", line 5:
def numba_stress(y):
	return [[y], [0]]  # will cause LoweringError
 ^

[1] During: lowering "$0.5 = build_list(items=[Var($0.2, /Users/jerry/dev/wcEcoli/user/numba_test.py (5)), Var($0.4, /Users/jerry/dev/wcEcoli/user/numba_test.py (5))])" at /Users/jerry/dev/wcEcoli/user/numba_test.py (5)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by 1fish2** [comment] 2019-05-13 23:10
BTW commenting out the `from __future__ import absolute_import` makes the test case raise a `ValueError` during `from numba import njit`:

```
  File "/Users/jerry/dev/wcEcoli/user/numba_test.py", line 4, in <module>
    from numba import njit
  File "/Users/jerry/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ValueError: __package__ set to non-string
```

**Comment by stuartarchibald** [comment] 2019-05-14 08:44
Thanks for the report. The issue you are seeing is because the global `y` is a `float` type and this is causing lists of mixed types to be used in a nested list. Lists have to be of homogeneous type i.e. "list of integers" or "list of complex128", in this particular case there is:
```
[[y], [0]] # list of (list of float) (list of int)
```
which fails, because `list of float` != `list of int`, i.e. list is heterogeneous. Then there is:
```
[[y], [0.0]] # list of (list of float) (list of float)
```
which works fine as the list is homogeneous with all elements being type "list of float".

This is another demonstration of the problem, without the use of a global:
```python
from numba import njit

def heterogeneous_list():
    x = [1]
    y = [1j]
    z = [x, y]

njit(heterogeneous_list)()
```

As this ticket is fundamentally a duplicate of https://github.com/numba/numba/issues/3818 I'm going to close it.

**Closed by stuartarchibald** 2019-05-14 08:44 UTC

**Comment by stuartarchibald** [comment] 2019-05-14 08:45
RE:
> BTW commenting out the from __future__ import absolute_import makes the test case raise a ValueError during from numba import njit:

I'm not sure what the issue is here but if you can isolate it please open another ticket with a reproducer, thanks. Locally I see:
```
$ python -c 'import numba; print(numba.__package__)'
numba
```
so am wondering if it's IDE configuration/setup related.

**Comment by 1fish2** [comment] 2019-05-15 08:47
Indeed, modifying the PyCharm "Run/Debug Configuration" to uncheck "Run with Python console" (which apparently means iPython) and/or switch from running a "Module name" to a "Script path" fixes the import problem `ValueError: __package__ set to non-string`. Running from a terminal window doesn't hit that problem, either.

Thanks for your help.

**Comment by stuartarchibald** [comment] 2019-05-15 17:44
@1fish2 thanks for reporting that you've got it working, glad to hear it! Thanks for using Numba :)
