### ISSUE TITLE
NotImplementedError followed by LoweringError

### ISSUE THREAD

**Issue by christinekaush** [numba/numba#3439] opened 2018-10-24 07:55 UTC
I got this error message:

     LoweringError: Failed at object (object mode backend)
     make_function(name=$const0.31, code=<code object <listcomp> at 0x7f8da9c439c0, file "<ipython- 
     input-13-d32eb8727d1e>", line 103>, closure=$0.29, defaults=None)

     File "<ipython-input-13-d32eb8727d1e>", line 103:
         def make_results(self, Xtest_vect, ytest):
             <source elided>
        
             relativ = pd.DataFrame([proba.loc[row].sort_values()[-2:][1]/proba.loc[row].sort_values()[-2:][0] for row in proba.index], index= ytest.index, columns=["Relativ"])
        ^
     [1] During: lowering "$0.32 = make_function(name=$const0.31, code=<code object <listcomp> at 0x7f8da9c439c0, file "<ipython-input-13-d32eb8727d1e>", line 103>, closure=$0.29, defaults=None)" at <ipython-input-13-d32eb8727d1e> (103)
     -------------------------------------------------------------------------------
     This should not have happened, a problem has occurred in Numba's internals._

The code I am running (within a class):

     @jit
     def degree_error(self, preds, ytest):
             error_deg = []
             for pred, real in zip(preds.values, ytest.values):
                 if pred != real:
                     for ind, val in enumerate(pred[0]):
                         if val != real[0][ind]:
                             error_deg.append(8-ind)
                             break
                         else:
                             continue
                 else:
                     error_deg.append(0)
                     continue
                
             return pd.DataFrame(error_deg, index=ytest.index, columns=['Grad av feil'])

     @jit
     def make_results(self, preds, virkelig):
          error_deg = self.degree_error(preds, virkelig)

Are there issues because of my code or is this something you can fix?

**numba version: 0.39.0**

**Comment by stuartarchibald** [comment] 2018-10-24 11:30
Thanks for the report. Without a functioning reproducer it is hard to ascertain precisely what went wrong. However, speculating... It seems like the code is returning or creating a function in a manner that Numba cannot handle (`make_function` op code in use). Numba 0.40 has some diagnostics added that catch cases it cannot handle and report to the user as such. Perhaps upgrade your Numba installation to obtain better reporting, also there were also some really important fixes in liveness analysis for `@jit` in 0.40, without them those bugs might also be contributing to the problem reported.

For your specific code, it looks like there are sections of pure algorithmic code and then things like Pandas DataFrame creation. Numba will do a whole lot better performance wise if you can compile the algorithmic part under `@jit(nopython=True)` and then just pass the result to e.g. Pandas. The [5 minute guide to Numba](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) is a good place to start for working out how to design your code so Numba can really help, then perhaps take a look at [performance tips](http://numba.pydata.org/numba-doc/latest/user/performance-tips.html).

Hope this helps.

**Comment by stuartarchibald** [comment] 2020-09-14 17:18
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-09-14 17:18 UTC
Labels: question
