### ISSUE TITLE
raising Exceptions in inlined functions fails on compile

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#4693] opened 2019-10-11 13:04 UTC
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

0.46.0

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The below:

```python

from numba import njit, generated_jit
from numba import types
import numpy as np


@njit(inline='always')
def inlining(array):
    if array.ndim != 1:
        raise ValueError("Invalid number of dimensions")

    return array

@njit
def fn(array):
    return inlining(array)

print(fn(np.zeros(10)))
```

fails with

```traceback
Traceback (most recent call last):
  File "test_inlining_generated_jit.py", line 19, in <module>
    print(fn(np.zeros(10)))
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: nopython frontend)
Unsupported constraint encountered: raise $10.3.7

File "test_inlining_generated_jit.py", line 9:
def inlining(array):
    <source elided>
    if array.ndim != 1:
        raise ValueError("Invalid number of dimensions")
        ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
```

but succeeds when `inline='never'`

**Comment by stuartarchibald** [comment] 2019-10-11 13:23
Thanks for the report, I can reproduce. It may not look like it, but it's the same root cause as this https://github.com/numba/numba/issues/4691.

**Comment by stuartarchibald** [comment] 2019-10-11 13:24
Also, out of interest. What's the use case for this inlining?

**Comment by sjperkins** [comment] 2019-10-11 13:28
@stuartarchibald I have a very flexible function that is composed out of many smaller functions.

https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/averaging/time_and_channel_avg.py

In some of the small functions (that I wish to inline) there are some checks that raise exceptions. For e.g. here https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/averaging/time_and_channel_mapping.py#L39-L52

**Comment by stuartarchibald** [comment] 2019-10-11 13:31
I see, but why do you want to inline them? What is the purpose of the inlining?

**Comment by sjperkins** [comment] 2019-10-11 13:37
Essentially i'm supporting an averaging function which supports the absence/presence of certain inputs. The following pseudo-code illustrates the intent by accumulation:

```
for r in range(rows):
   for f in range(chans):
       for c in range(corrs):
           if array is None:
               pass
           else:
               avg_array[r, f, c] += array[r, f, c]
```

The inline functions serve to replace the if-else statement with an implementation (if array is an ndarray) or a noop (if array is None).

I could of course place the if statement outside the loops, but I've multiple input arrays to average that may or may not be present.

**Comment by stuartarchibald** [comment] 2019-10-11 13:50
Thanks, I'm wondering what the purpose is? Are you perhaps hoping for better performance? Is this a type-inference problem? Is this helping with code organisation?

**Comment by sjperkins** [comment] 2019-10-11 13:54
> Thanks, I'm wondering what the purpose is? Are you perhaps hoping for better performance? Is this a type-inference problem? Is this helping with code organisation?

I'd say its a combination of:

1. Performance (inline function calls in the inner loop)
2. Flexibility in handling inputs (provide different inlined implementations, depending on the presence/absence of inputs)

I'm less concerned about code organisation (although I'd welcome tips on how to improve it!)

**Comment by stuartarchibald** [comment] 2019-10-11 14:14
> > Thanks, I'm wondering what the purpose is? Are you perhaps hoping for better performance? Is this a type-inference problem? Is this helping with code organisation?
> 
> I'd say its a combination of:
> 
>     1. Performance (inline function calls in the inner loop)

I'd say that this is unlikely to have any impact on performance for two reasons.
1. There's an optimisation pass in Numba called "branch pruning" that looks for `if <something that can be determined as True/False>` and kills off branches that are dead. Doing `if X is None` where `X` is a kwarg which defaults to `None` will be subject to consideration by this pass.
2. This is inlining at the Numba intermediate representation level, it's essentially creating larger function bodies to pass to LLVM. LLVM is the thing that does the optimisation and it will inline function calls as it sees fit during it's opimisation phase, typically inlining things at the Numba IR level is entirely unnecessary and it's unlikely to make any difference.

> 
>     2. Flexibility in handling inputs (provide different inlined implementations [noop or accumulate], depending on the presence/absence of inputs)

See previous remark about branch pruning. Here's an example:
```python
from numba import njit
import numpy as np

@njit
def foo(arr0, arr1=None):

    rows, cols = arr0.shape

    # always accumulate arr0
    arr0_acc = np.zeros_like(arr0)

    # if arr1 is present then define an accumulator for it, else set to None
    if arr1 is None:
        arr1_acc = None
    else:
        arr1_acc = np.zeros_like(arr1)

    for i in range(rows):
        for j in range(cols):
            # arr0 is always present
            arr0_acc[i, j] += arr0[i, j]

            # arr1 is sometimes present
            if arr1 is not None:
                arr1_acc[i, j] += arr1[i, j]

    return arr0_acc, arr1_acc


r, c = 3, 5
in_arr0 = np.ones((r, c)) * 2
in_arr1 = np.ones((r, c)) * 3

print(foo(in_arr0, arr1=None))
print(foo(in_arr0, arr1=in_arr1))
```

**Comment by sjperkins** [comment] 2019-10-11 15:03
> > > Thanks, I'm wondering what the purpose is? Are you perhaps hoping for better performance? Is this a type-inference problem? Is this helping with code organisation?
> > 
> > 
> > I'd say its a combination of:
> > ```
> > 1. Performance (inline function calls in the inner loop)
> > ```
> 
> I'd say that this is unlikely to have any impact on performance for two reasons.
> 
>     1. There's an optimisation pass in Numba called "branch pruning" that looks for `if <something that can be determined as True/False>` and kills off branches that are dead. Doing `if X is None` where `X` is a kwarg which defaults to `None` will be subject to consideration by this pass.
> 
>     2. This is inlining at the Numba intermediate representation level, it's essentially creating larger function bodies to pass to LLVM.  LLVM is the thing that does the optimisation and it will inline  function calls as it sees fit during it's opimisation phase, typically inlining things at the Numba IR level is entirely unnecessary and it's unlikely to make any difference.

My view on how inlining might be working is probably naively informed by the C/C++ inline keyword. Repeating back what I think you've told me: The LLVM IR for the inlined function will simply be placed at the site where the inlined function is  called in other IR code. But this might not result in any improvements because LLVM will decide where/when to inline (other?) function calls.

Perhaps referring to a concrete example might be helpful to my understanding. I have a function 
called [jones_mul](https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/rime/predict.py#L135-L150) which multiples matrices that are either of shape (1,), (2,) or (2, 2). The 2x2 case is highlighted.

I call jones_mul in an [inner_loop](https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/rime/predict.py#L198-L201) and would hope to remove the cost of an inner loop function call here by jitting jones_mul with `inline='always'`. But it seems that this might not inline as I expect it to do so?

I've certainly seen speedups where numba functions like jones_mul have had their contents manually written within a larger numba function. Should I manually write out every permutation rather than compose functions out of smaller functions?


> > ```
> > 2. Flexibility in handling inputs (provide different inlined implementations [noop or accumulate], depending on the presence/absence of inputs)
> > ```
> 
> See previous remark about branch pruning. Here's an example:
> 
> ```python
> from numba import njit
> import numpy as np
> 
> @njit
> def foo(arr0, arr1=None):
> 
>     rows, cols = arr0.shape
> 
>     # always accumulate arr0
>     arr0_acc = np.zeros_like(arr0)
> 
>     # if arr1 is present then define an accumulator for it, else set to None
>     if arr1 is None:
>         arr1_acc = None
>     else:
>         arr1_acc = np.zeros_like(arr1)
> 
>     for i in range(rows):
>         for j in range(cols):
>             # arr0 is always present
>             arr0_acc[i, j] += arr0[i, j]
> 
>             # arr1 is sometimes present
>             if arr1 is not None:
>                 arr1_acc[i, j] += arr1[i, j]
> 
>     return arr0_acc, arr1_acc
> 
> 
> r, c = 3, 5
> in_arr0 = np.ones((r, c)) * 2
> in_arr1 = np.ones((r, c)) * 3
> 
> print(foo(in_arr0, arr1=None))
> print(foo(in_arr0, arr1=in_arr1))
> ```

Thanks very much for the example. I think I might have developed the current (verbose!) strategy before branch pruning (on Nones) was implemented. I'll see if I can simplify the current code.

**Comment by JSKenyon** [comment] 2019-10-14 07:22
> I've certainly seen speedups where numba functions like jones_mul have had their contents manually written within a larger numba function. Should I manually write out every permutation rather than compose functions out of smaller functions?

Function calls in inner loops do seem more expensive than manually inlining. I have run into this myself. However, I wrote the following super simple test this morning which seems to suggest that the inlining does help in this case.

```python
import numpy as np
from numba import jit
import time


@jit(nopython=True, cache=True, nogil=True, inline='never')
def inner_func(x):
    return x + 1

@jit(nopython=True, cache=True, nogil=True, inline='always')
def inlined_inner_func(x):
    return x + 1


@jit(nopython=True, cache=True, nogil=True)
def loop_with_inner():

    a = 0

    for i in range(10000000):
        a = inner_func(a)

    return a

@jit(nopython=True, cache=True, nogil=True)
def loop_with_inlined_inner():

    a = 0

    for i in range(10000000):
        a = inlined_inner_func(a)

    return a

@jit(nopython=True, cache=True, nogil=True)
def loop_without_inner():

    a = 0

    for i in range(10000000):
        a = a + 1

    return a

if __name__ == "__main__":
    nruns = 100000

    t0 = time.time()
    r = [loop_with_inner() for i in range(nruns)]
    t1 = time.time()
    inner_average = (t1-t0)/nruns
    print("Average time with inner function: {}".format(inner_average))

    t0 = time.time()
    r = [loop_with_inlined_inner() for i in range(nruns)]
    t1 = time.time()
    inlined_inner_average = (t1-t0)/nruns
    print("Average time with inlined inner function: {}".format(
                                                        inlined_inner_average))

    t0 = time.time()
    r = [loop_without_inner() for i in range(nruns)]
    t1 = time.time()
    no_inner_average = (t1-t0)/nruns
    print("Average time without inner function: {}".format(no_inner_average))
```

This produces the following output on my system after a few runs:
```
Average time with inner function: 8.029127120971679e-07
Average time with inlined inner function: 2.399301528930664e-07
Average time without inner function: 2.1071910858154298e-07
```

Whilst this is obviously a trivial example, it does seem that the inlining can give superior performance. It will be interesting to see what happens for more complicated functions.

**Comment by stuartarchibald** [comment] 2019-10-14 10:17
> > > > Thanks, I'm wondering what the purpose is? Are you perhaps hoping for better performance? Is this a type-inference problem? Is this helping with code organisation?
> > > 
> > > 
> > > I'd say its a combination of:
> > > ```
> > > 1. Performance (inline function calls in the inner loop)
> > > ```
> > 
> > 
> > I'd say that this is unlikely to have any impact on performance for two reasons.
> > ```
> > 1. There's an optimisation pass in Numba called "branch pruning" that looks for `if <something that can be determined as True/False>` and kills off branches that are dead. Doing `if X is None` where `X` is a kwarg which defaults to `None` will be subject to consideration by this pass.
> > 
> > 2. This is inlining at the Numba intermediate representation level, it's essentially creating larger function bodies to pass to LLVM.  LLVM is the thing that does the optimisation and it will inline  function calls as it sees fit during it's opimisation phase, typically inlining things at the Numba IR level is entirely unnecessary and it's unlikely to make any difference.
> > ```
> 
> My view on how inlining might be working is probably naively informed by the C/C++ inline keyword. Repeating back what I think you've told me: The LLVM IR for the inlined function will simply be placed at the site where the inlined function is called in other IR code. But this might not result in any improvements because LLVM will decide where/when to inline (other?) function calls.


This isn't quite right so I'll try and clarify. Numba has it's own intermediate representation (IR) that it uses, this Numba-IR is converted to LLVM-IR for compilation by LLVM. The `inline` keyword is for inlining at the Numba-IR level, i.e. Numba IR of one function gets inlined into the call site of the Numba IR of another function. When LLVM does inlining it's doing so using it's own IR and makes its own choices about what to inline. 

> 
> Perhaps referring to a concrete example might be helpful to my understanding. I have a function
> called [jones_mul](https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/rime/predict.py#L135-L150) which multiples matrices that are either of shape (1,), (2,) or (2, 2). The 2x2 case is highlighted.
> 
> I call jones_mul in an [inner_loop](https://github.com/ska-sa/codex-africanus/blob/c55c02e4c4699d9bb2326e3dcb4b035a0ef00cb6/africanus/rime/predict.py#L198-L201) and would hope to remove the cost of an inner loop function call here by jitting jones_mul with `inline='always'`. But it seems that this might not inline as I expect it to do so?
> 
> I've certainly seen speedups where numba functions like jones_mul have had their contents manually written within a larger numba function. Should I manually write out every permutation rather than compose functions out of smaller functions?

It's often a good strategy to use real data, measure performance and then analyse the performance in light of any changes against the burden of carrying such a change. Sometimes you might just be wasting effort manually inlining functions as LLVM is already doing it for you. Numba has 3 useful `.inspect_*` methods on the dispatcher to look at what's being generated:

* `.inspect_types()` - the Numba-IR
* `.inspect_llvm()` - the LLVM IR
* `.inspect_asm()` - the dis-assembly of the compiled code

Docs: http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#dispatcher-objects

<snip>

**Comment by stuartarchibald** [comment] 2019-10-14 10:31
> > I've certainly seen speedups where numba functions like jones_mul have had their contents manually written within a larger numba function. Should I manually write out every permutation rather than compose functions out of smaller functions?
> 
> Function calls in inner loops do seem more expensive than manually inlining. I have run into this myself. However, I wrote the following super simple test this morning which seems to suggest that the inlining does help in this case.
> 
> ```python
> import numpy as np
> from numba import jit
> import time
> 
> 
> @jit(nopython=True, cache=True, nogil=True, inline='never')
> def inner_func(x):
>     return x + 1
> 
> @jit(nopython=True, cache=True, nogil=True, inline='always')
> def inlined_inner_func(x):
>     return x + 1
> 
> 
> @jit(nopython=True, cache=True, nogil=True)
> def loop_with_inner():
> 
>     a = 0
> 
>     for i in range(10000000):
>         a = inner_func(a)
> 
>     return a
> 
> @jit(nopython=True, cache=True, nogil=True)
> def loop_with_inlined_inner():
> 
>     a = 0
> 
>     for i in range(10000000):
>         a = inlined_inner_func(a)
> 
>     return a
> 
> @jit(nopython=True, cache=True, nogil=True)
> def loop_without_inner():
> 
>     a = 0
> 
>     for i in range(10000000):
>         a = a + 1
> 
>     return a
> 
> if __name__ == "__main__":
>     nruns = 100000
> 
>     t0 = time.time()
>     r = [loop_with_inner() for i in range(nruns)]
>     t1 = time.time()
>     inner_average = (t1-t0)/nruns
>     print("Average time with inner function: {}".format(inner_average))
> 
>     t0 = time.time()
>     r = [loop_with_inlined_inner() for i in range(nruns)]
>     t1 = time.time()
>     inlined_inner_average = (t1-t0)/nruns
>     print("Average time with inlined inner function: {}".format(
>                                                         inlined_inner_average))
> 
>     t0 = time.time()
>     r = [loop_without_inner() for i in range(nruns)]
>     t1 = time.time()
>     no_inner_average = (t1-t0)/nruns
>     print("Average time without inner function: {}".format(no_inner_average))
> ```
> 
> This produces the following output on my system after a few runs:
> 
> ```
> Average time with inner function: 8.029127120971679e-07
> Average time with inlined inner function: 2.399301528930664e-07
> Average time without inner function: 2.1071910858154298e-07
> ```
> 
> Whilst this is obviously a trivial example, it does seem that the inlining can give superior performance. It will be interesting to see what happens for more complicated functions.

What you are seeing in the above is the power of LLVM. If you do `.inspect_asm()` on the dispatcher objects in the above you'll note that they all have turned the jitted function into a piece of machine code like:
```python
__main__<whatever the jit function is called>$241E:
        movq    $10000000, (%rdi)
        xorl    %eax, %eax
        retq
```
because LLVM inlined the function call in all cases, worked out that the loop over `a` has static bounds and is doing trivial arithmetic, so it just pre-computed the value of `a` at the end of the loop and is returning that (the assembly above is just putting the pre-computed value of `a` (10000000) into a register and returning). I think what the above is measuring is largely the performance of Numba initialising and dragging functions out of cache, if you repeat the first timing loop at the end it's the same speed as the others as there's no init cost.

**Comment by JSKenyon** [comment] 2019-10-14 11:02
Thanks for the clarification @stuartarchibald. In what circumstances is inlining expected to be useful then?

**Comment by stuartarchibald** [comment] 2019-10-14 11:11
@JSKenyon numerous, but one common case is explained in the first section of the 0.46 release developers demo notebook, you can see it on [binder here](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2FNumba_046_developers_release_demo.ipynb).

**Closed** 2020-05-29 20:33 UTC
Labels: bug
