### ISSUE TITLE
Support for >1D bool array indexing

### ISSUE THREAD

**Issue by pantelisantonoudiou** [numba/numba#7594] opened 2021-11-24 01:18 UTC
## Reporting a bug
When using a 2D bool array to index an array of the same shape an error is raised.

### Code to reproduce error

```Python
import numpy as np
from numba import njit

arr = np.random.rand(100,10)

@njit
def f(arr):
    logic = arr > 0.5
    arr[logic] = 1     # error raised here
    return arr

f(arr)

# current workaround
@njit
def f2(arr):
    d1,d2 = arr.shape
    for i in range(d2):
        logic = arr[:,i]>0.5
        arr[logic,i] = 1
    return arr

f2(arr)
    

```

### Error
```
TypingError: No implementation of function Function(<built-in function getitem>) found for signature:
 
getitem(array(float64, 2d, C), array(bool, 2d, C))

```

### Numba/NumPy/Python version information

Numba: 0.54.1, Numpy: 1.20.3, Python: 3.9.5

**Comment by stuartarchibald** [comment] 2021-11-24 10:14
Thanks for the report. I cannot reproduce the same error message (the reproducer is doing a `setitem` not a `getitem`?), however, the issue is that Numba does not cuurently support >1D bool array indexing. Another work around is:
```python
import numpy as np
from numba import njit

np.random.seed(0)
arr = np.random.rand(4,3)

@njit
def f(arr):
    logic = arr > 0.5
    arr.ravel()[logic.ravel()] = 1
    return arr

print(f(arr))
```
Marking this as a feature request and adjusting the title.

**Comment by kc611** [comment] 2022-11-22 18:15
Support for multidimensional boolean indexing is now being tracked at https://github.com/numba/numba/issues/8616.

Hence we can close this particular issue as a duplicate.

**Closed by kc611** 2022-11-22 18:15 UTC
Labels: feature_request
