### ISSUE TITLE
unicode.join typing fails with unichr array

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6405] opened 2020-10-21 20:16 UTC
.join seems to not work properly with unicode arrays. Here is a reproducer:

```python
In [16]: str_arr = np.array(["hi", "there"])

In [17]: ",".join(str_arr)
Out[17]: 'hi,there'
In [18]: numba.njit(lambda str_arr: ",".join(str_arr))(str_arr)
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function unicode_join at 0x7fbaf3f19ca0>) found for signature:

 >>> unicode_join(unicode_type, array([unichr x 5], 1d, C))

There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'unicode_join': File: numba/cpython/unicode.py: Line 1343.
        With argument(s): '(unicode_type, array([unichr x 5], 1d, C))':
       Rejected as the implementation raised a specific error:
         TypingError: Failed in nopython mode pipeline (step: nopython frontend)
       No implementation of function Function(<function join_list at 0x7fbaf3f19940>) found for signature:

        >>> join_list(unicode_type, list([unichr x 5])<iv=None>)

       There are 2 candidate implementations:
             - Of which 2 did not match due to:
             Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
               With argument(s): '(unicode_type, list([unichr x 5])<iv=None>)':
              Rejected as the implementation raised a specific error:
                TypingError: Failed in nopython mode pipeline (step: nopython frontend)
              Unknown attribute '_kind' of type [unichr x 5]

              File "../numba/numba/cpython/unicode.py", line 1324:
              def join_list(sep, parts):
                  <source elided>
                      length += len(p)
                      kind = _pick_kind(kind, p._kind)
                      ^

              During: typing of get attribute at /Users/nicholasriasanovsky/Documents/bodo/numba/numba/cpython/unicode.py (1324)

              File "../numba/numba/cpython/unicode.py", line 1324:
              def join_list(sep, parts):
                  <source elided>
                      length += len(p)
                      kind = _pick_kind(kind, p._kind)
                      ^

         raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typeinfer.py:1071

       During: resolving callee type: Function(<function join_list at 0x7fbaf3f19940>)
       During: typing of call at /Users/nicholasriasanovsky/Documents/bodo/numba/numba/cpython/unicode.py (1360)


       File "../numba/numba/cpython/unicode.py", line 1360:
               def join_iter_impl(sep, parts):
                   <source elided>
                   parts_list = [p for p in parts]
                   return join_list(sep, parts_list)
                   ^

  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typeinfer.py:1071

- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.UnicodeType'>, 'join') for unicode_type)
During: typing of call at <ipython-input-19-5ba407ce8204> (1)


File "<ipython-input-19-5ba407ce8204>", line 1:
numba.njit(lambda str_arr: ",".join(str_arr))(str_arr)
^
```

**Comment by stuartarchibald** [comment] 2020-10-21 20:49
Thanks for the report. Copy-pastable reproducer:
```python
from numba import njit
import numpy as np

@njit
def foo(str_arr):
    return ",".join(str_arr)

arg = np.array(["hi", "there"])

foo(arg)
```
Think the issue is that `parts` in the unicode `join` is turning up as an array type, which is iterable and converted to a list, but then is directly handed off to `join_list` whereas it probably ought to dispatch again. Starter patch for fixing it:
```diff
diff --git a/numba/cpython/unicode.py b/numba/cpython/unicode.py
index d1b3fe49c..2f92bfe9e 100644
--- a/numba/cpython/unicode.py
+++ b/numba/cpython/unicode.py
@@ -1358,7 +1358,7 @@ def unicode_join(sep, parts):
     elif isinstance(parts, types.IterableType):
         def join_iter_impl(sep, parts):
             parts_list = [p for p in parts]
-            return join_list(sep, parts_list)
+            return sep.join(parts_list)
         return join_iter_impl
     elif isinstance(parts, types.UnicodeType):
         # Temporary workaround until UnicodeType is iterable
```

**Comment by esc** [comment] 2021-03-31 17:27
Closing this as #6425 has been merged some time ago.

**Closed by esc** 2021-03-31 17:27 UTC
Labels: bug - failure to compile, good first issue
