### ISSUE TITLE
Interrupting in an iPython kernel kills it

### ISSUE THREAD

**Issue by Phyks** [numba/numba#2324] opened 2017-03-30 08:42 UTC
Hi,

I am using `numba.jit` with `nopythonmode` in some Jupyter notebooks. Whenever I interrupt (menu `Kernel` -> `Interrupt` which should be equivalent to a `^C`) a running cell executing code compiled with Numba, the kernel dies.

I am not sure about what happens exactly, and I cannot see any traceback or log info in the jupyter process output. Please, let me know if this is more to be solved on the Jupyter side and I am posting in the wrong place.

Thanks!

**Comment by stuartarchibald** [comment] 2017-03-30 13:34
Thanks for the report. Perhaps the first thing to check would be that `^C` is handled correctly by the `numba.jit`ted code outside of Jupyter (i.e. run the same thing from the command line as a script) to try and isolate whether the problem is a bug in Numba or the interaction of Numba with Jupyter? Thanks.

**Comment by Phyks** [comment] 2017-03-30 14:49
Running the code in a plain Python shell and interrupting with `^C` in a `numba.jit`ted part sometimes gives a segmentation fault. The rest of the time, the program simply ignores the `^C`.

I guess ignoring the `^C` is a "normal" behavior for `numba.jit`ted code, as numpy C code cannot be interrupted as well, I think. The segfaulting case is the reason why Jupyter kernel dies I think.

I can try to publish a minimal example in case it is useful for debugging.

Thanks

**Comment by stuartarchibald** [comment] 2017-03-30 15:51
Your description/interpretation of what you are experiencing I think is correct. A segfault would cause the Jupyter kernel to die so I think it is not a problem with Jupyter. If you have a reproducer that'd be great thanks.

**Comment by Phyks** [comment] 2017-04-03 10:13
I'm trying to write a minimal example to reproduce at the moment. However, it seems I can only fall in the "not-interruptible" case, and could not reproduce the segfault case with a minimal example :/

**Comment by seibert** [comment] 2017-10-31 20:41
Closing.  Reopen if you have an example.

**Closed by seibert** 2017-10-31 20:41 UTC
