### ISSUE TITLE
KeyError when first trying to run a jit decorated function

### ISSUE THREAD

**Issue by nordam** [numba/numba#2348] opened 2017-04-23 07:14 UTC
I'm working with numerical integration of ODEs, using numba to speed up python implementations of various integrators. I have my jit-decorated functions specified in files, and I use ``@jit(nopython=True, cache=True)``. There are three files, file1 defines some functions that are used by functions in file2, which in turn are used by functions in file3. I don't pass these as arguments, but import them and just use them as global names within other functions. All functions are decorated in the same way.

Then, I finally use the functions from file3 in a jupyter notebook. The first time I call one of these functions, I get an error: ``KeyError: '_440_21'``. Then, I re-run the cell, nothing changed, and the second time it works. There is nothing called 440 or 21 or similar in my functions, so I have no idea where this error is coming from. I include the rest of the error message below. I'm happy to provide my code as well, if required.

```

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-6b60cf260044> in <module>()
     21 
     22 tic = time()
---> 23 Xdopri5c, Nsteps = traj_dopri5c(U, V, xc, yc, tc, X0[:,n], T0[n], hout, days = days, atol = tol, rtol = tol)
     24 toc = time()
     25 print('Dormand-Prince, cubic:   ', toc - tic)

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    275             else:
    276                 real_args.append(self.typeof_pyval(a))
--> 277         return self.compile(tuple(real_args))
    278 
    279     def inspect_llvm(self, signature=None):

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/dispatcher.py in compile(self, sig)
    495             cres = self._compiler.compile(args, return_type)
    496             self.add_overload(cres)
--> 497             self._cache.save_overload(sig, cres)
    498             return cres.entry_point
    499 

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/caching.py in save_overload(self, sig, cres)
    381             self._save_index(overloads)
    382 
--> 383         self._save_data(data_name, cres)
    384 
    385     def _check_cachable(self, cres):

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/caching.py in _save_data(self, name, cres)
    478 
    479     def _save_data(self, name, cres):
--> 480         data = cres._reduce()
    481         data = self._dump(data)
    482         path = self._data_path(name)

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/compiler.py in _reduce(self)
     71         libdata = self.library.serialize_using_object_code()
     72         # Make it (un)picklable efficiently
---> 73         typeann = str(self.type_annotation)
     74         fndesc = self.fndesc
     75         # Those don't need to be pickled and may fail

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/annotations/type_annotations.py in __str__(self)
    258 
    259     def __str__(self):
--> 260         return self.annotate()
    261 
    262 

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/annotations/type_annotations.py in annotate(self)
    119         #     return "Source code unavailable"
    120 
--> 121         groupedinst = self.prepare_annotations()
    122 
    123         # Format annotations

/Users/nordam/anaconda/lib/python3.5/site-packages/numba/annotations/type_annotations.py in prepare_annotations(self)
    103                         found_lifted_loop = True
    104                     else:
--> 105                         atype = self.typemap[inst.target.name]
    106 
    107                     aline = "%s = %s  :: %s" % (inst.target, inst.value, atype)

KeyError: '_440_21'

```

**Comment by stuartarchibald** [comment] 2017-05-01 21:08
Thanks for the report. I would guess that `_440_21` is possibly some internal reference in Jupyter to the location/name of the function being called. If you have a small reproducer that would be great thanks.

**Comment by seibert** [comment] 2017-10-31 19:54
Closing since we don't have example code to work with.

**Closed by seibert** 2017-10-31 19:54 UTC
