### ISSUE TITLE
NotImplementedError: offset=21 opcode=0x84 opname=MAKE_FUNCTION

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [numba/numba#1328] opened 2015-07-22 23:14 UTC
Consider the following example (taken from [this answer](http://stackoverflow.com/a/31575371/1732769))

``` python
from numba import jit

from datetime import date, timedelta
from calendar import day_abbr

@jit
def solve(start, end, data):
    days = list(day_abbr)
    output = dict.fromkeys(days, 0)

    while start <= end:
        day = days[start.weekday()]
        if start.hour in data[day]:
            output[day] += 1
        start = start + timedelta(minutes=60)

    return output
```

And the following test:

``` python
start = datetime(2015, 7, 22, 17, 58, 54, 746784)
end = datetime(2015, 8, 30, 10, 22, 36, 363912)


data = {
 'Mon': [9, 23],
 'Thu': [12, 13, 14],
 'Tue': [11, 12, 14],
 'Wed': [11, 12, 13, 14],
 'Fri': [13],
 'Sat': [],
 'Sun': [],
}

print(solve(start, end, data))
```

I get `NotImplementedError: offset=21 opcode=0x84 opname=MAKE_FUNCTION` when invoking `solve`. Is there anything in `solve` that is not supported by `numba` yet? What am I missing?

**Comment by sklam** [comment] 2015-07-23 14:48
I got a different error.  @amelio-vazquez-reina, Can you tell me which python version you are using?

**Comment by seibert** [comment] 2015-07-23 14:51
More broadly, this kind of function will not see a speed improvement in the current Numba.  Nopython mode (where the biggest speedup is achieved) does not support lists, dictionaries, or datetime objects.  Numba is primarily aimed at code that makes use of numpy arrays, numbers (int, float, complex), and tuples.

We are interested in broadening Numba's applicability to some of these data types in the long term, but we are not there today.

**Comment by amelio-vazquez-reina** [comment] 2015-07-23 16:09
Thanks @seibert  and @sklam.
```
$ python --version
Python 3.4.3 :: Anaconda 2.1.0 (x86_64)
```
* My [`$ pip freeze`](https://gist.github.com/amelio-vazquez-reina/ae910998d9cb47990aa4)

**Comment by amelio-vazquez-reina** [comment] 2015-07-23 16:11
@seibert Thanks for the info. I appreciate it. I take that as there is no easy way of having `@jit` work with the logic I have in the function (i.e. even if I replace lists by numpy arrays) (?).

**Comment by seibert** [comment] 2015-07-23 17:04
While we have support for numpy's `datetime64` and `timedelta64` types, I don't think they have an equivalent to the `datetime.weekday()` function that is used above.

This function is a good example of something that Numba could speed up, but is very difficult for it to do today.  :)

**Comment by sklam** [comment] 2015-07-23 17:13
I am using python 3.4 on osx and I cannot reproduce the MAKE_FUNCTION error.  The only error I get is `in` operator not implemented.  I added it in https://github.com/numba/numba/pull/1329.

The error about MAKE_FUNCTION is due to numba does not understand the bytecode for creating new function object.  The bytecode will appear in any comprehension expression and defining function inside the jitted function.  A less likely case is that numba is parsing the bytecode incorrectly.

**Comment by seibert** [comment] 2017-11-03 16:22
Closing now that parallel accelerator adds support for lambda functions.

**Closed by seibert** 2017-11-03 16:22 UTC
