### ISSUE TITLE
AssertionError: Failed in object mode pipeline (step: object mode frontend)

### ISSUE THREAD

**Issue by loretoparisi** [numba/numba#4848] opened 2019-11-14 16:21 UTC
I'm using `Python 3.7.3`.

My module's import
```
import os
import math
import json
import numpy as np
import datetime
import time
import copy
import librosa
from numba import jit
```

Stacktrace:
```
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 462, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 423, in frontend_looplift
    flags=loop_flags)
  File "/usr/local/lib/python3.7/site-packages/numba/transforms.py", line 191, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/usr/local/lib/python3.7/site-packages/numba/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/usr/local/lib/python3.7/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed in object mode pipeline (step: object mode frontend)
```

**Comment by stuartarchibald** [comment] 2019-11-14 17:20
Thanks for the report. Which version of Numba are you using?

**Comment by loretoparisi** [comment] 2019-11-14 17:35
@saulshanabrook I'm using the latest available from `pip`:

```
python3 -c "import numba; print(numba.__version__);"
0.43.1
```

**Comment by stuartarchibald** [comment] 2019-11-14 17:40
@loretoparisi the latest numba release is 0.46.0, try that?

**Comment by loretoparisi** [comment] 2019-11-14 18:14
@stuartarchibald how I get it from pip?

**Comment by stuartarchibald** [comment] 2019-11-14 18:16
@loretoparisi the usual way? `pip install numba` ? Which OS/arch are you using?

**Comment by loretoparisi** [comment] 2019-11-14 18:28
@stuartarchibald from `macos`, with `setup.py`, so `python3 setup.py install`:

```python
    python_requires='>=3.6, <3.8',
    include_package_data=True,
    install_requires=[
        'ffmpeg-python',
        'importlib_resources ; python_version<"3.7"',
        'norbert==0.2.1',
        'pandas==0.25.1',
        'requests',
        'setuptools>=41.0.0',
        'librosa',
        'numba',
        '{}=={}'.format(tensorflow_dependency, tensorflow_version),
    ],
```

**Comment by stuartarchibald** [comment] 2019-11-14 19:33
Right, well until Numba is upgraded to 0.46 I don't think there's much that can be done. Perhaps try and work out what's constraining the version?

**Comment by loretoparisi** [comment] 2019-11-15 09:56
@stuartarchibald ok updated:

```
Using /usr/local/lib/python3.7/site-packages
Searching for numba==0.46.0
Best match: numba 0.46.0
Processing numba-0.46.0-py3.7-macosx-10.14-x86_64.egg
```

my function's decorator is 

```python
@jit
def process(self, args)
```

The error was

```
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 462, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 423, in frontend_looplift
    flags=loop_flags)
  File "/usr/local/lib/python3.7/site-packages/numba/transforms.py", line 191, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/usr/local/lib/python3.7/site-packages/numba/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/usr/local/lib/python3.7/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed in object mode pipeline (step: object mode frontend)
```

Let me know if I can provide more info...

**Comment by stuartarchibald** [comment] 2019-11-15 09:59
@loretoparisi great, thanks! Do you have a reproducing piece of code/can you share the function that's causing this problem? The issue is essentially that Numba's control flow analysis can't work out what's going on and something illegal has happened as a result.

**Comment by loretoparisi** [comment] 2019-11-15 10:22
@stuartarchibald yes, so this error comes out in several cases, like this one:

```
Untyped global name 'get_item': cannot determine Numba type of <class 'function'>

def process(self, items):
    <source elided>
    items = get_item(text)
    ^

This error may have been caused by the following argument(s):
- argument 3: Cannot type list element of <class 'dict'>
This is not usually a problem with Numba itself but instead often caused by
...
```

**Comment by stuartarchibald** [comment] 2019-11-15 10:23
I see, thanks. Do you have a piece of code that you could share so I can run it locally to debug it please? Thanks!

**Comment by stuartarchibald** [comment] 2019-11-15 10:29
Also, that your code is falling back to run in "object mode" suggests the performance won't be very good. This explains what's going on http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode, if you are not hugely familiar with Numba I'd recommend reading the 5 minute guide and perhaps taking a look at [this tutorial](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=tutorials/nasa_apps_oct_2019).

**Comment by loretoparisi** [comment] 2019-11-15 10:35
@stuartarchibald got it, sorry the latest logging was one of the tests with `@jit(nopython=True)`. When using `@jit` only I get

```
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 462, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/usr/local/lib/python3.7/site-packages/numba/compiler.py", line 423, in frontend_looplift
    flags=loop_flags)
  File "/usr/local/lib/python3.7/site-packages/numba/transforms.py", line 191, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/usr/local/lib/python3.7/site-packages/numba/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/usr/local/lib/python3.7/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed in object mode pipeline (step: object mode frontend)
```

without any other specific error. Let me check if I can share some code.

**Comment by stuartarchibald** [comment] 2019-11-15 10:43
I see. In the above `@jit` has done the fallback to object mode and has gone down the route of trying to lift out a loop to compile and then there's something in the code/transforms that's hit a bug in control flow analysis, that `assert` is an internal check that's preventing nonsense from being compiled :) I'm thinking that this should be patched so that something more friendly is raised asking for a bug to be reported.

Irrespective of all this, there's evidently an issue in Numba and if you can provide a code sample that can be run so that we can debug it it would be most appreciated (you are welcome to obfuscate/change the source to be something very generic). Thanks!

**Comment by loretoparisi** [comment] 2019-11-15 14:11
@stuartarchibald okay let me try to provide you some code that fails. Thank you.

**Comment by stuartarchibald** [comment] 2019-11-15 17:00
Great, thanks for your help.

**Comment by stuartarchibald** [comment] 2020-02-06 09:24
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-02-06 09:24 UTC
Labels: needtriage, objectmode
