### ISSUE TITLE
Passing *args to function calls fails when parallel=True

### ISSUE THREAD

**Issue by dimitar-petrov** [numba/numba#3841] opened 2019-03-07 07:39 UTC
## Reporting a bug

Simple example.

```
@numba.jit(nopython=True, parallel=True)
def numba_loop(fn, data, *args):
    lst = []
    for i in numba.prange(data.shape[0]):
        a, b, = data[i]
        lst.append(fn(a, b, *args))
    
    return lst

@numba.jit
def fn(a, b, mult):
    return mult*(a+b)

data = np.random.rand(20, 2)
res = numba_loop(fn, data, 5)
```

With parallel=False the code snippet is working fine but when parallel=True, the following exception is raised from numba internals. (numba version '0.42.1')

## Exception
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    616     try:
--> 617         yield
    618     except NumbaError as e:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_inst(self, inst)
    407                 if isinstance(inst, _class):
--> 408                     func(self, inst)
    409                     return

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parfor.py in _lower_parfor_parallel(lowerer, parfor)
    280         index_var_typ,
--> 281         parfor.races)
    282     if config.DEBUG_ARRAY_OPT:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parfor.py in call_parallel_gufunc(lowerer, cres, gu_signature, outer_sig, expr_args, expr_arg_types, loop_ranges, redvars, reddict, redarrdict, init_block, index_var_typ, races)
   1085     wrapper_ptr, env, wrapper_name = build_gufunc_wrapper(llvm_func, cres, sin,
-> 1086                                                           sout, {})
   1087     cres.library._ensure_finalized()

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parallel.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache)
    218     innerfunc, env, wrapper_name = ufuncbuilder.build_gufunc_wrapper(
--> 219         py_func, cres, sin, sout, cache=cache)
    220     sym_in = set(sym for term in sin for sym in term)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache)
    461                else _GufuncWrapper)
--> 462     return wrapcls(py_func, cres, sin, sout, cache).build()
    463 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in build(self)
    413             # Build wrapper
--> 414             self._build_wrapper(wrapperlib, wrapper_name)
    415             # Cache

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in _build_wrapper(self, library, name)
    374             ary = GUArrayArg(self.context, builder, arg_args,
--> 375                              arg_steps, i, step_offset, typ, sym, sym_dim)
    376             step_offset += len(sym)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in __init__(self, context, builder, args, steps, i, step_offset, typ, syms, sym_dim)
    615                 raise TypeError("scalar type {0} given for non scalar "
--> 616                                 "argument #{1}".format(typ, i + 1))
    617             self._loader = _ScalarArgLoader(dtype=typ, stride=core_step)

TypeError: scalar type tuple(int64 x 1) given for non scalar argument #3

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-52-ddc17370ec69> in <module>
----> 1 res = numba_loop(fn, data, 5)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                     e.patch_message(''.join(e.args) + help_msg)
    366             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 367             raise e
    368 
    369     def inspect_llvm(self, signature=None):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    322                 argtypes.append(self.typeof_pyval(a))
    323         try:
--> 324             return self.compile(tuple(argtypes))
    325         except errors.TypingError as e:
    326             # Intercept typing error that may be due to an argument

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    653 
    654             self._cache_misses[sig] += 1
--> 655             cres = self._compiler.compile(args, return_type)
    656             self.add_overload(cres)
    657             self._cache.save_overload(sig, cres)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    924     pipeline = pipeline_class(typingctx, targetctx, library,
    925                               args, return_type, flags, locals)
--> 926     return pipeline.compile_extra(func)
    927 
    928 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    372         self.lifted = ()
    373         self.lifted_from = None
--> 374         return self._compile_bytecode()
    375 
    376     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    855         """
    856         assert self.func_ir is None
--> 857         return self._compile_core()
    858 
    859     def _compile_ir(self):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    842         self.define_pipelines(pm)
    843         pm.finalize()
--> 844         res = pm.run(self.status)
    845         if res is not None:
    846             # Early pipeline completion

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    253                     # No more fallback pipelines?
    254                     if is_final_pipeline:
--> 255                         raise patched_exception
    256                     # Go to next fallback pipeline
    257                     else:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    244                 try:
    245                     event(stage_name)
--> 246                     stage()
    247                 except _EarlyPipelineCompletion as e:
    248                     return e.result

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in stage_nopython_backend(self)
    715         """
    716         lowerfn = self.backend_nopython_mode
--> 717         self._backend(lowerfn, objectmode=False)
    718 
    719     def stage_compile_interp_mode(self):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    664             self.library.enable_object_caching()
    665 
--> 666         lowered = lowerfn()
    667         signature = typing.signature(self.return_type, *self.args)
    668         self.cr = compile_result(

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in backend_nopython_mode(self)
    651                 self.calltypes,
    652                 self.flags,
--> 653                 self.metadata)
    654 
    655     def _backend(self, lowerfn, objectmode):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1046         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1047                                metadata=metadata)
-> 1048         lower.lower()
   1049         if not flags.no_cpython_wrapper:
   1050             lower.create_cpython_wrapper(flags.release_gil)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    176         if self.generator_info is None:
    177             self.genlower = None
--> 178             self.lower_normal_function(self.fndesc)
    179         else:
    180             self.genlower = self.GeneratorLower(self)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    217         # Init argument values
    218         self.extract_function_arguments()
--> 219         entry_block_tail = self.lower_function_body()
    220 
    221         # Close tail of entry block

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    242             bb = self.blkmap[offset]
    243             self.builder.position_at_end(bb)
--> 244             self.lower_block(block)
    245 
    246         self.post_lower()

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    257             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 
    261     def create_cpython_wrapper(self, release_gil=False):

~/.pyenv/versions/3.6.6/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    623         from numba import config
    624         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 625         six.reraise(type(newerr), newerr, tb)
    626 
    627 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type tuple(int64 x 1) given for non scalar argument #3

File "<ipython-input-50-b8f79cef4077>", line 4:
def numba_loop(fn, data, *args):
    <source elided>
    lst = []
    for i in numba.prange(data.shape[0]):
    ^

[1] During: lowering "id=3[LoopNest(index_variable = parfor_index.378, range = (0, $6.6, 1))]{24: <ir.Block at <ipython-input-50-b8f79cef4077> (4)>}Var(parfor_index.378, <ipython-input-50-b8f79cef4077> (4))" at <ipython-input-50-b8f79cef4077> (4)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    616     try:
--> 617         yield
    618     except NumbaError as e:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_inst(self, inst)
    407                 if isinstance(inst, _class):
--> 408                     func(self, inst)
    409                     return

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parfor.py in _lower_parfor_parallel(lowerer, parfor)
    280         index_var_typ,
--> 281         parfor.races)
    282     if config.DEBUG_ARRAY_OPT:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parfor.py in call_parallel_gufunc(lowerer, cres, gu_signature, outer_sig, expr_args, expr_arg_types, loop_ranges, redvars, reddict, redarrdict, init_block, index_var_typ, races)
   1085     wrapper_ptr, env, wrapper_name = build_gufunc_wrapper(llvm_func, cres, sin,
-> 1086                                                           sout, {})
   1087     cres.library._ensure_finalized()

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/parallel.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache)
    218     innerfunc, env, wrapper_name = ufuncbuilder.build_gufunc_wrapper(
--> 219         py_func, cres, sin, sout, cache=cache)
    220     sym_in = set(sym for term in sin for sym in term)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache)
    461                else _GufuncWrapper)
--> 462     return wrapcls(py_func, cres, sin, sout, cache).build()
    463 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in build(self)
    413             # Build wrapper
--> 414             self._build_wrapper(wrapperlib, wrapper_name)
    415             # Cache

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in _build_wrapper(self, library, name)
    374             ary = GUArrayArg(self.context, builder, arg_args,
--> 375                              arg_steps, i, step_offset, typ, sym, sym_dim)
    376             step_offset += len(sym)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/npyufunc/wrappers.py in __init__(self, context, builder, args, steps, i, step_offset, typ, syms, sym_dim)
    615                 raise TypeError("scalar type {0} given for non scalar "
--> 616                                 "argument #{1}".format(typ, i + 1))
    617             self._loader = _ScalarArgLoader(dtype=typ, stride=core_step)

TypeError: scalar type tuple(int64 x 1) given for non scalar argument #3

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-52-ddc17370ec69> in <module>
----> 1 res = numba_loop(fn, data, 5)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                     e.patch_message(''.join(e.args) + help_msg)
    366             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 367             raise e
    368 
    369     def inspect_llvm(self, signature=None):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    322                 argtypes.append(self.typeof_pyval(a))
    323         try:
--> 324             return self.compile(tuple(argtypes))
    325         except errors.TypingError as e:
    326             # Intercept typing error that may be due to an argument

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    653 
    654             self._cache_misses[sig] += 1
--> 655             cres = self._compiler.compile(args, return_type)
    656             self.add_overload(cres)
    657             self._cache.save_overload(sig, cres)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    924     pipeline = pipeline_class(typingctx, targetctx, library,
    925                               args, return_type, flags, locals)
--> 926     return pipeline.compile_extra(func)
    927 
    928 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    372         self.lifted = ()
    373         self.lifted_from = None
--> 374         return self._compile_bytecode()
    375 
    376     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    855         """
    856         assert self.func_ir is None
--> 857         return self._compile_core()
    858 
    859     def _compile_ir(self):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    842         self.define_pipelines(pm)
    843         pm.finalize()
--> 844         res = pm.run(self.status)
    845         if res is not None:
    846             # Early pipeline completion

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    253                     # No more fallback pipelines?
    254                     if is_final_pipeline:
--> 255                         raise patched_exception
    256                     # Go to next fallback pipeline
    257                     else:

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    244                 try:
    245                     event(stage_name)
--> 246                     stage()
    247                 except _EarlyPipelineCompletion as e:
    248                     return e.result

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in stage_nopython_backend(self)
    715         """
    716         lowerfn = self.backend_nopython_mode
--> 717         self._backend(lowerfn, objectmode=False)
    718 
    719     def stage_compile_interp_mode(self):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    664             self.library.enable_object_caching()
    665 
--> 666         lowered = lowerfn()
    667         signature = typing.signature(self.return_type, *self.args)
    668         self.cr = compile_result(

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in backend_nopython_mode(self)
    651                 self.calltypes,
    652                 self.flags,
--> 653                 self.metadata)
    654 
    655     def _backend(self, lowerfn, objectmode):

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1046         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1047                                metadata=metadata)
-> 1048         lower.lower()
   1049         if not flags.no_cpython_wrapper:
   1050             lower.create_cpython_wrapper(flags.release_gil)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    176         if self.generator_info is None:
    177             self.genlower = None
--> 178             self.lower_normal_function(self.fndesc)
    179         else:
    180             self.genlower = self.GeneratorLower(self)

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    217         # Init argument values
    218         self.extract_function_arguments()
--> 219         entry_block_tail = self.lower_function_body()
    220 
    221         # Close tail of entry block

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    242             bb = self.blkmap[offset]
    243             self.builder.position_at_end(bb)
--> 244             self.lower_block(block)
    245 
    246         self.post_lower()

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    257             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 
    261     def create_cpython_wrapper(self, release_gil=False):

~/.pyenv/versions/3.6.6/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    623         from numba import config
    624         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 625         six.reraise(type(newerr), newerr, tb)
    626 
    627 

~/develop/python/osiris/.venv/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type tuple(int64 x 1) given for non scalar argument #3

File "<ipython-input-50-b8f79cef4077>", line 4:
def numba_loop(fn, data, *args):
    <source elided>
    lst = []
    for i in numba.prange(data.shape[0]):
    ^

[1] During: lowering "id=3[LoopNest(index_variable = parfor_index.378, range = (0, $6.6, 1))]{24: <ir.Block at <ipython-input-50-b8f79cef4077> (4)>}Var(parfor_index.378, <ipython-input-50-b8f79cef4077> (4))" at <ipython-input-50-b8f79cef4077> (4)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment] 2019-03-07 09:12
Thanks for the report. I think this is a different way of triggering this problem https://github.com/numba/numba/issues/3748

MWE based on the above:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def numba_loop(data, *args):
    for i in prange(data.shape[0]):
        fn(*args)

@njit
def fn(x):
    pass

res = numba_loop(np.zeros(1), 5)
```

**Comment by dimitar-petrov** [comment] 2019-03-08 06:09
@stuartarchibald, 
Do you have an idea for a workarround untill this is resolved. 
I am trying to pass different functions with different signatures but cannot come up with a way.

**Comment by stuartarchibald** [comment] 2019-03-08 08:53
@dimitar-petrov right now I don't think there is, it's a limitation of the gufunc backend that deals with the parallel kernel generation. @ehsantn @DrTodd13 any ideas? FWIW generating specific kernels based on the arg len doesn't help, it's fundamentally a problem of `VAR_POSITIONAL` in the signature (which I guess cannot be analysed).

**Comment by stuartarchibald** [comment] 2020-02-19 16:28
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:28 UTC
Labels: ParallelAccelerator, bug, duplicate
