### ISSUE TITLE
ConstantInferenceError: Failed in nopython mode pipeline (step: nopython rewrites) Constant inference not possible for: getattr(attr=format, value=$const447.2) File "<input>", line 29: <source missing, REPL/exec in use?> File "<input>", line 29: <source missing, REPL/exec in use?>

### ISSUE THREAD

**Issue by getawork** [numba/numba#5192] opened 2020-02-03 23:31 UTC

**Comment by esc** [comment] 2020-02-04 10:20
@getawork thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

**Comment by stuartarchibald** [comment] 2020-02-10 12:01
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-02-10 12:01 UTC
Labels: more info needed
