### ISSUE TITLE
Filter list comprehensions unsupported

### ISSUE THREAD

**Issue by bonk1t** [numba/numba#4572] opened 2019-09-16 00:27 UTC
Minimal reproducer:

```
from numba import jit
list_1 = [0., 10., 20., 30., 43.]
@jit
def f(my_list):
    return [i for i in my_list if i not in [0., 20., 43.]]
f(list_1)
```

Should return: [10.0, 30.0]

Instead it returns:

```
<input>:1: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "f" failed type inference due to: Type of variable '$6.4.100' cannot be determined, operation: unary(fn=<built-in function not_>, value=$6.4.100), location: <input> (3)
File "<input>", line 3:
<source missing, REPL/exec in use?>
Traceback (most recent call last):
  File "Path\To\numba\errors.py", line 662, in new_error_context
    yield
  File "Path\To\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "Path\To\numba\pylowering.py", line 96, in lower_inst
    value = self.lower_assign(inst)
  File "Path\To\numba\pylowering.py", line 190, in lower_assign
    return self.lower_expr(value)
  File "Path\To\numba\pylowering.py", line 259, in lower_expr
    value = self.loadvar(expr.value.name)
  File "Path\To\numba\pylowering.py", line 555, in loadvar
    assert name in self._live_vars, name
AssertionError: $6.4.121
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "Path\To\numba\dispatcher.py", line 395, in _compile_for_args
    raise e
  File "Path\To\numba\dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "Path\To\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "Path\To\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "Path\To\numba\dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "Path\To\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "Path\To\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "Path\To\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "Path\To\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "Path\To\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "Path\To\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "Path\To\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "Path\To\numba\compiler.py", line 266, in run
    raise patched_exception
  File "Path\To\numba\compiler.py", line 257, in run
    stage()
  File "Path\To\numba\compiler.py", line 728, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "Path\To\numba\compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "Path\To\numba\compiler.py", line 675, in backend_object_mode
    self.flags)
  File "Path\To\numba\compiler.py", line 1167, in py_lowering_stage
    lower.lower()
  File "Path\To\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "Path\To\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "Path\To\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "Path\To\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "Path\To\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "Path\To\numba\errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "Path\To\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
$6.4.121
File "<input>", line 3:
<source missing, REPL/exec in use?>
[1] During: lowering "$6.4.121 = unary(fn=<built-in function not_>, value=$6.4.121)" at <input> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.
```

**Comment by stuartarchibald** [comment] 2019-09-16 12:59
Thanks for the report, I can reproduce. I think the issue here is more the use of a function operating on a list as a filter rather than a filter itself. 
e.g. This works fine:
```python
from numba import njit
list_1 = [0., 10., 20., 30., 43.]

@njit
def f(my_list):
    return [i for i in my_list if i > 20]

print(f(list_1))
```
I suspect the list comprehension rewrite is struggling to reach over the function call/this seems to be mixed with the `[0., 20., 43.]` being rewritten as a tuple if no function call is made.

**Comment by Bonikt** [comment] 2019-09-16 15:20
One workaround is to switch to dictionaries (numba.typed.Dict). This code works (copying is mandatory):

@njit
def filter_dict(my_dict: numba.typed.Dict, not_in_dict: numba.typed.Dict) -> numba.typed.Dict:
    my_dict_copy = my_dict.copy()
    for i in my_dict.keys():
        if i in not_in_dict:
            del my_dict_copy[i]
    return my_dict_copy

**Comment by stuartarchibald** [comment] 2021-12-15 17:27
This does not reproduce on mainline as of Numba 0.55, closing assuming fixed.

**Closed by stuartarchibald** 2021-12-15 17:27 UTC
Labels: bug
