### ISSUE TITLE
ValueError raised by arviz tests with numba 0.60.0 and 0.59.1 (regression from 0.58.1)

### ISSUE THREAD

**Issue by folded** [numba/numba#9725] opened 2024-09-16 22:26 UTC
It's a little bit difficult to create a minimal reproducer for this, and it seems to be in the python fallback so probably a low priority.

Python: 3.11.6
ArviZ: v0.15.1 (git hash f80265030f9662d1e31a680ad05cc58e6f3bf9eb)

In an arviz checkout:

```
pip install .
pip install -r requirements-test.txt
pip install scipy==1.12.0
pip install numba==0.60.0
MPLBACKEND=pdf pytest -k test_plot_forest_single_value
```

Leads to:

```
ValueError: Cannot add edge as dest node 510 not in nodes {260, 262, 17, 498, 146, 148, 20, 212, 18, 499, 412}
```

The same test also fails with 0.59.1 and passes with 0.58.1

If you think it's worth digging deeper based upon this, I can collect more information.

**Comment by gmarkall** [comment] 2024-09-16 23:00
When it was working, were you using a different Python version?

**Comment by folded** [comment] 2024-09-17 06:01
No, I can repro this regression in the one venv by pip installing different
numba versions.

**Comment by gmarkall** [comment] 2024-09-23 10:37
Rather than running the test suite, the command:

```
python -c "from arviz.plots import plot_forest; plot_forest({'x': [1]})"
```

seems to be sufficient to reproduce the issue.

**Comment by gmarkall** [comment] 2024-09-23 10:52
Standalone reproducer:

```python
from numba import jit
import numpy as np


class Val:
    def labels_ticks_and_vals(self):
        return None, None, None, None


val = [Val()]


@jit(forceobj=True)
def f():
    labels, idxs = [], []
    for plotter in val:
        sub_labels, sub_idxs, _, _ = plotter.labels_ticks_and_vals()
        labels_to_idxs = defaultdict(list)
        for label, idx in zip(sub_labels, sub_idxs):
            labels_to_idxs[label].append(idx)
        sub_idxs = []
        sub_labels = []
        for label, all_idx in labels_to_idxs.items():
            sub_labels.append(label)
            sub_idxs.append(np.mean([j for j in all_idx]))
        labels.append(sub_labels)
        idxs.append(sub_idxs)
    return np.concatenate(labels), np.concatenate(idxs)


f()
```

**Comment by gmarkall** [comment] 2024-09-23 11:14
Minimal reproducer:

```python
from numba import jit

@jit(forceobj=True)
def f():
    for i in []:
        for j in []:
            sum([k for k in j])

f.py_func()
f()
```

giving a traceback ending in

```
  File "/home/gmarkall/numbadev/numba/numba/core/transforms.py", line 358, in canonicalize_cfg
    return canonicalize_cfg_single_backedge(blocks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/core/transforms.py", line 287, in canonicalize_cfg_single_backedge
    cfg = compute_cfg_from_blocks(blocks)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/core/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/home/gmarkall/numbadev/numba/numba/core/controlflow.py", line 114, in add_edge
    raise ValueError("Cannot add edge as dest node %s not in nodes %s" %
ValueError: Cannot add edge as dest node 86 not in nodes {7, 8, 72, 74, 10, 75, 16, 18}
```

**Comment by gmarkall** [comment] 2024-09-23 11:16
```
ce80ef637af604594e54ca8c7db88bd1c904a125 is the first bad commit
commit ce80ef637af604594e54ca8c7db88bd1c904a125
Author: Stuart Archibald <stuartarchibald@users.noreply.github.com>
Date:   Mon Dec 11 20:11:57 2023 +0000

    Fix numerous failing tests for objmode fall-back.
```

**Comment by gmarkall** [comment] 2024-09-23 11:18
This resulted from the removal of object mode fallback: https://github.com/numba/numba/pull/9352

**Comment by stuartarchibald** [comment] 2024-09-27 15:05
Thanks for the report. It looks like the issue is that:
1. The IR is "cloned" in the LoopLifting code to try and avoid mutation effects, but then it is used on both sides of a try/except. https://github.com/numba/numba/blob/301ba23116864ef66a2caccfab7c7123e7bcbcfc/numba/core/dispatcher.py#L1131-L1163
2. Even if a separate copy of the IR is used either side of the above try/except, the `rename_labels` function that is used by the closure inlining pass (as needed by the list-comp in the OP) mutates the terminator nodes directly opposed to replacing them: https://github.com/numba/numba/blob/301ba23116864ef66a2caccfab7c7123e7bcbcfc/numba/core/ir_utils.py#L1312-L1318

I have a fix for this locally and will make it into a PR.

**Closed** 2024-10-17 20:27 UTC
Labels: bug - ice, bug - regression
