### ISSUE TITLE
numba error when using scanpy

### ISSUE THREAD

**Issue by taopeng1100** [numba/numba#6054] opened 2020-07-30 18:49 UTC
https://github.com/theislab/scanpy/blob/2f160ea403d124d237fc2138c0aa0d175fbad22a/scanpy/preprocessing/_qc.py#L402-L428

The message from Scanpy:

@taopeng1100: This is a numba bug. Please report this there, but only if you use the newest numba version. Give them this link so they see the code that triggers their bug:
https://github.com/theislab/scanpy/blob/2f160ea403d124d237fc2138c0aa0d175fbad22a/scanpy/preprocessing/_qc.py#L402-L428
@team: We should include numba in the package versions list.

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by gmarkall** [comment] 2020-07-31 10:41
@taopeng1100 Thanks for the report - could you describe what the bug is please? Ideally, if you could provide a self-contained executable reproducer, that would be very helpful.

**Comment by taopeng1100** [comment] 2020-07-31 19:07
I originally posted the message on scanpy GitHub and the link is as follows:

https://github.com/theislab/scanpy/issues/1341


Thx!

**Comment by taopeng1100** [comment] 2020-07-31 19:09
When I installed anaconda a few days ago, the numba is 0.50.1.

From: Peng, Tao
Sent: Friday, July 31, 2020 12:07 PM
To: numba/numba <reply@reply.github.com>; numba/numba <numba@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [numba/numba] numba error when using scanpy (#6054)

I originally posted the message on scanpy GitHub and the link is as follows:

https://github.com/theislab/scanpy/issues/1341


Thx!

**Comment by stuartarchibald** [comment] 2020-08-03 10:33
Thanks for the report, I think that this is a duplicate of https://github.com/numba/numba/issues/5955 so am closing, if this is not the case then please do reopen.

**Closed by stuartarchibald** 2020-08-03 10:33 UTC
Labels: more info needed
