### ISSUE TITLE
parallel=True causes TypingError

### ISSUE THREAD

**Issue by louisabraham** [numba/numba#4462] opened 2019-08-18 15:19 UTC
The following code fails when I set parallel=True

```python
import numpy as np
from numba import jit, njit, prange, typed, types

from tqdm import tqdm


@njit
def _neighbors(indptr, indices, node):
    return indices[indptr[node] : indptr[node + 1]].astype(np.uint64)


@njit  # (parallel=True)
def _BFS(indptr, indices, query_src, query_dsts, limit, distances, a, b):
    k = query_dsts.shape[1]

    for q in prange(a, b):
        src = query_src[q]
        dsts = {}
        for i in range(k):
            dsts[query_dsts[q, i]] = np.uint64(i)
        lvl = {src}
        visited = set()
        d = 0
        while len(dsts) and len(lvl) and len(visited) < limit:
            newlvl = set()
            for node in lvl:
                visited.add(node)
                if node in dsts:
                    distances[q, dsts[node]] = d
                    del dsts[node]

                for v in _neighbors(indptr, indices, node):
                    if v not in visited:
                        newlvl.add(v)

            lvl = newlvl
            d += 1


def BFS(indptr, indices, query_src, query_dsts, limit=100):
    distances = np.full_like(query_dsts, -1, dtype=np.int64)

    c = 0

    batch_size = 10000

    for a in tqdm(range(0, len(query_src), batch_size)):
        _BFS(
            indptr,
            indices,
            query_src,
            query_dsts,
            limit,
            distances,
            a,
            min(len(query_src), a + batch_size),
        )

    return distances


if __name__ == "__main__":
    import numba

    print(numba.config.NUMBA_DEFAULT_NUM_THREADS)

    print(
        BFS(
            np.arange(100, dtype=np.int32),
            np.arange(100, dtype=np.int32),
            np.full(10_000_000, 0, dtype=np.uint64),
            np.full(50_000_000, 5, dtype=np.uint64).reshape(10_000_000, 5),
        )
    )
    BFS.inspect_types()
```

The error is 

```
Failed in nopython mode pipeline (step: nopython frontend)
Type of variable '$196.4' cannot be determined, operation: unary(fn=<built-in function not_>, value=$196.4), location: bfs.py (33)

File "bfs.py", line 33:
def _BFS(indptr, indices, query_src, query_dsts, limit, distances, a, b):
    <source elided>
                for v in _neighbors(indptr, indices, node):
                    if v not in visited:
                    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.16, range = (a, b, 1))]{96: <ir.Block at bfs.py (24)>, 194: <ir.Block at bfs.py (32)>, 196: <ir.Block at bfs.py (32)>, 104: <ir.Block at bfs.py (24)>, 136: <ir.Block at bfs.py (26)>, 138: <ir.Block at bfs.py (26)>, 76: <ir.Block at bfs.py (20)>, 238: <ir.Block at bfs.py (34)>, 206: <ir.Block at bfs.py (33)>, 112: <ir.Block at bfs.py (24)>, 48: <ir.Block at bfs.py (19)>, 242: <ir.Block at bfs.py (37)>, 50: <ir.Block at bfs.py (19)>, 180: <ir.Block at bfs.py (30)>, 24: <ir.Block at bfs.py (16)>, 218: <ir.Block at bfs.py (32)>, 158: <ir.Block at bfs.py (28)>, 124: <ir.Block at bfs.py (24)>, 222: <ir.Block at bfs.py (34)>}Var(parfor_index.16, bfs.py (16))" at bfs.py (16)
```

A temporary fix is to use

```python
if not bool(v in visited):
```

This error doesn't make any sense!

I'm sorry that I don't have the time to produce a minimal example, but I thought making the bug known is more important!

**Comment by stuartarchibald** [comment] 2019-08-19 08:18
Thanks for the report, think this is due to conditionals not being interpreted correctly as predicates, https://github.com/numba/numba/pull/3901 fixes but needs at least this https://github.com/numba/numba/pull/4445 and quite possibly this https://github.com/numba/numba/pull/3757 for convenience.

**Comment by stuartarchibald** [comment] 2021-12-15 16:44
This doesn't reproduce on mainline for Numba 0.55. Closing assumed fix. Please do reopen if the issue persists in 0.55+. Thanks.

**Closed by stuartarchibald** 2021-12-15 16:44 UTC
Labels: bug, duplicate
