### ISSUE TITLE
numba 0.19 beta: performance decreased by a factor of seven

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1180] opened 2015-05-26 09:06 UTC
If I run the following test with numba 0.18.2

python KPS4P_v2.py

I get the following execution time reported:

Execution time (µs):  15.9597396851

If I do the same test with numba 0.19 beta
(0.18.2-np19py27_519) I get the following result:

Execution time (µs):  108.22057724

This is about 7 times slower than before.

The code is available from git at:
https://bitbucket.org/ufechner/freekitesim

Any idea?

**Comment by sklam** [comment] 2015-05-26 19:57
@ufechner7, I am trying reproduce the problem but I am stuck at installing kitesim on a ubuntu14.04 64-bit VM with conda 3.12.0.

```bash
(kitesim)builder@lubuntu1404x64:~/00PythonSoftware/FreeKiteSim$ python fks_control install-base
Installing base system
FreeKiteSim requires freeglut3 and gfortran.
Please make sure these packages are installed before continuing
with the installation. Continue? y/[n] y
Fetching index ...
Resolving dependencies ...
^CTraceback (most recent call last):
  File "/home/builder/miniconda/envs/kitesim/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/builder/miniconda/envs/kitesim/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/builder/00PythonSoftware/FreeKiteSim/fks_control/__main__.py", line 7, in <module>
    main()
  File "/home/builder/00PythonSoftware/FreeKiteSim/fks_control/__main__.py", line 4, in main
    KitepowerPackageManager()
  File "fks_control/fks_control.py", line 96, in __init__
    self.install_base()
  File "fks_control/fks_control.py", line 240, in install_base
    self.install('freekitesim')
  File "fks_control/fks_control.py", line 303, in install
    tbi = self.resolve(package)
  File "fks_control/fks_control.py", line 367, in resolve
    matches = self.search(packages[j])
  File "fks_control/fks_control.py", line 539, in search
    matches = {k:v for k, v in self.cache.iteritems() if package_name == v['name']}
  File "fks_control/fks_control.py", line 539, in <dictcomp>
    matches = {k:v for k, v in self.cache.iteritems() if package_name == v['name']}
KeyboardInterrupt
```

The install is stuck at the line indicated in the traceback above.  

FYI, I have freeglut3 and gfortran installed despite the warning

**Comment by sklam** [comment] 2015-05-26 20:51
@ufechner7, I am able to workaround the installation problem by manually installing the dependencies.  I can confirm a 4x slow down on my machine.  From 32us to 123us.  Investigating...

**Comment by sklam** [comment] 2015-05-26 20:58
I found the problem.  This is due to an error in the compiler that causes the function to compile in objmode.

**Comment by ufechner7** [comment] 2015-05-27 05:19
Results are better with 0.18.2-np19py27_528, but there is still a slowdown by a factor of two:
0.18.2-np19py27_528 : 24 us
0.18.2-np19py27_1: 12.5 us
(Different PC, Haswell CPU).

**Comment by seibert** [comment] 2015-05-27 17:00
We think this remaining performance difference is due to an increase in the overhead to call Numba compiled functions.  The new memory management system is currently doing some extra work to track allocations, which is slowing down short functions that don't need memory management.  We won't be able to fix this in time for Numba release this week, but I think we can address it in the June release.

We will keep this issue open to track the problem.

**Comment by ufechner7** [comment] 2015-05-27 17:53
Wasn't there the plan to have a parameter for the jit decorator to tell numba if the new memory management is needed for a function or not?

**Comment by seibert** [comment] 2015-05-27 20:23
Yes, we have the undocumented `_nrt` option to `@jit`, but it is intended only for testing purposes.  (You could certainly try it out as a temporary workaround.) We need to fix the underlying performance issue, though.

**Comment by stuartarchibald** [comment] 2019-12-31 13:27
Closing this issue due to lack of information (seems like the issue was object mode fallback https://github.com/numba/numba/issues/1180#issuecomment-105662954 and then refcounting in the NRT which has had some improvements [on 0.47.0 at present]). If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-12-31 13:27 UTC
Labels: needtriage
