### ISSUE TITLE
Errors with Cuda Memory Management (I suppose)

### ISSUE THREAD

**Issue by Hendiadyoin1** [numba/numba#4351] opened 2019-07-22 15:09 UTC
During testing of a primitive Prime-Finder I ran into issues with Numba tryinng to free Memory on the GPU or under some cricumstances copying the results back to the host.
When testing with the batch size I ran into cuModuleUnload Errors too.
Further testing showed:
til 100.000 items : OK
10.000.000 items : cuMemcpyDtoH
100.000.000 items : cuModuleUnload
45.000.000 items:  cuMemFree

The code is as following:
```
from numba import cuda, vectorize, i8
import numpy as np
from math import ceil


@vectorize([i8(i8)], target='cuda')
def factorize_V(number):
    i = 2
    while True:
        j = number % i
        if j == 0:
            if i == number:
                return number
            else:
                break
        else:
            i += 1
        if i > number:
            break
    return 0


@cuda.jit()
def factorize_J(numbers, ret):
    pos = cuda.grid(1)
    number = numbers[pos]
    i = 2
    while True:
        j = number % i
        if j == 0:
            if i == number:
                ret[pos] = number
                return
            else:
                ret[pos] = 0
                return
        if i > number:
            ret[pos] = 0
            return
        i += 1


if __name__ == '__main__':
    factorize_V.max_blocksize = 32
    numbers = np.arange(5 * 10**6, 5 * 10**7 - 1, dtype='i8')
    ret = np.zeros_like(numbers, dtype='i8')

    threadsize = 16
    blocksize = ceil(numbers.shape[0] / threadsize)

    factorize_J[blocksize, threadsize](numbers, ret)
    ret = ret[ret > 0]
    print(ret)
```
the full error Message is as follows:

> Traceback (most recent call last):
>   File "C:\Users\...\Documents\Python\Multiprocessing\factorizer-GPU.py", line 56, in <module>
>     factorize_J[blocksize, threadsize](numbers, ret)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 808, in __call__
>     cfg(*args)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 538, in __call__
>     sharedmem=self.sharedmem)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\compiler.py", line 649, in _kernel_call
>     wb()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\args.py", line 65, in <lambda>
>     retr.append(lambda: devary.copy_to_host(self.value, stream=stream))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\devices.py", line 212, in _require_cuda_context
>     return fn(*args, **kws)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 235, in copy_to_host
>     _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1856, in device_to_host
>     fn(host_pointer(dst), device_pointer(src), size, *varargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 293, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 328, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 745, in _exitfunc
>     f()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1324, in deref
>     mem.free()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1210, in free
>     self._finalizer()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 906, in core
>     deallocations.add_item(driver.cuMemFree, handle, size)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 546, in add_item
>     self.clear()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 557, in clear
>     dtor(handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 293, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 328, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemFree results in CUDA_ERROR_LAUNCH_FAILED
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 745, in _exitfunc
>     f()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 985, in core
>     dealloc.add_item(module_unload, handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 546, in add_item
>     self.clear()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 557, in clear
>     dtor(handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 293, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 328, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemFree results in CUDA_ERROR_LAUNCH_FAILED

and the numba -s output is:

> System info:
> --------------------------------------------------------------------------------
> __Time Stamp__
> 2019-07-22 14:56:16.398640
> 
> __Hardware Information__
> Machine                                       : AMD64
> CPU Name                                      : bdver2
> CPU count                                     : 8
> CPU Features                                  :
> 64bit aes avx bmi cmov cx16 f16c fma fma4 lzcnt mmx pclmul popcnt prfchw sahf
> sse sse2 sse3 sse4.1 sse4.2 sse4a ssse3 tbm xop xsave
> 
> __OS Information__
> Platform                                      : Windows-10-10.0.17763-SP0
> Release                                       : 10
> System Name                                   : Windows
> Version                                       : 10.0.17763
> OS specific info                              : 1010.0.17763SP0Multiprocessor Free
> 
> __Python Information__
> Python Compiler                               : MSC v.1916 64 bit (AMD64)
> Python Implementation                         : CPython
> Python Version                                : 3.7.3
> Python Locale                                 : de_DE cp1252
> 
> __LLVM information__
> LLVM version                                  : 8.0.0
> 
> __CUDA Information__
> Found 1 CUDA devices
> id 0     b'GeForce GTX 1050'                              [SUPPORTED]
>                       compute capability: 6.1
>                            pci device id: 0
>                               pci bus id: 1
> Summary:
>         1/1 devices are supported
> CUDA driver version                           : 10000
> CUDA libraries:
> Finding cublas from CUDA_HOME
>         named  cublas64_100.dll
>         trying to open library...       ok
> Finding cusparse from CUDA_HOME
>         named  cusparse64_100.dll
>         trying to open library...       ok
> Finding cufft from CUDA_HOME
>         named  cufft64_100.dll
>         trying to open library...       ok
> Finding curand from CUDA_HOME
>         named  curand64_100.dll
>         trying to open library...       ok
> Finding nvvm from CUDA_HOME
>         named  nvvm64_33_0.dll
>         trying to open library...       ok
> Finding libdevice from CUDA_HOME
>         searching for compute_20...     ok
>         searching for compute_30...     ok
>         searching for compute_35...     ok
>         searching for compute_50...     ok
> 
> __ROC Information__
> ROC available                                 : False
> Error initialising ROC due to                 : No ROC toolchains found.
> No HSA Agents found, encountered exception when searching:
> Error at driver init:
> 
> HSA is not currently supported on this platform (win32).
> :
> 
> __SVML Information__
> SVML state, config.USING_SVML                 : False
> SVML library found and loaded                 : False
> llvmlite using SVML patched LLVM              : True
> SVML operational                              : False
> 
> __Threading Layer Information__
> TBB Threading layer available                 : False
> +--> Disabled due to                          : Unknown import problem.
> OpenMP Threading layer available              : False
> +--> Disabled due to                          : Unknown import problem.
> Workqueue Threading layer available           : True
> 
> __Numba Environment Variable Information__
> None set.
> 
> __Conda Information__
> Conda not present/not working.
> Error was [WinError 2] Das System kann die angegebene Datei nicht finden
> 
> --------------------------------------------------------------------------------

**Comment by Hendiadyoin1** [comment] 2019-07-23 13:31
further testing showed me that the size of numbers has an effect on the type/existince of an error

the batchsize was 2**16, and the numbers started at 327680 and ended at 393216.
direct testing of the numbers caused a cuMemcpyDtoH error and in the testing loop an cuMemFree Error

My first idea would be that that has something to do with number optimizations and Integer64(i8) calculation on the GPU but the error persists after changing to Integer32(i4)'s

**Comment by seibert** [comment] 2019-07-23 13:38
How long does this kernel run for before raising an error?  I notice that you are running with a single GPU on Windows, which means the watchdog timer will be enabled.  The timer will terminate the CUDA kernel (causing a CUDA error message that doesn't always make sense) after a few seconds to allow the display driver to update the screen.

**Comment by Hendiadyoin1** [comment] 2019-07-23 14:00
propably just over 2 seconds and the screen is still updating at a good speed during computation

**Comment by Hendiadyoin1** [comment] 2019-07-23 14:00
> 327680 and ended at 393216

with a smaller batch size it will run further
But it seems that memmory is not the issue

**Comment by Hendiadyoin1** [comment] 2019-07-25 15:39
To clarify that the watchdog timer is not the problem I've let the program run with device arrays and tryed to copy them back resulting in the crash:

> Traceback (most recent call last):
>   File "C:\Users\...\Documents\Python\Multiprocessing\GPU\factorizer-GPU.py", line 76, in <module>
>     ret = retG.copy_to_host()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\devices.py", line 223, in _require_cuda_context
>     return fn(*args, **kws)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 235, in copy_to_host
>     _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1908, in device_to_host
>     fn(host_pointer(dst), device_pointer(src), size, *varargs)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 294, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 329, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 745, in _exitfunc
>     f()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1376, in deref
>     mem.free()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1262, in free
>     self._finalizer()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 958, in core
>     deallocations.add_item(driver.cuMemFree, handle, size)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 599, in add_item
>     self.clear()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 610, in clear
>     dtor(handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 294, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 329, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemFree results in CUDA_ERROR_LAUNCH_FAILED
> Traceback (most recent call last):
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 745, in _exitfunc
>     f()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\utils.py", line 669, in __call__
>     return info.func(*info.args, **(info.kwargs or {}))
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1037, in core
>     dealloc.add_item(module_unload, handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 599, in add_item
>     self.clear()
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 610, in clear
>     dtor(handle)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 294, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cuda\cudadrv\driver.py", line 329, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemFree results in CUDA_ERROR_LAUNCH_FAILED

Intrestingly the Error in cuMemcpyDtoH resulted in two additional Errors in cuMemFree

**Comment by seibert** [comment] 2019-07-25 20:28
I have also seen `CUDA_ERROR_LAUNCH_FAILED` when the kernel has a block or thread configuration that isn't supported by the device.  That doesn't seem to be the case here, because it looks like your grid size is 2812500 blocks by 16 threads, which should be allowed.

**Comment by sklam** [comment] 2019-07-29 18:22
Here's an example of the script terminating due to timeout error:
```
Traceback (most recent call last):
  File "chk4351.py", line 54, in <module>
    factorize_J[blocksize, threadsize](numbers, ret)
  File "/Users/me/dev/numba/numba/cuda/compiler.py", line 808, in __call__
    cfg(*args)
  File "/Users/me/dev/numba/numba/cuda/compiler.py", line 538, in __call__
    sharedmem=self.sharedmem)
  File "/Users/me/dev/numba/numba/cuda/compiler.py", line 615, in _kernel_call
    driver.device_to_host(ctypes.addressof(excval), excmem, excsz)
  File "/Users/me/dev/numba/numba/cuda/cudadrv/driver.py", line 1908, in device_to_host
    fn(host_pointer(dst), device_pointer(src), size, *varargs)
  File "/Users/me/dev/numba/numba/cuda/cudadrv/driver.py", line 294, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/Users/me/dev/numba/numba/cuda/cudadrv/driver.py", line 329, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [702] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_TIMEOUT
```
Due to asynchronous nature of the GPU kernel launches, the error is showed at the D->H transfer point.    

According to Nvidia [docs](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html), `CUDA_ERROR_LAUNCH_FAILED` can be caused by out-of-bound error: 
> An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointer and accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases can be found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched.

It looks like `numbers[pos]` and `ret[pos]` is not protected from potential out-of-bound.  Note there's no boundchecking at array getitem.

**Comment by Hendiadyoin1** [comment] 2019-08-03 14:23
That could be the case but it take see the question why it's only been raised at an specific point and not in runs with the same amount, but lower numbers, therefore it seems more likely that the watchdog timer in conjunction with the asynchronous behaviour is the problem, because the batch size is divisible by 1024(the threadsize) and therefore the shouldn't be threads that raise a null pointer and when testing with a faster algorlrithm the error does not occur.
So if the watchdog timer is the problem, is there a way to notice when it's killing the process, or to completely circumvent it?

**Comment by seibert** [comment] 2019-08-05 13:01
I'm not aware of any solutions beyond:
 * Adding a second GPU you can run with the Windows "TCC" driver (Tesla, Quadro, Titan)
 * Switch to Linux where you can stop the GUI process (X.org)
 * Chunking the work so that your kernels take much less than the timeout to run (hard to estimate where that point is, of course)

**Comment by stuartarchibald** [comment] 2020-09-11 18:22
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-11 18:22 UTC
Labels: CUDA, needtriage
