### ISSUE TITLE
Numpy isnan failing when used multiple times in prange

### ISSUE THREAD

**Issue by bbooze1** [numba/numba#3752] opened 2019-02-10 01:22 UTC
I've encountered an error when I try and use isnan on more than one array in any function I prange. Below I've provided a minimal example and the error message. 

I'm using Numpy 1.15.4 and Numba 0.42.0

```
import numpy as np
from numba import prange, njit


@njit(parallel=True)
def nanWorks (nan_array):
    for i in prange(2):
        test =  nan_array[i][~np.isnan(nan_array[i])]
        
@njit(parallel=True)
def nanNoWork (nan_array, nan_array2):
    for i in prange(2):
        test = nan_array[i][~np.isnan(nan_array[i])]
        test2 = nan_array2[i][~np.isnan(nan_array2[i])]

nan_array = np.array([[np.nan, 5, 6, 7, np.nan], [3, 5, 6, np.nan, np.nan]])
nan_array2 = np.array([[np.nan, 1, 2, 3, np.nan], [4, 7, 8, np.nan, np.nan]])

nanWorks(nan_array)
nanNoWork(nan_array, nan_array2)
```

Error Message

```
Traceback (most recent call last):
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\errors.py", line 617, in new_error_context
    yield
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 408, in lower_inst
    func(self, inst)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\npyufunc\parfor.py", line 238, in _lower_parfor_parallel
    bool(alias_map), index_var_typ, parfor.races)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\npyufunc\parfor.py", line 1012, in _create_gufunc_for_parfor_body
    locals)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 941, in compile_ir
    lifted_from=lifted_from)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 382, in compile_ir
    return self._compile_ir()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 864, in _compile_ir
    return self._compile_core()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 255, in run
    raise patched_exception
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 246, in run
    stage()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 485, in stage_nopython_frontend
    self.locals)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 1028, in type_inference_stage
    infer.build_constraint()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 816, in build_constraint
    self.constrain_statement(inst)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1094, in constrain_statement
    f(inst, self)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\parfor.py", line 3903, in parfor_typeinfer
    typeinferer.build_constraint()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 816, in build_constraint
    self.constrain_statement(inst)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1076, in constrain_statement
    self.typeof_assign(inst)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1139, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1267, in typeof_global
    self.lock_type(target.name, lit or typ, loc=inst.loc)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 883, in lock_type
    tv.lock(tp, loc=loc, literal_value=literal_value)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\typeinfer.py", line 76, in lock
    assert not self.locked
AssertionError: Failed in nopython mode pipeline (step: nopython frontend)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Bryce\source\repos\testing nan.py", line 20, in <module>
    nanNoWork(nan_array, nan_array2)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 255, in run
    raise patched_exception
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 246, in run
    stage()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Bryce\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\Bryce\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
[1m[1mFailed in nopython mode pipeline (step: nopython frontend)

[1m
File "testing nan.py", line 12:[0m
[1mdef nanNoWork (nan_array, nan_array2):
[1m    for i in prange(2):
[0m    [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "id=4[LoopNest(index_variable = parfor_index.144, range = (0, $const2.2, 1))]{12: <ir.Block at C:\Users\Bryce\source\repos\testing nan.py (12)>}Var(parfor_index.144, C:\Users\Bryce\source\repos\testing nan.py (12))" at C:\Users\Bryce\source\repos\testing nan.py (12)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```

**Comment by stuartarchibald** [comment] 2019-02-11 10:09
Thanks for the report. I think the root cause is the same as https://github.com/numba/numba/issues/3686 which was fixed in https://github.com/numba/numba/pull/3706 and will make it into the next (0.43) release. The code sample presented works fine when using the Numba master branch. 
If you would like to try out the latest development releases of Numba they are available via:
```bash
conda install -c numba/label/dev numba
```

**Closed** 2019-02-11 10:09 UTC
Labels: ParallelAccelerator, bug, duplicate, no action required

**Comment by bbooze1** [comment] 2019-02-12 00:58
Thank you, it does work now with the new update.
