### ISSUE TITLE
invalid number of args for optional arguments of jitclass methods. 

### ISSUE THREAD

**Issue by roosephu** [numba/numba#5961] opened 2020-07-06 00:02 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Numba version: 0.50.1. 

Code to reproduce: 

```code
import numba as nb

@nb.experimental.jitclass([('x', nb.int64)])
class Cls:
    def __init__(self, x=1):
        self.x = x

@nb.njit
def test(): 
    Cls()  # doesn't work: `invalid number of args: expected 2, got 1`
    Cls(1)  # works

test()
```

Expected behavior: No errors. 
Results: `invalid number of args: expected 2, got 1` for `Cls()`.

**Comment by esc** [comment] 2020-07-06 08:22
@roosephu thanks for reporting this, I can reproduce it! I believe it is a duplicate of: https://github.com/numba/numba/issues/4820 - please check for duplicates the next time, thanks!

**Closed by esc** 2020-07-06 08:22 UTC
Labels: needtriage
