### ISSUE TITLE
NUMBA - Building wheel for numba (setup.py) ... error

### ISSUE THREAD

**Issue by dhgokul** [numba/numba#6230] opened 2020-09-09 10:22 UTC
When install numba package i got below error . Any help appreciated !!

Collecting numba
Using cached numba-0.51.2.tar.gz (2.1 MB)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.6/dist-packages (from numba) (0.34.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from numba) (1.19.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from numba) (50.3.0)
Building wheels for collected packages: numba
Building wheel for numba (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sthq7y87/numba/setup.py'"'"'; file='"'"'/tmp/pip-install-sthq7y87/numba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-143d6zug
cwd: /tmp/pip-install-sthq7y87/numba/
Complete output (868 lines):
Using Intel TBB from: /usr
Using OpenMP from: True
running bdist_wheel
running build
got version from file /tmp/pip-install-sthq7y87/numba/numba/_version.py {'version': '0.51.2', 'full': '9d570961590c09a1eba748c9c37e91d1224fc9ad'}
running build_py

**Comment by stuartarchibald** [comment] 2020-09-09 11:42
Thanks for the report. Please could you provide the following to help diagnose this:

1. Which Os you are using.
2. Which hardware you are using.
3. The full log for the reported problem (is a reason provided for the build failure?).

Many thanks.

**Comment by esc** [comment] 2020-09-09 12:29
@dhgokul is this the same issue as reported here: https://github.com/numba/llvmlite/issues/628

**Comment by stuartarchibald** [comment] 2020-09-09 12:31
Closing as duplicate of numba/llvmlite#628, let's resolve this over there as it seems to involve a from-source build.

**Closed by stuartarchibald** 2020-09-09 12:31 UTC
Labels: needtriage, wheels
