### ISSUE TITLE
Compiling error with loop, works if there is a print statement though

### ISSUE THREAD

**Issue by dsm-72** [numba/numba#8210] opened 2022-06-29 19:14 UTC
## Reporting a bug

- [x ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I have a loop:

```python
for i, row in enumerate(data):
    if something:
       storage.append(thing)

np.vstack(storage)
```

This throws an error when compiled with `jit(forceobj=True)`

but if I add a print statement
```python
for i, row in enumerate(data):
    if something:
       storage.append(thing)

    print(i)
np.vstack(storage)
```

it runs. 

Not sure what is gong on

**Comment by esc** [comment] 2022-06-30 07:33
@dsm-72 thank you for reporting this, the example you listed is incomplete so we can not reproduce. Please submit a fully runnable reproducer (including imports) and the error message you receive when trying to compile, thank you.

**Comment by stuartarchibald** [comment] 2022-07-19 08:11
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed as completed by stuartarchibald** 2022-07-19 08:11 UTC
Labels: more info needed
