### ISSUE TITLE
Heap slower than without numba??

### ISSUE THREAD

**Issue by mha-py** [numba/numba#6975] opened 2021-04-25 21:46 UTC
Hey!

I was trying to make a batched "n largest elements" algorithm, hoping to parallelize it with numba, however the implementation of heappushpop seems to be slower than the python implementation,

```python
from heapq import heapify, heappushpop

#@njit(cache=True)
def nlargest(n, it):  # taken from heapq (simplified)
    result = list(it[:n])
    heapify(result)
    for elem in it:
        heappushpop(result, elem)
    #result.sort(reverse=True)
    return result

%time nlargest(20, np.array(10000*[7,3,4,7,2,3,4,6]))
# python: 50.3 ms
# numba: 330 ms
```

**Comment by stuartarchibald** [comment] 2021-04-26 10:57
Thanks for the report. I suspect the issue is could be down to single vs average timing. When measuring performance multiple runs are often used to get an average time, as Numba is a JIT it has to load itself (an entire compiler) and then actually JIT the function before running it, whilst the sample has `cache=True` could it be that `%time` is capturing compilation and import time too? In the following `timeit.timeit` is used to get an execution time from many runs.
```python
from heapq import heapify, heappushpop
from timeit import timeit
from numba import njit
import numpy as np

@njit(cache=True)
def nlargest(n, it):  # taken from heapq (simplified)
    result = list(it[:n])
    heapify(result)
    for elem in it:
        heappushpop(result, elem)
    #result.sort(reverse=True)
    return result

arr = np.array(10000*[7,3,4,7,2,3,4,6])
nlargest(20, arr) # trigger compilation to cache

t = timeit(stmt='nlargest(20, arr)', number=100, globals=globals())
print(t)
t = timeit(stmt='nlargest(20, arr)', number=100, globals=globals())
print(t)
```
this gives:
```
$ python issue6975.py 
0.2512762369999564
0.251613486999986

$ NUMBA_DISABLE_JIT=1 python issue6975.py 
1.7290780050000194
1.7348066239999298
```
i.e. Numba is about 7x faster.

Also note that in the original code the creation of the `NumPy` array is included in the timing cost.

**Comment by mha-py** [comment] 2021-04-26 15:50
I see, thanks for the clarification!

**Comment by stuartarchibald** [comment] 2021-04-26 16:08
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks and thanks for using Numba!

**Closed by stuartarchibald** 2021-04-26 16:08 UTC
Labels: needtriage, performance - run time
