### ISSUE TITLE
when to support python 3.11？

### ISSUE THREAD

**Issue by liukaiyueyuo** [numba/numba#8825] opened 2023-03-17 02:17 UTC
when to support python 3.11？
My environment is python 3.11，I need it by other python package who rely on numba

**Comment by esc** [comment] 2023-03-17 07:11
@liukaiyueyuo this is a duplicate of https://github.com/numba/numba/issues/8304 -- please subscribe to that issue for updates.

**Closed by esc** 2023-03-17 07:11 UTC
Labels: duplicate
