### ISSUE TITLE
Immutable error: "No implementation of function Function(<built-in function setitem>) found for signature"

### ISSUE THREAD

**Issue by remember9069** [numba/numba#7669] opened 2021-12-19 04:26 UTC
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,
I have a 2d-array filled with IDs of some entities, for now I am going to replace each value with a vector, so I create a 3d-array with ```np.zeros()``` and decorate the code with ```@njit``` as a means to accelerate it.
```python
import numpy as np
from numba import njit

tre_n_arr = np.empty([len(tre_n_split), max(tre_n_split, key=lambda x: len(x)), hidden_dim])
tre_n_arr.fill(0)


@njit
def emb():
    for line in range(len(tre_n_split)):
        for path in range(len(tre_n_split[line])):
            emb_vals = emb_n[tre_n_split[line][path]]
            for emb_val_idx in range(len(emb_vals)):
                emb_val = emb_vals[emb_val_idx]
                tre_n_arr[line][path][emb_val_idx] = emb_val

    return tre_n_arr
``` 
However, an error occurred:
```python
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(readonly array(float64, 1d, C), int64, float64)
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(readonly array(float64, 1d, C), int64, float64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 171.
    With argument(s): '(readonly array(float64, 1d, C), int64, float64)':
   Rejected as the implementation raised a specific error:
     TypeError: Cannot modify value of type readonly array(float64, 1d, C)
```

Obviously, ```[line], [path], [emb_val_idx] ```  are ``` <int>``` indices, while ```emb_val``` is a ``` <float>```  value. Of these,
```python
>>> setitem(readonly array(float64, 1d, C), int64, float64)
```
I'm quite confused about what these```array(float64, 1d, C), int64, float64```  are referring to，and would like to know how could I fix the error. Thanks in advance.

**Comment by gmarkall** [comment] 2021-12-20 11:01
The line:

```
>>> setitem(readonly array(float64, 1d, C), int64, float64)
```

describes the arguments to `__setitem__` in order. This is equivalent to writing:

```python
a[i] = v
```

where:

- `a` is a read-only 1D array of `float64` values that is C-contiguous (`readonly array(float64, 1d, C)`)
- `i` is an `int64`
- `v` is a `float64`.

I couldn't run your code to reproduce the error for more info (e.g. `tre_n_split` is undedefined) but somehow an array (or view) you are writing to is marked as read-only - perhaps its broadcasted or a view of something?

If you remove the `@njit` decorator, do you get a different error message that explains the issue in another way?

(For future reference - the [Numba Discourse](https://numba.discourse.group) is a good place to post questions like this, as there are more active users answering questions there than on this issue tracker)

**Comment by stuartarchibald** [comment] 2022-01-04 12:01
I think something like this would produce the same:
```python
import numpy as np
from numba import njit

tre_n_arr = np.empty((3, 4))
tre_n_arr.fill(0)


@njit
def emb():
    tre_n_arr[0][0] = 12

emb()
```
The issue is caused by Numba treating global values as compile time constants. In this case the array `tre_n_arr` would be considered constant and so is made read-only at compile time and so writing to it is a violation.

**Comment by gmarkall** [comment] 2022-01-10 15:25
Closing as it appears that the original question is answered and no further follow-up has been received.

**Closed by gmarkall** 2022-01-10 15:25 UTC
Labels: question
