### ISSUE TITLE
Process hangs with a specific sequence of add/removes on a set

### ISSUE THREAD

**Issue by JernejPuc** [numba/numba#8627] opened 2022-11-30 17:10 UTC
### Description

Compiling a function that should perform a specific sequence of add/remove operations on a set hangs the process. CTRL-C is not enough to abort it, it must be killed via terminal.

### To reproduce

The problematic sequence was originally longer and the example below is the shortest I could get that still hangs.

```python
from numba import njit


@njit
def bug():
    tmp = set()

    tmp.add(0)
    tmp.remove(0)
    tmp.add(1)
    tmp.add(2)
    tmp.remove(1)
    tmp.add(3)
    tmp.add(4)
    tmp.add(5)
    tmp.add(6)
    tmp.remove(4)
    tmp.add(7)
    tmp.remove(3)
    tmp.add(8)
    tmp.remove(7)
    tmp.add(9)
    tmp.remove(8)
    tmp.remove(9)
    tmp.add(10)
    tmp.add(11)
    tmp.add(12)
    tmp.add(13)
    tmp.remove(5)
    tmp.add(14)
    tmp.remove(13)
    tmp.add(15)

    return 0 in tmp


print(bug())
```

### Expected behaviour

Regular python version does not hang (in this case it should print out `False`). Other sequences also generally do not hang.

### Additional context

- The original sequence had different (larger) numbers. When the process still hanged after replacing them with smaller numbers, I thought that the numbers do not need to be specific, that only their symbolic order is important. However, now replacing e.g. all instances of 15 with 150 in the above example, I cannot reproduce the bug - the process behaves normally.
- Swapping the last line in the function for `return 0 in tmp.copy()` works - the process behaves normally.
- I was able to reproduce the bug on a different Linux machine with python 3.9 and the same numba version number.

### System/versions

```
OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.17

# Name                    Version                   Build
numba                     0.56.3           py38h417a72b_0  
python                    3.8.12               h12debd9_0  
```

**Comment by esc** [comment] 2022-11-30 17:13
IIRC this is known and there are both issues and PRs about it already, but alas it remains unsolved. Would recommend to check the issue tracker for duplicates.

**Comment by JernejPuc** [comment] 2022-11-30 17:30
I was unable to find any issues or solutions regarding this behaviour with sets. My current workaround is to simulate a set by using a typed dictionary, where values are arbitrary, e.g. all 0, since I only need its keys.

**Comment by esc** [comment] 2022-11-30 18:18
> I was unable to find any issues or solutions regarding this behaviour with sets. My current workaround is to simulate a set by using a typed dictionary, where values are arbitrary, e.g. all 0, since I only need its keys.

I just had another look, I think this may be a duplicate, or potentially related to : https://github.com/numba/numba/issues/6543

**Comment by JernejPuc** [comment] 2022-11-30 18:42
Thank you for finding that issue, I read through it and can confirm that this is a duplicate. Interestingly, my encounter with the bug also came from implementing A* and the last comment is referring to the same solution that I am using.

Since the issue is still open, I think this behaviour should be more known, perhaps noted in the official documentation. Running into a random series of add/removes that causes problems is not something one would expect to happen and a heads-up would help to avoid them.

**Comment by guilhermeleobas** [comment] 2022-11-30 23:25
Closing this issue as it is a duplicate of #6543. A potential fix for this issue is being developed in https://github.com/numba/numba/pull/7875

**Closed by guilhermeleobas** 2022-11-30 23:25 UTC
Labels: duplicate, bug - incorrect behavior
