### ISSUE TITLE
Support `str` as a construction method for strings

### ISSUE THREAD

**Issue by richardxing** [numba/numba#3989] opened 2019-04-17 20:06 UTC
Hi there, 

I am trying to create a string in nopython node but it fails. The version is 0.43.1. http://numba.pydata.org/numba-doc/latest/reference/pysupported.html 2.6.2.3 states 

> Strings can be passed into nopython mode as arguments, as well as constructed and returned from nopython mode.

Here is a minimal code example.  Thank you for your help!

```import numba
@numba.njit
def test():
    c = '1' #Literal[str]
    return c
test()
#test() works fine, but

@numba.njit
def test2():
    b = str(1)
    return b
test2()
#TypingError: cannot determine Numba type of <class 'type'>
```

numba.typeof(str(1)) shows it as unicode_type

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by esc** [comment] 2019-04-18 07:56
Yup, I can reproduce this locally.

**Comment by stuartarchibald** [comment] 2019-04-18 09:18
Thanks for the report. The error you are seeing is because the use of `str` as a constructor is not supported. The documentation on string support can be [found here](http://numba.pydata.org/numba-doc/dev/reference/pysupported.html#str).

**Comment by stuartarchibald** [comment] 2019-04-18 09:19
NOTE: Updated title to reflect the issue in hand.

**Comment by richardxing** [comment] 2019-04-18 15:12
Thanks, everyone!
@stuartarchibald the document said, as I quoted, strings can be constructed from the nopython mode. So can you modify the documentation to avoid confusion for others? Thanks!

**Comment by stuartarchibald** [comment] 2019-04-18 15:32
I think unfortunately "construction" as a term is overloaded (e.g. `str1+str2` is effectively constructing a new string). If you could please make a suggestion (or make a pull request) to clarify the documentation in a manner that you feel is less confusing it would be much appreciated, thanks.

**Comment by stuartarchibald** [comment] 2021-12-15 15:35
This is working on mainline for 0.55:
```python
from numba import njit
import numpy as np

@njit
def test2():
    b = str(1)
    c = str('abc')
    return b, c

print(test2())
```
Closing as fixed. Thanks!

**Closed by stuartarchibald** 2021-12-15 15:35 UTC
Labels: feature_request
