### ISSUE TITLE
problem has occurred in Numba's internals.

### ISSUE THREAD

**Issue by HiuNaoki** [numba/numba#3446] opened 2018-10-26 08:22 UTC
bellow, the error message and traceback 

```
/Users/hiunaoki/.pyenv/versions/anaconda2-4.2.0/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/Users/hiunaoki/.pyenv/versions/anaconda2-4.2.0/lib/python2.7/site-packages/numba/dataflow.py:386: RuntimeWarning: Python2 style print partially supported.  Please use Python3 style print.
  "Python3 style print.", RuntimeWarning)
Traceback (most recent call last):
  File "/Users/hiunaoki/Documents/workspace/Py/src/fx_bq_fft_5.py", line 407, in <module>
    _train = create_data(getData(train_week[0] , train_week[1]))
  File "/Users/hiunaoki/Documents/workspace/Py/src/fx_bq_fft_5.py", line 294, in create_data
    ,vector_ma2([t[p.open] for t in data])
  File "/Users/hiunaoki/.pyenv/versions/anaconda2-4.2.0/lib/python2.7/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
list index out of range

File "fx_bq_fft_5.py", line 162:
def vector_ma2(data):
    print("ma2 s")
    ^

1] During: lowering "data = arg(0, name=data)" at /Users/hiunaoki/Documents/workspace/Py/src/fx_bq_fft_5.py (162)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x118c953d0>> ignored

Process finished with exit code 1
```

**Comment by stuartarchibald** [comment] 2018-10-26 09:57
Thanks for the report. Do you have a simple piece of code for reproducing this issue please? It is not clear from the traceback what caused the problem. It might be worth also checking that your code works without Numba too? This can be done easily by setting the environment variable [`NUMBA_DISABLE_JIT` to non zero](http://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_JIT).

(NOTE: Reformatted the markdown in the OP)

**Comment by sklam** [comment] 2018-10-26 13:17
Guessing from the `RuntimeWarning: Python2 style print partially supported.  Please use Python3 style print` appearing in the trace, i think the source file is missing a `from __future__ import print_function`.

**Comment by stuartarchibald** [comment] 2019-04-01 09:52
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-04-01 09:52 UTC
Labels: needtriage
