### ISSUE TITLE
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode) Use of unsupported opcode (SETUP_EXCEPT) found

### ISSUE THREAD

**Issue by PADMAG6** [numba/numba#4400] opened 2019-08-02 10:17 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by PADMAG6** [comment] 2019-08-02 10:19
numba version:0.45.0
python:3.6.8

**Comment by stuartarchibald** [comment] 2019-08-02 10:42
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

Were I to guess, I think the code has a `try/except` block in use which is not supported by Numba.

**Comment by stuartarchibald** [comment] 2019-08-05 12:05
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed** 2019-09-11 14:53 UTC
Labels: no action required

**Comment by PedroRaposo** [comment] 2019-12-02 17:15
Hello,

I am having a similar problem as @PADMAG6.
I have the latest version of numba installed (0.46.0). I'm trying to replicate a simple code from https://umap-learn.readthedocs.io/en/0.4dev/plotting.html:

```
import sklearn.datasets
import pandas as pd
import numpy as np
import umap

pendigits = sklearn.datasets.load_digits()
mapper = umap.UMAP().fit(pendigits.data)
```

And this is the error output:
```
/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py:58: RuntimeWarning: inconsistent stack offset for block(offset:468, outgoing: [490, 532], incoming: [282, 394])
  warnings.warn("inconsistent stack offset for %s" % blk,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/AD/praposo/packages/umap-0.4dev/umap/umap_.py", line 1617, in fit
    self.graph_, self._sigmas, self._rhos = fuzzy_simplicial_set(
  File "/home/AD/praposo/packages/umap-0.4dev/umap/umap_.py", line 590, in fuzzy_simplicial_set
    sigmas, rhos = smooth_knn_dist(
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/untyped_passes.py", line 78, in run_pass
    func_ir = interp.interpret(bc)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/interpreter.py", line 103, in interpret
    self.dfa.run()
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 30, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 76, in run_on_block
    callback(info)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 304, in pop_info
    info.pop()
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 853, in pop
    return self.make_incoming()
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 880, in make_incoming
    ib.request_outgoing(self, ret, stack_index)
  File "/home/AD/praposo/anaconda3/envs/R2_env/lib/python3.8/site-packages/numba/dataflow.py", line 897, in request_outgoing
    varname = self.stack[stack_index - self.stack_offset]
IndexError: Failed in nopython mode pipeline (step: analyzing bytecode)
list index out of range
```

Is there something that I'm doing wrong?

Thank you in advance!

**Comment by stuartarchibald** [comment] 2019-12-02 17:26
@PADMAG6 Thanks for the report, I think what you are seeing is unrelated to the original issue. I think the error you can see is because you are using Python 3.8 which is not supported by Numba 0.46. The next release (0.47), which is due within the month, has Python 3.8 support.

**Comment by PedroRaposo** [comment] 2019-12-02 17:29
Ok. Thank you for the fast response!

A Seg, 2/12/2019, 17:26, stuartarchibald <notifications@github.com>
escreveu:

**Comment by stuartarchibald** [comment] 2019-12-02 17:34
@PedroRaposo no problem.
