### ISSUE TITLE
Parallel vs sequential for loop different results

### ISSUE THREAD

**Issue by miguelcarcamov** [numba/numba#7984] opened 2022-04-14 17:13 UTC
Hello I'm using Python 3.10.2 and numba 0.55.1. I am trying to do the following operation:

```
@njit(parallel=True)
def sum_parallel(data, idxs):
    data_len = len(data)
    grid = np.zeros((128, 128), dtype=np.float64)
    for k in prange(data_len):
        i = idxs[1][k]
        j = idxs[0][k]
        grid[i][j] += data[k]
    return grid

def sum_sequential(data, idxs):
    data_len = len(data)
    grid = np.zeros((128, 128), dtype=np.float64)
    for k in prange(data_len):
        i = idxs[1][k]
        j = idxs[0][k]
        grid[i][j] += data[k]
    return grid

data = np.random.random((8000))
idxs = np.random.randint(size=(2, 8000), low=0, high=128)

grid_parallel = sum_parallel(data,idxs)
grid_sequential = sum_sequential(data, idxs)
std_difference = np.std(grid_parallel-grid_sequential)
print(std_difference)
0.014976131305802937
```

I guess there is a race condition here, although I am not sure if this is a bug or if it is something that I have not taken into consideration when writing my parallel function, is there a way to provide a critical section?

**Comment by guilhermeleobas** [comment] 2022-04-15 19:22
Hi @miguelcarcamov, thanks for the report. I can reproduce the error when parallel is enabled. Maybe @stuartarchibald knows a workaround to this issue. 

Related discussion:
https://numba.discourse.group/t/how-do-i-use-thread-locks-in-nopython-mode/1258
https://numba.discourse.group/t/how-to-use-locks-in-nopython-mode/221

**Comment by stuartarchibald** [comment] 2022-04-19 09:37
There's no lock/critical section provided by Numba at present. Most of the information in relation to this is captured on discourse. I think the above code does exhibit a race condition in that the `idxs` array likely has repeated values and is being used as an index into `grid` for the purpose of accumulation. In the next release of Numba there will hopefully be support for obtaining the current thread ID, which means there could be a per-thread accumulation buffer that can be accessed in a thread safe manner, and then reduced outside of the parallel region.

**Comment by miguelcarcamov** [comment] 2022-04-19 09:49
@stuartarchibald thanks for your answer. Sad that there's no lock/critical sections, I thought that numba could recognize the shared variables and provide the lock automatically if there is a write operation on it. Anyway, thanks for the help ! Eager to see the next release of numba with thread ID support.

**Comment by stuartarchibald** [comment] 2022-04-19 10:06
@miguelcarcamov No problem. Whilst it'd be good to have critical sections, I think a lot could be done if atomic primitives were provided, they'd cover use cases such as the above and should be implemented first xref: https://github.com/numba/numba/issues/2988

**Comment by stuartarchibald** [comment] 2022-05-20 09:42
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!

**Closed by stuartarchibald** 2022-05-20 09:42 UTC
Labels: ParallelAccelerator, question
