### ISSUE TITLE
segmentation fault on list insert

### ISSUE THREAD

**Issue by eltrompetero** [numba/numba#3999] opened 2019-04-20 15:54 UTC
On the current official release v0.43.1 with Python 3.7.2. (I tried to install the latest dev version but it relies on LLVM 0.29dev which required too much work to install)

First, I've given a simple example which I think is the source of the problem in the following more complex example. I'm confused because in the second example the segfault only appears the second time the insertion loop is called.

```
# simple example
from numba import njit 

@njit
def test_append(s):
    s.append('0')
    
s = ['0']
test_append(s)
print(s)

# this throws seg fault
@njit
def test_insert(s):
    s.insert(0,'0')
    
s = ['0']
test_insert(s)
```

```
from numba import njit 
NUMERALS = '0123456789'
ALPHNUM = '0123456789ABCDEFGHJIKLMNOPQRSTUVWXYZ'

@njit
def xpotts_states(n, k):
    """Generator for iterating through all states for Potts model with k distinct states.

    Parameters
    ----------
    n : int
        Number of spins.
    k : int
        Number of distinct states. These are labeled by integers starting from 0 and must
        be <=36.

    Returns
    -------
    generator
    """

    assert n>0, "n cannot be <0"
    assert k>=2, "k cannot be <2"
   
    for i in range(k**n):
        state = base_repr(i, k)
        while len(state)<n:
            state.insert(0, '0')
        yield state

@njit
def base_repr(i, base):
    """Return decimal number in given base as list.
    
    Parameters
    ----------
    i : int
    base : int

    Returns
    -------
    list
    """

    assert i>=0 and base>=2
    
    if i==0:
        return ['0']

    if base<=10:
        return _small_base(i, base)

    assert base<=36
    return _large_base(i, base)

@njit
def _small_base(i, base):
    rep = []
    exponent = int(np.log(i)/np.log(base))
    term = int(i/base**exponent)
    # handle problematically rounded cases
    if term==base:
        exponent += 1
        term = 1
    rep.append(NUMERALS[term])
    i -= term*base**exponent
    
    exponent -= 1
    while exponent>=0:
        baseToExp = base**exponent
        if baseToExp>i:
            rep.append('0')
        else:
            term = int(i/baseToExp)
            rep.append(NUMERALS[term])
            i -= term*baseToExp
        exponent -= 1
    return rep
  
@njit
def _large_base(i, base):
    ALPHANUM = '0123456789ABCDEFGHJIKLMNOPQRSTUVWXYZ'
    rep = []
    exponent = int(np.log(i)/np.log(base))
    term = int(i/base**exponent)
    # handle problematically rounded cases
    if term==base:
        exponent += 1
        term = 1
    rep.append(ALPHANUM[term])
    i -= term*base**exponent
    
    exponent -= 1
    while exponent>=0:
        baseToExp = base**exponent
        if baseToExp>i:
            rep.append('0')
        else:
            term = int(i/baseToExp)
            rep.append(ALPHANUM[term])
            i -= term*baseToExp
        exponent -= 1
    return rep

f = xpotts_states(3,2)
next(f)
next(f)
```

**Comment by eltrompetero** [comment] 2019-04-20 15:57
Also, I'm aware that there are other ways to implement what I'm trying to do that avoid this particular problem. But this was bothering me.

**Comment by stuartarchibald** [comment] 2019-04-23 08:45
Thanks for the report, I can reproduce. This seems to also reproduce the problem:
```python
from numba import njit
@njit
def test_insert(x):
    x.insert(0, 'a')

x = ['z']
test_insert(x)
```
however, this does not:
```python
from numba import njit
@njit
def test_insert(x):
    x.insert(0, 1)

x = [1]
test_insert(x)
```
and neither does this:
```python
from numba import njit

@njit
def test_insert():
    x = ['z']
    x.insert(0, 'a')
    return x

test_insert()
```
I'm going to guess that the problem is somewhere in the  list-of-unicode insertion and reflection behaviours.

**Comment by stuartarchibald** [comment] 2019-07-18 10:26
Numba 0.45 (release upcoming) typed.List implementation works correctly in this situation, would suggest using that as reflected lists are being deprecated, thanks.

```python
from numba import njit
from numba.typed import List

@njit
def test_insert(x):
    x.insert(0, 'a')

x = List()
x.append('z')
test_insert(x)
print(x)
```
Closing.

**Closed by stuartarchibald** 2019-07-18 10:26 UTC
Labels: bug
