### ISSUE TITLE
Bug with addition assignment operator in an array when using njit(parallel=True)

### ISSUE THREAD

**Issue by edckev** [numba/numba#5100] opened 2020-01-17 16:28 UTC
Hi,

I want to select a subarray by using `slice` in a function which is decorated with `njit` with the option `Parallel=True`.

The following minimal working example tries to reproduce my code. In the real code, I create an array Y for each thread in the loop, then I test some condition and I increment the variable `n_Y` if the condition is True. I have simplified the code to just reproduce the error while keeping the essential elements.

```python
import numba as nb
import numpy as np

@nb.njit(nogil=True, cache=False, parallel=True)
def f():
    for i in nb.prange(4):
        Y = np.ones(10, dtype=np.float64)
        
        n_Y = 0
        n_Y += 1
        n_Y_sum = np.sum(Y[:n_Y])

f()
```

The last code works well by using both Windows 10 or Linux with the version 0.46 of numba. But when I am using the version 0.47 of numba, it works only on Windows 10 and I get the following error on Linux: 
![image](https://user-images.githubusercontent.com/12555787/72624669-a57b3d80-3947-11ea-82a6-491de95b6f3f.png)

But if I change the code a little bit in the following way, it's working :
- First solution : doing `n_Y +1 -1` in the slice
```python
import numba as nb
import numpy as np

@nb.njit(nogil=True, cache=False, parallel=True)
def f():
    for i in nb.prange(4):
        Y = np.ones(10, dtype=np.float64)
        
        n_Y = 0
        n_Y += 1
        n_Y_sum = np.sum(Y[:n_Y + 1 - 1])

f()
```
- Second solution : cast the variable `n_Y` into np.int64 in the slice
```python
import numba as nb
import numpy as np

@nb.njit(nogil=True, cache=False, parallel=True)
def f():
    for i in nb.prange(4):
        Y = np.ones(10, dtype=np.float64)
        
        n_Y = 0
        n_Y += 1
        n_Y_sum = np.sum(Y[: np.int64(n_Y)])

f()
```

I think the problem is related to the `addition assignment operator` because when I remove `n_Y+=1` and change it for `n_Y = 10` for example just to test, it works on Linux.
```python
import numba as nb
import numpy as np

@nb.njit(nogil=True, cache=False, parallel=True)
def f():
    for i in nb.prange(4):
        Y = np.ones(10, dtype=np.float64)
        
        n_Y = 10
        n_Y_sum = np.sum(Y[:n_Y])

f()
```

I want also to point out that I have tested this code on Linux with both versions of numba 0.47 and 0.48, and it doesn't work for any version If I don't use the tricks described before.

Thank you in advance for your answer.

**Comment by stuartarchibald** [comment] 2020-01-17 18:17
Thanks for the report, I can reproduce.

This:
```python
import numba as nb
import numpy as np

@nb.njit(nogil=True, cache=False, parallel=True)
def f():
    for i in nb.prange(4):
        Y = np.ones(10, dtype=np.float64)
        
        n_Y = 0
        n_Y += 1
        n_Y_sum = np.sum(Y[:n_Y])

f()
```
is hitting a bug in array analysis here:
```
  File "numba/array_analysis.py", line 763, in plus
    (var, offset) = x
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
cannot unpack non-iterable NoneType object
```
cc @DrTodd13

**Comment by DrTodd13** [comment] 2020-01-21 19:21
@stuartarchibald I am unable to reproduce on master.  This sounds vaguely like something fixed recently.  Did you merge anything in the last 4 days that could have fixed this?

**Comment by wevonosky** [comment] 2020-03-02 16:56
I am having the same issue as the OP. I have a function that compiles and runs fine using numba.njit but fails when I add the parallel=True argument. Numba version 0.48.0 Python 3.6 on Linux.

I can verify the above sample code fails on my machine, but I haven't been able to identify where the problem is arising in my code and whether or not the OP's fix works for me.

**Comment by stuartarchibald** [comment] 2020-03-02 17:01
Current master still has this bug (a4c4a8dce), https://github.com/numba/numba/issues/5100#issuecomment-575737665 reproduces exactly.

**Comment by stuartarchibald** [comment] 2020-03-02 17:02
@wevonosky If you can reduce your code to a small reproducer, please could you share it? Thanks!

**Comment by wevonosky** [comment] 2020-03-02 17:34
@stuartarchibald I can't seem to identify the source of the error and my code isn't simple enough to reduce down without spending a large amount of time doing so. I'm not certain my problem is with indexing, just that I get the same NoneType is not iterable error. 

Here is the full trace if it is helpful:

```
In [1]: runfile('/home/user/gen_scene.py', wdir='/home/user /simulation')
Traceback (most recent call last):

  File "/home/user /gen_scene.py", line 74, in <module>
    mipmap, east, north)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/typed_passes.py", line 349, in run_pass
    lower.lower()

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/lowering.py", line 195, in lower
    self.lower_normal_function(self.fndesc)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/lowering.py", line 248, in lower_normal_function
    entry_block_tail = self.lower_function_body()

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/lowering.py", line 273, in lower_function_body
    self.lower_block(block)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)

  File "/home/user/.conda/envs/py36/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)

  File "/home/user/.conda/envs/py36/lib/python3.6/site-packages/numba/six.py", line 669, in reraise
    raise value

LoweringError: Failed in nopython mode pipeline (step: convert to parfors)
'NoneType' object is not iterable
```

**Comment by stuartarchibald** [comment] 2020-03-02 18:26
@wevonosky thanks for the log. I'm afraid that the bug you are seeing is unlikely related to the OP. The error you are seeing comes from lowering (translating Numba internal representation of your code to LLVM IR) whereas the OP has a problem from array analysis which is earlier on in the compilation pipeline. If you can reduce the code to make a reproducer please feel free to open a ticket and someone will take a look. Thanks!

**Comment by P-Tillmann** [comment] 2020-03-26 12:01
Hi,
also came across this error, with numba version 0.48 on linux.
Heres the minimal example, failing in array analysis.

```
@nb.jit(nopython=True, parallel=True)
def f3():
    arr = np.arange(20)
    for i in nb.prange(2):
        for j in range(20):
            idx = j

        _ = arr[:idx]

f3()
```
I hope this helps and thanks for the great work you are doing at numba!

**Comment by stuartarchibald** [comment] 2020-03-26 21:23
@P-Tillmann thanks, https://github.com/numba/numba/issues/5439 tracks.

**Comment by stuartarchibald** [comment] 2020-03-26 21:24
Closing as OP doesn't replicate on master as of e20b179

**Closed by stuartarchibald** 2020-03-26 21:24 UTC
Labels: ParallelAccelerator, bug
