### ISSUE TITLE
Anaconda 3 and PowerBI Connection Error

### ISSUE THREAD

**Issue by lwernke** [numba/numba#5649] opened 2020-04-29 11:51 UTC
Hi everyone! 
I'm trying to connect my Power BI app with Anaconda 3, to perform some machine learning analysis. To do it, i'm following the steps listed in []https://towardsdatascience.com/machine-learning-in-power-bi-using-pycaret-34307f09394a. 

Everything is fine, until I executed the code bellow. It always returns an error. 
`from pycaret.clustering import *`
`dataset = get_clusters(data = dataset)`

Anyone have any clue about how to fix it? 

DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pycaret\preprocess.py", line 26, in <module>
    from pyod.models.knn import KNN
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pyod\__init__.py", line 4, in <module>
    from . import utils
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pyod\utils\__init__.py", line 11, in <module>
    from .stat_models import pairwise_distances_no_broadcast
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pyod\utils\stat_models.py", line 11, in <module>
    from numba import njit
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: Não foi possível encontrar o módulo especificado.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\lwernke\Anaconda3\envs\myenv\python.exe

Detalhes:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
Traceback (most recent call last):
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pycaret\preprocess.py", line 26, in <module>
    from pyod.models.knn import KNN
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pyod\__init__.py", line 4, in <module>
    from . import utils
  File "C:\Users\lwernke\Anaconda3\envs\myenv\lib\site-packages\pyod\utils\__ini...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

**Comment by esc** [comment] 2020-04-29 12:22
@lwernke thanks for asking about this on the Numba issue tracker. This is most likely a duplicate of #5600 -- there is a workaround here: https://github.com/numba/numba/issues/5600#issuecomment-617937885

**Comment by stuartarchibald** [comment] 2020-05-01 16:31
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-05-01 16:31 UTC
Labels: duplicate
