### ISSUE TITLE
minimal not working example producing error on my PC

### ISSUE THREAD

**Issue by bmer** [numba/numba#1706] opened 2016-02-11 22:01 UTC
Hi all,

MnWE: https://gist.github.com/bmer/e1c637385c543b4f3305

When this script is run, I get the following error:

```
    infer.propagate()
  File "A:\anaconda\lib\site-packages\numba\typeinfer.py", line 565, in propagate
    raise errors[0]
TypingError: cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'b'

Failed at nopython (nopython frontend)
cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'b'
```
I am using 32-bit Anaconda.

Are you able to reproduce this error too?

Kind regards,
Brian

**Comment by sklam** [comment] 2016-02-11 22:06
Yes, I can reproduce this error on 64-bit osx.  Hmm... I thought we have implicit cast between arrays of different dtype

**Comment by sklam** [comment] 2016-02-11 22:32
Here's a smaller reproducer:

```python

import numba as nb
import numpy as np

@nb.jit(nopython=True)
def f():
    a = np.zeros(2, dtype=np.float64)
    b = np.zeros(2, dtype=np.float32)
    for i in range(1):
        b = a

f()
```

It turns out we do not allow implict cast for arrays due to a limitation in the compiler's variable definition rule.  The 1st assignment to `b` is the only definition.  The 2nd assignment will reuse the 1st variable definition.  If implicit cast is allowed, the loop will change the the array type before it.  

However, it is not easy to fix this.  Let say the 2nd assignment creates a new variable for `b`.  We version the old variable as `b.1` and the new variable as `b.2`.  `b.1` and `b.2` will have two different dtypes, float32 and float64 respectively.  After the loop, if `b` is referenced, what should be the type of `b`?  For strict python semantic, it can be either `b.1` or `b.2`.  Implicitly casting can be dangerous.  Another option is to create a different path of different version of the variable.  But we don't know if it will cause code bloat.

Or, we keep disallow this kind of usage.  I think rpython has the same problem.

**Comment by pitrou** [comment] 2016-02-11 22:44
Note that the simple workaround is to not reuse the same variable name for different things (which is good practice, by the way, from a software engineering perspective).

**Comment by bmer** [comment] 2016-02-11 23:15
@pitrou Could you recommend how I can rewrite this? The use case is actually something like this: https://gist.github.com/bmer/66d2485a4727b9eebc62

which is just the bisection algorithm -- I want to update `test_coord` based on what `a` and `b` are every loop, and then update `a` or `b` based on some condition, also every loop.

**Comment by pitrou** [comment] 2016-02-11 23:18
If your goal is to stay in the float32 realm then `test_coord = np.float32(0.5) * (a + b)` should probably work. The problem is that floating-point literals (like `0.5`) are considered to be double-precision by default.

**Comment by seibert** [comment] 2016-02-11 23:19
You also don't need to initialize `test_coord` before the loop, since you immediately replace the value anyway.

**Comment by seibert** [comment] 2016-02-11 23:20
Also, if you want `float32` precision for speed reasons, you should make sure to cast `a` and `b` to `float32` before operating on them (which it sounds like they are not).

**Comment by bmer** [comment] 2016-02-11 23:51
Ahh, I see! I was switching to float32 for memory reasons -- there's a memory leak somewhere, but I haven't been able to trace it yet. I suppose what i should do then is go back to float64, and redouble my efforts to trace the memory leak, because its unlikely that switching to float32 or float16 will help?

**Comment by seibert** [comment] 2016-02-12 14:59
I don't know if we have support for `float16` in Numba.  We'll need to take a look at that, though, since NVIDIA's Pascal GPU architecture will introduce native instructions for manipulating `float16`.  (Someone realized that neural networks do not need high precision, so being able to natively handle `float16` effectively gives you a free 2x in memory bandwidth, register space, and floating point throughput.)

**Comment by pitrou** [comment] 2016-02-12 15:11
No, we don't support `float16` yet.

**Comment by seibert** [comment] 2016-02-12 16:06
And x86 doesn't have native `float16` instruction support anyway, so the motivation is pretty low.

**Comment by seibert** [comment] 2016-04-27 16:10
I think we can close this issue.  We're not prepared to support this kind of type polymorphism in Numba's nopython mode.

**Closed by seibert** 2016-04-27 16:10 UTC
