### ISSUE TITLE
x**(-1) is zero when x is integer

### ISSUE THREAD

**Issue by ruoyu0088** [numba/numba#8169] opened 2022-06-17 07:38 UTC
Version: Numba 0.55.1

The result of f() and f_jit() is different:

```
import numba

def f(x):
    return x**(-1)

f_jit = numba.jit(f)
f(2), f_jit(2)
```

output:

```
(0.5, 0)
```

**Comment by guilhermeleobas** [comment] 2022-06-17 16:49
Hi @ruoyu0088, thanks for the report, I can reproduce the error.

This bug happens due to a combination of two things. First, `a ^ (-b) = (1 / a) ^ b`, results in a float value, but Numba types `math.pow` as `(a: int, b: int) -> int`. Second, at the impl. function, when `b < 0`, Numba truncates the result of `a ^ (-b)` to the nearest integer, `0`.

https://github.com/numba/numba/blob/57ce5528af436d5269dd4aa34f24b58a2063cef2/numba/core/typing/builtins.py#L251-L253

https://github.com/numba/numba/blob/57ce5528af436d5269dd4aa34f24b58a2063cef2/numba/cpython/numbers.py#L218-L230

If you know the exponent is `< 0`, I suggest changing the code to do the division first to avoid this kind of problem.

I am going to close this issue as it is a duplicate of https://github.com/numba/numba/issues/7012 which tracks the same issue.

**Closed by guilhermeleobas** 2022-06-17 16:49 UTC
Labels: duplicate, bug - numerically incorrect
