### ISSUE TITLE
Numba interfers with Pytest causing Python to crash on windows. 

### ISSUE THREAD

**Issue by CiaranWelsh** [numba/numba#8223] opened 2022-07-05 14:56 UTC
## Reporting a bug

- [Y ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ Y] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Pytest interacts badly with numba. For instance, this simple script: 
```
import pytest 
import numba

def test():
    print("D")
```
crashes Python 
```
collecting ... Windows fatal exception: code 0xc0000139

Current thread 0x00003c90 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
```
I've traced the error to `numba/misc/appdirs`, specifically with the following code section: 
```
if system == "win32":
    try:
        import win32com.shell
        _get_win_folder = _get_win_folder_with_pywin32
    except ImportError:
        try:
            from ctypes import windll
            _get_win_folder = _get_win_folder_with_ctypes
        except ImportError:
            try:
                import com.sun.jna
                _get_win_folder = _get_win_folder_with_jna
            except ImportError:
                _get_win_folder = _get_win_folder_from_registry
```

I am using miniconda environment Python 3.9  numba version 0.55.2 on Windows 11.

**Comment by esc** [comment] 2022-07-05 15:46
> Pytest interacts badly with numba. For instance, this simple script:

@CiaranWelsh thank you for asking about this. This is a known issue. Both pytest and Numba rewrite bytecode so that can result in strange errors. As a result it is not recommended to use pytest when testing Numba and we have a custom test runner which you can read about here:

https://numba.readthedocs.io/en/stable/developer/contributing.html#running-tests

**Comment by seibert** [comment] 2022-07-06 14:28
I'm trying to reproduce this bug, but need some additional details, since I think the cause is something subtle:

* What channel did you get the Numba 0.55.2 package and pytest from? (Numba 0.55.2 hasn't been released in the Anaconda distribution yet, so I am assuming you either got it from conda-forge or from the numba channel?)
* Is the above reproducer script complete?  It defines a function but never runs it, so the only statements that do anything are the import of pytest and the import of numba, correct?

**Comment by seibert** [comment] 2022-07-06 14:32
I don't see the bug on Windows 10 with Numba 0.55.1 and pytest 7.1.2, both from the Anaconda main channel, but that is not exactly the configuration listed above, so I'll need to try again with something more similar once I get more details.

**Comment by seibert** [comment] 2022-07-07 20:46
OK, I have access to a Windows 11 system now, but I have not been able to reproduce the above crash bug.  I've created environments both ways:
```
conda create -n issue_8223_cf -c conda-forge python=3.9 pytest numba=0.55.2
```
and
```
conda create -n issue_8223 -c numba python=3.9 pytest numba=0.55.2
```

And the script:
```
import pytest
import numba

def test():
    print("D")
```
does not produce the crash seen above.  Can you give more information about your environment?  Maybe the output of `conda list`?

**Comment by stuartarchibald** [comment] 2022-08-15 14:25
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2022-08-15 14:25 UTC
Labels: needtriage, more info needed
