### ISSUE TITLE
Compilation is falling back to object mode WITH looplifting enabled

### ISSUE THREAD

**Issue by fenglinxiu** [numba/numba#4461] opened 2019-08-18 10:12 UTC
### code:
```
def calc(keep_stock_threshold, buy_change_threshold):
    trade_strategy2 = TradeStrategy2()
    TradeStrategy2.set_keep_stock_threshold(keep_stock_threshold)
    TradeStrategy2.set_buy_change_threshold(buy_change_threshold)
    trade_loop_back = TradeLoopBack(trade_days, trade_strategy2)
    trade_loop_back.execute_trade()
    profit = 0.0 if len(trade_loop_back.profit_arr) == 0 else reduce(lambda a, b: a + b, trade_loop_back.profit_arr)
    return profit, keep_stock_threshold, buy_change_threshold

keep_stock_list = list(range(1, 504, 1))
buy_change_list = [buy_change / 100 for buy_change in list(range(-1, -100, -1))]
def do_single_task():
    task_list = list(itertools.product(keep_stock_list, buy_change_list))
    print('笛卡尔积参数集合总共有：{} 个'.format(len(task_list)))
    for keep_stock_threshold, buy_change_threshold in task_list:
        calc(keep_stock_threshold, buy_change_threshold)
%time do_single_task()

import numba as nb
do_single_task_nb = nb.jit(do_single_task)
%time do_single_task_nb()
```
### error:
```
<ipython-input-64-31e59472e89b>:3: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "do_single_task" failed type inference due to: Untyped global name 'calc': cannot determine Numba type of <class 'function'>

File "<ipython-input-64-31e59472e89b>", line 7:
def do_single_task():
    <source elided>
    for keep_stock_threshold, buy_change_threshold in task_list:
        calc(keep_stock_threshold, buy_change_threshold)
        ^

  def do_single_task():
<ipython-input-64-31e59472e89b>:3: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "do_single_task" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "<ipython-input-64-31e59472e89b>", line 6:
def do_single_task():
    <source elided>
    print('笛卡尔积参数集合总共有：{} 个'.format(len(task_list)))
    for keep_stock_threshold, buy_change_threshold in task_list:
    ^

  def do_single_task():
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    660     try:
--> 661         yield
    662     except NumbaError as e:

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 

~/anaconda3/lib/python3.7/site-packages/numba/pylowering.py in lower_inst(self, inst)
    175         else:
--> 176             raise NotImplementedError(type(inst), inst)
    177 

NotImplementedError: (<class 'numba.ir.Print'>, <numba.ir.Print object at 0x1c2c1ea898>)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<timed eval> in <module>

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    368                     e.patch_message(''.join(e.args) + help_msg)
    369             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 370             raise e
    371 
    372     def inspect_llvm(self, signature=None):

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    325                 argtypes.append(self.typeof_pyval(a))
    326         try:
--> 327             return self.compile(tuple(argtypes))
    328         except errors.TypingError as e:
    329             # Intercept typing error that may be due to an argument

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, sig)
    657 
    658             self._cache_misses[sig] += 1
--> 659             cres = self._compiler.compile(args, return_type)
    660             self.add_overload(cres)
    661             self._cache.save_overload(sig, cres)

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    953     pipeline = pipeline_class(typingctx, targetctx, library,
    954                               args, return_type, flags, locals)
--> 955     return pipeline.compile_extra(func)
    956 
    957 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    375         self.lifted = ()
    376         self.lifted_from = None
--> 377         return self._compile_bytecode()
    378 
    379     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    884         """
    885         assert self.func_ir is None
--> 886         return self._compile_core()
    887 
    888     def _compile_ir(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    871         self.define_pipelines(pm)
    872         pm.finalize()
--> 873         res = pm.run(self.status)
    874         if res is not None:
    875             # Early pipeline completion

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    252                     # No more fallback pipelines?
    253                     if is_final_pipeline:
--> 254                         raise patched_exception
    255                     # Go to next fallback pipeline
    256                     else:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event("-- %s" % stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_objectmode_frontend(self)
    461         if self.flags.enable_looplift:
    462             assert not self.lifted
--> 463             cres = self.frontend_looplift()
    464             if cres is not None:
    465                 raise _EarlyPipelineCompletion(cres)

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in frontend_looplift(self)
    433                               self.args, self.return_type,
    434                               outer_flags, self.locals,
--> 435                               lifted=tuple(loops), lifted_from=None)
    436             return cres
    437 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_ir(typingctx, targetctx, func_ir, args, return_type, flags, locals, lifted, lifted_from, is_lifted_loop, library, pipeline_class)
   1015                                   args, return_type, flags, locals)
   1016         return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
-> 1017                                 lifted_from=lifted_from)
   1018 
   1019 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_ir(self, func_ir, lifted, lifted_from)
    383 
    384         self._set_and_check_ir(func_ir)
--> 385         return self._compile_ir()
    386 
    387     def stage_analyze_bytecode(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_ir(self)
    891         """
    892         assert self.func_ir is not None
--> 893         return self._compile_core()
    894 
    895 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    871         self.define_pipelines(pm)
    872         pm.finalize()
--> 873         res = pm.run(self.status)
    874         if res is not None:
    875             # Early pipeline completion

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    252                     # No more fallback pipelines?
    253                     if is_final_pipeline:
--> 254                         raise patched_exception
    255                     # Go to next fallback pipeline
    256                     else:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event("-- %s" % stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    709         """
    710         lowerfn = self.backend_object_mode
--> 711         self._backend(lowerfn, objectmode=True)
    712 
    713         # Warn, deprecated behaviour, code compiled in objmode without

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    685             self.library.enable_object_caching()
    686 
--> 687         lowered = lowerfn()
    688         signature = typing.signature(self.return_type, *self.args)
    689         self.cr = compile_result(

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in backend_object_mode(self)
    657                                      self.library,
    658                                      self.func_ir,
--> 659                                      self.flags)
    660 
    661     def backend_nopython_mode(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
   1146     with targetctx.push_code_library(library):
   1147         lower = pylowering.PyLower(targetctx, library, fndesc, interp)
-> 1148         lower.lower()
   1149         if not flags.no_cpython_wrapper:
   1150             lower.create_cpython_wrapper()

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower(self)
    175         if self.generator_info is None:
    176             self.genlower = None
--> 177             self.lower_normal_function(self.fndesc)
    178         else:
    179             self.genlower = self.GeneratorLower(self)

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    216         # Init argument values
    217         self.extract_function_arguments()
--> 218         entry_block_tail = self.lower_function_body()
    219 
    220         # Close tail of entry block

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_function_body(self)
    241             bb = self.blkmap[offset]
    242             self.builder.position_at_end(bb)
--> 243             self.lower_block(block)
    244 
    245         self.post_lower()

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    256             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 
    260     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    667         from numba import config
    668         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 669         six.reraise(type(newerr), newerr, tb)
    670 
    671 

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.Print'>, <numba.ir.Print object at 0x1c2c1ea898>)

File "<ipython-input-64-31e59472e89b>", line 5:
def do_single_task():
    <source elided>
    task_list = list(itertools.product(keep_stock_list, buy_change_list))
    print('笛卡尔积参数集合总共有：{} 个'.format(len(task_list)))
    ^

[1] During: lowering "print($0.14)" at <ipython-input-64-31e59472e89b> (5)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment] 2019-08-19 08:46
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

It looks like Numba might be able to accelerate some part of your code. If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by fenglinxiu** [comment] 2019-08-20 10:33
> Thanks for the report. Please could you provide more information about what caused this problem:
> 
> 1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
> 2. Any data needed to run the code.
> 3. The full trace back of the exception.
> 
> Thanks.
> 
> It looks like Numba might be able to accelerate some part of your code. If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

Thanks for your reply. This link has the full code: https://github.com/bbfamily/abu/blob/master/ipython/%E7%AC%AC%E4%BA%8C%E7%AB%A0-%E9%87%8F%E5%8C%96%E8%AF%AD%E8%A8%80%E2%80%94%E2%80%94Python.ipynb

using jit area : "In [60]:"

![1566297168875](https://user-images.githubusercontent.com/6799138/63340129-ee1ed280-c378-11e9-9dea-51cfc0b8d934.jpg)

**Comment by stuartarchibald** [comment] 2019-08-21 10:22
Thanks for the code. I think that whilst this is a problem in that Numba cannot handle the `ir.Print` node, fundamentally the code presented in the notebook would need adapting to be more amenable to computation by Numba.

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by fenglinxiu** [comment] 2019-08-25 12:19
I find out the reason. Using "forceobj=True" will make it work.
```
keep_stock_list = list(range(1, 504, 1))
buy_change_list = [buy_change / 100 for buy_change in list(range(-1, -100, -1))]
from numba import jit
**@jit(forceobj=True)**
def do_single_task():
    task_list = list(itertools.product(keep_stock_list, buy_change_list))
    print('笛卡尔积参数集合总共有：{} 个'.format(len(task_list)))
    for keep_stock_threshold, buy_change_threshold in task_list:
        calc(keep_stock_threshold, buy_change_threshold)
```

**Comment by stuartarchibald** [comment] 2019-08-26 08:43
`forceobj=True` means that the code will essentially run in the interpreter, which will probably not make it any quicker, and due to various overheads is quite likely to make it slower.

A description of nopython vs. object mode can be found here http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode

**Comment by stuartarchibald** [comment] 2020-05-12 12:04
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-05-12 12:04 UTC
Labels: wontfix

**Comment by sophronesis** [comment] 2020-06-05 12:51
Same issue here.
Trying to emulate np.tile because it isn't supported in numba
```
@jit()
def numpyTile(obj, len_):
    withdim = np.expand_dims(obj, axis=0)
    unstacked = np.repeat(withdim, len_, axis=0)
    return np.concatenate(unstacked)

print(numpyTile(np.array([1, 2, 3]), 2))
```

and thats what i get

STDOUT:

```
[1 2 3 1 2 3]
```
STDERR:

```
<ipython-input-34-5c02ce6622a3>:23: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "numpyTile" failed type inference due to: Invalid use of Function(<function repeat at 0x7f7804436d90>) with argument(s) of type(s): (array(int64, 2d, C), int64, axis=Literal[int](0))
 * parameterized
In definition 0:
    TypeError: np_repeat() got an unexpected keyword argument 'axis'
    raised from /usr/local/lib/python3.6/dist-packages/numba/core/typing/templates.py:579
In definition 1:
    TypeError: np_repeat() got an unexpected keyword argument 'axis'
    raised from /usr/local/lib/python3.6/dist-packages/numba/core/typing/templates.py:579
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function repeat at 0x7f7804436d90>)
[2] During: typing of call at <ipython-input-34-5c02ce6622a3> (26)


File "<ipython-input-34-5c02ce6622a3>", line 26:
def numpyTile(obj, len_):
    <source elided>
    withdim = np.expand_dims(obj, axis=0)
    unstacked = np.repeat(withdim, len_, axis=0)
    ^

  @jit()
/usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:178: NumbaWarning: Function "numpyTile" was compiled in object mode without forceobj=True.

File "<ipython-input-34-5c02ce6622a3>", line 24:
@jit()
def numpyTile(obj, len_):
^

  state.func_ir.loc))
/usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "<ipython-input-34-5c02ce6622a3>", line 24:
@jit()
def numpyTile(obj, len_):
^

  state.func_ir.loc))
```

**Comment by stuartarchibald** [comment] 2020-06-08 10:39
@sophronesis if you use features that are unsupported, and also don't specify `nopython=True` in the `@jit` decorator, then Numba will fall back to using object mode. Suggested reading: http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode

Hope this helps.
