### ISSUE TITLE
numba segmentation fault on Python 3.7.4

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#4323] opened 2019-07-14 09:49 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

_Kind of_: I will try with 0.45 when the wheels are out :)

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
$ cat fail.py 
from numba import njit
import numpy as np

@njit
def foo():
    yield np.array([ 1.0, 1.0, 1.0])

list(foo())
```

With Python 3.7.3:

```
$ python fail.py
$ # No news, good news!
```

With Python 3.7.4:

```
$ python fail.py 
Segmentation fault
$ PYTHONFAULTHANDLER=1 python fail.py
Fatal Python error: Segmentation fault

Current thread 0x00007f1d57b09080 (most recent call first):
  File "fail.py", line 8 in <module>
Segmentation fault
$ gdb /home/juanlu/.pyenv/versions/poliastro37_4/bin/python
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/juanlu/.pyenv/versions/poliastro37_4/bin/python...done.
warning: File "/home/juanlu/.pyenv/versions/3.7.4/bin/python3.7-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/juanlu/.pyenv/versions/3.7.4/bin/python3.7-gdb.py
line to your configuration file "/home/juanlu/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/juanlu/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) run fail.py
Starting program: /home/juanlu/.pyenv/versions/3.7.4/envs/poliastro37_4/bin/python fail.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec9c9700 (LWP 8103)]
[New Thread 0x7fffec1c8700 (LWP 8104)]
[New Thread 0x7fffe79c7700 (LWP 8105)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fe446b in generator_dealloc (gen=0x7fffdf9ba9b0) at numba/_dynfunc.c:352
352	numba/_dynfunc.c: No such file or directory.
```

**Comment by Juanlu001** [comment] 2019-07-14 10:05
This problem also appears in numba 0.43, only in Python 3.7.4.

**Comment by stuartarchibald** [comment] 2019-07-15 10:25
Thanks for the report, I can reproduce. This is a variant of the problem reported in #4313. Essentially, the closure deallocation sequence now has a segfault.

**Comment by stuartarchibald** [comment] 2019-07-15 11:16
As noted here https://github.com/numba/numba/issues/4313#issuecomment-511361696 recompilation of Numba against 3.7.4 helps, but the generators also need inlining turned off to make LLVM happy, this needs some investigation, but with the two described fixes the above works.

**Comment by stuartarchibald** [comment] 2019-07-18 10:16
Fixed by https://github.com/numba/numba/pull/4328 which is now on mainline, the upcoming 0.45.0 release will contain this fix.

**Closed by stuartarchibald** 2019-07-18 10:16 UTC
Labels: bug, duplicate

**Comment by moluzhui** [comment] 2022-03-19 05:32
When I was in python3.10 and numba0.55.1, sometimes I could run and sometimes there were segmentation failed errors
```
run with  10  iterations
Windows fatal exception: code 0xc0000374

Current thread 0x00003c04 (most recent call first):
....
```

**Comment by TnzGit** [comment] 2022-06-06 10:34
> When I was in python3.10 and numba0.55.1, sometimes I could run and sometimes there were segmentation failed errors
> 
> ```
> run with  10  iterations
> Windows fatal exception: code 0xc0000374
> 
> Current thread 0x00003c04 (most recent call first):
> ....
> ```
> 
> > numba+numpy+matplotlab

I ran into the same problem with python 3.10.4 and numba 0.55.2.

**Comment by Joueswant** [comment] 2022-12-01 17:53
> > When I was in python3.10 and numba0.55.1, sometimes I could run and sometimes there were segmentation failed errors
> > ```
> > run with  10  iterations
> > Windows fatal exception: code 0xc0000374
> > 
> > Current thread 0x00003c04 (most recent call first):
> > ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > numba+numpy+matplotlab
> 
> I ran into the same problem with python 3.10.4 and numba 0.55.2.

I also ran into the same problem, for an interative script that uses Numba in some parts of the code. After finishing a block of iterations, I got a `Segmentation fault` from the OS and the scripts automatically breaks

The script also uses no other python module written in C (asides from Numpy).

I am also using Python 3.10.5 / Numba 0.55.1 / Ubuntu 20.04.5 LTS

I am afraid I am not able to reproduce the issue
