### ISSUE TITLE
Numba has issue running from the Umap install

### ISSUE THREAD

**Issue by chaunceychason** [numba/numba#5414] opened 2020-03-24 02:43 UTC
I have had this issue come up before and had an issue with the compatibility of some functions. 

```pytb
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "../../../.local/lib/python3.6/site-packages/umap/umap_.py", line 107:
def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):
    <source elided>
    #rho = np.zeros(distshape)
    rho = np.zeros(distances.shape[0])
    ^

[1] During: lowering "$0.24 = call $0.19($0.23, func=$0.19, args=[Var($0.23, /Users/nc/.local/lib/python3.6/site-packages/umap/umap_.py (107))], kws=(), vararg=None)" at /Users/nc/.local/lib/python3.6/site-packages/umap/umap_.py (107)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

With that said, this was in the code beforehand - 

```pytb
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-3-3c7606c21f87> in <module>
----> 1 umapobj.fit_transform(olddata)

~/.local/lib/python3.6/site-packages/umap/umap_.py in fit_transform(self, X, y)
   1607             Embedding of the training data in low-dimensional space.
   1608         """
-> 1609         self.fit(X, y)
   1610         return self.embedding_
   1611 

~/.local/lib/python3.6/site-packages/umap/umap_.py in fit(self, X, y)
   1426                 self.set_op_mix_ratio,
   1427                 self.local_connectivity,
-> 1428                 self.verbose,
   1429             )
   1430         else:

~/.local/lib/python3.6/site-packages/umap/umap_.py in fuzzy_simplicial_set(X, n_neighbors, random_state, metric, metric_kwds, knn_indices, knn_dists, angular, set_op_mix_ratio, local_connectivity, verbose)
    483 
    484     sigmas, rhos = smooth_knn_dist(
--> 485         knn_dists, n_neighbors, local_connectivity=local_connectivity
    486     )
    487 

/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                     e.patch_message(''.join(e.args) + help_msg)
    366             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 367             raise e
    368 
    369     def inspect_llvm(self, signature=None):

/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    322                 argtypes.append(self.typeof_pyval(a))
    323         try:
--> 324             return self.compile(tuple(argtypes))
    325         except errors.TypingError as e:
    326             # Intercept typing error that may be due to an argument

/anaconda3/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    653 
    654             self._cache_misses[sig] += 1
--> 655             cres = self._compiler.compile(args, return_type)
    656             self.add_overload(cres)
    657             self._cache.save_overload(sig, cres)

/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    902     pipeline = pipeline_class(typingctx, targetctx, library,
    903                               args, return_type, flags, locals)
--> 904     return pipeline.compile_extra(func)
    905 
    906 

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    365         self.lifted = ()
    366         self.lifted_from = None
--> 367         return self._compile_bytecode()
    368 
    369     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    833         """
    834         assert self.func_ir is None
--> 835         return self._compile_core()
    836 
    837     def _compile_ir(self):

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    820         self.define_pipelines(pm)
    821         pm.finalize()
--> 822         res = pm.run(self.status)
    823         if res is not None:
    824             # Early pipeline completion

/anaconda3/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    242                 try:
    243                     event(stage_name)
--> 244                     stage()
    245                 except _EarlyPipelineCompletion as e:
    246                     return e.result

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in stage_nopython_backend(self)
    694         """
    695         lowerfn = self.backend_nopython_mode
--> 696         self._backend(lowerfn, objectmode=False)
    697 
    698     def stage_compile_interp_mode(self):

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    644             self.library.enable_object_caching()
    645 
--> 646         lowered = lowerfn()
    647         signature = typing.signature(self.return_type, *self.args)
    648         self.cr = compile_result(

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in backend_nopython_mode(self)
    631                 self.return_type,
    632                 self.calltypes,
--> 633                 self.flags)
    634 
    635     def _backend(self, lowerfn, objectmode):

/anaconda3/lib/python3.6/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags)
   1021 
   1022     lower = lowering.Lower(targetctx, library, fndesc, interp)
-> 1023     lower.lower()
   1024     if not flags.no_cpython_wrapper:
   1025         lower.create_cpython_wrapper(flags.release_gil)

/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215 
    216         # Close tail of entry block

/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240 
    241         self.post_lower()

/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 
    256     def create_cpython_wrapper(self, release_gil=False):

/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/anaconda3/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    605         from numba import config
    606         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 607         six.reraise(type(newerr), newerr, tb)
    608 
    609 

/anaconda3/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:
```

Hope that helps.

**Comment by sklam** [comment] 2020-03-25 13:16
(edited original post for formatting)

**Comment by sklam** [comment] 2020-03-25 13:37
Can you provide an reproducer and tell us which numba version you are using?

**Comment by sklam** [comment] 2020-03-25 13:40
The error looks similar to #5415

**Comment by sklam** [comment] 2020-03-25 16:23
If it's the same bug as #5415. It has been fixed since 0.47.0.

**Comment by chaunceychason** [comment] 2020-03-25 17:09
Thank you, I was having issues with several versions of numpy but was able
to get it to work after updating a few other packages.

**Comment by esc** [comment] 2020-03-25 18:24
@chaunceychason thanks for reporting back, I will close this issue now as I assume it is resolved. Please don't hesitate to open a new issue in case you hit any more snags.

**Closed by esc** 2020-03-25 18:24 UTC
Labels: more info needed, needtriage
