### ISSUE TITLE
myarr.searchsorted(...) raises TypingError while np.searchsorted(myarr, ...) works

### ISSUE THREAD

**Issue by TomGoBravo** [numba/numba#5244] opened 2020-02-13 00:50 UTC
While trying to debug why calling as a method bound to an array of records as myarr.searchsorted(...) raises TypingError I noticed that changing to `np.searchsorted(myarr, ...)` works. I'm guessing this is obvious to everyone with some numba experience but the error message didn't help me.
For future reference here is a very simple example: https://repl.it/@TomGoBravo/numba-searchsorted-recs

## Feature request

Support for `myarr.searchsorted(...)` or more clarity on https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#array-types that the function needs to be called statically would have helped me.

Thank you!

**Comment by stuartarchibald** [comment] 2020-02-17 11:31
Thanks for the report. https://repl.it/@TomGoBravo/numba-searchsorted-recs is not working (404)? I suspect that there's a wiring problem somewhere in Numba as `np.X` is often wired to `somearray.X` (or vice versa). If you have a reproducer that would be most helpful, thanks.

**Comment by stuartarchibald** [comment] 2020-03-06 18:11
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-03-06 18:11 UTC
Labels: more info needed
