### ISSUE TITLE
built in round function Segmentation Fault

### ISSUE THREAD

**Issue by Lomelgande** [numba/numba#2435] opened 2017-06-28 06:47 UTC
Using the built in round function in a CUDA.jit function causes a Segmentation Fault error. I am taking the int of the rounded value int(round(x)) to get the closest array index value. Not sure if taking the int of the rounded value is the cause or if it's just the round function. Replacing the int(round(x)) with int(x) works just fine.

**Comment by stuartarchibald** [comment] 2017-06-28 08:23
Thanks for the report. Do you have a short piece of code to reproduce this issue? Do you think it's possible that the `round` is rounding to an out of bounds index and using that is the cause of the segfault? The CUDA simulator might help with diagnosing this http://numba.pydata.org/numba-doc/dev/cuda/simulator.html.

**Comment by Lomelgande** [comment] 2017-06-28 16:07
I tried implementing a clip function to fix the issue and it still came up.
The only reason I posted the report is due to the unusual error message.
I've been off in my indexing before and usually I receive a python error.
I've never received a C error.

**Comment by stuartarchibald** [comment] 2019-07-02 15:56
Fixed in https://github.com/numba/numba/pull/4137

**Closed by stuartarchibald** 2019-07-02 15:56 UTC
Labels: CUDA, bug
