### ISSUE TITLE
x += x.T and x = x + x.T yield different result.

### ISSUE THREAD

**Issue by vinson2233** [numba/numba#6949] opened 2021-04-20 10:11 UTC
Numba version : 0.53.1
Python version : 3.8.5
Numpy version : 1.19.2
## Bug Description
When working with 2D array, `x+= x.T `and `x = x + x.T` yield different result.

``` python
from numba import jit
import numpy as np

@jit 
def self_addition1(x):
    x += x.T
    return x

@jit
def self_addition2(x):
    x = x + x.T
    return x

x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

self_addition1(x)
> array([[2, 5],[8, 8]])

self_addition2(y)
> array([[2, 5],[5, 8]])
```

This behaviour don't happen when I remove the numba decorator

**Comment by stuartarchibald** [comment] 2021-04-28 19:03
Thanks for the report. I can reproduce this and also various variants of it with 'C' and 'F' ordered arrays. I think the issue is ultimately that the functions are not checking for overlapping memory bounds and as a result writing over their own data.

**Comment by guoqiangqi** [comment] 2021-05-08 08:59
I am interested in this issue, did anyone have worked into this? if nobody did this, i am willing to try to fix this.

**Comment by stuartarchibald** [comment] 2021-06-18 17:15
xref: Duplicate/variant of https://github.com/numba/numba/issues/5739.

**Comment by stuartarchibald** [comment] 2022-01-04 14:51
Closing as a duplicate of #5739. @guoqiangqi please feel free to submit a PR fixing this/the originally reported problem. Thanks.

**Closed by stuartarchibald** 2022-01-04 14:51 UTC
Labels: bug - incorrect behavior
