### ISSUE TITLE
support for axis argument in mean, max, median, nanmean, nanmax, etc

### ISSUE THREAD

**Issue by auderson** [numba/numba#7549] opened 2021-11-10 04:29 UTC
---

## Feature request

Currently, only `sum` supports `axis` argument. It will be nice if functions like `mean`, `max` and `nan-functions` support `axis` argument as well.

**Comment by esc** [comment] 2021-11-10 07:23
@auderson thank you for raising this. I believe this is a duplicate of https://github.com/numba/numba/issues/1269

**Closed** 2021-11-13 17:33 UTC
Labels: duplicate
