### ISSUE TITLE
prange fails when returning tuple of numpy arrays

### ISSUE THREAD

**Issue by tobermeier** [numba/numba#2705] opened 2018-01-26 12:05 UTC
Hi,

the issue seems to be related to https://github.com/numba/numba/issues/2537 - when returning a tuple of scalars, everything works fine, but it seems like there's still a problem with the following test code:

```
import numpy as np
from numba import njit

@njit(parallel=True)
def test_par(xx):
    for i in prange(10):
        x, y = test_inner(xx)

@njit
def test_inner(xx):
    x = np.zeros(2)
    y = np.zeros(2)

    return x, y

test_par(5)
```

The error message is:
...     return tuple(self.ind_to_var[i][0] for i in inds)
IndexError: Failed at nopython (convert to parfors)
list index out of range

I was wondering if there's a fix or workaround to return multiple arrays?

**Comment by sklam** [comment] 2018-02-01 15:59
I can't reproduce this issue on master.

**Comment by sklam** [comment] 2018-02-15 15:56
Closing.  Can't reproduce on master.

**Closed by sklam** 2018-02-15 15:56 UTC
