### ISSUE TITLE
Object mode live variable analysis failure.

### ISSUE THREAD

**Issue by compmech** [numba/numba#3025] opened 2018-06-08 16:06 UTC
## Reporting a bug

- [X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Just run the attached notebook using the branch "numba" of the repository meshless that I've been working on:

https://github.com/compmech/meshless/tree/numba

**Comment by stuartarchibald** [comment] 2018-06-08 16:13
Edited the bug report to drag the reported issue out of the comment block.

**Comment by stuartarchibald** [comment] 2018-06-08 16:15
@compmech can't seem to find the notebook? Please could you provide some more details as to what the problem is? Thanks.

**Comment by compmech** [comment] 2018-06-08 16:16
[test.ipynb.zip](https://github.com/numba/numba/files/2085157/test.ipynb.zip)

I am attaching the notebook

**Comment by stuartarchibald** [comment] 2018-06-08 16:35
Edited title to match issue.

**Comment by stuartarchibald** [comment] 2019-09-11 14:10
Closing this issue, assume fixed by https://github.com/numba/numba/pull/3230. If this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:10 UTC
Labels: bug
