### ISSUE TITLE
Array contains non-contiguous buffer error even after using np.ascontiguousarray

### ISSUE THREAD

**Issue by aktech** [numba/numba#6824] opened 2021-03-15 10:10 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

It seems numba raises `"Array contains non-contiguous buffer"` error even after using `np.ascontiguousarray`.

### Minimal example:

```python
import dask.array as da
import numpy as np
from numba import guvectorize

x = da.arange(10000, dtype=np.float64).reshape(100, 100).rechunk((1, 10))
f = np.ascontiguousarray(x.blocks[0, 0])
g = np.ascontiguousarray(x.blocks[0, 0])

@guvectorize(["void(float64[:], float64[:], float64[:], float64[:])"],
    "(n),(n),(p)->(p)",
    nopython=True,
    target="cuda",
)

def gpu_error(x, y, _, out) -> None:
    sum_ = 0.0
    for i in range(x.shape[0]):
        sum_ += (x[i] + y[i])
    out[:] = sum_

gpu_error(f, g, np.empty(1, dtype=x.dtype))
```

### Traceback

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-ed5511acd179> in <module>
----> 1 gpu_error(f, g, np.empty(1, dtype=x.dtype))

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/np/ufunc/deviceufunc.py in __call__(self, *args, **kws)
    651         callsteps.adjust_input_types(indtypes)
    652         callsteps.allocate_outputs(schedule, outdtype)
--> 653         callsteps.prepare_kernel_parameters()
    654         newparams, newretval = self._broadcast(schedule,
    655                                                callsteps.kernel_parameters,

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/np/ufunc/deviceufunc.py in prepare_kernel_parameters(self)
    810                 params.append(inp)
    811             else:
--> 812                 params.append(self.to_device(inp))
    813         assert all(self.is_device_array(a) for a in params)
    814         self.kernel_parameters = params

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/dispatcher.py in to_device(self, hostary)
    102 
    103     def to_device(self, hostary):
--> 104         return cuda.to_device(hostary, stream=self._stream)
    105 
    106     def to_host(self, devary, hostary):

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    222     def _require_cuda_context(*args, **kws):
    223         with _runtime.ensure_context():
--> 224             return fn(*args, **kws)
    225 
    226     return _require_cuda_context

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/api.py in to_device(obj, stream, copy, to)
    102     """
    103     if to is None:
--> 104         to, new = devicearray.auto_device(obj, stream=stream, copy=copy)
    105         return to
    106     if copy:

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py in auto_device(obj, stream, copy)
    774             devobj = from_array_like(obj, stream=stream)
    775         if copy:
--> 776             devobj.copy_to_device(obj, stream=stream)
    777         return devobj, True
    778 

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    222     def _require_cuda_context(*args, **kws):
    223         with _runtime.ensure_context():
--> 224             return fn(*args, **kws)
    225 
    226     return _require_cuda_context

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py in copy_to_device(self, ary, stream)
    208             return
    209 
--> 210         sentry_contiguous(self)
    211         stream = self._default_stream(stream)
    212         self_core, ary_core = array_core(self), array_core(ary)

~/.conda/envs/sgkit-gpu/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py in sentry_contiguous(ary)
    745     core = array_core(ary)
    746     if not core.flags['C_CONTIGUOUS'] and not core.flags['F_CONTIGUOUS']:
--> 747         raise ValueError(errmsg_contiguous_buffer)
    748 
    749 

ValueError: Array contains non-contiguous buffer and cannot be transferred as a single memory region. Please ensure contiguous buffer with numpy .ascontiguousarray()
```

### Array flags

```python
f.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

```python
g.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

**Comment by esc** [comment] 2021-03-15 12:49
@aktech thank you for reporting this, I believe this will need some triaging.

**Comment by aktech** [comment] 2021-03-15 12:54
@esc Let me know if you have any questions.

**Comment by esc** [comment] 2021-03-15 12:57
@gmarkall would you have some time to take a look at this?

**Comment by gmarkall** [comment] 2021-03-15 13:13
I can reproduce it, I think there's some limitation in the computation of the contiguity flags - the shape of the device array that gets constructed to copy the array into is `(1, 10)` with strides of `(800, 80)` - so if the shape were bigger in the first axis it wouldn't be contiguous, but I think there's an assumption somewhere that that stride always results in a non-contiguous array regardless of the size of the first axis.

**Comment by aktech** [comment] 2021-03-16 08:20
@gmarkall is there a potential workaround?

**Comment by gmarkall** [comment] 2021-03-16 10:52
For this particular example, I can make it work by recomputing (or "lying about"?) the strides:

```python
import dask.array as da
import numpy as np
from numba import guvectorize

x = da.arange(10000, dtype=np.float64).reshape(100, 100).rechunk((1, 10))
f = np.ascontiguousarray(x.blocks[0, 0])
g = np.ascontiguousarray(x.blocks[0, 0])

f.strides = (f.strides[-1] * f.shape[-1], f.strides[-1])
g.strides = (g.strides[-1] * g.shape[-1], g.strides[-1])


@guvectorize(
    ["void(float64[:], float64[:], float64[:], float64[:])"],
    "(n),(n),(p)->(p)",
    nopython=True,
    target="cuda",
)
def gpu_error(x, y, _, out) -> None:
    sum_ = 0.0
    for i in range(x.shape[0]):
        sum_ += x[i] + y[i]
    out[:] = sum_


result = gpu_error(f, g, np.empty(1, dtype=x.dtype))

print(result)
```

Which gives:

```
$ python repro.py 
[[90.]]
```

Does this fit into your use case, or is it too "dirty"?

**Comment by aktech** [comment] 2021-03-16 11:08
Thanks a lot for the workaround, let me try that. That should be fine, if it isn't an expensive operation.

**Comment by gmarkall** [comment] 2021-03-16 11:16
Some earlier references: #4943, #2766. At the time I was looking at #4943 I left it because I wasn't too familiar with `NPY_RELAXED_STRIDES_CHECKING` and was concerned it might not be the default in some places, but I think it's probably enabled everywhere relevant these days and safe to use the relaxed definition in Numba's dummy array.

**Comment by gmarkall** [comment] 2021-03-16 15:44
@aktech This should be fixed by #6830. Thanks for the nice reproducer - I've thought about this bug before but your example helped get over the line towards a fix :-)

**Comment by aktech** [comment] 2021-03-16 16:30
Great! Looking forward to the fix. :)

**Closed** 2021-03-17 19:53 UTC
Labels: CUDA, bug - incorrect behavior

**Comment by aktech** [comment] 2021-03-23 11:36
@gmarkall By the way that (strides) workaround above seems to change the array in some cases like [[2, 0], [1, 0]] becomes [[2, 0], [0, 1]], I don't have a nice reproducer for the same yet, but I'll share as soon as I have one, just an FYI.
