### ISSUE TITLE
NotDefinedError

### ISSUE THREAD

**Issue by zq19** [numba/numba#5034] opened 2020-01-06 07:28 UTC
---------------------------------------------------------------------------KeyError                                  Traceback (most recent call last)/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    266         try:
--> 267             return self._con[name]
    268         except KeyError:
KeyError: '$10setup_with.1'
During handling of the above exception, another exception occurred:
NotDefinedError                           Traceback (most recent call last)/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/ir.py in get_exact(self, name)
   1064         try:
-> 1065             return self.localvars.get(name)
   1066         except NotDefinedError:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    268         except KeyError:
--> 269             raise NotDefinedError(name)
    270 
NotDefinedError: Variable '$10setup_with.1' is not defined.
During handling of the above exception, another exception occurred:
KeyError                                  Traceback (most recent call last)/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    266         try:
--> 267             return self._con[name]
    268         except KeyError:
KeyError: '$10setup_with.1'
During handling of the above exception, another exception occurred:
NotDefinedError                           Traceback (most recent call last)<ipython-input-17-a394de744cf7> in <module>
      1 origin_inp = 'work/Job-1.inp'
      2 node_dic,node,maxnode = node_dic_create(origin_inp)
----> 3 element_dic,nodetimes = element_dic_create(origin_inp)
      4 new_node_assign,new_node_dic = new_node_element(node,nodetimes,maxnode,node_dic)
      5 new_element_dic = assign(element_dic,new_node_assign)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    407             # These errors are probably from an issue with either the code supplied
    408             # being syntactically or otherwise invalid
--> 409             error_rewrite(e, 'interpreter')
    410         except errors.ConstantInferenceError as e:
    411             # this is from trying to infer something as constant when it isn't
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670 
NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode)
Variable '$10setup_with.1' is not defined.

Unsupported Python functionality was found in the code Numba was trying to
compile. This error could be due to invalid code, does the code work
without Numba? (To temporarily disable Numba JIT, set the `NUMBA_DISABLE_JIT`
environment variable to non-zero, and then rerun the code).

If the code is valid and the unsupported functionality is important to you
please file a feature request at: https://github.com/numba/numba/issues/new

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

**Comment by stuartarchibald** [comment] 2020-01-06 09:37
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

(were I to guess, I'd say there's a nested with block in your code?)

**Comment by zq19** [comment] 2020-01-07 09:10
Thanks for your reply
The origin_inp is a pure text file,like:
1111111
222222
33333
444444
Here is the  function which colud not run successfully:


from numba import jit@jitdefnode_dic_create(origin_inp):with open(origin_inp,'r') as f: #读取节点编号及坐标，装进字典 node_dic={} node=[] inpline=f.readlines() value=0 k=0for i in range(len(inpline)): if inpline[i].startswith('*Node'): value+=1if inpline[i].startswith('*Element'): value=0breakif value==1: k+=1if k>1: l=inpline[i].replace(' ','').replace('\n','').split(',') node_dic[int(l[0])]=l[1:] node.append(l[0]) else: pass maxnode=k-1return node_dic,node,maxnode


origin_inp = 'work/Job-1.inp' node_dic,node,maxnode = node_dic_create(origin_inp)


Looking forward to your reply.

**Comment by stuartarchibald** [comment] 2020-01-07 14:28
Thanks for the update. 

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

What's presented as a minimum working example is unfortunately impossible to decipher as it's presented as a single line and therefore it's not possible to infer precisely what the source code is. However, from the single line I can see the use of a `with open()`, this is not supported in Numba's `nopython` mode, and given the rest of the code (string parsing), I'm not sure how good a fit Numba is to the use case (Numba works best with numerical code). 

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment] 2020-01-13 11:00
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-01-13 11:00 UTC
Labels: needtriage
