### ISSUE TITLE
Error with umap.plot.diagnostic

### ISSUE THREAD

**Issue by qo4on** [numba/numba#5132] opened 2020-01-23 12:21 UTC
Working with [this](https://umap-learn.readthedocs.io/en/latest/plotting.html) tutorial in Colab I got an error:
```
local_dims = umap.plot.diagnostic(mapper, diagnostic_type='local_dim')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    716     try:
--> 717         yield
    718     except NumbaError as e:

39 frames
TypeError: scalar type Tuple() given for non scalar argument #4

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numba/six.py in reraise(tp, value, tb)
    667         if value.__traceback__ is not tb:
    668             raise value.with_traceback(tb)
--> 669         raise value
    670 
    671 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type Tuple() given for non scalar argument #4

File "umap/umap/nndescent.py", line 290:
def initialized_nnd_search(
    <source elided>
):
    for i in numba.prange(query_points.shape[0]):
    ^

[1] During: lowering "id=11[LoopNest(index_variable = parfor_index.1739, range = (0, $4.6, 1))]{118: <ir.Block at /content/umap/umap/nndescent.py (306)>, 62: <ir.Block at /content/umap/umap/nndescent.py (302)>, 102: <ir.Block at /content/umap/umap/nndescent.py (302)>, 42: <ir.Block at /content/umap/umap/nndescent.py (297)>, 130: <ir.Block at /content/umap/umap/nndescent.py (308)>, 144: <ir.Block at /content/umap/umap/nndescent.py (302)>, 142: <ir.Block at /content/umap/umap/nndescent.py (309)>, 22: <ir.Block at /content/umap/umap/nndescent.py (290)>, 104: <ir.Block at /content/umap/umap/nndescent.py (305)>, 208: <ir.Block at /content/umap/umap/nndescent.py (311)>, 216: <ir.Block at /content/umap/umap/nndescent.py (300)>, 60: <ir.Block at /content/umap/umap/nndescent.py (301)>}Var(parfor_index.1739, nndescent.py:290)" at /content/umap/umap/nndescent.py (290)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.47.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by sklam** [comment] 2020-01-24 17:06
Can you provide a smaller reproducer?

Also, it looks like `umap.plot` is still in development. Please check with umap developers.

**Comment by stuartarchibald** [comment] 2020-01-24 18:35
I think that this is a duplicate/related to this: https://github.com/numba/numba/issues/5065#issuecomment-576429383

**Comment by qo4on** [comment] 2020-01-26 05:54
I'm not sure what you mean by "reproducer" but if you go to 
https://umap-learn.readthedocs.io/en/latest/plotting.html
and find the line
local_dims = umap.plot.diagnostic(mapper, diagnostic_type='local_dim')
you will see the error.

> `umap.plot` is still in development
I guess you're right.

**Comment by stuartarchibald** [comment] 2020-02-19 16:23
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:23 UTC
Labels: needtriage
