### ISSUE TITLE
Comparison with a single-element array

### ISSUE THREAD

**Issue by deanpa** [numba/numba#5217] opened 2020-02-08 02:08 UTC
@jit(nopython = True)
def numbaTestFunct2():
    r = np.array([.25])
    z = .75
    if r > z:
        print('r', r, 'z', z)

Traceback (most recent call last):
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/base.py", line 692, in cast
    return impl(self, builder, fromty, toty, val)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/numbers.py", line 1323, in any_to_boolean
    return context.is_true(builder, fromty, val)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/base.py", line 730, in is_true
    impl = self.get_function(bool, typing.signature(types.boolean, typ))
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/base.py", line 551, in get_function
    return self.get_function(fn, sig, _firstcall=False)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/base.py", line 553, in get_function
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering <class 'bool'>(array(bool, 1d, C),) -> bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/errors.py", line 662, in new_error_context
    yield
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 310, in lower_inst
    pred = self.context.cast(self.builder, cond, condty, types.boolean)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/targets/base.py", line 695, in cast
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
NotImplementedError: Cannot cast array(bool, 1d, C) to bool: %".276" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$0.9"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../wb_work/betaGamma.py", line 1850, in <module>
    main()
  File "../wb_work/betaGamma.py", line 1845, in main
    numbaTestFunct2()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/dean/miniconda3/envs/p_env/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast array(bool, 1d, C) to bool: %".276" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$0.9"

File "../wb_work/betaGamma.py", line 1766:
def numbaTestFunct2():
    <source elided>
#    z = np.random.uniform(0, 1.0)
    if r > z:
    ^

[1] During: lowering "branch $0.9, 24, 38" at ../wb_work/betaGamma.py (1766)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by ARF1** [comment] 2020-02-08 08:57
@deanpa The problem is that you are comparing an array type (`r`) with a scalar type (`z`). Your need to "unpack" the single element from the array with `r[0]` to compare a scalar against a scalar:

```python
import numpy as np
from numba import jit

@jit(nopython = True)
def numbaTestFunct2():
    r = np.array([.25])
    z = .75
    if r[0] > z:
        print('r', r, 'z', z)

numbaTestFunct2()
```

**Comment by stuartarchibald** [comment] 2021-12-16 16:33
The MWR does not reproduce on mainline as of 0.55, closing assumed fixed.

**Closed by stuartarchibald** 2021-12-16 16:33 UTC
Labels: feature_request
