### ISSUE TITLE
LoweringError when passing in prange values as a tuple

### ISSUE THREAD

**Issue by reversefold** [numba/numba#5277] opened 2020-02-18 22:01 UTC
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

# Description
Passing in values for `prange` in a tuple gives LoweringError. I have tested this reproduction case with both 0.48.0 and master (`f4e39942f37b90df8ee80d3fbfefe5fb9905a25e`). Switching from the `size` parameter to two individual parameters for the dimensions works as expected.

## Reproducer
```
#!/usr/bin/env python
import numba
import numpy


@numba.njit(parallel=True)
def parallel_test(size, arr):
    for x in numba.prange(size[0]):
        for y in numba.prange(size[1]):
            arr[y][x] = x * 4.5 + y


def main():
    size = (10, 10)
    arr = numpy.zeros(size, dtype=int)
    parallel_test(size, arr)
    print(arr)


if __name__ == '__main__':
    main()
```
## Error
```
Traceback (most recent call last):
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\errors.py", line 714, in new_error_context
    yield
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 271, in lower_block
    self.lower_inst(inst)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 459, in lower_inst
    func(self, inst)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\parfors\parfor_lowering.py", line 276, in _lower_parfor_parallel
    parfor.races)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\parfors\parfor_lowering.py", line 1240, in call_parallel_gufunc
    cache=False, is_parfors=True)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\parallel.py", line 260, in build_gufunc_wrapper
    py_func, cres, sin, sout, cache=cache, is_parfors=is_parfors,
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\wrappers.py", line 501, in build_gufunc_wrapper
    py_func, cres, sin, sout, cache, is_parfors=is_parfors,
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\wrappers.py", line 454, in build
    wrapperlib = self._compile_wrapper(wrapper_name)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\wrappers.py", line 433, in _compile_wrapper
    self._build_wrapper(wrapperlib, wrapper_name)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\wrappers.py", line 399, in _build_wrapper
    arg_steps, i, step_offset, typ, sym, sym_dim)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\np\ufunc\wrappers.py", line 657, in __init__
    "argument #{1}".format(typ, i + 1))
TypeError: scalar type UniTuple(int64 x 2) given for non scalar argument #3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_numba.py", line 21, in <module>
    main()
  File "test_numba.py", line 16, in main
    parallel_test(size, arr)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    raise e
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler.py", line 548, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler.py", line 390, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler.py", line 370, in _compile_core
    raise e
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler.py", line 361, in _compile_core
    pm.run(self.state)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_machinery.py", line 335, in run
    raise patched_exception
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_machinery.py", line 326, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_machinery.py", line 290, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\compiler_machinery.py", line 263, in check
    mangled = func(compiler_state)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\typed_passes.py", line 349, in run_pass
    lower.lower()
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 231, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 256, in lower_function_body
    self.lower_block(block)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\lowering.py", line 271, in lower_block
    self.lower_inst(inst)
  File "c:\users\paper\appdata\local\programs\python\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\errors.py", line 721, in new_error_context
    reraise(type(newerr), newerr, tb)
  File "C:\Users\paper\AppData\Local\pypoetry\Cache\virtualenvs\raytrace-b3yBLzzW-py3.7\lib\site-packages\numba\core\utils.py", line 78, in reraise
    raise value
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type UniTuple(int64 x 2) given for non scalar argument #3

File "test_numba.py", line 8:
def parallel_test(size, arr):
    for x in numba.prange(size[0]):
    ^

[1] During: lowering "id=1[LoopNest(index_variable = parfor_index.7, range = (0, $12binary_subscr.4, 1))]{20: <ir.Block at test_numba.py (8)>}Var(parfor_index.7, test_numba.py:8)" at test_numba.py (8)
```

**Comment by stuartarchibald** [comment] 2020-02-19 09:01
Thanks for the report. This is a known issue with Parallel Accelerator, root cause is due to `gufunc`s (Generalized Universal Functions) not accepting tuple inputs.

**Comment by stuartarchibald** [comment] 2020-02-19 09:02
xref: https://github.com/numba/numba/issues/5065

**Comment by stuartarchibald** [comment] 2020-02-19 16:27
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:27 UTC
Labels: ParallelAccelerator, bug, duplicate
