### ISSUE TITLE
Stange behavior with Numba (Could not load llvmlite.dll)

### ISSUE THREAD

**Issue by ymmx2** [numba/numba#5405] opened 2020-03-20 12:01 UTC
If I do this :

    from numba import float64, jitclass
    spec = [ ('A' ,float64)]
    
    @jitclass(spec)
    class MyClass:
        def __init__(self):
            self.A = 3.
    
    instance = MyClass() 
    print(instance.A)

I get this error :

> OSError: Could not load shared object file: llvmlite.dll

But, if I add for instance `from PyQt5.QtGui import *` before importing numba :

    from PyQt5.QtGui import *
    from numba import float64, jitclass
    spec = [ ('A' ,float64)]
    
    @jitclass(spec)
    class MyClass:
        def __init__(self):
            self.A = 3.
    
    instance = MyClass()
    print(instance.A)

It is working...

I don't understand what happens here.
It works also if I add `import scipy.io` or `import matplotlib`, but don't work  with `import numpy as np`.
I'm so confused.

**Comment by stuartarchibald** [comment] 2020-03-20 14:33
Thanks for the report. Which OS are you using and how did you install Numba?

Suspect this is libc related.

**Comment by ymmx2** [comment] 2020-03-20 14:55
I'm on windows 10
I installed python3.6.8
then I install several module from the pycharm interface, which uses pip if I'm not mistaken.

**Comment by stuartarchibald** [comment] 2020-03-23 09:35
This is may become challenging to debug. Is this reproducible on another machine/in a different environment? If so, could you please share that reproducer, thanks. Also, if you create a new environment with just `Numba` in it, does Numba work ok?

**Comment by ymmx2** [comment] 2020-03-25 09:47
Create a new environment with just numba doesn't change anything.
I cannot test on another machine for now.
Do I need to install other stuffs on my computer?

**Comment by stuartarchibald** [comment] 2020-09-11 18:27
Is this still a problem on the latest version of Numba (0.51.2)? Thanks!

**Comment by stuartarchibald** [comment] 2020-11-16 20:35
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-11-16 20:35 UTC
Labels: llvmlite, needtriage
