### ISSUE TITLE
Error message for unsupported comprehensions (e.g. generator) needs improving.

### ISSUE THREAD

**Issue by fredm73** [numba/numba#3366] opened 2018-10-01 18:12 UTC
I got this exception with my first attempt at using numba.  I have no experience -- forgive if the submission is inappropriate.
"-----------------------------
  Message=LoweringError('Failed at object (object mode backend)\n\x1b[1m\x1b[1mmake_function(name=$const0.11, code=<code object <genexpr> at 0x0000021EB30F31E0, file "D:\\Documents\\Visual Studio 2017\\Projects\\MovieLens\\MovieLens\\MovieLens.py", line 62>, closure=$0.9, defaults=None)\n\x1b[1m\nFile "MovieLens.py", line 62:\x1b[0m\n\x1b[1mdef predict(userFact, movieFact, wtFact):\n    <source elided>\n    xProd, aSize = crossProd()\n\x1b[1m    anIter = ((movieFact[m,i]-userFact[u,i])*wtFact[u,i] for (u,m,i) in xProd)\n\x1b[0m    \x1b[1m^\x1b[0m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1m[1] During: lowering "$0.12 = make_function(name=$const0.11, code=<code object <genexpr> at 0x0000021EB30F31E0, file "D:\\Documents\\Visual Studio 2017\\Projects\\MovieLens\\MovieLens\\MovieLens.py", line 62>, closure=$0.9, defaults=None)" at D:\\Documents\\Visual Studio 2017\\Projects\\MovieLens\\MovieLens\\MovieLens.py (62)\x1b[0m\n-------------------------------------------------------------------------------\nThis should not have happened, a problem has occurred in Numba\'s internals.\n\nPlease report the error message and traceback, along with a minimal reproducer\nat: https://github.com/numba/numba/issues/new\n\nIf more help is needed please feel free to speak to the Numba core developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n',)
  Source=d:\documents\visual studio 2017\projects\movielens\movielens\movielens.py
  StackTrace:
  File "d:\documents\visual studio 2017\projects\movielens\movielens\movielens.py", line 145, in <module>
    pred, dPred = predict(userFact, movieFact, wtFact)
"----------------------------------------
I enclose the .py file -- it is fairly minimal
[MovieLens.zip](https://github.com/numba/numba/files/2435087/MovieLens.zip)

**Comment by stuartarchibald** [comment] 2018-10-01 22:30
Thanks for the report. I think if you use the latest version of Numba the error message would read:
```
    yp = self.generator_info.yield_points[inst.index]
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'

File "MovieLens.py", line 63:
def predict(userFact, movieFact, wtFact):
    <source elided>
    xProd, aSize = crossProd()
    anIter = ((movieFact[m,i]-userFact[u,i])*wtFact[u,i] for (u,m,i) in xProd)
    ^

[1] During: lowering "$4.23.69 = yield $4.22" at MovieLens.py (63)
```
the problem is that generator comprehensions are not supported and one is in use in the code. I'm going to mark this ticket as a bug because the error message should be better.

In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment] 2018-10-01 22:32
Updated the report title to reflect the issue.

**Comment by stuartarchibald** [comment] 2019-09-11 13:48
Assuming fixed by https://github.com/numba/numba/pull/4282

**Closed by stuartarchibald** 2019-09-11 13:48 UTC
Labels: bug
