### ISSUE TITLE
Broadcasting error with sliced array and ParallelAccelerator

### ISSUE THREAD

**Issue by bdch1234** [numba/numba#4215] opened 2019-06-23 20:41 UTC
Running this:
```python
import numpy as np
from numba import jit

@jit(nopython=True, parallel=True)
def test(x1, x2):
    x1 = x1.reshape(x1.size, 1)
    x2 = x2.reshape(1, x2.size)
    return x1 >= x2[:, :-1]

x1 = np.random.rand(5)
x2 = np.random.rand(3)
test(x1, x2)
```
I get
```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-15-a9fd360d9c07> in <module>
     10 x1 = np.random.rand(5)
     11 x2 = np.random.rand(3)
---> 12 test(x1, x2)

AssertionError: Sizes of x1.1, $0.24 do not match on <ipython-input-15-a9fd360d9c07> (8)
```
using version 0.44.1. When setting parallel = False I get no error.

**Comment by stuartarchibald** [comment] 2019-06-24 10:39
Thanks for the report. The immediate problem of the `AssertionError` is fixed on the current master branch by virtue of recent work updating slice analysis, however the above now produces:
```python
  File "<path>/numba/types/functions.py", line 116, in get_impl_key
    return self._impl_keys[sig.args]
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
(int64, int64)

File "issue4215.py", line 8:
def test(x1, x2):
    <source elided>
    x2 = x2.reshape(1, x2.size)
    return x1 >= x2[:, :-1]
    ^

[1] During: lowering "replacement_slice.13 = call $0.21(zero.11, explicit_neg.12, func=$0.21, args=(Var(zero.11, issue4215.py (8)), Var(explicit_neg.12, issue4215.py (8))), kws=(), vararg=None)" at issue4215.py (8)
```
CC @DrTodd13

**Comment by DrTodd13** [comment] 2019-06-25 20:52
Fixed the issue you were seeing @stuartarchibald and now I see the error reported by @bdch1234.  Looking into that now.

**Comment by DrTodd13** [comment] 2019-06-25 21:31
@stuartarchibald @bdch1234 

See Numba documentation section 1.9.1 point 5.

"Multi-dimensional arrays are also supported for the above operations when operands have matching dimension and size. **The full semantics of Numpy broadcast between arrays with mixed dimensionality or size is not supported**, nor is the reduction across a selected dimension."

**Comment by stuartarchibald** [comment] 2019-06-26 08:56
Thanks for looking at this @DrTodd13. Whilst this is not supported now, is there any way to detect this and produce an error message that indicates what the problem is (Lowering errors are not ideal!)? I consider this a bug as a result of the problem not being reported correctly.

**Comment by DrTodd13** [comment] 2019-06-26 16:40
@stuartarchibald It isn't a lowering error.  We insert assert_equiv where we can't prove array equivalence and if they aren't identical then we assert, so it is a runtime error.  I guess most of those cases wouldn't produce an error in standard Python or Numba as broadcasting would kick in.  Can we say that this is true in every case?  If so, we could just change the error message to say ParallelAccelerator doesn't do broadcasting and maybe somehow try to make it clearer which arrays aren't equivalent.  Right now, internal IR names are used.  Maybe we give the Python variable name if available, else give the line where the array was created.

**Closed** 2019-07-04 00:55 UTC
Labels: ParallelAccelerator, feature_request
