### ISSUE TITLE
Compile times are nontrivally higher in 0.50 vs 0.46

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6133] opened 2020-08-14 16:53 UTC
## Feature request

Hi there! We've noted nontrivial slowdown in `@cuda.jit` compilation. It's not the easiest to replicate, as it seems to only show up in large kernels- the below should do it, on my sys >2x slower. Profiling, it seems to be related to this commit: https://github.com/numba/numba/pull/5351/commits/76b606ddfde801b8ea833120fc6c3d6691bda0e6

Any thoughts/advice? I know the example below is somewhat contrived, but it demos the issue pretty well.

```
from numba import cuda
import time
import numpy as np
from numpy import float64, int32, uint64, bool_
import numba


PDTYPE = [('pvar67', float64, (30,)), ('pvar72', float64, (210,))]
P_NP_DTYPE = np.dtype(PDTYPE, align=True)
P_NB_DTYPE = numba.from_dtype(P_NP_DTYPE)


INT_64_TYPE = [("uint64_1", uint64, (121, 47,)),
               ("uint64_2", uint64, (16, 31,))]
SV_TYPE = [("svvar1", float64, (121, 31, )),  ("svvar2", float64, (30, 31, )), ("svvar6", float64, (210, 31, )), ("svvar9", float64, (210, 31,))]


STYPE = [("svar9", float64, (161, 41, )), ("svar10", SV_TYPE)]
S_NP_TYPE = np.dtype(STYPE, align=True)
S_NB_TYPE = numba.from_dtype(S_NP_TYPE)


COTPYE13 = [('co13var1', bool_),
            ('co13var2', bool_),
            ('co13var3', bool_),
            ('co13var4', int32)]


COTYPE = [('covar13', COTPYE13)]
CO_NP_TYPE = np.dtype(COTYPE, align=True)
CO_NB_TYPE = numba.from_dtype(CO_NP_TYPE)



def load_kernel_2():
    @cuda.jit(argtypes=[P_NB_DTYPE[::1], CO_NB_TYPE[::1], S_NB_TYPE[::1]])
    def kernel_2(p_group, c_group, s_group):
        lane = cuda.blockDim.x * cuda.blockIdx.x + cuda.threadIdx.x
        pn = 1
        s_float = s_group[32].svar9
        s_vec = s_group[25].svar10
        c_s = c_group[0].covar13

        s_vec.svvar1[:, lane] = 0.0
### Copy/Paste Below ~100x
        for fi in range(0, 10):
            s_vec.svvar6[fi][lane] = s_vec.svvar9[fi][lane] + 1
            for index in range(0, 7):
                idx = fi * 7 + index
                if c_s.co13var4:
                    s_vec.svvar9[idx][lane] = p_group[pn].pvar72[fi]
                else:
                    s_vec.svvar9[idx][lane] = 0 if s_vec.svvar6[fi][lane] < 0 else s_vec.svvar6[fi][lane] / s_float[11][lane]
                    s_vec.svvar6[fi][lane] += s_vec.svvar9[idx][lane]
                s_vec.svvar1[idx][lane] = p_group[pn].pvar67[idx]
    return kernel_2


def main():
    begin = time.time()
    load_kernel_2()
    print('total time 1', time.time() - begin)


if __name__ == '__main__':
    main()
```

**Comment by sklam** [comment] 2020-08-14 17:27
There's a related gitter thread starting at: https://gitter.im/numba/numba?at=5f36c1ec22a7e979dbdf6e3a

**Comment by stuartarchibald** [comment] 2020-08-18 17:05
Dumping some data:
0.48 does this:
```
total time 19.03354549407959
[('18_nopython_backend', 14.400799010996707),
 ('13_nopython_type_inference', 0.9372242539975559),
 ('6_generic_rewrites', 0.6153244379893295),
 ('7_inline_closure_likes', 0.5352205469898763),
 ('16_nopython_rewrites', 0.4969588339954498),
 ('17_ir_legalization', 0.4620937929939828),
 ('0_translate_bytecode', 0.45751662400289206),
 ('3_with_lifting', 0.4355984980065841),
 ('2_ir_processing', 0.4096418179979082),
 ('10_dead_branch_prune', 0.08617717400193214),
 ('5_dead_branch_prune', 0.07707564900920261),
 ('15_inline_overloads', 0.010967884998535737),
 ('4_rewrite_semantic_constants', 0.004538285989838187),
 ('9_inline_inlinables', 0.0034364270104561),
 ('11_find_literally', 0.0028799229985452257),
 ('8_make_function_op_code_to_jit_function', 0.002804909003316425),
 ('12_literal_unroll', 0.002387796004768461),
 ('14_annotate_types', 4.2118001147173345e-05),
 ('19_dump_parfor_diagnostics', 1.548000000184402e-05),
 ('1_fixup_args', 1.097700442187488e-05)]
```
0.51 does this:
```
total time 33.92240238189697
[('20_nopython_backend', 16.67088437399798),
 ('13_reconstruct_ssa', 8.04999349200807),
 ('14_nopython_type_inference', 1.506562948001374),
 ('7_inline_closure_likes', 1.3121618410004885),
 ('18_nopython_rewrites', 1.2904103030014085),
 ('6_generic_rewrites', 1.036173433996737),
 ('19_ir_legalization', 0.6457480310054962),
 ('16_strip_phis', 0.6445920070036664),
 ('3_with_lifting', 0.6094680530004553),
 ('15_annotate_types', 0.6074441259916057),
 ('0_translate_bytecode', 0.5605414890014799),
 ('2_ir_processing', 0.5302879919981933),
 ('5_dead_branch_prune', 0.12433454499114305),
 ('10_dead_branch_prune', 0.12118224400182953),
 ('17_inline_overloads', 0.013697410009626765),
 ('4_rewrite_semantic_constants', 0.005118879998917691),
 ('9_inline_inlinables', 0.0043564580046222545),
 ('11_find_literally', 0.0034362839942332357),
 ('12_literal_unroll', 0.002521170004911255),
 ('8_make_function_op_code_to_jit_function', 0.0024468509946018457),
 ('21_dump_parfor_diagnostics', 1.5155004803091288e-05),
 ('1_fixup_args', 1.0121992090716958e-05)]
```
Reconstruct SSA is obviously adding a lot to the work, but also the passes which do CFG rebuilds a lot are contributing.

**Comment by sklam** [comment] 2020-08-18 18:01
Here's an alternative reproducer that only use the CPU:

```python
import numpy as np
import numba

body = """
    for fi in range(0, 10):
        data[fi] += 1
        for index in range(0, 7):
            idx = index
            if idx % 2 == 0:
                data[idx] += fi
            else:
                data[idx] += 1 if data[idx] < 3 else 2
                data[idx] += 1
            data[idx] += 1
"""

wrapper = """
def kernel(data):
    {}
"""

source = wrapper.format(body * 100)
glbs = {}
exec(source, glbs)

arg = np.zeros(100)
argtypes = (numba.typeof(arg),)

kernel = numba.njit(argtypes)(glbs['kernel'])

# 0.48.0 takes 24sec
# 0.51.0 takes 1min13sec
```

**Comment by sklam** [comment] 2020-08-18 18:37
I am removing the CUDA label because this is not specific to CUDA but a problem of the core compiler.

**Comment by sklam** [comment] 2020-08-18 18:46
I found an old branch that tries to address this problem but I was not able to find a case that it made an significant impact. However, applying it for this case has a huge impact. See https://github.com/numba/numba/pull/6146

**Comment by stuartarchibald** [comment] 2020-08-28 11:53
Numbers:
0.48.0 (total time: real    0m35.833s):
```
$ python test_6146.py                                                                                                  
18_nopython_backend                      18.9                                                                                   
7_inline_closure_likes                   2.4                                                                                    
6_generic_rewrites                       2.16                                                                                   
16_nopython_rewrites                     2.01                                                                                   
3_with_lifting                           1.98                                                                                   
17_ir_legalization                       1.95                                                                                   
2_ir_processing                          1.92                                                                                   
13_nopython_type_inference               1.49                                                                                   
0_translate_bytecode                     1.34                                                                                   
5_dead_branch_prune                      0.594                                                                                  
10_dead_branch_prune                     0.467                                                                                  
15_inline_overloads                      0.00835                                                                                
9_inline_inlinables                      0.00818                                                                                
4_rewrite_semantic_constants             0.00763                                                                                
8_make_function_op_code_to_jit_function  0.00523                                                                                
11_find_literally                        0.00516                                                                                
12_literal_unroll                        0.00488                                                                                
14_annotate_types                        5.9e-05                                                                                
19_dump_parfor_diagnostics               1.43e-05                                                                               
1_fixup_args                             9.65e-06
```
0.51.0 (total time: real    2m19.956s [139.956s]):
```
$ python test_6146.py 
13_reconstruct_ssa                       81.8
20_nopython_backend                      25.3
7_inline_closure_likes                   5.52
18_nopython_rewrites                     5.36
15_annotate_types                        2.73
16_strip_phis                            2.62
19_ir_legalization                       2.62
6_generic_rewrites                       2.55
2_ir_processing                          2.42
3_with_lifting                           2.34
14_nopython_type_inference               2.25
0_translate_bytecode                     1.65
10_dead_branch_prune                     0.666
5_dead_branch_prune                      0.655
17_inline_overloads                      0.0132
9_inline_inlinables                      0.0104
4_rewrite_semantic_constants             0.00807
11_find_literally                        0.00695
12_literal_unroll                        0.00534
8_make_function_op_code_to_jit_function  0.00482
21_dump_parfor_diagnostics               1.48e-05
1_fixup_args                             1.27e-05
```
0.51.1 (total time: real    0m56.379s):
```
$ python test_6146.py 
20_nopython_backend                      23.2
13_reconstruct_ssa                       14.1
18_nopython_rewrites                     2.95
7_inline_closure_likes                   2.42
14_nopython_type_inference               2.28
3_with_lifting                           1.77
15_annotate_types                        1.52
19_ir_legalization                       1.36
16_strip_phis                            1.3
0_translate_bytecode                     1.26
6_generic_rewrites                       1.25
2_ir_processing                          1.1
5_dead_branch_prune                      0.0342
10_dead_branch_prune                     0.0177
17_inline_overloads                      0.017
9_inline_inlinables                      0.011
4_rewrite_semantic_constants             0.00848
11_find_literally                        0.00691
12_literal_unroll                        0.00534
8_make_function_op_code_to_jit_function  0.00497
21_dump_parfor_diagnostics               1.57e-05
1_fixup_args                             1.12e-05
```
@sklam's patch in #6146 massively reduced the SSA cost. The reason the closure inliner and nopython rewrites are taking a load more time now is because the IR is by default `ir.Del` free, but some legacy algorithms rely on analysis of dels and so the postprocessor has to be run on the IR to regenerate them (and CFG rebuild is hit), the alg is then run and then the IR stripped of dels again.

**Comment by stuartarchibald** [comment] 2020-12-21 21:44
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-12-21 21:44 UTC
Labels: SSA, performance
