### ISSUE TITLE
Unstable software

### ISSUE THREAD

**Issue by Sequential-circuits** [numba/numba#6669] opened 2021-01-28 11:50 UTC
On Python 3.6.9 in a venv environment I type "import numba" and I get

AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'

Before that, I had tried to install it downloading it from the github repository but some error showed up saying to reinstall saying "inplace"

Before that, I tried to install it with a simple pip install, but it says "cannot import jit"

In all honesty, what an unstable software

**Comment by gmarkall** [comment] 2021-01-28 12:02
> On Python 3.6.9 in a venv environment I type "import numba" and I get
> 
> AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'
>
> ...
>
> Before that, I tried to install it with a simple pip install, but it says "cannot import jit"

Could you please provide the exact set of commands you used to create the virtualenv and install Numba, and the output they produced? It seems like something is wrong with the virtualenv, but it's difficult to suggest what without more details.

> Before that, I had tried to install it downloading it from the github repository but some error showed up saying to reinstall saying "inplace"

Building Numba does require the `--inplace` argument to `setup.py`, as documented here: https://numba.readthedocs.io/en/stable/developer/contributing.html#building-numba.

If you'd like to continue to build Numba locally instead of installing e.g. from pip, and still have some problems, then the commands you ran and their output will be helpful for troubleshooting.

> In all honesty, what an unstable software

Let's see if we can find a way to make it work for you.

**Comment by stuartarchibald** [comment] 2021-01-28 14:04
The specific issue here is probably due to a development version of Numba based on github mainline having been installed by some means but it was installed against a non-development version of `llvmlite`. These to projects are strongly linked, as are their release cycles. Instructions for building a development version of llvmlite are here: https://llvmlite.pydata.org/en/latest/admin-guide/install.html#building-manually

If you would like to try out the latest development releases of Numba they are available via:
```bash
conda install -c numba/label/dev numba
```
(usual caveats about development versions apply!).

Alternatively, unless you have a need for a development version of the Numba compiler, perhaps consider installing a released version (latest is 0.52) as a conda package or via `pip`?

**Comment by braniii** [comment] 2021-02-01 17:45
Hi,
I am facing a similar issue. I've installed anaconda 4.9.2 and tried to follow allong the instruction given at the [manual](https://numba.readthedocs.io/en/stable/developer/contributing.html). It seems that conda is not using the correct package. It would be great if someone could point me out, what I am doing wrong.

So running
```
$ conda config --add channels numba
$ conda create -n numbaenv python=3.8 llvmlite numpy scipy jinja2 cffi
$ conda activate numbaenv

$ conda update -n numaenv --all
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> # All requested packages already installed.

$ conda list | grep llvmlite
> llvmlite                  0.36.0dev0      py38hf484d3e_42    numba

# so far so good, but
$ python -c "import llvmlite; print(llvmlite.__version__)"
> 0.32.1
```
This results in the same error as found by @Sequential-circuits

So trying to compile and import numba
```
$ git clone git://github.com/numba/numba.git
$ cd numba
$ python setup.py build_ext --inplace

$ python -c "import numba" 
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pathTo/numba/numba/__init__.py", line 39, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/home/pathTo/numba/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/home/pathTo/numba/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/home/pathTo/numba/numba/core/registry.py", line 4, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "/home/pathTo/numba/numba/core/dispatcher.py", line 16, in <module>
    from numba.core import utils, types, errors, typing, serialize, config, compiler, sigutils
  File "/home/pathTo/numba/numba/core/compiler.py", line 6, in <module>
    from numba.core import (utils, errors, typing, interpreter, bytecode, postproc,
  File "/home/pathTo/numba/numba/core/callconv.py", line 12, in <module>
    from numba.core.base import PYOBJECT, GENERIC_POINTER
  File "/home/pathTo/numba/numba/core/base.py", line 1230, in <module>
    _initialize_llvm_lock_event()
  File "/home/pathTo/numba/numba/core/utils.py", line 285, in inner
    res = fn()
  File "/home/pathTo/numba/numba/core/base.py", line 1227, in _initialize_llvm_lock_event
    ll.ffi.register_lock_callback(enter_fn, exit_fn)
AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'
```

**Comment by stuartarchibald** [comment] 2021-02-01 18:00
Hi @braniii

First question, do you need a development version of the Numba compiler?

Second, it looks like you've somehow got a corrupted environment. Numba and llvmlite development are strongly linked, the current Numba development version (0.53.0dev0) needs a development version of llvmlite to work (0.36.0dev0).

I just did:
```
$ conda create -n _tmp_issue6669 -c numba python=3.8 llvmlite numpy scipy jinja2 cffi
$ conda activate _tmp_issue6669
```
and got:
```
$  conda list | grep llvmlite
llvmlite                  0.36.0dev0      py38hf484d3e_42    numba

$ python -c "import llvmlite; print(llvmlite.__version__)"
0.36.0dev0+42.g69fde4e
```
If you can get to the same point, i.e. 0.36.0dev0 available then Numba should build and run ok.

**Comment by braniii** [comment] 2021-02-01 18:10
@stuartarchibald yes I need a development version of numba, because I'd liked to contribute to numba. And thx for your help. But using your code reproduces my error. So I guess my conda installation is the problem? I will try to fix it and otherwise open an issue on the conda project.

**Comment by stuartarchibald** [comment] 2021-02-01 18:15
> @stuartarchibald yes I need a development version of numba, because I'd liked to contribute to numba. 

Ah, thanks, great to hear that :)

> And thx for your help. But using your code reproduces my error. So I guess my conda installation is the problem? I will try to fix it and otherwise open an issue on the conda project.

No problem. Perhaps try restarting your shell, there might be some state that's incorrect, and then creating an environment with a new name? Another possibility is that `llvmlite` has been e.g. `pip` installed and perhaps a version has been overwritten? Finally, perhaps download a new copy of (mini)conda and see if the problem persists with that? Also, if you are still stuck it might be worth logging in to https://gitter.im/numba/numba so someone can help you in real time.

**Comment by Sequential-circuits** [comment] 2021-02-02 14:10
I don't use conda, so any feedback which involves it is not helpful

I use venv, so if at least I could just have a command to install it under this platform which at the end it does not mean it not loading at runtime that'd be great

**Comment by esc** [comment] 2021-02-02 14:41
> I don't use conda, so any feedback which involves it is not helpful
> 
> I use venv, so if at least I could just have a command to install it under this platform which at the end it does not mean it not loading at runtime that'd be great

@Sequential-circuits thank you for following up on this. In an unmodified virtual environment the command `pip install numba` should install the latest `numba` with the correct `llvmlite` on all platforms supported by the Numba wheels on PyPi. If that command does not work, it may very well be a bug. In that case, further assistance may be provided if you copy the command you entered and the resulting output here in order to aid debugging. Thank you.

**Comment by Sequential-circuits** [comment] 2021-02-02 15:31
The problem is not installing, it is running a program, as it keeps saying

Traceback (most recent call last):
  File "numba.py", line 1, in <module>
    from numba import jit
  File "/var/www/html/stipra.com/api/numba.py", line 1, in <module>
    from numba import jit
ImportError: cannot import name 'jit'

The program is actually a test program listed online: pretty standard stuff I believe
from numba import jit
import numpy as np
import time

x = np.arange(100).reshape(10, 10)

@jit(nopython=True)
def go_fast(a): # Function is compiled and runs in machine code
    trace = 0.0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (with compilation) = %s" % (end - start))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))

**Comment by esc** [comment] 2021-02-02 15:37
@Sequential-circuits thank you for reporting this. Unfortunately, when using the `numba` module you can not name your file `numba.py`. Python will get confused. Try renaming the file to `my_numba_example.py` or something like that.

**Comment by Sequential-circuits** [comment] 2021-02-02 15:44
Thanks, but still problems (told ya this is a problematic software!):

/venv/bin/python3 my_numba_example.py                   Traceback (most recent call last):
  File "my_numba_example.py", line 1, in <module>
    import numba
ImportError: bad magic number in 'numba': b'\x03\xf3\r\n'

**Comment by Sequential-circuits** [comment] 2021-02-02 15:46
ok, got it to work by deleting an old numba.pyc

**Comment by esc** [comment] 2021-02-02 15:52
@Sequential-circuits thank you for following and confirming this resolved your issue. I will close this issue now as it appears to be resolved. Thank you again for your cooperation.

**Closed by esc** 2021-02-02 15:52 UTC
Labels: question
