### ISSUE TITLE
Feeding lengthy tuples into jitted functions leads to crash

### ISSUE THREAD

**Issue by ml31415** [numba/numba#2195] opened 2016-11-12 13:44 UTC
I had tried to feed a list of arrays with irregular length into a jitted function and followed the advice in #1239 to use tuples instead. Unfortunately it looks like using tuples longer than 1000 entries or so, even with plain ints crashes. Tested with 0.29 and 0.28.1.

```python
import numpy as np
import numba as nb
print nb.__version__

@nb.njit
def eattuple(a):
    return len(a)

for i in range(8):
    b = tuple(xrange(10**i))
    #b = tuple([np.arange(10) for i in range(10**i)])
    print eattuple(b)
```
```
0.29.0
1
10
100
1000
fish: 'ipython' terminated by signal SIGKILL
```

**Comment by stuartarchibald** [comment] 2016-11-14 17:18
Thanks for the report. This is most likely the kernel OOM killer sending the SIGKILL.
```
[Mon Nov 14 15:00:28 2016] Out of memory: Kill process 2238 (python) score 989 or sacrifice child                               
[Mon Nov 14 15:00:28 2016] Killed process 2238 (python) total-vm:32608876kB, anon-rss:32401924kB, file-rss:4kB
```
I think the culprit is probably the IR being near 6Gb in size and it requiring a few translations and manipulations, this exhausting memory. The apparent size seems largely down to this declaration:
```
declare i32 @"__main__.eattuple$5.(int64_x_10000)"(i64* %".1", {i8*, i32}** %".2", i8* %".3", i64 %".4", i64 %".5",...
```
which continues with many incrementing `i64 %".n",` expressions.

**Comment by sklam** [comment] 2016-11-15 11:57
Looks like we need to change how big tuple is passed as arguments.  The current scheme unpacks the tuple and pass individual element by value.

**Comment by pitrou** [comment] 2016-11-15 12:05
Well... currently, a tuple maps to a LLVM struct with the same number of elements, so even if we fix unpacking, the IR will still be very large (except for toy functions such as the above).

Perhaps we should simply raise an error when type-inferring a tuple of more than a certain size (e.g. 1000 elements), and suggest the user passes a list instead.

**Comment by ml31415** [comment] 2016-11-15 13:27
I would have been totally happy to pass a list, though this only seems to work for scalars.
```python
import numpy as np
import numba as nb
print nb.__version__

@nb.njit
def eattuple(a):
    return len(a)

for i in range(8):
    b = [np.arange(i % 9) for i in xrange(10**i)]
    print eattuple(b)
```
```
LoweringError: reflected list(array(int64, 1d, C)): unsupported nested memory-managed object
File "<ipython-input-5-c2d8ef785641>", line 7
[1] During: lowering "a = arg(0, name=a)" at <ipython-input-5-c2d8ef785641> (7)

Failed at nopython (nopython mode backend)
reflected list(array(int64, 1d, C)): unsupported nested memory-managed object
File "<ipython-input-5-c2d8ef785641>", line 7
[1] During: lowering "a = arg(0, name=a)" at <ipython-input-5-c2d8ef785641> (7)
```

**Comment by wkerzendorf** [comment] 2019-05-05 01:08
any update on this?

**Comment by stuartarchibald** [comment] 2019-05-06 11:41
@wkerzendorf WRT `tuples` I don't think so, however the list method described here https://github.com/numba/numba/issues/2195#issuecomment-260640732 should now work fine.

**Comment by ml31415** [comment] 2019-05-07 08:55
Indeed, the example above works fine now. I'd be fine closing this issue, as the myriads of tuples were a work around anyways. Though I guess @pitrou was totally right to suggest to just raise an error message for overly long tuple inputs.

**Comment by stuartarchibald** [comment] 2019-05-07 17:13
Marking this as a bug and easy to resolve. Tuple length is known at compile time.

**Comment by guilhermeleobas** [comment] 2019-05-10 02:20
Hi, I want to work on this issue.

**Comment by stuartarchibald** [comment] 2019-05-10 08:25
@guilhermeleobas great thanks. I think this should be a question of adding a check in `numba/ir_utils.py` in the `raise_on_unsupported_feature` function. The `func_ir` variable has the attr `arg_names` for the names of the arguments and the `typemap` variable contains a map of name->type, so I think it's just a question of linking the two up, checking for tuple types and then making sure they are not greater than say 1000. Thanks!

**Comment by guilhermeleobas** [comment] 2019-05-10 16:58
Hi @stuartarchibald, I tried to reproduce the error with values greater than 1000 but couldn't. The code I used to reproduce was the same posted in the first post. I only changed the exponential operation by a multiplication. 

![image](https://user-images.githubusercontent.com/2712115/57543743-99a49980-732b-11e9-894c-aecb9db7880c.png)

```python
import numpy as np
import numba as nb

@nb.njit
def eattuple(a):
    return len(a)

for i in range(8):
    b = tuple(range(i * 1000))
    #b = tuple([np.arange(10) for i in range(10**i)])
    print (eattuple(b))
```

**Comment by stuartarchibald** [comment] 2019-05-10 17:06
@guilhermeleobas thanks for trying the above, the issue is that the LLVM IR becomes enormous as the tuple length increases, to the point where LLVM cannot reasonably compile it/machine runs out of memory. `1000` was an arbitrary number as a point where to stop.

**Closed** 2019-05-17 11:58 UTC
Labels: bug, easy
