### ISSUE TITLE
`tuple_zip`: `free(): invalid pointer`

### ISSUE THREAD

**Issue by yohplala** [numba/numba#8849] opened 2023-03-26 07:22 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi, I would like to use ``literal_unroll`` along with ``tuple_zip`` as provided in [documentation page](https://numba-how-to.readthedocs.io/en/latest/tuples.html#how-to-zip-several-tuples). I get however a ``Typingerror``.

```python
from numba import types
from numba.extending import intrinsic
from numba.core.cgutils import unpack_tuple
from numba.core.errors import TypingError

@intrinsic
def tuple_zip(tyctx, *tys):
    if len(tys) > 1:
        tys = types.StarArgTuple(tys)
    elif len(tys) == 1:
        raise ValueError("Only one argument received. Tuples to be zipped must be passed as individual arguments")
    if not all(isinstance(x, types.BaseTuple) for x in tys):
        raise TypingError("All inputs must be tuples") 
    nitems = min((x.count for x in tys))
    tuples = [types.Tuple(inner_ty) for inner_ty in zip(*tys)]
    ret = types.Tuple(tuples)

    def codegen(cgctx, builder, sig, args):
        assert len(args) == 1  # it is a vararg tuple
        args_tup = unpack_tuple(builder, args[0])
        values = []
        for i in range(nitems):
            inner_vals = [builder.extract_value(x, i) for x in args_tup]
            inner_tup = cgctx.make_tuple(builder, tuples[i], inner_vals)
            values.append(inner_tup)
        return cgctx.make_tuple(builder, sig.return_type, values)

    sig = ret(tys)
    return sig, codegen


import numpy as np
from numba import njit

t_in = (np.array([1,2,3], dtype="int64"),np.array([4,5,6], dtype="float64"))
t_out = (np.zeros(3, dtype="int64"),np.zeros(3, dtype="float64"))

@njit
def calc(t_in, t_out):
    for ars in literal_unroll(tuple_zip(t_in, t_out)):
        ar_in, ar_out = ars
        ar_out[:] = ar_in
    return t_out

calc(t_in, t_out)
```

I then get:

```bash
Traceback (most recent call last):

  Cell In[4], line 1
    calc(t_in, t_out)

  File ~/mambaforge/lib/python3.10/site-packages/numba/core/dispatcher.py:468 in _compile_for_args
    error_rewrite(e, 'typing')

  File ~/mambaforge/lib/python3.10/site-packages/numba/core/dispatcher.py:409 in error_rewrite
    raise e.with_traceback(None)

TypingError: Cannot determine Numba type of <class 'numba.core.ir.UndefinedType'>
```

Using
spyder IDE (execution in iPython 8.11),
python 3.10.9,
numba 0.56.4

**Comment by sklam** [comment] 2023-03-27 13:49
In addition, the documentation at https://numba-how-to.readthedocs.io is written by a community member to share useful code recipes. For the "official" documentation, please use https://numba.readthedocs.io/en/stable/

**Comment by sklam** [comment] 2023-03-28 21:50
I found the problem. `tuple_zip` is missing an increment to the reference count.

It should look like:

```python

@intrinsic
def tuple_zip(tyctx, *tys):
    if len(tys) > 1:
        tys = types.StarArgTuple(tys)
    elif len(tys) == 1:
        raise ValueError("Only one argument received. Tuples to be zipped must be passed as individual arguments")
    if not all(isinstance(x, types.BaseTuple) for x in tys):
        raise TypingError("All inputs must be tuples")
    nitems = min((x.count for x in tys))
    tuples = [types.Tuple(inner_ty) for inner_ty in zip(*tys)]
    ret = types.Tuple(tuples)

    def codegen(cgctx, builder, sig, args):
        assert len(args) == 1  # it is a vararg tuple
        args_tup = unpack_tuple(builder, args[0])
        values = []
        for i in range(nitems):
            inner_vals = [builder.extract_value(x, i) for x in args_tup]
            inner_tup = cgctx.make_tuple(builder, tuples[i], inner_vals)
            values.append(inner_tup)
        res = cgctx.make_tuple(builder, sig.return_type, values)
        cgctx.nrt.incref(builder, sig.return_type, res)    # <---- increment RC
        return res

    sig = ret(tys)
    return sig, codegen
```

**Comment by stuartarchibald** [comment] 2023-03-29 14:40
Thanks for debugging this @sklam, am going to close this as the issue is now being tracked in the source repository for the documentation containing the issue. @yohplala Thanks for reporting this and then carrying the issue to the `numba-how-to` repository.

**Closed by stuartarchibald** 2023-03-29 14:40 UTC
Labels: needtriage
