### ISSUE TITLE
Segfault using `generated_jit` and `profiler`

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#3625] opened 2018-12-21 10:35 UTC
I was profiling some complex code and python kept crashing with a segfault. I could not locate the exact problem, but I have an example demonstrating the problem:

```python
import cProfile as profiler
# import data_profiler as profiler

import numpy as np
import numba

dim = 16
arr = np.arange(dim)
out = np.empty_like(arr)

def jit_allocate_out(func):
    @numba.generated_jit(nopython=True)
    def wrapper(arr, out=None):
        if isinstance(out, (numba.types.NoneType, numba.types.Omitted)):
            # function is called without `out`
            f_jit = numba.njit(func)
            
            def f_with_allocated_out(arr, out):
                """ helper function allocating output array """
                return f_jit(arr, out=np.empty_like(arr))

            return f_with_allocated_out
        
        else:
            # function is called with `out` argument
            return func    
    
    return wrapper  # type: ignore
        
                       
def copy(arr, out=None):
    """ apply laplace operator to array `arr` """
    for i in range(dim):
        out[i] = arr[i]
    return out
    
copy_allocat_out = jit_allocate_out(copy)

def apply(func, data):
    func(data)

def run():

    # call without allocating `out`
    print(copy_allocat_out(arr))
    
    # call with pre-allocated `out`
    copy_allocat_out(arr, out)
    print(out)
    
    # call in sub-routine
    apply(copy_allocat_out, arr)
    
run()

profiler.run('run()')
```

I tried reducing the complexity of the example, but to no avail. Note that python only crashes when `run` is called by the profiler. This could thus very well be a problem with the profiler, too. However, the crash also happens when I replace `cProfile` by `profile` or `data_profiler`.

**Comment by stuartarchibald** [comment] 2018-12-21 10:46
Thanks for the report. I think it's probably this issue https://github.com/numba/numba/issues/3229.

**Comment by david-zwicker** [comment] 2018-12-21 10:50
Yes, this sounds very related!

**Comment by mikedh** [comment] 2019-01-04 05:59
I too recently (last month or so) started seeing segfaults in a complex application. When I played around with [faulthandler](https://docs.python.org/3/library/faulthandler.html) the top candidate was `numba` and `llvmlite`. This was in a Debian Stretch docker container.

Freezing at one version old appears to have fixed it for my application:
```
numba==0.41.0
llvmlite==0.26.0
```

The output from faulthandler:

```
Fatal Python error: Segmentation fault

Current thread 0x00007febdb053700 (most recent call first):
  File "/home/user/conda/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 108 in __call__
  File "/home/user/conda/lib/python3.6/site-packages/llvmlite/binding/executionengine.py", line 22 in create_mcjit_compiler
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/codegen.py", line 613 in _init
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/codegen.py", line 603 in __init__
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/cpu.py", line 47 in init
  File "/home/user/conda/lib/python3.6/site-packages/numba/compiler_lock.py", line 32 in _acquire_compile_lock
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/base.py", line 250 in __init__
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/registry.py", line 34 in _toplevel_target_context
  File "/home/user/conda/lib/python3.6/site-packages/numba/utils.py", line 353 in __get__
  File "/home/user/conda/lib/python3.6/site-packages/numba/targets/registry.py", line 50 in target_context
  File "/home/user/conda/lib/python3.6/site-packages/numba/dispatcher.py", line 539 in __init__
  File "/home/user/conda/lib/python3.6/site-packages/numba/decorators.py", line 174 in wrapper
  File "/home/user/conda/lib/python3.6/site-packages/sparse/coo/indexing.py", line 261 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/user/conda/lib/python3.6/site-packages/sparse/coo/core.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/user/conda/lib/python3.6/site-packages/sparse/coo/__init__.py", line 1 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/user/conda/lib/python3.6/site-packages/sparse/__init__.py", line 1 in <module>

```

**Comment by stuartarchibald** [comment] 2019-01-07 19:23
@mikedh thanks for commenting, were you running with `cProfile` or is this some other issue? Running your code with `catchsegv` http://manpages.ubuntu.com/manpages/trusty/man1/catchsegv.1.html will produce a load more output about what happened should a segfault occur (the native stack is very useful). If you manage to create a reproducer (appreciate that may be hard in a complex program) then please open a new ticket and someone will take a look. Thanks again.

**Comment by stuartarchibald** [comment] 2019-01-07 20:45
@mikedh ah ok, thanks. I've started working on fixing it here https://github.com/numba/numba/pull/3638, that patch demonstrates more the issue in the CPython interaction. Will hopefully be able to resolve it soon.

**Comment by sklam** [comment] 2020-03-09 21:04
Closing because of #4476

**Closed by sklam** 2020-03-09 21:04 UTC
Labels: bug
