### ISSUE TITLE
Inconsistency in Numpy version

### ISSUE THREAD

**Issue by shaleenb** [numba/numba#9214] opened 2023-09-26 14:49 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).

In `setup.py`, the value for `min_numpy_run_version` is `1.21`. However, in `numba/__init__.py`, we have the following code block starting at line 37:

```
    if numpy_version < (1, 22):
        msg = (f"Numba needs NumPy 1.22 or greater. Got NumPy "
               f"{numpy_version[0]}.{numpy_version[1]}.")
        raise ImportError(msg)
```

As a result, numba can get installed alongside numpy 1.21 but not actually work.

**Comment by esc** [comment] 2023-09-26 14:53
@shaleenb thank you for reporting, duplicate of #9209

**Closed** 2023-09-26 14:53 UTC
Labels: duplicate
