### ISSUE TITLE
More than one definition bug

### ISSUE THREAD

**Issue by arose13** [numba/numba#3896] opened 2019-03-23 02:39 UTC
I'm sure this is a bug different from issue #3742 

The following code throws the following error. `compute_w(x, z)` returns a list with numpy arrays that are the same shape as those generated by the list comprehension.
```
    if enable_cache:
        precomputed_w = compute_w(x, z)
    else:
        precomputed_w = [np.zeros((n, k)) for _ in range(x.shape[1])]
```
The error message
```
KeyError: 'Failed in nopython mode pipeline (step: inline calls to locally defined closures)\n"more than one definition for \'precomputed_w\'"'
```

(I'm using numba version 0.43.0)

**Comment by stuartarchibald** [comment] 2019-03-25 10:04
Thanks for the report. It's likely the cause is the same problem as in #3742, there's multiple definition sites for `precompute_w` and the closure inlining code will be running to handle the list comprehension (which is where that error message comes from). Just to double check, please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.

Thanks.

**Comment by stuartarchibald** [comment] 2021-08-05 08:44
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

Also, it's probably safe to assume that this is fixed since Numba started using SSA based IR in type inference.

**Closed by stuartarchibald** 2021-08-05 08:44 UTC
Labels: SSA, bug, duplicate
