### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kalyaniasthana** [numba/numba#5051] opened 2020-01-08 15:30 UTC
mfdca compute_di protein refined_alignments/PF00131_refined.fasta --verbose
INFO 2020-01-08 21:15:03,901 meanfield_dca __init__ 
	Total number of unique site states found in alignment data: 21
INFO 2020-01-08 21:15:03,905 meanfield_dca compute_sequences_weight 
	Computing sequences weights
INFO 2020-01-08 21:15:04,335 meanfield_dca __init__ 
	Created a MeanFieldDCA object with the following attributes
        	biomolecule: PROTEIN
        	total states at sites: 21
        	pseudocount: 0.5
        	sequence identity: 0.8
        	alignment length: 63
        	total number of (non-effective) sequences: 92
        	effective number of sequences: 26.642204136407397
        
INFO 2020-01-08 21:15:04,335 meanfield_dca get_single_site_freqs 
	Computing single site frequencies
Traceback (most recent call last):
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/errors.py", line 599, in new_error_context
    yield
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 449, in lower_assign
    return self.lower_expr(ty, value)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 855, in lower_expr
    res = self.lower_call(resty, expr)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 821, in lower_call
    res = impl(self.builder, argvals)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/targets/base.py", line 1081, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/targets/arrayobj.py", line 3272, in numpy_zeros_nd
    _zero_fill_array(context, builder, ary)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/targets/arrayobj.py", line 3201, in _zero_fill_array
    cgutils.memset(builder, ary.data, builder.mul(ary.itemsize, ary.nitems), 0)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/cgutils.py", line 847, in memset
    builder.call(fn, [ptr, value, size, int32_t(0), bool_t(0)])
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/llvmlite/ir/builder.py", line 841, in call
    cconv=cconv, tail=tail, fastmath=fastmath)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/llvmlite/ir/instructions.py", line 84, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/Data/consensus/venv/bin/mfdca", line 8, in <module>
    sys.exit(run_meanfield_dca())
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/pydca/main.py", line 766, in run_meanfield_dca
    remove_all_gaps = args_dict.get('remove_all_gaps'),
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/pydca/main.py", line 435, in execute_from_command_line
    sorted_DI, couplings = mfdca_instance.compute_sorted_DI()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/meanfield_dca.py", line 719, in compute_sorted_DI
    reg_fi = self.get_reg_single_site_freqs()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/meanfield_dca.py", line 463, in get_reg_single_site_freqs
    single_site_freqs = self.get_single_site_freqs()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/meanfield_dca.py", line 442, in get_single_site_freqs
    seqs_weight = self.__sequences_weight,
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 835, in _compile_bytecode
    return self._compile_core()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 822, in _compile_core
    res = pm.run(self.status)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 696, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 646, in _backend
    lowered = lowerfn()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 633, in backend_nopython_mode
    self.flags)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/compiler.py", line 1023, in native_lowering_stage
    lower.lower()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/errors.py", line 607, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/media/Data/consensus/venv/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "venv/lib/python3.5/site-packages/pydca/meanfield_dca/msa_numerics.py", line 84:
def compute_single_site_freqs(alignment_data=None,
    <source elided>
    single_site_freqs = np.zeros(shape = (seqs_len, num_site_states),
        dtype = np.float64)
        ^

[1] During: lowering "$0.19 = call $0.11(vararg=None, func=$0.11, args=[], kws=[('shape', Var($0.15, /media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/msa_numerics.py (83))), ('dtype', Var($0.18, /media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/msa_numerics.py (84)))])" at /media/Data/consensus/venv/lib/python3.5/site-packages/pydca/meanfield_dca/msa_numerics.py (84)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment] 2020-01-08 16:37
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

**Comment by seibert** [comment] 2020-01-08 16:38
Just to check: What version of Numba and llvmlite are you using?

**Comment by stuartarchibald** [comment] 2020-02-06 09:35
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-02-06 09:35 UTC
Labels: needtriage
