### ISSUE TITLE
Why jit change the result ,actually the function is the same. Is this a bug ???

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4144] opened 2019-06-04 11:28 UTC
```
def ts_prod3(x,d):
	'''
	time-series product over the past d days
	x: such as open/high/low/close ...
	d: the delay window 
	'''
	n = len(x)
	x_ = np.lib.stride_tricks.as_strided(x,shape=(n-d+1,d),strides=(x.strides[0],x.strides[0]))
	
	ret = np.zeros(n-d+1)
	for i in np.arange(n-d+1):
		ret[i] = x_[i,:].prod()

	return ret
```

```
@jit(nopython=True)
def ts_prod3_jit(x,d):
	'''
	time-series product over the past d days
	x: such as open/high/low/close ...
	d: the delay window 
	'''
	n = len(x)
	x_ = np.lib.stride_tricks.as_strided(x,shape=(n-d+1,d),strides=(x.strides[0],x.strides[0]))
	
	ret = np.zeros(n-d+1)
	for i in np.arange(n-d+1):
		ret[i] = x_[i,:].prod()

	return ret
```

```
v1 = np.arange(1,1001)
ans3 = ts_prod3(v1,10)
ans3j = ts_prod3_jit(v1,10)

ans3[:10]
Out[302]: 
array([ 3.62880000e+06,  3.99168000e+07,  2.39500800e+08,  1.03783680e+09,
       -6.62538496e+08, -1.98761549e+09, -1.00534067e+09,  1.85342566e+09,
       -1.24759552e+08,  2.13837312e+08])

ans3j[:10]
Out[303]: 
array([3.62880000e+06, 3.99168000e+07, 2.39500800e+08, 1.03783680e+09,
       3.63242880e+09, 1.08972864e+10, 2.90594304e+10, 7.05729024e+10,
       1.58789030e+11, 3.35221286e+11])
```

Why jit change the result ,actually the function is the same. Is this a bug ???

```

**Comment by synapticarbors** [comment] 2019-06-04 13:50
What version of numba and numpy are you using? Running your code with a very current commit off of master, I'm getting:

```python
print('numba version: ', numba.__version__)
print('numpy version: ', np.__version__)
print('all close: ', np.allclose(ans3, ans3j))
```

returns:

```python
numba version:  0.44.0dev0+558.g258408e61
numpy version:  1.16.3
all close:  True
```

**Comment by sklam** [comment] 2019-06-04 14:28
I also cannot replicate the issue.  I checked both master, 0.44.0, 0.43.0, 0.42.0 on OSX.



<details>
<summary>Here's the code I used to test</summary>

```python
import numpy as np
from numba import jit


@jit(nopython=True)
def ts_prod3_jit(x, d):
    """
    time-series product over the past d days
    x: such as open/high/low/close ...
    d: the delay window
    """
    n = len(x)
    x_ = np.lib.stride_tricks.as_strided(
        x, shape=(n - d + 1, d), strides=(x.strides[0], x.strides[0])
    )

    ret = np.zeros(n - d + 1)
    for i in np.arange(n - d + 1):
        ret[i] = x_[i, :].prod()

    return ret


v1 = np.arange(1,1001)
ans3 = ts_prod3_jit.py_func(v1,10)
ans3j = ts_prod3_jit(v1,10)

print(np.allclose(ans3, ans3j))
```
</details>

If the issue persist, please copy and paste the output of `numba -s` into this issue.

**Comment by isaac-you** [comment] 2019-06-05 01:18
```
print('numba version: ', numba.__version__)
print('numpy version: ', np.__version__)
print('all close: ', np.allclose(ans3, ans3j))
```

Returns:

```
numba version:  0.42.1
numpy version:  1.16.2
all close:  False
```

I am using  Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04)
Spyder 3.3.4

**Comment by isaac-you** [comment] 2019-06-05 01:26
I know the problem now, the version of numba can produce different result 

```
print('numba version: ', numba.__version__)
print('numpy version: ', np.__version__)
print('all close: ', np.allclose(ans3, ans3j))
```

Returns:
```
numba version:  0.44.0
numpy version:  1.14.3
all close:  True
```
This experiment excuted in Python 3.6.5 |Anaconda, Inc
JupyterLab  Version 0.32.1

**Comment by isaac-you** [comment] 2019-06-05 01:41
NO!!!  This is not the problem of numba version. Maybe it is the problem of spyder, weird!

```
print('numba version: ', numba.__version__)
print('numpy version: ', np.__version__)
print('all close: ', np.allclose(ans3, ans3j))
```

```
numba version:  0.44.0
numpy version:  1.16.2
all close:  False
```
Spyder 3.3.4   Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04)

**Comment by esc** [comment] 2020-09-21 09:19
@isaac-you This issue is now > 1 year old. I will assume since no newfollow-ups were posted the issue is most likely resolved and therefore I will close it. If this is not the case and the issue persists even with a newer version of Numba, please don't hesitate to open a new issue or start a discussion on Discourse: https://numba.discourse.group/ -- thank you for using Numba!

**Closed by esc** 2020-09-21 09:19 UTC
Labels: more info needed

**Comment by carlos-adir** [comment] 2023-01-20 19:40
I replicated the error:

```
numba version:  0.56.4
numpy version:  1.23.1
python version:  3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
all close:  False
```
