### ISSUE TITLE
`.strip()` not stripping `\t`.

### ISSUE THREAD

**Issue by sklam** [numba/numba#4731] opened 2019-10-21 18:18 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
>>> from numba import njit
>>> s = '  \t bbcd\t '
>>> s.strip()
'bbcd'
>>> @njit
... def foo(s):
...     return s.strip()
...
>>> foo(s)
'\t bbcd\t'
>>>

```

**Comment by sklam** [comment] 2019-10-21 18:30
Need to fix these 2 lines
https://github.com/numba/numba/blob/ad3303c25133d57127abf8be1cd72d6048f45813/numba/unicode.py#L890
https://github.com/numba/numba/blob/ad3303c25133d57127abf8be1cd72d6048f45813/numba/unicode.py#L879
Perhaps replacing `' '` with https://docs.python.org/3.7/library/string.html#string.whitespace

**Comment by ehsantn** [comment] 2019-10-21 18:49
duplicate of #4188.

**Comment by shimst3r** [comment] 2019-10-23 09:52
I'd like to take a look at this as my first issue. Is this okay even though the issue is marked as `duplicate` or should I resolve the original issue instead?

**Comment by stuartarchibald** [comment] 2019-10-23 10:04
@shimst3r great, thanks for wanting to contribute. I'd go for resolving the issue reported here with `\t` and extending the testing for cover that, and then if you are happy with that move on to cover the contents of #4188. Hows that sound?

As a new contributor, some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.

Thanks!

**Comment by shimst3r** [comment] 2019-10-23 10:24
Sounds great to me and thank you for the link. 👍

**Comment by rohitsanj** [comment] 2020-02-07 14:40
@shimst3r @stuartarchibald took this one home

**Closed** 2020-02-10 21:05 UTC
Labels: bug, duplicate, easy, good first issue
