### ISSUE TITLE
Using literal dicts fails to compile when string keys hold numeric data

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#7416] opened 2021-09-17 19:08 UTC
- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi!

Trying to use a LiteralStrKeyDict we found an issue, when string keys with numeric data are forbidden, e.g.

```
import numpy as np
import numba
from numba import types, njit

@njit
def tested():
    lit_dict = {'0': np.ones(5),
                    '1': ['a', 'b', 'c']}
    return len(lit_dict)

print("Dict size: ", tested())

# # below commented version works as expected
# @njit
# def tested():
#     lit_dict = {'f0': np.ones(5),
#                 'f1': ['a', 'b', 'c']}
#     return len(lit_dict)
#   
# print("Dict size: ", tested())
```

produces:
> Traceback (most recent call last):
>   File "test_literal_dict.py", line 12, in <module>
>     print("Dict size: ", tested())
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 420, in _compile_for_args
>     error_rewrite(e, 'typing')
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 361, in error_rewrite
>     raise e.with_traceback(None)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Internal error at <numba.core.typeinfer.BuildMapConstraint object at 0x000001F7C7783288>.
> Type names and field names must be valid identifiers: '0'
> During: typing of dict at test_literal_dict.py (9)
> Enable logging at debug level for details.
> 
> File "test_literal_dict.py", line 9:
> def tested():
>     <source elided>
>     lit_dict = {'0': np.ones(5),
>                 '1': ['a', 'b', 'c']}
>                 ^

It seems the reason is that namedtuple used in impl requires field names to be non-numeric, here:
https://github.com/numba/numba/blob/4911192c5b51f3ecbb76a12b74372979378c43a1/numba/core/types/containers.py#L775

When the above code executes `strkeys == ['0', '1']` and this line raises above exception. Is there any easy fix for this?

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment] 2021-09-20 09:52
Thanks for the report. I think this is a duplicate of https://github.com/numba/numba/issues/6518 ? Fix is likely that noted here: https://github.com/numba/numba/issues/6518#issuecomment-736651396

**Comment by stuartarchibald** [comment] 2021-09-29 11:45
@kozlov-alexey am hoping that #7441 will fix.

**Closed** 2021-11-18 00:20 UTC
Labels: duplicate, bug - failure to compile
