### ISSUE TITLE
Error compiling umap

### ISSUE THREAD

**Issue by andresgalarza-astro** [numba/numba#4236] opened 2019-06-28 04:45 UTC
I tried the basic test with iris data but I found this issue:

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-20-31642242b990> in <module>
----> 1 embedding = reducer.fit_transform(iris.data)
      2 embedding.shape

~/anaconda/lib/python3.6/site-packages/umap/umap_.py in fit_transform(self, X, y)
   1594             Embedding of the training data in low-dimensional space.
   1595         """
-> 1596         self.fit(X, y)
   1597         return self.embedding_
   1598 

~/anaconda/lib/python3.6/site-packages/umap/umap_.py in fit(self, X, y)
   1417                 self.set_op_mix_ratio,
   1418                 self.local_connectivity,
-> 1419                 self.verbose,
   1420             )
   1421         else:

~/anaconda/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    348                 e.patch_message(msg)
    349 
--> 350             error_rewrite(e, 'typing')
    351         except errors.UnsupportedError as e:
    352             # Something unsupported is present in the user code, add help info

~/anaconda/lib/python3.6/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    315                 raise e
    316             else:
--> 317                 reraise(type(e), e, None)
    318 
    319         argtypes = []

~/anaconda/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type none

File "../../anaconda/lib/python3.6/site-packages/umap/umap_.py", line 93:
def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):
    <source elided>
    target = np.log2(k) * bandwidth
    rho = np.zeros(distances.shape[0])
    ^

[1] During: typing of get attribute at /Users/Andres/anaconda/lib/python3.6/site-packages/umap/umap_.py (93)

File "../../anaconda/lib/python3.6/site-packages/umap/umap_.py", line 93:
def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):
    <source elided>
    target = np.log2(k) * bandwidth
    rho = np.zeros(distances.shape[0])
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by esc** [comment] 2019-07-01 01:58
Hi @andresgalarza-astro , thanks for trying out Numba and for reporting this. I will fixup your comment to use markdown for formatting. Also, could you list the version of Numbad and umap that you are working with with? Thanks!

**Comment by andresgalarza-astro** [comment] 2019-07-01 23:40
Sure!
Versions are: Numba  0.43.1 and umap 0.3.9

**Comment by esc** [comment] 2019-07-02 15:11
@andresgalarza-astro great, could you perhaps upgrade to the latest Numba 0.44.1 and check if the error persists. If yes, please report back the commands you used to run the tests so that we can try to reproduce this.

**Comment by andresgalarza-astro** [comment] 2019-07-05 14:31
Sorry for the delay.
I'll follow your suggestion and give a feedback later in the day

**Comment by stuartarchibald** [comment] 2020-02-24 13:21
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-02-24 13:21 UTC
Labels: needtriage
