### ISSUE TITLE
 numba acceleration not working in python-sgp4

### ISSUE THREAD

**Issue by sklam** [numba/numba#3141] opened 2018-07-20 16:18 UTC
A user at scipy sprint pointed out this numba issue:

https://github.com/brandon-rhodes/python-sgp4/issues/18

**Comment by stuartarchibald** [comment] 2020-09-11 08:10
Closing this as the upstream issue is closed and there's no reproducer.

**Closed by stuartarchibald** 2020-09-11 08:10 UTC
Labels: needtriage

**Comment by astrojuanlu** [comment] 2020-09-11 08:36
xref https://github.com/brandon-rhodes/python-sgp4/issues/46 upstream issue was closed because the numba implementation was problematic (not necessarily numba's fault, adding this just for context)
