### ISSUE TITLE
Numba 0.42.1 on Linux : 'No threading layer could be loaded' when config.THREADING_LAYER = 'omp'

### ISSUE THREAD

**Issue by Yoshi2112** [numba/numba#3843] opened 2019-03-08 06:26 UTC
Hi all, sorry if this is not appropriate as its my first bug report. It may simply be user error. Trying to get numba to use OpenMP as the threading layer, following the bare bones example from the documentation. This is clearly a problem with the 'Unknown import problem'. It was installed via pip install intel-openmp

### Minimum Working Example
```
from numba import config, njit, threading_layer
import numpy as np

config.THREADING_LAYER = 'omp'

@njit(parallel=True)
def foo(a, b):
    return a+b

x = np.arange(10.)
y = x.copy()

foo(x, y)

print("Threading layer chosen: %s" % threading_layer())
```
### Output
```
Traceback (most recent call last):
  File "threading_layer_test.py", line 18, in <module>
    foo(x, y)
  File "/home/yoshi/.local/lib/python2.7/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No threading layer could be loaded.


File "threading_layer_test.py", line 12:
def foo(a, b):
    return a+b
    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.8, range = (0, a_size0.1, 1))]{1: <ir.Block at threading_layer_test.py (12)>}Var(parfor_index.8, threading_layer_test.py (12))" at threading_layer_test.py (12)
`Traceback (most recent call last):
  File "threading_layer_test.py", line 18, in <module>
    foo(x, y)
  File "/home/yoshi/.local/lib/python2.7/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No threading layer could be loaded.


File "threading_layer_test.py", line 12:
def foo(a, b):
    return a+b
    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.8, range = (0, a_size0.1, 1))]{1: <ir.Block at threading_layer_test.py (12)>}Var(parfor_index.8, threading_layer_test.py (12))" at threading_layer_test.py (12)
```

### System
```
__Time Stamp__
2019-03-08 06:09:36.885706

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake
Number of accessible CPU cores                : 8
Listed accessible CPUs cores                  : 0-7
CFS restrictions                              : None
CPU Features                                  : 
adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase invpcid lzcnt
mmx movbe pclmul popcnt prfchw rdrnd rdseed rtm sahf sgx sse sse2 sse3 sse4.1
sse4.2 ssse3 xsave xsavec xsaveopt xsaves

__OS Information__
Platform                                      : Linux-4.15.0-36-generic-x86_64-with-LinuxMint-19-tara
Release                                       : 4.15.0-36-generic
System Name                                   : Linux
Version                                       : #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018
OS specific info                              : LinuxMint19tara
glibc info                                    : glibc 2.7

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 2.7.15rc1
Python Locale                                 : en_AU UTF-8

__LLVM information__
LLVM version                                  : 7.0.0

__CUDA Information__
Error: CUDA device intialisation problem. Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBAPRO_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
Conda not present/not working.
Error was [Errno 2] No such file or directory
```

**Comment by stuartarchibald** [comment] 2019-03-08 09:10
Thanks for the report. As noted, that there is an "unknown problem" would be the reason it doesn't work, once that is fixed the code above should work fine. On linux IIRC the OpenMP threading layer is linked against `libgomp.so` to provide the necessary functionality, so this needs to be present and functioning correctly.

Please could you paste the output (redacting any parts you don't wish to share) of the following:
```
python -c 'from numba.npyufunc import omppool'
```
and
```
ldd $(find `python -c 'import sys; print(sys.prefix)'`|egrep 'omppool.cpython.*\.so')
```

The first may report a more raw error about the problem with `omppool` and the second is checking the linkage of the `omppool` DSO. Thanks again!

**Comment by Yoshi2112** [comment] 2019-03-08 10:51
It may simply be an issue with my install of OpenMP, however as I followed the instructions (and I'm not a dev) and I was aware there were issues with this in the 0.40 build I figured better safe than sorry.

```
python -c 'from numba.npyufunc import omppool'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name omppool
```
and

```
ldd $(find `python -c 'import sys; print(sys.prefix)'`|egrep 'omppool.cpython.*\.so')
ldd: missing file arguments
Try `ldd --help' for more information.
```

**Comment by stuartarchibald** [comment] 2019-03-08 10:57
@Yoshi2112 thanks, this has jogged my memory :) I assume you `pip` installed Numba? If so the reason the OpenMP backend doesn't work is because it is disabled since 0.40.1 in wheel builds (and evidently isn't built/shipped as noted by `ldd: missing file arguments`). An issue describing some of the details is here https://github.com/numba/numba/issues/3400 .

For a working OpenMP backend use the Anaconda distribution package or compile from source?

**Comment by Yoshi2112** [comment] 2019-03-08 11:09
I did pip install numba. I only use my linux machine (with a Python 2.7 environment) to run particle codes (hence the need for speedup and multiprocessing). I will try reinstalling everything in a conda environment instead (and hope I don't break any dependencies). Would you be able to tell me how to install OpenMP from source without going through the Anaconda distribution? Just for completion and reference.

Thanks for your help! :)

**Comment by stuartarchibald** [comment] 2019-03-08 11:29
I see, then what you experience is expected (#3400). 

> Would you be able to tell me how to install OpenMP from source without going through the Anaconda distribution?

Apologies, I perhaps wasn't sufficiently clear, it's Numba that needs compiling from source, instructions are here: http://numba.pydata.org/numba-doc/latest/user/installing.html#installing-from-source, a from-source build would detect the `libgomp` present on your machine and so the OpenMP threading layer would get built and should work fine.

I'm going to close this ticket as I think the issue is resolved. If you have any further issues please open a new ticket. Thanks for using Numba.

**Closed by stuartarchibald** 2019-03-08 11:29 UTC
Labels: needtriage
