### ISSUE TITLE
numba.njit(parallel=True) LoweringError with astropy.units

### ISSUE THREAD

**Issue by StanczakDominik** [numba/numba#4637] opened 2019-09-30 09:11 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I'm trying to get numba to work together with [astropy.units](https://docs.astropy.org/en/stable/units/). Consider this code sample:
```python
import numpy as np
import astropy.units as u
import numba

@numba.njit()
def inplace_update(x, v, dt):
    for i in numba.prange(len(x)):
        x[i] = v[i]*dt


x = np.arange(1000) * u.m
v = np.arange(1000) * (u.m / u.s)
dt = 1 * u.s
inplace_update(x, v, dt)
print(x)
```
This, to my positive surprise, works properly, returning what it should! However, if I try to do the same thing with `parallel=True`: 

```python
import numpy as np
import astropy.units as u
import numba

@numba.njit(parallel=True)
def parallel_inplace_update(x, v, dt):
    for i in numba.prange(len(x)):
        x[i] = v[i]*dt


x = np.arange(1000) * u.m
v = np.arange(1000) * (u.m / u.s)
dt = 1 * u.s
parallel_inplace_update(x, v, dt)
print(x)
```

this results in an exception, with the following traceback:

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/errors.py", line 662, in new_error_context
    yield
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 410, in lower_inst
    func(self, inst)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/parfor.py", line 283, in _lower_parfor_parallel
    parfor.races)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/parfor.py", line 1177, in call_parallel_gufunc
    cache=False, is_parfors=True)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/parallel.py", line 250, in build_gufunc_wrapper
    py_func, cres, sin, sout, cache=cache, is_parfors=is_parfors,
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 503, in build_gufunc_wrapper
    py_func, cres, sin, sout, cache, is_parfors=is_parfors,
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 456, in build
    wrapperlib = self._compile_wrapper(wrapper_name)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 435, in _compile_wrapper
    self._build_wrapper(wrapperlib, wrapper_name)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 412, in _build_wrapper
    args = [a.get_array_at_offset(loop.index) for a in arrays]
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 412, in <listcomp>
    args = [a.get_array_at_offset(loop.index) for a in arrays]
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 663, in get_array_at_offset
    data=self.data, ind=ind)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/npyufunc/wrappers.py", line 719, in load
    meminfo=None)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/targets/base.py", line 975, in populate_array
    return arrayobj.populate_array(arr, **kwargs)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 226, in populate_array
    setattr(array, k, v)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/cgutils.py", line 164, in __setattr__
    self[self._datamodel.get_field_position(field)] = value
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/cgutils.py", line 193, in __setitem__
    index=index))
TypeError: Invalid store of [1 x i64] to [0 x i64] in <numba.datamodel.models.ArrayModel object at 0x7fa92c71b550> (trying to write member #5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numbatest2.py", line 14, in <module>
    parallel_inplace_update(x, v, dt)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/progs/miniconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Invalid store of [1 x i64] to [0 x i64] in <numba.datamodel.models.ArrayModel object at 0x7fa92c71b550> (trying to write member #5)

File "numbatest2.py", line 7:
def parallel_inplace_update(x, v, dt):
    for i in numba.prange(len(x)):
    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.5, range = (0, x_size0.1, 1))]{18: <ir.Block at numbatest2.py (7)>}Var(parfor_index.5, numbatest2.py (7))" at numbatest2.py (7)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
</details>

I thought maybe numba can't parallelize the single `dt` timestep between threads, so I tried with `dt = np.ones(1000) * u.s`, resulting in:

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "numbatest3.py", line 14, in <module>
    parallel_inplace_update(x, v, dt)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 376, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 343, in error_rewrite
    reraise(type(e), e, None)
  File "/progs/miniconda3/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float64, 1d, C), int64, array(float64, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at numbatest3.py (8)

File "numbatest3.py", line 8:
def parallel_inplace_update(x, v, dt):
    <source elided>
    for i in numba.prange(len(x)):
        x[i] = v[i]*dt
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
</details>

I'm thus confused on whether numba accidentally happens to work with astropy.units in some cases and not in others!

**Comment by esc** [comment] 2019-09-30 09:34
@StanczakDominik thanks for reporting this, we appreciate it. I can confirm that I am able to reproduce the error. I suspect a bug in parfors (parallel accelerator), but this will need some more triage.

**Comment by stuartarchibald** [comment] 2019-10-01 13:15
Given this looks like it's just a typing issue, it'd be good to get an plain NumPy rendition of the problem. I expect it's something to do with 0d arrays or degrading 1d array assignments or similar.

**Comment by stuartarchibald** [comment] 2019-10-03 09:19
I suspect that `astropy.units` "just working" is due to them looking a lot like NumPy arrays once you scale/combine them with a quantity, e.g.
```python
import astropy.units as u
a = u.s * 1 # this is a "<Quantity 1. s>"
print(a.__array_interface__)
```
which gives:
```
{'data': (93838271247360, False), 'strides': None, 'descr': [('', '<f8')], 'typestr': '<f8', 'shape': (), 'version': 3}
```
and is therefore consumable as a NumPy ndarray.

--------------------

The first issue, that results in:
```
Invalid store of [1 x i64] to [0 x i64] in <numba.datamodel.models.ArrayModel object at 0x7fa92c71b550> (trying to write member #5)
```
is a bug and is caused by ParallelAccelerator incorrectly handling 0d arrays, reproducer:
```python
import numpy as np
import numba

@numba.njit(parallel=True)
def foo(x, v, dt):
    for i in numba.prange(len(x)):
        x[i] = v[i]*dt

x = np.arange(1000)
v = np.arange(1000)
dt = np.array(1)
foo(x, v, dt)
print(x)
```
@DrTodd13 any chance you could take a look at the above please? Thanks.

------------------
The second issue which results in a:
```
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float64, 1d, C), int64, array(float64, 1d, C))
```
is not exclusively a ParallelAccelerator problem, it happens under standard `@njit`. The issue is that NumPy supports the degrading of a n-d array containing one element into a single value suitable for assignment, Numba does not. This is the same problem and has the same work around and explanation as here: https://github.com/numba/numba/issues/4650#issuecomment-537579052

Perhaps try this work around?:
```python
import numpy as np
import astropy.units as u
import numba

@numba.njit(parallel=True)
def parallel_inplace_update(x, v, dt):
    for i in numba.prange(len(x)):
        x[i] = (v[i] * dt)[0] # Take the zero-th index to permit assignment


x = np.arange(1000) * u.m
v = np.arange(1000) * (u.m / u.s)
dt = np.ones(1000) * u.s
parallel_inplace_update(x, v, dt)
print(x)
```

**Comment by DrTodd13** [comment] 2020-06-29 23:34
@StanczakDominik Seems to be working with master.  Will close this.  Please re-open if you have additional issues.

**Closed by DrTodd13** 2020-06-29 23:34 UTC
Labels: ParallelAccelerator, bug

**Comment by StanczakDominik** [comment] 2020-06-30 03:48
Wow, glad to hear that! I'll try it out, thanks :)
