### ISSUE TITLE
Inconsistant result between numba and py_func

### ISSUE THREAD

**Issue by renzhengchi** [numba/numba#6564] opened 2020-12-10 12:49 UTC
The result is inconsistant between numba and py_func. 
Platform: macOS Big Sur 11.0.1; Intel Core i5
Numba version: 0.51.2

```
import numpy as np
from numpy import nan, array
from numba import njit


@njit(cache=True, error_model='numpy')
def nanstd_1d(_array, ddof=0):
    count = (~np.isnan(_array)).sum()
    if count > 1:
        return (np.nanvar(_array) * count / (count - ddof)) ** 0.5
    else:
        return np.float64(np.NaN)


a = array([141.6, 141.6, 141.6, 141.6, 141.6, 141.6, 141.6, 141.6, 141.6,
       141.6, 141.6, 141.6,   nan, 141.6, 141.6, 141.6, 141.6,   nan,
         nan, 141.6,   nan,   nan, 141.6, 141.6,   nan, 141.6, 141.6,
       141.6,   nan,   nan,   nan, 141.6, 141.6, 141.6,   nan, 141.6,
         nan, 141.6, 141.6, 141.6,   nan,   nan,   nan, 141.6,   nan,
         nan,   nan, 141.6, 141.6,   nan,   nan, 141.6,   nan,   nan,
         nan, 141.6, 141.6, 141.6,   nan, 141.6, 141.6, 141.6, 141.6,
       141.6,   nan, 141.6,   nan, 141.6,   nan,   nan, 141.6, 141.6,
       141.6, 141.6, 141.6, 141.6,   nan,   nan,   nan, 141.6,   nan,
         nan,   nan, 141.6,   nan,   nan,   nan, 141.6, 141.6,   nan,
       141.6, 141.6, 141.6, 141.6, 141.6, 141.6,   nan, 141.6,   nan,
       141.6,   nan,   nan,   nan, 141.6,   nan, 141.6, 141.6, 141.6,
         nan,   nan,   nan, 141.6,   nan,   nan, 141.6,   nan,   nan,
         nan,   nan, 141.6])


print(nanstd_1d(a, ddof=1))
# 1.7179815698821102e-13
print(nanstd_1d.py_func(a, ddof=1))
# 0.0


```

**Comment by esc** [comment] 2020-12-10 13:07
@renzhengchi hello and thank you for your message. I have just tried the script on Catalina an receive the same result:

```
1.7179815698821102e-13
0.0
```

Which means this result is probably independent of BigSur.  I am not sure though there is much we can do about this and I'm not convinced (yet) that this is actually a bug. Floating point operations comes with rounding caveats, and perhaps this result can be considered "good enough"?

**Comment by stuartarchibald** [comment] 2020-12-10 13:17
Expect this comes from Numba using a fast but naive loop accumulation in the summation parts of the implementations whereas NumPy does, IIRC, pairwise.

**Comment by esc** [comment] 2020-12-10 13:32
@stuartarchibald thanks for the information. Does this mean, that the result is different because floating point arithmetic isn't associative in this case so the order in which elements are summed matters?

**Comment by seibert** [comment] 2020-12-10 14:43
Yes.  Both NumPy's approach and Numba's approach will have errors for some inputs relative to the "infinite precision" answer, but NumPy's errors will generally be smaller.

You minimize floating point errors when doing addition if both operands are of similar magnitude, which a pairwise sum tree will often achieve if all your input values have similar magnitude.  A begining-to-end loop will be adding a large number to a small number at the end.

The tradeoff is that pairwise summing an array (without destroying its contents) requires temporary storage, whereas a loop just needs a scalar accumulator.

The open PR to switch to pairwise sum is here: https://github.com/numba/numba/pull/3046

**Comment by stuartarchibald** [comment] 2020-12-21 22:08
Closing as the root issue is a duplicate of: https://github.com/numba/numba/issues/4259 along with others. Thanks for reporting this!

**Closed by stuartarchibald** 2020-12-21 22:08 UTC
Labels: question
