### ISSUE TITLE
heap implementation doesn't support typed list

### ISSUE THREAD

**Issue by p-ortmann** [numba/numba#5500] opened 2020-04-03 13:49 UTC
I am working with numba 0.48, couldn't see anything related in the change logs though
```
from heapq import heappop
   ...:from numba.typed import List
   ...:from numba import njit
   ...:@njit
   ...:def foo():
   ...:    my_heap=List()
   ...:    heap_item=(0,1)
   ...:    my_heap.append(heap_item)
   ...:    heappop(my_heap)
   ...:    
foo()
Traceback (most recent call last):
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-45-c19b6d9633cf>", line 1, in <module>
    foo()
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function heappop>) with argument(s) of type(s): (ListType[UniTuple(int64 x 2)])
 * parameterized
In definition 0:
    TypingError: heap argument must be a list
    raised from C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\targets\heapq.py:109
In definition 1:
    TypingError: heap argument must be a list
    raised from C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\targets\heapq.py:109
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function heappop>)
[2] During: typing of call at <ipython-input-44-b246dd417c7b> (10)
File "<ipython-input-44-b246dd417c7b>", line 10:
def foo():
    <source elided>
    my_heap.append(heap_item)
    heappop(my_heap)
    ^

```
seems to work fine inside of a njitted function with []
```
from heapq import heappop
   ...:from numba import njit
   ...:@njit
   ...:def foo():
   ...:    my_heap=[]
   ...:    heap_item=(0,1)
   ...:    my_heap.append(heap_item)
   ...:    heap_item=heappop(my_heap)
   ...:foo()
```

**Comment by p-ortmann** [comment] 2020-04-03 13:58
I am just realizing I got the example wrong, will update this ..

**Comment by esc** [comment] 2020-04-03 14:44
@p-ortmann thanks for submitting this! I believe this is a duplicate of https://github.com/numba/numba/issues/4926 and I will close this issue now and mark as duplicate. Let me know if this is erroneous.

**Closed** 2020-04-03 14:44 UTC
Labels: duplicate
