### ISSUE TITLE
Regression in Numba 0.20 / cudatoolkit 0.7 (NVVM_ERROR_COMPILATION)

### ISSUE THREAD

**Issue by hmgaudecker** [numba/numba#1341] opened 2015-08-03 15:00 UTC
I have some Numba-CUDA code that compiles and runs fine on Ubuntu 15.04 with a GTX 980 and NVIDIA Drivers 346.59 in a Python 3.4 Miniconda environment with numba=0.19 cudatoolkit=6. It fails with the latest versions of the latter two, see below.

Unfortunately, I have not been able to track down the issue to a simple testcase, but @gmarkall has the whole code base. It would be great to know if this is my ignorance or some issue in Numba.

Thanks.

```
$ conda install numba=0.20 cudatoolkit=7
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /home/xxx/miniconda3/envs/yyy:

The following packages will be UPDATED:

    cudatoolkit: 6.0-p0            --> 7.0-1
    llvmlite:    0.5.0-py34_0      --> 0.6.0-py34_0
    numba:       0.19.1-np19py34_0 --> 0.20.0-np19py34_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE ]|###################################################| 100%
Linking packages ...
[      COMPLETE ]|###################################################| 100%
(yyy)xxx@xxx$ python src/analysis/main.py baseline solve_and_simulate start

Traceback (most recent call last):
  File "/home/xxx/econ/yyy-master/src/analysis/main.py", line 34, in <module>
    m.solve_and_simulate(stage=stage)
  File "/home/xxx/econ/yyy-master/src/model/empirical_model.py", line 111, in solve_and_simulate
    self.choices_valuations = find_decision_rules(self.model, converted_data)
  File "/home/xxx/econ/yyy-master/src/model/find_decision_rules.py", line 44, in find_decision_rules
    h5file
  File "/home/xxx/econ/yyy-master/src/model/find_decision_rules.py", line 125, in find_decision_rules_one_pref_type
    h5file
  File "/home/xxx/econ/yyy-master/src/model/find_decision_rules.py", line 225, in find_decision_rules_one_age
    age_dependent_data
  File "/home/xxx/econ/yyy-master/src/model/compute_valuation.py", line 63, in compute_valuation
    _compute_valuation[(blockspergrid, threadsperblock)](*kernelargs)
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/compiler.py", line 504, in __call__
    kernel = self.specialize(*args)
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/compiler.py", line 523, in specialize
    kernel.bind()
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/compiler.py", line 321, in bind
    self._func.get()
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/compiler.py", line 256, in get
    ptx = self.ptx.get()
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/compiler.py", line 228, in get
    **self._extra_options)
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 422, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 213, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 231, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 120, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

(0) Error: unsupported operation

NVVM_ERROR_COMPILATION
```

**Comment by gmarkall** [comment] 2015-08-03 15:33
I can reproduce this - just looking out for if there is something unwanted that's crept into the IR somehow.

**Comment by gmarkall** [comment] 2015-08-04 09:20
A somewhat smaller reproducer:

```python
import numpy as np
from numba import cuda, int32

@cuda.jit(device=True)
def inner_kernel(p):
    p[0] = 1 / p[0]

@cuda.jit
def outer_kernel(p1, p2, p3, p4, p5, p6, p7, p8):
    local_p = cuda.local.array((2,), dtype=int32)
    inner_kernel(p1)

p1 = np.zeros(16, dtype=np.float32)
p2 = np.zeros((216, 12), dtype=np.int8)
p3 = np.zeros(216, dtype=np.float32)
p4 = np.zeros(216, dtype=np.float32)
p5 = np.zeros(216, dtype=np.float32)
p6 = 94
p7 = np.zeros(1, dtype=np.float64)
p8 = np.zeros(32, dtype=np.float32)

outer_kernel(p1, p2, p3, p4, p5, p5, p7, p8)
```

produces:

```
$ python issue_1341.py 
Traceback (most recent call last):
  File "issue_1341.py", line 22, in <module>
    outer_kernel(p1, p2, p3, p4, p5, p5, p7, p8)
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/compiler.py", line 504, in __call__
    kernel = self.specialize(*args)
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/compiler.py", line 523, in specialize
    kernel.bind()
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/compiler.py", line 321, in bind
    self._func.get()
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/compiler.py", line 256, in get
    ptx = self.ptx.get()
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/compiler.py", line 228, in get
    **self._extra_options)
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 422, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 213, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 231, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/home/gmarkall/miniconda3/envs/py34np19/lib/python3.4/site-packages/numba/cuda/cudadrv/nvvm.py", line 120, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

(0) Error: unsupported operation

NVVM_ERROR_COMPILATION
```

Removing any of the parameters or the local array also makes the error message go away.

**Comment by gmarkall** [comment] 2015-08-04 09:20
Also using any operation other than a division also removes the error message.

**Comment by gmarkall** [comment] 2015-08-04 11:23
Update: this is something to do with `___numba_cas_hack` - commenting out the call to this function in the generated LLVM IR removes the error message.

**Comment by hmgaudecker** [comment] 2015-08-10 14:54
Just to note: Adding the patch does not help on either Graham's test or the real project.

**Comment by sklam** [comment] 2015-08-10 15:24
@hmgaudecker, Can you try the prebuilt numba package?  `conda install -c numba numba`.

I verified Graham's test on the following versions with ubuntu 14.04, python34, numpy19, Tesla K20c:
```
numba                     0.20.0             np19py34_523  
llvmlite                  0.6.0                   py34_17  
cudatoolkit               7.0                           1 
```

**Comment by sklam** [comment] 2015-08-10 15:27
btw, my driver version is 346.46

**Comment by hmgaudecker** [comment] 2015-08-10 15:28
Good catch! Graham's test passes indeed, unfortunately the larger project does not.

**Comment by sklam** [comment] 2015-08-19 20:13
My investigation has led me to believe that the libnvvm from cuda 7 has memory errors when a kernel has complex control flow.  For a function that has a large if-elif-else chain, nvvm consumed over 6GB of RAM.  The same program crashed inside nvvm for cuda 6.5; and, for cuda 6, it finished with max 1GB RAM usage.  

I started testing with CUDA 7.5rc.  My test program compiles a lot faster and with just 100+MB of RAM.  @gmarkall, can you test with CUDA 7.5rc?

**Comment by sklam** [comment] 2015-08-19 20:40
My test script: https://gist.github.com/sklam/f62f1f48bb0be78f9ceb
It uses llvmlite to generate a interpreter-loop like kernel.

**Comment by gmarkall** [comment] 2015-08-25 09:23
The test script works for me both with CUDA 7.0 and 7.5rc1, but runs an order of magnitude faster with 7.5rc1.

The struct-ret code now is now failing in `simulate_all_decisions` whereas before, it was failing in `compute_valuation` - this failure occurs with both CUDA 7.0 and 7.5rc1.

I can reproduce the issue easily - it was sufficient to pickle the arguments to `simulate_all_decisions` then call it with the pickled arguments to replicate the issue, so I don't need to wait 15 minutes for a test each time. Hopefully I can cut down this new issue to a smaller test case.

**Comment by gmarkall** [comment] 2015-08-25 12:07
A reproducer for the current issue, which fails with Numba master and both the 7.0 and 7.5rc1 CUDA toolkits:

```python
from numba import cuda, int64
import numpy as np
 
p1 = np.zeros(2000, dtype=np.int64)
p2 = np.zeros(2000, dtype=np.int16)
p3 = np.zeros(2000, dtype=np.int16)
p4 = np.zeros(2000, dtype=np.float32)
p5 = np.zeros((22390, 2), dtype=np.int64)
p6 = np.zeros(22390, dtype=np.float64)
p7 = np.zeros(22390, dtype=np.int8)
 
@cuda.jit
def f(p1, p2, p3, p4, p5, p6, p7):
    if 0 >= len(p1):
        return
 
    l1 = cuda.local.array((2,), dtype=int64)
    l1[0] = 0
    l1[1] = 0
 
f(p1, p2, p3, p4, p5, p6, p7)
```

My current hypothesis/hunch is that NVVM doesn't like it when there is an `alloca` that doesn't dominate all `ret`s... What do you think @sklam ?

**Comment by gmarkall** [comment] 2015-08-25 12:52
@hmgaudecker Moving the `cuda.local.array` declarations to the top of the `simulate_all_decisions` function seems to provide a workaround (with CUDA 7.5rc1 - just trying again with CUDA 7.0) - `waf` runs to completion and I have various figures produced in the `fake/out/figures/moments/baseline-data-vs-baseline-model` folder. I have pushed this to the issue_1341_workaround branch of the struct-ret repo.

**Comment by gmarkall** [comment] 2015-08-25 13:23
Just finished running with CUDA 7.0 - it also seems to work with the local array declarations moved.

**Comment by sklam** [comment] 2015-08-25 14:55
If it is the location of ``cuda.local.array``, we can fix it in the codegen so that @hmgaudecker does not need to modify his code.

**Comment by gmarkall** [comment] 2015-08-25 15:01
I think it is - one thing I plan to test is to turn off the O1 optimisation pass before sending the IR to NVVM, and then moving the `cuda.local.array` declarations to the top of the `compute_valuation` function and seeing if that also manages to run successfully... If that works, then it would add weight to the idea that the problem is to do with the location of allocations.

**Comment by seibert** [comment] 2017-11-03 16:21
Closing, as it looks like this was resolved.

**Closed by seibert** 2017-11-03 16:21 UTC
