### ISSUE TITLE
Asking about the dict in numba

### ISSUE THREAD

**Issue by baopanda** [numba/numba#6019] opened 2020-07-22 09:27 UTC
Dear Numba team
I have using your library to optimize my code but when I apply it, I caught a trouble. Can you help me to fix it?
```
@jit
def encode2char_safe(input_lines, char_dict):
    unk = char_dict['<u>']
    forw_lines = [list(map(lambda m: list(map(lambda t: char_dict.get(t, unk), m)), line)) for line in input_lines]
    return forw_lines
```
and the error
```
numba.core.errors.TypingError: Failed in object mode pipeline (step: convert make_function into JIT functions)
Cannot capture the non-constant value associated with variable 'char_dict' in a function that will escape.

def encode2char_safe(input_lines, char_dict):
    <source elided>
    unk = char_dict['<u>']
    forw_lines = [list(map(lambda m: list(map(lambda t: char_dict.get(t, unk), m)), line)) for line in input_lines]
    ^

This error may have been caused by the following argument(s):
- argument 1: cannot determine Numba type of <class 'dict'>
```

can you help me to use numba to optimize my code.
Thank you in advance and I hope to hearing from you soon.

**Comment by esc** [comment] 2020-07-22 10:16
@baopanda thanks for submitting this, would you be able to supply some sample inputs, like `input_lines` and `char_dict`? It will help to reproduce your issue. Thanks!

**Comment by baopanda** [comment] 2020-07-22 10:32
@esc yeppp,
input_lines (list of strings) : input corpus
char_dict (dictionary) : char-level dictionary
thank for your help

**Comment by stuartarchibald** [comment] 2020-07-22 10:33
The issue is here:
```python
map(lambda t: char_dict.get(t, unk), m)
```
the `lambda` must be compiled and passed to `map`, but the `lambda` is capturing the variable `char_dict` in the process and there's no way to capture it in a function for static compilation as it's non-constant (it's an argument to the outer function). `map`, `filter` and `reduce` are quite restricted due to this.

**Comment by baopanda** [comment] 2020-07-22 10:38
@stuartarchibald yeppp, thank you. Can you tell me the way to fix it? I will very appreciate

**Comment by stuartarchibald** [comment] 2020-07-22 10:53
I'm afraid that I don't think there is a way to fix this without hitting more problems, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) to find out what Numba is best at and whether it's a good fit for your problem? I'd also suggest trying to simplify code as much as possible, it makes it easier for Numba to work out what to do (i.e. `map`s with `lambda`s are really hard to analyse!).

**Comment by esc** [comment] 2020-07-27 14:54
I will close this issue now, as I believe it has been resolved. If this is not the case, please don't hesitate to reopen this or open a new one.

**Closed by esc** 2020-07-27 14:54 UTC
Labels: question
