### ISSUE TITLE
Lowering error

### ISSUE THREAD

**Issue by hyunwoongko** [numba/numba#7889] opened 2022-03-05 09:44 UTC
```python
import numpy as np
import numba as nb

@nb.njit
def fn(iterable, k): 
    if k == 1: 
        return [[iterable]] # list[list[np.array(int64)]] 
    if k == len(iterable): 
        return [[i for i in iterable.reshape(iterable.shape[0], 1)]] # list[list[np.array(int64)]]

arr = np.array([1, 2, 3, 4])
fn(arr, 1)
fn(arr, 4)
```

```
File "numba_version.py", line 10:
def fn(iterable, k):
    <source elided>
    if k == 1:
        return [[iterable]]
        ^

During: lowering "$16return_value.3 = cast(value=$14build_list.2)" at / ...
```

I can't understand why this can not be compiled. could you help me?

**Comment by esc** [comment] 2022-03-06 20:24
@hyunwoongko thank you for posting this. I am having trouble reproducing this error message. Which version of Numba and Python are you on. (Can you post `numba -s`).

**Comment by stuartarchibald** [comment] 2022-03-22 15:02
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2022-03-22 15:02 UTC
Labels: needtriage
