### ISSUE TITLE
interest in arm64 (armv8, aarch64, 64-bit arm) support

### ISSUE THREAD

**Issue by vielmetti** [numba/numba#3308] opened 2018-09-13 21:23 UTC
## Feature request

I'm interested in arm64 support for numba. Before diving in to look at code,
I looked at the issues repository, and found some items related to the Tegra TX2 (e.g. #2849 ) which suggested that the "build from source" option could be useful.

**Comment by vielmetti** [comment] 2018-09-13 22:10
ah, I notice hidden documentation at https://github.com/numba/numba/commit/e1335a44971ae1fbd99ef7d02e2b6ed3dc0bd7ac#diff-918372d20763a54fb1530f1e41e96f4b pending news from @seibert - I'll be patient to see how the referenced dependencies shake out.

**Comment by seibert** [comment] 2018-09-14 15:28
Yeah, we've tested Numba on the Jetson TX2 board running Ubuntu 16.04 and confirmed both the CPU and CUDA backends work.  The main obstacle to wider use is a good way to distribute binary packages, since building LLVM from scratch is a pain.  [Berryconda](https://github.com/jjhelmus/berryconda) is a great conda-based distribution for the Raspberry Pi.  I have a fork of it called [Jetconda](https://github.com/seibert/jetconda) that we've used to build a very skeleton environment for Numba testing on the TX2 (though I expect the packages to work on any Ubuntu-based ARMv8 board).  It needs more packages, however, and I haven't had time to expand it yet.

**Comment by stuartarchibald** [comment] 2018-09-28 08:51
There's a few 0.40.0dev0 builds for `aarch64` on the Numba channel.
```
$ CONDA_SUBDIR=linux-aarch64 conda search -c numba numba
Loading channels: done
# Name                  Version           Build  Channel             
numba                0.40.0dev0   np111py36_316  numba               
numba                0.40.0dev0   np111py36_328  numba               
numba                0.40.0dev0   np111py36_331  numba               
numba                0.40.0dev0   np111py36_356  numba 
```
these were built against Jetconda on a TX2. They are hugely experimental!

**Comment by nmgeek** [comment] 2018-12-26 17:15
@seibert said
> The main obstacle to wider use is a good way to distribute binary packages, since building LLVM from scratch is a pain.

It looks to me like the numba/llvmlite developers do this for x86 and other platforms using automated build scripts and posting the binary wheels to pypi.  But I have found that arm64 build servers are a bit hard to find.  Maybe the system/cloud you use to run the automated builds has no arm64 servers.

Instructions for running this build manually are [here](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html) but how are the builds run automatically?  I see yaml files that describe how to apply the patches but I'm not sure what uses them.

**Comment by seibert** [comment] 2018-12-28 01:44
We use [conda-build](https://conda.io/docs/user-guide/tasks/build-packages/index.html), which takes the YAML recipe files you see and produces binary conda packages.  We built a very limited fork of the [Berryconda](https://github.com/jjhelmus/berryconda) for ARMv8 that we're calling [Jetconda](https://github.com/seibert/jetconda/releases) (because it is built and tested on the Jetson TX2).  Jetconda is not kept very up to date, since we don't currently have the resources to do that, but it does let us confirm that Numba/llvmlite/LLVM work properly on ARMv8.

Due to various limitations of public CI systems (no GPUs, no PPC, no ARM, generally slow hardware), the Numba developers maintain a private build farm at Anaconda that contains one of every supported platform (ARMv7 is handled by a Raspberry Pi 3B+, and ARMv8 is built and tested on the Jetson TX2) and does the final build and test of packages.  We currently use buildbot to launch conda-build when commits are made to the master branch, but in the past we have also used Jenkins for this.  Either way, conda-build is doing all the heavy lifting, regardless of what job scheduler we use.

**Comment by nmgeek** [comment] 2018-12-28 18:06
I made that wheel: llvmlite-0.23.0-cp27-cp27mu-linux_aarch64.whl.  What about posting it?

FWIW, the manual build instructions at https://llvmlite.readthedocs.io/en/v0.23.0/admin-guide/install.html do not include patching instructions and the patches don't work out of the box so it involved some manual cleanup.  If I knew how conda-build applied patches it might have been easier.  And building that llvm monster on a TX2 takes more than an hour.  I applied these patches:
```
llvm-lto-static.patch
twine_cfg_undefined_behavior.patch
intel-svml.patch
0001-Transforms-Add-missing-header-for-InstructionCombini.patch
```

**Comment by vielmetti** [comment] 2019-01-04 19:00
@seibert - @nmgeek - If it would help the `jetconda` effort to have data center grade arm64 servers to run on, please contact me - I run the @worksonarm program at Packet and we have resources specifically to provide CI/CD infrastructure to open source projects for that platform. Specifically we have access to 64-bit Arm machines with 32 or more cores that greatly speed up build cycles for any builds that are even the least bit parallel.

**Comment by MyraBaba** [comment] 2019-02-06 09:49
Hi,

Can we compile or use your binary in the NanoPc T4 which is Rockchip 3399 [http://wiki.friendlyarm.com/wiki/index.php/NanoPC-T4]
(http://wiki.friendlyarm.com/wiki/index.php/NanoPC-T4) 

what is your suggestion. I have plenty time today and try to compile..  

is berryconda can work ?

**Comment by stuartarchibald** [comment] 2019-02-06 10:45
@MyraBaba Given the cost of trying is quite low, perhaps try with `berryconda` first (but be aware that it's all 32 bit, so you may need a 32 bit OS or the 32 bit runtime libraries), and if that doesn't work try `jetconda`. If neither work, it'd be interesting to know what happens and what's on your system!

If you want to build from source, then `llvmlite` needs building first, this requires a specific build of LLVM, instructions are here: http://llvmlite.pydata.org/en/latest/admin-guide/install.html#building-manually

**Comment by MyraBaba** [comment] 2019-02-06 11:02
Starting to compile llvmlite now.. Let you know the situation 

Best

**Comment by MyraBaba** [comment] 2019-02-06 13:40
Update...

I successfully compiled numba . as everybody said yes there is a pain in the ....:)

`>>> import numba
>>> numba.__version__
'0.43.0dev0+271.g865b87a97'`


now compiling mxnet..

**Comment by vielmetti** [comment] 2019-06-20 02:16
Hi @MyraBaba - is there an update on your progress?

**Comment by pwuertz** [comment] 2020-04-24 13:00
Just tried Ubuntu 20.04 (64bit) on a Raspberry4.
Numba 0.48 is in the 20.04 repository and works like a charm.

**Comment by gmarkall** [comment] 2021-02-08 14:25
Closing the issue as the original issue appears to be resolved, and no further updates have been provided in quite some time.

**Closed by gmarkall** 2021-02-08 14:25 UTC
Labels: ISA: ARM, feature_request
