### ISSUE TITLE
Invalid use of Function(<built-in function setitem>)

### ISSUE THREAD

**Issue by sw14928** [numba/numba#5112] opened 2020-01-20 15:20 UTC
I am not sure what my error means - can anyone help?

Below is the code that I am trying to run:

```python
@njit
def kaczmarz(finalArray,responseArray):
    #KaczResult =  np.zeros_like(finalArray)#convolve(sourceOntable, response, method = 'direct', mode='same')
    solution = np.zeros_like(finalArray)
    #solution = finalArray
    #remnants =  np.zeros_like(finalArray)
    widthFinalArray = finalArray.shape[0]
    depthFinalArray = finalArray.shape[1]
    widthRes = responseArray.shape[0]
    depthRes = responseArray.shape[1]
    xRad = int(widthRes/ 2)
    yRad = int(depthRes/ 2)
    #usefulResponseIndicies = response>0
    rawValues = widthFinalArray * depthFinalArray * finalArray.shape[2]
    damping = 0.01
    for i in range(5000):
        print(i)
        update = np.zeros_like(solution)
        count = 0
        for x in range(finalArray.shape[0]):
            for y in range(finalArray.shape[1]):
                #randomPoint = np.random.randint(rawValues)
                #coords =  np.unravel_index(randomPoint, finalArray.shape)
                #x = coords[0]
                #y = coords[1]
                
                x = np.random.randint(finalArray.shape[0])
                y = np.random.randint(finalArray.shape[1])
                #print(x,y,z)
                
                x1 = x-xRad
                if x1 < 0: x1 = 0
                if x1 > widthFinalArray: x1 = widthFinalArray
        
                x2 = xRad+x
                if x2 < 0: x2 = 0
                if x2 > widthFinalArray: x2 = widthFinalArray
        
                x3 = xRad-x
                if x3 < 0: x3 = 0
                if x3 > widthRes: x3 = widthRes
        
                x4 = xRad-x+widthFinalArray
                if x4 < 0: x4 = 0
                if x4 > widthRes: x4 = widthRes
        
                y1 = y-yRad
                if y1 < 0: y1 = 0
                if y1 > depthFinalArray: y1 = depthFinalArray
        
                y2 = yRad+y
                if y2 < 0: y2 = 0
                if y2 > depthFinalArray: y2 = depthFinalArray
        
                y3 = yRad-y
                if y3 < 0: y3 = 0
                if y3 > depthRes: y3 = depthRes
        
                y4 = yRad-y+depthFinalArray
                if y4 < 0: y4 = 0
                if y4 > depthRes: y4 = depthRes
        
                subSection = solution[x1:x2+1, y1:y2,0]
                #shape = np.shape(subSection)
                #test = np.sum(subSection)
        
                subResponse = responseArray[x3:x4,y3:y4]
                KaczResult = np.sum(subResponse * subSection)
                remnant = finalArray[x,y,0]-KaczResult
                
                subUpdate = subResponse*remnant

                #print(np.max(subResponse))
                #print(np.max(subResponse))
                update[x1:x2+1, y1:y2,0] += subUpdate
                count += 1
                
                solution[solution < 0] = 0
        solution += damping*update/count

    return solution
```

**Comment by esc** [comment] 2020-01-20 15:34
@sw14928 thanks for asking about this on the Numba issue tracker. I have updated your comment to include syntax highlighting for legibility. For future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by sw14928** [comment] 2020-01-20 15:35
Hi esc! Thank you for that tip - I'll be sure to do that in future. Best regards,
Sam

**Comment by esc** [comment] 2020-01-20 15:36
@sw14928 In order to diagnose this, would it be possible to  include a snippet to create the `finalArray` and `responseArray`? This would allow us to reproduce your issue locally.

**Comment by sw14928** [comment] 2020-01-20 15:38
@esc they are just arrays filled with numbers - two random arrays of size (60,60) should do it

**Comment by esc** [comment] 2020-01-20 15:51
@sw14928 I tried using:

```
a = np.ones((60,60))
b = np.ones((60,60))
kaczmarz(a,b)
```

But then I get:

```
💥 zsh» python foo/foo98.py
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/errors.py", line 717, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 379, in __call__
    value=ty, index=self.index,
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 316, in resolve_static_getitem
    return self.resolve_function_type("static_getitem", args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 212, in resolve_function_type
    res = self._resolve_builtin_function_type(func, args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 229, in _resolve_builtin_function_type
    res = defn.apply(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 245, in apply
    sig = generic(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/builtins.py", line 626, in generic
    ret = tup.types[idx]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 148, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 388, in __call__
    self.fallback(typeinfer)
  File "/Users/vhaenel/miniconda3/envs/numba_3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/vhaenel/git/numba/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 717, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 379, in __call__
    value=ty, index=self.index,
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 316, in resolve_static_getitem
    return self.resolve_function_type("static_getitem", args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 212, in resolve_function_type
    res = self._resolve_builtin_function_type(func, args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 229, in _resolve_builtin_function_type
    res = defn.apply(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 245, in apply
    sig = generic(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/builtins.py", line 626, in generic
    ret = tup.types[idx]
numba.errors.InternalError: tuple index out of range
[1] During: typing of static-get-item at foo/foo98.py (19)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo/foo98.py", line 91, in <module>
    kaczmarz(a,b)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 342, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 81, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 95, in run_pass
    raise_errors=self._raise_errors)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 67, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 985, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.StaticGetItemConstraint object at 0x617839610>.
tuple index out of range
[1] During: typing of static-get-item at foo/foo98.py (19)
Enable logging at debug level for details.

File "foo/foo98.py", line 19:
def kaczmarz(finalArray,responseArray):
    <source elided>
    #usefulResponseIndicies = response>0
    rawValues = widthFinalArray * depthFinalArray * finalArray.shape[2]
    ^
```

**Comment by sw14928** [comment] 2020-01-20 15:57
hmmm, I just tried it inputting "ones" too and obtained the same result. Perhaps there is a deeper problem at large...

Do you think everything in the function should be accepted by njit?

Best regards,
Sam

**Comment by sw14928** [comment] 2020-01-20 15:58
'''
def kaczmarz(finalArray,responseArray):
    #KaczResult =  np.zeros_like(finalArray)#convolve(sourceOntable, response, method = 'direct', mode='same')
    solution = np.zeros_like(finalArray)
    #solution = finalArray
    #remnants =  np.zeros_like(finalArray)
    widthFinalArray = finalArray.shape[0]
    depthFinalArray = finalArray.shape[1]
    widthRes = responseArray.shape[0]
    depthRes = responseArray.shape[1]
    xRad = int(widthRes/ 2)
    yRad = int(depthRes/ 2)
    #usefulResponseIndicies = response>0
    rawValues = widthFinalArray * depthFinalArray
    damping = 0.01
    for i in range(5000):
        print(i)
        update = np.zeros_like(solution)
        count = 0
        for x in range(finalArray.shape[0]):
            for y in range(finalArray.shape[1]):
                #randomPoint = np.random.randint(rawValues)
                #coords =  np.unravel_index(randomPoint, finalArray.shape)
                #x = coords[0]
                #y = coords[1]
                
                x = np.random.randint(finalArray.shape[0])
                y = np.random.randint(finalArray.shape[1])
                #print(x,y,z)
                
                x1 = x-xRad
                if x1 < 0: x1 = 0
                if x1 > widthFinalArray: x1 = widthFinalArray
        
                x2 = xRad+x
                if x2 < 0: x2 = 0
                if x2 > widthFinalArray: x2 = widthFinalArray
        
                x3 = xRad-x
                if x3 < 0: x3 = 0
                if x3 > widthRes: x3 = widthRes
        
                x4 = xRad-x+widthFinalArray
                if x4 < 0: x4 = 0
                if x4 > widthRes: x4 = widthRes
        
                y1 = y-yRad
                if y1 < 0: y1 = 0
                if y1 > depthFinalArray: y1 = depthFinalArray
        
                y2 = yRad+y
                if y2 < 0: y2 = 0
                if y2 > depthFinalArray: y2 = depthFinalArray
        
                y3 = yRad-y
                if y3 < 0: y3 = 0
                if y3 > depthRes: y3 = depthRes
        
                y4 = yRad-y+depthFinalArray
                if y4 < 0: y4 = 0
                if y4 > depthRes: y4 = depthRes
        
                subSection = solution[x1:x2, y1:y2]
                #shape = np.shape(subSection)
                #test = np.sum(subSection)
        
                subResponse = responseArray[x3:x4,y3:y4]
                KaczResult = np.sum(subResponse * subSection)
                remnant = finalArray[x,y]-KaczResult
                
                subUpdate = subResponse*remnant

                #print(np.max(subResponse))
                #print(np.max(subResponse))
                update[x1:x2, y1:y2] += subUpdate
                count += 1
                
                solution[solution < 0] = 0
        solution += damping*update/count

    return solution
'''

**Comment by sw14928** [comment] 2020-01-20 15:59
^^This should work better - sorry for that!

**Comment by esc** [comment] 2020-01-20 17:34
@sw14928 thanks for updating the issue, for reference  you need to use backticks, not  apostrophes to format code in github issue.I.e ` not '.

**Comment by esc** [comment] 2020-01-20 17:44
I have narrowed this down to the following minimum reproducer:

```
from numba import njit
import numpy as np


@njit
def foo(x):
    x[x < 0] = 0


oned = np.ones(60)
twod = np.ones((60,60))
foo(oned)
print("one-d O.K.")
foo(twod)
print("two-d O.K.")
```

And so the current hypothesis is that the statement `x[x < 0] = 0` doesn't work if x has dimensionality larger than one.

**Comment by esc** [comment] 2020-01-20 17:46
It appears this may be a duplicate of https://github.com/numba/numba/issues/4225

**Comment by stuartarchibald** [comment] 2020-01-20 18:22
@esc thanks for the debug, reason seems spot on https://github.com/numba/numba/blob/40fb2d06859a782db9463ac6d7eae8405eb6a81d/numba/typing/arraydecl.py#L60-L62

**Comment by esc** [comment] 2020-01-20 21:15
@stuartarchibald Not sure that is the right place. I don't see the `TypeError` in the raised exception.

**Closed as completed** 2021-12-16 15:52 UTC
Labels: duplicate
