### ISSUE TITLE
pip>=19.3 does not install 0.48 wheel on py38/Windows

### ISSUE THREAD

**Issue by asodeur** [numba/numba#5160] opened 2020-01-29 17:42 UTC
pip refuses to install the Numba 0.48.0 wheels from PyPi on py38/Windows b/c the 'm' seems to be dropped from the ABI specifier (see [here](https://bugs.python.org/issue36707)), ie the wheel should have been named `numba-0.48.0-cp38-cp38-win_amd64.whl`. However, this name seems to cause [trouble](https://github.com/pypa/pip/issues/6885) with some pip 19.2 versions

**Comment by seibert** [comment] 2020-01-29 17:48
@sklam: Can we fix before announcing 0.48?

**Comment by sklam** [comment] 2020-01-29 20:18
posted new wheels.

turns out the bad wheels are caused by accidentally using old `wheel==0.30`

**Comment by sklam** [comment] 2020-01-29 20:19
Manually verified with `pip install`. closing..

**Closed by sklam** 2020-01-29 20:19 UTC
Labels: wheels
