### ISSUE TITLE
Instantiating a jitclass with unicode attributes fails

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#5671] opened 2020-05-05 11:53 UTC
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

numba 0.49.0

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

# Reproducer

Below, see two classes, A and B with an  ASCII and Unicode attribute respectively. Instantiating an object of B fails:

```python
import numpy as np
import numba
from numba.experimental import jitclass
from numba import typeof

@jitclass([('dphi', typeof(np.float64(0)))])
class A(object):
    def __init__(self, v):
        self.dphi = numba.float64(v)


@jitclass([('𝞓𝞇', typeof(np.float64(0)))])
class B(object):
    def __init__(self, v):
        self.𝞓𝞇 = numba.float64(v)

a = A(0)
b = B(0)
```

This produces the following traceback

```traceback
$ python test_unicode_jitclass.py 
Traceback (most recent call last):
  File "test_unicode_jitclass.py", line 18, in <module>
    b = B(0)
  File "/home/sperkins/venv/numba/local/lib/python3.6/site-packages/numba/experimental/jitclass/base.py", line 122, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/home/sperkins/venv/numba/local/lib/python3.6/site-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/sperkins/venv/numba/local/lib/python3.6/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/sperkins/venv/numba/local/lib/python3.6/site-packages/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot resolve setattr: (instance.jitclass.B#7f4560cb0668<𝞓𝞇:float64>).Δψ = float64

File "test_unicode_jitclass.py", line 15:
    def __init__(self, v):
        self.𝞓𝞇 = numba.float64(v)
        ^

[1] During: typing of set attribute 'Δψ' at test_unicode_jitclass.py (15)

File "test_unicode_jitclass.py", line 15:
    def __init__(self, v):
        self.𝞓𝞇 = numba.float64(v)
        ^

[1] During: resolving callee type: jitclass.B#7f4560cb0668<𝞓𝞇:float64>
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: jitclass.B#7f4560cb0668<𝞓𝞇:float64>
[4] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

```

**Comment by sjperkins** [comment] 2020-05-05 12:03
Fixed the reproducer and traceback.

**Comment by stuartarchibald** [comment] 2020-05-05 12:13
Thanks for the report, pretty sure this is a duplicate of https://github.com/numba/numba/issues/4816

**Comment by stuartarchibald** [comment] 2020-05-05 12:21
This:
```python
import numpy as np
import numba
from numba.experimental import jitclass
from numba import typeof

@jitclass([('dphi', typeof(np.float64(0)))])
class A(object):
    def __init__(self, v):
        self.dphi = numba.float64(v)


special_chars = '𝞓𝞇'

@jitclass([(special_chars, typeof(np.float64(0)))])
class B(object):
    def __init__(self, v):
        self.𝞓𝞇 = numba.float64(v)

a = A(0)
try:
    b = B(0)
except Exception:
    print("failed")

cps = [ord(x) for x in special_chars]

import unicodedata
nrml = [ord(unicodedata.normalize("NFKC", chr(x))) for x in cps]

print(cps)
print(nrml)

normalize_specials = [chr(x) for x in nrml]
print(normalize_specials)

@jitclass([('Δψ', typeof(np.float64(0)))])
class C(object):
    def __init__(self, v):
        self.Δψ = numba.float64(v)

c = C(0)
```
does this:
```
failed
[120723, 120711]
[916, 968]
['Δ', 'ψ']
```
so it's the same problem and same solution as in #4816, i.e. use normalised character forms.

**Closed by stuartarchibald** 2020-05-05 12:21 UTC

**Comment by sjperkins** [comment] 2020-05-05 12:26
Thanks for the analysis @stuartarchibald

**Comment by stuartarchibald** [comment] 2020-05-05 12:55
@sjperkins no problem, #4816 was sufficiently strange that it stuck in memory, I presume you can work around the issue as demonstrated in the above example?

**Comment by sjperkins** [comment] 2020-05-05 13:03
Yes thanks, I should've said that I don't regard this as a priority issue at all.

I liked the bold greek characters because they stand out, but the normalised characters work perfectly well!
