### ISSUE TITLE
Test failure with Numba master and Numpy 1.19

### ISSUE THREAD

**Issue by esc** [numba/numba#6069] opened 2020-08-04 06:27 UTC
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Observing the following test case failure with Numba `master` @ `0.51.0dev0-458-g6bb2930025` and Numpy 1.19 installed via `conda`:

```
zsh» python -m numba.runtests numba.tests.test_np_functions.TestNPFunctions.test_ediff1d_edge_cases
...
======================================================================
ERROR: test_ediff1d_edge_cases (numba.tests.test_np_functions.TestNPFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/tests/test_np_functions.py", line 2080, in test_ediff1d_edge_cases
    _check_raises_type_error(params, 'to_begin')
  File "/Users/vhaenel/git/numba/numba/tests/test_np_functions.py", line 2047, in _check_raises_type_error
    pyfunc(**params)
  File "/Users/vhaenel/git/numba/numba/tests/test_np_functions.py", line 233, in ediff1d
    return np.ediff1d(ary, to_end, to_begin)
  File "<__array_function__ internals>", line 5, in ediff1d
  File "/Users/vhaenel/miniconda3/envs/numba_3.8/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 107, in ediff1d
    raise TypeError("dtype of `to_end` must be compatible "
TypeError: dtype of `to_end` must be compatible with input `ary` under the `same_kind` rule.

----------------------------------------------------------------------
Ran 1 test in 6.313s

FAILED (errors=1)
```

**Comment by stuartarchibald** [comment] 2020-08-04 08:27
Duplicate of https://github.com/numba/numba/issues/5929, closing.

**Closed by stuartarchibald** 2020-08-04 08:27 UTC
Labels: needtriage, numpy
