### ISSUE TITLE
Some threads can apparently pass though syncthreads() before all threads arrive there

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1626] opened 2016-01-14 15:18 UTC
Sorry for the long reproducer - I was having trouble shrinking it any further. Running the following:

``` python
from numba import cuda, float64
import numpy as np

@cuda.jit()
def f(a):
    sh_arr = cuda.shared.array((1, 3), dtype=float64)

    x = cuda.threadIdx.x
    y = cuda.threadIdx.y

    if y > 3:
        return

    if 1 == 3:
        next_hs = y
    else:
        next_hs = (0, 2, 3)[y]

    if next_hs > 0:
        assets_value = a[0]

    n = a.size
    if assets_value < a[0]:
        pass
    elif assets_value < a[n - 1]:
        for i in range(1, n):
            pass

    sh_arr[x, y] = -999.0

    cuda.syncthreads()

    if (x == 0 and y == 0):
        for j in range(1):
            for k in range(3):
                print(sh_arr[j, k])


a = np.asarray([0.0, 0.0, 0.0])
f[(1, (1,3))](a)
```

results in the following output (on my GTX 970 and @stuartarchibald's 750Ti):

```
-999.000000
0.000000
0.000000
```

whereas I would have expected:

```
-999.000000
-999.000000
-999.000000
```

It seems as though thread 0 manages to get past the `syncthreads()` call before threads 2 and 3 arrive. If `print(7)` is added just before the call to `syncthreads()`, the output looks something like

```
7
-999.000000
0.000000
0.000000
77

```

This is a strange thing to observe (and hard to believe it is happening) because the three threads are all in the same warp - they "should" be executing in lock-step.

**Comment by stuartarchibald** [comment] 2016-01-14 15:27
The `0.000000` in the last two elements of output where there ought be `-999.000000` is random junk (locally `0.007813` and  `0` seem to be favourites). If the `sh_arr` elements are set to a fixed value immediately after allocation then it is those that are reported in the place of the `0.000000`/junk. I've also tried 100 runs of the test in case there was an easily spotted race, at no point does it produce the right answer.

**Comment by gmarkall** [comment] 2016-01-27 12:03
This issue seems to disappear with Numba master and llvmlite 0.9.0.dev. There are significant differences in the generated PTX, so it's not very easy to tell what the change was.

**Comment by seibert** [comment] 2017-11-03 16:03
Closing since we probably can't reproduce this anymore.

**Closed by seibert** 2017-11-03 16:03 UTC
