### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [numba/numba#6746] opened 2021-02-23 10:41 UTC
[numba-build-error-log.txt](https://github.com/numba/numba/files/6028339/numba-build-error-log.txt)

**Comment by esc** [comment] 2021-02-23 11:24
@LutzWeischerFujitsu thank you for reporting this. Looking at the error log:

```
Processing dependencies for numba==0.54.0.dev0+35.g3fd158f79
Searching for llvmlite<0.37,>=0.36.0.dev0
Reading https://pypi.org/simple/llvmlite/
Download error on https://pypi.org/simple/llvmlite/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'llvmlite' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for llvmlite<0.37,>=0.36.0.dev0
error: Could not find suitable distribution for Requirement.parse('llvmlite<0.37,>=0.36.0.dev0')
```

This suggests a temporary network failure. Please try again and check if the issue you encounter is reproducible.

**Comment by esc** [comment] 2021-02-23 12:15
@LutzWeischerFujitsu having another look at your error log, I think you may have ended up in the following situation

a) Attempted to install from a git clone using `sudo python3 setup.py install --verbose`
b) This compiles fine but then `llvmlite` can't be installed because the version constraint `llvmlite<0.37,>=0.36.0.dev0` can not be satisfied.

This again is because the the imminent llvmlite release -- 0.36 -- is still in the release candidate phase and a final version is not yet available from PyPi. We can consider this to be broken on `master`. The issue will likely rectify itself as soon as the correct version is available from PyPi in a few weeks from now (at least for `x86_*`).

However, since you are on `aarch64`, I can forsee that you will run into further issues when using `pip` to install `llvmlite`. This is because llvmlite does not yet ship wheels for `aarch64` and so there is no way to install an llvmlite binary. Basically you will receive a different error message. We plan to upgrade to support `aarch64` wheels for the 0.37 release in a few months from now. Until then the recommended workaround is to use `conda` to install Numba and llvmlite.

Hope this helps?

PS: if you need to build Numba from a git checkout, you can satisfy the dependencies in a conda environment before doing so. There is also the following makefile I use personally for building from `master`, if it helps: https://github.com/esc/numba-dev-files/blob/master/Makefile

**Comment by LutzWeischerFujitsu** [comment] 2021-02-24 12:46
It seems not to be a temporary network failure, it looks reproducible. 
conda does not work do to anaconda repo not yet supporting AArch64. 
Hope to get noted when this will work via the standard process, i.e. also for AArch64 (A64FX).

**Comment by esc** [comment] 2021-02-24 13:55
@LutzWeischerFujitsu perhaps miniforge is an option? https://github.com/conda-forge/miniforge

**Comment by esc** [comment] 2021-02-24 13:57
@LutzWeischerFujitsu the issue to watch is: https://github.com/numba/llvmlite/issues/665 -- and I will close this one for now.

**Closed** 2021-03-01 15:32 UTC
Labels: no action required
