### ISSUE TITLE
min/max on typed lists extremely slower than on python lists

### ISSUE THREAD

**Issue by ma-sadeghi** [numba/numba#4928] opened 2019-12-06 04:48 UTC
# Description
Calling `min`/`max` on Numba's typed lists is extremely slower (>10x) compared to when operating on native Python lists.
# How to reporduce
```
import numpy as np
from numba.typed import List
x = np.random.rand(10000).tolist()
xt = List()
xt.extend(x)
```
```
%timeit min(xt)
22.6 ms ± 272 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
```
%timeit min(x)
166 µs ± 5.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by esc** [comment] 2019-12-06 09:10
@ma-sadeghi thanks for reporting this, I presume this is a result of having to unbox the elements of the typed list into Python objects during min and max.

**Comment by stuartarchibald** [comment] 2019-12-06 09:10
Thanks for the report. I think this is expected behaviour, the `typed.List` uses native memory storage and accessing that through Python calls (as would happen in CPython's `min`) requires pulling the data out of the storage and converting it to a CPython internal representation for use. If however one does a `min` call inside a `@numba.jit` compiled function following the same pattern, the native memory storage can be used directly and the performance is much better.
```pycon
In [10]: %paste
import numpy as np
from numba.typed import List
x = np.random.rand(10000).tolist()
xt = List()
xt.extend(x)

## -- End pasted text --

In [11]: %timeit min(xt)
34.6 ms ± 327 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]: %timeit min(x)
221 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [13]: %timeit min(xt)
34.1 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [14]: from numba import njit

In [15]: @njit
    ...: def jmin(x):
    ...:     return min(x)
    ...:

In [16]: %timeit jmin(xt)
46.1 µs ± 8.48 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by esc** [comment] 2019-12-06 09:24
I was looking for `__min__` and `__max__` contracts, but they don't seem to exist?

**Comment by esc** [comment] 2019-12-06 13:12
After some more thought, I believe we could implement `min()` and `max()` as methods on the `List` class, would that help.

**Comment by ma-sadeghi** [comment] 2019-12-06 15:14
@stuartarchibald Thank you for looking into this, actually I'm using `min`/`max` inside a Numba jitted function, so probably I'm not being affected. @esc Thank you, looking forward to it.

**Comment by stuartarchibald** [comment] 2019-12-09 15:46
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-12-09 15:46 UTC
Labels: performance
