### ISSUE TITLE
TypeError  vectorized assignment in ´prange` loop with if statements

### ISSUE THREAD

**Issue by JeppeDruedahl** [numba/numba#5663] opened 2020-05-03 23:45 UTC
## Reporting a bug

- [X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

There seems to be a bug related to vectorized assignment in ´prange` loop with if statements.

```
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def f(a,b,compute_a=True,compute_b=True):
    for i in prange(10):
        if compute_a:
            a[i,:] = 1
        if compute_b:
            b[i,:] = 1     

a = np.zeros((10,10))
b = np.zeros((10,10))  
f(a,b)
```

Produces the error below. 

The error disappears in any of these cases:

1. The if statements are removed
2. The assignment is to a single elementer rather than a vector
3. parallel=True is dropped

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\numba\core\errors.py in new_error_context(fmt_, *args, **kwargs)
    800     try:
--> 801         yield
    802     except NumbaError as e:

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_block(self, block)
    266                                    loc=self.loc, errcls_=defaulterrcls):
--> 267                 self.lower_inst(inst)
    268         self.post_block(block)

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_inst(self, inst)
    479                 if isinstance(inst, _class):
--> 480                     func(self, inst)
    481                     return

~\Anaconda3\lib\site-packages\numba\parfors\parfor_lowering.py in _lower_parfor_parallel(lowerer, parfor)
    239             lowerer, parfor, typemap, typingctx, targetctx, flags, {},
--> 240             bool(alias_map), index_var_typ, parfor.races)
    241     finally:

~\Anaconda3\lib\site-packages\numba\parfors\parfor_lowering.py in _create_gufunc_for_parfor_body(lowerer, parfor, typemap, typingctx, targetctx, flags, locals, has_aliases, index_var_typ, races)
   1326         flags,
-> 1327         locals)
   1328 

~\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_ir(typingctx, targetctx, func_ir, args, return_type, flags, locals, lifted, lifted_from, is_lifted_loop, library, pipeline_class)
    631         return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
--> 632                                    lifted_from=lifted_from)
    633 

~\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_ir(self, func_ir, lifted, lifted_from)
    348         FixupArgs().run_pass(self.state)
--> 349         return self._compile_ir()
    350 

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_ir(self)
    407         assert self.state.func_ir is not None
--> 408         return self._compile_core()
    409 

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    380                 if is_final_pipeline:
--> 381                     raise e
    382         else:

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    371             try:
--> 372                 pm.run(self.state)
    373                 if self.state.cr is not None:

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    340                 patched_exception = self._patch_error(msg, e)
--> 341                 raise patched_exception
    342 

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    331                 if isinstance(pass_inst, CompilerPass):
--> 332                     self._runPass(idx, pass_inst, state)
    333                 else:

~\Anaconda3\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    290         with SimpleTimer() as pass_time:
--> 291             mutated |= check(pss.run_pass, internal_state)
    292         with SimpleTimer() as finalize_time:

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in check(func, compiler_state)
    263         def check(func, compiler_state):
--> 264             mangled = func(compiler_state)
    265             if mangled not in (True, False):

~\Anaconda3\lib\site-packages\numba\core\typed_passes.py in run_pass(self, state)
    287                                          state.parfor_diagnostics)
--> 288         parfor_pass.run()
    289 

~\Anaconda3\lib\site-packages\numba\parfors\parfor.py in run(self)
   2589         with Parfors when possible and optimize the IR."""
-> 2590         self._pre_run()
   2591         # run stencil translation to parfor

~\Anaconda3\lib\site-packages\numba\parfors\parfor.py in _pre_run(self)
   2584         # run array analysis, a pre-requisite for parfor translation
-> 2585         self.array_analysis.run(self.func_ir.blocks)
   2586 

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in run(self, blocks, equiv_set)
   1106         # Traverse blocks in topological order
-> 1107         self._run_on_blocks(topo_order, blocks, cfg, init_equiv_set)
   1108 

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in _run_on_blocks(self, topo_order, blocks, cfg, init_equiv_set)
   1127             pending_transforms = self._determine_transform(
-> 1128                 cfg, block, label, scope, init_equiv_set
   1129             )

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in _determine_transform(self, cfg, block, label, scope, init_equiv_set)
   1208             pre, post = self._analyze_inst(
-> 1209                 label, scope, equiv_set, inst, redefined
   1210             )

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in _analyze_inst(self, label, scope, equiv_set, inst, redefined)
   1325             if needs_define:
-> 1326                 equiv_set.define(lhs, redefined, self.func_ir, typ)
   1327         elif isinstance(inst, ir.StaticSetItem) or isinstance(

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in define(self, var, redefined, func_ir, typ)
    920         ):
--> 921             value = guard(self._get_or_set_rel, name, func_ir)
    922             # turn constant definition into equivalence

~\Anaconda3\lib\site-packages\numba\core\ir_utils.py in guard(func, *args, **kwargs)
   1449     try:
-> 1450         return func(*args, **kwargs)
   1451     except GuardException:

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in _get_or_set_rel(self, name, func_ir)
    870                     elif expr.fn == operator.sub:
--> 871                         value = minus(lhs, rhs)
    872             elif isinstance(expr, ir.Const) and isinstance(expr.value, int):

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in minus(x, y)
    833                 if isinstance(y, int):
--> 834                     return plus(x, -y)
    835                 elif (

~\Anaconda3\lib\site-packages\numba\parfors\array_analysis.py in plus(x, y)
    825                 else:
--> 826                     (var, offset) = x
    827                     if y_is_const:

TypeError: Failed in nopython mode pipeline (step: convert to parfors)
cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-18-603cc0fe1892> in <module>
     12 a = np.zeros((10,10))
     13 b = np.zeros((10,10))
---> 14 f(a,b)

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    418                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    419             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 420             raise e
    421 
    422     def inspect_llvm(self, signature=None):

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    351                 argtypes.append(self.typeof_pyval(a))
    352         try:
--> 353             return self.compile(tuple(argtypes))
    354         except errors.ForceLiteralArg as e:
    355             # Received request for compiler re-entry with the list of arguments

~\Anaconda3\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in compile(self, sig)
    792             self._cache_misses[sig] += 1
    793             try:
--> 794                 cres = self._compiler.compile(args, return_type)
    795             except errors.ForceLiteralArg as e:
    796                 def folded(args, kws):

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in compile(self, args, return_type)
     75 
     76     def compile(self, args, return_type):
---> 77         status, retval = self._compile_cached(args, return_type)
     78         if status:
     79             return retval

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_cached(self, args, return_type)
     89 
     90         try:
---> 91             retval = self._compile_core(args, return_type)
     92         except errors.TypingError as e:
     93             self._failed_cache[key] = e

~\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_core(self, args, return_type)
    107                                       args=args, return_type=return_type,
    108                                       flags=flags, locals=self.locals,
--> 109                                       pipeline_class=self.pipeline_class)
    110         # Check typing error if object mode is used
    111         if cres.typing_error is not None and not flags.enable_pyobject:

~\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    566     pipeline = pipeline_class(typingctx, targetctx, library,
    567                               args, return_type, flags, locals)
--> 568     return pipeline.compile_extra(func)
    569 
    570 

~\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_extra(self, func)
    337         self.state.lifted = ()
    338         self.state.lifted_from = None
--> 339         return self._compile_bytecode()
    340 
    341     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_bytecode(self)
    399         """
    400         assert self.state.func_ir is None
--> 401         return self._compile_core()
    402 
    403     def _compile_ir(self):

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    379                 self.state.status.fail_reason = e
    380                 if is_final_pipeline:
--> 381                     raise e
    382         else:
    383             raise CompilerError("All available pipelines exhausted")

~\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    370             res = None
    371             try:
--> 372                 pm.run(self.state)
    373                 if self.state.cr is not None:
    374                     break

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    339                     (self.pipeline_name, pass_desc)
    340                 patched_exception = self._patch_error(msg, e)
--> 341                 raise patched_exception
    342 
    343     def dependency_analysis(self):

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    330                 pass_inst = _pass_registry.get(pss).pass_inst
    331                 if isinstance(pass_inst, CompilerPass):
--> 332                     self._runPass(idx, pass_inst, state)
    333                 else:
    334                     raise BaseException("Legacy pass in use")

~\Anaconda3\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    289             mutated |= check(pss.run_initialization, internal_state)
    290         with SimpleTimer() as pass_time:
--> 291             mutated |= check(pss.run_pass, internal_state)
    292         with SimpleTimer() as finalize_time:
    293             mutated |= check(pss.run_finalizer, internal_state)

~\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in check(func, compiler_state)
    262 
    263         def check(func, compiler_state):
--> 264             mangled = func(compiler_state)
    265             if mangled not in (True, False):
    266                 msg = ("CompilerPass implementations should return True/False. "

~\Anaconda3\lib\site-packages\numba\core\typed_passes.py in run_pass(self, state)
    440 
    441         # TODO: Pull this out into the pipeline
--> 442         NativeLowering().run_pass(state)
    443         lowered = state['cr']
    444         signature = typing.signature(state.return_type, *state.args)

~\Anaconda3\lib\site-packages\numba\core\typed_passes.py in run_pass(self, state)
    368                 lower = lowering.Lower(targetctx, library, fndesc, interp,
    369                                        metadata=metadata)
--> 370                 lower.lower()
    371                 if not flags.no_cpython_wrapper:
    372                     lower.create_cpython_wrapper(flags.release_gil)

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower(self)
    177         if self.generator_info is None:
    178             self.genlower = None
--> 179             self.lower_normal_function(self.fndesc)
    180         else:
    181             self.genlower = self.GeneratorLower(self)

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_normal_function(self, fndesc)
    225         # Init argument values
    226         self.extract_function_arguments()
--> 227         entry_block_tail = self.lower_function_body()
    228 
    229         # Close tail of entry block

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_function_body(self)
    251             bb = self.blkmap[offset]
    252             self.builder.position_at_end(bb)
--> 253             self.lower_block(block)
    254         self.post_lower()
    255         return entry_block_tail

~\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_block(self, block)
    265             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    266                                    loc=self.loc, errcls_=defaulterrcls):
--> 267                 self.lower_inst(inst)
    268         self.post_block(block)
    269 

~\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~\Anaconda3\lib\site-packages\numba\core\errors.py in new_error_context(fmt_, *args, **kwargs)
    806         newerr = errcls(e).add_context(_format_msg(fmt_, args, kwargs))
    807         tb = sys.exc_info()[2] if numba.core.config.FULL_TRACEBACKS else None
--> 808         reraise(type(newerr), newerr, tb)
    809 
    810 

~\Anaconda3\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     78     if value.__traceback__ is not tb:
     79         raise value.with_traceback(tb)
---> 80     raise value
     81 
     82 

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: convert to parfors)
cannot unpack non-iterable NoneType object

File "<ipython-input-18-603cc0fe1892>", line 6:
def f(a,b,compute_a=True,compute_b=True):
    for i in prange(10):
    ^

[1] During: lowering "id=43[LoopNest(index_variable = parfor_index.2014, range = (0, $const6.1, 1))]{36: <ir.Block at <ipython-input-18-603cc0fe1892> (9)>, 40: <ir.Block at <ipython-input-18-603cc0fe1892> (10)>, 14: <ir.Block at <ipython-input-18-603cc0fe1892> (6)>, 20: <ir.Block at <ipython-input-18-603cc0fe1892> (8)>, 58: <ir.Block at <ipython-input-18-603cc0fe1892> (6)>}Var(parfor_index.2014, <ipython-input-18-603cc0fe1892>:6)" at <ipython-input-18-603cc0fe1892> (6)
```

**Comment by esc** [comment] 2020-05-04 08:24
I can reproduce this on current master `0.50.0dev0-179-g86e600d0ec` and I suspect this is an issue with the parallel accelerator. @DrTodd13 perhaps you could have a look?

**Comment by stuartarchibald** [comment] 2020-05-04 10:17
Duplicate of https://github.com/numba/numba/issues/5601

**Comment by esc** [comment] 2020-05-04 12:20
I'll close now because it's a dup.

**Closed by esc** 2020-05-04 12:20 UTC
Labels: ParallelAccelerator, bug, duplicate
