### ISSUE TITLE
numba.typed.typeddict.Dict.get returns the default even though the key is present 

### ISSUE THREAD

**Issue by MarcMassar** [numba/numba#7908] opened 2022-03-14 20:11 UTC
With some specific key dtypes, Dict.get returns the default value even when the key is present. This has been tested with numba 0.55.1

To reproduce:

```
import numba

numba_dict = numba.typed.typeddict.Dict.empty(
    key_type=numba.types.Tuple([numba.types.uint32, numba.types.uint32]),
    value_type=numba.types.int64)

numba_dict[(1,1)] = 12345
assert numba_dict.get((1,1), 1) == numba_dict[(1,1)]
```

The error depends on the size of the ints in the key, not on the unsigned aspect. It disappears with e.g. `numba.types.Tuple([numba.types.uint32, numba.types.uint64])`

**Comment by guilhermeleobas** [comment] 2022-03-15 18:33
Hi @MarcMassar, thanks for the report. I can confirm this is a bug in Numba. 

```python
import numba
from numba.core.types import Tuple, int64, uint32
from numba.typed.typeddict import Dict

d = Dict.empty(
    key_type=Tuple([uint32, uint32]),
    value_type=int64)

d[(1,1)] = 12345
print(d[(1, 1)])  # print "12345"
print(d.get((1, 1)))  # print None
```

I guess the issue is because `dict.get` is using the non-casted `key` as the second argument to `_dict_lookup`. Whereas `operator.getitem` uses the casted one.
https://github.com/numba/numba/blob/2e825b000e609e090005f8fb3d567999f1f1940c/numba/typed/dictobject.py#L731-L741
https://github.com/numba/numba/blob/2e825b000e609e090005f8fb3d567999f1f1940c/numba/typed/dictobject.py#L749-L758

If I am correct, the fix is just a matter of replacing `key` by `castedkey` on line `741`.

**Comment by MarcMassar** [comment] 2022-03-15 19:20
It's probably a casting issue. The weird thing is that this issue disappear it the key type is `Tuple(in32, int64)`. But your suggested fix is almost surely going to work, so it might not be worth it to investigate further.

**Comment by guilhermeleobas** [comment] 2022-03-16 00:07
Would you like to give it a try and send a patch to Numba containing a fix?

**Comment by czgdp1807** [comment] 2022-04-02 10:04
On running the above example with the following diff,

```diff
diff --git a/numba/typed/dictobject.py b/numba/typed/dictobject.py
index 74c6ab02c..ec334eb1b 100644
--- a/numba/typed/dictobject.py
+++ b/numba/typed/dictobject.py
@@ -738,7 +738,7 @@ def impl_get(dct, key, default=None):
 
     def impl(dct, key, default=None):
         castedkey = _cast(key, keyty)
-        ix, val = _dict_lookup(dct, key, hash(castedkey))
+        ix, val = _dict_lookup(dct, castedkey, hash(castedkey))
         if ix > DKIX.EMPTY:
             return val
         return default
```

I get the following warning,

```python
/Users/czgdp1807/numba_project/numba/numba/typed/typeddict.py:33: NumbaTypeSafetyWarning: unsafe cast from UniTuple(int64 x 2) to UniTuple(uint32 x 2). Precision may be lost.
  d[key] = value
```

Are we okay with the above? If so, I can go ahead and make a PR to close this issue.

**Comment by stuartarchibald** [comment] 2022-04-05 09:58
@guilhermeleobas Thanks for debugging, your assessment in https://github.com/numba/numba/issues/7908#issuecomment-1068327361 seems to highlight the likely cause. 

@czgdp1807 RE the warning:
```
NumbaTypeSafetyWarning: unsafe cast from UniTuple(int64 x 2) to UniTuple(uint32 x 2). Precision may be lost.
```
This is because the dictionary is declared as taking `uint32` but Numba will infer the type of a Python int as `int64`, as a result the type of the requested key `UniTuple(int64 x 2)` has to be cast to match the types of the keys as declared in the dictionary. This is expected.

Patches to fix and test as suggested are welcome. Many thanks!

**Comment by czgdp1807** [comment] 2022-04-05 11:35
Great. I will send a fix with a regression test tomorrow.

**Closed** 2022-04-07 23:01 UTC
Labels: good second issue, bug - incorrect behavior
