### ISSUE TITLE
Calling jitted function with *args in a prange fails

### ISSUE THREAD

**Issue by lmcinnes** [numba/numba#5065] opened 2020-01-11 02:07 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ X ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have tried to track this down from errors that have begun occurring in some of my libraries after the release of 0.47 (the same code works perfectly well under 0.46). I have managed to get a reasonably small reproducer. The following is enough to trigger the issue:

```python
import numba
import numpy as np

@numba.njit(parallel=True) 
def reproducer(a, dist, dist_args): 
     result = np.zeros((a.shape[0], a.shape[0]), dtype=np.float32) 
     for i in numba.prange(a.shape[0]): 
        for j in range(i + 1, a.shape[0]): 
             d = dist(a[i], a[j], *dist_args) 
             result[i, j] = d 
             result[j, i] = d 
     return result 

@numba.njit()
def euclidean(x, y):
    result = 0.0
    for i in range(x.shape[0]):
        result += (x[i] - y[i]) ** 2
    return np.sqrt(result)

a = np.random.random(size=(5,2))

reproducer(a, euclidean,())
```

This results in an error:

```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type Tuple() given for non scalar argument #5

File "<ipython-input-29-3dfcc0ab5f42>", line 4:
def reproducer(a, dist, dist_args):
    <source elided>
    result = np.zeros((a.shape[0], a.shape[0]), dtype=np.float32)
    for i in numba.prange(a.shape[0]):
    ^

[1] During: lowering "id=12[LoopNest(index_variable = parfor_index.1340, range = (0, $46binary_subscr.5, 1))]{132: <ir.Block at <ipython-input-29-3dfcc0ab5f42> (8)>, 78: <ir.Block at <ipython-input-29-3dfcc0ab5f42> (5)>, 80: <ir.Block at <ipython-input-29-3dfcc0ab5f42> (5)>, 54: <ir.Block at <ipython-input-29-3dfcc0ab5f42> (4)>}Var(parfor_index.1340, <ipython-input-29-3dfcc0ab5f42>:4)" at <ipython-input-29-3dfcc0ab5f42> (4)
```

The passing of \*args to the function seems to be necessary to trigger the error, as does the prange. In the original code a distance function that may or may not take extra arguments is passed in and used, with the extra arguments handled via the \*args which is sometimes empty, so this is necessary for my use case. In prior versions it worked fine. Any assistance getting to either solutions or workarounds would be appreciated.

Edit: Update reproducer code to actually reproduce the error -- sorry.

**Comment by stuartarchibald** [comment] 2020-01-13 10:43
Thanks for the report and for tracking this down, it was on my TODOs, so this is really helpful!

MWR:
```python
from numba import njit, prange

@njit(parallel=True)
def foo(func, args):
    for _ in prange(1):
        func(1, *args)

@njit()
def bar(x):
    return 1

foo(bar, ())
```
CC @DrTodd13

**Comment by DrTodd13** [comment] 2020-01-14 19:34
@stuartarchibald @lmcinnes Isn't this just another example of you can't pass tuples to gufuncs?

**Comment by lmcinnes** [comment] 2020-01-14 19:44
Possibly -- but this worked just fine in numba 0.46; the error only arrived with 0.47.

**Comment by stuartarchibald** [comment] 2020-01-15 09:06
This did "work" in 0.46, I guess the question is, did this work simply because it didn't break when it should have or did it work then but something has broken since?

Whilst the `__repr__` of the type for `tuple()` has changed between 0.46 and 0.47, the types look the same (0.47 is on the left):
```
---------------------------------Variable types--------------   ---------------------------------Variable types--------------
{'$10get_iter.3': range_iter_int64,                           | {'$10.2': pair<int64, bool>,
 '$12for_iter.1': pair<int64, bool>,                          |  '$10.3': int64,
 '$12for_iter.2': int64,                                      |  '$10.4': bool,
 '$12for_iter.3': bool,                                       |  '$12.4': none,
 '$20call_function_ex.4': none,                               |  '$2.1': Function(<class 'numba.special.prange'>),
 '$30return_value.1': none,                                   |  '$2.3': range_state_int64,
 '$4load_global.0': Function(<class 'numba.special.prange'>), |  '$2.4': range_iter_int64,
 '$8call_function.2': range_state_int64,                      |  '$26.2': none,
 '$const28.0': none,                                          |  '$const2.2': Literal[int](1),
 '$const6.1': Literal[int](1),                                |  '$const26.1': none,
 '$phi12.0': range_iter_int64,                                |  '$phi10.1': range_iter_int64,
 '$phi14.1': int64,                                           |  '$phi12.1': int64,
                                                              >  '$phi24.1': int64,
                                                              >  '$phi24.2': range_iter_int64,
 '_': int64,                                                     '_': int64,
 'arg.args': Tuple(),                                         |  'arg.args': (),
 'arg.func': type(CPUDispatcher(<function bar at 0x7fa5755543 |  'arg.func': type(CPUDispatcher(<function bar at 0x7f8588736a
 'args': Tuple(),                                             |  'args': (),
 'func': type(CPUDispatcher(<function bar at 0x7fa5755543b0>) |  'func': type(CPUDispatcher(<function bar at 0x7f8588736a70>)
----------------------------------Return type----------------   ----------------------------------Return type----------------

```
The variable `args.args` is a `tuple` type in both cases.

**Comment by stuartarchibald** [comment] 2020-01-15 09:37
I think I've found it. This line here:
https://github.com/numba/numba/blob/release0.46/numba/npyufunc/wrappers.py#L656
checks if the symbol is scalar...
*  In Numba 0.46, the argument `()` appears as an empty `tuple` with no associated symbol hence `bool(syms)`, as in the predicate for the check, evaluates to `False` and  the code "works". (I  suspect the generated code is striding into the tuple data at invalid access locations but it is "got away with" as a result of not being accessed/the jumps being small if accessed).
* In Numba 0.47,  the argument `()` appears as a `numba.Tuple` type and has an associated symbol `('c',)` from the `numba.npyufunc.parfors::_create_shape_signature` function, therefore `bool(syms)` evaluates to `True` and the branch with the raise is called.

I think the 0.47 behaviour is correct? What do you think  @DrTodd13?

I also suspect that this is now working (as in, correctly not working) as a result of certain forms of tuple being interpreted into `Tuple` types opposed to constants and analysis being updated to handle that.

**Comment by lmcinnes** [comment] 2020-01-15 17:40
I don't follow all the details of the internals, but this makes some sense. I can accept that we now have "correct" behaviour -- my question then is: what should I be doing instead? Is there some other datatype I can use instead of tuples?

**Comment by lmcinnes** [comment] 2020-01-17 18:29
It seems like the approach may be to essentially use partial functions. That is, for any distance functions that are going to take extra \*args define a proxy function:
```python
if len(args) > 0:
    @numba.njit()
    def dist_to_pass(x, y):
        return dist(x, y, *args)
else:
    dist_to_pass = dist
```
and then have all the functions that take distances use distances that don't use any optional args.
In some small experiments that seems to work (in that is made numba happy), but I am not sure about the overhead costs involved in the indirection, or whether I am actually solving the problem, or pushing it to somewhere else where numba fails to detect the issue. Any thoughts @stuartarchibald ?

**Comment by DrTodd13** [comment] 2020-01-18 16:41
@stuartarchibald I believe the gufunc signature should only get a symbol for a param if it is an array.  So, a tuple of any kind should not get a symbol.  We need to do a tuple check before the lowerer so we can throw a nicer error like we do now for reduction errors.  Until we have gufuncs that support tuples, we should have a nice error that reports a tuple being passed inside a parfor and the associated line number.

**Comment by stuartarchibald** [comment] 2020-01-20 20:43
> @stuartarchibald I believe the gufunc signature should only get a symbol for a param if it is an array. So, a tuple of any kind should not get a symbol. We need to do a tuple check before the lowerer so we can throw a nicer error like we do now for reduction errors. Until we have gufuncs that support tuples, we should have a nice error that reports a tuple being passed inside a parfor and the associated line number.

Agreed! This is a quick thing to do and should hopefully help the group of users that keep hitting this.

**Comment by stuartarchibald** [comment] 2020-01-20 20:47
> It seems like the approach may be to essentially use partial functions. That is, for any distance functions that are going to take extra *args define a proxy function:
> 
> ```python
> if len(args) > 0:
>     @numba.njit()
>     def dist_to_pass(x, y):
>         return dist(x, y, *args)
> else:
>     dist_to_pass = dist
> ```
> 
> and then have all the functions that take distances use distances that don't use any optional args.
> In some small experiments that seems to work (in that is made numba happy), but I am not sure about the overhead costs involved in the indirection, or whether I am actually solving the problem, or pushing it to somewhere else where numba fails to detect the issue. Any thoughts @stuartarchibald ?

I think I understand how you are working around this (effectively baking in the args?) and I think this may well work, but will it also push a lot onto the compiler as it'll end up specialising on the closed over `*args` ?

**Comment by lmcinnes** [comment] 2020-01-20 21:03
@stuartarchibald : For my current use case the args are essentially fixed once on instantiation of a given class, and the above would be run then. From that point of view it might be okay. I admit I am not quite sure what you mean by " will it also push a lot onto the compiler". Is the concern that the compilation phase will be long? That was already the case regardless for this project, so this is not much extra all up as far as I can tell.  If the concern was that the compiler will do a special compile of the dist function for specific args that might not generalise well -- I think that is definitely okay for my use case.

PS. I implemented a version of this for pynndescent and it seems to be running successfully under 0.47 so that's a good start. I still have some benchmarking tests to get through before I decide to go with this approach.

**Comment by stuartarchibald** [comment] 2020-01-20 21:11
> @stuartarchibald : For my current use case the args are essentially fixed once on instantiation of a given class, and the above would be run then. From that point of view it might be okay. I admit I am not quite sure what you mean by " will it also push a lot onto the compiler". Is the concern that the compilation phase will be long? That was already the case regardless for this project, so this is not much extra all up as far as I can tell. If the concern was that the compiler will do a special compile of the dist function for specific args that might not generalise well -- I think that is definitely okay for my use case.

Yes, I was concerned about compilation time especially. I also wonder how "freezing" of compile time freevars as constants is working here? I guess it's because the `@njit` is in a closure itself so it'll be creating a new version every time though and as a result also capturing `*args` correctly. I think so long as `*args` remains read only and of a type of constant that is lowerable (and compile time isn't a concern) then this could well work ok for your use case.
 
> PS. I implemented a version of this for pynndescent and it seems to be running successfully under 0.47 so that's a good start. I still have some benchmarking tests to get through before I decide to go with this approach.

Well, this is good news! Nothing like proof from the field!!

**Comment by stuartarchibald** [comment] 2020-02-19 16:24
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:24 UTC
Labels: ParallelAccelerator, bug, duplicate
