### ISSUE TITLE
cgutils.py error:  TypeError: 'IntType' object is not callable

### ISSUE THREAD

**Issue by nscozzaro** [numba/numba#2658] opened 2017-12-21 13:43 UTC
When I try and import Librosa, the traceback I get shows there's an error happening with Numba. I've looked over the other issues but I can't seem to find this exact issue so I'm opening this as a new issue. Please let me know what I can try to solve the problem. 
I'm running this on a Google Cloud Platform Ubuntu 16.04 VM. 

/home/nscozzaro/librosa/librosa/util/decorators.py in <module>()
      7 from decorator import decorator
      8 import six
----> 9 from numba.decorators import jit as optional_jit
     10 
     11 __all__ = ['moved', 'deprecated', 'optional_jit']

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/__init__.py in <module>()
     10 
     11 # Re-export typeof
---> 12 from .special import typeof, prange
     13 
     14 # Re-export error classes

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/special.py in <module>()
      2 
      3 from .typing.typeof import typeof
----> 4 from .parfor import prange
      5 
      6 __all__ = ['typeof', 'prange']

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/parfor.py in <module>()
     20 
     21 import numba
---> 22 from numba import ir, ir_utils, types, typing, rewrites, config, analysis
     23 from numba import array_analysis, postproc, typeinfer
     24 from numba.typing.templates import infer_global, AbstractTemplate

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/ir_utils.py in <module>()
     10 import numba
     11 from numba.six import exec_
---> 12 from numba import ir, types, typing, config, analysis, utils, cgutils
     13 from numba.typing.templates import signature, infer_global, AbstractTemplate
     14 from numba.targets.imputils import impl_ret_untracked

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/cgutils.py in <module>()
     20 voidptr_t = int8_t.as_pointer()
     21 
---> 22 true_bit = bool_t(1)
     23 false_bit = bool_t(0)
     24 true_byte = int8_t(1)

TypeError: 'IntType' object is not callable

**Comment by stuartarchibald** [comment] 2018-01-01 17:28
Thanks for the report. Please could you post some precise steps to replicate what you are seeing?

Many thanks.

**Comment by nscozzaro** [comment] 2018-01-01 18:20
The only step I did was "import librosa" in jupyter notebook. 
I solved the problem by pip installing librosa=0.4.3
I'm not sure why it's throwing that error with the librosa 0.5.1 version

**Comment by pajevic** [comment] 2018-01-23 20:50
I get the same error (with or without librosa 0.4.3) anytime I import numba (tried versions 0.36.2, 0.35, 0.34, ...). Error is always in cgutils.py, line 22! I am running this on Mac OSX, anaconda python, and pip installed numba (numba-0.36.2-cp27-cp27m-macosx_10_6_x86_64.whl). I could not find this error addressed in any other post.

**Comment by stuartarchibald** [comment] 2018-02-07 09:32
@pajevic thanks for posting too.

I'm struggling to reproduce this. I have an OSX machine, Anaconda python, and have pip installed `librosa==0.4.3` and Numba 0.36.2, and I also have a clean env with just Numba 0.36.2, both of which `import numba` fine. Please could one of you or @nscozzaro provide the exact steps to reproduce?

I also wonder if there is something problematic in the pip dependency resolution, do you know which combinations of Numba and llvmlite you have installed? These packages are released in lock-step and so Numba 0.36.2 should have llvmlite version 0.21.0.

Many thanks.

**Comment by nscozzaro** [comment] 2018-02-07 12:22
I ended up just using an older version of librosa which worked, I completed
my project, and now I've moved on so I unfortunately won't be able to
assist in the steps to reproduce this any more. Thank you for your help
though.

**Comment by pajevic** [comment] 2018-02-07 17:46
Reproducing the error on my system is simple, just “import numba” will do it!

I tried pretty much all the versions of numba (and librosa) and only when I pip install numba with: pip install 'numba<=0.19'
does the error go away! Specifically, the latest version of numba that works on my system:
numba.__version__
'0.18.2'

but then it does not have jitclass, so it would be nice to resolve this problem.

This numba version works also with the latest librosa version (0.5.1, as well as 0.4.3, as was suggested to resolve this problem).

I will soon be installing anaconda and everything else from scratch on another Mac OSX computer, and will post if the problem there still persists.

**Comment by person142** [comment] 2018-03-28 18:08
Just ran into this on armv7 where `conda install -c numba llvmlite` gets an ancient `llvmlite` version 0.7:

```
>>> import llvmlite
>>> llvmlite.__version__
'0.7.0.dev+21.gcda19bd.dirty'
```

(This is also confirmed on the website: https://anaconda.org/numba/llvmlite.) In particular, this is before https://github.com/numba/llvmlite/commit/eb745f3f4b9d1340b4fabed754e53b9f787b0816 was added (in 0.10), which leads to these errors when importing Numba.

Might be sensible to take down the old version of `llvmlite` for arm?

**Comment by seibert** [comment] 2018-03-28 20:32
I need to push my more recent builds of llvmlite and numba for ARMv7 to the channel.  (At conference, so I can't get to my Raspberry Pi.)  They pass most unit tests, except for the handful of failing SVD-related linear algebra tests that Stuart is trying to figure out.

**Comment by Juanlu001** [comment] 2019-03-12 17:23
Observed this error again in a Debian Jessie machine with Python 3.4, will try to provide more details in a couple of days (hence leaving this as a self-reminder)

**Comment by stuartarchibald** [comment] 2019-03-27 21:42
@Juanlu001 any update? thanks.

**Comment by Juanlu001** [comment] 2019-03-28 01:24
I tried to reproduce this again with no luck... In general installing numba on Debian Jessie + Python 3.4 is a bit tricky, because it requires the perfect combination of

* llvm, llvmlite<0.6, numba<0.21, or
* llvm-4.0, llvmlite<0.20, and numba<0.36.

However, despite my best efforts I could not go back to our previous failing state. Perhaps it was a bad pip version, an unfortunate pinning somewhere, or something else.

**Comment by stuartarchibald** [comment] 2019-03-28 10:43
@Juanlu001 thanks, unless you object, I'm inclined to close this. It's seemingly hard to reproduce and is almost certainly down to using ancient packages. Numba now ships both linux-aarch64 and linux-armv7l conda packages which can also be pip installed.

**Comment by Juanlu001** [comment] 2019-03-28 10:47
> is almost certainly down to using ancient packages

Definitely. +1 for closing

**Comment by stuartarchibald** [comment] 2019-03-28 10:49
@Juanlu001 thanks. Closing.

**Closed by stuartarchibald** 2019-03-28 10:49 UTC
Labels: needtriage
