### ISSUE TITLE
Numba compiled code prints RuntimeWarning where there should be none

### ISSUE THREAD

**Issue by andrej5elin** [numba/numba#5656] opened 2020-04-30 08:55 UTC
## Reporting a bug

Dera Numba developers, I have found this bug, running latest numba 0.49 on Mac OSX. If we make a vectorized version of function that uses np.log (which raises Warnings if used with x = 0)
and we make sure that arguments are always larger than 1, like:

>>> @nb.jit([nb.float64(nb.float64)])
>>> def numba_no_bug(x):
...        """does not print divide by zero warning, when x = 0"""
...        return 0 if x <= 1 else np.log(x)

>>> @nb.vectorize([nb.float64(nb.float64)])
>>> def numba_bug(x):
...        """prints divide by zero warning, when x = 0"""
...        return numba_no_bug(x)

Then the non-vectorized function works as expected:

>>> numba_no_bug(0)
0

The vectorized version of the function prints warnings, which is unexpected

>>> numba_bug(0)
__main__:1: RuntimeWarning: divide by zero encountered in numba_bug

- [yes ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [yes ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by esc** [comment] 2020-04-30 09:15
@andrej5elin thanks for submitting this to the Numba issue tracker, we value your input. Before we triage it, I'd like to direct you attention to formatting in GitHub issues. For future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by esc** [comment] 2020-04-30 09:50
@andrej5elin thanks for submitting this to the Numba issue tracker. I managed to reproduce your error using the following reproducer:


```python
import numba as nb
import numpy as np


@nb.jit([nb.float64(nb.float64)])
def numba_no_bug(x):
    """does not print divide by zero warning, when x = 0"""
    return 0 if x <= 1 else np.log(x)


@nb.vectorize([nb.float64(nb.float64)])
def numba_bug(x):
    """prints divide by zero warning, when x = 0"""
    return numba_no_bug(x)


numba_no_bug(0)
numba_bug(0)

```

This looks very similar to #4793 and I suspect the same root cause, so I will label it as a duplicate provisionally.

**Comment by stuartarchibald** [comment] 2020-05-01 09:49
Added explanation here: https://github.com/numba/numba/issues/4793#issuecomment-622323686

Closing as duplicate.

**Closed by stuartarchibald** 2020-05-01 09:49 UTC
Labels: duplicate
