### ISSUE TITLE
LoweringError: Failed at object (object mode frontend)

### ISSUE THREAD

**Issue by pluiez** [numba/numba#3131] opened 2018-07-19 08:47 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, I have a single function shuffling lines in files by given indices. In python 3, it's extremely slow due to the massive invocation of file.tell method, which is not a problem in python 2. So I'm intended to use numba to speed up this function. However, a LoweringError raised:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    576     try:
--> 577         yield
    578     except NumbaError as e:

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/objmode.py in lower_inst(self, inst)
     64         if isinstance(inst, ir.Assign):
---> 65             value = self.lower_assign(inst)
     66             self.storevar(value, inst.target.name)

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/objmode.py in lower_assign(self, inst)
    158         elif isinstance(value, ir.Expr):
--> 159             return self.lower_expr(value)
    160         elif isinstance(value, ir.Global):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/objmode.py in lower_expr(self, expr)
    372         else:
--> 373             raise NotImplementedError(expr)
    374 

NotImplementedError: make_function(name=$const236.13, code=<code object <listcomp> at 0x7f654d500810, file "/home/pluiefox/work/base/thseq/utils/file.py", line 70>, closure=$236.11, defaults=None)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-2-118eec84de1c> in <module>()
----> 1 shuffle('test.py', 'xxx')

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    366                     e.patch_message(''.join(e.args) + help_msg)
    367             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 368             raise e
    369 
    370     def inspect_llvm(self, signature=None):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    323                 argtypes.append(self.typeof_pyval(a))
    324         try:
--> 325             return self.compile(tuple(argtypes))
    326         except errors.TypingError as e:
    327             # Intercept typing error that may be due to an argument

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    651 
    652                 self._cache_misses[sig] += 1
--> 653                 cres = self._compiler.compile(args, return_type)
    654                 self.add_overload(cres)
    655                 self._cache.save_overload(sig, cres)

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    871     pipeline = pipeline_class(typingctx, targetctx, library,
    872                               args, return_type, flags, locals)
--> 873     return pipeline.compile_extra(func)
    874 
    875 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    365         self.lifted = ()
    366         self.lifted_from = None
--> 367         return self._compile_bytecode()
    368 
    369     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    802         """
    803         assert self.func_ir is None
--> 804         return self._compile_core()
    805 
    806     def _compile_ir(self):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    789         self.define_pipelines(pm)
    790         pm.finalize()
--> 791         res = pm.run(self.status)
    792         if res is not None:
    793             # Early pipeline completion

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event(stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in stage_objectmode_frontend(self)
    436         if self.flags.enable_looplift:
    437             assert not self.lifted
--> 438             cres = self.frontend_looplift()
    439             if cres is not None:
    440                 raise _EarlyPipelineCompletion(cres)

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in frontend_looplift(self)
    426                               self.args, self.return_type,
    427                               outer_flags, self.locals,
--> 428                               lifted=tuple(loops), lifted_from=None)
    429             return cres
    430 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in compile_ir(typingctx, targetctx, func_ir, args, return_type, flags, locals, lifted, lifted_from, library)
    885                         args, return_type, flags, locals)
    886     return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
--> 887                                lifted_from=lifted_from)
    888 
    889 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in compile_ir(self, func_ir, lifted, lifted_from)
    373 
    374         self._set_and_check_ir(func_ir)
--> 375         return self._compile_ir()
    376 
    377     def stage_analyze_bytecode(self):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in _compile_ir(self)
    809         """
    810         assert self.func_ir is not None
--> 811         return self._compile_core()
    812 
    813 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    789         self.define_pipelines(pm)
    790         pm.finalize()
--> 791         res = pm.run(self.status)
    792         if res is not None:
    793             # Early pipeline completion

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event(stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    650         """
    651         lowerfn = self.backend_object_mode
--> 652         self._backend(lowerfn, objectmode=True)
    653 
    654         # Warn if compiled function in object mode and force_pyobject not set

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    626             self.library.enable_object_caching()
    627 
--> 628         lowered = lowerfn()
    629         signature = typing.signature(self.return_type, *self.args)
    630         self.cr = compile_result(

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in backend_object_mode(self)
    599                                      self.library,
    600                                      self.func_ir,
--> 601                                      self.flags)
    602 
    603     def backend_nopython_mode(self):

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
   1016         )
   1017     lower = objmode.PyLower(targetctx, library, fndesc, interp)
-> 1018     lower.lower()
   1019     if not flags.no_cpython_wrapper:
   1020         lower.create_cpython_wrapper()

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215 
    216         # Close tail of entry block

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240 
    241         self.post_lower()

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 
    256     def create_cpython_wrapper(self, release_gil=False):

~/anaconda2/envs/py36/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    583         from numba import config
    584         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 585         six.reraise(type(newerr), newerr, tb)
    586 
    587 

~/anaconda2/envs/py36/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed at object (object mode frontend)
Failed at object (object mode backend)
make_function(name=$const236.13, code=<code object <listcomp> at 0x7f654d500810, file "/home/pluiefox/work/base/thseq/utils/file.py", line 70>, closure=$236.11, defaults=None)

File "utils/file.py", line 70:
def shuffle(inputs, outputs, indices=None, strict=False):
    <source elided>
        counts = [count] * len(inputs)
        offsets = [offs[:count] for offs in offsets]
        ^
[1] During: lowering "$236.14 = make_function(name=$const236.13, code=<code object <listcomp> at 0x7f654d500810, file "/home/pluiefox/work/base/thseq/utils/file.py", line 70>, closure=$236.11, defaults=None)" at /home/pluiefox/work/base/thseq/utils/file.py (70)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

```

This is minimal code reproducing this error.

```
import itertools
import numpy
import numba

@numba.jit
def shuffle(inputs, outputs, indices=None, strict=False):
    """
    shuffle with low memory usage
    :param inputs: a list of input files
    :param outputs: a list of corresponding output files
    :param indices: a numpy array of size (num_lines,)
    :param strict:
    :return:
    """
    if isinstance(inputs, str):
        inputs = [inputs]
    if isinstance(outputs, str):
        outputs = [outputs]

    if len(inputs) != len(outputs):
        raise ValueError("The number of input files and output files doesn't match.")
    counts = []
    offsets = [] # find offsets of each line for each input file
    for f in inputs:
        c = 0
        offs = []
        r = open(f, 'r')
        off = 0
        r.readline()
        while r.tell() > off:
            off = r.tell() # this method is significantly SLOW in python 3, not in python 2.  
            offs.append(off)
            c += 1
            r.readline()
        if c > 0:
            offs = [0] + offs[:-1]

        counts.append(c)
        offsets.append(offs)
    if strict: # consistency check
        if len(set(counts)) != 1:
            raise ValueError("The files are not strictly aligned.")
    else:
        count = min(counts)
        counts = [count] * len(inputs)
        offsets = [offs[:count] for offs in offsets]

    offsets = numpy.array(offsets)
    if indices is None:
        indices = numpy.arange(counts[0])
        numpy.random.shuffle(indices)

    indices = numpy.array(indices)

    if indices.size != counts[0]:
        raise ValueError("The given indices doesn't match lines of file.")

    offsets = offsets[:, indices]  # shuffle offsets by indices
    for i, (fi, fo) in enumerate(itertools.zip_longest(inputs, outputs)):
        r=open(fi)
        w=open(fo, 'w')
        # the above 2 lines is an alternative to the following commented with statement,
        # since numba would raise an error on it.
        # with open(fi) as r, open(fo, 'w') as w:
        for off in offsets[i]: # write line by seeking indexed offset
            r.seek(off)
            line = r.readline()
            w.write("%s\n" % line.strip())
    return indices

shuffle('test.py','test.out')
```

**Comment by stuartarchibald** [comment] 2018-07-19 11:35
Thanks for the report. Unfortunately I cannot seem to be able to reproduce this using the sample code. The sample code for me does however hit a known bug which is reported and discussed here https://github.com/numba/numba/issues/2657. I can also guess at the cause of the reported lowering error as the same bug as https://github.com/numba/numba/issues/3118.

FWIW I think Numba is going to struggle with your code. Numba is great a compiling loop based numerical and NumPy array orientated code. It supports a subset of Python and NumPy as declared [here](http://numba.pydata.org/numba-doc/dev/reference/pysupported.html) and [here](http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html), you'll also want to look at `nopython` vs. `object mode` as described in the [performance guide](http://numba.pydata.org/numba-doc/dev/user/performance-tips.html#no-python-mode-vs-object-mode) and in the definition of object mode [here](http://numba.pydata.org/numba-doc/dev/glossary.html#term-object-mode). As your code will be running in object mode, and there's very few lops that are liftable, performance may not be great (and I'm afraid Numba will not help with `file.tell()`.

**Comment by jonas-hagen** [comment] 2018-09-10 11:44
@stuartarchibald Thanks a lot! I did not now about `njit`, this implementation would have been my first choice if I knew about it!

**Comment by stuartarchibald** [comment] 2018-09-17 09:03
@jonas-hagen no problem, thanks for getting back to us to confirm this is a good workaround.

**Comment by stuartarchibald** [comment] 2019-09-11 13:59
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2019-09-11 13:59 UTC
Labels: bug
