### ISSUE TITLE
Feature req: Fast, generic nan check

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [numba/numba#3297] opened 2018-09-07 20:35 UTC
## Feature request

I am working on a numba function with very similar behavior for `int64[:]` and `float64[:]` inputs. The only difference is that `float64[:]` has some NaN checking, whereas the `int64[:]` one doesn't. When the `float64[:]` has no NaNs behavior aside from typing is identical to that of `int64[:]`. This is a very simplified version:

```py
njit()
def func(vals):
    if vals.dtype == numba.int64:
        no_nas = True
    else:
        no_nas = False

    sum = 0.0
    for v in vals:
        if no_nas or not np.isnan(v):
            sum += v
```

I am forced to define the `no_nas` flag because `np.isnan` will raise an exception if called on an int. But checking both `no_nas` and `np.isnan` in a single if-statement impacts performance, particularly for the `int64[:]` case. Another alternative is to implement the function twice, once for `int64[:]` without nan checks and again for `float64[:]` with nan checks, but this will lead to a lot of duplicate code.

While looking for a solution I ran into [this example](https://numba.pydata.org/numba-doc/dev/user/generated-jit.html), which implements an efficient `is_missing`, which *I think* will let numba compile down nan-checks in if-statements to no-ops for `int64`. I would love to see this efficient nan check included in numba as a utility, which will make generic function writing *much* easier.

If you think this use case justifies it, I would be more than happy to make a PR to add a generic, efficient nan check to numba based on the one in the docs.

**Comment by stuartarchibald** [comment] 2018-09-28 09:57
Thanks for the report. I don't think I can reproduce what you describe, the following does not raise an exception for an `int64` input.
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return np.isnan(x)

print(foo(np.int64(10)))
print(foo(np.float64(10)))

print(foo.inspect_asm(foo.signatures[0]))
print(foo.inspect_asm(foo.signatures[1]))
```
both `int64` and `float64` are supported in `isnan` and the resulting machine code looks like:
`int64`:
```asm
_ZN8__main__7foo$241Ex:
	movb	$0, (%rdi)
```
`float64`:
```asm
_ZN8__main__7foo$242Ed:
	ucomisd	%xmm0, %xmm0
	setp	(%rdi)
	xorl	%eax, %eax
	retq
```
which is what I'd expect for an `isnan`.

**Comment by stuartarchibald** [comment] 2019-03-27 22:29
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-03-27 22:29 UTC
