### ISSUE TITLE
Compilation hangs in complex use case with 0.51.1

### ISSUE THREAD

**Issue by juanjgalvez** [numba/numba#6192] opened 2020-08-31 14:00 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

A complex use case with Bodo seemingly hangs (or takes very long to compile) during compilation with the latest Numba 0.51.1.  This worked with the previous release. After aborting with CTRL-C the stacktrace seems to suggest that Numba is stuck in control flow analysis:

```
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/dispatcher.py", line 105, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler.py", line 627, in compile_extra
    push_state(cur_node)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 588, in push_state
    return pipeline.compile_extra(func)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler.py", line 425, in _compile_bytecode
    succs_state[node] = [dest for dest in self._succs[node]]
KeyboardInterrupt
    return self._compile_core()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler.py", line 396, in _compile_core
    pm.run(self.state)
  File "/home/ubuntu/bodo-master/bodo/numba_compat.py", line 1478, in passmanager_run
    self._runPass(idx, pass_inst, state)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/untyped_passes.py", line 86, in run_pass
    func_ir = interp.interpret(bc)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/interpreter.py", line 127, in interpret
    self.cfa = AdaptCFA(flow)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/byteflow.py", line 1364, in __init__
    backbone = self._flow.cfgraph.backbone()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 268, in backbone
    return self._post_doms[self._entry_point]
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/utils.py", line 349, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 227, in _post_doms
    return self._find_post_dominators()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 554, in _find_post_dominators
    for loop in self._loops.values():
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/utils.py", line 349, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 219, in _loops
    return self._find_loops()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 645, in _find_loops
    for src, dest in self._back_edges:
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/utils.py", line 349, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 207, in _back_edges
    return self._find_back_edges()
  File "/home/ubuntu/miniconda3/envs/DEV/lib/python3.8/site-packages/numba/core/controlflow.py", line 600, in _find_back_edges
    if cur_node in stack:
KeyboardInterrupt
```

I have not been able to find a smaller or different reproducer yet.

**Comment by esc** [comment] 2020-08-31 14:05
@juanjgalvez thanks for reporting this. It might be similar to:  https://github.com/numba/numba/issues/6186 -- there is a proposed fix in #6187 which you could try, perhaps?

**Comment by juanjgalvez** [comment] 2020-08-31 16:07
Thanks @esc ! I can confirm that #6187 solves the issue for this use case, and it also seems that Numba 0.51.1 with this fix speeds up compilation a bit (maybe 8%) for this use case.

**Comment by esc** [comment] 2020-08-31 16:12
@juanjgalvez excellent, thanks for trying this and confirming it solves your issue. We are planning to release 0.51.2 on Wednesday with the aforementioned patch, so it shouldn't be too long until you have a working release.

**Comment by juanjgalvez** [comment] 2020-08-31 16:14
> @juanjgalvez excellent, thanks for trying this and confirming it solves your issue. We are planning to release 0.51.2 on Wednesday with the aforementioned patch, so it shouldn't be too long until you have a working release.

Sounds great. Thanks very much.

**Comment by stuartarchibald** [comment] 2020-09-01 22:03
Thanks for following up on this @juanjgalvez @esc, closing as a duplicate of https://github.com/numba/numba/issues/6186.

**Closed by stuartarchibald** 2020-09-01 22:03 UTC
Labels: bug - regression, performance, performance - compile time
