### ISSUE TITLE
@guvectorized functions over dask distributed

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#4314] opened 2019-07-12 13:43 UTC
### UPDATE 2024
Statically defined gufuncs don't work with distributed anymore, either. Read: https://github.com/numba/numba/issues/4314#issuecomment-1992103833

### Original post

Dynamically defined functions - namely, anything from a Jupyter notebook - can be executed over a dask distributed grid thanks to cloudpickle.
Functions decorated with @guvectorize can be pickled, but only as long as they are defined in a static module.

Type in a jupyter notebook:

```python
import distributed
from numba import guvectorize, i8

def f(x):
    return x * 2


@guvectorize([(i8, i8[:])], '()->()')
def g(x, out):
    out[0] = x * 2

    
client = distributed.Client()

print(f(2))
print(g(2))
print(client.submit(f, 2).result())
print(client.submit(g, 2).result())
```
Output:
```
4
4
4

AttributeError: module '__main__' has no attribute 'g'
```

Note that the above is not the same as just writing ``cloudpickle.loads(cloudpickle.dumps(g))``, which works (but isn't terribly useful) because loads and dumps are running in the same interpreter.

Workaround:
```python
def cp_guvectorize(*args, **kwargs):
    """Same as :func:`numba.guvectorize`, but can be used to decorate dynamically
    defined function and then pickle them with
    `cloudpickle <https://pypi.org/project/cloudpickle/>`_.
    On the other hand, it can't be called from another jit-compiled function.
    """

    def decorator(func):
        return _PickleableGUVectorized(func, args, kwargs)

    return decorator


class _PickleableGUVectorized:
    def __init__(self, func, guvectorize_args, guvectorize_kwargs):
        self.args = func, guvectorize_args, guvectorize_kwargs
        decorator = numba.guvectorize(*guvectorize_args, **guvectorize_kwargs)
        self.ufunc = decorator(func)

    def __reduce__(self):
        return _PickleableGUVectorized, self.args

    def __call__(self, *args, **kwargs):
        return self.ufunc(*args, **kwargs)

    
@cp_guvectorize([(i8, i8[:])], '()->()')
def h(x, out):
    out[0] = x * 2

print(client.submit(h, 2).result())
```
Output:
```
4
```

**Comment by mrocklin** [comment] 2019-08-03 20:36
I would also love to see this.  This might also be fixed by adding `__setstate__` and `__getstate__` methods.

**Comment by mrocklin** [comment] 2019-08-03 20:56
Oh, I see that this returns a proper `numpy.ufunc` typed object.  Perhaps some wrapper solution like what @crusaderky suggests is necessary.

**Comment by rabernat** [comment] 2020-02-06 15:00
In the issue cited just above, I experienced a very similar serialization problem with a statically defined numba function (inside a module inside an installed package). Is there any documentation of successfully using dask.distributed + numba functions?

**Comment by crusaderky** [comment] 2020-02-07 13:18
@rabernat last time I checked, ``@guvectorize``'d functions are pickleable, but ``@vectorize``'d ones aren't. ``@jit``'ed functions are pickleable only when you explicitly define a signature. It's been a while since I last tested this so I may be wrong.

**Comment by sklam** [comment] 2020-02-07 15:12
I can replicate the issue with `multiprocessing`:

```python
from numba import guvectorize, f8
import pickle
import multiprocessing as mproc
import numpy as np



def make_g():

    @guvectorize([(f8, f8[:])], '()->()')
    def g(x, out):
        out[0] = x * 2

    return g


if __name__ == '__main__':
    spawner = mproc.get_context("spawn")
    x = np.ones(10)
    with spawner.Pool(1) as pool:
        g = make_g()
        res = pool.apply(g, [x])
        print(res)
```

This shows the error:

```pytb
  File "/Users/siu/miniconda3/envs/dev-numba-py37/lib/python3.7/site-packages/numpy/core/__init__.py", line 125, in _ufunc_reconstruct
    return getattr(mod, name)
AttributeError: module '__mp_main__' has no attribute 'g'
```

Note that the problem actually comes from NumPy's `_ufunc_reconstruct`.

**Comment by sklam** [comment] 2020-02-07 15:16
It looks like this is a numba gufunc problem. Numba `@vectorize`d and `@njit` functions are fine with and without explicit signatures.

**Comment by sklam** [comment] 2020-02-07 17:59
This issue is caused byhttps://github.com/numpy/numpy/blob/f71d9937d1e8a1e709f325f689f1e971e64c26a7/numpy/core/__init__.py#L124-L135

`@vectorize` is unaffected because we subclass from ufunc to make a `DUfunc` class. We will need to do the same for gufunc.

**Comment by llllllllll** [comment] 2020-02-16 00:07
The numpy ufunc serialization code is similar to the builtin pickle procedure for Python functions, which uses the `__name__` and `__module__` to find the object. This will work for statically defined ufuncs, because the deserializer can import the module and find the function. Like picking regular functions, this breaks when the function isn't in a static location, for example a closure. Cloudpickle solves this problem for closures and dynamically defined functions by serializing the bytecode and closure cells directly so that the function object can be reconstructed by the deserializer. This works because, given the same version of Python, the bytecode is a uniform representation for function we want to transfer. Arbitrary numpy ufunc objects do not have a uniform representation. Instead, ufunc objects contain a bunch of C function pointers which help select more C functions for actually performing the operations. There is no general way to represent native code, and any higher level information needed to do so will have been erased by the time the ufunc object is created. For that reason, the numpy serialization method is likely as good as they can do for ufuncs. Numba still has the higher level information which could be used to serialize arbitrary code, so if `guvectorize` was made to return a box like proposed, then the ufunc-like objects could be serialized just like `vectorize` created ufuncs.

**Comment by valpesendorfer** [comment] 2020-07-23 08:31
Is there any movement on this issue? 

I'm trying to compute a `@guvectorize` function over a distributed cluster (created using [dask-cloudprovider](https://github.com/dask/dask-cloudprovider)), and I'm running into the same error described [above](https://github.com/numba/numba/issues/4314#issuecomment-583444435).

I've found a couple of different issues regarding `ufuncs` and `distributed`. Some of them offer some workarounds, like importing the function differently. This works for me on a local cluster, but not for the one running on ECS instances created through cloudprovider.

**Comment by mrocklin** [comment] 2020-07-29 16:54
This came up again in a Pangeo call.  Given that Numpy moves slowly, I wonder if there is a workaround.  It looks like @sklam proposed a solution here:

> @vectorize is unaffected because we subclass from ufunc to make a DUfunc class and that bypasses the numpy registered reduce/reconstruct pair. We will need to do the same for gufunc.

Do we have a sense for how long this would take?  Are there people or resources around that would make sense to allocate here?

**Comment by rabernat** [comment] 2020-07-29 16:59
Thanks for the push on this @mrocklin. 

First, I want to note that I think this problem does also apply to `@vectorize`. Here is an example of a `@vectorize` function defined in a package:
https://github.com/xgcm/fastjmd95/blob/c828391890d18c82ff5e44484409055605111c1e/fastjmd95/jmd95numba.py#L150-L154
And here is an example of that function failing in distributed mode:
https://nbviewer.jupyter.org/github/xgcm/fastjmd95/blob/master/doc/fastjmd95_tutorial.ipynb

I would love if someone with more numba experience could verify this by pip installing `fastjmd95` and calling `jmd95numba.rho` in distributed mode. Perhaps I've done something wrong in packaging my functions.

More generally, I would love to support the overall goal of making all numba functions serializable and compatible with dask.distributed. In Pangeo, we fell like this is a great path to scaling out performant code. But the challenges described in this issue require annoying workarounds.

**Comment by stuartarchibald** [comment] 2020-09-11 08:37
xref https://github.com/numba/numba/pull/6234

**Comment by crusaderky** [comment] 2024-03-12 16:43
Resurrecting this as the situation has somewhat gotten worse.
As of numba 0.59, the code in my initial post doesn't work anymore even when the function is defined in a static module.

`@vectorize` still works.

The issue lays in `GUFunc.__call__:
https://github.com/numba/numba/blob/54433810bfa60458209ed2c24f62e793b12aca6b/numba/np/ufunc/gufunc.py#L171-L172

These two lines undo the serialization hack implemented by GUFunc:
https://github.com/numba/numba/blob/54433810bfa60458209ed2c24f62e793b12aca6b/numba/np/ufunc/gufunc.py#L33-L46

By the time control reaches `dask.array.Array.__array_ufunc__`, it's too late - we've lost the reference to the GUFunc object as well as the wrapped pure-python object. I can't find a way to hack around it in our serialization layer.

The workaround is to bypass `GUFunc.__call__`:
```python
@numba.guvectorize(["f8,f8[:]"], "()->()")
def double(x, out):
    out[:] = x * 2

x = da.random.randint(...)
y = x.__array_ufunc__(double, "__call__", x)
client = distributed.Client()
y.compute()  # Works
```
the above calls `GUFunc.__call__` for the first time on the remote worker, on the wrapped numpy data.

# Proposed design
`GUFunc.__call__` could special-cases dask. Dask will add some sort of duck-type interface, e.g.
```diff
def call(self, *args, **kwargs):
-     return self.ufunc(*args, **kwargs) 
+     if getattr(args[0], "__lazy_array__", False) is True:
+         return args[0].__array_ufunc__(self, "__call__", *args, **kwargs)
+     else:
+         return self.ufunc(*args, **kwargs) 
```
Dask wrappers, such as xarray and pint, will also need to implement the same `__lazy_array__` property.

**Closed** 2024-06-10 11:34 UTC
Labels: feature_request
