### ISSUE TITLE
Caching Silently Fails with Omitted Arguments

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7405] opened 2021-09-15 18:11 UTC
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Here is a reproducer:

```python
import numba

@numba.njit(cache=True)
def test_cache(num=1000):
    return num

test_cache()
print(test_cache._cache_hits[test_cache.signatures[0]])
```

No matter how often you run this code, it will never cache. I had narrowed down the cause of this issue to these lines in the class definition of the Omitted type:

```python
@property
    def key(self):
        return type(self._value), id(self._value)
 ```
 
 Replacing `id(self._value)` with `self._value` seems to fix the issue. I'll open a PR for this.

**Comment by njriasan** [comment] 2021-09-15 19:21
This issue only arises when testing with different subprocesses, so I'm not sure how to best write a test for this inside Numba.

**Comment by gmarkall** [comment] 2021-09-15 20:03
Some of the CUDA tests use subprocesses, so you can follow this pattern: https://github.com/numba/numba/blob/master/numba/cuda/tests/cudadrv/test_ptds.py (note that you probably don't want a `'spawn'` context, but that is needed for CUDA to avoid a CUDA-specific hazard).

I think there was a related issue around the key of `Omitted` - I'll see if I can find it.

**Comment by gmarkall** [comment] 2021-09-15 20:04
Ah, this is a duplicate of #6957.

**Closed** 2021-09-15 20:11 UTC
Labels: duplicate, needtriage
