### ISSUE TITLE
Incorrect array returned from guvectorize

### ISSUE THREAD

**Issue by sjster** [numba/numba#4893] opened 2019-11-26 02:01 UTC
The results returned from the function accelerated don't match the array values in the function. The values computed in the function are correct, however when I print them out in the caller the results are different. The signature of my function is shown here

```
@guvectorize(
    ["u8, u8, u8, u8, f8[:,:], f8[:,:], f8[:,:], f8[:,:], f8[:], f8[:], f8[:,:]"], "(), (), (), (), (nrow, nrow), (ncol, ncol), (nrow, ncol), (nrow, ncol), (nrow), (ndim) -> (nrow, ndim)", nopython=True,  target="cpu"
)
def numba_svd_derivative(j, nrow, ncol, ncomp, u, v, Xorig, X, d_sq, dum_var, result):


```

This is assigned in the caller as

```
res = numba_svd_derivative(j, self.nrow, self.ncol, self.projection_components, \
                                        self.u, self.v, self.Xorig, self.X, d_sq, dum_var)
```

I print out the result in the function and the caller as

```
Result from function  [[-0.05272821 -0.0053777 ]
 [-0.41784501  0.02318533]
 [ 0.44103981 -0.05173443]
 [-0.4346603   0.02583883]
 [ 0.46492926 -0.03837702]]

Result in caller  [[ 1.41032176e-08 -2.77016590e-07]
 [-5.57580582e-09  1.01076087e-06]
 [ 5.33546625e-08 -8.56518529e-07]
 [ 3.96530548e-08 -1.49919655e-06]
 [-3.67771149e-08  7.18771000e-07]]
```

I have verified the return types and shapes of the result array and they are both float64. Any ideas why this should happen?

**Comment by esc** [comment] 2019-11-26 09:40
@sjster thanks for reporting this on the Numba issue tracker. It is not possible to diagnose or reproduce this w/o having access to the code. Maybe you could construct a minimal reproducer which you can submit that highlights the issue? In any case, just guessing from the numbers in the result in the caller it might be that you are seeing is an uninitialized memory region, for example created with `np.empty`.?

**Comment by sjster** [comment] 2019-11-26 17:50
I can put a self-contained repository in GitHub and give you access. Would that work?

**Comment by sjster** [comment] 2019-11-26 18:00
You can access the code here [https://github.com/sjster/Numba/blob/master/numba_test.py](https://github.com/sjster/Numba/blob/master/numba_test.py)

You run it as python numba_test.py and in the output there are two relevant sections. 
1. The output matrix under 'Result from function' (A)differs from the 
2. output matrix under 'Result in calling function' (B).

A is correct however B is not and as you suggested probably a Numpy initialized location.  The function that is accelerated by Numba is named 'numba_svd_derivative '(A) and the calling function is named 'compute_svd_derivative' (B).

Please let me know if I can provide any further information

**Comment by esc** [comment] 2019-11-27 08:57
@sjster thanks for submitting this, it should help to figure out what is going on. Since the code seems quite involved, it may take some time to get to the bottom of this, however.

**Comment by stuartarchibald** [comment] 2019-11-27 18:22
This line is likely the problem:
https://github.com/sjster/Numba/blob/master/numba_test.py#L174
it should read:
```python
result[:, :] = res_elem1 + res_elem2
```
such that the value from the addition is assigned back into the memory allocated in the `result` array. At present `result = <new memory>` is probably just making the underlying pointer point to somewhere it shouldn't be, hence no update and weird values.

**Comment by sjster** [comment] 2019-11-28 03:35
Thanks for the pointer and the explanation, this fixed it!

**Comment by esc** [comment] 2019-11-28 08:39
@sjster thanks for confirming, will close the issue now as I believe it is resolved. If you encounter any Numba snags in future please don't hesitate to open an issue! Thanks.

**Closed** 2019-11-28 09:01 UTC
Labels: no action required
