### ISSUE TITLE
PyPI wheels for numba contain incorrect hashes which lead to resolver failure on strict hash checking

### ISSUE THREAD

**Issue by kwlzn** [numba/numba#3665] opened 2019-01-07 23:09 UTC
currently, all versions of `numba` from 0.37.0 (earliest checked) to 0.42.0 (latest checked) for both py2 and py3 have bad hash values for their contents inside of the .whl RECORD files that are distributed on pypi.

for unknown reasons `pip` does not actually check the file hashes for integrity, but other resolvers (like e.g. `pex`) will which can lead to resolve failures. per the wheel spec (PEP 427), these hashes are expected to be verifiable on install.

minimal repro:

```
[omerta show]$ curl -sLO https://github.com/pantsbuild/pex/releases/download/v1.6.0/pex37
[omerta show]$ chmod 700 pex37
[omerta show]$ ./pex37 numba==0.42.0
Traceback (most recent call last):
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 352, in execute
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 397, in _execute
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 495, in execute_entry
  File "/private/tmp/show/pex37/.bootstrap/pex/pex.py", line 510, in execute_pkg_resources
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/bin/pex.py", line 667, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/bin/pex.py", line 600, in build_pex
    pex_builder.add_distribution(resolved_dist.distribution)
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/pex_builder.py", line 336, in add_distribution
    dist_hash = self._add_dist_zip(dist.location, dist_name)
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/pex_builder.py", line 301, in _add_dist_zip
    wf.install(overrides=self._get_installer_paths(whltmp), force=True)
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/vendor/_vendored/wheel/wheel/install.py", line 374, in install
    shutil.copyfileobj(source, destination)
  File "/opt/twitter_mde/package/eepython27/e4cdee382b83e4185a42b54120b1b11021cec1d8285cc9023ef2dabf8c9af24d/lib/python2.7/shutil.py", line 63, in copyfileobj
    buf = fsrc.read(length)
  File "/opt/twitter_mde/package/eepython27/e4cdee382b83e4185a42b54120b1b11021cec1d8285cc9023ef2dabf8c9af24d/lib/python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "/opt/twitter_mde/package/eepython27/e4cdee382b83e4185a42b54120b1b11021cec1d8285cc9023ef2dabf8c9af24d/lib/python2.7/zipfile.py", line 692, in read1
    self._update_crc(data, eof=eof)
  File "/Users/kwilson/.pex/install/pex-1.6.0-py2.py3-none-any.whl.019d39b951e0df9d6d8b58c04f09aeee7ef71226/pex-1.6.0-py2.py3-none-any.whl/pex/vendor/_vendored/wheel/wheel/install.py", line 495, in _update_crc
    raise BadWheelFile("Bad hash for file %r" % ef.name)
pex.vendor._vendored.wheel.wheel.install.BadWheelFile: Bad hash for file 'numba/_dispatcher.so'
```

**Comment by sklam** [comment] 2019-01-08 14:12
That's odd.  The wheels are just made with `python setup.py bdist_wheel` and then repaired with `auditwheel repair` for manylinux1.  We should check the wheels for llvmlite.  I switched to use the manylinux1 docker image from PyPA for that.

**Comment by seibert** [comment] 2019-01-08 14:21
Hunting around for related problems, here's a project where the culprit was stripping the binary and not updating the hash:

https://github.com/grpc/grpc/issues/17409

We aren't doing that, but perhaps there is some other post-processing of the binary happening?

**Comment by sklam** [comment] 2019-01-08 15:39
Ok, I found the cause.  We are patching the .so to adjust the rpaths on osx.

**Comment by sklam** [comment] 2019-01-08 17:40
TODOS: 
- [ ] Need to check our linux wheel building scripts.
- [ ] Do a bugfix release to provide the fixed wheels.

**Comment by kwlzn** [comment] 2019-01-08 23:02
and in case it's helpful as prior art, here's a PR the pytorch folks used to remediate this issue in their wheel builds (due to similar rpath patching): https://github.com/pytorch/builder/pull/6/files

**Comment by sklam** [comment] 2019-02-01 22:54
OSX wheels for llvmlite 0.27.1 and numba 0.42.1 is uploaded to PyPI.  Request for `numba==0.42` should get OSX wheels from 0.42.1, but get 0.42.0 on other platforms.

**Comment by kwlzn** [comment] 2019-02-05 18:48
@sklam thanks a ton!

**Comment by ironfoot** [comment] 2019-03-28 15:07
This is happening again with numba==0.43.1
```
[ironfoot@] pex numba==0.43.1
Traceback (most recent call last):
  File "/Users/ironfoot/miniconda3/envs/dev/bin/pex", line 10, in <module>
    sys.exit(main())
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/pex/bin/pex.py", line 735, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/pex/bin/pex.py", line 667, in build_pex
    pex_builder.add_distribution(resolved_dist.distribution)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/pex/pex_builder.py", line 326, in add_distribution
    dist_hash = self._add_dist_zip(dist.location, dist_name)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/pex/pex_builder.py", line 291, in _add_dist_zip
    wf.install(overrides=self._get_installer_paths(whltmp), force=True)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/wheel/install.py", line 351, in install
    shutil.copyfileobj(source, destination)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/zipfile.py", line 962, in _read1
    self._update_crc(data)
  File "/Users/ironfoot/miniconda3/envs/dev/lib/python3.6/site-packages/wheel/install.py", line 457, in _update_crc
    raise BadWheelFile("Bad hash for file %r" % ef.name)
wheel.install.BadWheelFile: Bad hash for file 'numba/_dispatcher.cpython-36m-darwin.so'
```

But it's fine with numba==0.43.0
```
[ironfoot@] pex numba==0.43.0
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

**Comment by seibert** [comment] 2019-03-28 15:24
@sklam: Can you take a look at this?

**Comment by sklam** [comment] 2019-03-28 15:33
Hmmm... i'm not sure how I messed it up.  The script is correctly using `wheel pack` and `wheel unpack`.

**Comment by sklam** [comment] 2019-03-28 15:44
I found why.  I stupidly logged in to an almost identical machine but with the wrong scripts in it.  Blaming myself to not check `git log`.

**Comment by sklam** [comment] 2019-03-28 16:38
Fixed, incremented build-number, and uploaded for mac wheels.

**Comment by seibert** [comment] 2019-07-03 15:22
closing this issue as it was fixed.

**Closed by seibert** 2019-07-03 15:22 UTC
Labels: wheels
