### ISSUE TITLE
Lowering error

### ISSUE THREAD

**Issue by nblocker** [numba/numba#2576] opened 2017-10-25 18:49 UTC
When executing the following code:

      @jitclass( [('child1', float64)])
      class Myclass(object):
           def __init__(self, child1):
                self.child1=child1
          def apply(self):
               return self.child1

      vop = Myclass(2)

      @vectorize([float64(int64, int64)],target="parallel", nopython=True)
      def foo(s,o): 
          if np.isfinite(s) and np.isfinite(o):
              return vop.apply()
          else:
              return np.nan

I get the following error:

 raise NotImplementedError("cannot lower constant of type '%s'" % (ty,))
 LoweringError: cannot lower constant of type 'instance.jitclass.Myclass#11252600<child1:float64>'
 File "<ipython-input-174-03a839ed45ed>", line 14
 [1] During: lowering "$30.1 = global(vop: <numba.jitclass.boxing.Myclass object at 0x2aab04170c50>)"   at <ipython-input-174-03a839ed45ed> (14)

 Failed at nopython (nopython mode backend)
 cannot lower constant of type `'instance.jitclass.Myclass#11252600<child1:float64>'`

If that may help, when instantiating vop locally inside the foo method as follows, it works fine:

      @vectorize([float64(int64, int64)],target="parallel", nopython=True)
      def foo(s,o): 
         vop = Myclass(2)
          if np.isfinite(s) and np.isfinite(o):
              return vop.apply()
          else:
              return np.nan

**Comment by seibert** [comment] 2017-10-25 18:54
@sklam: Can you take a look at this?  Sounds like we're missing the lowering for a global jitclass, which should probably work the same as a global numpy array.

**Comment by shuraD** [comment] 2017-10-31 11:02
Is there maybe a workaround for that issue, or a local modification in the numba library code I can do in the meantime? 
Thanks

**Comment by seibert** [comment] 2017-10-31 18:59
This is a duplicate of #2501.

**Closed by seibert** 2017-10-31 18:59 UTC
Labels: duplicate
