### ISSUE TITLE
Numba error

### ISSUE THREAD

**Issue by Lzwetsloot** [numba/numba#6638] opened 2021-01-14 16:03 UTC
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~\.conda\envs\vdp\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    716     try:
--> 717         yield
    718     except NumbaError as e:

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_block(self, block)
    259                                    loc=self.loc, errcls_=defaulterrcls):
--> 260                 self.lower_inst(inst)
    261 

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_inst(self, inst)
    302             ty = self.typeof(inst.target.name)
--> 303             val = self.lower_assign(ty, inst)
    304             self.storevar(val, inst.target.name)

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_assign(self, ty, inst)
    464         elif isinstance(value, ir.Expr):
--> 465             return self.lower_expr(ty, value)
    466 

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_expr(self, resty, expr)
    950             castval = self.context.cast(self.builder, val, ty, fty)
--> 951             res = impl(self.builder, (castval,))
    952             res = self.context.cast(self.builder, res, signature.return_type,

~\.conda\envs\vdp\lib\site-packages\numba\targets\base.py in __call__(self, builder, args, loc)
   1131     def __call__(self, builder, args, loc=None):
-> 1132         res = self._imp(self._context, builder, self._sig, args, loc=loc)
   1133         self._context.add_linking_libs(getattr(self, 'libs', ()))

~\.conda\envs\vdp\lib\site-packages\numba\targets\base.py in wrapper(*args, **kwargs)
   1156             kwargs.pop('loc')     # drop unused loc
-> 1157             return fn(*args, **kwargs)
   1158 

~\.conda\envs\vdp\lib\site-packages\numba\targets\imputils.py in wrapper(context, builder, sig, args)
    333             func(context, builder, sig, args,
--> 334                 _IternextResult(context, builder, pairobj))
    335             if ref_type == RefType.NEW:

~\.conda\envs\vdp\lib\site-packages\numba\targets\iterators.py in iternext_zip(context, builder, sig, args, result)
    109         with builder.if_then(is_valid):
--> 110             srcres = call_iternext(context, builder, srcty, iterobj)
    111             is_valid = builder.and_(is_valid, srcres.is_valid())

~\.conda\envs\vdp\lib\site-packages\numba\targets\imputils.py in call_iternext(context, builder, iterator_type, val)
    368     iternext_impl = context.get_function('iternext', iternext_sig)
--> 369     val = iternext_impl(builder, (val,))
    370     pairobj = context.make_helper(builder, pair_type, val)

~\.conda\envs\vdp\lib\site-packages\numba\targets\base.py in __call__(self, builder, args, loc)
   1131     def __call__(self, builder, args, loc=None):
-> 1132         res = self._imp(self._context, builder, self._sig, args, loc=loc)
   1133         self._context.add_linking_libs(getattr(self, 'libs', ()))

~\.conda\envs\vdp\lib\site-packages\numba\targets\base.py in wrapper(*args, **kwargs)
   1156             kwargs.pop('loc')     # drop unused loc
-> 1157             return fn(*args, **kwargs)
   1158 

~\.conda\envs\vdp\lib\site-packages\numba\targets\imputils.py in wrapper(context, builder, sig, args)
    333             func(context, builder, sig, args,
--> 334                 _IternextResult(context, builder, pairobj))
    335             if ref_type == RefType.NEW:

~\.conda\envs\vdp\lib\site-packages\numba\targets\arrayobj.py in iternext_array(context, builder, sig, args, result)
    292         # TODO
--> 293         raise NotImplementedError("iterating over %dD array" % arrayty.ndim)
    294 

NotImplementedError: iterating over 2D array

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-16-5f46731b298a> in <module>
     49 support_domain = 16
     50 
---> 51 mvs.plot_photoconsistency_along_ray(image0, image1, camera0, camera1, point3D, pc_func, support_domain)

~\Documents\Uni\Visual Data Processing\mvs.py in plot_photoconsistency_along_ray(image0, image1, camera0, camera1, point3D, pc_func, support_domain)
    379     # Shoot a ray from camera0 through the pixel. Walk along it in image space (of image1) and compute photo consistency.
    380     pixels, photo_consistency = compute_photo_consistency_along_ray(
--> 381         image0, image1, camera0, camera1, pixel0, pc_func, support_domain)
    382 
    383     if len(pixels) == 0:

~\Documents\Uni\Visual Data Processing\mvs.py in compute_photo_consistency_along_ray(image0, image1, camera0, camera1, pixel0, photo_consistency_function, support_domain)
    291         support0, support1 = get_support_domains_no_bounds_check(
    292             image0, image1, pixel0, pixel1, support_domain)
--> 293         photo_consistency = photo_consistency_function(support0, support1)
    294 
    295         pixels.append(pixel1)

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    418                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    419             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 420             raise e
    421 
    422     def inspect_llvm(self, signature=None):

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    351                 argtypes.append(self.typeof_pyval(a))
    352         try:
--> 353             return self.compile(tuple(argtypes))
    354         except errors.ForceLiteralArg as e:
    355             # Received request for compiler re-entry with the list of arguments

~\.conda\envs\vdp\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    766             self._cache_misses[sig] += 1
    767             try:
--> 768                 cres = self._compiler.compile(args, return_type)
    769             except errors.ForceLiteralArg as e:
    770                 def folded(args, kws):

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     75 
     76     def compile(self, args, return_type):
---> 77         status, retval = self._compile_cached(args, return_type)
     78         if status:
     79             return retval

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in _compile_cached(self, args, return_type)
     89 
     90         try:
---> 91             retval = self._compile_core(args, return_type)
     92         except errors.TypingError as e:
     93             self._failed_cache[key] = e

~\.conda\envs\vdp\lib\site-packages\numba\dispatcher.py in _compile_core(self, args, return_type)
    107                                       args=args, return_type=return_type,
    108                                       flags=flags, locals=self.locals,
--> 109                                       pipeline_class=self.pipeline_class)
    110         # Check typing error if object mode is used
    111         if cres.typing_error is not None and not flags.enable_pyobject:

~\.conda\envs\vdp\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    526     pipeline = pipeline_class(typingctx, targetctx, library,
    527                               args, return_type, flags, locals)
--> 528     return pipeline.compile_extra(func)
    529 
    530 

~\.conda\envs\vdp\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    324         self.state.lifted = ()
    325         self.state.lifted_from = None
--> 326         return self._compile_bytecode()
    327 
    328     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~\.conda\envs\vdp\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    383         """
    384         assert self.state.func_ir is None
--> 385         return self._compile_core()
    386 
    387     def _compile_ir(self):

~\.conda\envs\vdp\lib\site-packages\numba\compiler.py in _compile_core(self)
    363                 self.state.status.fail_reason = e
    364                 if is_final_pipeline:
--> 365                     raise e
    366         else:
    367             raise CompilerError("All available pipelines exhausted")

~\.conda\envs\vdp\lib\site-packages\numba\compiler.py in _compile_core(self)
    354             res = None
    355             try:
--> 356                 pm.run(self.state)
    357                 if self.state.cr is not None:
    358                     break

~\.conda\envs\vdp\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    326                     (self.pipeline_name, pass_desc)
    327                 patched_exception = self._patch_error(msg, e)
--> 328                 raise patched_exception
    329 
    330     def dependency_analysis(self):

~\.conda\envs\vdp\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    317                 pass_inst = _pass_registry.get(pss).pass_inst
    318                 if isinstance(pass_inst, CompilerPass):
--> 319                     self._runPass(idx, pass_inst, state)
    320                 else:
    321                     raise BaseException("Legacy pass in use")

~\.conda\envs\vdp\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\.conda\envs\vdp\lib\site-packages\numba\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    279             mutated |= check(pss.run_initialization, internal_state)
    280         with SimpleTimer() as pass_time:
--> 281             mutated |= check(pss.run_pass, internal_state)
    282         with SimpleTimer() as finalize_time:
    283             mutated |= check(pss.run_finalizer, internal_state)

~\.conda\envs\vdp\lib\site-packages\numba\compiler_machinery.py in check(func, compiler_state)
    266 
    267         def check(func, compiler_state):
--> 268             mangled = func(compiler_state)
    269             if mangled not in (True, False):
    270                 msg = ("CompilerPass implementations should return True/False. "

~\.conda\envs\vdp\lib\site-packages\numba\typed_passes.py in run_pass(self, state)
    378             state.library.enable_object_caching()
    379 
--> 380         NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
    381         lowered = state['cr']
    382         signature = typing.signature(state.return_type, *state.args)

~\.conda\envs\vdp\lib\site-packages\numba\typed_passes.py in run_pass(self, state)
    323                 lower = lowering.Lower(targetctx, library, fndesc, interp,
    324                                        metadata=metadata)
--> 325                 lower.lower()
    326                 if not flags.no_cpython_wrapper:
    327                     lower.create_cpython_wrapper(flags.release_gil)

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower(self)
    177         if self.generator_info is None:
    178             self.genlower = None
--> 179             self.lower_normal_function(self.fndesc)
    180         else:
    181             self.genlower = self.GeneratorLower(self)

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_normal_function(self, fndesc)
    218         # Init argument values
    219         self.extract_function_arguments()
--> 220         entry_block_tail = self.lower_function_body()
    221 
    222         # Close tail of entry block

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_function_body(self)
    243             bb = self.blkmap[offset]
    244             self.builder.position_at_end(bb)
--> 245             self.lower_block(block)
    246 
    247         self.post_lower()

~\.conda\envs\vdp\lib\site-packages\numba\lowering.py in lower_block(self, block)
    258             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    259                                    loc=self.loc, errcls_=defaulterrcls):
--> 260                 self.lower_inst(inst)
    261 
    262     def create_cpython_wrapper(self, release_gil=False):

~\.conda\envs\vdp\lib\contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~\.conda\envs\vdp\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    723         from numba import config
    724         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 725         six.reraise(type(newerr), newerr, tb)
    726 
    727 

~\.conda\envs\vdp\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    667         if value.__traceback__ is not tb:
    668             raise value.with_traceback(tb)
--> 669         raise value
    670 
    671 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
iterating over 2D array

File "<ipython-input-16-5f46731b298a>", line 6:
def photo_consistency_SSD(support0, support1):
    <source elided>
    SS = 0
    for it, jt in zip (support0, support1):
    ^

[1] During: lowering "$16.2 = iternext(value=$phi16.1)" at <ipython-input-16-5f46731b298a> (6)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment] 2021-01-14 16:13
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (so we can just do `python bug.py` to reproduce the problem).
2. Any data needed to run the code.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

**Comment by stuartarchibald** [comment] 2021-01-25 10:36
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2021-01-25 10:36 UTC
Labels: more info needed
