### ISSUE TITLE
mssa.fit()出错

### ISSUE THREAD

**Issue by xiaobai12321** [numba/numba#6134] opened 2020-08-15 10:11 UTC
LoweringError: Failed at nopython (nopython mode backend)
Operands must be the same type, got (i64, i32)

File "Anaconda3\lib\site-packages\pymssa\optimized.py", line 226:
def incremental_component_reconstruction(trajectory_matrix,
    <source elided>

    components = np.zeros((P, N, rank))
    ^
[1] During: lowering "$0.7 = call $0.2($0.6, func=$0.2, args=[Var($0.6, C:\Users\Administrator\Anaconda3\lib\site-packages\pymssa\optimized.py (226))], kws=(), vararg=None)" at C:\Users\Administrator\Anaconda3\lib\site-packages\pymssa\optimized.py (226)

**Comment by esc** [comment] 2020-08-17 08:34
@xiaobai12321 thanks for submitting this. Unfortunately there is not enough information in this ticket to be able to reproduce the error you are seeing. Please follow the guidelines at:

https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

to create a minimum working reproducer so that we can debug this issue further.

**Comment by stuartarchibald** [comment] 2020-08-17 08:41
Probably a duplicate of https://github.com/numba/numba/issues/3910 and https://github.com/numba/numba/issues/5208.

**Comment by stuartarchibald** [comment] 2020-09-02 09:41
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-09-02 09:41 UTC
Labels: more info needed
