### ISSUE TITLE
Bound checking for array indexing

### ISSUE THREAD

**Issue by sklam** [numba/numba#730] opened 2014-08-26 18:15 UTC

**Comment by seibert** [comment] 2015-07-29 21:20
+1 from the mailing list on this.  :)

One thing we need to decide is how to handle adding more compiler flags, like "boundscheck".  Do we want to keep throwing them into the JIT decorator as keyword arguments?

**Comment by ovillellas** [comment] 2015-07-30 10:14
IMO, having a single keyword for flags that takes some dictionary could be an option.

Then have a way to set default flags for all numba functions. Merging the default flag with any explicit falg in any jit function. Maybe even reading the initial default compile flags from the environment. The idea being that it will be really useful to be able to set common flags for a whole program, but also tweak flags for a particular function.

I also think that not using specific keywords for compiler options allows better error handling: an unsupported compiler option could just be warned about or ignored, instead of giving hard errors.

An extra nicety would be that being able to get the default compile flags would provide a reference of the available flags (as long as the list is exahustive... that is, disabled options appear in the flags, but "disabled").

**Comment by complyue** [comment] 2017-08-09 07:02
+1 for I came across the same situation as the mail list posting. When seg fault could appear after small amount of data throughput, disabling jit is quite useful, but when the bug is only reproducible after fair huge amount of data passed through, it's real productivity killer.

**Comment by syphax** [comment] 2017-08-11 20:24
I'd love to have array index bound checking as a debug option. I arrived here after having just found a subtle out-of-bounds indexing bug. As mentioned, disabling jit enables bound checking (among other things), but is sometimes too slow to be practical (because numba is so amazing at speeding up code).

By the way, older versions of numba docs (v0.15) [explicitly call out](http://numba.pydata.org/numba-doc/0.15.1/arrays.html) the no bounds checking issue; the current version (0.34.0) does not.

**Comment by seibert** [comment] 2017-08-14 14:18
Yes, this is something we want to bring back.  Now that we have a debug mode (which still compiles stuff, but disables compiler optimizations and inserts GDB line information), that seems like a natural place to also want bounds checking.

**Comment by theindigamer** [comment] 2017-12-13 23:59
Is out of bounds access undefined behaviour? Or is guaranteed to read/write regardless? Maybe I missed this in the docs ... IMO, this should be documented on the [@jit](https://numba.pydata.org/numba-doc/0.36.1/user/jit.html) page as a WARNING!, if not elsewhere.

**Comment by sklam** [comment] 2019-08-06 18:50
@asmeurer, This is how you raise an exception with the IRBuilder.
https://github.com/numba/numba/blob/c3eb9867545e4e57c5ffe7b7d427de78f21223a6/numba/cgutils.py#L785

**Comment by stuartarchibald** [comment] 2021-12-15 10:38
Closing as implemented in https://github.com/numba/numba/pull/4432.

**Closed by stuartarchibald** 2021-12-15 10:38 UTC
Labels: enhancement
