### ISSUE TITLE
Builtin function "map" produces memory leak

### ISSUE THREAD

**Issue by Trizalio** [numba/numba#8367] opened 2022-08-18 11:14 UTC
I am using the latest [stable] released version of Numba '0.56.0'
Code sample to reproduce the problem:
```python
import numba

@numba.njit
def leak():
    map(int, [1])

leak()
print(numba.core.runtime.rtsys.get_allocation_stats())
```
Longer sample shows refcount leak:
```python
import sys
import numpy
import numba

@numba.njit
def leak(arr: numpy.ndarray):
    map(int, arr)

zeros = numpy.zeros(3)
print(sys.getrefcount(zeros))  # 2
leak(zeros)
print(sys.getrefcount(zeros))  # 3
del zeros
print(numba.core.runtime.rtsys.get_allocation_stats())
```
My real world use case:
```python
@numba.njit('types.unicode_type(i4[:])')
def ndarray_to_str(arr: numpy.ndarray):
    return f'[{",".join(map(str, arr))}]'  # leaks
```

**Comment by stuartarchibald** [comment] 2022-08-18 15:18
Thanks for the report. Think this might be a duplicate of https://github.com/numba/numba/issues/6236 ?

**Comment by Trizalio** [comment] 2022-08-19 09:03
Sure it is. Sorry, that i made a duplicate. Somehow i didn't found that one =(

**Comment by gmarkall** [comment] 2022-08-19 10:50
No problem :slightly_smiling_face:! I'll close this issue.

**Closed by gmarkall** 2022-08-19 10:50 UTC
Labels: duplicate
