### ISSUE TITLE
Issue lowering `ir.StaticSetItem`

### ISSUE THREAD

**Issue by maryam69898895** [numba/numba#4392] opened 2019-08-01 14:12 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by maryam69898895** [comment] 2019-08-01 14:15
Hello. I am running  a code for pose estimation. I get this error: 

 @jit Process _Worker-4: Process _Worker-5: Traceback (most recent call last):   File "/home/maryam/.local/lib/python3.5/site-packages/numba/errors.py", line 661, in new_error_context     yield   File "/home/maryam/.local/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block     self.lower_inst(inst)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/pylowering.py", line 176, in lower_inst     raise NotImplementedError(type(inst), inst) NotImplementedError: (<class 'numba.ir.StaticSetItem'>, heatmap.1[(slice(None, None, None), slice(None, None, None), -1)] = $151.17)  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap     self.run()   File "/home/maryam/.local/lib/python3.5/site-packages/tensorpack/dataflow/parallel.py", line 173, in run     for dp in self.ds:   File "/home/maryam/.local/lib/python3.5/site-packages/tensorpack/dataflow/common.py", line 293, in __iter__     ret = self.func(copy(dp))  # shallow copy the list   File "/home/maryam/Downloads/tf-pose-estimation-master/tf_pose/pose_augment.py", line 263, in pose_to_img     meta_l[0].get_heatmap(target_size=(_network_w // _scale, _network_h // _scale)),   File "/home/maryam/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 370, in _compile_for_args     raise e   File "/home/maryam/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 327, in _compile_for_args     return self.compile(tuple(argtypes))   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock     return func(*args, **kwargs)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 659, in compile     cres = self._compiler.compile(args, return_type)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 83, in compile     pipeline_class=self.pipeline_class)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 955, in compile_extra     return pipeline.compile_extra(func)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 377, in compile_extra     return self._compile_bytecode()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 886, in _compile_bytecode     return self._compile_core()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 873, in _compile_core     res = pm.run(self.status)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock     return func(*args, **kwargs)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 254, in run     raise patched_exception   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 245, in run     stage()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 463, in stage_objectmode_frontend     cres = self.frontend_looplift()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 435, in frontend_looplift     lifted=tuple(loops), lifted_from=None)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 1017, in compile_ir     lifted_from=lifted_from)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 385, in compile_ir     return self._compile_ir()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 893, in _compile_ir     return self._compile_core()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 873, in _compile_core     res = pm.run(self.status)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock     return func(*args, **kwargs)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 254, in run     raise patched_exception   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 245, in run     stage()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 711, in stage_objectmode_backend     self._backend(lowerfn, objectmode=True)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 687, in _backend     lowered = lowerfn()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 659, in backend_object_mode     self.flags)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/compiler.py", line 1148, in py_lowering_stage     lower.lower()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/lowering.py", line 177, in lower     self.lower_normal_function(self.fndesc)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/lowering.py", line 218, in lower_normal_function     entry_block_tail = self.lower_function_body()   File "/home/maryam/.local/lib/python3.5/site-packages/numba/lowering.py", line 243, in lower_function_body     self.lower_block(block)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block     self.lower_inst(inst)   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__     self.gen.throw(type, value, traceback)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/errors.py", line 669, in new_error_context     six.reraise(type(newerr), newerr, tb)   File "/home/maryam/.local/lib/python3.5/site-packages/numba/six.py", line 659, in reraise     raise value numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend) Failed in object mode pipeline (step: object mode backend) (<class 'numba.ir.StaticSetItem'>, heatmap.1[(slice(None, None, None), slice(None, None, None), -1)] = $151.17)  File "tf_pose/pose_dataset.py", line 120:     def get_heatmap(self, target_size):         <source elided>         # background         heatmap[:, :, -1] = np.clip(1 - np.amax(heatmap, axis=2), 0.0, 1.0)         ^  [1] During: lowering "heatmap.1[(slice(None, None, None), slice(None, None, None), -1)] = $151.17" at /home/maryam/Downloads/tf-pose-estimation-master/tf_pose/pose_dataset.py (120) ------------------------------------------------------------------------------- This should not have happened, a problem has occurred in Numba's internals.  Please report the error message and traceback, along with a minimal reproducer at: https://github.com/numba/numba/issues/new  If more help is needed please feel free to speak to the Numba core developers directly at: https://gitter.im/numba/numba  Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment] 2019-08-01 14:53
Thanks for the report. I have formatted your code to help make it more readable. RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment] 2019-08-01 14:56
I think this issue was fixed in Numba 0.45.0, please could you update your Numba version to 0.45 and see if the problem is still present? Thanks.

**Comment by maryam69898895** [comment] 2019-08-01 15:21
Thanks for reply. I updated numba to 0.45 but I get the same issue.

**Comment by stuartarchibald** [comment] 2019-08-01 15:27
Thanks for trying 0.45. Do you have a piece of code you could share that reproduces this issue please? Thanks.

**Comment by maryam69898895** [comment] 2019-08-01 15:34
Yes. 
        # logger.debug('joint size=%d' % len(self.joint_list))

    @jit
    def get_heatmap(self, target_size):
        heatmap = np.zeros((CocoMetadata.__coco_parts, self.height, self.width), dtype=np.float32)

        for joints in self.joint_list:
            for idx, point in enumerate(joints):
                if point[0] < 0 or point[1] < 0:
                    continue
                CocoMetadata.put_heatmap(heatmap, idx, point, self.sigma)

        heatmap = heatmap.transpose((1, 2, 0))

        # background
        heatmap[:, :, -1] = np.clip(1 - np.amax(heatmap, axis=2), 0.0, 1.0)

        if target_size:
            heatmap = cv2.resize(heatmap, target_size, interpolation=cv2.INTER_AREA)

        return heatmap.astype(np.float16)

**Comment by stuartarchibald** [comment] 2019-08-01 15:45
Thanks. Two things:

1. That code is the cause of the issue but unfortunately without input data or definitions for e.g. `CocoMetadata` etc it's going to be possible to reproduce what you are seeing. Please could you try and create a self contained example such that e.g. `python example.py` just works and produces the problem above. Thanks.
2. It looks like your code might be a good fit for Numba with some additional effort. Using `@jit` by itself is not recommended. If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment] 2019-09-11 14:53
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:53 UTC
Labels: no action required
