### ISSUE TITLE
pop() method of the typed list of typed list crashes on numba 0.49

### ISSUE THREAD

**Issue by Rinoahu** [numba/numba#5814] opened 2020-06-03 17:39 UTC
## Reporting a bug
Dear Sir or Madam,

I found the pop() method of the typted list of typed list caused a crash on numba 0.49. The code I tested is shown as below:
```python
import numba as nb

@nb.njit
def test_0(n):
    x = nb.typed.List.empty_list(nb.typed.List.empty_list(nb.int32))
    for i in range(n):
        j = nb.typed.List.empty_list(nb.int32)
        for k in range(i, i+5):
            j.append(k)
        x.append(j)


    while len(x) > 0:
        y = x.pop()
    return x

@nb.njit
def test_1(n):
    x = nb.typed.Dict()
    for i in range(n):
        j = nb.typed.List.empty_list(nb.int32)
        for k in range(i, i+5):
            j.append(k)
        x[i] = j

    while len(x) > 0:
        y = x.popitem()
    return x

test_0(10**6)
test_1(10**6)
```
test_0 function crashed on numba 0.49. However, if using typed Dict instead of typed List, it (test_1 function) works.

**Comment by stuartarchibald** [comment] 2020-06-04 09:27
Thanks for the report, I think this is a duplicate of https://github.com/numba/numba/issues/5787 and was fixed by https://github.com/numba/numba/pull/5602. I cannot reproduce this problem on the `master` branch and Numba 0.50 (out in about a week's time) will contain this fix.

**Closed by stuartarchibald** 2020-06-04 09:27 UTC
