### ISSUE TITLE
jitclass test failure in longlabel_not_truncated: LLVM use of undefined value

### ISSUE THREAD

**Issue by drew-parsons** [numba/numba#5771] opened 2020-05-29 02:24 UTC
- [ 0.49.1] I am using the latest released version of Numba
- [y] I have included below a minimal working reproducer

test_jitclass_longlabel_not_truncated in numba.tests.test_jitclasses is failing, apparently due to a LLVM IR parsing error with use of undefined value.

This is on debian unstable, with 
* numba 0.49.1
* llvmlite 0.32.0
* llvm 8.0.1

The failure happens with `python3 -Wd -m numba.runtests -v -m`
but can be invoked directly with

    python3 -c "import numba.tests.test_jitclasses as tjc; jit_test=tjc.TestJitClass(); jit_test.test_jitclass_longlabel_not_truncated()"

The full error message is

    $ python3 -c "import numba.tests.test_jitclasses as tjc; jit_test=tjc.TestJitClass(); jit_test.test_jitclass_longlabel_not_truncated()"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/numba/tests/test_jitclasses.py", line 911, in test_jitclass_longlabel_not_truncated
        TruncatedLabel().meth2()
      File "/usr/lib/python3/dist-packages/numba/experimental/jitclass/boxing.py", line 60, in wrapper
        return method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
        error_rewrite(e, 'typing')
      File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 344, in error_rewrite
        reraise(type(e), e, None)
      File "/usr/lib/python3/dist-packages/numba/core/utils.py", line 80, in reraise
        raise value.with_traceback(tb)
    numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Failed in nopython mode pipeline (step: nopython frontend)
    Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f340e236f70>.
    Failed in nopython mode pipeline (step: nopython mode backend)
    LLVM IR parsing error
    <string>:152:12: error: use of undefined value '%_ZN5numba5tests15test_jitclasses12TestJitClass37test_jitclass_longlabel_not_truncated12$3clocals$3e14TruncatedLabel10meth1$2461EN8instance8jitclass1228TruncatedLabel$237f343c4629a0$3caaaaaaaaaa$3afloat64$2cbbbbbbbbbb$3afloat64$2ccccccccccc$3afloat64$2cdddddddddd$3afloat64$2ceeeeeeeeee$3afloat64$2cffffffffff$3afloat64$2cgggggggggg$3afloat64$2chhhhhhhhhh$3afloat64$2ciiiiiiiiii$3afloat64$2cjjjjjjjjjj$3afloat64$2ckkkkkkkkkk$3afloat64$2cllllllllll$3afloat64$2cmmmmmmmmmm$3afloat64$2cnnnnnnnnnn$3afloat64$2coooooooooo$3afloat64$2cpppppppppp$3afloat64$2cqqqqqqqqqq$3afloat64$2crrrrrrrrrr$3afloat64$2cssssssssss$3afloat64$2ctttttttttt$3afloat64$2cuuuuuuuuuu$3afloat64$2cvvvvvvvvvv$3afloat64$2cwwwwwwwwww$3afloat64$2cxxxxxxxxxx$3afloat64$2cyyyyyyyyyy$3afloat64$2czzzzzzzzzz$3afloat64$2cAAAAAAAAAA$3afloat64$2cBBBBBBBBBB$3afloat64$2cCCCCCCCCCC$3afloat64$2cDDDDDDDDDD$3afloat64$2cEEEEEEEEEE$3afloat64$2cFFFFFFFFFF$3afloat64$2cGGGGGGGGGG$3afloat64$2cHHHHHHHHHH$3afloat64$2cIIIIIIIIII$3afloat64$2cJJJJJJJJJJ$3afloat64$2cKKKKKKKKKK$3a4'
      br label %"_ZN5numba5tests15test_jitclasses12TestJitClass37test_jitclass_longlabel_not_truncated12$3clocals$3e14TruncatedLabel10meth1$2461EN8instance8jitclass1228TruncatedLabel$237f343c4629a0$3caaaaaaaaaa$3afloat64$2cbbbbbbbbbb$3afloat64$2ccccccccccc$3afloat64$2cdddddddddd$3afloat64$2ceeeeeeeeee$3afloat64$2cffffffffff$3afloat64$2cgggggggggg$3afloat64$2chhhhhhhhhh$3afloat64$2ciiiiiiiiii$3afloat64$2cjjjjjjjjjj$3afloat64$2ckkkkkkkkkk$3afloat64$2cllllllllll$3afloat64$2cmmmmmmmmmm$3afloat64$2cnnnnnnnnnn$3afloat64$2coooooooooo$3afloat64$2cpppppppppp$3afloat64$2cqqqqqqqqqq$3afloat64$2crrrrrrrrrr$3afloat64$2cssssssssss$3afloat64$2ctttttttttt$3afloat64$2cuuuuuuuuuu$3afloat64$2cvvvvvvvvvv$3afloat64$2cwwwwwwwwww$3afloat64$2cxxxxxxxxxx$3afloat64$2cyyyyyyyyyy$3afloat64$2czzzzzzzzzz$3afloat64$2cAAAAAAAAAA$3afloat64$2cBBBBBBBBBB$3afloat64$2cCCCCCCCCCC$3afloat64$2cDDDDDDDDDD$3afloat64$2cEEEEEEEEEE$3afloat64$2cFFFFFFFFFF$3afloat64$2cGGGGGGGGGG$3afloat64$2cHHHHHHHHHH$3afloat64$2cIIIIIIIIII$3afloat64$2cJJJJJJJJJJ$3afloat64$2cKKKKKKKKKK$3a4"
               ^
    
    [1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'meth1') for instance.jitclass.TruncatedLabel#7f343c4629a0<aaaaaaaaaa:float64,bbbbbbbbbb:float64,cccccccccc:float64,dddddddddd:float64,eeeeeeeeee:float64,ffffffffff:float64,gggggggggg:float64,hhhhhhhhhh:float64,iiiiiiiiii:float64,jjjjjjjjjj:float64,kkkkkkkkkk:float64,llllllllll:float64,mmmmmmmmmm:float64,nnnnnnnnnn:float64,oooooooooo:float64,pppppppppp:float64,qqqqqqqqqq:float64,rrrrrrrrrr:float64,ssssssssss:float64,tttttttttt:float64,uuuuuuuuuu:float64,vvvvvvvvvv:float64,wwwwwwwwww:float64,xxxxxxxxxx:float64,yyyyyyyyyy:float64,zzzzzzzzzz:float64,AAAAAAAAAA:float64,BBBBBBBBBB:float64,CCCCCCCCCC:float64,DDDDDDDDDD:float64,EEEEEEEEEE:float64,FFFFFFFFFF:float64,GGGGGGGGGG:float64,HHHHHHHHHH:float64,IIIIIIIIII:float64,JJJJJJJJJJ:float64,KKKKKKKKKK:float64,LLLLLLLLLL:float64,MMMMMMMMMM:float64,NNNNNNNNNN:float64,OOOOOOOOOO:float64,PPPPPPPPPP:float64,QQQQQQQQQQ:float64,RRRRRRRRRR:float64,SSSSSSSSSS:float64,TTTTTTTTTT:float64,UUUUUUUUUU:float64,VVVVVVVVVV:float64,WWWWWWWWWW:float64,XXXXXXXXXX:float64,YYYYYYYYYY:float64,ZZZZZZZZZZ:float64>)
    [2] During: typing of call at /usr/lib/python3/dist-packages/numba/tests/test_jitclasses.py (908)
    
    Enable logging at debug level for details.
    
    File "../../../../../../usr/lib/python3/dist-packages/numba/tests/test_jitclasses.py", line 908:
                def meth2(self):
                    self.meth1()
                    ^
    
    [1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'meth2') for instance.jitclass.TruncatedLabel#7f343c4629a0<aaaaaaaaaa:float64,bbbbbbbbbb:float64,cccccccccc:float64,dddddddddd:float64,eeeeeeeeee:float64,ffffffffff:float64,gggggggggg:float64,hhhhhhhhhh:float64,iiiiiiiiii:float64,jjjjjjjjjj:float64,kkkkkkkkkk:float64,llllllllll:float64,mmmmmmmmmm:float64,nnnnnnnnnn:float64,oooooooooo:float64,pppppppppp:float64,qqqqqqqqqq:float64,rrrrrrrrrr:float64,ssssssssss:float64,tttttttttt:float64,uuuuuuuuuu:float64,vvvvvvvvvv:float64,wwwwwwwwww:float64,xxxxxxxxxx:float64,yyyyyyyyyy:float64,zzzzzzzzzz:float64,AAAAAAAAAA:float64,BBBBBBBBBB:float64,CCCCCCCCCC:float64,DDDDDDDDDD:float64,EEEEEEEEEE:float64,FFFFFFFFFF:float64,GGGGGGGGGG:float64,HHHHHHHHHH:float64,IIIIIIIIII:float64,JJJJJJJJJJ:float64,KKKKKKKKKK:float64,LLLLLLLLLL:float64,MMMMMMMMMM:float64,NNNNNNNNNN:float64,OOOOOOOOOO:float64,PPPPPPPPPP:float64,QQQQQQQQQQ:float64,RRRRRRRRRR:float64,SSSSSSSSSS:float64,TTTTTTTTTT:float64,UUUUUUUUUU:float64,VVVVVVVVVV:float64,WWWWWWWWWW:float64,XXXXXXXXXX:float64,YYYYYYYYYY:float64,ZZZZZZZZZZ:float64>)
    [2] During: typing of call at <string> (3)
    
    [3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'meth2') for instance.jitclass.TruncatedLabel#7f343c4629a0<aaaaaaaaaa:float64,bbbbbbbbbb:float64,cccccccccc:float64,dddddddddd:float64,eeeeeeeeee:float64,ffffffffff:float64,gggggggggg:float64,hhhhhhhhhh:float64,iiiiiiiiii:float64,jjjjjjjjjj:float64,kkkkkkkkkk:float64,llllllllll:float64,mmmmmmmmmm:float64,nnnnnnnnnn:float64,oooooooooo:float64,pppppppppp:float64,qqqqqqqqqq:float64,rrrrrrrrrr:float64,ssssssssss:float64,tttttttttt:float64,uuuuuuuuuu:float64,vvvvvvvvvv:float64,wwwwwwwwww:float64,xxxxxxxxxx:float64,yyyyyyyyyy:float64,zzzzzzzzzz:float64,AAAAAAAAAA:float64,BBBBBBBBBB:float64,CCCCCCCCCC:float64,DDDDDDDDDD:float64,EEEEEEEEEE:float64,FFFFFFFFFF:float64,GGGGGGGGGG:float64,HHHHHHHHHH:float64,IIIIIIIIII:float64,JJJJJJJJJJ:float64,KKKKKKKKKK:float64,LLLLLLLLLL:float64,MMMMMMMMMM:float64,NNNNNNNNNN:float64,OOOOOOOOOO:float64,PPPPPPPPPP:float64,QQQQQQQQQQ:float64,RRRRRRRRRR:float64,SSSSSSSSSS:float64,TTTTTTTTTT:float64,UUUUUUUUUU:float64,VVVVVVVVVV:float64,WWWWWWWWWW:float64,XXXXXXXXXX:float64,YYYYYYYYYY:float64,ZZZZZZZZZZ:float64>)
    [4] During: typing of call at <string> (3)
    
    
    File "<string>", line 3:
    <source missing, REPL/exec in use?>
    
    $ echo $?
    1

**Comment by esc** [comment] 2020-05-29 09:00
@RizzerOnGitHub thanks for reporting this. I am unable to reproduce this, but then again I am on a Mac using Numba `master`, a development build of `llvmlite` and `miniconda/conda`  as package manager -- so perhaps that isn't too surprising. 

Without looking into this further, my best guess is that the LLVM you are using is unfortunately not the  LLVM that llvmlite needs. Specifically, the FAQ entry here:

https://llvmlite.readthedocs.io/en/latest/faqs.html#why-static-linking-to-llvm

points in this direction:


```
2. The LLVM shipped by most Linux distributions is not the version llvmlite needs - The release cycles of Linux distributions will never line up with LLVM or llvmlite releases.

3. We need to patch LLVM - The binary packages of llvmlite are built against LLVM with a handful of patches to either fix bugs or to add features that have not yet been merged upstream. In some cases, we’ve had to carry patches for several releases before they make it into LLVM.
```

As a temporary workaround I would suggest to try using the Numba and llvmlite packages from anaconda.org which are available via `miniconda/conda`, if that is an option.

**Comment by esc** [comment] 2020-05-29 09:06
Going further, there is a way to verify the hypothesis of llvmlite/LLVM mismatch in:

https://github.com/numba/numba/issues/3876

Specifically the suggestion in:

https://github.com/numba/numba/issues/3876#issuecomment-473886851

**Comment by RizzerOnGitHub** [comment] 2020-05-29 09:19
That's a good assessment, thanks @esc .  If I inject

    from llvmlite import binding
    binding.set_option("tmp", "-non-global-value-max-name-size=2048")

into test_jitclasses.py then the test passes cleanly.

I'll keep watch on https://github.com/numba/numba/pull/4373,
though one could argue if the problem can be fixed at run time then perhaps llvm doesn't need a patch.

**Comment by esc** [comment] 2020-05-29 10:41
@RizzerOnGitHub thanks for following up! And do let us know how it goes.

**Comment by stuartarchibald** [comment] 2020-05-29 17:15
> That's a good assessment, thanks @esc . If I inject
> 
> ```
> from llvmlite import binding
> binding.set_option("tmp", "-non-global-value-max-name-size=2048")
> ```
> 
> into test_jitclasses.py then the test passes cleanly.
> 
> I'll keep watch on #4373, we can apply it in Debian.

The patch in question is a reversion of LLVM mainline's https://reviews.llvm.org/D41296. The merits of not reverting and other fixes have been discussed quite a bit, some people very for keeping LLVM as is, other's concerned about it https://reviews.llvm.org/D41296#1607582.

**Comment by RizzerOnGitHub** [comment] 2020-05-29 17:42
If it's as simple as that to configure in a client program, then I can understand why some people mightn't want to fiddle with llvm. Even with numba, you could just patch test_jitclasses.py where it's known to be needed, and leave __init__.py with the llvm default value. I guess it depends how often these long name limits are hit, how likely it might happen in the middle of a production calculation.

**Comment by stuartarchibald** [comment] 2020-06-01 09:55
> I guess it depends how often these long name limits are hit, how likely it might happen in the middle of a production calculation.

It's this which is incredibly hard to determine. Also setting state in LLVM from the llvmlite dynamic shared object is notoriously hard to get right.

**Comment by stuartarchibald** [comment] 2022-01-04 14:58
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2022-01-04 14:58 UTC
Labels: llvm
