### ISSUE TITLE
Numpy argmin not compiling

### ISSUE THREAD

**Issue by h-g-s** [numba/numba#4966] opened 2019-12-14 15:01 UTC
## Reporting a bug

- [ X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ X ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

"""Selects the best branching for a dataset"""
from typing import List
from sys import stdout as out, stderr as err
from math import ceil
from numpy import array, intc, ndarray, zeros, amin, float64, argmin
from numpy import sort, empty
import numpy as np
import numba as nb
from algsel import AlgSel
import parameters as param

#  compatible with numpy limits
oo = 2399999999

# set true for debugging
VERBOSE = False

class Branch:
    """information describing a branching in the dataset"""

    def __init__(self,
                 els: ndarray,  # elements in this branch
                 i: int,  # position in els where the split happens
                 # multivariate branching can have multiple features
                 # with different weights
                 ifeats: List[int],  # list of features indexes
                 nfeats: List[str],  # list of feature names
                 ifeatw: List[float],  # feature weights
                 value: float,  # branch value
                 cost: float,  # cost of this branching
                 best_alg: List[int]):  # best alg per child node
        assert len(ifeats) == len(ifeatw)
        self.els = els.copy()
        self.i = i
        self.ifeats = ifeats.copy()
        self.nfeats = nfeats.copy()
        self.ifeatw = ifeatw.copy()
        self.value = value
        self.cost = cost
        self.best_alg = best_alg.copy()

    def print(self):
        out.write('branching: feats, weights: [')
        for i, ifeat in enumerate(self.ifeats):
            out.write('(%d, %g) ' % (ifeat, self.ifeatw[i]))
        out.write('], value: %g cost %g, best algs: [%d, %d]\n' % (self.value,
                                                                   self.cost,
                                                                   self.best_alg[0],
                                                                   self.best_alg[1]))

    def better(self, other):
        return self.cost <= other.cost-1e-15

    def check(self, asds: AlgSel, verbose=True):
        if verbose:
            print("checking branch.")
            out.write("features and weights [")
            for i, f in enumerate(self.ifeats):
                if i:
                    out.write(" ")
                out.write("(%d %s, %g)" %
                          (f, asds.features[f], self.ifeatw[i]))
            out.write("\n")
            print("branch value: %g" % self.value)
        elsleft = [self.els[i] for i in range(0, self.i+1)]
        elsright = [self.els[i] for i in range(self.i+1, len(self.els))]
        if verbose:
            print("instances at left:")
        mfeat = asds.mfeat

        # summation of time for each algorithm in each partition
        p1, p2 = zeros(asds.na, dtype=float64), zeros(asds.na, dtype=float64)
        for i in elsleft:
            val_inst = sum(mfeat[i][self.ifeats[j]]*self.ifeatw[j]
                           for j in range(len(self.ifeatw)))
            if val_inst >= self.value + 1e-10:
                err.write("instance %d %s has value %g and is allocated at left\n" % (
                    i, asds.instances[i], val_inst))
                exit(1)
            for a in range(asds.na):
                p1[a] += asds.mres[i][a]
            if verbose:
                print("instance %d %s value: %g" %
                      (i, asds.instances[i], val_inst))

        best_a1 = argmin(p1)
        if best_a1 != self.best_alg[0]:
            err.write('in partition 1 the best algorithm should be %d %s\n' % (
                best_a1, asds.algs[best_a1]))
            exit(1)

        if verbose:
            print()
            print("second partition")
        for i in elsright:
            val_inst = sum(mfeat[i][self.ifeats[j]]*self.ifeatw[j]
                           for j in range(len(self.ifeatw)))
            if val_inst <= self.value - 1e-10:
                err.write("instance %d %s has value %g and is allocated at right\n" % (
                    i, asds.instances[i], val_inst))
                exit(1)
            for a in range(asds.na):
                p2[a] += asds.mres[i][a]

            if verbose:
                print("instance %d %s value: %g" %
                      (i, asds.instances[i], val_inst))

        best_a2 = argmin(p2)
        if best_a2 != self.best_alg[1]:
            err.write('in partition 2 the best . should be %d %s \n' % (
                best_a2, asds.algs[best_a2]))
            # exit(1)

        if verbose:
            print("expected branch cost: %g" %
                  ((p1[best_a1]+p2[best_a2]) / len(self.els)))
            print()

    def as_dict(self):
        if not self.ifeatw:
            return {"branch": None}
        return {
            "features": [nm for nm in self.nfeats],
            "weights": [w for w in self.ifeatw],
            "value": self.value
        }

# adds results of one element to partition
@nb.jit((nb.intc, nb.float64[:], nb.intc, nb.float64[:, :]), nopython=True)
def add_els_part(na,  # number of algorithms
                 resa,  # results partition
                 el,  # element
                 mres):  # complete results
    for ia in range(na):
        resa[ia] += mres[int(el)][int(ia)]

# removes results of one element to partition
@nb.jit((nb.intc, nb.float64[:], nb.intc, nb.float64[:, :]), nopython=True)
def rem_els_part(na,  # number of algorithms
                 resa,  # results partition
                 el,  # element
                 mres):  # complete results
    for ia in range(na):
        resa[ia] -= mres[int(el)][int(ia)]

@nb.jit((nb.intc,  # na
         nb.float64[:, :],  # fvs
         nb.float64[:, :],  # mres
         nb.float64[:],  # outf
         nb.float64[:],  # p1
         nb.float64[:]),  # p2
        nopython=True)
def best_branch_feature(na,  # number of algorithms
                        fvs,  # sort.elements [inst_idx, feat_value]
                        mres,  # results insts x algs
                        outf,  # branchidx, cost, best alg left, best alg right
                        p1,  # algorithm's cost in p1
                        p2  # algorithm's cost in p2
                        ):
    outf[0], outf[1], nels = -1, oo, len(fvs)

    p1.fill(0)
    p2.fill(0)
    for i in range(0, nels):
        add_els_part(na, p2, fvs[i][0], mres)

    iidxa1 = 0
    iidxa2 = 0

    for i in range(0, nels-1):
        add_els_part(na, p1, fvs[i][0], mres)
        rem_els_part(na, p2, fvs[i][0], mres)

        if (abs(fvs[i][1] - fvs[i+1][1]) >= param.MIN_DIF_FV
            and i >= param.MIN_INST_NODE
                and nels-i >= param.MIN_INST_NODE):
            iidxa1 = argmin(p1)
            iidxa2 = argmin(p2)

            cost = (p1[iidxa1] + p2[iidxa2]) / len(fvs)
            if cost <= outf[1] - 1e-10:
                outf[0] = i
                outf[1] = cost
                outf[2] = iidxa1
                outf[3] = iidxa2

# results of algorithm in partition
@nb.jit(nb.void(
    nb.intc,  # na
    nb.float64[:, :],  # fvs
    nb.float64[:, :],  # mres
    nb.intc,  # start
    nb.intc,  # end
    nb.float64[:],  # resp
    nb.float64,  # pdisc
    nb.float64[:]  # res
), nopython=True)
def res_alg_part_disc(na,  # number of algorithms
                      fvs,  # sort. elements [inst_idx, feat_value]
                      mres,  # results insts x algs
                      start,  # start position
                      end,  # end position
                      resp,  # vetor with alg results part
                      pdisc,  # percentage to discard
                      res  # result: [idxAlg, cost]
                      ):
    nels = end-start
    nelp = ceil(nels * (1-pdisc))  # number of elements to sum
    res[0], res[1] = -1, oo
    for ia in range(na):
        for i in range(start, end):
            resp[i-start] = mres[int(round(fvs[i][0]))][ia]
        R = sort(resp[0:nels])
        resa = R[0:nelp].sum()
        if resa <= res[1] - 1e-10:
            res[0], res[1] = ia, resa

@nb.jit(nb.void(nb.intc,  # na
                nb.float64[:, :],  # fvs
                nb.float64[:, :],  # mres
                nb.float64[:],  # outf
                nb.float64[:],  # rp
                nb.float64),  # pdisc
        nopython=True)
def best_branch_feature_d(na,  # number of algorithms
                          fvs,  # sort.elements [inst_idx, feat_value]
                          mres,  # results inst x algs
                          outf,  # bridx, cost, best alg left, best alg right
                          rp,  # vetor with results of a partition, should have
                          pdisc  # perc of worse results per algorithn to disc.
                          ):
    """searches for best branching in a feature discarding a percentage of
    the worse results for each algorithm configuration"""
    outf[0], outf[1], nels = -1, oo, len(fvs)
    res = np.empty(shape=(2), dtype=np.float64)

    for i in range(0, nels-1):
        if (abs(fvs[i][1] - fvs[i+1][1]) >= np.float64(param.MIN_DIF_FV) and
                i >= param.MIN_INST_NODE and nels-i >= param.MIN_INST_NODE):
            res_alg_part_disc(nb.intc(na), fvs, mres, nb.intc(
                0), nb.intc(i+1), rp, nb.float64(pdisc), res)
            ia1, bc1 = res[0], res[1]
            res_alg_part_disc(na, fvs, mres, i+1, len(fvs), rp, pdisc, res)
            ia2, bc2 = res[0], res[1]

            cost = (bc1 + bc2) / len(fvs)
            if cost <= outf[1] - 1e-10:
                outf[0], outf[1] = i, cost
                outf[2], outf[3] = ia1, ia2

def best_branch(asds: AlgSel,  # algsel instance
                els: ndarray = None,  # elements
                pdisc: float = 0.0  # percentage to discard
                ) -> Branch:
    if els is None:
        els = ndarray([i for i in range(asds.ni)], dtype=intc)

    na, mres, nf, mfeat, nels = asds.na, asds.mres, int(asds.nf), asds.mfeat, len(
        els)

    if nels < param.MIN_INST_NODE:
        return None

    # for left and right nodes
    best_alg = [-1, -1]

    bvalue = float('inf')

    # cost for each algorithm in partitions 1 and 2
    p1, p2 = zeros(shape=(na), dtype=float64), zeros(shape=(na), dtype=float64)

    resp = None
    if pdisc >= 1e-7:
        resp = empty(shape=[len(els)], dtype=np.float64)

    outbb = array([-1, -1, -1, -1], dtype=float64)  # [index, cost]

    best, idiv, bestfeat = float('inf'), -1, -1
    for ifeat in range(nf):
        # feat vals
        fvals = array([[els[i], mfeat[els[i]][ifeat]]
                       for i in range(nels)], dtype=float64)
        # sort by feature value
        fvs = fvals[fvals[:, 1].argsort()]

        outbb.fill(-1.0)

        if pdisc >= 1e-7:
            best_branch_feature_d(na, fvs, mres, outbb, resp, pdisc)
        else:
            best_branch_feature(na, fvs, mres, outbb, p1, p2)

        if outbb[0] == -1:
            continue

        if outbb[1] < best:
            idiv = int(round(outbb[0]))
            best = outbb[1]
            elsdiv = array([int(round(fvs[i][0]))
                            for i in range(nels)], dtype=intc)
            bvalue = fvs[idiv][1]
            bestfeat = ifeat
            best_alg[0] = int(round(outbb[2]))
            best_alg[1] = int(round(outbb[3]))

    if idiv == -1:
        return None

    assert best_alg[0] in range(na)
    assert best_alg[1] in range(na)
    return Branch(elsdiv, idiv, [bestfeat], [asds.features[bestfeat]],
                  [1.0], bvalue, best, best_alg)

**Comment by h-g-s** [comment] 2019-12-14 15:03
[tn.py.docx](https://github.com/numba/numba/files/3963951/tn.py.docx)


included in .doc since .py is not supported

**Comment by stuartarchibald** [comment] 2019-12-16 10:09
Thanks for the report. Is this the minimal working reproducer?
```python
import numpy as np
import numba as nb

from numpy import argmin


#  compatible with numpy limits
oo = 2399999999

# removes results of one element to partition
@nb.jit((nb.intc, nb.float64[:], nb.intc, nb.float64[:, :]), nopython=True)
def rem_els_part(na,  # number of algorithms
                 resa,  # results partition
                 el,  # element
                 mres):  # complete results
    for ia in range(na):
        resa[ia] -= mres[int(el)][int(ia)]



# adds results of one element to partition
@nb.jit((nb.intc, nb.float64[:], nb.intc, nb.float64[:, :]), nopython=True)
def add_els_part(na,  # number of algorithms
                 resa,  # results partition
                 el,  # element
                 mres):  # complete results
    for ia in range(na):
        resa[ia] += mres[int(el)][int(ia)]



@nb.jit((nb.intc,  # na
         nb.float64[:, :],  # fvs
         nb.float64[:, :],  # mres
         nb.float64[:],  # outf
         nb.float64[:],  # p1
         nb.float64[:]),  # p2
        nopython=True)
def best_branch_feature(na,  # number of algorithms
                        fvs,  # sort.elements [inst_idx, feat_value]
                        mres,  # results insts x algs
                        outf,  # branchidx, cost, best alg left, best alg right
                        p1,  # algorithm's cost in p1
                        p2  # algorithm's cost in p2
                        ):
    outf[0], outf[1], nels = -1, oo, len(fvs)

    p1.fill(0)
    p2.fill(0)
    for i in range(0, nels):
        add_els_part(na, p2, fvs[i][0], mres)

    iidxa1 = 0
    iidxa2 = 0

    for i in range(0, nels-1):
        add_els_part(na, p1, fvs[i][0], mres)
        rem_els_part(na, p2, fvs[i][0], mres)

        if (abs(fvs[i][1] - fvs[i+1][1]) >= 0.00005
            and i >= 5
                and nels-i >= 5):
            iidxa1 = argmin(p1)
            iidxa2 = argmin(p2)

            cost = (p1[iidxa1] + p2[iidxa2]) / len(fvs)
            if cost <= outf[1] - 1e-10:
                outf[0] = i
                outf[1] = cost
                outf[2] = iidxa1
                outf[3] = iidxa2
```
if so, I cannot reproduce locally, which version of Numba are you using?

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment] 2020-02-06 09:33
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-02-06 09:33 UTC
Labels: needtriage
