### ISSUE TITLE
Cannot unify array(int64, 2d, F) and array(float64, 2d, C) for 'X.2', np.linalg.inv() even with np.ascontiguousarray() .astype(np.float64) everywhere

### ISSUE THREAD

**Issue by segatrade** [numba/numba#6218] opened 2020-09-05 16:56 UTC
### Check off these boxes:

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
0.51.2
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
- [X] ensure that there is no other issue present that
already describes the issue you have
(search at https://github.com/numba/numba/issues?&q=is%3Aissue).

### Details of the bug here, including, if applicable, what you expected to happen

Getting this error even with np.ascontiguousarray() .astype(np.float64) everywhere:

```
Cannot unify array(int64, 2d, F) and array(float64, 2d, C) for 'X.2',

@njit
def numba_get(): 
  X=np.ascontiguousarray(X.astype(np.float64)) 
  xx = np.ascontiguousarray(np.dot(X.T, X).astype(np.float64))
  xx_inv = np.ascontiguousarray(np.linalg.inv(xx).astype(np.float64))
         ^
```
```
xx=[[949.74599572 137.822009  ]
 [137.822009    20.        ]]
```

**Comment by stuartarchibald** [comment] 2020-09-07 09:01
Thanks for the report. This doesn't appear to be a minimal working reproducer, please could you format your report in such a way that it can be copy-pasted and then executed, so as to demonstrate the problem you are having, many thanks!

**Comment by stuartarchibald** [comment] 2020-09-28 09:56
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-09-28 09:56 UTC
Labels: more info needed
