### ISSUE TITLE
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)

### ISSUE THREAD

**Issue by yylhero** [numba/numba#6595] opened 2020-12-22 13:18 UTC
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Operands must be the same type, got (i64, i32)

File "pymssa\optimized.py", line 226:
def incremental_component_reconstruction(trajectory_matrix,
    <source elided>

    components = np.zeros((P, N, rank))
    ^

[1] During: lowering "$0.7 = call $0.2($0.6, func=$0.2, args=[Var($0.6, D:\lyy\MSSA\pymssa-master\examples\pymssa\optimized.py (226))], kws=(), vararg=None)" at D:\lyy\MSSA\pymssa-master\examples\pymssa\optimized.py (226)

**Comment by stuartarchibald** [comment] 2020-12-22 13:21
Thanks for the report. Is this a duplicate of https://github.com/numba/numba/issues/5208#issuecomment-584093779 ? Please could you try updating your Numba version to >= 0.47, thanks.

**Comment by yylhero** [comment] 2020-12-22 13:45
Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "numba/numba"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 晚上9:22
收件人:&nbsp;"numba/numba"<numba@noreply.github.com&gt;;
抄送:&nbsp;"李阳阳"<626439197@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [numba/numba] LoweringError: Failed in nopython mode pipeline (step: nopython mode backend) (#6595)





 
Thanks for the report. Is this a duplicate of #5208 (comment) ? Please could you try updating your Numba version to &gt;= 0.47, thanks.

**Comment by stuartarchibald** [comment] 2021-01-04 11:21
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2021-01-04 11:21 UTC
Labels: needtriage
