### ISSUE TITLE
UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode) Use of unsupported opcode (IMPORT_NAME) found

### ISSUE THREAD

**Issue by rmelikov** [numba/numba#5644] opened 2020-04-28 15:51 UTC
## Reporting a bug

- [x ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Here is my function:

```Python
from numba import jit

@jit(nopython=True)
def analyze_market_faster(market, verbose=False):
    
    from collections import deque
    
    '''
        I developed 2 methods here. The second (uncommented) method
        is faster. I thought that method 1 would be faster than method 2
        but I proved myself wrong.
    '''
    
    
    '''METHOD 1: 109 TIMES FASTER'''
    ###################################################################
    #if len(market) < 2: return int(0), int(0)
    #
    #trades = []
    #
    #sorted_market = deque(sorted(
    #    market,
    #    key = lambda x: (x[0], -x[1])
    #))
    #
    #while sorted_market and (sorted_market[0][0] != sorted_market[-1][0]):
    #    max_buy_price = sorted_market.popleft()
    #    min_sell_price = sorted_market.pop()
    #    if max_buy_price[1] >= min_sell_price[1]:
    #        trades.append((max_buy_price[1], min_sell_price[1]))
    ###################################################################
    
    
    '''METHOD 2: 170 TIMES FASTER'''
    ###################################################################
    if len(market) < 2: return int(0), int(0)
    
    buy_prices, sell_prices, trades = deque([]), deque([]), []
    
    for who, price in sorted(market):
        if who == 'buyer':
            buy_prices.append(price)
        else:
            sell_prices.append(price)
            
    for i in range(min(len(buy_prices), len(sell_prices))):
        max_buy_price = buy_prices.pop()
        min_sell_price = sell_prices.popleft()
        if max_buy_price >= min_sell_price:
            trades.append((max_buy_price, min_sell_price))
        else:
            break
    ###################################################################
    
    
    if verbose: print(trades)
    
    if trades:
        return trades[-1][1], len(trades)
    
    return int(0), int(0)

clearing_price0, trades0 = analyze_market(market_demo, verbose=True)
clearing_price1, trades1 = analyze_market_faster(market_demo, verbose=True)
print("Baseline: The clearing price is ${} with {} trades.".format(clearing_price0, trades0))
print("Your method: The clearing price is ${} with {} trades.".format(clearing_price1, trades1))
```

And here is the error that I'm getting:

```
---------------------------------------------------------------------------
UnsupportedError                          Traceback (most recent call last)
<ipython-input-8-2da7b7fd642f> in <module>
     62 
     63 clearing_price0, trades0 = analyze_market(market_demo, verbose=True)
---> 64 clearing_price1, trades1 = analyze_market_faster(market_demo, verbose=True)
     65 print("Baseline: The clearing price is ${} with {} trades.".format(clearing_price0, trades0))
     66 print("Your method: The clearing price is ${} with {} trades.".format(clearing_price1, trades1))

C:\Program Files\Python37\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info
--> 404             error_rewrite(e, 'unsupported_error')
    405         except (errors.NotDefinedError, errors.RedefinedError,
    406                 errors.VerificationError) as e:

C:\Program Files\Python37\lib\site-packages\numba\core\dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

C:\Program Files\Python37\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     77         value = tp()
     78     if value.__traceback__ is not tb:
---> 79         raise value.with_traceback(tb)
     80     raise value
     81 

UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (IMPORT_NAME) found

File "<ipython-input-8-2da7b7fd642f>", line 6:
def analyze_market_faster(market, verbose=False):
    <source elided>
    
    from collections import deque
    ^
```

**Comment by seibert** [comment] 2020-04-28 16:02
This error is because modules cannot be imported in inside a compiled function.  However, Numba does not have support for deque, so moving the import outside your function will still show a (different) error.

**Comment by rmelikov** [comment] 2020-04-28 16:14
Thanks for a quick response. I tried using `Numba` on another function, the one that I improved with my previous function using deques, and I still got an error. Here is my new code.

```Python
from numba import jit

@jit(nopython=True)
def analyze_market_faster(market, verbose=False):
    
    buy_prices = [price for who, price in market if who == 'buyer']
    sell_prices = [price for who, price in market if who == 'seller']
    trades = [] # Tracks trades
    unmatched = buy_prices and sell_prices
    while unmatched:
        i_buyer = buy_prices.index(max(buy_prices))
        i_seller = sell_prices.index(min(sell_prices))
        if buy_prices[i_buyer] >= sell_prices[i_seller]: # A match!
            trades.append((buy_prices[i_buyer], sell_prices[i_seller]))
            del buy_prices[i_buyer]
            del sell_prices[i_seller]
            unmatched = buy_prices and sell_prices
        else:
            unmatched = False # Stops trading
    if verbose: print(trades)
    if trades:
        return trades[-1][1], len(trades)
    return int(0), int(0)
```

And here is the error:

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-8-9590b48e399a> in <module>
     25 
     26 clearing_price0, trades0 = analyze_market(market_demo, verbose=True)
---> 27 clearing_price1, trades1 = analyze_market_faster(market_demo, verbose=True)
     28 print("Baseline: The clearing price is ${} with {} trades.".format(clearing_price0, trades0))
     29 print("Your method: The clearing price is ${} with {} trades.".format(clearing_price1, trades1))

C:\Program Files\Python37\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

C:\Program Files\Python37\lib\site-packages\numba\core\dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

C:\Program Files\Python37\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     77         value = tp()
     78     if value.__traceback__ is not tb:
---> 79         raise value.with_traceback(tb)
     80     raise value
     81 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify list(float64) and bool for 'unmatched.3', defined at <ipython-input-8-9590b48e399a> (10)

File "<ipython-input-8-9590b48e399a>", line 10:
def analyze_market_faster(market, verbose=False):
    <source elided>
    unmatched = buy_prices and sell_prices
    while unmatched:
    ^

[1] During: typing of assignment at <ipython-input-8-9590b48e399a> (10)

File "<ipython-input-8-9590b48e399a>", line 10:
def analyze_market_faster(market, verbose=False):
    <source elided>
    unmatched = buy_prices and sell_prices
    while unmatched:
    ^
```

**Comment by stuartarchibald** [comment] 2020-04-28 16:38
The problem is because `matched` is used both as a boolean and a list of float64. See: http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by rmelikov** [comment] 2020-04-28 16:59
Yeah, I saw the documentation. I'll have to read some more. Thanks!

**Comment by esc** [comment] 2020-04-28 20:36
@rmelikov I'll close this issue for now as I assume it is resolved. Thanks for using Numba and if you hit any other snags, don't hesitate to open a new issue!

**Closed by esc** 2020-04-28 20:36 UTC
Labels: no action required, question
