### ISSUE TITLE
Structured arrays 10 times slower than two dimensional arrays in nopython mode

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1067] opened 2015-04-01 12:46 UTC
Hello,

using structured arrays as suggested by Graham Markall
( https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/Mqi9SXzqdTg ) 
instead of class properties is about 10 times slower than to use
two dimensional arrays.

Implemented code example with two dimensional arrays:
https://gist.github.com/ufechner7/d4fd1b75af0f1e5cd48c

Benchmark code:
https://gist.github.com/ufechner7/95db14f734edd51dcd9b

Benchmark results:

```
time for numba sub_plain      [µs]:     0.33
time for numba sub_rec_array  [µs]:     1.97
time for numba sub_array      [µs]:     0.19
```

This prevents me from using record arrays, even though the code is
shorter and cleaner, if they could be used.

Code using record arrays:

``` python
x_dt = np.dtype([('v_wind', np.float64),
                 ('v_wind_gnd', np.float64),
                 ('result', np.float64)])
buf = np.zeros((3, 3)) # initialize the record array with zeros
vec3 = np.recarray(3, dtype=x_dt, buf=buf) 

sub(vec3.v_wind, vec3.v_wind_gnd, vec3.result)  
```

Code using two dimensional arrays:

``` python
V_wind = 0 # (westwind, downwind direction to the east)
V_wind_gnd = 1
Result = 2 
vec3 = np.zeros((3, 3))

sub(vec3[V_wind], vec3[V_wind_gnd], vec3[Result]) 
```

It would be nice, if this could be fixed.

**Comment by gmarkall** [comment] 2015-04-01 13:35
The code inside the jitted functions (which appears to be very similar to that we discussed in #1057) is performing too few operations to get the most benefit from being jitted. If this is representative of an operation that needs to be performed many times in your code in a loop, then you will have to push the loop inside the jitted function, otherwise the overhead of dispatching jitted functions dominates, as you see here.

For the sake of example, if we make the jitted functions do more work by modifying them to perform the operation 100000 times, like for example:

```python
@jit(nopython=False)
def sub_rec_array(vec3):
    for i in range(100000):
        sub(vec3.v_wind, vec3.v_wind_gnd, vec3.result)
```

(and make a similar change to the other two functions) then the differences between the times changes:

```
time for numba sub_plain      [µs]:    104.70
time for numba sub_rec_array  [µs]:    105.63
time for numba sub_array      [µs]:    117.55
```

as the execution time is no longer dominated by the dispatcher. Using recarrays turns out to be faster than arrays in this case, possibly because the overhead of passing a single recarray is lower than the overhead of passing three arrays (though it would require further investigation to confirm whether or not this is the reason).

**Comment by ufechner7** [comment] 2015-04-01 13:57
This is not the point. The code is between 2 times and 50 times faster, than the equivalent numpy functions, and this is fast enough for me. And the overhead of passing parameters is low, if I use 2-dimensional numpy arrays to pass the parameters. Therefore I insist on this being a performance bug. If I want to work on arrays with 10000 elements, then I do not need numba, then numpy is also fast.

**Comment by ufechner7** [comment] 2015-04-01 14:02
Please have a look at the gist: 
https://gist.github.com/ufechner7/d4fd1b75af0f1e5cd48c
This is a full example of what I am doing.

If I would flatten this code manually, nobody could understand and maintain it any longer.

**Comment by gmarkall** [comment] 2015-04-01 14:21
>This is a full example of what I am doing.

There's a lot more computation going on inside jitted functions there, so intuitively I would imagine that the overhead of dispatch is much lower in that example, and you wouldn't see the same discrepancy in runtimes between using structured arrays and many separate arrays. The suggestion to push a loop inside the jitted function (and the example alteration to repeat the same operation many times) was about moving more work inside jitted functions.

**Comment by ufechner7** [comment] 2015-04-01 14:48
As you can see in my code, the outer loop IS in a jit function, but this jit function is calling other jit functions. It must be allowed to use nested functions without too much overhead.
The function def loop(scalars, vec3, initial_masses, masses, pos, vel, posd, veld, res0, res1)
is calling def calcRes(scalars, vec3, pos1, pos2, vel1, vel2, mass, veld, result, i) which is calling
def calcDrag(vec3, v_segment, unit_vector, rho, last_tether_drag, v_app_perp, area) which is calling functions that work on 3-element vectors lik sub3 etc.
And also the complex, complete example was about 10 times slower with record arrays than with 2-dimensional arrays.

**Comment by gmarkall** [comment] 2015-04-01 14:49
It's been suggested to me that there is a lack of documentation/explanation on what Numba actually does when it invokes a jitted function, so I hope that I can explain a bit more here about what Numba is doing in order to clarify things:

When you make a call to a function that has been decorated with the jit decorator, Numba has to figure out what the types of all the arguments are in order to either compile the jitted function for those arguments (because every time a new set of argument types is used, Numba must compile a specialised version of the function), or to retrieve a cached compiled version of the function for those specific arguments. In the case of scalar types and arrays of scalar types, this is fairly simple - each dtype has a unique integer that identifies it, so comparing argument types is just a case of comparing integers, and this is very fast. For structured types, it is more complicated, since every field needs to be compared. In order to do this, we have to call a function which computes the "data type descriptor" of the structured type (i.e. http://docs.scipy.org/doc/numpy/reference/c-api.types-and-structures.html#c.PyArray_Descr). This takes much longer than just looking up the integer corresponding to a type, and also takes longer to compare with other data type descriptors for the already-compiled versions of the function.

This lookup of argument types and comparisons happens within the Numba dispatcher, which is also responsible for marshalling any arguments into their native types before passing them to the compiled code. 

What you are seeing with the benchmark above, is that the time taken to call the function increases by about 2us when a structured type is involved, because of all this extra work that is going on in the dispatcher. The actual generated code has not slowed down, but its runtime is a very small part of the total runtime because it is much shorter than the time spent in the dispatcher.

In summary:
- the time taken to call an empty jitted function is greater than the time taken to call an empty Python function, due to the work that the dispatcher does - this is the overhead of the dispatch.
- the overhead of the dispatch is larger when structured types are involved.
- The execution of the benchmark above is dominated mainly by the dispatch overhead, because the `sub` function's body has a very short execution time.
- Your complete example would be expected to be much less dominated by the dispatch overhead, because there is more computation to be done inside the jitted functions, and therefore I'd expect you not to observe the same ratio between execution times when using arrays and when using structured types in that code.
- Or, to put it another way - the benchmark provided is unlikely to characterise the performance of your full example, because it does a lot less work inside the jitted function than the full example appears to.

**Comment by gmarkall** [comment] 2015-04-01 14:58
> As you can see in my code, the outer loop IS in a jit function, but this jit function is calling other jit functions.

I'm finding it a little bit difficult to understand how this code is used as it doesn't include calls to the functions. I see the loops inside the `loop` function, but I don't know how large `SEGMENTS` is (though I would not think it should have to be very large).

> It must be allowed to use nested functions without too much overhead.

There should not be any extra overhead using structured types when calling one jitted function from another, since calls from one nopython function to another are resolved at compile-time.

> And also the complex, complete example was about 10 times slower with record arrays than with 2-dimensional arrays.

What was the total runtime of the complete, complex example? Can you give a rough idea of how many times it makes a call from a Python function into a jitted function?

**Comment by ufechner7** [comment] 2015-04-01 18:27
I added an full, working example to the public git repository:
https://bitbucket.org/ufechner/freekitesim
To run it, you can change int the FreeKiteSim directory (this should be a subdirectory of ~/00PythonSoftware) and type:
python  python KPS3_v2.py

Do NOT follow the installation instructions, because they would install numba 0.11.

The total runtime of the complete, complex example is now about 22 microseconds on a sandybridge core i7 with 3.4 GHz. This routine is called by a solver. This solver needs to supply a result every 50 ms to meet the (soft) real-time requirements of our flight-simulator. This requirement is met, if the execution time of the method "residual" is less then 80 microseconds.

The total number of calls from Python to a jit function is three (for each call of the method residual):
calcLoD, calcAeroForces and loop are called once.

**Comment by gmarkall** [comment] 2015-04-01 20:01
Thanks for posting the example.

 Some initial observations/thoughts:

- In `residual`, there appear to be 4 calls into a jitted function:  `calcLoD`, `calcAeroForces`, `loop` and `la.norm`.
- If you could outline the calls to `calcLoD`, `calcAeroForces`, `loop` and `la.norm` into an additional jitted function, that would cut down the dispatcher overhead (optimistically I'd hope to reduce it by 75%, but it might not quite be as high as that).
- If you change the code to use structured types, then you will gain some additional overhead from the dispatcher going through the process to compute and compare descriptors that I mentioned in an earlier comment. For the simple benchmark I was observing an overhead of about 1us, but if you have a more complicated structured type then it could be more, but I do not know how much by, or whether that fully explains the 10 times slowdown that you mentioned. (I would not have expected the dispatcher to become so slow in this case that it would be completely responsible for the slowdown, but it's hard to be certain without also seeing the version that used structured types).
- The value of `SEGMENTS` did not have a large influence on execution time for me - setting `SEGMENTS` to 20 from 6 increased the execution time from about 13us to 14.5us, so it does not appear to be dominating the performance of the code in its present form.

If the problem is largely down to the dispatcher, then for a longer-term solution, one workaround to avoid the dispatcher overhead in your case would be for Numba to provide a way to bypass computing the types of arguments and checking them - this would only be compatible with having a single specialisation of a jitted function, but I don't think (correct me if I am wrong) this would be a problem for your use case. However, this would probably require some discussion about how to safely implement it and avoid creating a feature that would make it easy to do the wrong thing and cause hard-to-debug issues.

**Comment by ufechner7** [comment] 2015-04-02 10:11
I rewrote my complex example and replaced 3 of the 21 3-element vectors with a record array with 3 elements. This already reduced the speed by more then a factor of two. Therefore I assume, that the speed reduction even in the complex example is about 10, if I would replace all vectors with record arrays.
You can find the code here: https://gist.github.com/ufechner7/538269c3c20e84665f60

**Comment by gmarkall** [comment] 2015-04-02 10:22
I'm getting:

```
$ python KPS3_v3.py 
m_k:  0.2
MODEL:  KPS4
Traceback (most recent call last):
  File "KPS3_v3.py", line 22, in <module>
    from Settings import C_SPRING, DAMPING, SEGMENTS, L_0, V_REEL_OUT, MASS, KITE_MASS, KCU_MASS, ELEVATION, \
ImportError: cannot import name pro
```

when attempting to run this code inside the FreeKiteSim repository. Is there some additional change I need?

**Comment by ufechner7** [comment] 2015-04-02 10:34
I updated the code in the gist. I hope, that it works now.

**Comment by gmarkall** [comment] 2015-04-02 10:40
Now I'm missing `mini_sim_core_cpp`:

```
$ python KPS3_v3.py 
m_k:  0.2
MODEL:  KPS4
Traceback (most recent call last):
  File "KPS3_v3.py", line 41, in <module>
    from mini_sim_core_cpp import minilib
ImportError: No module named mini_sim_core_cpp
```

**Comment by ufechner7** [comment] 2015-04-02 10:46
Sorry. I uploaded another version.

**Comment by gmarkall** [comment] 2015-04-02 10:49
Thanks, that seems to run now.

**Comment by gmarkall** [comment] 2015-04-02 12:52
So, compared to KPS3_v2.py, KPS3_v3.py loses performance for two reasons.

- One is the inefficiency of attribute access for recarrays.
- The other is the overhead of passing recarrays to the dispatcher, as mentioned before.

On my system, KPS3_v2.py reports a timing of about 13us, and KPS3_v3.py reports a timing of about 28us.

To demonstrate the first issue, I added an extra benchmark at the end of the code that measures the time taken to compute only v_app:

```python
    with Timer() as t:
        for j in range(LOOPS):
            v_app = MY_KPS.rec3.v_wind - MY_KPS.v_kite
    print "\nv_app Execution time (µs): ", t.secs / LOOPS * 1e6
```

The output of this is generally around:

```
v_app Execution time (µs):  8.48054885864
```

The reason for this is that attribute access on recarrays is fairly slow, so you would need to avoid making accesses like this in Python code where possible. It is OK to do attribute access in Numba, as it is much faster - this is because the attribute access is compiled down to pointer arithmetic that computes the offset from the base of the record. 

To regain the performance lost by both of the above causes, I pushed this computation done by the Numba functions, and the computations of `v_app` and `pos[SEGMENTS - 1] - self.pos_kite` inside another jitted function, `numba_residual`. I've pushed this version to a fork at: https://bitbucket.org/gmarkall/freekitesim

The runtime of KPS3_v3.py on my machine is now around 11us, compared to KPS3_v2.py's 13us runtime. I am optimistic that if you do convert the rest of your data structures to use recarrays, then you should be able to keep performance similar to what you had already in KPS3_v2.py, as long as you can avoid doing recarray attribute access inside Python code, and only do attribute access inside Numba jitted code. 

Does this provide a suitable way forward for your use case?

**Comment by ufechner7** [comment] 2015-04-02 13:16
I could not find any code from you in your fork. Perhaps you forgot to push?

**Comment by gmarkall** [comment] 2015-04-02 13:18
Whoops! Yes, I did - I have pushed now :-)

**Comment by ufechner7** [comment] 2015-04-02 13:21
Thank's!

**Comment by axil** [comment] 2019-01-23 05:36
So are they still 10 times slower as of today?

**Comment by stuartarchibald** [comment] 2023-01-03 15:27
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2023-01-03 15:27 UTC
Labels: needtriage, performance
