### ISSUE TITLE
ImportError: Numba could not be imported.

### ISSUE THREAD

**Issue by Spratumn** [numba/numba#5631] opened 2020-04-25 09:28 UTC
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: 找不到指定的模块。'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Program Files\Python36\python.exe

**Comment by esc** [comment] 2020-04-25 12:31
@Spratumn thanks for asking about this on the Numba issue tracker. I believe this is a duplicate of #5600 and will close the issue now and mark it as such. If this is an error on my part, please feel free to re-open the issue providing additional information.

**Closed by esc** 2020-04-25 12:31 UTC
