### ISSUE TITLE
call_conv holds a reference to a different CPUContext object

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#8236] opened 2022-07-08 22:38 UTC
While working on #8134, I notice on `BaseLower` that the CPUContext `context` and `context.call_conv.context` are not referencing the same object. I believe this is due to `context.call_conv` being implemented as a `@cached_property` and not a `@property`.

https://github.com/numba/numba/blob/0b75a0053a72b2ebd85a7bde4d12c3c010fe13fd/numba/core/lowering.py#L34
https://github.com/numba/numba/blob/0b75a0053a72b2ebd85a7bde4d12c3c010fe13fd/numba/core/cpu.py#L111-L113

The problem that this brings is that both contexts can have the same attribute with different values (i.e. NRT)

Reproducer:
```diff
diff --git a/numba/core/lowering.py b/numba/core/lowering.py
index 251851d70..6abe61a14 100644
--- a/numba/core/lowering.py
+++ b/numba/core/lowering.py
@@ -34,6 +34,9 @@ class BaseLower(object):
         self.blocks = utils.SortedMap(func_ir.blocks.items())
         self.func_ir = func_ir
         self.call_conv = context.call_conv
+        print(context is context.call_conv.context)  # False
+        print(context.enable_nrt)  # True
+        print(self.call_conv.context.enable_nrt)  # False
         self.generator_info = func_ir.generator_info
         self.metadata = metadata
         self.flags = targetconfig.ConfigStack.top_or_none()
```

**Comment by gmarkall** [comment] 2022-08-18 15:59
I wonder if the root cause of https://github.com/numba/numba/issues/8036 is a similar problem.

**Comment by guilhermeleobas** [comment] 2022-08-18 16:35
I have a fix for it in #8134, which just replace `@cached_property` by `@property`.

**Comment by gmarkall** [comment] 2022-08-18 16:49
Thanks for the pointer - turns out that doing that alone doesn't resolve #8036. Maybe there's something else going wrong too, but it feel like that's a step in the right direction.

**Comment by stuartarchibald** [comment] 2023-03-29 15:03
@guilhermeleobas is this now fixed through #8134 ?

**Comment by guilhermeleobas** [comment] 2023-03-29 15:04
Yes!

**Comment by stuartarchibald** [comment] 2023-03-29 15:06
> Yes!

Thanks for confirming, closing!

**Closed by stuartarchibald** 2023-03-29 15:06 UTC
Labels: bug - incorrect behavior
