### ISSUE TITLE
Travis build error with python 3.4

### ISSUE THREAD

**Issue by bmcfee** [numba/numba#2464] opened 2017-07-15 14:58 UTC
This popped up over the last few days (since the last release), and I brought it up during the scipy sprint.

I'm currently getting an error with the conda package for numba on python 3.4.  Here's a link to the log: https://travis-ci.org/librosa/librosa/jobs/252844064

**Comment by seibert** [comment] 2017-07-15 15:11
After some triage, it appears the issue is triggered by only having Numba Python 3.4 packages for NumPy 1.10 in the public Anaconda repo.  We should see if the Anaconda team will put our build for NumPy 1.11 in the public repo as well.

**Comment by seibert** [comment] 2017-07-15 15:23
Correction: I do see the NumPy 1.10 / Python 3.4 build in the public repo, but I'm not sure why conda  is not picking it in the build.

**Comment by stuartarchibald** [comment] 2017-07-17 10:53
Think it's because there's no np111py34 build for linux64 in the channel as noted by  @seibert , were this present the package downgrading etc would not be needed.

The error message as seen is due to SciPy in the installation having ufuncs that need `libgfortran.so.1` but the installation environment having `libgfortran.so.3`. I think this is probably a mistake somewhere in constraint specification/resolution in the package dependencies.

**Comment by stuartarchibald** [comment] 2018-04-11 15:42
Closing as I think this was resolved and librosa appears to be building fine again. Thanks.

**Closed by stuartarchibald** 2018-04-11 15:42 UTC
