### ISSUE TITLE
Failed in nopython mode pipeline (step: nopython mode backend)

### ISSUE THREAD

**Issue by MainzKCL** [numba/numba#3932] opened 2019-04-02 22:04 UTC
Cannot cast array(bool, 1d, C) to bool: %".1784" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$222.6"

File "<ipython-input-230-eba33f80b228>", line 31:
def stabilitySelect(lambdaNeed,x,y,numIter,mask):
    <source elided>
        for i in prange(0,b.shape[0]):
            if(b[i]>0):
            ^

[1] During: lowering "branch $222.6, 236, 305" at <ipython-input-230-eba33f80b228> (31)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment] 2019-04-03 08:52
Thanks for the report. Whilst there is no minimal working reproducer present I can guess from the lowering error that this is a case of trying to do this:
```python
from numba import njit
import numpy as np

@njit
def foo():
    a = np.ones(1, np.bool_)
    if a > 0:
        print('truebr')
    else:
        print('falsebr')

foo()
```
and the root cause is that `a > 0` is not a predicate but rather a conditional. https://github.com/numba/numba/pull/3901 is WIP to fix.

**Comment by MainzKCL** [comment] 2019-04-03 10:58
Hi,

I'm sorry I forgot to add the minimum work. The function acted more like:

@njit(parallel=True, fastmath=True)
Def foo():
A = np.ones(1,10)

If(A[0,0]<0):
Print()

I write the statement like this because I was only passing one value of the array into the statement which is why I couldn't figure out the issue. No python mode has been very difficult to deal with especially in the case of machine learning which was my intended use. Great system but still having some issues on this if statement.

**Comment by stuartarchibald** [comment] 2019-04-03 16:35
Thanks for the update. If you could produce a sample that reproduces the error I'd be happy to take a look. The sample is invalid without Numba being involved as the `np.ones` calls is incorrect (`shape` should be a tuple):
```python
import numpy as np

def foo():
    A = np.ones(1, 10)
    if(A[0,0]<0):
        print()

foo()
```
and if that is fixed then:
```python
from numba import njit
import numpy as np

@njit(parallel=True, fastmath=True)
def foo():
    A = np.ones((1, 10))
    if(A[0,0]<0):
        print()

foo()
```
compiles and executes fine.

**Comment by stuartarchibald** [comment] 2019-04-18 22:01
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-04-18 22:01 UTC
Labels: bug, duplicate
