### ISSUE TITLE
numpy.median gives error in stencil

### ISSUE THREAD

**Issue by lpuglia** [numba/numba#3528] opened 2018-11-22 16:26 UTC
```
In [1]: numba.__version__
Out[1]: '0.41.0dev0+94.g361809189'
```

I'm trying to use the median function in a stencil:

```python
from numba import stencil
import numpy as np

@stencil(neighborhood=((-1, 1), (-1, 1)), )
def interpolate(L):
    return np.median(L[-1:2, -1:2])

x = np.arange(20, dtype=np.uint32).reshape(4, 5)
interpolate(x)
```

but i get the following error:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function add>) with argument(s) of type(s): (slice<a:b>, int64)
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * parameterized
In definition 0:
    All templates rejected
In definition 1:
    All templates rejected
In definition 2:
    All templates rejected
In definition 3:
    All templates rejected
In definition 4:
    All templates rejected
In definition 5:
    All templates rejected
In definition 6:
    All templates rejected
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-1-cd13b97c2df7> (4)

File "<ipython-input-1-cd13b97c2df7>", line 4:

@stencil(neighborhood=((-1, 1), (-1, 1)), )
```

**Comment by stuartarchibald** [comment] 2018-11-22 16:32
Thanks for the report. This is a bug, the problem is evident in the IR, a slice is being added to an index variable.
```python
from numba import stencil
import numpy as np

@stencil(neighborhood=((-1, 1), (-1, 1)), )
def interpolate(L):
    tmp = np.empty((3, 3))
    for i in range(-1, 2):
        for j in range(-1, 2):
            tmp[i, j] = L[i, j]
    return np.median(tmp)

x = np.arange(20, dtype=np.float64).reshape(4, 5)
interpolate(x)
```
is an inefficient work around.

**Comment by lpuglia** [comment] 2018-11-28 10:33
interestingly enough using a njitted func with parallel=True bypass the error:

```
@jit(nopython=True, parallel=True)
def inter(x,y):
    y = interpolate(x)

x = np.arange(20, dtype=np.uint32).reshape(4, 5)
y = np.zeros_like(x)
inter(x,y)
```

**Comment by lpuglia** [comment] 2019-01-26 12:11
any news on this?

**Comment by stuartarchibald** [comment] 2019-01-28 14:43
@lpuglia I'm afraid not. @DrTodd13 may have some ideas?

**Comment by DrTodd13** [comment] 2019-01-28 18:30
It didn't have ParallelAccelerator tag so I didn't see it.  I will look into it soon.  @lpuglia

**Comment by stuartarchibald** [comment] 2019-01-28 22:02
@DrTodd13 sorry, forgot to add it. Think it's invariant of `ParallelAccelerator`?

**Comment by DrTodd13** [comment] 2019-01-28 22:10
@stuartarchibald Well, we don't have a stencil tag.  So, the ParallelAccelerator one is the only one that gets my attention.

**Comment by stuartarchibald** [comment] 2019-01-28 23:03
:) noted, thanks for looking at it.

**Comment by lpuglia** [comment] 2019-04-03 10:11
@DrTodd13 just got latest version from repository:

numba                     0.43.1           py36h962f231_0

nothing changed, is the fix only in develop?

**Comment by stuartarchibald** [comment] 2019-04-03 10:29
@lpuglia it's a PR still https://github.com/numba/numba/pull/3719

**Comment by stuartarchibald** [comment] 2019-09-11 13:28
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 13:28 UTC
Labels: ParallelAccelerator, bug
