### ISSUE TITLE
support for standard library sum()

### ISSUE THREAD

**Issue by gemerden** [numba/numba#6672] opened 2021-01-30 18:12 UTC
---
Not sure if i am missing something, but it seems the sum(iterable) function is not supported (cannot find it in the supported list). That seems odd. Any chance of adding it?

I get the error:

Untyped global name 'sum': Cannot determine Numba type of <class 'builtin_function_or_method'>

the code is:

`cost -= late_cost * sum([s for s in spares if s < 0])`

(all floats)

**Comment by stuartarchibald** [comment] 2021-02-01 10:23
Thanks for opening this feature request. As this is a duplicate of https://github.com/numba/numba/issues/5088 I'm going to close it with view of keeping the number of open issues in the issue tracker to a minimum. I suggest commenting on and/or subscribing to #5088 to check for progress. Thanks again!

**Closed by stuartarchibald** 2021-02-01 10:23 UTC
