### ISSUE TITLE
Can't install in environment using Python 3.11

### ISSUE THREAD

**Issue by iantimmis** [numba/numba#8844] opened 2023-03-23 15:01 UTC
I have an environment with Python 3.11 and can not install numba. 

I tried, `pip install numba`and `conda install numba`and neither case worked.

Part of the pip error message
```
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3c/95r_6q8x7gb72krfrm43xdx80000gp/T/pip-install-o5_gt9gv/numba_22af8ac404d3442bbaed12a7184e817f/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/3c/95r_6q8x7gb72krfrm43xdx80000gp/T/pip-install-o5_gt9gv/numba_22af8ac404d3442bbaed12a7184e817f/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]
```

Part of the conda error message
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - numba -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.11
```

I am on an M1 macbook.

**Comment by esc** [comment] 2023-03-23 15:03
duplicate of https://github.com/numba/numba/issues/8304

**Closed by esc** 2023-03-23 15:03 UTC

**Comment by esc** [comment] 2023-03-23 15:06
@iantimmis I should also note -- for completeness -- that Numba (more specifically LLVM 11-14) are currently considered  broken on M1: https://github.com/numba/numba/issues/8567#issuecomment-1464930794 -- regardless of the Python 3.11 support. Unfortunately for certain use-cases the best recommendation is to use a different hardware architecture.
