### ISSUE TITLE
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)

### ISSUE THREAD

**Issue by smcantab** [numba/numba#4260] opened 2019-07-02 14:22 UTC
Using Numba 0.44.1+0.ge5aad2df9.dirty

using the following code in python2.7 (latest anaconda distribution)

```python
from __future__ import print_function, division, absolute_import
import numpy as np
from numba import jit

rs_rules = dict([(0, [[0, 2], [4, 6]]), 
				 (1, [[1, 3], [5, 7]]),
				 (2, [[0, 2], [5, 7]]),
				 (3, [[1, 3], [4, 6]]),
				 (4, [[0, 3], [4, 7]]),
				 (5, [[1, 2], [5, 6]]),
				 (6, [[0, 3], [5, 6]]),
				 (7, [[1, 2], [4, 7]])
				])

rs_id = dict([(0, [[1, 1], [1, 1]]), (1, [[-1, -1], [-1, -1]]),
			  (2, [[1, 1], [-1, -1]]), (3, [[-1, -1], [1, 1]]),
			  (4, [[1, -1], [1, -1]]), (5, [[-1, 1], [-1, 1]]),
			  (6, [[1, -1], [-1, 1]]), (7, [[-1, 1], [1, -1]]),
			 ])

@jit
def _func(nmax):
	assert nmax >= 1
	a = np.array([[0, 2], [4, 6]]) # seed
	for n in xrange(2, nmax+1):
		A = np.zeros((2**n, 2**n))
		for x in xrange(0, 2**n, 2):
			i = x//2
			for y in xrange(0, 2**n, 2):
				j = y//2
				A[x:x+2, y:y+2] = rs_rules[a[i, j]]
		a = np.array(A)
	return a

@jit
def func(nmax):
	a = _func(nmax)
	n = nmax + 1
	A = np.zeros((2**n, 2**n))
	for x in xrange(0, 2**n, 2):
		i = x//2
		for y in xrange(0, 2**n, 2):
			j = y//2
			A[x:x+2, y:y+2] = rs_id[a[i, j]]
	return A
```

here's the error:

```
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x7f8f6dfc9850>)

File "path/to/file.py", line 27:
def _func(nmax):
	assert nmax >= 1
 ^

[1] During: lowering "raise <type 'exceptions.AssertionError'>" at path/to/file.py (27)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```

**Comment by stuartarchibald** [comment] 2019-07-02 14:41
Thanks for the report, this is a duplicate of https://github.com/numba/numba/issues/4185, https://github.com/numba/numba/pull/4224 fixes. Also, you may want to look at Numba's [typed dictionary](https://numba.pydata.org/numba-doc/latest/reference/pysupported.html#dict) and pass that in as a variable/define it in the function, lookup is often very fast because of inlining. Further, performance will be a lot better if you can switch to `@jit(nopython=True)`. For example:
```python
from __future__ import print_function, division, absolute_import
import numpy as np
from numba import jit, typed

@jit(nopython=True)
def _func(nmax):
        rs_rules = {0: np.array([[0, 2], [4, 6]]),
                    1: np.array([[1, 3], [5, 7]]),
                    2: np.array([[0, 2], [5, 7]]),
                    3: np.array([[1, 3], [4, 6]]),
                    4: np.array([[0, 3], [4, 7]]),
                    5: np.array([[1, 2], [5, 6]]),
                    6: np.array([[0, 3], [5, 6]]),
                    7: np.array([[1, 2], [4, 7]])}
        assert nmax >= 1
        a = np.array([[0, 2], [4, 6]], dtype=np.int64) # seed
        for n in xrange(2, nmax+1):
                A = np.zeros((2**n, 2**n), dtype=np.int64)
                for x in xrange(0, 2**n, 2):
                        i = x//2
                        for y in xrange(0, 2**n, 2):
                                j = y//2
                                A[x:x+2, y:y+2] = rs_rules[a[i, j]]
                a = A
        return a


@jit(nopython=True)
def func(nmax):
        rs_id = {0: np.array([[1, 1], [1, 1]]),
                 1: np.array([[-1, -1], [-1, -1]]),
                 2: np.array([[1, 1], [-1, -1]]),
                 3: np.array([[-1, -1], [1, 1]]),
                 4: np.array([[1, -1], [1, -1]]),
                 5: np.array([[-1, 1], [-1, 1]]),
                 6: np.array([[1, -1], [-1, 1]]),
                 7: np.array([[-1, 1], [1, -1]])}
        a = _func(nmax)
        n = nmax + 1
        A = np.zeros((2**n, 2**n))
        for x in xrange(0, 2**n, 2):
                i = x//2
                for y in xrange(0, 2**n, 2):
                        j = y//2
                        A[x:x+2, y:y+2] = rs_id[a[i, j]]
        return A

func(5)
from time import time
ts = time()
func(5)
print(time()-ts)
```
gives:
```
$ python issue4260.py 
0.000247001647949
```
vs the original:
```
$ python issue4260.py 
0.00503706932068
```

**Comment by smcantab** [comment] 2019-07-02 14:49
great, thank you! I'll let you decide whether/when to close the issue

**Comment by stuartarchibald** [comment] 2019-07-18 10:05
https://github.com/numba/numba/pull/4224 is in mainline, closing.

**Closed by stuartarchibald** 2019-07-18 10:05 UTC
Labels: bug, duplicate, objectmode
