### ISSUE TITLE
Implement basic support for (list) comprehensions.

### ISSUE THREAD

**Issue by stefanseefeld** [numba/numba#2262] opened 2017-02-01 16:38 UTC
It appears one of the main issues blocking support for comprehensions is the need for closures to capture variables used in the expression inside the comprehension.
I suspect a large class of applications doesn't require these variables to alias the outer scope, i.e. the variables could be truly local, simplifying the required closure logic substantially. 

This suggests that this would be a good use-case to aim for as an incremental step when adding support for comprehensions to Numba.

**Comment by gandhis1** [comment] 2017-02-02 02:54
This is a duplicate of #504, but you are right, and I'm pretty sure this is one of the most desired features by Numba users in general.

**Comment by stuartarchibald** [comment] 2017-06-06 11:48
Added in https://github.com/numba/numba/pull/2369

**Closed by stuartarchibald** 2017-06-06 11:48 UTC
Labels: enhancement
