### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'core'

### ISSUE THREAD

**Issue by yuguanw** [numba/numba#6240] opened 2020-09-12 19:03 UTC
I am using Linux and numba-0.51.2. I am not able to import this package.

import numba

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-68d4f1bcefa7> in <module>
----> 1 import numba

~/.local/lib/python3.6/site-packages/numba/__init__.py in <module>
     26 
     27 # Re-export types itself
---> 28 import numba.core.types as types
     29 
     30 # Re-export all type names

AttributeError: module 'numba' has no attribute 'core'

I have the following dependent packages llvmlite-0.34.0 numpy-1.19.2 setuptools-50.3.0.
What happens here and could you give me some advice?

**Comment by stuartarchibald** [comment] 2020-09-14 10:04
Thanks for the report. This seems to typically arise in the case of a corrupted environment where multiple version of numba have been installed using `pip` and there's some artifacts from a previous version of numba still present. Can you reproduces this in an entirely new environment?

**Comment by stuartarchibald** [comment] 2020-09-23 15:57
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2020-09-23 15:57 UTC
Labels: needtriage
