### ISSUE TITLE
Partial indexing is slow

### ISSUE THREAD

**Issue by seibert** [numba/numba#1319] opened 2015-07-14 16:01 UTC
This code from the mailing list demonstrates a failure to inline a fairly simple function:

``` python
@numba.jit(nopython=True)
def sqeuclidean(x, y):
    distance = 0.
    for n in xrange(x.shape[0]):
        distance += (x[n] - y[n])**2
    return distance

@numba.jit(nopython=True)
def cdist(x, y):
    D = np.zeros((x.shape[0], y.shape[0]))
    for i in xrange(x.shape[0]):
        for j in xrange(y.shape[0]):
            for d in xrange(x.shape[1]):
                D[i, j] += (x[i, d] - y[i, d])**2
    return D

@numba.jit(nopython=True)
def cdist_func(x, y):
    D = np.empty((x.shape[0], y.shape[0]))
    for i in xrange(x.shape[0]):
        for j in xrange(y.shape[0]):
            D[i, j] = sqeuclidean(x[i], y[i])
    return D

a = np.random.random_sample((1000, 10))
b = np.random.random_sample((1000, 10))
%timeit cdist(a, b)
%timeit cdist_func(a, b)
```

Output:

```
10 loops, best of 3: 19.7 ms per loop
10 loops, best of 3: 87.6 ms per loop
```

The other possibility is that there is something less efficient about the way we handle the partial indexing of the 2D array in `cdist_func`.

**Comment by pitrou** [comment] 2015-07-15 20:20
Looking at the assembly, the function *is* inlined and the inner loop (the one which computes the squared distance) is compiled efficiently, but there's a lot of surrounding code handling reference counts on NRT structures, so I'm presuming this is the cause of the discrepancy.

**Comment by seibert** [comment] 2015-07-15 20:25
oh, interesting.  Is the output of `inspect_llvm()` before optimization?

**Comment by pitrou** [comment] 2015-07-15 20:25
I meant the x86_64 assembly, not the LLVM assembly. I presume the LLVM assembly before optimization would be basically unreadable.

**Comment by pitrou** [comment] 2015-07-15 20:31
Here is the full loop nest:
https://gist.github.com/pitrou/6aca05016469510dd863

The inner loop (squared distance) is in `LBB0_39`. Storing the squared distance result and incrementing the indices in in `LBB0_45`. Of the 5 other blocks, 3 are reference counting boilerplate (in the outer loop).

**Comment by pitrou** [comment] 2015-07-15 20:33
By the way, what seems weird to me is that there are two increfs and two decrefs to the same meminfo block (pointed to by `%rbx`), rather than one for each distinct meminfo block (i.e. `x[i]` and `y[i]`)...

**Comment by seibert** [comment] 2015-07-15 20:39
the LLVM IR is kind of unreadable, but I thought I saw it call the sqeuclidean function, but that might have been before LLVM inlined the call.

In any event, know the problem is actually reference counting overhead is useful.

**Comment by pitrou** [comment] 2016-01-13 14:46
Changing the title to reflect current diagnosis: partial indexing of an array (or slicing, presumably) is not zero-cost as it creates a NRT-managed structure, incurring reference counting costs.

**Comment by jllanfranchi** [comment] 2021-10-08 18:12
Update for timings taken using Numba 0.54.0:

```python
@numba.jit(nopython=True)
def sqeuclidean(x, y):
    distance = 0.
    for n in range(x.shape[0]):
        distance += (x[n] - y[n])**2
    return distance

@numba.jit(nopython=True)
def cdist(x, y):
    D = np.zeros((x.shape[0], y.shape[0]))
    for i in range(x.shape[0]):
        for j in range(y.shape[0]):
            for d in range(x.shape[1]):
                D[i, j] += (x[i, d] - y[i, d])**2
    return D

@numba.jit(nopython=True)
def cdist_func(x, y):
    D = np.empty((x.shape[0], y.shape[0]))
    for i in range(x.shape[0]):
        for j in range(y.shape[0]):
            D[i, j] = sqeuclidean(x[i], y[i])
    return D

a = np.random.random_sample((1000, 10))
b = np.random.random_sample((1000, 10))

%timeit cdist(a, b)
%timeit cdist_func(a, b)
```
Output:
```
16.9 ms ± 489 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.17 ms ± 77.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So... now the function-call version is ~3x _faster_ than bare version (which seems odd to me). Other things I tried:

1. Switching `(...)**2` -> `np.square(...)` shaves 2-3 ms off of `cdist` but increases the runtime of `cdist_func` by ~0.2 ms.
2. Switching to `diff = x[n] - y[n]; distance += diff * diff` instead shaves another 1.3 ms off of `cdist` and increases `cdist_func` by another 0.02 ms.

Maybe the increases in runtime of `cdist_func` are insignificant, but the _decreases_ in runtime for `cdist_func` seems "real."

In the end, the best timings I can get for the two functions are 12.1 ms for `cdist` and 5.17 ms for `cdist_func`.

**Comment by gmarkall** [comment] 2021-12-07 11:30
I see similar timings.

In the `cdist_func` version, the loop is unrolled 8 times in `sqeuclidean`, whereas it is fully rolled in `cdist` - I'd imagine this goes some way towards explaining the difference in speed.

**Comment by gmarkall** [comment] 2021-12-07 11:34
Also, there are no relevant refcounts going on around the loop nests, so the original issue reported here is, I believe, resolved. I'm going to close this - if there's any further discussion to be had around loop unrolling / other performance optimization, it would be best to open a new issue to disambiguate it from the original issue reported here.

**Closed by gmarkall** 2021-12-07 11:34 UTC
Labels: performance - run time
