### ISSUE TITLE
CUDA: Stream Should Be Used for Debug Transfers

### ISSUE THREAD

**Issue by njwhite** [numba/numba#2735] opened 2018-02-08 09:26 UTC
https://github.com/numba/numba/blob/ee5d0d3cd2c25565206c5408ad8fb5da9a21d28c/numba/cuda/compiler.py#L561 & https://github.com/numba/numba/blob/master/numba/cuda/compiler.py#L569 

@sklam too late for v0.38? Getting 999-code driver errors occasionally.

**Comment by seibert** [comment] 2018-02-08 14:19
If this is triggering problems in your code, we can fix it between the RC and final Numba release.

**Comment by sklam** [comment] 2018-02-08 15:43
Shouldn't stream0 be synchronizing?  The code is using the implicit sync.

**Comment by sklam** [comment] 2018-02-08 15:43
In debug mode, we need to wait til the kernel is done and check the exception status.

**Comment by njwhite** [comment] 2018-02-08 17:55
I'm seeing errors like the below (from `cuda-memcheck` when copying the debug arrays back to the host. It's not particularly helpful :/

````
========= CUDA-MEMCHECK
========= Program hit CUDA_ERROR_UNKNOWN (error 999) due to "unknown error" on CUDA API call to cuMemcpyDtoH_v2. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:C:\windows\system32\nvcuda.dll (cuD3D10MapResources + 0x1b4332) [0x1c195c]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\DLLs\_ctypes.pyd (PyInit__ctypes + 0x1abb) [0xbfc3]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\DLLs\_ctypes.pyd [0x55dc]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\DLLs\_ctypes.pyd [0x5015]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\DLLs\_ctypes.pyd [0x4a8f]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x37b5) [0x1a79b5]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyFunction_SetAnnotations + 0xbb4) [0x112ea4]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x37b5) [0x1a79b5]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x436) [0x1aacb6]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e2) [0x1aaa62]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x36b3) [0x1a78b3]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyFunction_SetAnnotations + 0xbb4) [0x112ea4]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x37b5) [0x1a79b5]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x436) [0x1aacb6]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e2) [0x1aaa62]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x36b3) [0x1a78b3]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x436) [0x1aacb6]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e2) [0x1aaa62]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x1101) [0x1a5301]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x436) [0x1aacb6]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e2) [0x1aaa62]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x1101) [0x1a5301]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyFunction_SetAnnotations + 0xbb4) [0x112ea4]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x37b5) [0x1a79b5]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyFunction_SetAnnotations + 0xbb4) [0x112ea4]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x37b5) [0x1a79b5]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x56a9) [0x1a98a9]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x436) [0x1aacb6]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e2) [0x1aaa62]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x1101) [0x1a5301]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x2d2) [0x1aab52]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_FastCallDict + 0x6e) [0xdefae]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call_Prepend + 0x94) [0xdf134]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_Call + 0x78) [0xdee78]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyType_Ready + 0x47db) [0x14fc9b]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyType_Modified + 0x16d2) [0x143652]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_FastCallDict + 0xe0) [0xdf020]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyObject_FastCallKeywords + 0x8a) [0xdf49a]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x1e9) [0x1aaa69]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_EvalFrameDefault + 0x1101) [0x1a5301]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x2d2) [0x1aab52]
=========     Host Frame:C:\Users\me\AppData\Local\Continuum\Anaconda3\python36.dll (PyEval_GetFuncDesc + 0x36c) [0x1aabec]
````

**Comment by sklam** [comment] 2018-02-12 16:08
It's blowing up in a deprecated CUDA + Direct3D API (http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__D3D10__DEPRECATED.html)

**Comment by sklam** [comment] 2018-02-12 16:09
What you may be seeing could be an effect on synchronization.  So in non-debug mode, putting a `cuda.synchronize()` after the affected kernel call should reveal the use problem.

**Comment by njwhite** [comment] 2018-02-12 17:46
Hm, should a debug mode kernel automatically synchronise after it's called, then? Localised failures are much easier to debug!

**Comment by sklam** [comment] 2018-02-13 16:36
Yes, it already does.  The device_to_host memcpy uses stream 0 and it's implicitly synchronizing.

**Comment by sklam** [comment] 2018-02-15 15:53
This probably is not a bug with the reason as described in the title.  Closing for now.

**Closed by sklam** 2018-02-15 15:53 UTC

**Comment by njwhite** [comment] 2018-03-02 22:27
@sklam you were right! [Window was killing my kernel](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys). Setting the `TdrLevel` key in that link to `0` "fixed" this issue.
