### ISSUE TITLE
Feature Request: axis argument in np.nan[sum | mean | std | var | max | min | median]

### ISSUE THREAD

**Issue by mroeschke** [numba/numba#6610] opened 2021-01-02 00:18 UTC
---

## Feature request

Over in pandas, I am trying to implement a windowing aggregation over an 2D array that utilizes numba: https://github.com/pandas-dev/pandas/issues/15095

I would like to utilize `np.nansum(window, axis=0)` for example to return a 2D result, but as I see documented the `axis` keyword is currently not supported https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#reductions

The particular functions I'd be interested in are `np.nansum`, `np.nanmean`, `np.nanmedian`, `np.nanstd`, `np.nanvar`, `np.nanmax`, and `np.nanmin`

Thanks!

**Comment by HPLegion** [comment] 2021-01-02 12:12
See also #1269

**Comment by esc** [comment] 2021-01-04 11:50
@mroeschke thank you for submitting this. I believe this is a duplicate of #1269 and can be closed and labelled as such.

**Closed by esc** 2021-01-04 11:50 UTC

**Comment by caniko** [comment] 2022-06-23 13:56
Not to be pedantic, but these functions aren't mentioned in the duplicate issue.

**Comment by esc** [comment] 2022-06-24 07:46
> Not to be pedantic, but these functions aren't mentioned in the duplicate issue.

feel free to add them to the duplicate, thank you!
