### ISSUE TITLE
njit(parallel=True) issue

### ISSUE THREAD

**Issue by vincentbonnetcg** [numba/numba#5001] opened 2019-12-22 04:28 UTC
Hello, 

**Brief**
I found a strange issue when using numba parallel. 
I have a tuple containing numpy array (basically an array of array) and looping over each array in the tuple. Unfortunately, when using parallel and numba.range, it crashes.

Here is a simple case to reproduce the issue.

**Code**
```
import numba
import numpy as np
@numba.njit(parallel=True)
def test_numba_parallel(myarray):
    result = [0] * len(myarray)
    for i in numba.prange(len(myarray)):
        result[i] = len(myarray[i])
    return result

@numba.njit
def test_numba_single(myarray):
    result = [0] * len(myarray)
    for i in range(len(myarray)):
        result[i] = len(myarray[i])
    return result


myarray = (np.empty(100),np.empty(50))
result = test_numba_single(myarray) # result = [100, 50]
#result = test_numba_parallel(myarray) # **Error**
```

**Error message when using parallel**
LoweringError: scalar type tuple(array(float64, 1d, C) x 2) given for non scalar argument #2

**Configuration :** 
- Numba Version 0.46.0
- Windows 10

Thanks, 
Let me know if you find a workaround or there is a possible fix in Numba.

## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by DrTodd13** [comment] 2019-12-22 17:10
@vincentbonnetcg The error message and perhaps the documentation can be improved but Numba does not support tuples passed to guvectorize and parallel=True uses this internally and so does not support tuples going from the non-parallel parts of a parallel=True function into the parallel parts.  You can easily fix this by changing the input from tuple to list as below.

```myarray = [np.empty(100),np.empty(50)]```

**Comment by vincentbonnetcg** [comment] 2019-12-22 22:56
Thanks @DrTodd13  for taking a look, your solution works for me. 
Unfortunately, I oversimplified my problem and Numba still failing with a complex data structure. 

I am trying to get to Numba to loop over an array of structure of array. 
The single threaded works when giving a tuple of structure of array. Anything else fail.

**Code**
```
import numba
import numpy as np

@numba.njit(parallel=True)
def test_numba_parallel(myarray):
    result = [0] * len(myarray)
    for i in numba.prange(len(myarray)):
        result[i] = len(myarray[i]['x'])
    return result

@numba.njit
def test_numba_single(myarray):
    result = [0] * len(myarray)
    for i in range(len(myarray)):
        result[i] = len(myarray[i]['x'])
    return result

# structure of array dtype
dtype_soa_dict = {}
dtype_soa_dict['names'] = ['x', 'v']
dtype_soa_dict['formats'] = []
dtype_soa_dict['formats'].append((np.float64, (5, 2)))
dtype_soa_dict['formats'].append((np.float64, (5, 2)))
dtype_soa = np.dtype(dtype_soa_dict, align=True)

# Allocate an array of structure of array
myarray = []
for i in range(3):
    data = np.zeros(1, dtype=dtype_soa)[0]
    myarray.append(data)

# Single threaded function
result = test_numba_single(tuple(myarray)) # WORKS
#result = test_numba_single(myarray) # ERROR - LoweringError: use load_from_data_pointer() instead

# Multi threaded function
#result = test_numba_parallel(tuple(myarray)) # ERROR - The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.
#result = test_numba_parallel(myarray) # ERROR - LoweringError: use load_from_data_pointer() instead
```

**Memory Layout**
Data structure describing the example above.
[image of memory layout](https://github.com/vincentbonnetcg/Numerical-Bric-a-Brac/blob/master/img/memory_layout.png)

Any ideas to get numba to support an array of structured array ? 
Thanks,

**Comment by DrTodd13** [comment] 2019-12-23 04:55
@vincentbonnetcg It will have to wait until after the holiday break but then I can look into how guvectorize and parallel=True treat array of structure (AOS).  However, it is a well-known performance trick in many cases to convert AOS to struct of arrays (SOA) or in this case just one array named x and another named v.  Separate arrays are well supported.  That would be my recommendation.

**Comment by vincentbonnetcg** [comment] 2020-01-08 07:20
Hi @DrTodd13 , I was on holidays as well.  
I would expect the single thread and MT to accept similar data. Let me know if you find something.
Thanks

**Comment by stuartarchibald** [comment] 2020-02-19 16:25
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.

**Closed by stuartarchibald** 2020-02-19 16:25 UTC
Labels: ParallelAccelerator
