### ISSUE TITLE
CUDA functions can be compiled but not called with Tuple and UniTuple arguments

### ISSUE THREAD

**Issue by heyer2** [numba/numba#4405] opened 2019-08-05 02:12 UTC
As the title suggests, functions with `Tuple` or  `UniTuple` arguments can be compiled just fine, but are unable to actually be called without raising an exception. Here's an example using `UniTuple`:

```python
import numpy as np
from numba import cuda, types

n_array = 5
@cuda.jit(types.void(types.UniTuple(types.float32[:], n_array), types.float32[:]))
def test(arrays, out):
	i = cuda.threadIdx.x
	tmp = 0
	for arr in arrays:
		tmp += arr[i]
	out[i] = tmp

def main():
	n_elements = 3
	arrays_in = [k * np.ones(n_elements, np.float32) for k in range(n_array)]
	array_out = np.empty(n_elements, np.float32)
	test[1, n_elements](arrays_in, array_out)
	print("output:", array_out)

if __name__=="__main__": main()
```
I have no real knowledge about the internals of Numba,
but I found adding the following lines to `_prepare_args` of the `CUDAKernel` class:

```python
...
elif isinstance(ty, types.UniTuple) or isinstance(ty, types.Tuple):
    assert len(ty)==len(val)
    for t, v in zip(ty, val):
       self._prepare_args(t, v, stream, retr, kernelargs)
...
```

seems to fix the minimal example I provided.
I am using the latest version of Numba.

**Comment by stuartarchibald** [comment] 2019-08-05 09:15
Thanks for the report, I can reproduce. Seems like this could work, one of the core devs will take a look.

**Comment by alsrgv** [comment] 2020-01-30 07:44
Would be wonderful if this was fixed.

**Comment by seibert** [comment] 2020-01-30 15:01
@gmarkall : Can you take a look at this? (in your backlog of other CUDA things you are checking out...)  It does seem like a straightforward thing to fix since we unpack tuples, so there is no memory allocated data structure to worry about on the GPU.

**Comment by gmarkall** [comment] 2020-04-08 13:38
Whoops, just noticed this mention - assigning to myself.

**Comment by atait** [comment] 2020-10-07 08:32
This fix is a lifesaver. 
- It enables otherwise impossible patterns for variable number of arguments (including but not limited to @heyer2's example)
- It makes code significantly more readable and modular

Supporting `namedtuple` is also possible with this approach
```python
elif isinstance(ty, (types.UniTuple, types.Tuple, types.NamedUniTuple, types.NamedTuple)):
    ...
```

**Closed** 2020-11-26 16:58 UTC
Labels: CUDA, bug
