### ISSUE TITLE
tuple slicing fails in inlined functions

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#4691] opened 2019-10-11 09:05 UTC
Before submitting a bug report please ensure that you can check off these boxes:

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

0.46.0

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Here is the reproducer:

```python
import numpy as np
from numba import njit, types
from numba.extending import overload


def output_factory(array, dtype):
    pass


@overload(output_factory, inline='always')
def ol_output_factory(array, dtype):
    if isinstance(array, types.npytypes.Array):
        def impl(array, dtype):
            shape = array.shape[3:]
            return np.zeros(shape, dtype=dtype)

        return impl


@njit(nogil=True)
def fn(array):
    out = output_factory(array, array.dtype)
    return out


@njit(nogil=True)
def fn2(array):
    return np.zeros(array.shape[3:], dtype=array.dtype)


fn(np.ones((10, 20, 30, 40, 50)))

fn2(np.ones((10, 20, 30, 40, 50)))
```

The call to ``fn`` fails with the following:

```traceback
Traceback (most recent call last):
  File "test_inlining.py", line 30, in <module>
    fn(np.ones((10, 20, 30, 40, 50)))
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function output_factory at 0x7f9f5ac4ce18>) with argument(s) of type(s): (array(float64, 5d, C), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (tuple(int64 x 5), slice<a:b>)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at test_inlining.py (14)

File "test_inlining.py", line 14:
        def impl(array, dtype):
            shape = array.shape[3:]
            ^

    raised from /home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/typeinfer.py:951
In definition 1:
    TypingError: Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (tuple(int64 x 5), slice<a:b>)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at test_inlining.py (14)

File "test_inlining.py", line 14:
        def impl(array, dtype):
            shape = array.shape[3:]
            ^

    raised from /home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/typeinfer.py:951
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function output_factory at 0x7f9f5ac4ce18>)
[2] During: typing of call at test_inlining.py (22)


File "test_inlining.py", line 22:
def fn(array):
    out = output_factory(array, array.dtype)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

but the call to ``fn2`` succeeds.

I know the ``inline`` feature is new. Am I perhaps using it incorrectly?

**Comment by stuartarchibald** [comment] 2019-10-11 11:00
Thanks for the report and example, I can reproduce. The `inline` feature is indeed a really new and advanced feature, you are using it correctly, this is a bug.

Engineering notes:
What's happening is that the inliner is processing the function to be inlined into raw Numba IR, this is then injected into the call site. The issue presented is that the `getitem` use in the `impl` in the `output_factory` `@overload` needs to be a `static_getitem` for the code to compile. Were the `impl` function called as a stand-alone function, the `getitem` would be re-written as such by a rewrite pass.

The issue above occurs because in the effort to not compile functions unless they are actually going to be used (inlined functions may never be called in their compiled form) the typing of the overloaded function triggers a run through `numba.compiler.run_frontend` to type the function. The problem with doing this is that transforms such as the `GenericRewrites` pass will not run as `run_frontend` is very basic and does not make such calls, the result being that the IR obtained via this method is untypable in cases such as the above. The fix is to probably make the `run_frontend` function contain a custom pipeline that duplicates the default nopython pipeline up to the point of type inference and then run that.

The same issue will occur without the use of `@overload` as an untyped inline triggered via `@njit(inline='always')` will hit the same problem. e.g.
```python
import numpy as np
from numba import njit

@njit(nogil=True, inline='always')
def inline_me(array, dtype):
    shape = array.shape[3:]
    return np.zeros(shape, dtype=dtype)

@njit(nogil=True)
def foo(array):
    return inline_me(array, array.dtype)

foo(np.ones((10, 20, 30, 40, 50)))
```
I think this path can be fixed by conditionally running the `GenericRewrites` pass if the `InlineInlinables` pass reports it mutated the IR. It might be a good idea to rerun the untyped optimisations after inlining too, there may be more branches that can be pruned after the inlined constants are rewritten.

**Closed** 2020-05-29 20:33 UTC
Labels: bug
