### ISSUE TITLE
Implement np.gradient

### ISSUE THREAD

**Issue by holymonson** [numba/numba#6302] opened 2020-10-05 05:01 UTC
## Feature request

Implement `np.gradient`, it mainly depends on `np.diff`.

---
A simplest overload:
```python
@numba.extending.overload(np.gradient)
def np_gradient(f):
    def np_gradient_impl(f):
        out = np.empty_like(f, np.float64)
        out[1:-1] = (f[2:] - f[:-2]) / 2.0
        out[0] = f[1] - f[0]
        out[-1] = f[-1] - f[-2]
        return out

    return np_gradient_impl
```

**Comment by esc** [comment] 2020-10-05 07:52
@holymonson thanks for submitting this request to the Numba issue tracker. This is a duplicate of: https://github.com/numba/numba/issues/4074 so I will be closing this in favor of that PR.

**Closed by esc** 2020-10-05 07:52 UTC
