### ISSUE TITLE
Website menu bar broken on Safari

### ISSUE THREAD

**Issue by Benjamin-Lee** [numba/numba#3313] opened 2018-09-17 01:34 UTC
The picture says it all:

![pic](https://snag.gy/onZbH3.jpg)

**Comment by stuartarchibald** [comment] 2018-09-17 09:12
@Benjamin-Lee thanks for the report. Are you referring to the search box floating around underneath the  rest of the menu drop-downs, or that the menu drop-downs are a bit high up, or both :) ? I assume this is a visual issue opposed to a functional issue?

**Comment by seibert** [comment] 2018-09-17 14:42
Out of curiosity, what version of Safari is this?  I can't seem to reproduce this on Safari 11.1.1 (macOS) at any zoom level.

**Comment by Benjamin-Lee** [comment] 2018-09-17 15:51
Just a visual issue, but it does make reading the docs harder because in some cases it obscured content.

I'm running Safari 11.0.3 on macOS 10.13.3.

**Comment by stuartarchibald** [comment] 2018-09-17 16:58
I can reproduce on Safari 11.1.2. It also looks like that on Firefox 60.2.0 ESR Quantum on Linux, the dropdown alignment isn't quite so bad but the search bar is in the same misaligned place. Firefox 60.2 Quantum on OSX is ok it seems though. Guess its font size as @seibert noted.

**Comment by seibert** [comment] 2018-09-17 18:01
OK, I made a small CSS change to tighten up the spacing.  This will only take effect for newly generated docs, so I think we want this merged before 0.40.0 final is tagged.

**Comment by Benjamin-Lee** [comment] 2018-11-08 03:13
Still broken:

![pic](https://snag.gy/RI4Pbu.jpg)

**Comment by seibert** [comment] 2018-11-08 14:43
Are you referring to the Numba logo having a funny vertical offset?  It looks like the Search box wrapping part is fixed, which was the original goal.

I will keep fighting with the CSS on the other issue.

**Comment by Benjamin-Lee** [comment] 2018-11-08 19:38
Yep, sorry for not making that clear. The search box is now fixed but the logo runs off the menu bar.

**Closed** 2018-11-14 01:03 UTC
