### ISSUE TITLE
Function Factory not working with 0.20

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1325] opened 2015-07-21 13:42 UTC
Hi, I have numba 0.20.0
and when trying to run the following code (found on the documentation)

```
from numba import njit

def my_g_function(t):
    return 2 * t

def make_f(g):
    # Note: a new f() is compiled each time make_f() is called!
    @njit
    def f(x):
        return g(x) + g(-x)
    return f

f = make_f(my_g_function)
result = f(1)
```

I get the following error (note the duplication of the error)

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-5-2f7b2a041512> in <module>()
----> 1 result = f(1)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    157         assert not kws
    158         sig = tuple([self.typeof_pyval(a) for a in args])
--> 159         return self.compile(sig)
    160 
    161     def inspect_llvm(self, signature=None):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in compile(self, sig)
    320                                           self.py_func,
    321                                           args=args, return_type=return_type,
--> 322                                           flags=flags, locals=self.locals)
    323 
    324             # Check typing error if object mode is used

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    592     pipeline = Pipeline(typingctx, targetctx, library,
    593                         args, return_type, flags, locals)
--> 594     return pipeline.compile_extra(func)
    595 
    596 

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(self, func)
    315                 raise e
    316 
--> 317         return self.compile_bytecode(bc, func_attr=self.func_attr)
    318 
    319     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    324         self.lifted_from = lifted_from
    325         self.func_attr = func_attr
--> 326         return self._compile_bytecode()
    327 
    328     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in _compile_bytecode(self)
    579 
    580         pm.finalize()
--> 581         return pm.run(self.status)
    582 
    583 

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
    207                     # No more fallback pipelines?
    208                     if is_final_pipeline:
--> 209                         raise patched_exception
    210                     # Go to next fallback pipeline
    211                     else:

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
    199             for stage, stage_name in self.pipeline_stages[pipeline_name]:
    200                 try:
--> 201                     res = stage()
    202                 except _EarlyPipelineCompletion as e:
    203                     return e.result

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in stage_nopython_frontend(self)
    412                 self.args,
    413                 self.return_type,
--> 414                 self.locals)
    415 
    416         with self.fallback_context('Function "%s" has invalid return type'

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    706         infer.seed_type(k, v)
    707 
--> 708     infer.build_constrain()
    709     infer.propagate()
    710     typemap, restype, calltypes = infer.unify()

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in build_constrain(self)
    384         for blk in utils.itervalues(self.blocks):
    385             for inst in blk.body:
--> 386                 self.constrain_statement(inst)
    387 
    388     def propagate(self):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in constrain_statement(self, inst)
    504     def constrain_statement(self, inst):
    505         if isinstance(inst, ir.Assign):
--> 506             self.typeof_assign(inst)
    507         elif isinstance(inst, ir.SetItem):
    508             self.typeof_setitem(inst)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in typeof_assign(self, inst)
    536                                              src=value.name, loc=inst.loc))
    537         elif isinstance(value, (ir.Global, ir.FreeVar)):
--> 538             self.typeof_global(inst, inst.target, value)
    539         elif isinstance(value, ir.Arg):
    540             self.typeof_arg(inst, inst.target, value)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in typeof_global(self, inst, target, gvar)
    601         else:
    602             raise TypingError("Untyped global name '%s'" % gvar.name,
--> 603                               loc=inst.loc)
    604 
    605     def typeof_expr(self, inst, target, expr):

TypingError: Failed at nopython (nopython frontend)
Untyped global name 'g'
File "<ipython-input-3-10e459892604>", line 5

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-5-2f7b2a041512> in <module>()
----> 1 result = f(1)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    157         assert not kws
    158         sig = tuple([self.typeof_pyval(a) for a in args])
--> 159         return self.compile(sig)
    160 
    161     def inspect_llvm(self, signature=None):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in compile(self, sig)
    320                                           self.py_func,
    321                                           args=args, return_type=return_type,
--> 322                                           flags=flags, locals=self.locals)
    323 
    324             # Check typing error if object mode is used

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    592     pipeline = Pipeline(typingctx, targetctx, library,
    593                         args, return_type, flags, locals)
--> 594     return pipeline.compile_extra(func)
    595 
    596 

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(self, func)
    315                 raise e
    316 
--> 317         return self.compile_bytecode(bc, func_attr=self.func_attr)
    318 
    319     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    324         self.lifted_from = lifted_from
    325         self.func_attr = func_attr
--> 326         return self._compile_bytecode()
    327 
    328     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in _compile_bytecode(self)
    579 
    580         pm.finalize()
--> 581         return pm.run(self.status)
    582 
    583 

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
    207                     # No more fallback pipelines?
    208                     if is_final_pipeline:
--> 209                         raise patched_exception
    210                     # Go to next fallback pipeline
    211                     else:

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
    199             for stage, stage_name in self.pipeline_stages[pipeline_name]:
    200                 try:
--> 201                     res = stage()
    202                 except _EarlyPipelineCompletion as e:
    203                     return e.result

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in stage_nopython_frontend(self)
    412                 self.args,
    413                 self.return_type,
--> 414                 self.locals)
    415 
    416         with self.fallback_context('Function "%s" has invalid return type'

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    706         infer.seed_type(k, v)
    707 
--> 708     infer.build_constrain()
    709     infer.propagate()
    710     typemap, restype, calltypes = infer.unify()

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in build_constrain(self)
    384         for blk in utils.itervalues(self.blocks):
    385             for inst in blk.body:
--> 386                 self.constrain_statement(inst)
    387 
    388     def propagate(self):

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in constrain_statement(self, inst)
    504     def constrain_statement(self, inst):
    505         if isinstance(inst, ir.Assign):
--> 506             self.typeof_assign(inst)
    507         elif isinstance(inst, ir.SetItem):
    508             self.typeof_setitem(inst)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in typeof_assign(self, inst)
    536                                              src=value.name, loc=inst.loc))
    537         elif isinstance(value, (ir.Global, ir.FreeVar)):
--> 538             self.typeof_global(inst, inst.target, value)
    539         elif isinstance(value, ir.Arg):
    540             self.typeof_arg(inst, inst.target, value)

/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in typeof_global(self, inst, target, gvar)
    601         else:
    602             raise TypingError("Untyped global name '%s'" % gvar.name,
--> 603                               loc=inst.loc)
    604 
    605     def typeof_expr(self, inst, target, expr):

TypingError: Failed at nopython (nopython frontend)
Untyped global name 'g'
File "<ipython-input-3-10e459892604>", line 5
```

Another strange fact is that I'm using Jupyter notebook and this simple code fails to terminate execution most of the cases, leaving me no option bu to restart the kernel and re-run the code

**Comment by seibert** [comment] 2015-07-21 14:32
The problem is that `my_g_function` also needs to be `@njit` if you want to call it from a nopython mode function.

The error message doesn't make this clear (which we need to fix) and the example from the documentation also should clarify this point.

**Comment by stuartarchibald** [comment] 2019-03-27 14:12
As of 0.43.1 this produces:
```python
Traceback (most recent call last):
  File "issue1325.py", line 14, in <module>
    result = f(1)
  File "<path>/numba/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<path>/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'g': cannot determine Numba type of <class 'function'>

File "issue1325.py", line 10:
    def f(x):
        return g(x) + g(-x)
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
[the docs](http://numba.pydata.org/numba-doc/latest/user/faq.html#can-i-pass-a-function-as-an-argument-to-a-jitted-function) also now say:
```
Can I pass a function as an argument to a jitted function?

As of Numba 0.39, you can, so long as the function argument has also been JIT-compiled:
```
I think both items are addressed. Closing.

**Closed by stuartarchibald** 2019-03-27 14:12 UTC
