### ISSUE TITLE
Memory leak in JIT function with numpy arrays

### ISSUE THREAD

**Issue by cgorski** [numba/numba#5427] opened 2020-03-25 20:01 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have a script containing two JIT functions. When executing with JIT, they seem to leak memory. When they execute non-JIT with the standard interpreter, they do not leak memory. 

Tried with numba 0.48.0 and numba 0.49.0dev0, with numpy 1.18.2.

```python
import numba
rtsys = numba.runtime.rtsys
import psutil
import numpy as np

@numba.njit
def jit_neighbors(y, x, h, w):
    n = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for p in n:
        yield ((p[0] + y) % h, (p[1] + x) % w)

@numba.njit
def jit_calc_cycle(o_uni, nv, h, w):
    n_uni = np.zeros((h, w))
    for y in range(0, h):
        for x in range(0, w):
            for e in jit_neighbors(y=y, x=x, h=h, w=w):
                found = False
                y2 = e[0]
                x2 = e[1]
                if o_uni[y][x] == (o_uni[y2][x2] + 1) % nv:
                    found = True
                    n_uni[y][x] = o_uni[y2][x2]
                    break
                if not found:
                    n_uni[y][x] = o_uni[y][x]
    return n_uni

def main():
    num_values = 8
    height = 100
    width = 100

    num_array = np.random.randint(num_values, size=(height, width))

    for i in range(10):
        num_array = jit_calc_cycle(num_array, num_values, height, width)
        print(proc.memory_full_info())
        print(rtsys.get_allocation_stats())

if __name__ == "__main__":
    proc = psutil.Process()
    print(proc.memory_full_info())
    main()

```

Output where memory allocation seems to exceed frees:

```bash
pfullmem(rss=96940032, vms=298278912, shared=55787520, text=3883008, lib=0, data=84439040, dirty=0, uss=94605312, pss=95118336, swap=0)
pfullmem(rss=109858816, vms=310120448, shared=57065472, text=3883008, lib=0, data=96264192, dirty=0, uss=107708416, pss=108221440, swap=0)
nrt_mstats(alloc=20002, free=11547, mi_alloc=10002, mi_free=5774)
pfullmem(rss=114192384, vms=314228736, shared=57126912, text=3883008, lib=0, data=100364288, dirty=0, uss=111816704, pss=112329728, swap=0)
nrt_mstats(alloc=40004, free=25049, mi_alloc=20004, mi_free=12526)
pfullmem(rss=114462720, vms=314642432, shared=57126912, text=3883008, lib=0, data=100777984, dirty=0, uss=112193536, pss=112706560, swap=0)
nrt_mstats(alloc=60006, free=38999, mi_alloc=30006, mi_free=19502)
pfullmem(rss=114462720, vms=314642432, shared=57126912, text=3883008, lib=0, data=100777984, dirty=0, uss=112193536, pss=112706560, swap=0)
nrt_mstats(alloc=80008, free=53285, mi_alloc=40008, mi_free=26646)
pfullmem(rss=114733056, vms=314933248, shared=57126912, text=3883008, lib=0, data=101068800, dirty=0, uss=112517120, pss=113030144, swap=0)
nrt_mstats(alloc=100010, free=67615, mi_alloc=50010, mi_free=33812)
pfullmem(rss=115273728, vms=315342848, shared=57126912, text=3883008, lib=0, data=101478400, dirty=0, uss=112939008, pss=113452032, swap=0)
nrt_mstats(alloc=120012, free=81771, mi_alloc=60012, mi_free=40891)
pfullmem(rss=115544064, vms=315760640, shared=57126912, text=3883008, lib=0, data=101896192, dirty=0, uss=113373184, pss=113886208, swap=0)
nrt_mstats(alloc=140014, free=95733, mi_alloc=70014, mi_free=47873)
pfullmem(rss=116084736, vms=316194816, shared=57126912, text=3883008, lib=0, data=102330368, dirty=0, uss=113819648, pss=114332672, swap=0)
nrt_mstats(alloc=160016, free=109497, mi_alloc=80016, mi_free=54756)
pfullmem(rss=116625408, vms=316645376, shared=57126912, text=3883008, lib=0, data=102780928, dirty=0, uss=114294784, pss=114807808, swap=0)
nrt_mstats(alloc=180018, free=122925, mi_alloc=90018, mi_free=61471)
pfullmem(rss=117166080, vms=317116416, shared=57126912, text=3883008, lib=0, data=103251968, dirty=0, uss=114782208, pss=115295232, swap=0)
nrt_mstats(alloc=200020, free=136113, mi_alloc=100020, mi_free=68066)

```

**Comment by cgorski** [comment] 2020-03-26 19:54
Updated to reflect that I tested  the latest release of numba, 0.49.0dev0. I also tested with the latest commits to master.

**Comment by cgorski** [comment] 2020-03-26 19:55
Also - would like to note that with any reasonable size arrays for my purposes, this is killed due to the process running out of memory on my Ubuntu instances.

**Comment by stuartarchibald** [comment] 2020-03-26 21:17
Thanks for the report. If you inline `jit_neighbors` / make it not a generator, do you see the same? Generators are known to be a bit leaky from other reports.

**Comment by cgorski** [comment] 2020-03-26 21:39
Thanks, it does look like the generator is what is causing the issue.  Here's the output with the generator turned into a list comprehension running on numby 0.48.0:

```python
(venv) ubuntu@ip-172-16-7-97:~/pycyclicspace/cyclicspace$ python3 testmem2.py
pfullmem(rss=96759808, vms=292773888, shared=56569856, text=3883008, lib=0, data=83460096, dirty=0, uss=93024256, pss=94111744, swap=0)
pfullmem(rss=110665728, vms=305577984, shared=57532416, text=3883008, lib=0, data=96256000, dirty=0, uss=106885120, pss=107972608, swap=0)
nrt_mstats(alloc=40002, free=40001, mi_alloc=20002, mi_free=20001)
pfullmem(rss=115630080, vms=310722560, shared=57647104, text=3883008, lib=0, data=101392384, dirty=0, uss=111943680, pss=113031168, swap=0)
nrt_mstats(alloc=80004, free=80003, mi_alloc=40004, mi_free=40003)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=120006, free=120005, mi_alloc=60006, mi_free=60005)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=160008, free=160007, mi_alloc=80008, mi_free=80007)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=200010, free=200009, mi_alloc=100010, mi_free=100009)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=240012, free=240011, mi_alloc=120012, mi_free=120011)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=280014, free=280013, mi_alloc=140014, mi_free=140013)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=320016, free=320015, mi_alloc=160016, mi_free=160015)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=360018, free=360017, mi_alloc=180018, mi_free=180017)
pfullmem(rss=115879936, vms=311046144, shared=57647104, text=3883008, lib=0, data=101715968, dirty=0, uss=112185344, pss=113272832, swap=0)
nrt_mstats(alloc=400020, free=400019, mi_alloc=200020, mi_free=200019)
```

I'm not sure if it is significant that there is one less free than alloc per iteration.

**Comment by cgorski** [comment] 2020-03-26 21:39
Here is the modified code for the output above:

```python
import numba
rtsys = numba.runtime.rtsys
import psutil
import numpy as np



@numba.njit
def jit_calc_cycle(o_uni, nv, h, w):
    n_uni = np.zeros((h, w))
    count = 1
    for y in range(0, h):
        for x in range(0, w):
            n = [(-1, 0), (1, 0), (0, -1), (0, 1)]
            neighbors = [((p[0] + y) % h, (p[1] + x) % w) for p in n]
            for e in neighbors:
                found = False
                y2 = e[0]
                x2 = e[1]

                if o_uni[y][x] == (o_uni[y2][x2] + 1) % nv:
                    found = True
                    n_uni[y][x] = o_uni[y2][x2]
                    break
                if not found:
                    n_uni[y][x] = o_uni[y][x]
                count +=1
    return n_uni

def main():
    num_values = 8
    height = 100
    width = 100

    num_array = np.random.randint(num_values, size=(height, width))

    for i in range(10):
        num_array = jit_calc_cycle(num_array, num_values, height, width)
        print(proc.memory_full_info())
        print(rtsys.get_allocation_stats())

if __name__ == "__main__":
    proc = psutil.Process()
    print(proc.memory_full_info())
    main()
```

**Comment by stuartarchibald** [comment] 2020-03-26 21:46
Thanks for checking, this is likely the same root cause as https://github.com/numba/numba/issues/5350.

**Comment by cgorski** [comment] 2020-03-28 23:12
Thank you for the work, happy to help.

**Comment by stuartarchibald** [comment] 2022-01-04 14:30
Closing as a duplicate of #5350. Thanks.

**Closed by stuartarchibald** 2022-01-04 14:30 UTC
Labels: bug, duplicate
