### ISSUE TITLE
np.where with boolean fails without parallel=True

### ISSUE THREAD

**Issue by sleighsoft** [numba/numba#4530] opened 2019-09-06 09:44 UTC
Works
```python
import numba
import numpy as np

@numba.njit(parallel=True)
def t(k):
    return np.where(k == False)

t(np.zeros([5,5]))
```

Works
```python
import numba
import numpy as np

@numba.njit()
def t(k):
    return np.where(k == np.array(False, np.bool_))

t(np.zeros([5,5]))
```

Fails
```python
import numba
import numpy as np

@numba.njit()
def t(k):
    return np.where(k == False)

t(np.zeros([5,5]))
```
---

> LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
> non-numeric type in Num
> 
> File "<ipython-input-5-f6117da47e15>", line 3:
> def t(k):
>     return np.where(k == False)

---

**Comment by rjenc29** [comment] 2019-09-07 06:42
Hi

Maybe a tweak in `numba.npyufunc.array_exprs._arr_expr_to_ast` along these lines:

```python
    elif isinstance(expr, ir.Const):
        if isinstance(expr.value, bool):  # introduce if-gate here...
            return ast.Constant(expr.value), {}
        return ast.Num(expr.value), {}
    raise NotImplementedError(
        "Don't know how to translate array expression '%r'" % (expr,))
```

...would do the trick?

**Comment by luk-f-a** [comment] 2019-09-07 06:47
I think this is not related to `np.where` but to the integer to boolean comparison because this fails in the same way.

```python
import numba
import numpy as np

@numba.njit()
def t(k):
    return (k == False)

t(np.zeros([5,5]))
```

**Comment by rjenc29** [comment] 2019-09-07 06:50
I agree

**Comment by esc** [comment] 2019-09-09 09:58
@sleighsoft thanks for submitting this to the Numba issue tracker. It is appreciated. For reference, I am indeed able to reproduce this. Just in case anyone is looking for a workaround, the following should probably work:

```
import numba
import numpy as np

@numba.njit()
def t(k):
    return (k == np.bool(False))

t(np.zeros([5,5]))
```

**Comment by stuartarchibald** [comment] 2019-09-09 10:38
Would recommend applying @rjenc29's suggestion as a fix and adding test(s).

**Comment by stuartarchibald** [comment] 2021-12-15 17:16
As of mainline for 0.55, the both the OP and the MWR in https://github.com/numba/numba/issues/4530#issuecomment-529079933 work as expected. Closing assuming fixed.

**Closed by stuartarchibald** 2021-12-15 17:16 UTC
Labels: bug
