### ISSUE TITLE
Python crashes for numba 0.44.1 (list.append not threadsafe)

### ISSUE THREAD

**Issue by qinxuye** [numba/numba#4206] opened 2019-06-20 07:09 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

## Code to reproduce the crash

I wrote a jit decorated function in the IPython.

```python
import numpy as np
import numba as nb

@nb.njit(parallel=True)
def nb_func(x, y, threshold):
    ret = []
    for i in nb.prange(x.shape[0]):
        for j in range(y.shape[0]):
            val = np.dot(x[i], y[j])
            if val >= threshold:
                ret.append([i, j, val])
    return np.array(ret)

a = np.random.rand(15000, 256)
```

Then I call the function by

```python
nb_func(a, a, 78.0)
```

Mostly, it works, but sometimes it crashes in a small chance. But if I call it twice, the crash would happen in a great chance.

## Environment

```
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
0.44.1
Darwin-17.7.0-x86_64-i386-64bit
```

**Comment by stuartarchibald** [comment] 2019-06-20 09:13
Thanks for the report. Numba's `list.append` is not thread safe and in the sample code `ret.append` is being called in the `prange` driven loop. That will most likely be the reason for the "crashes", I imagine they are taking the form of `SIGSEGV`'s?

To work around this the code will need to use a preallocated data structure to hold the information `(i, j, val)` and then each thread will need to write to a slot in that structure. I'm not sure how easy this will be to write and also get a decent performance gain.

**Comment by stuartarchibald** [comment] 2019-06-20 09:14
xref: https://github.com/numba/numba/issues/2408

**Comment by sklam** [comment] 2019-07-02 13:05
As noted in numba core-devs discussion, our shortterm fix is to blacklist all mutable containers.

**Comment by stuartarchibald** [comment] 2021-04-14 16:13
Documented here https://numba.readthedocs.io/en/latest/user/parallel.html#unsupported-operations

Closing as a duplicate of #2408

**Closed by stuartarchibald** 2021-04-14 16:13 UTC
Labels: bug, duplicate
