### ISSUE TITLE
numpy.lib.recfunctions

### ISSUE THREAD

**Issue by avanchev** [numba/numba#5203] opened 2020-02-05 16:32 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hello,

I am trying to use numba for fast joining two arrays of type unaligned array(Record(a[type=int64;offset=0],b[type=int64;offset=8],c[type=float64;offset=16];24;False), 1d, C).

I would use pandas but one of the arrays has 30 million records and the other 200 records.

Can you please add numpy.lib.recfunctions and numpy.lib.recfunctions.join_by functionality to numba?

Thanks

**Comment by avanchev** [comment] 2020-02-05 16:35
import numpy.lib.recfunctions as rfn
@njit
def join_df_2():
    a = np.array([(1, 10.), (2, 20.), (3, 30.)], dtype=[('id', int), ('A', float)])
    b = np.array([(2, 20., 15), (3, 30., 25), (4, 400., 35)], dtype=[('id', int), ('A', float), ('C', int)])
    res = rfn.join_by(['id','A'], a, b, jointype='inner', usemask=False)['C']
    
    return res

join_df_2()

**Comment by esc** [comment] 2020-02-05 18:08
@avanchev thanks for submitting this. It looks like a duplicate of #5202 ?

**Comment by avanchev** [comment] 2020-02-05 21:04
My mistake. Same yes. 

Kind Regards,

Atanas Vanchev. 
347-296-9725

**Comment by esc** [comment] 2020-02-06 12:32
@avanchev thanks for reporting back, will close this one as a duplicate.

**Closed** 2020-02-06 12:33 UTC
Labels: duplicate
