### ISSUE TITLE
Ufunc method incompatibility with Numpy 1.21

### ISSUE THREAD

**Issue by mhostetter** [numba/numba#7175] opened 2021-07-01 16:49 UTC
Using ufunc methods of Numba-generated ufuncs doesn't work with Numpy 1.21. In Numpy 1.21 they added [argument checking](https://numpy.org/devdocs/release/1.21.0-notes.html#error-type-changes-in-universal-functions) to ufuncs. It seems to have implications here.

Numpy complains that exactly two arguments are required, but two arguments are passed in. So I'm unsure what the actual error is.

Numpy version: 1.21.0
Numba version: 0.53.1

## Minimal example

```python
# File bug.py
import numpy as np
import numba

print("numpy version:", np.__version__)
print("numba version", numba.__version__)

def my_xor(x, y):
    return x ^ y

xor_ufunc = numba.vectorize("int64(int64, int64)", nopython=True)(my_xor)

x = np.array([1, 7], dtype=np.int64)
y = np.array([3, 4], dtype=np.int64)
z = xor_ufunc(x, y)
print("x:", x)
print("y:", y)
print("my_xor(x, y):", z)

z2 = xor_ufunc.outer(x, y)
print("my_xor.outer(x, y):\n", z2)
```

## Output with Numpy 1.20.3

```python
In [1]: %run bug.py                                                                                                                          
numpy version: 1.20.3
numba version 0.53.1
x: [1 7]
y: [3 4]
my_xor(x, y): [2 3]
my_xor.outer(x, y):
 [[2 5]
 [4 3]]
```

## Output with Numpy 1.21.0

```python
In [1]: %run bug.py                                                                                                                          
numpy version: 1.21.0
numba version 0.53.1
x: [1 7]
y: [3 4]
my_xor(x, y): [2 3]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/repos/galois/bug.py in <module>
     18 print("my_xor(x, y):", z)
     19 
---> 20 z2 = xor_ufunc.outer(x, y)
     21 print("my_xor.outer(x, y):\n", z2)

TypeError: exactly two arguments expected
```

**Comment by gmarkall** [comment] 2021-07-01 16:55
Thanks for the report! NumPy 1.21 is not yet supported, but this will be looked at as part of supporting it.

**Comment by gmarkall** [comment] 2021-07-01 16:56
#7176 created to track items needed for NumPy 1.21 support.

**Comment by gmarkall** [comment] 2021-08-02 09:33
I've removed needtriage so the stale bot doesn't turn up on this issue again.

**Comment by seberg** [comment] 2021-09-30 17:32
I completely randomly stumbled on this issue.  It seems fairly likely to me that this is a NumPy issue!  Please make sure to bug me/us about this type of thing!
Do you think the reduce crash could be a similar problem?

**Comment by seberg** [comment] 2021-09-30 17:53
OK, nevermind. I thought the problem here might be that NumPy does not take into account the possible existance of [`PY_VECTORCALL_ARGUMENTS_OFFSET` (and uses the NARGS macro)](https://docs.python.org/3/c-api/call.html#c.PyVectorcall_NARGS).  This may still be a bug in NumPy, but not what is causing this.

Trying it out, NumPy actually reports 0 arguments being passed.  Which means the problem is quite different: It looks like Numba is calling the NumPy method slot directly in C, but simply assumes the method is a normal Python method and not a vectorcall/fastcall one?  I guess as a micro-optimization to avoid using `PyObject_Call`?

The reduction crash seems like exactly the same problem.

**Comment by seberg** [comment] 2021-09-30 18:03
Yeah, the code below will not work because it does not know about vectorcall.  That is a bit unfortunate, I hope numba can easily catch up and use the vectorcall protocol on newer NumPy versions.

https://github.com/numba/numba/blob/39271156a52c58ca18b15aebcb1c85e4a07e49ed/numba/np/ufunc/_internal.c#L289L351

**Comment by rekado** [comment] 2021-11-19 21:25
I'm just a curious bystander, but I'd like to note that numpy 1.21.3 will become the default numpy in GNU Guix in a few days.  We'll keep around numpy 1.20 specifically for numba, but it will complicate the installation of numba together with other Python packages using numpy 1.21 by default.

I'd be happy to upgrade numba in Guix as soon as compatibility with numpy 1.21 is achieved.  (Subscribing to this issue to be get notification when this happens.)

Good luck!

**Comment by stuartarchibald** [comment] 2021-11-22 12:25
@rekado Numba 0.55 release candidates will be out within the next week or so (hopefully!), these will have NumPy 1.21.x series support. A post will be made to https://numba.discourse.group/c/announcements/ when RC builds are shipped.

**Comment by stuartarchibald** [comment] 2021-11-23 12:01
Fixed by the now merged https://github.com/numba/numba/pull/7483, which includes the C code changes from #7449. Closing.

**Closed by stuartarchibald** 2021-11-23 12:01 UTC
Labels: numpy
