### ISSUE TITLE
Avoid _raise_errors class attribute in BaseTypeInference

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#5681] opened 2020-05-07 15:50 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

`BaseTypeInference` class has `_raise_errors` as attribute [here](https://github.com/numba/numba/blob/1ea770564cb3c0c6cb9d8ab92e7faf23cd4c4c19/numba/core/typed_passes.py#L80), which is set to False in `PartialTypeInference` [here](https://github.com/numba/numba/blob/1ea770564cb3c0c6cb9d8ab92e7faf23cd4c4c19/numba/core/typed_passes.py#L157). This seems extremely dangerous, since type inference can be called recursively, potentially changing this global value. This attribute is checked when assigning a function's return type [here](https://github.com/numba/numba/blob/1ea770564cb3c0c6cb9d8ab92e7faf23cd4c4c19/numba/core/typed_passes.py#L100). I don't have a small reproducer yet, but this can cause strange errors down the line.

Why is this attribute a class attribute instead of instance attribute? Also, why is it checked for assigning return type?

**Comment by stuartarchibald** [comment] 2020-05-11 09:49
Thanks for the report. This was added to help with partial type inference. If you could please create a reproducer when it becomes clearer how to trigger it it would be most helpful, thanks.

**Comment by sklam** [comment] 2020-05-11 18:16
@ehsantn, I don't think it is a concern that `_raise_errors` would be changed. When it is assigned in the class as class attribute, it is unique to the class. It's subclasses will have a fresh variable.

i.e. 

```python

In [1]: class A:
   ...:     opt = 100
   ...:

In [2]: class B(A):
   ...:     opt = 200
   ...:

In [3]: B.opt, A.opt
Out[3]: (200, 100)
```

The `_raise_errors` is controlling whether the type-inference should report errors. The `return_type` coming back from `type_inference_stage` could be incorrect if `_raise_errors = False` because type-inference is not complete.  I would also add that this is a hack to make `PartialTypeInference` work without much change.

**Comment by ehsantn** [comment] 2020-05-11 18:47
Thanks for the clarification @sklam. Makes sense. I'll investigate further and update this.

**Comment by sklam** [comment] 2020-05-12 14:24
ok, i'll close this for now. Reopen if you have any update.

**Closed by sklam** 2020-05-12 14:24 UTC
Labels: more info needed, needtriage
