### ISSUE TITLE
doc and impl of RewriteArrayExprs are inconsistent

### ISSUE THREAD

**Issue by dlee992** [numba/numba#7967] opened 2022-04-07 09:28 UTC
```
def test_single_array_expr():
    def _test_impl(array):
        ret = array >= 0.1
        return ret

    jitted = numba.jit()(_test_impl)
    arr = np.random.rand(10)
    jit_ret = jitted(arr)
```

Code above will be rewritten by `RewriteArrayExprs` Pass. But `array >= 0.1` only has one operator. Is it necessary to rewrite this  expression, since loop fusion and shortcut deforestation optimizations don't seem to work?
And in numba developer doc, it wrote (https://numba.readthedocs.io/en/latest/developer/rewrites.html):

> RewriteArrayExprs.match(): The rewrite pass looks for two or more array operations that form an array expression.

Is it inconsistent between doc and impl?

If this can be confirmed as a real inconsistency, I would like to contribute some code to fix it.

**Comment by gmarkall** [comment] 2022-04-07 20:34
Is this an SDC issue, or a Numba issue? If it's a Numba issue, can you paste an executable variant of the code that uses Numba to reproduce the issue please?

**Comment by dlee992** [comment] 2022-04-08 02:33
Oh, sry, I didn't notice it. U can just replace `sdc.jit` with `numba.jit` in this case. SDC didn't re-implement `RewriteArrayExprs` Pass.

Below is the corresponding Numba IR:
```
----------------SSA IR DUMP: test_array_expr.<locals>._test_impl----------------
label 0:
    array1 = arg(0, name=array1)             ['array1']
    $const4.1 = const(float, 0.1)            ['$const4.1']
    ret = array1 >= $const4.1                ['$const4.1', 'array1', 'ret']
    $12return_value.4 = cast(value=ret)      ['$12return_value.4', 'ret']
    return $12return_value.4                 ['$12return_value.4']

______________________________________________________________________
REWRITING (RewriteArrayExprs):
    array1 = arg(0, name=array1)             ['array1']
    $const4.1 = const(float, 0.1)            ['$const4.1']
    ret = array1 >= $const4.1                ['$const4.1', 'array1', 'ret']
    del array1                               []
    del $const4.1                            []
    $12return_value.4 = cast(value=ret)      ['$12return_value.4', 'ret']
    del ret                                  []
    return $12return_value.4                 ['$12return_value.4']
____________________________________________________________
    array1 = arg(0, name=array1)             ['array1']
    $const4.1 = const(float, 0.1)            ['$const4.1']
    ret = arrayexpr(expr=(<built-in function ge>, [Var(array1, test_df_filter.py:162), const(float, 0.1)]), ty=array(bool, 1d, C)) ['array1', 'ret']
    del array1                               []
    del $const4.1                            []
    $12return_value.4 = cast(value=ret)      ['$12return_value.4', 'ret']
    del ret                                  []
    return $12return_value.4                 ['$12return_value.4']
```

**Comment by dlee992** [comment] 2022-04-08 03:25
Besides, I also want to know the difference between `IR DUMP` and `SSA IR DUMP`, I print some IR/SSA IR, but they look the same to me. like:
```
-------------------IR DUMP: __numba_array_expr_0x7f5a82fc8a90-------------------
label 0:
    array1_1 = arg(0, name=array1_1)         ['array1_1']
    $const4.1 = const(float, 0.1)            ['$const4.1']
    $6compare_op.2 = array1_1 >= $const4.1   ['$6compare_op.2', '$const4.1', 'array1_1']
    $8return_value.3 = cast(value=$6compare_op.2) ['$6compare_op.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']

-----------------SSA IR DUMP: __numba_array_expr_0x7f5a82fc8a90-----------------
label 0:
    array1_1 = arg(0, name=array1_1)         ['array1_1']
    $const4.1 = const(float, 0.1)            ['$const4.1']
    $6compare_op.2 = array1_1 >= $const4.1   ['$6compare_op.2', '$const4.1', 'array1_1']
    $8return_value.3 = cast(value=$6compare_op.2) ['$6compare_op.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']
```

**Comment by gmarkall** [comment] 2022-04-12 09:20
IR is not in SSA form, but SSA IR is in SSA form. For example, if you have:

```python
from numba import njit

@njit('int32(boolean)')
def f(c):
    if c:
        a = 1
    else:
        a = 2
    return a
```

Then the dumps are:

```
$ NUMBA_DUMP_IR=1 NUMBA_DUMP_SSA=1 python repro.py 
-----------------------------------IR DUMP: f-----------------------------------
label 0:
    c = arg(0, name=c)                       ['c']
    bool4 = global(bool: <class 'bool'>)     ['bool4']
    $4pred = call bool4(c, func=bool4, args=(Var(c, repro.py:6),), kws=(), vararg=None, target=None) ['$4pred', 'bool4', 'c']
    branch $4pred, 6, 14                     ['$4pred']
label 6:
    a = const(int, 1)                        ['a']
    $12return_value.2 = cast(value=a)        ['$12return_value.2', 'a']
    return $12return_value.2                 ['$12return_value.2']
label 14:
    a = const(int, 2)                        ['a']
    $20return_value.2 = cast(value=a)        ['$20return_value.2', 'a']
    return $20return_value.2                 ['$20return_value.2']

---------------------------------SSA IR DUMP: f---------------------------------
label 0:
    c = arg(0, name=c)                       ['c']
    bool4 = global(bool: <class 'bool'>)     ['bool4']
    $4pred = call bool4(c, func=bool4, args=(Var(c, repro.py:6),), kws=(), vararg=None, target=None) ['$4pred', 'bool4', 'c']
    branch $4pred, 6, 14                     ['$4pred']
label 6:
    a = const(int, 1)                        ['a']
    $12return_value.2 = cast(value=a)        ['$12return_value.2', 'a']
    return $12return_value.2                 ['$12return_value.2']
label 14:
    a.1 = const(int, 2)                      ['a.1']
    $20return_value.2 = cast(value=a.1)      ['$20return_value.2', 'a.1']
    return $20return_value.2                 ['$20return_value.2']
```

The IR is not SSA form because there are multiple assignments to `a` - in the SSA form, the second assignment is to a new variable, `a.1`.  The introductory paragraphs of the Wikipedia article provide a reasonable summary: https://en.wikipedia.org/wiki/Static_single_assignment_form

**Comment by sklam** [comment] 2022-04-12 14:08
My first guess is that the doc is wrong and `arrayexpr` is needed to map array operations to ufunc. But the code was written years ago and I need to look at it to confirm.

**Comment by esc** [comment] 2022-05-13 12:25
@dlee992 @gmarkall what shall we do about this one? @sklam did you ever manage to get to the bottom of this.

**Comment by sklam** [comment] 2022-05-18 16:13
The code is at https://github.com/numba/numba/blob/c6e79f05639094ae7f005e8960c1b3d6e7296a85/numba/np/ufunc/array_exprs.py#L66-L94

It will match anything that can be mapped to a supported NumPy ufunc and that there is no explicit output (i.e. the `out` argument in ufunc).

**Comment by dlee992** [comment] 2022-06-23 03:43
I think this issue can be closed. All we need to do is rewrite the Numba doc from `looks for two or more array operations` to `looks for one or more array operations`, since I guess we wouldn't want to change the related code.

**Comment by sklam** [comment] 2022-07-12 17:10
We should close this when a corresponding patch is merged.

**Closed** 2022-11-21 23:55 UTC
Labels: bug - documentation incorrect
