### ISSUE TITLE
Entries in record arrays cannot be flexibly set to zero

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#8456] opened 2022-09-22 14:22 UTC
I use numpy record array with various (also dynamically created) dtypes in my code. I now tried setting a single record to zero, but this did not work with numba.

```python
import numpy as np
import numba as nb

# create example array
dtype = np.dtype([("a", float), ("b", float, (2,))])
arr = np.ones((2,), dtype)

# set it the last record to zero using numpy
arr[1] = 0
print(arr)

# restore state
arr[...] = 1

# try using numba to set the array
@nb.njit
def f(arr):
    arr[1] = 0
f(arr)
```
This resulted in an error that `setitem` could not be used with this signature.

I also tried `arr[1].fill(0)` instead, but this resulted in `Internal error at resolving type of attribute "fill" of "$6binary_subscr.2".`

I finally used what I learned from #6634, but to no avail:
```python
import numpy as np
import numba as nb
from numba import literal_unroll
from numba.extending import overload

dtype = np.dtype([("a", float), ("b", float, (2,))])
arr = np.ones((2,), dtype)

def fill_zeros(recarr):
    for o in recarr.dtype.fields.keys():
        recarr[o] = 0

@overload(fill_zeros)
def ol_fill_zeros(recarr):
    keys = tuple(recarr.dtype.fields.keys())    
    def fill_zeros_impl(recarr):
        for o in literal_unroll(keys):
            recarr[o] = 0
    return fill_zeros_impl

@nb.njit
def f(arr):
    fill_zeros(arr[1])

f(arr)
print(arr)
```
This resulted in another `setitem` problem. Interestingly, the last case works if the dtype does not contain any arrays, e.g., for `dtype = np.dtype([("a", float), ("b", float, (2,))])`, while the methods discussed above also fail in this simpler case.

Does this simply mean that numba does not support recarrays (yet)? Is there an alternative approach that I missed?

**Comment by apmasell** [comment] 2022-09-22 19:41
The problem is that 0 isn't assignable to an array. It is possible to assign it to all subscripts in an array using `arr[:] = 0`. That requires separating the cases in your second `fill_zero_impl` to know the type, like this:
```
import numpy as np
import numba as nb
from numba import literal_unroll
from numba.extending import overload

dtype = np.dtype([("a", float), ("b", float, (2,))])
arr = np.ones((2,), dtype)

def fill_zeros(recarr):
    for o in recarr.dtype.fields.keys():
        recarr[o] = 0

@overload(fill_zeros)
def ol_fill_zeros(recarr):
    keys = tuple(recarr.dtype.fields.keys())    
    def fill_zeros_impl(recarr):
        for o in literal_unroll(keys):
            if isinstance(recarr[o], float):
              recarr[o] = 0
            else:
              recarr[o][:] = 0
    return fill_zeros_impl

@nb.njit
def f(arr):
    fill_zeros(arr[1])

f(arr)
print(arr)
```

**Comment by david-zwicker** [comment] 2022-09-22 19:59
Thank you very much for the quick response! Your solution works, although I'm still surprised that assigning `0` does not work directly. However, I suppose that my use case is a bit out there and not of highest priority to support...

**Comment by stuartarchibald** [comment] 2022-09-23 10:00
> Thank you very much for the quick response! Your solution works, although I'm still surprised that assigning `0` does not work directly. However, I suppose that my use case is a bit out there and not of highest priority to support...

I think this ought to be fixed as it's a disparity between the behaviour in Numba and NumPy.

There's two issues in this ticket:
1. Lack of support for `setitem` simultaneously across all fields of record arrays.
2. The `.fill` on a record array results in a `KeyError`. MWR:
   ```python
   from numba import njit
   import numpy as np
   dtype = np.dtype([("a", float), ("b", float)])
   arr = np.ones((2,), dtype)
   @njit
   def f(arr):
       arr[1].fill(0)
    f(arr)
   ```
Reopening to make sure that it's discussed at a triage meeting and bugs are assigned.

**Comment by apmasell** [comment] 2022-09-27 21:18
This has been broken into two smaller issues and will be closed in favour of those.

**Closed by apmasell** 2022-09-27 21:18 UTC
Labels: bug - incorrect behavior

**Comment by stuartarchibald** [comment] 2022-09-28 12:09
> This has been broken into two smaller issues and will be closed in favour of those.

Thanks @apmasell.
