### ISSUE TITLE
njitted array getitem accepts out-of-bounds array indices

### ISSUE THREAD

**Issue by pearu** [numba/numba#4436] opened 2019-08-11 19:51 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Consider example session:
```
>>> import numba as nb
>>> import numpy as np
>>> def foo(x, i): return x[i]
... 
>>> getitem = nb.njit(foo)
>>> getitem(np.array([1,2]), 2)
140182891159624
```
In the last expression, the following IndexError would be expected:
```
>>> np.array([1,2])[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by seibert** [comment] 2019-08-12 01:00
I think Aaron is working on this in #4432.

**Comment by stuartarchibald** [comment] 2019-08-12 09:20
For anyone finding this ticket, the reason bounds checking is not on by default is because checking the every access would prevent vectorization of loops and dramatically decrease performance as a result. The `boundscheck` feature being worked on in #4432 will make such checks opt-in, so that they can be used whilst developing code and switched off if desirable in production to get the extra performance.

**Comment by asmeurer** [comment] 2019-08-15 17:09
This issue is a duplicate of https://github.com/numba/numba/issues/730

**Comment by stuartarchibald** [comment] 2021-12-15 16:27
Closing, #4432 implemented optional bounds checking.

**Closed by stuartarchibald** 2021-12-15 16:27 UTC
Labels: feature_request
