### ISSUE TITLE
numba loses its edge when dealing with large matrices

### ISSUE THREAD

**Issue by TejasAvinashShetty** [numba/numba#5475] opened 2020-04-01 14:20 UTC
I have written out the following speed test adapted from the one at numba website.
```python
from numba import njit
from numpy import arange, tanh
from numpy import zeros
from time import time
from numpy.random import random_sample
from matplotlib import use
from matplotlib.pyplot import figure, axes

from matplotlib import rcParams
from matplotlib.pyplot import style
from matplotlib.pyplot import cla, close
use("TkAgg")
pgf_with_rc_fonts = {"pgf.texsystem": "pdflatex"}
rcParams.update(pgf_with_rc_fonts)
style.use('seaborn-whitegrid')

print('Please input a number')
max_plot_val = int(input())


def numba_time(max_plot_val):
    dum = arange(5**2).reshape(5, 5)
    @njit
    def go_fast(a):  # Function is compiled and runs in machine code
        trace = 0
        for i in range(a.shape[0]):
            trace += tanh(a[i, i])
        return a + trace

    go_fast(dum)  # compiled
    numba_time_array = zeros((max_plot_val,))

    for m in range(max_plot_val):
        x = arange(m**2).reshape(m, m)
        start = time()
        go_fast(x)
        end = time()
        numba_time_val = end - start
        numba_time_array[m] = numba_time_val

    return numba_time_array


def normal_time(max_plot_val):
    dum = arange(5**2).reshape(5, 5)

    def go_slow(a):  
        trace = 0
        for i in range(a.shape[0]):
            trace += tanh(a[i, i])
        return a + trace

    go_slow(dum)  # just keeping the sam format
    normal_time_array = zeros((max_plot_val,))

    for mnor in range(max_plot_val):
        x = arange(mnor**2).reshape(mnor, mnor)
        start = time()
        go_slow(x)
        end = time()
        normal_time_val = end - start
        normal_time_array[mnor] = normal_time_val

    return normal_time_array


# the random number
t_r_no = str(round(random_sample(), 5))

normal_time_array = normal_time(max_plot_val)
numba_time_array = numba_time(max_plot_val)
sf_fig = figure()
sf_ax = axes()

sf_ax.plot(normal_time_array, label='normal')
sf_ax.plot(numba_time_array, label='numba')
sf_ax.legend()
sf_ax.set(xlabel='value', ylabel='time taken',
          title='Plot of time taken for each value')

sf_rand_name = 's' + str(max_plot_val) + 'f' + str(t_r_no) + '.pdf'
sf_fig.savefig(sf_rand_name)
cla()
close(sf_fig)

```

- [x] I am using the 0.48 released version of Numba (This is because this is the highest version that is compatible with matplotlib, numpy, scipy at least according to the conda package manager).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by TejasAvinashShetty** [comment] 2020-04-01 14:28
For arrays of size ~ 200 numba is still considerably fast.
![image](https://user-images.githubusercontent.com/27445854/78148774-db15ca00-7452-11ea-80b4-73b03c3c867e.png)

**Comment by TejasAvinashShetty** [comment] 2020-04-01 14:32
But things turn bad around ~2000.
![image](https://user-images.githubusercontent.com/27445854/78149445-a48c7f00-7453-11ea-9586-bbfdd0b77102.png)

**Comment by TejasAvinashShetty** [comment] 2020-04-01 14:56
And continue to worsen thereafter.
![plot till 10,000](https://user-images.githubusercontent.com/27445854/78152107-013d6900-7457-11ea-9055-8ed9768953ad.png)

**Comment by esc** [comment] 2020-04-01 19:13
@TejasAvinashShetty thanks for submitting this. I just gave the above example you posted a spin, but I get the following error:

```
💥 zsh» python foo027.py
Please input a number
2000
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 149, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 610, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 538, in resolve
    typeinfer.add_type(self.target, sig.return_type, loc=self.loc)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 998, in add_type
    unified = tv.add_type(tp, loc=loc)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 70, in add_type
    raise TypingError(msg % (self.type, tp, self.var,
numba.core.errors.TypingError: Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$50binary_add.2', defined at foo027.py (28)

File "foo027.py", line 28:
    def go_fast(a):  # Function is compiled and runs in machine code
        <source elided>
            trace += tanh(a[i, i])
        return a + trace
        ^

[1] During: typing of intrinsic-call at foo027.py (28)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo027.py", line 71, in <module>
    numba_time_array = numba_time(max_plot_val)
  File "foo027.py", line 30, in numba_time
    go_fast(dum)  # compiled
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 342, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 81, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 92, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 986, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$50binary_add.2', defined at foo027.py (28)

File "foo027.py", line 28:
    def go_fast(a):  # Function is compiled and runs in machine code
        <source elided>
            trace += tanh(a[i, i])
        return a + trace
        ^

[1] During: typing of intrinsic-call at foo027.py (28)

File "foo027.py", line 28:
    def go_fast(a):  # Function is compiled and runs in machine code
        <source elided>
            trace += tanh(a[i, i])
        return a + trace
        ^

python foo027.py  18.02s user 16.06s system 90% cpu 37.624 total
```

Please could you tell me, which Numba version (commit hash or version) you are using?

**Comment by esc** [comment] 2020-04-01 19:22
@TejasAvinashShetty I just tried `0.48.0` and it worked. But it would be good if  you could perhaps try the current master and attempt to produce a minimal reproducer for the  problem I noted above?

**Comment by TejasAvinashShetty** [comment] 2020-04-02 05:47
Sorry, @esc I could not understand your statement very well. As I understand, You just want me to retry the code for the numba version 0.49.0.

**Comment by TejasAvinashShetty** [comment] 2020-04-02 06:11
The current master sees to be at 0.50.0.dev0+4.g1e2dc49c6.
Anyway for reproducibility this is how I have built the required stuff, numba.
```

conda create --name numba-minimal-latest python=3.7
conda install llvmlite
git clone git://github.com/numba/numba.git
cd numba/
pip install numpy
python setup.py install

```

**Comment by TejasAvinashShetty** [comment] 2020-04-02 06:19
On running the modified speed test, I get
```python-Traceback
Please input a number
2000
Traceback (most recent call last):
  File "n2.py", line 71, in <module>
    numba_time_array = numba_time(max_plot_val)
  File "n2.py", line 30, in numba_time
    go_fast(dum)  # compiled
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$54binary_add.2', defined at n2.py (28)

File "n2.py", line 28:
    def go_fast(a):  # Function is compiled and runs in machine code
        <source elided>
            trace += tanh(a[i, i])
        return a + trace
        ^

[1] During: typing of intrinsic-call at n2.py (28)

File "n2.py", line 28:
    def go_fast(a):  # Function is compiled and runs in machine code
        <source elided>
            trace += tanh(a[i, i])
        return a + trace
        ^


```

**Comment by TejasAvinashShetty** [comment] 2020-04-02 07:19
This an MWE for the error 
```python
from numba import njit
from numpy import arange, tanh
from time import time


dum = arange(5**2).reshape(5, 5)
@njit
def go_fast(a):  # Function is compiled and runs in machine code
    trace = 0
    for i in range(a.shape[0]):
        trace += tanh(a[i, i])
    return a + trace


go_fast(dum)  # compiled
start = time()
go_fast(dum)
end = time()
numba_time_val = end - start


dum = arange(5**2).reshape(5, 5)


def go_slow(a):  # Function is compiled and runs in machine code
    trace = 0
    for i in range(a.shape[0]):
        trace += tanh(a[i, i])
    return a + trace


go_slow(dum)
start = time()
go_slow(dum)
end = time()
normal_time_val = end - start

print('Numba time', numba_time_val)
print('Normal time', normal_time_val)
```
On running the above  piece of code, we get
```python-Traceback
Traceback (most recent call last):
  File "n2MWE.py", line 15, in <module>
    go_fast(dum)  # compiled
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$54binary_add.2', defined at n2MWE.py (12)

File "n2MWE.py", line 12:
def go_fast(a):  # Function is compiled and runs in machine code
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^

[1] During: typing of intrinsic-call at n2MWE.py (12)

File "n2MWE.py", line 12:
def go_fast(a):  # Function is compiled and runs in machine code
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^


```

**Comment by TejasAvinashShetty** [comment] 2020-04-02 07:21
Just changing `@njit` to `@jit` transforms the error into a warning.
```python-Traceback
Traceback (most recent call last):
  File "n2MWE.py", line 15, in <module>
    go_fast(dum)  # compiled
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/tejas/anaconda3/envs/numba-minimal-latest/lib/python3.7/site-packages/numba-0.50.0.dev0+4.g1e2dc49c6-py3.7-linux-x86_64.egg/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$54binary_add.2', defined at n2MWE.py (12)

File "n2MWE.py", line 12:
def go_fast(a):  # Function is compiled and runs in machine code
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^

[1] During: typing of intrinsic-call at n2MWE.py (12)

File "n2MWE.py", line 12:
def go_fast(a):  # Function is compiled and runs in machine code
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^


```

**Comment by esc** [comment] 2020-04-02 09:43
@TejasAvinashShetty thanks for following up on this, I have reduced the reproducer to:

```
from numba import njit
from numpy import arange, tanh


bar = arange(5**2).reshape(5, 5)


@njit
def foo(a):
    trace = 0
    for i in range(a.shape[0]):
        trace += tanh(a[i, i])
    return a + trace


foo(bar)
```

The warning you see when using `jit` instead basically means that the code couldn't be compiled properly and that Numba is now in objectmode-fallback: http://numba.pydata.org/numba-doc/latest/glossary.html#term-object-mode

**Comment by stuartarchibald** [comment] 2020-04-02 11:14
I think this is what's happening...
```python
from numba import njit
from numpy import arange, tanh

bar = arange(5**2).reshape(5, 5)

@njit
def foo(a):
    # trace is defined as an int64
    trace = 0
    # It's not possible to tell at compile time if this loop will run. If it does
    # then `trace` becomes a float64 by virtue of the infix addition of tanh()
    for i in range(a.shape[0]): 
        trace += tanh(a[i, i])
    # if the loop executes then the return type is:
    #     2d of array int64 + float64 -> 2d array of float64
    # if the loop does not execute then the return type is:
    #     2d of array int64 + int64 -> 2d array of int64
    # The compile cannot statically determine what the return type will be.
    return a + trace


foo(bar)
```
(Incidentally, the workaround for the example is to make `trace` a float in the first place, like `trace = 0.`.)

This case has the same "problem" but is simpler:
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    a = np.zeros(10, dtype=np.int64)
    b = np.zeros(10, dtype=np.float64)
    if x:
        return a
    else:
        return b

x = False
foo(x)
```
I'm not sure anything can be done here without coercing int arrays into float arrays. CC @sklam.

**Comment by esc** [comment] 2020-04-02 11:43
It's important to note that this is a regression and the reproducer I posted does work with 0.48.0

**Comment by esc** [comment] 2020-04-02 17:35
So, I think we ought to split here and talk about the regression in separate issue.

**Comment by TejasAvinashShetty** [comment] 2020-04-03 05:47
Yes @esc. It would confuse anyone who would come looking for it in the future.

**Comment by esc** [comment] 2020-04-03 09:52
@stuartarchibald how do we best split this? Are the unification issues something we can address at all? Or would you consider them a user-error?

**Comment by stuartarchibald** [comment] 2020-04-03 11:13
I think open a new ticket for the SSA induced issue and work on the performance things here.

**Comment by esc** [comment] 2020-04-03 15:04
@stuartarchibald thanks for the advice, new issue is up at #5501

**Comment by esc** [comment] 2020-04-03 19:50
@TejasAvinashShetty I ran this on my 2019 15 Inch Macbook Pro (2.9 GHz 6-Core Intel Core i9 and 16 GB 2400 MHz DDR4) with Numba master (`0.50.0dev0-7-g917f582433-dirty`) and I am unable to reproduce the numbers you reported. Instead I see:

[s10000f0.6911.pdf](https://github.com/numba/numba/files/4429566/s10000f0.6911.pdf)

In order to shed some more light on this, would you be able to follow up with your version of Numba, your operating system, the Python version and distribution type and lastly CPU brand and model and the amount of RAM. Also, if possible, please try to re-run the script you have with the  `trace = 0.0` workaround and report back if you observe any changes. Thanks very much for you efforts to improve Numba, it is appreciated!

**Comment by esc** [comment] 2020-04-03 19:52
![s10000f0 6911](https://user-images.githubusercontent.com/41563/78399544-5f07b780-75f5-11ea-83ff-e580b28e14a0.png)

**Comment by TejasAvinashShetty** [comment] 2020-04-05 16:22
Package | version 1 | version 2
-------------|----------|-----
numba  | 0.48      | 0.50.0.dev0+4.g1e2dc49c6
Python | 3.7.7 | 3.7.7

Ubuntu (Linux) 18.04 LTS 

I have an HP g3 Elitedesk.
RAM 23.4 GB
8 core
![image](https://user-images.githubusercontent.com/27445854/78503896-27307980-7787-11ea-8a3a-60b9f88ca6bd.png)

**Comment by TejasAvinashShetty** [comment] 2020-04-05 16:32
The MWE I produced runs smoothly without any problems.
![image](https://user-images.githubusercontent.com/27445854/78504118-9c507e80-7788-11ea-9328-b6190fc33e0d.png)
in 0.48
But failed in 0.50.0.dev0+4.g1e2dc49c6
![image](https://user-images.githubusercontent.com/27445854/78504209-24368880-7789-11ea-9cd2-36958fcf2012.png)

**Comment by TejasAvinashShetty** [comment] 2020-04-05 17:03
Maybe you could let me know he to build Numba from source properly. 
>  If you are building from source for the purposes of Numba development, see :ref:`buildenv` for details on how to create a Numba development environment with conda.

in https://github.com/numba/numba/blob/master/docs/source/user/installing.rst

seems to be a cyclic link.

**Comment by TejasAvinashShetty** [comment] 2020-04-05 17:13
Output of `numba -s`
[num0.48.txt](https://github.com/numba/numba/files/4434390/num0.txt)
[num0.50.0.dev0+4.g1e2dc49c6.txt](https://github.com/numba/numba/files/4434391/num1.txt)

**Comment by esc** [comment] 2020-04-06 16:19
@TejasAvinashShetty thanks for following up on this. The `trace = 0.0` should also work on current Numba master. As for building, I'm not sure what cyclic link you are referring to, can you link to the line in the docs? You may also find my personal `Makefile` of use, but you may have to adapt that for use with Linux:

https://github.com/esc/numba-dev-files/blob/master/Makefile 

As for the performance issue, I am not sure how to proceed here. Unless I or someone else can reproduce this issue it will be very difficult to track down. It may in fact have something to do with the hardware and software configuration of your specific machine. Do you perhaps have any other hardware that you could try this on?

**Comment by stuartarchibald** [comment] 2020-09-02 09:59
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-02 09:59 UTC
Labels: needtriage, performance
