### ISSUE TITLE
"Failed at convert to parfors" when a passed in function is used in the for parallelised loop

### ISSUE THREAD

**Issue by ashleysommer** [numba/numba#3255] opened 2018-08-23 11:44 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Traceback:
```
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typeinfer.py", line 423, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typeinfer.py", line 450, in resolve
    literals=literals)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typeinfer.py", line 1173, in resolve_call
    literals=literals)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typing/context.py", line 205, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/types/abstract.py", line 268, in get_call_type_with_literals
    return self.get_call_type(context, args, kws)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/types/functions.py", line 255, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 273, in get_call_template
    self.compile(tuple(args))
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 873, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 804, in _compile_bytecode
    return self._compile_core()
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 791, in _compile_core
    res = pm.run(self.status)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/compiler.py", line 521, in stage_parfor_pass
    parfor_pass.run()
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/parfor.py", line 633, in run
    stencil_pass.run()
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/stencilparfor.py", line 49, in run
    if isinstance(call_list[0], StencilFunc):
IndexError: Failed at nopython (convert to parfors)
list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/typeinfer.py", line 423, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/user/PycharmProjects/project/venv/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: Failed at nopython (convert to parfors)
list index out of range
[1] During: resolving callee type: type(CPUDispatcher(<function process_cell at 0x7f9d3dc26c80>))
[2] During: typing of call at /home/user/PycharmProjects/project/test1.py (27)

--%<----------------------------------------------------------------------------
```
Minimal reproduction:
```
import math
import numpy as np
from numba import njit, float64

@njit(float64(float64))
def my_square_func(x):
    return math.exp(2) * x

@njit(parallel=True)
def process_array(array, func):
    shape = array.shape
    rows = shape[0]
    cols = shape[1]
    for y in range(0, rows):
        for x in range(0, cols):
            cell = array[y, x]
            array[y, x] = func(cell)
    return array

if __name__ == "__main__":
    array = np.random.random((8, 8))
    array = process_array(array, my_square_func)
    print(array)
```

While writing this issue, I see it has actually been fixed here:
https://github.com/numba/numba/commit/61563800022ced1fef69d3819dce60cfd78ca359#diff-281a0b47828be951d54f12255e54fbfaR49
Has there not been a release since then?

**Comment by seibert** [comment] 2018-08-23 20:32
Yes, it looks like that was part of a PR merged after 0.39 was released.  I've confirmed that your code works on Numba master.  You can install a development version of Numba to test with:

```
conda install -c numba numba
```

(We build and upload every update to Numba master to the `numba` channel if it passes tests on that platform.)

**Comment by seibert** [comment] 2018-08-23 20:33
The Numba 0.40 release (with the fix) should be ~Sept 10.

**Comment by seibert** [comment] 2018-08-26 22:38
Closing this as it seems to be fixed on master.

**Closed by seibert** 2018-08-26 22:38 UTC
