### ISSUE TITLE
Parallel prange fails on higher number of iterations and is slower

### ISSUE THREAD

**Issue by step135** [numba/numba#6859] opened 2021-03-24 08:15 UTC
```
from numba import jit, prange
@jit(nopython=True, parallel=True)
def parorig(p):
    o=[]
    for item in prange(p):
        if item%2==0:o.append(2)
        else: o.append(1)
    return o
```
It is 10 times slower and unstable than if we remove `parallel=True`.
It works for small numbers, but calling `parorig(10000)` fails with "**The kernel appears to have died. It will restart automatically.**".

**Comment by farahhariri** [comment] 2021-03-24 16:17
Thanks for reporting the issue @step135 ! I have tried it on my linux machine and I am able to trigger an error for a large input `p`. I am getting: 
```
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
```
However, when I remove the `parallel=True` everything goes smoothly even for larger inputs. What machine are you running on? and what versions of python and numba?

**Comment by step135** [comment] 2021-03-24 18:14
It was tested in Jupyter notebook on Lenovo tablet with graphics card from Intel. Anyway, I suppose that GPU acceleration is not supported in numba for Intel? Alternatively, it could cause some problems.

**Comment by farahhariri** [comment] 2021-03-24 19:25
So after some debugging, it seems like this is an issue due to Numba not having support for parallelism with lists. Basically as of now you can't use a list with `prange`.

Suggestion to numba devs: to mark this issue as a bug/feature request as you see fit and open an issue to update the docs indicating that prange is not supported with lists

**Comment by sklam** [comment] 2021-03-25 12:56
marking this as a segfault and a duplicate of #2408

**Comment by stuartarchibald** [comment] 2021-04-12 12:39
Docs update in https://github.com/numba/numba/pull/6918

**Comment by stuartarchibald** [comment] 2021-04-14 16:12
Closing as duplicate of #2408.

**Closed by stuartarchibald** 2021-04-14 16:12 UTC
Labels: bug - segfault, duplicate
