### ISSUE TITLE
Issue when using 'not in' in numba

### ISSUE THREAD

**Issue by Hbodor** [numba/numba#6797] opened 2021-03-05 12:34 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.

Hi,

When trying to convert my code to be compatible with numba, I remarked that 'not in' is not working properly in numba. 

Here is an example :

```python3
@njit
def test4():
    l = [ [2 for i in range(0)] for i in range(5)]
    for i in range(5):
      for j in range(i,10):
        j = j%5
        if j not in l[i]:
          l[i].append(j)
    return l
test4()

``` 

this code produces the following error 

```

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Type of variable '$66compare_op.10' cannot be determined, operation: unary(fn=<built-in function not_>, value=$66compare_op.10), location: <ipython-input-50-a39b79080121> (7)

File "<ipython-input-50-a39b79080121>", line 7:
def test4():
    <source elided>
        j = j%5
        if j not in l[i]:
        ^

```

To solve it I did : 

```python3
@njit
def test4():
    l = [ [2 for i in range(0)] for i in range(5)]
    for i in range(5):
      for j in range(i,10):
        j = j%5
        if j in l[i]:
          pass
        else:
          l[i].append(j)
    return l
test4()
```

which gives the desired output

**Comment by gmarkall** [comment] 2021-03-05 12:52
I can't reproduce this with Numba master - running:

```python
from numba import njit


@njit
def test4():
    l = [[2 for i in range(0)] for i in range(5)]
    for i in range(5):
        for j in range(i, 10):
            j = j % 5
            if j not in l[i]:
                l[i].append(j)
    return l


test4()
```

results in no output:

```
0 gmarkall@blixen 12:50:06 (main) ~/numbadev/issues/6797
$ python repro.py 
(numba) 
0 gmarkall@blixen 12:50:09 (main) ~/numbadev/issues/6797
$
```

Can you provide the output of `numba -s` please?

**Comment by Hbodor** [comment] 2021-03-05 13:56
Here is my output for ``` numba -s ```


```

System info:
--------------------------------------------------------------------------------
__Time Stamp__
2021-03-05 13:51:25.447553

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : haswell
Number of accessible CPU cores                : 2
Listed accessible CPUs cores                  : 0-1
CFS restrictions                              : None
CPU Features                                  : 
64bit aes avx avx2 bmi bmi2 cmov cx16 f16c fma fsgsbase invpcid lzcnt mmx movbe
pclmul popcnt rdrnd sahf sse sse2 sse3 sse4.1 sse4.2 ssse3 xsave xsaveopt

__OS Information__
Platform                                      : Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Release                                       : 4.19.112+
System Name                                   : Linux
Version                                       : #1 SMP Thu Jul 23 08:00:38 PDT 2020
OS specific info                              : Ubuntu18.04bionic
glibc info                                    : glibc 2.15

__Python Information__
Python Compiler                               : GCC 7.5.0
Python Implementation                         : CPython
Python Version                                : 2.7.17
Python Locale                                 : en_US UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Error: CUDA device intialisation problem. Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
Conda not present/not working.
Error was [Errno 2] No such file or directory

--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

```

**Comment by Hbodor** [comment] 2021-03-05 17:05
Hi,

Here are the versions of numba and llvmlite :

```
Package                       Version       
----------------------------- --------------
llvmlite                      0.35.0
numba                         0.52.0 
```

**Comment by sklam** [comment] 2021-03-05 17:09
Numba 0.52 requires Python >=3.6, <3.9 but it looks like Python 2.7 is being used. The LLVM version is also too old.

**Comment by Hbodor** [comment] 2021-03-05 17:54
Hi,

Thanks for your answer. However it's just because I am running it in google colab. I did ``` !numba -s ``` which run it with python 2.7. but my colab kernel runs indeed in python 3.7. Here is the real output of numba -s obtained by running ``` !python3 -m numba -s ``` : 


```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2021-03-05 17:53:16.931420
UTC start time                                : 2021-03-05 17:53:16.931431
Running time (s)                              : 0.714849

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : haswell
CPU Count                                     : 2
Number of accessible CPUs                     : 2
List of accessible CPUs cores                 : 0 1
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit aes avx avx2 bmi bmi2 cmov
                                                cx16 cx8 f16c fma fsgsbase fxsr
                                                invpcid lzcnt mmx movbe pclmul
                                                popcnt rdrnd sahf sse sse2 sse3
                                                sse4.1 sse4.2 ssse3 xsave xsaveopt

Memory Total (MB)                             : 13021
Memory Available (MB)                         : 8549

__OS Information__
Platform Name                                 : Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Platform Release                              : 4.19.112+
OS Name                                       : Linux
OS Version                                    : #1 SMP Thu Jul 23 08:00:38 PDT 2020
OS Specific Version                           : ?
Libc Version                                  : glibc 2.26

__Python Information__
Python Compiler                               : GCC 7.5.0
Python Implementation                         : CPython
Python Version                                : 3.7.10
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Detect Output:
None
CUDA Librairies Test Output:
None

__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package                       Version       
----------------------------- --------------
absl-py                       0.10.0        
alabaster                     0.7.12        
albumentations                0.1.12        
altair                        4.1.0         
appdirs                       1.4.4         
argon2-cffi                   20.1.0        
asgiref                       3.3.1         
astor                         0.8.1         
astropy                       4.2           
astunparse                    1.6.3         
async-generator               1.10          
atari-py                      0.2.6         
atomicwrites                  1.4.0         
attrs                         20.3.0        
audioread                     2.1.9         
autograd                      1.3           
Babel                         2.9.0         
backcall                      0.2.0         
beautifulsoup4                4.6.3         
biopython                     1.78          
bleach                        3.3.0         
blis                          0.4.1         
bokeh                         2.1.1         
Bottleneck                    1.3.2         
branca                        0.4.2         
bs4                           0.0.1         
CacheControl                  0.12.6        
cachetools                    4.2.1         
catalogue                     1.0.0         
certifi                       2020.12.5     
cffi                          1.14.5        
chainer                       7.4.0         
chardet                       3.0.4         
click                         7.1.2         
cloudpickle                   1.3.0         
cmake                         3.12.0        
cmdstanpy                     0.9.5         
colorlover                    0.3.0         
community                     1.0.0b1       
contextlib2                   0.5.5         
convertdate                   2.3.1         
coverage                      3.7.1         
coveralls                     0.5           
crcmod                        1.7           
cufflinks                     0.17.3        
cvxopt                        1.2.6         
cvxpy                         1.0.31        
cycler                        0.10.0        
cymem                         2.0.5         
Cython                        0.29.22       
daft                          0.0.4         
dask                          2.12.0        
datascience                   0.10.6        
debugpy                       1.0.0         
decorator                     4.4.2         
defusedxml                    0.6.0         
descartes                     1.1.0         
dill                          0.3.3         
distributed                   1.25.3        
Django                        3.1.7         
dlib                          19.18.0       
dm-tree                       0.1.5         
docopt                        0.6.2         
docutils                      0.16          
dopamine-rl                   1.0.5         
earthengine-api               0.1.238       
easydict                      1.9           
ecos                          2.0.7.post1   
editdistance                  0.5.3         
en-core-web-sm                2.2.5         
entrypoints                   0.3           
ephem                         3.7.7.1       
et-xmlfile                    1.0.1         
fa2                           0.3.5         
fancyimpute                   0.4.3         
fastai                        1.0.61        
fastdtw                       0.3.4         
fastprogress                  1.0.0         
fastrlock                     0.5           
fbprophet                     0.7.1         
feather-format                0.4.1         
filelock                      3.0.12        
firebase-admin                4.4.0         
fix-yahoo-finance             0.0.22        
Flask                         1.1.2         
flatbuffers                   1.12          
folium                        0.8.3         
future                        0.16.0        
gast                          0.3.3         
GDAL                          2.2.2         
gdown                         3.6.4         
gensim                        3.6.0         
geographiclib                 1.50          
geopy                         1.17.0        
gin-config                    0.4.0         
glob2                         0.7           
google                        2.0.3         
google-api-core               1.16.0        
google-api-python-client      1.7.12        
google-auth                   1.27.0        
google-auth-httplib2          0.0.4         
google-auth-oauthlib          0.4.2         
google-cloud-bigquery         1.21.0        
google-cloud-bigquery-storage 1.1.0         
google-cloud-core             1.0.3         
google-cloud-datastore        1.8.0         
google-cloud-firestore        1.7.0         
google-cloud-language         1.2.0         
google-cloud-storage          1.18.1        
google-cloud-translate        1.5.0         
google-colab                  1.0.0         
google-pasta                  0.2.0         
google-resumable-media        0.4.1         
googleapis-common-protos      1.52.0        
googledrivedownloader         0.4           
graphviz                      0.10.1        
grpcio                        1.32.0        
gspread                       3.0.1         
gspread-dataframe             3.0.8         
gym                           0.17.3        
h5py                          2.10.0        
HeapDict                      1.0.1         
hijri-converter               2.1.1         
holidays                      0.10.5.2      
holoviews                     1.13.5        
html5lib                      1.0.1         
httpimport                    0.5.18        
httplib2                      0.17.4        
httplib2shim                  0.0.3         
humanize                      0.5.1         
hyperopt                      0.1.2         
ideep4py                      2.0.0.post3   
idna                          2.10          
image                         1.5.33        
imageio                       2.4.1         
imagesize                     1.2.0         
imbalanced-learn              0.4.3         
imblearn                      0.0           
imgaug                        0.2.9         
importlib-metadata            3.7.0         
importlib-resources           5.1.0         
imutils                       0.5.4         
inflect                       2.1.0         
iniconfig                     1.1.1         
intel-openmp                  2021.1.2      
intervaltree                  2.1.0         
ipykernel                     4.10.1        
ipython                       5.5.0         
ipython-genutils              0.2.0         
ipython-sql                   0.3.9         
ipywidgets                    7.6.3         
itsdangerous                  1.1.0         
jax                           0.2.9         
jaxlib                        0.1.60+cuda101
jdcal                         1.4.1         
jedi                          0.18.0        
jieba                         0.42.1        
Jinja2                        2.11.3        
joblib                        1.0.1         
jpeg4py                       0.1.4         
jsonschema                    2.6.0         
jupyter                       1.0.0         
jupyter-client                5.3.5         
jupyter-console               5.2.0         
jupyter-core                  4.7.1         
jupyterlab-pygments           0.1.2         
jupyterlab-widgets            1.0.0         
kaggle                        1.5.10        
kapre                         0.1.3.1       
Keras                         2.4.3         
Keras-Preprocessing           1.1.2         
keras-vis                     0.4.1         
kiwisolver                    1.3.1         
knnimpute                     0.1.0         
korean-lunar-calendar         0.2.1         
librosa                       0.8.0         
lightgbm                      2.2.3         
llvmlite                      0.35.0        
lmdb                          0.99          
lucid                         0.3.8         
LunarCalendar                 0.0.9         
lxml                          4.2.6         
Markdown                      3.3.4         
MarkupSafe                    1.1.1         
matplotlib                    3.2.2         
matplotlib-venn               0.11.6        
missingno                     0.4.2         
mistune                       0.8.4         
mizani                        0.6.0         
mkl                           2019.0        
mlxtend                       0.14.0        
more-itertools                8.7.0         
moviepy                       0.2.3.5       
mpmath                        1.2.1         
msgpack                       1.0.2         
multiprocess                  0.70.11.1     
multitasking                  0.0.9         
murmurhash                    1.0.5         
music21                       5.5.0         
natsort                       5.5.0         
nbclient                      0.5.3         
nbconvert                     5.6.1         
nbformat                      5.1.2         
nest-asyncio                  1.5.1         
networkx                      2.5           
nibabel                       3.0.2         
nltk                          3.2.5         
notebook                      5.3.1         
np-utils                      0.5.12.1      
numba                         0.52.0        
numexpr                       2.7.2         
numpy                         1.19.5        
nvidia-ml-py3                 7.352.0       
oauth2client                  4.1.3         
oauthlib                      3.1.0         
okgrade                       0.4.3         
opencv-contrib-python         4.1.2.30      
opencv-python                 4.1.2.30      
openpyxl                      2.5.9         
opt-einsum                    3.3.0         
osqp                          0.6.2.post0   
packaging                     20.9          
palettable                    3.3.0         
pandas                        1.1.5         
pandas-datareader             0.9.0         
pandas-gbq                    0.13.3        
pandas-profiling              1.4.1         
pandocfilters                 1.4.3         
panel                         0.9.7         
param                         1.10.1        
parso                         0.8.1         
pathlib                       1.0.1         
patsy                         0.5.1         
pexpect                       4.8.0         
pickleshare                   0.7.5         
Pillow                        7.0.0         
pip                           19.3.1        
pip-tools                     4.5.1         
plac                          1.1.3         
plotly                        4.4.1         
plotnine                      0.6.0         
pluggy                        0.7.1         
pooch                         1.3.0         
portpicker                    1.3.1         
prefetch-generator            1.0.1         
preshed                       3.0.5         
prettytable                   2.0.0         
progressbar2                  3.38.0        
prometheus-client             0.9.0         
promise                       2.3           
prompt-toolkit                1.0.18        
protobuf                      3.12.4        
psutil                        5.4.8         
psycopg2                      2.7.6.1       
ptyprocess                    0.7.0         
py                            1.10.0        
pyarrow                       3.0.0         
pyasn1                        0.4.8         
pyasn1-modules                0.2.8         
pycocotools                   2.0.2         
pycparser                     2.20          
pyct                          0.4.8         
pydata-google-auth            1.1.0         
pydot                         1.3.0         
pydot-ng                      2.0.0         
pydotplus                     2.0.2         
PyDrive                       1.3.1         
pyemd                         0.5.1         
pyerfa                        1.7.2         
pyglet                        1.5.0         
Pygments                      2.6.1         
pygobject                     3.26.1        
pymc3                         3.7           
PyMeeus                       0.4.2         
pymongo                       3.11.3        
pymystem3                     0.2.0         
pynndescent                   0.5.2         
PyOpenGL                      3.1.5         
pyparsing                     2.4.7         
pyrsistent                    0.17.3        
pysndfile                     1.3.8         
PySocks                       1.7.1         
pystan                        2.19.1.1      
pytest                        3.6.4         
python-apt                    0.0.0         
python-chess                  0.23.11       
python-dateutil               2.8.1         
python-louvain                0.15          
python-slugify                4.0.1         
python-utils                  2.5.6         
pytz                          2018.9        
pyviz-comms                   2.0.1         
PyWavelets                    1.1.1         
PyYAML                        3.13          
pyzmq                         22.0.3        
qdldl                         0.1.5.post0   
qtconsole                     5.0.2         
QtPy                          1.9.0         
regex                         2019.12.20    
requests                      2.23.0        
requests-oauthlib             1.3.0         
resampy                       0.2.2         
retrying                      1.3.3         
rpy2                          3.4.2         
rsa                           4.7.2         
scikit-image                  0.16.2        
scikit-learn                  0.22.2.post1  
scipy                         1.4.1         
screen-resolution-extra       0.0.0         
scs                           2.1.2         
seaborn                       0.11.1        
Send2Trash                    1.5.0         
setuptools                    54.0.0        
setuptools-git                1.2           
Shapely                       1.7.1         
simplegeneric                 0.8.1         
six                           1.15.0        
sklearn                       0.0           
sklearn-pandas                1.8.0         
smart-open                    4.2.0         
snowballstemmer               2.1.0         
sortedcontainers              2.3.0         
SoundFile                     0.10.3.post1  
spacy                         2.2.4         
Sphinx                        1.8.5         
sphinxcontrib-serializinghtml 1.1.4         
sphinxcontrib-websupport      1.2.4         
SQLAlchemy                    1.3.23        
sqlparse                      0.4.1         
srsly                         1.0.5         
statsmodels                   0.10.2        
strkernel                     0.2           
sympy                         1.7.1         
tables                        3.4.4         
tabulate                      0.8.9         
tblib                         1.7.0         
tensorboard                   2.4.1         
tensorboard-plugin-wit        1.8.0         
tensorflow                    2.4.1         
tensorflow-datasets           4.0.1         
tensorflow-estimator          2.4.0         
tensorflow-gcs-config         2.4.0         
tensorflow-hub                0.11.0        
tensorflow-metadata           0.28.0        
tensorflow-probability        0.12.1        
termcolor                     1.1.0         
terminado                     0.9.2         
testpath                      0.4.4         
text-unidecode                1.3           
textblob                      0.15.3        
textgenrnn                    1.4.1         
Theano                        1.0.5         
thinc                         7.4.0         
tifffile                      2021.2.26     
toml                          0.10.2        
toolz                         0.11.1        
torch                         1.7.1+cu101   
torchsummary                  1.5.1         
torchtext                     0.3.1         
torchvision                   0.8.2+cu101   
tornado                       5.1.1         
tqdm                          4.41.1        
traitlets                     5.0.5         
tweepy                        3.10.0        
typeguard                     2.7.1         
typing-extensions             3.7.4.3       
tzlocal                       1.5.1         
umap-learn                    0.5.1         
uritemplate                   3.0.1         
urllib3                       1.24.3        
vega-datasets                 0.9.0         
wasabi                        0.8.2         
wcwidth                       0.2.5         
webencodings                  0.5.1         
Werkzeug                      1.0.1         
wheel                         0.36.2        
widgetsnbextension            3.5.1         
wordcloud                     1.5.0         
wrapt                         1.12.1        
xarray                        0.15.1        
xgboost                       0.90          
xkit                          0.0.0         
xlrd                          1.1.0         
xlwt                          1.3.0         
yellowbrick                   0.9.1         
zict                          2.0.0         
zipp                          3.4.0         

No errors reported.


__Warning log__
Warning (cuda): CUDA device intialisation problem. Message:Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda': 'conda'

--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

```

**Comment by MarrakchiMouad** [comment] 2021-03-05 18:55
I was facing the same issue, thanks @Hbodor  for the little hack :) !

**Comment by gmarkall** [comment] 2021-03-08 15:07
Closing as the original issue seems to be resolved.

**Closed by gmarkall** 2021-03-08 15:07 UTC
Labels: needtriage
