### ISSUE TITLE
Can't compile tuple generators

### ISSUE THREAD

**Issue by Harrelix** [numba/numba#7295] opened 2021-08-10 13:59 UTC
```python
@njit
def gen():
    yield 1, 2
    yield 3, 4

for i in gen():
    print(i)
```
I expected the output to be
```
(1, 2)
(3, 4)
```
Instead, I got this error
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
('{i64, i64}', '[2 x i64]')
```

Works fine with only 1 yield
```python
@njit
def gen():
    for i in range(10):
        yield i, i + 1


for i in gen():
    print(i)
```

**Comment by sklam** [comment] 2021-08-10 15:00
Thanks for reporting the issue. I can confirm that this is a bug.

**Comment by sklam** [comment] 2021-08-10 15:02
Also noting, the problem is not new. It has at least been around since the last 2 versions (0.53, 0.52).

**Comment by stuartarchibald** [comment] 2021-08-10 16:48
This last worked in 0.46.

**Comment by sklam** [comment] 2021-08-10 21:55
I'm working on a fix for this.

**Closed** 2021-08-19 20:36 UTC
Labels: bug - ice
