### ISSUE TITLE
'NoneType' object has no attribute 'module'

### ISSUE THREAD

**Issue by uta-bolt** [numba/numba#4417] opened 2019-08-06 19:39 UTC
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    626     try:
--> 627         yield
    628     except NumbaError as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_inst(self, inst)
    300             ty = self.typeof(inst.target.name)
--> 301             val = self.lower_assign(ty, inst)
    302             self.storevar(val, inst.target.name)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_assign(self, ty, inst)
    453         elif isinstance(value, ir.Expr):
--> 454             return self.lower_expr(ty, value)
    455 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_expr(self, resty, expr)
   1002             else:
-> 1003                 impl = self.context.get_getattr(ty, expr.attr)
   1004                 attrty = self.context.typing_context.resolve_getattr(ty,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\targets\base.py in get_getattr(self, typ, attr)
    587                 pyval = getattr(typ.pymod, attr)
--> 588                 llval = self.get_constant(attrty, pyval)
    589                 def imp(context, builder, typ, val, attr):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\targets\base.py in get_constant(self, ty, val)
    509         # HACK: pass builder=None to preserve get_constant() API
--> 510         return self.get_constant_generic(None, ty, val)
    511 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\targets\base.py in get_constant_generic(self, builder, ty, val)
    499             impl = self._get_constants.find((ty,))
--> 500             return impl(self, builder, ty, val)
    501         except NotImplementedError:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\targets\arrayobj.py in constant_record(context, builder, ty, pyval)
   2283     """
-> 2284     return context.make_constant_array(builder, ty, pyval)
   2285 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\targets\base.py in make_constant_array(self, builder, typ, ary)
   1014             consts = Constant.array(Type.int(8), bytearray(flat.data))
-> 1015             data = cgutils.global_constant(builder, ".const.array.data", consts)
   1016             # Ensure correct data alignment (issue #1933)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\cgutils.py in global_constant(builder_or_module, name, value, linkage)
    874     else:
--> 875         module = builder_or_module.module
    876     data = module.add_global_variable(value.type, name=name)

AttributeError: 'NoneType' object has no attribute 'module'

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-6-d724da083cd1> in <module>
      1 start=time.clock()
----> 2 vopt_out, pf_out,kss_out,success=aiyagari(kinit,p,epsseries,uss)
      3 end=time.clock()-start
      4 print(end)

<ipython-input-5-9e23103da0fc> in aiyagari(kbar, p, epsseries, u)
     82         print("outer loop:")
     83         print(j)
---> 84         vopt, pf,kss,success=vfi(kbar,p,epsseries,u)
     85         if abs(kss-kbar)>p.tol_outer:
     86             kbar=kss

<ipython-input-5-9e23103da0fc> in vfi(kbar, p, epsseries, u)
     73         else:
     74             print("convergence 1 achieved")
---> 75             kss=simulate(pf,epsseries,r,w)
     76 
     77             break

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    367                     e.patch_message(''.join(e.args) + help_msg)
    368             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 369             raise e
    370 
    371     def inspect_llvm(self, signature=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    324                 argtypes.append(self.typeof_pyval(a))
    325         try:
--> 326             return self.compile(tuple(argtypes))
    327         except errors.TypingError as e:
    328             # Intercept typing error that may be due to an argument

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    656 
    657             self._cache_misses[sig] += 1
--> 658             cres = self._compiler.compile(args, return_type)
    659             self.add_overload(cres)
    660             self._cache.save_overload(sig, cres)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    939     pipeline = pipeline_class(typingctx, targetctx, library,
    940                               args, return_type, flags, locals)
--> 941     return pipeline.compile_extra(func)
    942 
    943 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    370         self.lifted = ()
    371         self.lifted_from = None
--> 372         return self._compile_bytecode()
    373 
    374     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    870         """
    871         assert self.func_ir is None
--> 872         return self._compile_core()
    873 
    874     def _compile_ir(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    857         self.define_pipelines(pm)
    858         pm.finalize()
--> 859         res = pm.run(self.status)
    860         if res is not None:
    861             # Early pipeline completion

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    242                 try:
    243                     event(stage_name)
--> 244                     stage()
    245                 except _EarlyPipelineCompletion as e:
    246                     return e.result

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in stage_nopython_backend(self)
    729         """
    730         lowerfn = self.backend_nopython_mode
--> 731         self._backend(lowerfn, objectmode=False)
    732 
    733     def stage_compile_interp_mode(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in _backend(self, lowerfn, objectmode)
    679             self.library.enable_object_caching()
    680 
--> 681         lowered = lowerfn()
    682         signature = typing.signature(self.return_type, *self.args)
    683         self.cr = compile_result(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in backend_nopython_mode(self)
    666                 self.calltypes,
    667                 self.flags,
--> 668                 self.metadata)
    669 
    670     def _backend(self, lowerfn, objectmode):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1061         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1062                                metadata=metadata)
-> 1063         lower.lower()
   1064         if not flags.no_cpython_wrapper:
   1065             lower.create_cpython_wrapper(flags.release_gil)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower(self)
    175         if self.generator_info is None:
    176             self.genlower = None
--> 177             self.lower_normal_function(self.fndesc)
    178         else:
    179             self.genlower = self.GeneratorLower(self)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_normal_function(self, fndesc)
    216         # Init argument values
    217         self.extract_function_arguments()
--> 218         entry_block_tail = self.lower_function_body()
    219 
    220         # Close tail of entry block

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_function_body(self)
    241             bb = self.blkmap[offset]
    242             self.builder.position_at_end(bb)
--> 243             self.lower_block(block)
    244 
    245         self.post_lower()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    256             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 
    260     def create_cpython_wrapper(self, release_gil=False):

~\AppData\Local\Continuum\anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    633         from numba import config
    634         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 635         six.reraise(type(newerr), newerr, tb)
    636 
    637 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'NoneType' object has no attribute 'module'

File "<ipython-input-5-9e23103da0fc>", line 40:
def simulate(pf,epsseries,r,w):
    <source elided>
        if epsilon==1:
            indk[ixN+1]=interp(p.kgrid,pf[:,1],indkcopy)
            ^

[1] During: lowering "$90.3 = getattr(value=$90.2, attr=kgrid)" at <ipython-input-5-9e23103da0fc> (40)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by uta-bolt** [comment] 2019-08-06 19:44
The interp function I use comes from: 
import quantecon as qe
from interpolation import interp 
and should be jittable

**Comment by sklam** [comment] 2019-08-07 15:53
Can you provide a reproducer?

**Comment by stuartarchibald** [comment] 2019-08-12 09:21
Thanks for the report. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

**Comment by stuartarchibald** [comment] 2019-09-11 14:53
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Closed by stuartarchibald** 2019-09-11 14:53 UTC
Labels: no action required
