### ISSUE TITLE
TBB threading layer deadlock on terminate

### ISSUE THREAD

**Issue by JSKenyon** [numba/numba#5908] opened 2020-06-23 09:24 UTC
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

## Environment
* Numba version: 0.50.0
* Python version: 3.6.9
* Operating System: Pop!_OS 18.04 LTS

## Problem

While attempting to dig into #4807, I uncovered some really bizarre behaviour. At first I thought it was a duplicate of #4484, but I have TBB installed and did `export NUMBA_THREADING_LAYER='tbb'`. The following reproducer deadlocks on the final compute call. It only deadlocks when `parallel=True` and only when invoked after the `scheduler='threads'` call. At first I thought it was caching related (again, digging into #4807) but the problem occurs regardless of whether caching is enabled. 

I endeavoured to reproduce it using a `ThreadPoolExecutor` and a `ProcessPoolExecutor` but couldn't get it right.

This is not blocking my workflow, but I thought it was worth reporting.

## Reproducer
```python
from numba import jit, prange
import dask.array as da
import numpy as np


@jit(nopython=True, parallel=False, cache=False, nogil=True)
def serial_f(x):

    y = np.zeros_like(x)

    for i in prange(x.size):

        y[i] = x[i]/(i + 1)

    return y


@jit(nopython=True, parallel=True, cache=False, nogil=True)
def parallel_f(x):

    y = np.zeros_like(x)

    for i in prange(x.size):

        y[i] = x[i]/(i + 1)

    return y


if __name__ == "__main__":

    data = da.ones((100), chunks=25)

    result = da.map_blocks(serial_f, data)

    result.compute(scheduler="threads")
    print("Threaded scheduler worked for serial function!")

    result.compute(scheduler="processes")
    print("Process scheduler worked for serial function!")

    result = da.map_blocks(parallel_f, data)

    result.compute(scheduler="threads")
    print("Threaded scheduler worked for parallel function!")

    result.compute(scheduler="processes")
    print("Process scheduler worked for parallel function!")  # It won't...
```

**Comment by stuartarchibald** [comment] 2020-06-23 09:40
Thanks for the report. I can reproduce, looks like the TBB scheduler is stuck on a blocking terminate.

**Comment by chebee7i** [comment] 2023-06-06 03:55
Hi all, do we see a path forward?  We seem to be hitting this still on newer versions of `numba`.

**Comment by sarathnandu** [comment] 2023-08-08 21:18
Can you please specify which particular numba/Python version and platform used. 
I have tried the above reproducer with numba-0.57 and Python 3.11.1 and seems to works fine.

**Comment by omalyshe** [comment] 2023-10-30 16:16
@chebee7i  @stuartarchibald  @JSKenyon Can you please confirm that it works for you with numba-0.57 and Python 3.11.1  (see sarathnandu comment).

**Comment by JSKenyon** [comment] 2023-11-01 08:09
I can confirm that I can no longer reproduce the error with the latest version of Numba.

**Comment by stuartarchibald** [comment] 2023-11-02 12:00
Thanks for following up @omalyshe and @JSKenyon. Given it is not reproducing any more I'll close this ticket. It may be that the underlying issue was in TBB and has been fixed upstream. If the issue reoccurs please do comment, reopen this or open a new ticket. Many thanks.

**Closed by stuartarchibald** 2023-11-02 12:00 UTC
Labels: bug, threading
