### ISSUE TITLE
Divide and become (/=) issue

### ISSUE THREAD

**Issue by shaharkadmiel** [numba/numba#2746] opened 2018-02-12 16:03 UTC
I encountered a bug which I have not been able to reproduce with a working example and my actual code is to complex to share but I'll describe what happened and perhaps this will ring a bell to someone.

Inside a _jitted_ function, just before the `return` statement, I have a line similar to this:

```python
x /= y
```

As I was comparing the _jitted_ version of my code to the pure python version, mainly to quantify the performance boost (which is significant BTW) when I noticed a factor of _y_ difference in my results.

To debug this, I added `print(x.max())` before and after the above line and saw that the division does actually take place. Compared my results again and they were the same. Commented out the `print` lines and again there was a factor of _y_ difference.

Changing  the line to:
```python
x = x / y
```
solves the problem but this is a very weird (and dangerous and probably undesired) behaviour.

I will try to come up with a simple example that reproduces this weird behaviour but in the meantime, I am interested to know if there is a known issue and if I should stay away from `+=, -=, *=, /=, ... ` type operators within Numba altogether.

**Comment by stuartarchibald** [comment] 2018-02-12 16:05
Thanks for the report. I wonder if it is related to this: https://github.com/numba/numba/issues/2644

**Comment by shaharkadmiel** [comment] 2018-02-12 16:19
yes! definitely seems so. I've tested the code in #2644 with inplace division and have been able to reproduce the behaviour I described.

```python
import numpy as np
import numpy.random as random
import numba

random.seed(111)
points = 10*random.rand(10, 2)

def sub(pts):
    points = pts.copy()
    points /= points[3]
    return points

@numba.njit('f8[:,::1](f8[:,::1])')
def sub_njit(pts):
    points = pts.copy()
    points /= points[3]
    return points

@numba.njit('f8[:,::1](f8[:,::1])')
def sub_njit_noninplace(pts):
    points = pts.copy()
    points = points / points[3]
    return points

print(np.allclose(sub(points), sub_njit(points)))
print(np.allclose(sub(points), sub_njit_noninplace(points)))
```

which outputs:
```
False
True
```

**Comment by stuartarchibald** [comment] 2018-02-13 09:48
Thanks for confirming @shaharkadmiel. I'm going to close this as a duplicate of #2644 as the reproducer contains the same logic. Please follow #2644 for work on fixes.

**Closed by stuartarchibald** 2018-02-13 09:48 UTC
Labels: needtriage
