### ISSUE TITLE
cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

### ISSUE THREAD

**Issue by gnthibault** [numba/numba#4255] opened 2019-07-02 06:27 UTC
Numba version: 
numba==0.44.1

System:
armhf (arm 32bits) build of debian stretch running on an aarch64 kernel.
I experienced some problem to properly import jit from numba, but it appeared to be solved at the end of https://github.com/numba/llvmlite/issues/497

MWE:
```
from pywi.processing.transform import starlet
import scipy.misc as misc
img=misc.face()[:,:,0]
t = starlet.wavelet_transform(img, number_of_scales=5)
```

Actual log:

> python3
> Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
> [GCC 6.3.0 20170516] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from pywi.processing.transform import starlet
> >>> import scipy.misc as misc
> >>> img=misc.face()[:,:,0]
> >>> t = starlet.wavelet_transform(img, number_of_scales=5)
> /home/rock/.local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py:237: NumbaWarning: 
> Compilation is falling back to object mode WITH looplifting enabled because Function "wavelet_transform" failed type inference due to: Internal error at <numba.typeinfer.CallConstraint object at 0xedcb6030>:
> --%<----------------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/errors.py", line 661, in new_error_context
>     yield
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typeinfer.py", line 455, in __call__
>     self.resolve(typeinfer, typevars, fnty)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typeinfer.py", line 474, in resolve
>     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typeinfer.py", line 1314, in resolve_call
>     return self.context.resolve_function_type(fnty, pos_args, kw_args)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typing/context.py", line 186, in resolve_function_type
>     res = self._resolve_user_function_type(func, args, kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typing/context.py", line 238, in _resolve_user_function_type
>     return func.get_call_type(self, args, kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/types/functions.py", line 214, in get_call_type
>     out = template.apply(args, kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typing/templates.py", line 225, in apply
>     sig = generic(args, kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typing/templates.py", line 778, in generic
>     sig = method_resolver(self, ty, args, kws)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 442, in resolve_astype
>     assert not kws
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typeinfer.py", line 144, in propagate
>     constraint(typeinfer)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/typeinfer.py", line 455, in __call__
>     self.resolve(typeinfer, typevars, fnty)
>   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/errors.py", line 669, in new_error_context
>     six.reraise(type(newerr), newerr, tb)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
>     raise value
> numba.errors.InternalError: 
> [1] During: resolving callee type: BoundFunction(array.astype for readonly array(uint8, 2d, A))
> [2] During: typing of call at /home/rock/.local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py (298)
> 
> --%<----------------------------------------------------------------------------
> 
> 
> File ".local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py", line 298:
> def wavelet_transform(input_image,
>     <source elided>
> 
>     input_image = input_image.astype('float64', copy=True)
>     ^
> 
>   @jit
> /home/rock/.local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py:237: NumbaWarning: 
> Compilation is falling back to object mode WITHOUT looplifting enabled because Function "wavelet_transform" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>
> 
> File ".local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py", line 315:
> def wavelet_transform(input_image,
>     <source elided>
> 
>     for scale_index in range(number_of_scales - 1):
>     ^
> 
>   @jit
> Traceback (most recent call last):
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/errors.py", line 661, in new_error_context
>     yield
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block
>     self.lower_inst(inst)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/pylowering.py", line 176, in lower_inst
>     raise NotImplementedError(type(inst), inst)
> NotImplementedError: (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0xedc40350>)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
>     raise e
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 327, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 659, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/dispatcher.py", line 83, in compile
>     pipeline_class=self.pipeline_class)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 955, in compile_extra
>     return pipeline.compile_extra(func)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 377, in compile_extra
>     return self._compile_bytecode()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 886, in _compile_bytecode
>     return self._compile_core()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 873, in _compile_core
>     res = pm.run(self.status)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 254, in run
>     raise patched_exception
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 245, in run
>     stage()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 463, in stage_objectmode_frontend
>     cres = self.frontend_looplift()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 435, in frontend_looplift
>     lifted=tuple(loops), lifted_from=None)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 1017, in compile_ir
>     lifted_from=lifted_from)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 385, in compile_ir
>     return self._compile_ir()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 893, in _compile_ir
>     return self._compile_core()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 873, in _compile_core
>     res = pm.run(self.status)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 254, in run
>     raise patched_exception
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 245, in run
>     stage()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 711, in stage_objectmode_backend
>     self._backend(lowerfn, objectmode=True)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 687, in _backend
>     lowered = lowerfn()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 659, in backend_object_mode
>     self.flags)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/compiler.py", line 1148, in py_lowering_stage
>     lower.lower()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/lowering.py", line 177, in lower
>     self.lower_normal_function(self.fndesc)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/lowering.py", line 218, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/lowering.py", line 243, in lower_function_body
>     self.lower_block(block)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block
>     self.lower_inst(inst)
>   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/errors.py", line 669, in new_error_context
>     six.reraise(type(newerr), newerr, tb)
>   File "/home/rock/.local/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
>     raise value
> numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)
> Failed in object mode pipeline (step: object mode backend)
> (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0xedc40350>)
> 
> File ".local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py", line 302:
> def wavelet_transform(input_image,
>     <source elided>
>         msg = "The data should be a 2D array."
>         raise WrongDimensionError(msg)
>         ^
> 
> [1] During: lowering "raise <class 'pywi.processing.transform.starlet.WrongDimensionError'>('The data should be a 2D array.')" at /home/rock/.local/lib/python3.5/site-packages/pywi/processing/transform/starlet.py (302)
> -------------------------------------------------------------------------------
> This should not have happened, a problem has occurred in Numba's internals.
> 
> Please report the error message and traceback, along with a minimal reproducer
> at: https://github.com/numba/numba/issues/new
> 
> If more help is needed please feel free to speak to the Numba core developers
> directly at: https://gitter.im/numba/numba
> 
> Thanks in advance for your help in improving Numba!

**Comment by gnthibault** [comment] 2019-07-02 06:37
Even worse, the simple numba examples are returning wrong values:

```
>>> from numba import jit
>>> import random
>>> @jit(nopython=True)
... def monte_carlo_pi(nsamples):
...     acc = 0
...     for i in range(nsamples):
...         x = random.random()
...         y = random.random()
...         if (x ** 2 + y ** 2) < 1.0:
...             acc += 1
...     return 4.0 * acc / nsamples
...
>>> monte_carlo_pi(65536)
3.2379e-319
>>> monte_carlo_pi(1000000)
2.216501094359597e-301
>>> monte_carlo_pi(1)
2.2165010939451453e-301
```

**Comment by stuartarchibald** [comment] 2019-07-02 14:43
Thanks for the report, the original error is a duplicate of https://github.com/numba/numba/issues/4185, https://github.com/numba/numba/pull/4224 fixes.

**Comment by stuartarchibald** [comment] 2019-07-02 15:07
@gnthibault RE the "wrong values", I cannot reproduce:
```bash
$ cat issue4255.py
from numba import jit
import random

@jit(nopython=True)
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples

print(monte_carlo_pi(65536))
print(monte_carlo_pi(1000000))
print(monte_carlo_pi(1))

$ python issue4255.py
3.1439208984375
3.141248
4.0
```
Is this on the self-compiled LLVM on aarch64 from here https://github.com/numba/llvmlite/issues/497?

**Comment by gnthibault** [comment] 2019-07-02 15:24
@stuartarchibald  Yes it is, but it is actually a armhf (32bits) version that I compiled. The aarch64 is the kernel.

**Comment by seibert** [comment] 2019-07-02 16:35
My speculation is that somehow Numba is querying platform properties (pointer widths, calling conventions, etc) and getting values for the kernel (64-bit) and not the process (32-bit).  The values you are seeing look like uninitialized floats, suggesting some offsets in the stack are just wrong.

**Comment by gnthibault** [comment] 2019-07-02 17:10
Ouch... this might be much harder to fix then...

**Comment by seibert** [comment] 2019-07-02 18:55
Yeah, we're still thinking about how to troubleshoot this.  We don't have a mixed 32/64 bit ARM system currently.

**Comment by gnthibault** [comment] 2019-07-03 06:06
Ok continuing investigating this problem, I tried to recompile and 'make check-all' on my llvm build.

I have 2 failing tests:

> Failing Tests (2):
>     LLVM :: tools/llvm-objdump/eh_frame-coff.test
>     LLVM :: tools/llvm-profdata/memop-size-prof.proftext

Do you have any idea about what this is and if it can explain why numba is failing in my case ?

**Comment by seibert** [comment] 2019-07-03 13:33
I don't think either of those tools impact the JIT functionality, so I don't think LLVM is at fault here.  (Or at least, not in a way their tests can detect.)  We don't have any test environments where kernel pointer size != process pointer size, so it is quite possible some assumptions have crept into the Numba code base.

We ship with the test suite, so you can run the unit tests this way:
```
python -m numba.runtests -m &> test_results.txt
```
The second `-m` tells it to run multiprocess, since there are 8000 tests.  If things seem to be crash or freeze, you might need to drop that and run single process.  Our Raspberry Pi 3 takes 70-80 minutes to complete the test suite in multiprocess mode.

Feel free to post that to a gist and it might give us some more ideas as to where compilation is going wrong.

**Comment by gnthibault** [comment] 2019-07-03 19:48
I will report the output here. Thank you very much for your support !

**Comment by gnthibault** [comment] 2019-07-04 05:55
Here are the results, apparently there are a lot of failures:

[test_results.txt](https://github.com/numba/numba/files/3357853/test_results.txt)

**Comment by gnthibault** [comment] 2019-07-04 19:34
Ok I also tried to rebuilt python+ all dependancies inside of a fully aarch64 chroot.
Unfortunately, numba does not work inside of a chroot apparently:

> /usr/local/lib/python3.5/dist-packages/numba/npyufunc/parallel.py:243: UserWarning: Could not obtain multiprocessing lock due to OS level error: [Errno 38] Function not implemented
> A likely cause of this problem is '/dev/shm' is missing orread-only such that necessary semaphores cannot be written.
> *** The responsibility of ensuring multiprocessing safe access to this initialization sequence/module import is deferred to the user! ***
> 
>   warnings.warn(msg % str(e))
> Can't read /proc/cpuinfo: No such file or directory
> Can't read /proc/cpuinfo: No such file or directory
> Can't read /proc/cpuinfo: No such file or directory
> Can't read /proc/cpuinfo: No such file or directory
> QXcbConnection: Could not connect to display
> 

Any other option ?

**Comment by stuartarchibald** [comment] 2019-07-05 08:27
The lack of semaphore based locking is not disastrous, it's there to make concurrent launches of the threading backends safer but they'll work in most cases without. That you cannot read `/proc/cpuinfo` is of concern, did you mount `/proc` in the chroot dir (and probably mounting `/dev/shm` there too would sort the semaphore problem out)?

**Comment by gnthibault** [comment] 2019-07-05 08:51
Ah, I completely forgot that I could just mount those two, thank you for the suggestion

**Comment by stuartarchibald** [comment] 2019-07-18 10:07
#4224 is in mainline and fixes the reported bug, closing.

**Closed by stuartarchibald** 2019-07-18 10:07 UTC
Labels: bug, duplicate, objectmode
