### ISSUE TITLE
SyntaxError: unqualified exec is not allowed in function '_add_offset_to_slice'

### ISSUE THREAD

**Issue by Maslino** [numba/numba#2653] opened 2017-12-18 10:27 UTC
numba version: 0.36.1
python version: 2.7.5
OS: CentOS Linux release 7.2.1511

The exception is:
```
File "/usr/lib/python2.7/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/usr/lib/python2.7/site-packages/resampy/core.py", line 9, in <module>
    from .interpn import resample_f
  File "/usr/lib/python2.7/site-packages/resampy/interpn.py", line 4, in <module>
    import numba
  File "/usr/lib64/python2.7/site-packages/numba/__init__.py", line 12, in <module>
    from .special import typeof, prange
  File "/usr/lib64/python2.7/site-packages/numba/special.py", line 4, in <module>
    from .parfor import prange
  File "/usr/lib64/python2.7/site-packages/numba/parfor.py", line 25, in <module>
    from numba import stencilparfor
SyntaxError: unqualified exec is not allowed in function '_add_offset_to_slice' it contains a nested function with free variables (stencilparfor.py, line 544)
```

I tried numba 0.35.0, all is fine.

**Comment by stuartarchibald** [comment] 2018-01-01 11:28
Thanks for the report. I think this is a duplicate of https://github.com/numba/numba/issues/2642 and is fixed in https://github.com/numba/numba/pull/2645 so I'm closing the issue. If you believe this is not the case please feel free to reopen, thanks.

**Closed by stuartarchibald** 2018-01-01 11:28 UTC
