### ISSUE TITLE
error during np_append which is implemented in numba.np.arrayobj.np_append

### ISSUE THREAD

**Issue by AlbertoWang** [numba/numba#6596] opened 2020-12-22 14:40 UTC
## Reporting a bug

- [*] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [*] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When I use np.append that numba overload numpy.append in numba.np.arrayobj.np_append, error message appears as follows:

```
/Applications/Anaconda-Navigator.app/Contents/MacOS/python /Users/alberto/PaperSpace/VecNet/main.py
Traceback (most recent call last):
  File "/Users/alberto/PaperSpace/VecNet/main.py", line 33, in <module>
    print(natural_neighbor(t.transpose(1, 2)))
  File "/Users/alberto/PaperSpace/VecNet/model_util.py", line 168, in natural_neighbor
    _lambda, _, nn = NaN_Searching(point_cloud)
  File "/Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function append at 0x7fb70e497440>) found for signature:
 
 >>> append(list(class(int64))<iv=None>, int64)
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload in function 'np_append': File: numba/np/arrayobj.py: Line 1709.
     With argument(s): '(list(class(int64))<iv=None>, int64)':
    Rejected as the implementation raised a specific error:
      TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    No implementation of function Function(<function concatenate at 0x7fb70e162a70>) found for signature:
     
     >>> concatenate(Tuple(array(class(int64), 1d, C), array(int64, 1d, C)))
     
    There are 2 candidate implementations:
          - Of which 2 did not match due to:
          Overload in function 'concatenate': File: numba/core/typing/npydecl.py: Line 789.
            With argument(s): '(Tuple(array(class(int64), 1d, C), array(int64, 1d, C)))':
           Rejected as the implementation raised a specific error:
             TypeError: np.concatenate(): input arrays must have compatible dtypes
      raised from /Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/typing/npydecl.py:773
    
    During: resolving callee type: Function(<function concatenate at 0x7fb70e162a70>)
    During: typing of call at /Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/np/arrayobj.py (1723)
    
    
    File "../../opt/anaconda3/lib/python3.7/site-packages/numba/np/arrayobj.py", line 1723:
            def impl(arr, values, axis=None):
                <source elided>
                values = np.ravel(np.asarray(values))
                return np.concatenate((arr, values))
                ^

  raised from /Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/typeinfer.py:1071

During: resolving callee type: Function(<function append at 0x7fb70e497440>)
During: typing of call at /Users/alberto/PaperSpace/VecNet/model_util.py (109)


File "model_util.py", line 109:
def NaN_Searching(X):
    <source elided>
            nb[q] = nb[q] + 1
            np.append(kNN[p], q)
            ^


Process finished with exit code 1

```

My code here:
```python
from numba.np.arrayobj import np_append
@njit
def NaN_Searching(X):
    N = len(X) # X is input of the function which is numpy array
    r = 1
    nb = np.zeros(N, dtype=np.int_)
    kNN = [[np.int_] for _ in range(N)]
    RkNN = [[np.int_] for _ in range(N)]
    count = [N]

    while True:
        idx = knn_numpy(X.transpose(1, 0), k=r + 1)
        for p in range(N):
            # find the r-th nearest neighbor of p
            neighbors_p = idx[p]
            q = -1
            for ele in neighbors_p:
                if (ele not in kNN[p]) and (ele != p):
                    q = ele
                    break
            nb[q] = nb[q] + 1
            np.append(kNN[p], q)
            # kNN[p].append(q)  # unsupported in numba
            np.append(RkNN[q], p)
            # RkNN[q].append(p)  # unsupported in numba
        count.append(len(nb[nb == 0]))
        if count[r] == count[r - 1] or r == 20:
            break
        r = r + 1
# compute natural neighbors
    NaN = [[np.int_] for _ in range(N)]
    for i in range(N):
        NaN[i] = intersection(kNN[i], RkNN[i])
    return r, nb, NaN
```
where the error appears with code: `np.append(kNN[p], q)` and `kNN` is a list, `q` is a int data

**Comment by AlbertoWang** [comment] 2020-12-22 14:47
I think the import message is
```
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload in function 'np_append': File: numba/np/arrayobj.py: Line 1709.
     With argument(s): '(list(class(int64))<iv=None>, int64)':
    Rejected as the implementation raised a specific error:
      TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    No implementation of function Function(<function concatenate at 0x7fb70e162a70>) found for signature:
     
     >>> concatenate(Tuple(array(class(int64), 1d, C), array(int64, 1d, C)))
     
    There are 2 candidate implementations:
          - Of which 2 did not match due to:
          Overload in function 'concatenate': File: numba/core/typing/npydecl.py: Line 789.
            With argument(s): '(Tuple(array(class(int64), 1d, C), array(int64, 1d, C)))':
           Rejected as the implementation raised a specific error:
             TypeError: np.concatenate(): input arrays must have compatible dtypes
      raised from /Users/alberto/opt/anaconda3/lib/python3.7/site-packages/numba/core/typing/npydecl.py:773
```
And I think may this caused by different implement between `numpy.append` and `numba.np.arrayobj.np_append` ? or just my method to use `numba.np.arrayobj.np_append` is wrong? I need to append items in numpy array, just as result of`list.append`

**Comment by stuartarchibald** [comment] 2020-12-22 15:42
@AlbertoWang Thanks for the report. There's a few issues with the above, some of which are hard to explain as unfortunately the code above is not a working reproducer, it's missing definitions of `knn_numpy` and `intersection`.

First problem is that `from numba.np.arrayobj import np_append` is not needed. Numba automatically "knows" what to do with the NumPy API, what you've done is import part of Numba's internal implementation and tried to use that, which causes problems as Numba doesn't know what to do with it's own API, just what to do with NumPy's API, the detection is automatic!

Next issue is a more general one in that Numba has to work out the types of all the variables in your code. It cannot figure out the type of the result of a `np.append` involving a list as it doesn't know at compile time how big the list is (lists are mutable data structures) and as a result it doesn't know what size the result of doing an `append` should be. The outcome from this is a `TypingError` similar to the one above, i.e. it can't work out the type resulting from an append with those input types.

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

Also, Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!

**Comment by AlbertoWang** [comment] 2020-12-23 06:47
Thanks for your reply! Sorry for forgetting to push all codes.
`knn_numpy` is defined as follows:
```python
@njit
def knn_numpy(n, k):
    """
    construct knn idxes using numpy to adapt numba
    :param n: input point cloud, shape: (dim, point_num)
    :param k:
    :return: idxes of knn, shape: (point_num, k)
    """
    # n_inner = -2 * np.einsum("ijk,ikn->ijn", n.transpose(0, 2, 1), n) # use in high dim(batched)
    n_inner = -2 * np.dot(n.transpose(1, 0), n)
    n_xx = np.sum(n ** 2, axis=0)  # , keepdims=True
    n1 = np.add(n_xx, n_inner)
    n2 = np.transpose(n_xx)
    n_pairwise_distance = np.add(n1, n2)  # (2048, 2048)
    n_idx = []
    for dis in n_pairwise_distance:
        n_idx.append(np.argsort(dis)[:k])
    # n_idx = np.argpartition(n_pairwise_distance, kth=k) # unsupported in numba
    # n_idx = np.array(n_idx)
    return n_idx  # [:, :k]
```
and `intersection ` is defined as follows:
```python
@njit
def intersection(X1, X2):
    commonElements = []
    if len(X1) <= len(X2):
        for i in range(len(X1)):
            if X1[i] in X2:
                commonElements.append(X1[i])
    else:
        for i in range(len(X2)):
            if X2[i] in X1:
                commonElements.append(X2[i])
    return commonElements
```
The purpose of `knn_numpy` function is to find k-nearest neighbor via numpy to calculate matrix, `np.argpartition` is not supported in numba, so I have to use other method to do this job, that is:
```python
 n_idx = []
    for dis in n_pairwise_distance:
        n_idx.append(np.argsort(dis)[:k])
```
to replace this code `n_idx = np.argpartition(n_pairwise_distance, kth=k)`
What confused me is how to use the operate: `append` in numba? Appreciate it if you can offer the example code of using `append` in numba!

**Comment by stuartarchibald** [comment] 2020-12-23 10:25
Here's an example of what's supported with `np.append`, might be worth looking at `np.concatenate` too:
```python
from numba import njit
import numpy as np

@njit
def foo():
    x = np.zeros((3,))
    y = np.append(x, x)
    z = np.concatenate((x, x, x))
    return y, z

print(foo())
```

**Comment by stuartarchibald** [comment] 2021-01-04 15:48
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2021-01-04 15:48 UTC
Labels: needtriage
