### ISSUE TITLE
for loop is not getting faster in some cases

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#5511] opened 2020-04-06 05:19 UTC
I have write a function to calculate move OLS beta for time series 
calculate it by a sliding window 
```
@jit(nopython=True)
def regBeta(y,x,n,d):
	'''
	y OLS with x and get the beta
	y,x: vector 
	d: past d dates
	'''
	rowNum_ = n-d+1
	y_ = np.lib.stride_tricks.as_strided(y,shape=(rowNum_,d),strides=(y.strides[0],y.strides[0]))
	x_ = np.lib.stride_tricks.as_strided(x,shape=(rowNum_,d),strides=(x.strides[0],x.strides[0]))
	#beta = np.zeros(rowNum_,dtype=np.float32)
	# for i in range(rowNum_):
	# 	x_i = x_[i]
	# 	y_i = y_[i]
	# 	#beta[i] = np.linalg.solve(np.dot(x_i.T,x_i),np.dot(x_i.T,y_i))
	#x1_.sum(1).reshape(n-d+1,1)/d
	
	x_mean = x_.sum(1).reshape(rowNum_,1) / d
	y_mean = y_.sum(1).reshape(rowNum_,1) / d
	x_1 = x_ - x_mean
	y_1 = y_ - y_mean
	x_2 = x_1 * x_1
	xy_1 = x_1 * y_1
	x_2_s = x_2.sum(1)
	xy_1_s = xy_1.sum(1)
	beta = xy_1_s / x_2_s

	return beta

@jit(nopython=True)
def regBeta_mat(m1,m2,d):
	'''
	m1 OLS with m2 in past d dates and get the beta
	m1,m2: matrix (m1:y,m2:x)
	return: beta of OLS 
	'''
	size1,size2 = m1.size,m2.size

	if size1 == 1 or size2 == 1:
		return np.full(fill_value=np.nan,shape=(1,1),dtype=np.float32)
	
	rowNum1 = m1.shape[0]
	rowNum2 = m2.shape[0]
	colNum = m1.shape[1]

	if d < 20:
		return np.full(fill_value=np.nan,shape=(rowNum1,colNum),dtype=np.float32)
	
	if rowNum1 < rowNum2:
		rowNum = rowNum1
		m2 = m2[-rowNum:]
	
	else:
		rowNum = rowNum2
		m1 = m1[-rowNum:]

	if rowNum <= d + 20:
		return np.full(fill_value=np.nan,shape=(rowNum,colNum),dtype=np.float32)

	retMat = np.zeros((rowNum-d+1,colNum),dtype=np.float32)
	
	for i in np.arange(colNum):
		retMat[:,i] = regBeta(m1[:,i],m2[:,i],rowNum,d)

	return retMat

```

```
m1 = np.random.randn(750,4000).astype(np.float32)
m2 = np.random.randn(750,4000).astype(np.float32)

%timeit regBeta_mat(m1,m2,20)
469 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit regBeta_mat.py_func(m1,m2,20)
477 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I created two random matrix (750,4000) . And I do the OLS column by column. So it will do 4000 times OLS , and for loop by 4000 times. 

And I think numba will accelerate the for loop significantly,  but the result is very close .
Maybe I miss something or forget something in numba, is there any method to accelerate the for loop significantly?  Thank you .

**Comment by isaac-you** [comment] 2020-04-06 05:22
np.__version__:  '1.17.4'
numba.__version__: '0.46.0'

**Comment by gmarkall** [comment] 2020-04-06 08:43
@isaac-you could you try with the latest version of Numba (0.48 is the latest released version, or 0.49.0rc1 available from the Numba channel: `conda install -c numba numba=0.49.0`) and see if you get similar results please?

**Comment by isaac-you** [comment] 2020-04-09 02:26
@ gmarkall
I have upgraded numba into 0.48 
but the same thing happened, result is very close. 
Not accelerated significantly!  almost not accelerated at all.

**Comment by isaac-you** [comment] 2020-04-09 02:27
@gmarkall 
I have upgraded numba into 0.48
but the same thing happened, result is very close.
Not accelerated significantly! almost not accelerated at all.

**Comment by gmarkall** [comment] 2020-04-09 10:41
Thanks for trying with 0.48. With this executable reproducer:

```python
from numba import jit
from timeit import Timer
import numpy as np


@jit(nopython=True)
def regBeta(y, x, n, d):
    """
    y OLS with x and get the beta
    y,x: vector 
    d: past d dates
    """
    rowNum_ = n - d + 1
    y_ = np.lib.stride_tricks.as_strided(
        y, shape=(rowNum_, d), strides=(y.strides[0], y.strides[0])
    )
    x_ = np.lib.stride_tricks.as_strided(
        x, shape=(rowNum_, d), strides=(x.strides[0], x.strides[0])
    )
    # beta = np.zeros(rowNum_,dtype=np.float32)
    # for i in range(rowNum_):
    #     x_i = x_[i]
    #     y_i = y_[i]
    #     #beta[i] = np.linalg.solve(np.dot(x_i.T,x_i),np.dot(x_i.T,y_i))
    # x1_.sum(1).reshape(n-d+1,1)/d

    x_mean = x_.sum(1).reshape(rowNum_, 1) / d
    y_mean = y_.sum(1).reshape(rowNum_, 1) / d
    x_1 = x_ - x_mean
    y_1 = y_ - y_mean
    x_2 = x_1 * x_1
    xy_1 = x_1 * y_1
    x_2_s = x_2.sum(1)
    xy_1_s = xy_1.sum(1)
    beta = xy_1_s / x_2_s

    return beta


@jit(nopython=True)
def regBeta_mat(m1, m2, d):
    """
    m1 OLS with m2 in past d dates and get the beta
    m1,m2: matrix (m1:y,m2:x)
    return: beta of OLS 
    """
    size1, size2 = m1.size, m2.size

    if size1 == 1 or size2 == 1:
        return np.full(fill_value=np.nan, shape=(1, 1), dtype=np.float32)

    rowNum1 = m1.shape[0]
    rowNum2 = m2.shape[0]
    colNum = m1.shape[1]

    if d < 20:
        return np.full(fill_value=np.nan, shape=(rowNum1, colNum), dtype=np.float32)

    if rowNum1 < rowNum2:
        rowNum = rowNum1
        m2 = m2[-rowNum:]

    else:
        rowNum = rowNum2
        m1 = m1[-rowNum:]

    if rowNum <= d + 20:
        return np.full(fill_value=np.nan, shape=(rowNum, colNum), dtype=np.float32)

    retMat = np.zeros((rowNum - d + 1, colNum), dtype=np.float32)

    for i in np.arange(colNum):
        retMat[:, i] = regBeta(m1[:, i], m2[:, i], rowNum, d)

    return retMat


m1 = np.random.randn(750, 4000).astype(np.float32)
m2 = np.random.randn(750, 4000).astype(np.float32)

def cb(number, time_taken):
    print("%d runs, %s" % (number, time_taken))

print("Timing jitted function:")
Timer("regBeta_mat(m1,m2,20)", globals=globals()).autorange(callback=cb)
print("Timing Python function:")
Timer("regBeta_mat.py_func(m1,m2,20)", globals=globals()).autorange(callback=cb)
```

I get:

```
Timing jitted function:
1 runs, 3.511282523002592
Timing Python function:
1 runs, 0.41677723299653735
```

(quite a bit slower for the jitted function)

**Comment by gmarkall** [comment] 2020-04-09 11:00
I should have just used the timeit magic - there are a couple of mistakes in my timing above - with the timeit magic I reproduce similar numbers:

```python
Timing jitted function:
405 ms ± 728 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
Timing Python function:
416 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by isaac-you** [comment] 2020-04-09 11:05
@gmarkall  yes as you can see, it is not accelerated significantly.  maybe I forget something.

**Comment by gmarkall** [comment] 2020-04-09 11:15
The Python code spends a lot of its time in the NumPy sum, reduce, and stride tricks functions (see profile graph), which won't be impacted much by Numba - these are already compiled code, so I don't think there is a great deal in this function for Numba to have an impact on performance with.

[pyfunc.pdf](https://github.com/numba/numba/files/4455791/pyfunc.pdf)

**Comment by stuartarchibald** [comment] 2020-05-01 16:35
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2020-05-01 16:35 UTC
Labels: performance, question
