### ISSUE TITLE
@jit is not working 

### ISSUE THREAD

**Issue by sejpalsinh** [numba/numba#5006] opened 2019-12-27 12:38 UTC
Traceback (most recent call last):
  File "kangaroo256-main.py", line 732, in <module>
    Sp.append(mul_2a(Sp[k]))
  File "kangaroo256-main.py", line 200, in mul_2a
    c = A.x * A.x * invert(A.y+A.y, p)          # 1I,2M,0S
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numba\dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numba\dispatcher.py", line 318, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mnon-precise type pyobject[0m
[0m[1m[1] During: typing of argument at kangaroo256-main.py (144)[0m
[1m
File "kangaroo256-main.py", line 144:[0m
[1mdef invert(b, p=modulo):
[1m    u, v = b%p, p
[0m [1m^[0m[0m

This error may have been caused by the following argument(s):
- argument 0: Int value is too large: 65341020041517633956166170261014086368942546761318486551877808671514674964848
- argument 1: Int value is too large: 115792089237316195423570985008687907853269984665640564039457584007908834671663

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by sklam** [comment] 2019-12-27 17:17
Closing. Duplicate of #5005

**Closed by sklam** 2019-12-27 17:17 UTC
