### ISSUE TITLE
Device function declaration order error message

### ISSUE THREAD

**Issue by aleaverfay** [numba/numba#2958] opened 2018-05-11 15:17 UTC
Hi,

I've discovered a surprising behavior from numba when writing device functions that are going to be called inside CUDA kernels: the device functions have to appear before (e.g. be written above) the kernel, or Numba will produce this not-so-useful error message:

      File "/home/anaconda3/envs/tmol/lib/python3.6/site-packages/numba/typeinfer.py", line 1119, in typeof_global
        typ = self.resolve_value_type(inst, gvar.value)
      File "/home/anaconda3/envs/tmol/lib/python3.6/site-packages/numba/typeinfer.py", line 1042, in resolve_value_type
        raise TypingError(msg, loc=inst.loc)
    numba.errors.TypingError: Failed at nopython (nopython frontend)
    Untyped global name 'identity_ht': cannot determine Numba type of <class 'object'>

(where `identity_ht` was the name of the function I was trying to call, but was declared later in the file)

This will only happen when trying to run on a GPU. If you run on a CPU with the simulator (NUMBA_ENABLE_CUDASIM=1), then numba does not care what order the functions appear in.

I am opening an issue here, as google does not turn up anything useful when you search with the error message. 

It would be helpful if perhaps this deviation from how python handles function declaration order were highlighted more clearly somewhere in the documentation, or if the error message gave you some hint as to what is wrong with your code.

I am using version 0.37 from anaconda.

**Comment by stuartarchibald** [comment] 2018-05-14 11:07
Thanks for the report. This is a minimal reproducer:
```python
import numpy as np
from numba import cuda, types

@cuda.jit(argtypes=(types.double[:], types.double[:], types.double[:]))
def foo(res, x, y):
    i = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    if i >= res.shape[0]:
        return

    res[i] = dev_bar(x[i], y[i])

@cuda.jit(device=True)
def dev_bar(a, b):
    return a + b

g = np.arange(256.)
h = np.arange(256.)
ret = np.zeros_like(g)

threadsperblock = 32
blockspergrid = (g.size + (threadsperblock - 1)) // threadsperblock
foo[blockspergrid, threadsperblock](ret, g, h)

print(ret)
```
which works under the simulator but not on hardware. I expect it's because on the CPU `Thread` running with target `foo` can see `dev_bar`.

I've added https://github.com/numba/numba/issues/2965 RE the error message.

**Comment by stuartarchibald** [comment] 2018-05-29 09:34
Closing this as it is known and valid behaviour, @sklam offers the reason for this.

**Closed by stuartarchibald** 2018-05-29 09:34 UTC
Labels: bug
