### ISSUE TITLE
TypingError with "in" operator comparing range() items with list

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5171] opened 2020-01-31 09:01 UTC
On numba master the following fails to compile:

```python
from numba import njit

@njit
def test_numba():
    source = [1, 2, 3]
    output = [n for n in range(6) if n not in source]
    return output

test_numba()
```

Output:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Type of variable '$14compare_op.5.13' cannot be determined, operation: unary(fn=, value=$14compare_op.5.13), location:  (6)

File "", line 6:
def test_numba():
    
    source = [1, 2, 3]
    output = [n for n in range(6) if n not in source]
    ^
```

**Comment by esc** [comment] 2020-01-31 10:41
@ARF1 thanks for reporting this. I can reproduce this locally and it does look like a bug indeed.

**Comment by esc** [comment] 2020-02-03 16:10
@ARF1 can you convert the code into a basic loop and then checking if the problem persists?

**Comment by ARF1** [comment] 2020-02-03 17:28
@esc A basic loop works:

```python
In [1]: from numba import njit
   ...:
   ...: @njit
   ...: def test_numba():
   ...:     source = [1, 2, 3]
   ...:     output = []
   ...:     for n in range(6):
   ...:         if n not in source:
   ...:             output.append(n)
   ...:     return output
   ...:
   ...: test_numba()
Out[1]: [0, 4, 5]
```

**Comment by esc** [comment] 2020-02-03 20:03
@ARF1 thanks for circling back on this one! I believe this indicates that there is some issue with the type-inference of the list comprehension. While this is a bit unfortunate, anyone hitting this is advised to use the loop version above for the time being.

**Comment by stuartarchibald** [comment] 2020-02-06 10:06
This is happening because the IR ends up like:
```
label 9:
    n.10 = $phi8.2.9                         ['$phi8.2.9', 'n.10']
    $12load_deref.4.12 = source              ['$12load_deref.4.12', 'source']
    $14compare_op.5.13 = n.10 in $12load_deref.4.12 ['$12load_deref.4.12', '$14compare_op.5.13', 'n.10']
    $14compare_op.5.13 = unary(fn=<built-in function not_>, value=$14compare_op.5.13) ['$14compare_op.5.13', '$14compare_op.5.13']
    branch $14compare_op.5.13, 19, 25        ['$14compare_op.5.13']
```
after the closure is inlined, then DCE runs which eliminates the first `$14compare_op.5.13`. The root cause is that basically two Vars end up with the same name.

`get_ir_of_code` is producing:
```
label 8:
    del $6for_iter.4                         []
    n = $phi8.2                              ['$phi8.2', 'n']
    del $phi8.2                              []
    $12load_deref.4 = freevar(source: None)  ['$12load_deref.4']
    $14compare_op.5 = n in $12load_deref.4   ['$12load_deref.4', '$14compare_op.5', 'n']
    del $12load_deref.4                      []
    $14compare_op.5 = unary(fn=<built-in function not_>, value=$14compare_op.5) ['$14compare_op.5', '$14compare_op.5']
    branch $14compare_op.5, 18, 25           ['$14compare_op.5']
```
for the closure, so I don't think it's the inliner at fault and more likely something wrong in byteflow analysis.

**Comment by stuartarchibald** [comment] 2021-12-16 16:09
This doesn't reproduce on mainline at ~0.55 (assume that the inliner scoping work fixed it). Closing.

**Closed by stuartarchibald** 2021-12-16 16:09 UTC
Labels: bug
