### ISSUE TITLE
Implicit narrowing conversion for list

### ISSUE THREAD

**Issue by memeplex** [numba/numba#1544] opened 2015-11-21 19:03 UTC
```
@jit(nopython=True)
def f(x):
    x1, x2 = x
    return x2
```

```
In: f([1,2.5])
Out: 2
```

```
In: f.inspect_types()
f (reflected list(int64),)
```

I don't think this is intended but a bug. An error must be reported or a safer type cast must be done.

**Comment by pitrou** [comment] 2015-12-01 13:49
This is due to the way dispatching in done on list arguments. Only the first list element is considered for type selection, and the other elements are converted. We cannot consider all list elements, because it would make dispatch much too slow (think about a 100-elements list).

So this is not really intended, but more of a by-product of the implementation decisions here...

**Comment by seibert** [comment] 2015-12-01 13:54
Can we raise an error in the wrapper if an unsafe cast has to be made?  That would at least prevent things like silent truncation.

**Comment by pitrou** [comment] 2015-12-01 14:15
Do you mean disallow float whenever an integer argument is expected, or only inside a list? The latter would add some nasty special-casing...

**Comment by seibert** [comment] 2015-12-01 14:22
The problem is that the first situation (float arg passed when int expected) will typically trigger the JIT to create a float version of the function (unless the function is closed to further compilation), so a user is unlikely to see any truncation problem.

In the second case, the JIT cannot trigger, and the user is guaranteed to get an unsafe cast.  (And someone starting a float list with an integer is very easy to do.) So yes, I think we have to special case this, unfortunately...

**Comment by pitrou** [comment] 2016-01-05 20:00
Now that I'm thinking about it, a brutal but generic way to solve this would be to mandate that the type of all list items is identical. This is a simple pointer compare so should be fast.

**Comment by memeplex** [comment] 2016-01-05 20:48
I'm curious, not that this is the best place to ask this, but anyway:

I understand you have plans to eventually remove the drastic nopython/object mode distinction. If that happens and you already have implemented lists and tuples numba-side, what will be the syntax to use a list or tuple through the c api (as in cython)? Given that lists are "copied" on input and output, sometimes there could be a legitimate desire of using a cpython list through the api, but no way to express that because the syntax was already taken.

**Comment by pitrou** [comment] 2016-01-05 20:54
That's a rather good question, and we don't have an answe for it. 
For now we don't have any concrete plans to remove the nopython/object mode schism. It would make a lot of sense to do so, but it implies a lot of surgery in the code. So it's merely something that sits in the back of our heads until it matures enough that we decide we're good to go :-)

**Comment by memeplex** [comment] 2016-01-05 20:56
Ok, thank you for your frank answer. I have ninjaedited my previous comment while you were already answering, though. At least I guess, maybe you're able to type 100 words per ms :)

**Comment by seibert** [comment] 2016-01-05 21:10
A next step for us would be making the python / nopython mode distinction at the level of blocks (not just loops), rather than entire functions or lifted loops.  This can get dangerous because it makes it very easy to incur invisible overhead switching into and out of nopython mode, so I don't know how we would mitigate that hazard yet.

**Comment by memeplex** [comment] 2016-01-05 21:21
IMO the problem here is simply that python type list is not homogeneous. Maybe numba shouldn't pretend so hard that numba lists and python lists are the same. As I see it, another manifestation of this problem is the need to copy lists at input/output, so the semantic caveat "changes won't be reflected until the function returns" is in order. One way out is to require some homogeneous subclass of list, instead of plain lists. Otherwise a structural check, element by element, should be done. Or to believe in the good will and sense of the caller.

**Comment by seibert** [comment] 2016-01-05 21:34
This is a valid point.  Part of the reason we implemented lists as an experimental feature was to try to discover how problematic the mismatch turns out to be in practice, and if there were any viable techniques for passing small Python object-based data structures across the no-python mode barrier.

For me, lists are not significantly interesting for Numba since for simple types a NumPy array *is* the homogenous list object.  However, a real use case we run into all the time is the need to pass a dictionary into no-python mode function.  The same technique used to handle a Python list would also work for a Python dict (with a little more typing complexity since we need a homogenously typed key and value), and that would be very useful.

I'm still on the fence about whether this whole approach is more dangerous than useful.  If we decide not to ever support passing Python dictionaries across the boundary, then we absolutely need to provide a dict-like data type in Numba that can be easily translated to/from a Python dictionary.  It is just too useful of a data structure to exclude it from nopython mode.

**Comment by memeplex** [comment] 2016-01-05 21:46
That's why I was suggesting the c api approach a la cython above, you can have great performance (llvm + ndarrays/buffers) combined with great flexibility (python + high level data structures). But at this point my ignorance about the complexities of combining the numba world with the cpython world -and the headaches this could cause regarding type inference- is abysmal. And as such an ignorant I tend to think: why don't they just drop the distinction?

**Comment by memeplex** [comment] 2016-01-05 21:55
A real use case, for the record: I started thinking about this issues because I needed to do a fast tree traversal. The tree was very large. For every node some kind of numerical operation was done. For a tiny number of nodes, a dictionary query was done. This is a special case of the 80/20 rule, the problem being that sometimes high level operations are very intertangled with low level ones, and this it's very difficult to isolate them at the function call boundary. I ended up implementing a node as an extension class.

**Comment by seibert** [comment] 2016-01-05 22:22
Perhaps a better solution would be to invert the control and allow a nopython mode function to switch back to python mode (reacquire the GIL, etc, etc) inside of a block if explicitly requested?  I guess that would require type inference to allow variables pointing at Python objects to exist in nopython mode code as long as they are not accessed.

Imagining some like this (contrived example):
``` python
@jit(nopython=True):
def do_stuff(x, my_array, default_values):
    if x > 10:
        with python_mode:  # Lift this block out into a function that acquires the GIL, wraps values into Python objects, and runs the following code with the Python interpreter
            my_array[x] = default_values['out_of_range']
    else:
        my_array[x] = x**2 + 1
````

**Comment by memeplex** [comment] 2016-01-06 04:13
I'm not familiar with the difficulties you are facing here. For example, the need to wrap that block inside a function. Is it because the way numba is currently organized will make it simpler to keep the two worlds separated into functions? If that is so, I believe yours is a good idea. I'm not sure about the need to explicitly demarcate the block, though, couldn't it be inferred without too much hassle? Moreover, would optional type annotations help to integrate both worlds or are you afraid of the loss of generality implied by fixing some types of local variables? There is now the possibility to specify a signature although it's not recommended, with sound reasons. In cython it's easy to cast a python object to a closer to the metal type, back and forth. but support for generic programming is minimal, while numba excels at this because of jit compilation and type inference.

**Comment by seibert** [comment] 2016-01-06 17:11
Our current model of code lowering assumes that functions are either 100% nopython mode (which means no python objects, and no CPython API calls) or not.  This restriction ensures that all Python object boxing/unboxing code only appears at function boundaries.  In fact, we JIT a wrapper that handles the object boxing/unboxing that in turn calls another function which is the pure nopython lowering of the original Python function body.  This allows other nopython mode JIT functions to bypass the wrapper.

The advantage of organizing the code this way is that we avoid having to assess the cost of transforming the representation of a piece of data (say, converting a Python object into a machine-friendly representation) inside the function.  Previous implementations of Numba allowed for the switch in and out of nopython mode to happen on a statement level.  This created some paradoxical situations where Numba's attempts to speed up some kinds of code had a negative effect that was hard to understand because the transitions were effectively invisible.  Tracing JITs have to worry about these kinds of issues (and all have "deoptimization" triggers to detect when an optimization has backfired), but Numba doesn't have this level of instrumentation yet.  It isn't obvious whether that kind of JIT model is possible to implement in Numba without also modifying the CPython interpreter (a direction we wish to avoid for many reasons).

(To be honest, another reason our compiler pipeline imposes these restrictions is that it allows us to more easily share compiler internals with our GPU targets, where there is no option to fall back to CPython API calls in the middle of a function.)

I would describe Numba's current strategy is seeing how far a conservative, highly restrictive JIT model can go, and then assess how to incrementally expand that model when the current "function-at-a-time" approach runs out of steam.

**Comment by pitrou** [comment] 2016-01-06 18:02
This is a duplicate of #1594, by the way. I would rather ask people to continue the discussion there (unless it's an off-topic one ;-)).

**Closed by pitrou** 2016-01-06 18:02 UTC

**Comment by memeplex** [comment] 2016-01-07 01:58
Thank you for the discussion @pitrou and @seibert, it was a very interesting conversation, for me at least. As an outsider with a superficial appreciation of numba complexities, my wish is that clever people like you invest more time in allowing the access to python from numba instead of reimplementing a mini-python inside nopython mode in a piecemeal fashion, because I feel it's a more general approach with a better cost-benefit trade off, that could be blocked once python syntax is definitively taken for another uses. That said, you know much better than me.
