### ISSUE TITLE
Masked array support

### ISSUE THREAD

**Issue by seibert** [numba/numba#2103] opened 2016-09-06 19:15 UTC
The would be handy in some cases, but not a high priority

**Comment by ml31415** [comment] 2017-07-19 12:54
Side note, this was already asked for in #1834. I'd suggest to close one of them.

**Comment by zxdawn** [comment] 2018-08-07 07:36
It seems still doesn't support.

**Comment by stephenworsley** [comment] 2019-07-04 15:37
Just to mention masked arrays come up a bit in a meteorological context (Iris).

**Comment by stuartarchibald** [comment] 2020-05-29 16:03
Closing as duplicate of https://github.com/numba/numba/issues/1834

**Closed by stuartarchibald** 2020-05-29 16:03 UTC
Labels: Numba1.0, lowpriority
