### ISSUE TITLE
l have got  a LLVM IR

### ISSUE THREAD

**Issue by chenxinghao** [numba/numba#1785] opened 2016-03-22 03:15 UTC

**Comment by chenxinghao** [comment] 2016-03-22 03:23
l have got a LLVM IR form setting the NUMBA_DUMP_LLVM environment variable to 1,but l can't find metadata msg,can I  find a way to correspond the LLVM ir code in  line number of python ?

**Comment by sklam** [comment] 2016-03-29 16:25
Numba does not generate any metadata (or debug info) in the llvm, yet.  The closest you can get is to use the following 3 environment variables:

* ``NUMBA_DEBUG_JIT=1``: add ``puts(<ir_statement>)`` at the start of each Numba-IR statement.
* ``NUMBA_DUMP_LLVM=1``: with ``NUMBA_DEBUG_JIT=1``, it is easier to see what LLVM-IR is generated for each Numba-IR statement.  
For example:

 ```llvm
B6:
  %".25" = call i32 (i8*) @"puts"(i8* bitcast ([48 x i8]* @".const.DEBUGJIT: $6.1 = global(range: <class 'range'>)" to i8*))
  %".27" = load i8*, i8** %"$6.1"
  store i8* null, i8** %"$6.1"
  %".29" = call i32 (i8*) @"puts"(i8* bitcast ([30 x i8]* @".const.DEBUGJIT: $6.3 = call $6.1(a)" to i8*))
  %".30" = load i64, i64* %"a"
  %".31" = call i32 (i8*) @"puts"(i8* bitcast ([63 x i8]* @".const.DEBUGJIT: # calling normal function: Function(<class 'range'>)" to i8*))
  %".34" = getelementptr inbounds {i64, i64, i64}, {i64, i64, i64}* %".32", i32 0, i32 0
  store i64 0, i64* %".34"
  %".36" = getelementptr inbounds {i64, i64, i64}, {i64, i64, i64}* %".32", i32 0, i32 1
  store i64 %".30", i64* %".36"
  %".38" = getelementptr inbounds {i64, i64, i64}, {i64, i64, i64}* %".32", i32 0, i32 2
``` 
* ``NUMBA_DUMP_ANNOTATION=1``: show the python source and their corresponding numba-ir code; 
For example:

```
def foo(a):

    # --- LINE 6 ---
    # label 0
    #   a = arg(0, name=a)  :: int64
    #   $const0.1 = const(int, 0)  :: int64
    #   c = $const0.1  :: int64
    #   del $const0.1

    c = 0

    # --- LINE 7 ---
    #   jump 6
    # label 6
    #   $6.1 = global(range: <class 'range'>)  :: Function(<class 'range'>)
    #   $6.3 = call $6.1(a)  :: (int64,) -> range_state_int64
    #   del a
```

**Comment by pitrou** [comment] 2016-03-30 13:40
Closing this as not a bug.

**Closed by pitrou** 2016-03-30 13:40 UTC
