### ISSUE TITLE
X[:, i].copy() is extremely slow in nopython mode

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1671] opened 2016-01-27 17:15 UTC
When running this

    import numpy as np
    from numba import njit
    X = np.random.randn(2, 1000000)
    @njit
    def f(index):
        Y = X[:, index].copy()
        return Y
    f(0)

It takes about 60 seconds to compile the function on my machine

whereas by running 

    def g(index):
        Y = X[:, index].copy()
        return Y
    g(0)

It is instantaneous.

Running 

    %timeit f(0)
    %timeit g(0)

Does show that after compilation f is faster (510 ns per loop) than g (809 ns per loop). But in terms of compilation time it is really slow! Does this make sense?

**Comment by seibert** [comment] 2016-01-27 17:36
I agree that 60 seconds to compile that function seems every long.  What Numba version, OS and hardware platform are you using?

**Comment by pitrou** [comment] 2016-01-27 17:47
It's probably a duplicate of https://github.com/numba/numba/issues/875
This is due to the global array being materialized as a LLVM array constant...

**Comment by pitrou** [comment] 2016-01-27 17:50
Closing as duplicate.

**Closed by pitrou** 2016-01-27 17:50 UTC

**Comment by seibert** [comment] 2016-01-27 17:53
ah, missed that the array was not being passed in.  The general workaround here is to pass large arrays as parameters for now.

**Comment by seibert** [comment] 2016-01-27 17:54
This also might be a good use case for `@jitclass` if X does not need to be truly global.

**Comment by nunocalaim** [comment] 2016-01-27 21:31
@seibert I'm in OSX 10.10.5 with numba 0.23.1. You said that this might be a use case for @jitclass and this depends on X being or not truly global. I'm failing to make sense of why using classes might help in this situation.

**Comment by seibert** [comment] 2016-01-27 22:23
A global variable + a function behaves a lot like a class where the global variable becomes an instance attribute, and the function becomes a method.  This would allow you to carry around some state (`X`) and the code to use it (`f()`) in a way that avoids Numba trying to inline the data.
