### ISSUE TITLE
ImportError: Numba could not be imported.

### ISSUE THREAD

**Issue by mbtallbert** [numba/numba#5632] opened 2020-04-25 21:39 UTC
Am trying to set uo and environment for machine learning with pycaret

`from pycaret.classification import *
exp1 = setup(diabetes, target = 'Class variable')`
 
and i am getting an error below

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\typeconv.py in <module>
      3     # Numba, if it fails to import, provide some feedback
----> 4     from numba.core.typeconv import _typeconv
      5 except ImportError as e:

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-a2db6282563d> in <module>
      1 from pycaret.classification import *
----> 2 exp1 = setup(diabetes, target = 'Class variable')

~\AppData\Roaming\Python\Python37\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, session_id, silent, profile)
    878 
    879     #import library
--> 880     from pycaret import preprocess
    881 
    882     data = preprocess.Preprocess_Path_One(train_data = data, 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\preprocess.py in <module>
     24 from sklearn.decomposition import IncrementalPCA
     25 from sklearn.preprocessing import KBinsDiscretizer
---> 26 from pyod.models.knn import KNN
     27 from pyod.models.iforest import IForest
     28 from pyod.models.pca import PCA as PCA_od

~\AppData\Roaming\Python\Python37\site-packages\pyod\__init__.py in <module>
      2 
      3 from . import models
----> 4 from . import utils
      5 # TODO: add version information here
      6 

~\AppData\Roaming\Python\Python37\site-packages\pyod\utils\__init__.py in <module>
      9 from .data import generate_data
     10 from .data import evaluate_print
---> 11 from .stat_models import pairwise_distances_no_broadcast
     12 from .stat_models import wpearsonr
     13 from .stat_models import pearsonr_mat

~\AppData\Roaming\Python\Python37\site-packages\pyod\utils\stat_models.py in <module>
      9 
     10 import numpy as np
---> 11 from numba import njit
     12 from scipy.stats import pearsonr
     13 from sklearn.utils.validation import check_array

~\AppData\Roaming\Python\Python37\site-packages\numba\__init__.py in <module>
     18 
     19 # Re-export typeof
---> 20 from numba.misc.special import (
     21     typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init,
     22     literally, literal_unroll

~\AppData\Roaming\Python\Python37\site-packages\numba\misc\special.py in <module>
      1 import numpy as np
      2 
----> 3 from numba.core.typing.typeof import typeof
      4 
      5 

~\AppData\Roaming\Python\Python37\site-packages\numba\core\typing\__init__.py in <module>
----> 1 from .context import BaseContext, Context
      2 from .templates import (signature, make_concrete_template, Signature,
      3                         fold_arguments)

~\AppData\Roaming\Python\Python37\site-packages\numba\core\typing\context.py in <module>
      9 import numba
     10 from numba.core import types, errors
---> 11 from numba.core.typeconv import Conversion, rules
     12 from numba.core.typing import templates
     13 from .typeof import typeof, Purpose

~\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\rules.py in <module>
      1 import itertools
----> 2 from .typeconv import TypeManager, TypeCastingRules
      3 from numba.core import types
      4 
      5 

~\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\typeconv.py in <module>
     15            "possible please include the following in your error report:\n\n"
     16            "sys.executable: %s\n")
---> 17     raise ImportError(msg % (url, reportme, str(e), sys.executable))
     18 
     19 from numba.core.typeconv import castgraph, Conversion

ImportError: Numba could not be imported.

> 

Kindly assist with a diagnosis and solution

**Comment by seibert** [comment] 2020-04-25 22:01
This is likely a duplicate of #5600.  There is a [workaround](https://github.com/numba/numba/issues/5600#issuecomment-617937885) in the issue discussion that should help until we get a patch release out next week.

**Comment by esc** [comment] 2020-04-26 13:48
@mbtallbert thank you for raising this issue with the Numba issue tracker. @seibert I concur with that assessment, will label and close the issue. @mbtallbert in case this is a mistake, please feel free to re-open the issue with additional information, thanks!

**Closed by esc** 2020-04-26 13:48 UTC
Labels: duplicate, no action required
