### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by hdcomb** [numba/numba#4308] opened 2019-07-11 12:10 UTC
Warning (from warnings module):
```
  File "D:\Desktop\Python编程学习\计算.py", line 3
    @jit
NumbaWarning: [1m
Compilation is falling back to object mode WITH looplifting enabled because Function "foo" failed type inference due to: [1m[1mUnknown attribute 'time' of type Module(<module 'time' (built-in)>)
[1m
File "计算.py", line 5:[0m
[1mdef foo(x,y):
[1m        tt = time.time()
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: typing of get attribute at D:\Desktop\Python编程学习\计算.py (5)[0m
[1m
File "计算.py", line 5:[0m
[1mdef foo(x,y):
[1m        tt = time.time()
[0m        [1m^[0m[0m
[0m

Warning (from warnings module):
  File "D:\Desktop\Python编程学习\计算.py", line 3
    @jit
NumbaWarning: [1m
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "foo" failed type inference due to: [1m[1mcannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>[0m
[1m
File "计算.py", line 7:[0m
[1mdef foo(x,y):
    <source elided>
        s = 0
[1m        for i in range(x,y):
[0m        [1m^[0m[0m
[0m[0m
Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 661, in new_error_context
    yield
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\pylowering.py", line 176, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.ir.Print'>, <numba.ir.Print object at 0x00000267563296D8>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\Python编程学习\计算.py", line 12, in <module>
    print(foo(1,100000000))
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 370, in _compile_for_args
    raise e
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 659, in backend_object_mode
    self.flags)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\J\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
[1m[1m(<class 'numba.ir.Print'>, <numba.ir.Print object at 0x00000267563296D8>)
[1m
File "计算.py", line 9:[0m
[1mdef foo(x,y):
    <source elided>
                s += i
[1m        print('Time used: {} sec'.format(time.time()-tt))
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "print($40.9)" at D:\Desktop\Python编程学习\计算.py (9)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
````

**Comment by stuartarchibald** [comment] 2019-07-11 12:21
NOTE: I've updated the report to format it. For future, GitHub has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment] 2019-07-11 12:25
Thanks for the report. This would reproduce:
```python
from numba import jit

@jit
def foo():
    acc = 0
    for x in range(10):
        acc += x
    object()
    print(acc)

foo()
```
It looks like another objmode+looplift refactor bug artifact and I can confirm it is fixed by https://github.com/numba/numba/pull/4224.

**Closed by stuartarchibald** 2019-07-11 12:25 UTC
