### ISSUE TITLE
simple recursion throws LLVM exception in 0.29.0

### ISSUE THREAD

**Issue by dnelson86** [numba/numba#2216] opened 2016-12-02 15:28 UTC
My original goal for recursion from issue #136 was working after the introduction of support for simple recursion, but now in v 0.29.0 this simple example has broken:

```
import numpy as np
from numba import jit

@jit(nopython=True, nogil=True)
def _updateNodeRecursive2(last):
    if last > 3:
        return

    for i in range(4):
        last += 1
        _updateNodeRecursive2(last)

@jit(nopython=True, nogil=True)
def _constructTree2():
    last = np.int32(-1)
    _updateNodeRecursive2(last)

def test():
    _constructTree2()
```

produces:

```
python: /test/llvm-3.8.1.src/lib/ExecutionEngine/ExecutionEngine.cpp:218: void llvm::ExecutionEngine::addGlobalMapping(llvm::StringRef, uint64_t): Assertion `(!CurVal || !Addr) && "GlobalMapping already established!"' failed.
Aborted (core dumped)
```

**Comment by sklam** [comment] 2016-12-05 09:47
Can you tell us which python version and OS you are using?  I tried on Mac and Linux with python3.5 and cannot reproduce the problem.

**Comment by dnelson86** [comment] 2016-12-05 12:57
This is python 2.7.10, both on Linux 2.6.32-642.6.2.el6.x86_64 and Linux 2.6.32-279.11.1.el6.x86_64.

llvmlite (0.14.0), LLVM version 3.8.1

**Comment by sklam** [comment] 2016-12-06 04:20
Are you using the conda packages?  Or, did you build numba, llvmlite, or llvm from source?

**Comment by sklam** [comment] 2016-12-06 07:37
Does the error occur by just running `test()` from the snippet?

I tested with centos5 2.6.18-410.el5 x86_64 and newer ubuntu14.04 3.13.0-32 x86_64 and still can't reproduce the problem.  

Since there's nogil=True, did you see the problem in a multithreaded execution?

**Comment by dnelson86** [comment] 2016-12-06 10:15
This is built from source, not conda. Yes the error occurs just as:

```
$ python
Python 2.7.10 (default, Dec  3 2015, 16:18:18)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import test2
>>> test2.test()
python: /dnelson/test/llvm-3.8.1.src/lib/ExecutionEngine/ExecutionEngine.cpp:218: void llvm::ExecutionEngine::addGlobalMapping(llvm::StringRef, uint64_t): Assertion `(!CurVal || !Addr) && "GlobalMapping already established!"' failed.
Aborted
```

I have deleted the `nogil=True` and the behavior is identical.

**Comment by dnelson86** [comment] 2016-12-06 15:44
I have also verified the same behavior on python 2.7.12 on "windows bash"/Ubuntu:

```
$ python
Python 2.7.12 (default, Dec  6 2016, 16:01:22)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import test2
>>> test2.test()
python2.7.12: /home/dnelson/llvm-3.8.1.src/lib/ExecutionEngine/ExecutionEngine.cpp:218: void llvm::ExecutionEngine::addGlobalMapping(llvm::StringRef, uint64_t): Assertion `(!CurVal || !Addr) && "GlobalMapping already established!"' failed.
Aborted (core dumped)
$ uname -a
Linux HOSTNAME 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

I am surprised we cannot reproduce?

**Comment by seibert** [comment] 2016-12-06 17:04
The conda build of LLVM applies 4 patches from the LLVM bug tracker that have not been merged yet:

https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/meta.yaml#L16-L23

(The comments give links for each patch.)

I think the next step will be for @sklam to build without those patches and see if the problem appears.

**Comment by dnelson86** [comment] 2016-12-06 17:45
I have verified the problem is not present in the conda packages (on the same system):

```
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

conda                     4.2.13                   py27_0
llvmlite                  0.14.0                   py27_0
numba                     0.29.0              np111py27_0
```

I cannot see that any of those patches have anything to do with the error, but I guess it must be somewhere in there.

**Comment by seibert** [comment] 2016-12-06 19:39
The only other possibly relevant difference is that we compile LLVM with gcc 4.8 on CentOS 5.

**Comment by sklam** [comment] 2016-12-13 07:52
I can reproduce now.  Our build recipe didn't enable assertion.  Building with assertion reveals the error.

**Closed** 2016-12-21 14:25 UTC
