### ISSUE TITLE
Compiled code returns wrong values or crashes

### ISSUE THREAD

**Issue by drthice** [numba/numba#3778] opened 2019-02-19 16:56 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The function _PT1()_ from the minimal reproducer below yields different result when being interpreted by Python vs. beeing compiled with Numba. The Numba version seems to somehow mix up memory locations, as it returns the conents of _values_ instead of the contents of _out_, like it should. Even worse, when altering the line 
``` python
out = np.empty_like(times) # using out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether
```
as written in the comment, the Numba compiled code seems to crash, as the 2nd print statement is not reached anymore. Fiddling around with the code a bit more made it return even more suprising values.

The bug seems to be related to the return statement, as uncommenting the line
``` python
# print(out) # calling print here delivers the correct results!
```
delivers the correct results from within the jitted function!

``` python
import numpy as np
import numba

times = np.arange(0., 5., 1.)
values = 1. * (times >= 3.)

def PT1(times, values):
    T = 4.
    out = np.empty_like(times) # using out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether
    out[0] = values[0]
    i = 1
    while i < times.shape[0]:
        dt = times[i] - times[i-1]
        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt) 
        i += 1
    # print(out) # calling print here delivers the correct results!
    return out


print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]
PT1 = numba.jit(PT1)
print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]
```

**Comment by stuartarchibald** [comment] 2019-02-20 10:05
Thanks for the report. I'm afraid I cannot reproduce any of the things you see... here is the output from trying to reproduce on the terminal, running the original script, and then some modifications as suggested:
```

$ python -c 'import numba; print(numba.__version__)'
0.42.0


$ cat issue3778.py 
import numpy as np
import numba

times = np.arange(0., 5., 1.)
values = 1. * (times >= 3.)

def PT1(times, values):
    T = 4.
    out = np.empty_like(times) # using out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether
    out[0] = values[0]
    i = 1
    while i < times.shape[0]:
        dt = times[i] - times[i-1]
        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt) 
        i += 1
    # print(out) # calling print here delivers the correct results!
    return out


print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]
PT1 = numba.jit(PT1)
print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]

$ python issue3778.py 
[0.   0.   0.   0.2  0.36]
[0.   0.   0.   0.2  0.36]


$ cat issue3778.py 
import numpy as np
import numba

times = np.arange(0., 5., 1.)
values = 1. * (times >= 3.)

def PT1(times, values):
    T = 4.
    out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether
    out[0] = values[0]
    i = 1
    while i < times.shape[0]:
        dt = times[i] - times[i-1]
        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt) 
        i += 1
    print(out) # calling print here delivers the correct results!
    return out


print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]
PT1 = numba.jit(PT1)
print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]

$ python issue3778.py 
[0.   0.   0.   0.2  0.36]
[0.   0.   0.   0.2  0.36]
[0.   0.   0.   0.2  0.36]
[0.   0.   0.   0.2  0.36]


$ cat issue3778.py 
import numpy as np
import numba

times = np.arange(0., 5., 1.)
values = 1. * (times >= 3.)

def PT1(times, values):
    T = 4.
    out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether
    out[0] = values[0]
    i = 1
    while i < times.shape[0]:
        dt = times[i] - times[i-1]
        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt) 
        i += 1
    #print(out) # calling print here delivers the correct results!
    return out


print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]
PT1 = numba.jit(PT1)
print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]

$ python issue3778.py 
[0.   0.   0.   0.2  0.36]
[0.   0.   0.   0.2  0.36]
```

I'm wondering if this is perhaps OS etc related. Please could you paste the output of `numba -s` (redact any parts you don't want to share first!)? Thanks.

**Comment by drthice** [comment] 2019-02-20 10:20
Thank you for getting back to me. The problem was actually me misusing pipenv, which caused my code to run with numba 0.41.0, instead of 0.42.0, as I thought it would do. I can confirm that with numba 0.42.0 everything works as expected. Sorry for the inconvinience.


Von: stuartarchibald <notifications@github.com>
Gesendet: Mittwoch, 20. Februar 2019 11:06
An: numba/numba <numba@noreply.github.com>
Cc: drthice <theiss@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [numba/numba] Compiled code returns wrong values or crashes (#3778)


Thanks for the report. I'm afraid I cannot reproduce any of the things you see... here is the output from trying to reproduce on the terminal, running the original script, and then some modifications as suggested:



$ python -c 'import numba; print(numba.__version__)'

0.42.0





$ cat issue3778.py

import numpy as np

import numba



times = np.arange(0., 5., 1.)

values = 1. * (times >= 3.)



def PT1(times, values):

    T = 4.

    out = np.empty_like(times) # using out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether

    out[0] = values[0]

    i = 1

    while i < times.shape[0]:

        dt = times[i] - times[i-1]

        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt)

        i += 1

    # print(out) # calling print here delivers the correct results!

    return out





print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]

PT1 = numba.jit(PT1)

print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]



$ python issue3778.py

[0.   0.   0.   0.2  0.36]

[0.   0.   0.   0.2  0.36]





$ cat issue3778.py

import numpy as np

import numba



times = np.arange(0., 5., 1.)

values = 1. * (times >= 3.)



def PT1(times, values):

    T = 4.

    out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether

    out[0] = values[0]

    i = 1

    while i < times.shape[0]:

        dt = times[i] - times[i-1]

        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt)

        i += 1

    print(out) # calling print here delivers the correct results!

    return out





print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]

PT1 = numba.jit(PT1)

print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]



$ python issue3778.py

[0.   0.   0.   0.2  0.36]

[0.   0.   0.   0.2  0.36]

[0.   0.   0.   0.2  0.36]

[0.   0.   0.   0.2  0.36]





$ cat issue3778.py

import numpy as np

import numba



times = np.arange(0., 5., 1.)

values = 1. * (times >= 3.)



def PT1(times, values):

    T = 4.

    out = np.zeros(times.shape[0]) # prevents the 2nd print() alltogether

    out[0] = values[0]

    i = 1

    while i < times.shape[0]:

        dt = times[i] - times[i-1]

        out[i] = out[i-1] + (values[i] - out[i-1]) * dt / (T + dt)

        i += 1

    #print(out) # calling print here delivers the correct results!

    return out





print(PT1(times, values)) # [0.   0.   0.   0.2  0.36]

PT1 = numba.jit(PT1)

print(PT1(times, values)) # should be equal, but: [0. 0. 0. 1. 1.]



$ python issue3778.py

[0.   0.   0.   0.2  0.36]

[0.   0.   0.   0.2  0.36]

I'm wondering if this is perhaps OS etc related. Please could you paste the output of numba -s (redact any parts you don't want to share first!)? Thanks.

**Comment by stuartarchibald** [comment] 2019-02-20 10:30
No problem. Thanks for getting back to us, glad Numba is working as expected! Closing.

**Closed by stuartarchibald** 2019-02-20 10:30 UTC
Labels: needtriage
