### ISSUE TITLE
UndefinedType Error

### ISSUE THREAD

**Issue by abdullahkavakli** [numba/numba#8441] opened 2022-09-15 15:07 UTC
I have tried using the stable released version of Numba .
The code I used is from here: https://numba.readthedocs.io/en/stable/cuda/cudapysupported.html

The code I run is this: 
```
from numba import cuda

@cuda.jit("int64(int64)", device=True)
def fib(n):
    if n < 2:
        return n
    return fib(n - 1) + fib(n - 2)
```

and although it's from docs I got this error:
```
File "C:\Users\xxx\.conda\envs\stable\lib\site-packages\numba\core\typeinfer.py", line 1466, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)

TypingError: Cannot determine Numba type of <class 'numba.core.ir.UndefinedType'>```

**Comment by esc** [comment] 2022-09-15 15:29
@abdullahkavakli thank you for asking about this. Can you provide more details on how to reproduce? I tried the following code but was unable to reproduce:

```python
from numba import njit


@njit
def fib(n):
    if n < 2:
        return n
    return fib(n - 1) + fib(n - 2)


print(fib(10))
```

**Comment by abdullahkavakli** [comment] 2022-09-15 15:32
I edited the code. Can u try again?

**Comment by abdullahkavakli** [comment] 2022-09-17 12:45
I just run the script above. Python version is 3.9.7, numba version is 0.54.1

**Comment by stuartarchibald** [comment] 2022-09-20 08:33
> I just run the script above. Python version is 3.9.7, numba version is 0.54.1

Thanks for confirming @abdullahkavakli. Self recursive device function support was added to the CUDA target in Numba version 0.56.0, if you update your Numba installation to that version or above it should work fine.
https://github.com/numba/numba/blob/d6731f6d22f6695ee7abc305f81f81115639e2a4/CHANGE_LOG#L102-L106

**Comment by esc** [comment] 2022-09-22 13:41
@abdullahkavakli thank you for following up. I am assuming this is now resolved and closing. Updating to a newer Numba should solve your issue.

**Closed by esc** 2022-09-22 13:41 UTC
Labels: question
