### ISSUE TITLE
please add np.min()/max() with augment:"axis"

### ISSUE THREAD

**Issue by scirocc** [numba/numba#8399] opened 2022-08-26 03:31 UTC
when  dealing with a n-dim array. I can't get the easiest work done like getting the smallest number of each row.

**Comment by sklam** [comment] 2022-08-30 14:16
related https://github.com/numba/numba/issues/1269

**Comment by stuartarchibald** [comment] 2022-09-05 09:53
xref #4414, possible duplicate?

**Comment by gmarkall** [comment] 2022-09-06 09:30
Closing as a duplicate of #1269

**Closed by gmarkall** 2022-09-06 09:30 UTC
Labels: feature_request
