### ISSUE TITLE
Why does numba not work with this nested function?

### ISSUE THREAD

**Issue by mbramerloh** [numba/numba#3095] opened 2018-07-11 14:38 UTC
## Bug report: why does numba not work with this nested function?

I am trying to precompile a minimzation running on 3D time series data with numba. As a first step, I wanted to define a cost function, but this already fails. Here is my code:

```
from numba import jit

@jit
def tester(axis,data):
    def lineCost(pars):
        A=pars[0]
        B=pars[1]
        return np.sum((A*axis+B - data)**2)
    return lineCost([axis,data])

tester(1,2)
```
This yields a "Not implemented" error:
```
~/.local/lib/python3.5/site-packages/numba/lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

~/.local/lib/python3.5/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215
    216         # Close tail of entry block

~/.local/lib/python3.5/site-packages/numba/lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240
    241         self.post_lower()

~/.local/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255
    256     def create_cpython_wrapper(self, release_gil=False):

/usr/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

~/.local/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    583         from numba import config
    584         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 585         six.reraise(type(newerr), newerr, tb)
    586
    587

~/.local/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660
    661 else:

LoweringError: Failed at object (object mode backend)
make_function(closure=$0.3, defaults=None, name=$const0.5, code=<code object lineCost at 0x7fd7ada3b810, file "<ipython-input-59-ef6835d3b147>", line 3>)

File "<ipython-input-59-ef6835d3b147>", line 3:
def tester(axis,data):
    def lineCost(pars):
    ^
[1] During: lowering "$0.6 = make_function(closure=$0.3, defaults=None, name=$const0.5, code=<code object lineCost at 0x7fd7ada3b810, file "<ipython-input-59-ef6835d3b147>", line 3>)" at <ipython-input-59-ef6835d3b147> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
I would expect numba to execute the functions as it works in plain python and just uses numpy functions.

see also:
https://stackoverflow.com/questions/51287155/why-does-numba-not-work-with-this-nested-function

**Comment by stuartarchibald** [comment] 2018-07-11 16:30
Thanks for the report. This error message isn't particularly helpful/accurate and as you are not using the latest release of Numba you are not seeing the more helpful one (pasted below):
```python
numba.errors.UnsupportedError: Failed at object (ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context:
<creating a function from a closure> (op code: make_function not supported). If the
feature is explicitly supported it is likely that the result of the expression is being used
in an unsupported manner.

File "issue3095.py", line 5:
def tester(axis,data):
    def lineCost(pars):
    ^
```
Essentially, Numba can inline most closures so long as they don't escape the function, in the example you present the closure is being returned which requires support for the `make_function` op code and all the mechanics associated with it, this is currently unsupported.

**Comment by stuartarchibald** [comment] 2018-07-11 16:35
Oh apologies, this error message fix didn't make it into the last major release, I can just see it locally as I'm working off something more current. However, unfortunately, the outcome is the same.

**Comment by Myridium** [comment] 2018-07-27 03:18
@stuartarchibald I'm sorry but I don't understand your reply. The following encounters the same error. What exactly 'escapes the function'?
```
@numba.jit("i4[:]()")
def hello():
    a = [];
    def getAnswer():
        return [1,2,3];
    
    a = getAnswer();
    return a;
```

```
...
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    576     try:
--> 577         yield
    578     except NumbaError as e:

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/objmode.py in lower_inst(self, inst)
     64         if isinstance(inst, ir.Assign):
---> 65             value = self.lower_assign(inst)
     66             self.storevar(value, inst.target.name)

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/objmode.py in lower_assign(self, inst)
    158         elif isinstance(value, ir.Expr):
--> 159             return self.lower_expr(value)
    160         elif isinstance(value, ir.Global):

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/objmode.py in lower_expr(self, expr)
    372         else:
--> 373             raise NotImplementedError(expr)
    374 

NotImplementedError: make_function(name=$const0.3, closure=None, defaults=None, code=<code object getAnswer at 0x7ff191404ae0, file "<ipython-input-42-d58d0fffd78f>", line 4>)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-42-d58d0fffd78f> in <module>()
----> 1 @numba.jit("i4[:]()")
      2 def hello():
      3     a = [];
      4     def getAnswer():
      5         return [1,2,3];

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/decorators.py in wrapper(func)
    196             with typeinfer.register_dispatcher(disp):
    197                 for sig in sigs:
--> 198                     disp.compile(sig)
    199                 disp.disable_compile()
    200         return disp

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/dispatcher.py in compile(self, sig)
    651 
    652                 self._cache_misses[sig] += 1
--> 653                 cres = self._compiler.compile(args, return_type)
    654                 self.add_overload(cres)
    655                 self._cache.save_overload(sig, cres)

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    871     pipeline = pipeline_class(typingctx, targetctx, library,
    872                               args, return_type, flags, locals)
--> 873     return pipeline.compile_extra(func)
    874 
    875 

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in compile_extra(self, func)
    365         self.lifted = ()
    366         self.lifted_from = None
--> 367         return self._compile_bytecode()
    368 
    369     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in _compile_bytecode(self)
    802         """
    803         assert self.func_ir is None
--> 804         return self._compile_core()
    805 
    806     def _compile_ir(self):

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in _compile_core(self)
    789         self.define_pipelines(pm)
    790         pm.finalize()
--> 791         res = pm.run(self.status)
    792         if res is not None:
    793             # Early pipeline completion

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event(stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    650         """
    651         lowerfn = self.backend_object_mode
--> 652         self._backend(lowerfn, objectmode=True)
    653 
    654         # Warn if compiled function in object mode and force_pyobject not set

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    626             self.library.enable_object_caching()
    627 
--> 628         lowered = lowerfn()
    629         signature = typing.signature(self.return_type, *self.args)
    630         self.cr = compile_result(

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in backend_object_mode(self)
    599                                      self.library,
    600                                      self.func_ir,
--> 601                                      self.flags)
    602 
    603     def backend_nopython_mode(self):

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
   1016         )
   1017     lower = objmode.PyLower(targetctx, library, fndesc, interp)
-> 1018     lower.lower()
   1019     if not flags.no_cpython_wrapper:
   1020         lower.create_cpython_wrapper()

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215 
    216         # Close tail of entry block

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240 
    241         self.post_lower()

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 
    256     def create_cpython_wrapper(self, release_gil=False):

/usr/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    583         from numba import config
    584         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 585         six.reraise(type(newerr), newerr, tb)
    586 
    587 

/home/murdock/Dropbox/python/venvs/ct/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed at object (object mode backend)
make_function(name=$const0.3, closure=None, defaults=None, code=<code object getAnswer at 0x7ff191404ae0, file "<ipython-input-42-d58d0fffd78f>", line 4>)

File "<ipython-input-42-d58d0fffd78f>", line 4:
    a = [];
    def getAnswer():
    ^
[1] During: lowering "$0.4 = make_function(name=$const0.3, closure=None, defaults=None, code=<code object getAnswer at 0x7ff191404ae0, file "<ipython-input-42-d58d0fffd78f>", line 4>)" at <ipython-input-42-d58d0fffd78f> (4)
```

**Comment by Myridium** [comment] 2018-07-27 03:33
I should add that I have tried `numba==0.39` and `numba==0.38`. Same result with both.

**Comment by stuartarchibald** [comment] 2018-07-27 08:16
Apologies @mbramerloh I interpreted this incorrectly! We've had a lot of reports about `make_function` and I erroneously assumed this was the same issue.

Your code:
```python
import numpy as np
from numba import jit, njit

@jit
def tester(axis,data):
    def lineCost(pars):
        A=pars[0]
        B=pars[1]
        return np.sum((A*axis+B - data)**2)
    return lineCost([axis,data])

tester(1,2)
```
should work if you use a Numba 0.40.0dev build from the Numba channel (`conda install -c numba numba`). The issue was not an unsupported use of `make_function` due to returning a closure, in actual fact there is/was a bug causing this to happen (this was my mistake, relying on the traceback opposed to paying attention to the code, the closure is clearly not returned!).

Essentially, this is what happens:
 1. In your code you are doing `np.sum()` on an `int64`, Numba doesn't handle this at present, it should, because it is trivial, but it doesn't, https://github.com/numba/numba/issues/3175 is a reminder to fix it!
 2. Due to 1. the `nopython` mode compilation pipeline failed (you can read about pipeline modes [here](http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#no-python-mode-vs-object-mode)) which caused a fall back to the `object mode` pipeline.
 3. Due to 2. the `object mode` pipeline was in use and this pipeline contained a [bug](https://github.com/numba/numba/pull/3118) which was fixed a few days back in https://github.com/numba/numba/pull/3122, (clearly the released versions don't contain this fix). The bug was essentially that closure inlining was not working in object mode, which is the reason for the errors you were seeing.

Apologies for any confusion caused...

**Comment by stuartarchibald** [comment] 2018-07-27 08:39
@Myridium thanks for reraising this and drawing attention to my mistake. In the case of your code, I've augmented it as follows:

```python
import numba

def hello():
    a = [];
    def getAnswer():
        return [1,2,3];

    a = getAnswer();
    return a;

print(numba.jit()(hello)())
print(numba.jit("i4[:]()")(hello)())
```
on 0.39.0 this gives me:
```
$ python issue3095b.py 
[1, 2, 3]
Traceback (most recent call last):
<snip>
numba.errors.LoweringError: Failed at object (object mode backend)
make_function(name=$const0.3, code=<code object getAnswer at 0x7f5ef265d780, file "issue3095b.py", line 5>, closure=None, defaults=None)

File "issue3095b.py", line 5:
    a = [];
    def getAnswer():
    ^
[1] During: lowering "$0.4 = make_function(name=$const0.3, code=<code object getAnswer at 0x7f5ef265d780, file "issue3095b.py", line 5>, closure=None, defaults=None)" at issue3095b.py (5)
```

the reason for this is similar to that in https://github.com/numba/numba/issues/3095#issuecomment-408347195.

1. Calling `print(numba.jit()(hello)())` allows Numba to determine the type information and it decides it can proceed with compilation in `nopython` mode (you can read about pipeline modes [here](http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#no-python-mode-vs-object-mode)). As `nopython` mode has a closure inlining pass in 0.39 it manages to inline the closure and then call it and return the result.
 2. Calling `print(numba.jit("i4[:]()")(hello)())` forces object mode because the type signature is invalid for `nopython` mode. `i4[:]()` means that you expect to return an `array(int32, 1d, A)` type, i.e. an 4 byte int array, but your function returns a `list(int64)`. Once in the object mode pipeline the issue is the same as in https://github.com/numba/numba/issues/3095#issuecomment-408347195 step 3., that a bug in the object mode pipeline prevents closure inlining, it's been fixed in master and 0.40.0dev builds do not have this problem (`conda install -c numba numba` to try).

Apologies for any confusion caused.

**Comment by stuartarchibald** [comment] 2018-07-27 08:42
I'm going to close this issue on the basis that all the code samples work under 0.40.0dev builds and I've now hopefully understood and explained the root causes and fixes.

**Closed by stuartarchibald** 2018-07-27 08:42 UTC

**Comment by yemaedahrav** [comment] 2021-07-17 08:58
I am facing a similar issue, I'm using the latest versions of Python and Numba

**Comment by esc** [comment] 2021-07-18 07:19
@yemaedahrav thank you for adding to this issue and helping to improve Numba. Since this issue is quite old, I would suggest  for you to open a new issue or better yet, start a thread on our Discourse https://numba.discourse.group/ to get help with your issues. Thank you!

**Comment by iantofirephp** [comment] 2025-02-04 15:53
https://pythoner.space/questions/how-would-one-go-about-creating-a-function-in-python-that-is-able-to-deactivate-a-nested-function



Here’s an answer to consider
