### ISSUE TITLE
new bug in numba lib

### ISSUE THREAD

**Issue by ahmedhaies** [numba/numba#5013] opened 2020-01-02 11:45 UTC
i have this error when use numba
Traceback (most recent call last):
  File "D:/data/Prog/start_tool_from_here.py", line 66, in <module>
    main()
  File "D:/data/Prog/start_tool_from_here.py", line 58, in main
    all_ids += p.map(partial_obj, get_range())
  File "C:\Program Files\Python37\lib\site-packages\numba\dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "C:\Program Files\Python37\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Program Files\Python37\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'FORMAT_VALUE'

and this is numba function

```
from numba import njit
from numba.typed import List
@njit
def get_range():
	data = List()
	for x in range(1000000):
		data.append(f"{x}.6d")
	for x in range(100000, 5000001):
		data.append(f"{x}.7d")
	return data
```

**i know this about format and format not found but how to made format like this by numba**

**Comment by stuartarchibald** [comment] 2020-01-02 13:07
Thanks for the report. I'm afraid that this is not a bug or a new bug, it's an unimplemented feature and a duplicate of https://github.com/numba/numba/issues/3250. Essentially `f-string`'s are not supported and there's no way right now to safely do the above and get decent performance. Assuming this is some sort of set-up, perhaps create `data` outside the function and pass it in?

**Closed** 2020-01-03 05:04 UTC
Labels: duplicate, feature_request
