### ISSUE TITLE
Error in Nopython mode during for loop usage

### ISSUE THREAD

**Issue by MainzKCL** [numba/numba#3947] opened 2019-04-05 17:29 UTC
Here is the error message I am receiving:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Buffer dtype cannot be buffer

File "<ipython-input-54-64a7ad975bb8>", line 10:
def stabilitySelect(lambdaNeed,x,y,numIter,mask):
    <source elided>
    vH=0;
    for i in prange(0,numIter):
    ^

[1] During: lowering "id=27[LoopNest(index_variable = parfor_index.2067, range = ($const56.2, numIter, 1))]{154: <ir.Block at <ipython-input-54-64a7ad975bb8> (10)>}Var(parfor_index.2067, <ipython-input-54-64a7ad975bb8> (10))" at <ipython-input-54-64a7ad975bb8> (10)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

The minimum reproduction:

@njit(parallel=True)
def foo(numIter, vals ):

     for i in prange(0,numIter): #this is the line where I get the error
           print(vals[i])
foo(10,[0,1,2,3,4,5,6,7,8,9])

**Comment by luk-f-a** [comment] 2019-04-06 11:03
Hi @MainzKCL , are you using the latest Numba version? I was able to run your reproduction code in v0.43.1

```python
@njit(parallel=True)
def foo(numIter, vals ):
 for i in prange(0,numIter): #this is the line where I get the error
       print(vals[i])
foo(10,[0,1,2,3,4,5,6,7,8,9])

0
4
5
621

3

7
8
9
```

**Comment by MainzKCL** [comment] 2019-04-06 17:19
HI,

It turns out the error was due to the jupyter notebook kernel itself. I restarted the kernel today and it worked.


________________________________

**Comment by esc** [comment] 2019-04-06 17:40
I can also confirm that the reproducer works fine on current master: b5a7131d88d6960f27497c7bc199e7bbfa6eab3f

**Comment by esc** [comment] 2019-04-06 17:40
@MainzKCL thanks for getting back to us with the report. Please don't hesitate to report any issues you have in the future! I'll close this one now.

**Closed by esc** 2019-04-06 17:40 UTC

**Comment by luk-f-a** [comment] 2019-04-06 20:18
the weird thing is that using a tuple instead of a list does not work

```python
@njit(parallel=True)
def foo(numIter, vals):
    a = 0.
    for i in prange(numIter): 
        a +=vals[i]
    return a
foo(10,(0,1,2,3,4,5,6,7,8,9))
```
with error
```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scalar type tuple(int64 x 10) given for non scalar argument #2

File "<ipython-input-65-ca3529a8403f>", line 6:
def foo(numIter, vals):
    <source elided>
    a = 0
    for i in prange(numIter): 
    ^

[1] During: lowering "id=17[LoopNest(index_variable = parfor_index.1070, range = (0, numIter, 1))]{16: <ir.Block at <ipython-input-65-ca3529a8403f> (6)>}Var(parfor_index.1070, <ipython-input-65-ca3529a8403f> (6))" at <ipython-input-65-ca3529a8403f> (6)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```

**Comment by luk-f-a** [comment] 2019-04-06 21:10
@esc, what do you think of the example above? Should I open a new issue?

**Comment by esc** [comment] 2019-04-07 18:04
@luk-f-a probably a good idea, I just had a look and discovered, that this works when not using `parallel=True`.

**Comment by luk-f-a** [comment] 2019-04-07 18:12
@esc, I was going to open it but it looks like it would be a duplicate of #2625 and #2651

**Comment by esc** [comment] 2019-04-07 18:20
@luk-f-a good catch!
