### ISSUE TITLE
TypeError when running CUDA tests

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1474] opened 2015-10-12 14:42 UTC
```
$ python -c "from numba import cuda; cuda.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antoine/numba/numba/cuda/__init__.py", line 12, in test
    raise cuda_error()
TypeError: exceptions must derive from BaseException
```

**Comment by p3732** [comment] 2019-04-10 00:17
This still happens wtih Numba-0.43.1 and Python 3.7.3 (Windows 10).

**Comment by gmarkall** [comment] 2020-06-11 12:37
I can't reproduce this on Windows 10 with no CUDA driver/device or Linux with a CUDA driver + device with current master plus PR #5852 - closing as I suspect whatever was causing this has changed / gone.

**Closed by gmarkall** 2020-06-11 12:37 UTC
Labels: CUDA, bug
