### ISSUE TITLE
Test failure on LLVM15: `test_remainder_float`

### ISSUE THREAD

**Issue by sklam** [numba/numba#9660] opened 2024-07-16 22:27 UTC
```
 % pytest numba/tests/npyufunc/test_errors.py -k test_remainder_float
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.0.0
rootdir: /Users/siu/dev/numba
collected 12 items / 11 deselected / 1 selected

numba/tests/npyufunc/test_errors.py F                                                                                                                                                       [100%]

============================================================================================ FAILURES =============================================================================================
________________________________________________________________________ TestFloatingPointExceptions.test_remainder_float _________________________________________________________________________

self = <numba.tests.npyufunc.test_errors.TestFloatingPointExceptions testMethod=test_remainder_float>

    @skip_m1_fenv_errors
    def test_remainder_float(self):
>       self.check_divmod_float(remainder,
                                [0.0, float('nan'), float('nan'), 1.0],
                                ["invalid value encountered"])

numba/tests/npyufunc/test_errors.py:121:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
numba/tests/npyufunc/test_errors.py:109: in check_divmod_float
    with self.check_warnings(messages):
../envs/numba.py311/lib/python3.11/contextlib.py:144: in __exit__
    next(self.gen)
numba/tests/support.py:1067: in check_warnings
    self.assertEqual(found, len(messages))
E   AssertionError: 0 != 1
===================================================================================== short test summary info =====================================================================================
FAILED numba/tests/npyufunc/test_errors.py::TestFloatingPointExceptions::test_remainder_float - AssertionError: 0 != 1
================================================================================ 1 failed, 11 deselected in 1.21s =================================================================================

```
This one may be OSX specific as buildfarm didn't fail this one on other platforms (yet)

**Comment by sklam** [comment] 2024-07-16 22:44
The lack of warning may be due to LLVM not setting the FP error cpu flags. This test is passing on linux + x86.

**Comment by gmarkall** [comment] 2024-07-17 07:57
This passed for me on Linux - will follow up with a check on OS X.

**Comment by gmarkall** [comment] 2024-07-17 09:19
Also OK on macOS AArch64, will check on macOS x86 next.

**Comment by gmarkall** [comment] 2024-07-17 09:55
I was able to reproduce this on macOS x86:

```
(numbadevx86) bash-3.2$ python runtests.py numba.tests.npyufunc.test_errors.TestFloatingPointExceptions.test_remainder_float
F
======================================================================
FAIL: test_remainder_float (numba.tests.npyufunc.test_errors.TestFloatingPointExceptions.test_remainder_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gmarkall/work/numbadev/numba/numba/tests/npyufunc/test_errors.py", line 121, in test_remainder_float
    self.check_divmod_float(remainder,
  File "/Users/gmarkall/work/numbadev/numba/numba/tests/npyufunc/test_errors.py", line 109, in check_divmod_float
    with self.check_warnings(messages):
  File "/Users/gmarkall/mambaforge-x86_64/envs/numbadevx86/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/gmarkall/work/numbadev/numba/numba/tests/support.py", line 1067, in check_warnings
    self.assertEqual(found, len(messages))
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1 test in 0.315s

FAILED (failures=1)
```

**Comment by sklam** [comment] 2024-07-17 14:03
Yeah, I think this is a known problematic test. The skip message say `"fenv.h-like functionality unreliable on OSX arm64"`. This might have expanded to OSX x86 as well.

I checked buildfarm. The error only show up on OSX x86. Maybe we can just skip the test on OSX.

**Comment by gmarkall** [comment] 2024-07-17 16:49
It only shows up on x86 because it's skipped on AArch64 - if I unskip it on my M2 Mac the failure is the same. I'll see if I can figure out the cause, in case this is something that can / should be fixed - or if not I'd like to better understand the cause before suggesting skipping on x86 too.

**Closed** 2024-07-17 22:19 UTC
