### ISSUE TITLE
sth about List comprehensions with func

### ISSUE THREAD

**Issue by 631068264** [numba/numba#3188] opened 2018-07-31 07:31 UTC
numba==0.39.0
I use py3.6.5
```
from math import *

import numba as nb

I = 500000
a_py = range(I)


def f(x):
    return abs(cos(x)) ** 0.5 + sin(2 + 3 * x)


@nb.jit()
def f1(a):
    res = []
    for x in a:
        res.append(f(x))
    return res


@nb.jit()
def f2(a):
    return [f(x) for x in a]


print(f1(a_py))
print(f2(a_py))
```
I can get the result with `f1` but get `Error` in `f2`

```
Traceback (most recent call last):
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/objmode.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/objmode.py", line 159, in lower_assign
    return self.lower_expr(value)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/objmode.py", line 373, in lower_expr
    raise NotImplementedError(expr)
NotImplementedError: make_function(name=$const0.2, code=<code object <listcomp> at 0x10694ab70, file "/Users/wyx/project/learn-sktf/c.py", line 29>, closure=None, defaults=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wyx/project/learn-sktf/c.py", line 33, in <module>
    print(f2(a_py))
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/dispatcher.py", line 368, in _compile_for_args
    raise e
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 873, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 804, in _compile_bytecode
    return self._compile_core()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 791, in _compile_core
    res = pm.run(self.status)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 652, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 628, in _backend
    lowered = lowerfn()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 601, in backend_object_mode
    self.flags)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/compiler.py", line 1018, in py_lowering_stage
    lower.lower()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "/usr/local/var/pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/wyx/project/learn-sktf/.env/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at object (object mode backend)
make_function(name=$const0.2, code=<code object <listcomp> at 0x10694ab70, file "/Users/wyx/project/learn-sktf/c.py", line 29>, closure=None, defaults=None)

File "c.py", line 29:
def f2(a):
    return [f(x) for x in a]
    ^
[1] During: lowering "$0.3 = make_function(name=$const0.2, code=<code object <listcomp> at 0x10694ab70, file "/Users/wyx/project/learn-sktf/c.py", line 29>, closure=None, defaults=None)" at /Users/wyx/project/learn-sktf/c.py (29)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment] 2018-07-31 09:26
Thanks for the report. Think this is a duplicate of the bug(s) in #3095, an explanation for what you are seeing is approximately the same as this: https://github.com/numba/numba/issues/3095#issuecomment-408347195. Essentially, in your code the function `f` is not compiled as you have not decorated it with a Numba `@jit` decorator and `range` is not understood as an argument by `nopython` mode, as a result, when you run `f1` or `f2` they are running in `object mode`. Unfortunately there was a bug in version 0.39 that meant that list comprehensions in `object mode` would not compile, this has since been [fixed](https://github.com/numba/numba/pull/3122) and builds of Numba 0.40dev0 from the Numba channel should compile your code correctly. To try these builds do:
```
conda install -c numba numba
```

To get better performance you should really `@jit` the `def f(x):` function and swap range for e.g. `numpy.arange` so that everything runs in `nopython` mode (perhaps take a look at the [performance tips](http://numba.pydata.org/numba-doc/latest/user/performance-tips.html) for some hints)?

**Closed by stuartarchibald** 2018-07-31 09:26 UTC
