### ISSUE TITLE
Unsupported functionality was found in the code Numba was trying to compile.

### ISSUE THREAD

**Issue by smyhlin** [numba/numba#4639] opened 2019-09-30 21:11 UTC
```
def fillDB(client):
    <source elided>
        username = str(u.user.username).replace('None', '')
        try:
        ^
```
"try" not suppported?((

**Comment by esc** [comment] 2019-10-01 13:22
@smyhlin thanks for reporting this issue and yes you are correct `try` isn't supported:

http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#language

**Comment by esc** [comment] 2019-10-01 13:23
This is a duplicate of https://github.com/numba/numba/issues/4019

**Closed by esc** 2019-10-01 13:23 UTC
