### ISSUE TITLE
A context manager numba implementation

### ISSUE THREAD

**Issue by AndreiKeino** [numba/numba#8501] opened 2022-10-12 06:20 UTC
I think developing numba is a great idea. But could it's usage be implemented not just as a decorator for a function (@jit for example), but so that it could be used in a manner of a context manager? I think this feature could be quite useful. For example the pseudocode:
```
b = []

with numba_cm_jit('some parameters here: maybe to turn JIT compilation on / off, etc...'):
    for i in range(10000000):
        b[i] = i**2 + 2*i + 1
```

**Comment by gmarkall** [comment] 2022-10-12 08:04
This is a duplicate of #8011, and unfortunately is not feasible for Numba: https://github.com/numba/numba/issues/8011#issuecomment-1113298752

**Comment by AndreiKeino** [comment] 2022-10-12 08:11
Thank you for explanation

**Comment by gmarkall** [comment] 2022-10-12 08:12
No problem - sorry to have brought the bad news.

**Comment by AndreiKeino** [comment] 2022-10-12 08:40
It's a pity. But there could be some workarounds. For example could be the code in the context be replaced by the new generated python function?

**Comment by gmarkall** [comment] 2022-10-12 08:48
The problem is that we have no way to grab the code inside the context, so we can't generate a new Python function based on it.

**Comment by AndreiKeino** [comment] 2022-10-12 08:52
is this solution (for example) sounds infeasible?

https://stackoverflow.com/questions/36815410/is-there-any-way-to-get-source-code-inside-context-manager-as-string

**Comment by stuartarchibald** [comment] 2022-10-12 09:45
Numba uses Python bytecode as its input as there's no guarantee that source code is present (consider source stripped proprietary packages that might be using Numba). Whilst it's likely still possible to extract the bytecode using the frame information, I think it could be quite hard to do this accurately and that it'd also be quite hard to create a legal function based on it. Were it possible to compile a context managed region, I think it might also lead to hard to explain/implement behaviours relating to modification of variables within the extracted region and then reflection of these modifications back into the interpreter state at the context manager `__exit__` point.

**Comment by AndreiKeino** [comment] 2022-10-12 10:05
Maybe this is not a good question, but can the source be bytecoded twice: first time as usual, second time with the added generated function(s) to call in the contex executing process? Or will it be a matter of too much fuss?

**Closed** 2022-10-13 02:32 UTC
Labels: wontfix, feature_request
