### ISSUE TITLE
Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x7f85e655ddd0>> ignored

### ISSUE THREAD

**Issue by oscarcapote** [numba/numba#2818] opened 2018-03-14 10:22 UTC
I want to compute something using numpy and numba. This is my code:
```
import numpy as np
from numba import jit,double,int64

@jit(locals=dict(i=int64,j=int64,k=int64,l=int64,suma=double))
def omega_comp_arrays(omega,p_kl,eta,theta,K,L,links_by_ratings_array):
    #new_omega = np.zeros(omega.shape)
    for rating,links  in enumerate(links_by_ratings_array):
        i = links[0]
        j = links[1]
        suma = 0
        for k in range(K):
            for l in range(L):
                omega[i,j,k,l] = p_kl[k,l,rating]*theta[i,k]*eta[j,l]
                suma += omega[i,j,k,l]
        omega[i,j,:,:] /= suma
    return omega

N_nodes=2
N_veins=[1,1]
N_items=2
N_ratings=1
K=2
L=2
##Definim matrius
theta  = np.random.rand(N_nodes,K)
eta = np.random.rand(N_items,L)
p_kl = np.random.rand(K,L,N_ratings)

suma = np.sum(theta,axis =1)
theta /=suma[:,np.newaxis]
suma = np.sum(eta,axis=1)
eta /= suma[:,np.newaxis]
suma = np.sum(p_kl,axis =2)
p_kl /=suma[:,:,np.newaxis]
links_by_ratings_array = [np.array([0,0])]

omega = np.ones((N_nodes,N_items,K,L))
omega = omega_comp_arrays(omega,p_kl,eta,theta,K,L,links_by_ratings_array)
```
But I have a weird error:
`Traceback (most recent call last):
Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x7f801123d3d0>> ignored`

And if I activate the nopython mode, then it rise the following errors:
```
Traceback (most recent call last):
  File "test_omega.py", line 41, in <module>
    omega = omega_comp_arrays(omega,p_kl,eta,theta,K,L,links_by_ratings_array)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 779, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 738, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 725, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 248, in run
    raise patched_exception
numba.errors.LoweringError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 240, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 658, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 613, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 600, in backend_nopython_mode
    self.flags)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 898, in native_lowering_stage
    lower.lower()
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 265, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 435, in lower_assign
    self.incref(ty, res)
  File "/usr/local/lib/python2.7/dist-packages/numba/lowering.py", line 990, in incref
    self.context.nrt.incref(self.builder, typ, val)
  File "/usr/local/lib/python2.7/dist-packages/numba/runtime/context.py", line 202, in incref
    self._call_incref_decref(builder, typ, typ, value, "NRT_incref")
  File "/usr/local/lib/python2.7/dist-packages/numba/runtime/context.py", line 179, in _call_incref_decref
    funcname, getters + (getter,))
  File "/usr/local/lib/python2.7/dist-packages/numba/runtime/context.py", line 188, in _call_incref_decref
    raise NotImplementedError("%s: %s" % (root_type, str(e)))
LoweringError: reflected list(array(int64, 1d, C)): unsupported nested memory-managed object
File "test_omega.py", line 9
[1] During: lowering "links_by_ratings_array = arg(6, name=links_by_ratings_array)" at test_omega.py (9)

Failed at nopython (nopython mode backend)
reflected list(array(int64, 1d, C)): unsupported nested memory-managed object
File "test_omega.py", line 9
[1] During: lowering "links_by_ratings_array = arg(6, name=links_by_ratings_array)" at test_omega.py (9)
```

What am I doing bad?

**Comment by stuartarchibald** [comment] 2018-03-14 10:43
Thanks for the report. The first problem:

> Traceback (most recent call last): Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x7f801123d3d0>> ignored

is known, it was caused by the thread safety patches and happens in Python 2.7 during the destruction sequences. I don't think there's an issue for this in the tracker at present, so this can be it! 

The second error in decorating the sample code with `njit` (no-python mode) is due to lists of arrays not being supported (or indeed any memory-managed object), which is issue https://github.com/numba/numba/issues/2560.

**Comment by oscarcapote** [comment] 2018-03-15 11:49
Ok, I searched a little bit about the list of arrays and I found [https://github.com/numba/numba/issues/1239#issuecomment-113911386](this) that suggest to convert the list into a tuple. So, I created this new version:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import numpy as np
from numba import jit,double,int64
from time import time

@jit(nopython=True,locals=dict(i=int64,j=int64,k=int64,l=int64,N_links=int64,suma=double))
def omega_comp_arrays(omega,p_kl,eta,theta,K,L,N_ratings,N_links_by_ratings,links_by_ratings_array):
    #new_omega = np.zeros(omega.shape)
    for rating in range(N_ratings):
        N_links = N_links_by_ratings[rating]
        for link in range(N_links):
            i = links_by_ratings_array[rating][link][0]
            j = links_by_ratings_array[rating][link][1]
            suma = 0
            for k in range(K):
                for l in range(L):
                    omega[i,j,k,l] = p_kl[k,l,rating]*theta[i,k]*eta[j,l]
                    suma += omega[i,j,k,l]
            omega[i,j,:,:] /= suma
    return omega

N_nodes=2
N_veins=[1,1]
N_items=2
N_ratings=2
K=2
L=2
##Definim matrius
theta  = np.random.rand(N_nodes,K)
eta = np.random.rand(N_items,L)
p_kl = np.random.rand(K,L,N_ratings)

suma = np.sum(theta,axis =1)
theta /=suma[:,np.newaxis]
suma = np.sum(eta,axis=1)
eta /= suma[:,np.newaxis]
suma = np.sum(p_kl,axis =2)
p_kl /=suma[:,:,np.newaxis]
links_by_ratings_array = tuple([tuple([np.array([0,0]),np.array([0,1])]),tuple([np.array([1,0])])])
N_links_by_ratings = np.array([len(i) for i in links_by_ratings_array])
print(links_by_ratings_array)
omega = np.ones((N_nodes,N_items,K,L))
omega_comp_arrays(omega,p_kl,eta,theta,K,L,N_ratings,N_links_by_ratings,links_by_ratings_array)


```
Now links_by_ratings_array is a tuple of tuples that contains arrays of 2 components. The problem appears when I run the code:

```
Traceback (most recent call last):
  File "test_omega.py", line 48, in <module>
    omega_comp_arrays(omega,p_kl,eta,theta,K,L,N_ratings,N_links_by_ratings,links_by_ratings_array)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
numba.errors.TypingError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 240, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 454, in stage_nopython_frontend
    self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 881, in type_inference_stage
    infer.propagate()
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 846, in propagate
    raise errors[0]
TypingError: Invalid usage of getitem with parameters (((array(int64, 1d, C) x 2), (array(int64, 1d, C) x 1)), int64)
 * parameterized
File "test_omega.py", line 13
[1] During: typing of intrinsic-call at test_omega.py (13)

Failed at nopython (nopython frontend)
Invalid usage of getitem with parameters (((array(int64, 1d, C) x 2), (array(int64, 1d, C) x 1)), int64)
 * parameterized
File "test_omega.py", line 13
[1] During: typing of intrinsic-call at test_omega.py (13)

```
In other words, it fails when I try to access to the array elements.

**Comment by will133** [comment] 2018-10-09 22:18
I'm using 0.40 from conda-forge and the NoneType is not callable is pretty annoying as I get like 30 of them at the end of process run.  Do you know if it's fixed in master?  If not, is there some pointer on how to fix this?

**Closed** 2018-10-19 13:59 UTC
Labels: bug
