### ISSUE TITLE
min()/max() fails to work with lists under some conditions related to list comprehensions

### ISSUE THREAD

**Issue by alexer** [numba/numba#2657] opened 2017-12-20 02:46 UTC
```
$ cat numba_minmax.py 
from numba import jit

@jit
def test_numba(data, chunksize):
        for i in range(0, len(data), chunksize):
                chunk = data[i:i+chunksize]
                rchunk = [v.real for v in chunk]
                min(rchunk)

test_numba([1, 2], 2)

$ python numba_minmax.py 
Traceback (most recent call last):
  File "numba_minmax.py", line 10, in <module>
    test_numba([1, 2], 2)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 766, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 725, in _compile_bytecode
    return self._compile_core()
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 712, in _compile_core
    res = pm.run(self.status)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 248, in run
    raise patched_exception
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 240, in run
    stage()
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 433, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/compiler.py", line 413, in frontend_looplift
    flags=loop_flags)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/transforms.py", line 193, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/analysis.py", line 213, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/home/alexer/numba/build/lib.linux-x86_64-3.4/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed at object (object mode frontend)
```

It doesn't show in the normal traceback, but with extended tracebacks enabled (which also show the values of variables at each level), I noticed that at `compiler.py` in `run()`, there's a variable called `status` which shows as:

```
fail_reason=Failed at nopython (nopython frontend)
Invalid usage of Function(<built-in function min>) with parameters (list(int64))
 * parameterized
File "numba_minmax.py", line 8
[1] During: resolving callee type: Function(<built-in function min>)
[2] During: typing of call at numba_minmax.py (8), can_fallback=True, can_giveup=0
```

It's worth noting that this isn't just a problem with passing the result of a list comprehension to `min()`; I get the same error even if I change `min()`'s argument from `rchunk` to `chunk`, ie. the mere fact that both the list comprehension and `min()` are present is enough to trigger this, even if they aren't used together. On the other hand, commenting out either the list comprehension or the `min()` call avoids the error.

I'll also note that this is a stripped down version of the code I had (the original calculates both `min()` and `max()` for the real and imaginary parts, in a chunked fashion); I'd have stripped this down further, removing the loop altogether, but that produces a different error message, namely:

```
...
NotImplementedError: make_function(defaults=None, closure=None, name=$const0.10, code=<code object <listcomp> at 0x7fc095236390, file "numba_minmax.py", line 7>)

During handling of the above exception, another exception occurred:

...
numba.errors.LoweringError: Failed at object (object mode backend)
make_function(code=<code object <listcomp> at 0x7fb259d56390, file "numba_minmax.py", line 7>, closure=None, name=$const0.3, defaults=None)
File "numba_minmax.py", line 7
[1] During: lowering "$0.4 = make_function(code=<code object <listcomp> at 0x7fb259d56390, file "numba_minmax.py", line 7>, closure=None, name=$const0.3, defaults=None)" at numba_minmax.py (7)
```

**Comment by stuartarchibald** [comment] 2018-01-01 17:19
Thanks for the report, I can replicate. 

Debug notes:
* The function won't compile in NPM as it uses a `list(int64)` type as an arg to `min`, which is unsupported, so it falls back to object mode after failing the `nopython frontend` stage.
* The function fails under object mode in the `object mode frontend` stage with the problem noted above in the CFG.
* The error appearing from looplifting is a red herring, it also appears without looplifting enabled, the CFG evidently has issues.
* Forcing object mode to be used triggers the `make_function` error as noted above, this is because the pure object pipeline doesn't have the closure inlining pass, adding this allows the code to run as expected.
* It would appear the invalid label in the CFG that is the root cause of the exception(s) above occurs in the preserved IR as a result of running the closure inlining pass, it, therefore, must be mutating the preserved IR despite it working on the original.

After some time in a debugger I think that the issues are as follows:
 * In NPM a copy of the IR ("preserved IR") is stored ahead of any IR mutating passes, however this copy is not deep enough as the instructions in the block bodies are shared between the copy and the original. The inline closure pass correctly runs on the original, but because it mutates some instructions directly a few instruction level mutations also appear in the "preserved IR" version that is held for use in the fall back pipeline. When object mode runs as the fallback, it sees the preserved IR and uses it it preference to IR from bytecode analysis, however as the preserved IR contains a nonsensical label CFG based code fails. Changing the `Block` class to make a more deep copy that includes copied instructions prevents this problem.
 * Were the above issue fixed, the object mode pipeline needs the inline closure pass to run to handle cases such as in the given code sample. This could be via either sharing common parts of the pipeline between the two modes and then storing the mutated IR ahead of attempting NPM lowering, or simply running the inline closure pass in object mode. I also think it might be better to have a `reinstate_preserved_ir` stage opposed to switching the IR in use inside the `stage_objectmode_frontend` function, this could also allow the skipping of bytecode analysis and IR post proc and help with sharing passes?

**Comment by sklam** [comment] 2018-01-02 17:16
>  Changing the Block class to make a more deep copy that includes copied instructions prevents this problem.

I think we can start by making the IR instructions (`Inst` class and subclasses) immutable and add utils to replace instructions in a block.  Much of the numba IR infrastructure was written before we thought about adding a rewrite system.

> I also think it might be better to have a reinstate_preserved_ir stage opposed to switching the IR in use inside the stage_objectmode_frontend function, this could also allow the skipping of bytecode analysis and IR post proc and help with sharing passes?

The IR switching line `self.func_ir = self.func_ir_original or self.func_ir` is definitely ugly.

The `stage_analyze_bytecode` should already be skipped when doing a fallback.  But objectmode still needs it in the `forceobj=True` case.   Nonetheless, we need to think about refactoring the pipeline to allow more reuse and componentizing.

**Comment by stuartarchibald** [comment] 2019-03-19 11:31
As of Numba 0.43 this sample now works. Closing.

**Closed by stuartarchibald** 2019-03-19 11:31 UTC
Labels: bug
