### ISSUE TITLE
NUMBA_DISABLE_JIT disables typed.List constructor

### ISSUE THREAD

**Issue by zhihaoy** [numba/numba#6034] opened 2020-07-24 17:12 UTC
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

`NUMBA_DISABLE_JIT=0`:

```python
>>> from numba import typed
>>> typed.List([0., 0., 0.])
ListType[float64]([0.0, 0.0, 0.0])
```

`NUMBA_DISABLE_JIT=1`:

```python
>>> from numba import typed
>>> typed.List([0., 0., 0.])
[]
```

**Comment by stuartarchibald** [comment] 2020-07-24 17:34
Thanks for the report, looks like this is a bug.
```
$ NUMBA_DISABLE_JIT=0 python -c "from numba import typed; print(typed.List([1., 2., 3.]).__repr__())"
ListType[float64]([1.0, 2.0, 3.0])

$ NUMBA_DISABLE_JIT=1 python -c "from numba import typed; print(typed.List([1., 2., 3.]).__repr__())"
[]
```

**Comment by esc** [comment] 2020-07-24 18:07
@zhihaoy thanks for reporting this on the Numba issue tracker. This is duplicate of #6001 .

**Closed by esc** 2020-07-24 18:07 UTC
Labels: bug
