### ISSUE TITLE
Numba `nogil` + dask threading backend results in no speed up (computation is slower)

### ISSUE THREAD

**Issue by david-hoffman** [numba/numba#4261] opened 2019-07-02 15:46 UTC
## Reporting a bug

- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I posted this on [stackoverflow](https://stackoverflow.com/questions/56855897/numba-nogil-dask-threading-backend-results-in-no-speed-up-computation-is-sl) as well.

My install looks like:
```
2019-07-02T11:42:10-04:00

CPython 3.7.3
IPython 7.5.0

compiler   : MSC v.1915 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
CPU cores  : 48
interpreter: 64bit

dask 1.2.2
numpy 1.16.4
numba 0.44.1
```

I'm trying to use [Numba](https://numba.pydata.org/) and [Dask](https://dask.org/) to speed up a slow computation that is similar to calculating the [kernel density estimate](https://en.wikipedia.org/wiki/Kernel_density_estimation) of a huge collection of points. My plan was to write the computationally expensive logic in a `jit`ed function and then split the work among the CPU cores using `dask`. I wanted to use the `nogil` feature of `numba.jit` function so that I could use the `dask` threading backend so as to avoid unnecessary memory copies of the input data (which is very large).

Unfortunately, Dask won't result in a speed up unless I use the `'processes'` scheduler. If I use a `ThreadPoolExector` instead then I see the expected speed up.

Here's a simplified example of my problem:

    import os
    import numpy as np
    import numba
    import dask
    
    CPU_COUNT = os.cpu_count()
    
    def render_internal(size, mag):
        """mag is the magnification to apply
        generate coordinates internally
        """
        coords = np.random.rand(size, 2)
        img = np.zeros((mag, mag), dtype=np.int64)
        for i in range(len(coords)):
            y0, x0 = coords[i] * mag
            y1, x1 = int(y0), int(x0)
            m = 1
            img[y1, x1] += m
    
    jit_render_internal = numba.jit(render_internal, nogil=True, nopython=True)
    
    args = 10000000, 100
    
    print("Linear time:")
    %time linear_compute = [jit_render_internal(*args) for i in range(CPU_COUNT)]
    
    delayed_jit_render_internal = dask.delayed(jit_render_internal)
    
    print()
    print("Threads time:")
    %time dask_compute_threads = dask.compute(*[delayed_jit_render_internal(*args) for i in range(CPU_COUNT)])
    
    print()
    print("Processes time:")
    %time dask_compute_processes = dask.compute(*[delayed_jit_render_internal(*args) for i in range(CPU_COUNT)], scheduler="processes")

And here's the output on my machine:

    Linear time:
    Wall time: 1min 17s
    
    Threads time:
    Wall time: 1min 47s
    
    Processes time:
    Wall time: 7.79 s

For both the processing and threading backends I see complete utilization of all CPU cores, as expected. But no speed up for the threading backend. I'm pretty sure that the jitted function, `jit_render_internal`, is not, in fact, releasing the GIL.

My two questions are:

1. If the `nogil` keyword is passed to `numba.jit` and the GIL cannot be released, why isn't an error raised?
2. Why doesn't the code, as I've written it, release the GIL? All the computation is embedded in the function and there's no return value.

**Comment by synapticarbors** [comment] 2019-07-02 16:09
I can reproduce this on MacOS using Dask 2.0. It's not a Dask issue, because if I use a `concurrent.futures.ThreadPoolWorker`, I see similar timings:

```
with ThreadPoolExecutor(max_workers=CPU_COUNT) as exc:
    fut = {exc.submit(jit_render_internal, *args): i for i in range(CPU_COUNT)}
    
    for f in as_completed(fut):
        print(f.result())
```

It looks like it's releasing the GIL though, because my CPU usage for the python process goes to 500+% on an 8-core laptop when running with threads. I'm not sure what the source of the discrepancy is between the processes and thread-based parallelization is at this point.

**Comment by synapticarbors** [comment] 2019-07-02 16:18
Actually, try the following, which is much faster and seems to fix the issue for me:

```
def render_internal(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        #y0, x0 = coords[i] * mag
        y0 = coords[i,0] * mag
        x0 = coords[i,1] * mag
        y1, x1 = int(y0), int(x0)
        m = 1
        img[y1, x1] += m
```

**Comment by david-hoffman** [comment] 2019-07-02 17:01
I ran on my machine and only got a speed up of a factor of 2 while processes was much faster:
```
Linear time:
Wall time: 2min 52s

Threads time:
Wall time: 1min 3s

Processes time:
Wall time: 16.5 s
```

Not sure where the factor of two speed up is coming from. I can see that a lot of the CPU time is taken up by the kernel which suggests a bunch of context switching, i.e. the GIL is not being released.

**Comment by david-hoffman** [comment] 2019-07-02 17:04
It seems to have something to do with item access in `coords`, if I use this code:
```python
def render_internal(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
#     coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(size):
        y0 = np.random.rand() * mag
        x0 = np.random.rand() * mag
        y1 = int(y0)
        x1 = int(x0)
        m = 1
        img[y1, x1] += m
```

I get the expected speed up.

**Comment by synapticarbors** [comment] 2019-07-02 17:10
With my code, I get:

```
Linear time:
CPU times: user 1.49 s, sys: 383 ms, total: 1.88 s
Wall time: 1.88 s

Threads time:
CPU times: user 2.73 s, sys: 815 ms, total: 3.54 s
Wall time: 471 ms

Processes time:
CPU times: user 17.9 ms, sys: 23.9 ms, total: 41.8 ms
Wall time: 718 ms
```

with your original code, I get:

```
Linear time:
CPU times: user 12.8 s, sys: 397 ms, total: 13.2 s
Wall time: 13.2 s

Threads time:
CPU times: user 1min 27s, sys: 755 ms, total: 1min 28s
Wall time: 11.4 s

Processes time:
CPU times: user 21.2 ms, sys: 26.7 ms, total: 47.8 ms
Wall time: 3.74 s
```

So for whatever reason, on my system, I'm seeing a huge performance difference.

**Comment by synapticarbors** [comment] 2019-07-02 17:18
And the `watermark` for my system:

```
CPython 3.7.3
IPython 7.5.0

numpy 1.16.4
numba 0.44.1
dask 2.0.0

compiler   : Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 18.6.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
```

**Comment by stuartarchibald** [comment] 2019-07-02 18:18
I'll try and take a look at this tomorrow. When Numba makes a RNG call for the first time it has to initialize a random state _per thread_ so each thread will call `os.urandom` from the interpreter do this, the GIL is reacquired in the process.

**Comment by stuartarchibald** [comment] 2019-07-03 11:46
I think I've got to the bottom of this... tl;dr the root cause seems to be too much pressure on the atomic reference counter for allocations managed by the Numba runtime cause by array temporaries in a tight loop. See also: https://github.com/numba/numba/issues/2699

How this was discovered:

1. Check it is definitely not the GIL. Use Numba's `gdb()` support, break on `PyGILState_Ensure`, run the function and see from where the calls arise.
```python
def render_internal(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    gdb()
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        y0, x0 = coords[i] * mag
        y1, x1 = int(y0), int(x0)
        img[y1, x1] += 1
```
running this
```
$ ipython issue4261.py

<snip>
[New LWP 22127]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

0x00007f0ab2d8ce2d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
81      T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
Breakpoint 1 at 0x7f0a9529e1e0: file numba/_helperlib.c, line 1133.
Continuing.

Thread 1 "ipython" hit Breakpoint 1, numba_gdb_breakpoint () at numba/_helperlib.c:1133
1133    numba_gdb_breakpoint(void) {
(gdb) break PyGILState_Ensure
Breakpoint 2 at 0x5568e2005f93: PyGILState_Ensure. (2 locations)
(gdb) c
Continuing.

Thread 1 "ipython" hit Breakpoint 2, PyGILState_Ensure ()
    at /tmp/build/80754af9/python_1553721932202/work/Python/pystate.c:1036
1036    /tmp/build/80754af9/python_1553721932202/work/Python/pystate.c: No such file or directory.
(gdb) f 1
#1  0x00007f0a9529f412 in rnd_implicit_init (state=0x5568e4bfa8d0) at numba/_random.c:190
190         PyGILState_STATE gilstate = PyGILState_Ensure();
(gdb) c
Continuing.
[Thread 0x7f0aa96b8700 (LWP 22127) exited]
[Inferior 1 (process 22124) exited normally]
(gdb)
```
as noted above, there's one GIL acquisition in the Numba RNG start up sequence in the C function `rnd_implicit_init`.


2. Look at the IR, reduce the code and work out why they aren't equivalent...

Using this harness:

```python
import os
import numpy as np
import numba
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor, as_completed
from IPython import get_ipython
from numba import gdb, gdb_init
ipython = get_ipython()

CPU_COUNT = os.cpu_count()

# ------------------------------------------------------------------------------
def render_internal_good(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        y0 = coords[i, 0] * mag
        x0 = coords[i, 1] * mag
        y1, x1 = int(y0), int(x0)
        img[y1, x1] += 1

def render_internal_bad(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        y0, x0 = coords[i] * mag
        y1, x1 = int(y0), int(x0)
        img[y1, x1] += 1

jit_render_internal_good = numba.jit(render_internal_good, nogil=True, nopython=True)
jit_render_internal_bad= numba.jit(render_internal_bad, nogil=True, nopython=True)

args = 1000000, 100
jit_render_internal_good(*args)
jit_render_internal_bad(*args)

jit_render_internal_good.inspect_types()
jit_render_internal_bad.inspect_types()


def PE(pool, func):
    with pool(max_workers=CPU_COUNT) as exc:
        fut = {exc.submit(func, *args): i for i in range(CPU_COUNT)}
        for f in as_completed(fut):
            f.result()

print("TPE bad : %s" % ipython.magic("timeit -o -q PE(ThreadPoolExecutor, jit_render_internal_bad)").best)
print("PPE bad : %s" % ipython.magic("timeit -o -q PE(ProcessPoolExecutor, jit_render_internal_bad)").best)
print("TPE good: %s" % ipython.magic("timeit -o -q PE(ThreadPoolExecutor, jit_render_internal_good)").best)
print("PPE good: %s" % ipython.magic("timeit -o -q PE(ProcessPoolExecutor, jit_render_internal_good)").best)
```
Initial run gave:
```
TPE bad : 1.810245512000165
PPE bad : 0.33432760300001974
TPE good: 0.036630975600019156
PPE good: 0.09105606599996463
```
removing the multiplication by `mag` in both functions evens things out a lot:
```
TPE bad : 0.09822850939999625
PPE bad : 0.14623121400018135
TPE good: 0.03803423310000653
PPE good: 0.08929413599980762
```
this hints at array temporaries being a problem (result of the `*` call on an array slice in "bad").

Rewriting the `good` function to have a pointless allocation in the loop leads
to these functions being about equivalent under processes vs. threads:
```python
def render_internal_good(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        DEAD = np.zeros(2) # <---------------------- POINTLESS ALLOCATION
        y0 = coords[i, 0] * mag
        x0 = coords[i, 1] * mag
        y1, x1 = int(y0), int(x0)
        img[y1, x1] += 1

def render_internal_bad(size, mag):
    """mag is the magnification to apply
    generate coordinates internally
    """
    coords = np.random.rand(size, 2)
    img = np.zeros((mag, mag), dtype=np.int64)
    for i in range(len(coords)):
        y0, x0 = coords[i] * mag
        y1, x1 = int(y0), int(x0)
        img[y1, x1] += 1
```
this gave:
```
TPE bad : 1.5873844870002358
PPE bad : 0.3514107969995166
TPE good: 1.721531098000014
PPE good: 0.28835104500012676
```


Finally, if Numba is rebuilt with reference counting disabled (don't do this!) then the result, using the original functions, is:
```
TPE bad : 0.2580618209995009
PPE bad : 0.30537596700014547
TPE good: 0.03892764359998182
PPE good: 0.09222646599937434
```
the "bad" function is still slower, but probably because it's making a load of `malloc` calls, but as these are now not going through an atomic counter in a tight loop the thread pool execution is not being rate limited hence threads faster than processes. Obviously the "good" function still runs quicker than the bad one most likely due to it not performing allocations in the tight loop.

Hope this helps.

**Comment by david-hoffman** [comment] 2019-07-07 23:52
Here's a follow up question, even with this fix, the following code results in little or no speed up (I would think releasing the GIL and using a `ThreadPoolExecutor` would result in a big boost).

```python
import os
import time
import numpy as np
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor, as_completed
from numba import njit, jit

CPU_COUNT = os.cpu_count()
print("CPU_COUNT", CPU_COUNT)

def PE(pool, func, args):
    with pool(max_workers=CPU_COUNT) as exc:
        fut = {exc.submit(func, *arg): i for i, arg in enumerate(args)}
        for f in as_completed(fut):
            f.result()

def render(params, mag):
    """Render gaussian peaks in small windows"""
    
    radius = 3
    
    for i in range(len(params)):
        y0 = params[i, 0] * mag
        x0 = params[i, 1] * mag
        sy = params[i, 2] * mag
        sx = params[i, 3] * mag
        
        # calculate the render window size
        wy = int(sy * radius * 2.0)
        wx = int(sx * radius * 2.0)
        
        # calculate the area in the image
        ystart = int(np.rint(y0)) - wy // 2
        yend = ystart + wy
        xstart = int(np.rint(x0)) - wx // 2
        xend = xstart + wx
        
        # adjust coordinates to window coordinates
        y1 = y0 - ystart
        x1 = x0 - xstart
        
        y = np.arange(wy)
        x = np.arange(wx)
        amp = 1 / (2 * np.pi * sy * sx)
        gy = np.exp(-((y - y0) / sy) ** 2 / 2)
        gx = np.exp(-((x - x0) / sx) ** 2 / 2)
        g = amp * np.outer(gy, gx)

jit_render = jit(render, nopython=True, nogil=True)

args = [(np.random.rand(1000000, 4) * (1, 1, 0.02, 0.02), 100) for i in range(CPU_COUNT)]

print("Single time:")
# %timeit render(*args[0])
%timeit jit_render(*args[0])

print()
print("Linear time:")
%time [jit_render(*a) for a in args]

print()
print("Threads time:")
%time PE(ThreadPoolExecutor, jit_render, args)
```

On my 8 core MacBook I get a speed up of about 2X

    Single time:
    1.6 s ± 153 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    
    Linear time:
    CPU times: user 11.8 s, sys: 43.1 ms, total: 11.9 s
    Wall time: 11.9 s
    
    Threads time:
    CPU times: user 45.4 s, sys: 125 ms, total: 45.5 s
    Wall time: 6.29 s

On my 24 core Windows box I get a speed up of about 1X:

    Single time:
    1.91 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    
    Linear time:
    Wall time: 1min 30s
    
    Threads time:
    Wall time: 1min 4s

**Comment by stuartarchibald** [comment] 2019-07-09 09:09
@sklam and I had a very long discussion about this issue (and related problems in ParallelAccelerator (`numba.njit(parallel=True)`)). The discussion went along the lines of...

* Can we put the allocators in TLS, so that in a threaded context each thread gets its own refcount/allocator pair. This would potentially work but is a giant piece of complexity in that all the semantics of initialization and destruction sequences would need orchestrating to form up "global" views of the refcounts each time a threaded region is entered and exited. This also becomes increasingly hard if there's nested threaded parallelism or something happening with threads that is poorly defined so cannot easily be analysed.
* Can we do various forms of static analysis to help, e.g. escape analysis, this to try and compute regions of "safety" where the refcounting can be removed. Outcome of this was that it'd be very hard to do because of aliasing etc (xref: https://github.com/numba/numba/pull/3908) and would potentially lead to hard to handle/debug leaking of allocations.
* Can we make use of parallel accelerator's sequential lowering passes to do things like shortcut deforestation, LICM of allocations etc to make it such that there are simply fewer hits on the atomic ref count. Outcome of this was yes, it helps, but there are a lot of cases where it won't.
* Are we looking at this from the wrong level, and in actual fact is refcount pruning best done at the LLVM IR level written as a LLVM compiler pass? We decided that this was the best route to take, albeit harder, but is more likely to work and could also work across basic blocks. Some ground work for custom passes was done here https://github.com/numba/llvmlite/pull/429, but given the importance to Numba of such a pass, just writing it and baking it in would probably be the best option.

**Comment by stuartarchibald** [comment] 2019-09-11 14:52
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:52 UTC
Labels: no action required
