### ISSUE TITLE
numba.jit fails on sympy.lambdify functions

### ISSUE THREAD

**Issue by asmeurer** [numba/numba#2328] opened 2017-03-30 22:14 UTC
In the SymPy master, something has broken the ability to do `numba.jit` on a lambdified function.

```py
>>> import numba
>>> from sympy import *
>>> f = lambdify(x, sin(x), 'numpy')
>>> f(1)
0.8414709848078965
>>> numba.jit(f)(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dispatcher.py", line 287, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dispatcher.py", line 555, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dispatcher.py", line 81, in compile
    flags=flags, locals=self.locals)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 699, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 660, in _compile_bytecode
    return self._compile_core()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 647, in _compile_core
    res = pm.run(self.status)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 238, in run
    raise patched_exception
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 230, in run
    stage()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 366, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/compiler.py", line 762, in translate_stage
    return interp.interpret(bytecode)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/interpreter.py", line 97, in interpret
    self.dfa.run()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dataflow.py", line 27, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dataflow.py", line 71, in run_on_block
    self.dispatch(info, inst)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/numba/dataflow.py", line 80, in dispatch
    fn = getattr(self, fname)
AttributeError: Failed at object (analyzing bytecode)
'DataFlowAnalysis' object has no attribute 'op_LOAD_CLOSURE'
```

Note that you need to run this from [this pull request](https://github.com/sympy/sympy/pull/12462) because of another issue (we weren't using `functools.wraps`). 

I bisected the change in SymPy, and I think it is due to that wrapper function that we are using. 

If this is not easy to fix in Numba if you could suggest a workaround that we could use in SymPy, that would be great.

**Comment by asmeurer** [comment] 2017-03-30 22:28
It also has issues with our use of dummy symbol names (the `dummify` option to lambdify). Somehow the original symbol names slip through. This could be a SymPy issue, although as far as I know everything behaves just fine from lambdified functions that aren't passed through numba.jit.

**Comment by stuartarchibald** [comment] 2017-03-31 08:54
Thanks for the report. I've built sympy from the [PR](https://github.com/sympy/sympy/pull/12462) and used latest Numba dev build, I can't replicate from exactly your code but I can from something similar, this is down to not supporting the `LOAD_CLOSURE` bytecode instruction. `dis` is:
```
(Pdb) dis.dis(f)
440           0 LOAD_DEREF               0 (funcarg)
              2 LOAD_CLOSURE             1 (namespace)
              4 BUILD_TUPLE              1
              6 LOAD_CONST               1 (<code object <listcomp> at 0x7f9ec7322390, file "<path>/sympy-1.0.1.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 440>)
              8 LOAD_CONST               2 ('lambdify.<locals>.array_wrap.<locals>.wrapper.<locals>.<listcomp>')
             10 MAKE_FUNCTION            8
             12 LOAD_FAST                0 (argsx)
             14 GET_ITER
             16 CALL_FUNCTION            1
             18 LOAD_FAST                1 (kwargsx)
             20 CALL_FUNCTION_EX         1
             22 RETURN_VALUE
```
Even if  `LOAD_CLOSURE` was supported both `MAKE_FUNCTION` and `CALL_FUNCTION_EX` with `kwargs` would both need to be supported to make what is present work (and I'm fairly sure `MAKE_FUNCTION` isn't supported and `CALL_FUNCTION_EX` only with `args` not `kwargs`). Perhaps @sklam may know a workaround/have a suggestion?

**Comment by asmeurer** [comment] 2017-03-31 15:43
I think our use of **kwargs is mostly unnecessary. It only affects the case where people call the parameters of the wrapped function by name (which, given the [current defaults](https://github.com/sympy/sympy/issues/12463), is unlikely to work in most cases anyway).

**Comment by asmeurer** [comment] 2017-04-13 18:17
Any updates on this? The ability to numba.jit lambdified functions is an important use-case for SymPy, and it's a shame to see it stop working.

**Comment by stuartarchibald** [comment] 2017-05-22 15:59
https://github.com/numba/numba/pull/2369 helps with the closure issue but `MAKE_FUNCTION` et al are still going to be needed.

**Comment by ninegua** [comment] 2017-05-22 21:31
With #2369, the example runs through just fine :-)

```
>>> import numba
>>> from sympy import *
>>> f = lambdify(x, sin(x), 'numpy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
>>> from sympy.abc import x
>>> f = lambdify(x, sin(x), 'numpy')
>>> f(1)
0.8414709848078965
>>> numba.jit(f)(1)
0.8414709848078965
```

**Comment by asmeurer** [comment] 2017-05-22 22:59
Great. This is with SymPy master? 

Any idea how long that will take to get to a numba release?

**Comment by seibert** [comment] 2017-05-23 12:31
Our goal is to review #2369 for merger in this release cycle.  Release candidate will be out at the end of June, and final release in time for SciPy.

**Comment by stuartarchibald** [comment] 2017-05-24 15:57
@ninegua you are completely right, it works fine :-), error on my part, just tested against SymPy master. Thanks.

**Comment by dhirschfeld** [comment] 2017-09-05 00:56
Is this supposed to work now? With sympy `1.1.1` and numba `'0.35.0rc1+15.g24edca2` I'm getting a `CALL_FUNCTION_EX` error when trying to jit a lambdafied function:
```python
from numba import jit
import sympy as sym

y = sym.exp(-x)
tanh = (1.0 - y) / (1.0 + y)
ddx_tanh = tanh.diff(x)
f = sym.lambdify(x, ddx_tanh, 'numpy')
g = jit(f)
```
```python
In [12]: f(1.0)
Out[12]: 0.3932238664829637
In [13]: g(1.0)

In [14]: Traceback (most recent call last):

  File "<ipython-input-13-7c2977bc7ed3>", line 1, in <module>
    g(1.0)

  File "C:\Miniconda3\lib\site-packages\numba\dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))

  File "C:\Miniconda3\lib\site-packages\numba\dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)

  File "C:\Miniconda3\lib\site-packages\numba\dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 360, in compile_extra
    return self._compile_bytecode()

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 722, in _compile_bytecode
    return self._compile_core()

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 709, in _compile_core
    res = pm.run(self.status)

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 246, in run
    raise patched_exception

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 238, in run
    stage()

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 374, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)

  File "C:\Miniconda3\lib\site-packages\numba\compiler.py", line 827, in translate_stage
    return interp.interpret(bytecode)

  File "C:\Miniconda3\lib\site-packages\numba\interpreter.py", line 98, in interpret
    self.dfa.run()

  File "C:\Miniconda3\lib\site-packages\numba\dataflow.py", line 28, in run
    self.infos[blk.offset] = self.run_on_block(blk)

  File "C:\Miniconda3\lib\site-packages\numba\dataflow.py", line 78, in run_on_block
    self.dispatch(info, inst)

  File "C:\Miniconda3\lib\site-packages\numba\dataflow.py", line 88, in dispatch
    fn(info, inst)

  File "C:\Miniconda3\lib\site-packages\numba\dataflow.py", line 354, in op_CALL_FUNCTION_EX
    raise NotImplementedError(errmsg)

NotImplementedError: Failed at object (analyzing bytecode)
CALL_FUNCTION_EX with **kwargs not supported
```

**Comment by stuartarchibald** [comment] 2017-09-05 12:03
Puzzling. I can reproduce what you see. It did work because I recall testing it! Looks like it has either been broken by Numba, or Sympy has moved something such that it is now broken again.

**Comment by dhirschfeld** [comment] 2017-09-09 01:08
Looks like it works in sympy 1.0 but 1.1 changed something and it unfortunately broke this functionality.

Are there any plans to support `CALL_FUNCTION_EX` with `**kwargs`? I can't see an issue specifically about it...

**Comment by asmeurer** [comment] 2017-09-09 02:19
I tried removing the `**kwargsx` (we don't actually need it), but then I get another error

```pytb
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 69, in get
    return self._con[name]
KeyError: 'argsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 670, in get_exact
    return self.localvars.get(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 71, in get
    raise NotDefinedError(name)
numba.errors.NotDefinedError: 'argsx' is not defined in None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 69, in get
    return self._con[name]
KeyError: 'argsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<mypython-2>", line 2, in <module>
    numba.jit(lambdify(x, sin(x), 'numpy'))(1)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 740, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 699, in _compile_bytecode
    return self._compile_core()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 686, in _compile_core
    res = pm.run(self.status)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 374, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 803, in translate_stage
    return interp.interpret(bytecode)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/interpreter.py", line 110, in interpret
    self._dispatch(inst, kws)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/interpreter.py", line 239, in _dispatch
    raise e
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/interpreter.py", line 235, in _dispatch
    return fn(inst, **kws)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/interpreter.py", line 540, in op_LOAD_FAST
    self.store(value=self.get(srcname), name=res)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/interpreter.py", line 273, in get
    var = self.current_scope.get(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 662, in get
    return self.get_exact(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 673, in get_exact
    return self.parent.get(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 662, in get
    return self.get_exact(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 670, in get_exact
    return self.localvars.get(name)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/numba/ir.py", line 71, in get
    raise NotDefinedError(name)
numba.errors.NotDefinedError: 'argsx' is not defined in ./sympy/utilities/lambdify.py (434)
```

That's from `numba.jit(lambdify(x, sin(x), 'numpy'))(1)`. `lambdify(x, sin(x), 'numpy')(1)` works just fine. 

This is the SymPy patch

```diff
diff --git a/sympy/utilities/lambdify.py b/sympy/utilities/lambdify.py
index 5056cc60c2..94aac3188f 100644
--- a/sympy/utilities/lambdify.py
+++ b/sympy/utilities/lambdify.py
@@ -428,11 +428,11 @@ def lambdify(args, expr, modules=None, printer=None, use_imps=True,
     if module_provided and _module_present('numpy',namespaces):
         def array_wrap(funcarg):
             @wraps(funcarg)
-            def wrapper(*argsx, **kwargsx):
+            def wrapper(*argsx):
                 asarray = namespace['asarray']
                 newargs = [asarray(i) if isinstance(i, integer_types + (float,
                     complex)) else i for i in argsx]
-                return funcarg(*newargs, **kwargsx)
+                return funcarg(*newargs)
             return wrapper
         func = array_wrap(func)
     # Apply the docstring
```

**Comment by thomasantony** [comment] 2017-09-30 06:49
I don't know if this needs to be a separate issue. `numba` also has troubles if the sympy function operates on matrices or returns matrices. `lambdify` converts the matrices into numpy arrays implicitly.

This is the case with the above patch applied.

Example:
```
import sympy, numba, numpy
X = sympy.Matrix(sympy.symbols('x:3')).T
Y = sympy.Matrix(sympy.symbols('y:3')).T
f = sympy.lambdify((*X, *Y), X+Y)
f(1,2,3,4,5,6) # returns [[5, 7, 9]]
f1 = numba.njit(f)
f1(1,2,3,4,5,6) # breaks
```
With `njit` I get this error:
```
Traceback (most recent call last):
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 186, in _call_incref_decref
    meminfo = data_model.get_nrt_meminfo(builder, value)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/datamodel/models.py", line 329, in get_nrt_meminfo
    "unsupported nested memory-managed object")
NotImplementedError: unsupported nested memory-managed object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 266, in lower_inst
    self.storevar(val, inst.target.name)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 934, in storevar
    self.decref(fetype, old)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 988, in decref
    self.context.nrt.decref(self.builder, typ, val)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 208, in decref
    self._call_incref_decref(builder, typ, typ, value, "NRT_decref")
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 179, in _call_incref_decref
    funcname, getters + (getter,))
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 188, in _call_incref_decref
    raise NotImplementedError("%s: %s" % (root_type, str(e)))
NotImplementedError: list(list(int64)): unsupported nested memory-managed object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 644, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 599, in _backend
    lowered = lowerfn()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 586, in backend_nopython_mode
    self.flags)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/compiler.py", line 882, in native_lowering_stage
    lower.lower()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/Users/tantony/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 266, in lower_inst
    self.storevar(val, inst.target.name)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 934, in storevar
    self.decref(fetype, old)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/lowering.py", line 988, in decref
    self.context.nrt.decref(self.builder, typ, val)
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 208, in decref
    self._call_incref_decref(builder, typ, typ, value, "NRT_decref")
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 179, in _call_incref_decref
    funcname, getters + (getter,))
  File "/Users/tantony/anaconda/lib/python3.6/site-packages/numba/runtime/context.py", line 188, in _call_incref_decref
    raise NotImplementedError("%s: %s" % (root_type, str(e)))
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
list(list(int64)): unsupported nested memory-managed object
File "<string>", line 1
[1] During: lowering "$0.12 = build_list(items=[Var($0.11, <string> (1))])" at <string> (1)
```
if I use `numba.jit` instead, I get this error:
`NameError: global name 'array' is not defined`

**Comment by stuartarchibald** [comment] 2017-10-02 13:53
@thomasantony Thanks for the report, this is a different issue I think. Nested lists are not supported in Numba `@jit` with `nopython=True` which is the cause of the first error message. I'm unsure why plain `@jit` is not finding the `array` global though.

**Comment by thomasantony** [comment] 2017-10-02 14:21
@stuartarchibald So is there any way right now to "njit" a sympy expression that generates a vector?

**Comment by dhirschfeld** [comment] 2017-10-02 20:04
I'm curious if there are any plans, distant or otherwise, to support kwargs in `CALL_FUNCTION_EX`?

**Comment by asmeurer** [comment] 2017-10-02 20:12
As I mentioned above we can remove the **kwargs from sympy.lambdify (we don't actually use it), but then there are other errors.

**Comment by dhirschfeld** [comment] 2019-03-19 12:25
It looks like this works now:
```python
In [14]: >>> import numba
    ...: >>> from sympy import *
    ...: >>> f = lambdify(x, sin(x), 'numpy')
    ...: >>> print(f(1))
    ...: >>> print(numba.jit(f)(1))
0.8414709848078965
0.8414709848078965

In [15]: sympy.__version__
Out[15]: '1.3'

In [16]: numba.__version__
Out[16]: '0.43.0'
```

**Comment by Juanlu001** [comment] 2019-03-19 12:51
Is it worth it to add some regression test?

**Comment by stuartarchibald** [comment] 2019-03-19 12:57
I think some regression tests upstream would be beneficial, especially as it's unclear what it is that broke/fixed/rebroke/refixed it.

**Comment by asmeurer** [comment] 2019-03-19 17:44
We refactored how lambdify works. It now produces a function instead of a lambda, and it no longer wraps it in a decorator. I still get the `CALL_FUNCTION_EX with **kwargs not supported` error with sympy 1.1.1, because the decorator used the standard `*args, **kwargs` pass through semantics (https://github.com/sympy/sympy/blob/sympy-1.1.1/sympy/utilities/lambdify.py#L440).

**Comment by stuartarchibald** [comment] 2020-09-10 19:13
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-10 19:13 UTC
Labels: needtriage

**Comment by asmeurer** [comment] 2020-09-10 19:56
I tried the examples here and they all work in SymPy master. I think either SymPy removed the things numba doesn't support of numba supports them now. Maybe you can add a basic test to your integration test suite? We don't have any numba tests in the SymPy test suite.

**Comment by stuartarchibald** [comment] 2020-09-10 20:15
Thanks for checking @asmeurer. The [Numba integration tests](https://github.com/numba/numba-integration-testing) check that packages consuming Numba are not broken by updates to Numba. I presume SymPy doesn't actually consume Numba and the interest here is in whether functions generated by SymPy can be jitted?

**Comment by asmeurer** [comment] 2020-09-10 22:03
Yes. If it makes sense, we can add a test to our test suite. Presumably if we do that you can add it to your integration tests and avoid breaking it from your side.

**Comment by asmeurer** [comment] 2020-09-10 22:05
https://github.com/sympy/sympy/issues/20070

**Comment by stuartarchibald** [comment] 2020-09-11 16:34
> Yes. If it makes sense, we can add a test to our test suite. Presumably if we do that you can add it to your integration tests and avoid breaking it from your side.

Thanks. It seems like a good idea for it to go into the integration testing once done, perhaps restrict the testing to just the tests that use Numba though so as to save compute time. [PRs are welcomed](https://github.com/numba/numba-integration-testing/pulls), for inspiration, a [number of other package authors](https://github.com/numba/numba-integration-testing/pulls?q=is%3Apr+is%3Aclosed) have added their own package to the integration testing. Thanks again!
