### ISSUE TITLE
numpy.std function not returning the correct results

### ISSUE THREAD

**Issue by GeorgePapanik** [numba/numba#9180] opened 2023-09-05 15:04 UTC
In my process to create a function that calculates the correlation between two time-series I come across this error. The following code demonstrates the result that I have.

I am using windows 10 with python 3.8.8 and numba 0.56.4

```
import numpy as np
from numba import jit

@jit
def error_test(a,b):
    
    sdb = np.std(b)
    sda = np.std(a)

    
    return sda,sdb

error_test(np.array([0.2,0.1]),np.array([0.3,0.2]))
```

The sda and sdb are supposed to be equal to 0.05 but the output I get is

`
(0.05, 0.0)
`

I was originally using @jit(no_python = True) but the result was the same. Also, if I remove '@jit`, the result is correct:

`
(0.05, 0.04999999999999999)
`

EDIT: Upgrading to python 3.11.4 using anaconda installer has resolved the issue for now.

**Comment by guilhermeleobas** [comment] 2023-09-06 13:28
Hi @GeorgePapanik, I cannot reproduce this error locally.

```python
$ cat repro.py
import numpy as np
from numba import njit

@njit
def error_test(a,b):
    sdb = np.std(b)
    sda = np.std(a)
    return sda, sdb

a = np.array([0.2, 0.1])
b = np.array([0.3, 0.2])
print(error_test(a, b))
print(error_test.py_func(a, b))


$ python d.py
(0.05, 0.04999999999999999)
(0.05, 0.04999999999999999)
```

> EDIT: Upgrading to python 3.11.4 using anaconda installer has resolved the issue for now.

Glad to hear that. I'll close this issue for now. Feel free to post an update if this issue happens again.

**Closed by guilhermeleobas** 2023-09-06 13:28 UTC
