### ISSUE TITLE
Casting to an array type fails with obscure error

### ISSUE THREAD

**Issue by pitrou** [numba/numba#496] opened 2014-06-16 20:13 UTC
```
>>> @jit
... def cast_object(dst_type, value):
...     return dst_type(value)
...
>>> cast_object(numba.double, 1)
1.0
>>> cast_object(numba.double[:], np.arange(10, dtype=np.double))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\dispatcher.py", line 126, in _compile_and_call
    return self(*args, **kws)
  File "numba\types.py", line 47, in __call__
    return self.cast_python_value(args[0])
TypeError: 'NotImplementedType' object is not callable
```

**Comment by MrMormon** [comment] 2016-02-01 18:38
Does this still happen?

**Comment by seibert** [comment] 2017-11-03 16:15
Confirmed this still happens with Numba 0.35.0.

**Comment by sklam** [comment] 2019-12-30 16:29
As of numba 0.48.0dev0, the nopython mode error indicates a TypingError because using the numba type ``numba.double[:]` as a cast function is unsupported. In objectmode, it raises a `NotImplementedError`. The error is no longer obscure.

Closing.

**Closed by sklam** 2019-12-30 16:29 UTC
Labels: needtriage
