### ISSUE TITLE
LLVM verify error: Terminator found in the middle of a basic block

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3876] opened 2019-03-18 02:39 UTC
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I see the error below in a large piece of code that's hard to reproduce. I'm using the master of Numba and dev version of llvmlite. Any ideas where to look for issues?

```
  File "/Users/etotoni/pse-hpc/python/numba/numba/compiler.py", line 731, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/etotoni/pse-hpc/python/numba/numba/compiler.py", line 681, in _backend
    lowered = lowerfn()
  File "/Users/etotoni/pse-hpc/python/numba/numba/compiler.py", line 668, in backend_nopython_mode
    self.metadata)
  File "/Users/etotoni/pse-hpc/python/numba/numba/compiler.py", line 1074, in native_lowering_stage
    cfunc = targetctx.get_executable(library, fndesc, env)
  File "/Users/etotoni/pse-hpc/python/numba/numba/targets/cpu.py", line 166, in get_executable
    baseptr = library.get_pointer_to_function(fndesc.llvm_func_name)
  File "/Users/etotoni/pse-hpc/python/numba/numba/targets/codegen.py", line 469, in get_pointer_to_function
    self._ensure_finalized()
  File "/Users/etotoni/pse-hpc/python/numba/numba/targets/codegen.py", line 104, in _ensure_finalized
    self.finalize()
  File "/Users/etotoni/pse-hpc/python/numba/numba/targets/codegen.py", line 221, in finalize
    self._final_module.verify()
  File "/anaconda3/envs/PA37/lib/python3.7/site-packages/llvmlite/binding/module.py", line 116, in verify
    raise RuntimeError(str(outmsg))
RuntimeError: Failed in nopython mode pipeline (step: nopython mode backend)
Terminator found in the middle of a basic block!
label %"_ZN4hpat8hiframes4join21copy_elem_buff$241518E16CategoricalArrayI766PDCategoricalDtype$28$5b$27AK$27$2c$20$27AL$27$2c$20$27AR$27$2c$20$27AZ$27$2c$20$27CA$27$2c$20$27CO$27$2c$20$27CT$27$2c$20$27DC$27$2c$20$27DE$27$2c$20$27FL$27$2c$20$27GA$27$2c$20$27HI$27$2c$20$27IA$27$2c$20$27ID$27$2c$20$27IL$27$2c$20$27IN$27$2c$20$27KS$27$2c$20$27KY$27$2c$20$27LA$27$2c$20$27MA$27$2c$20$27MD$27$2c$20$27ME$27$2c$20$27MI$27$2c$20$27MN$27$2c$20$27MO$27$2c$20$27MS$27$2c$20$27MT$27$2c$20$27NC$27$2c$20$27ND$27$2c$20$27NE$27$2c$20$27NH$27$2c$20$27NJ$27$2c$20$27NM$27$2c$20$27NV$27$2c$20$27NY$27$2c$20$27OH$27$2c$20$27OK$27$2c$20$27OR$27$2c$20$27PA$27$2c$20$27PR$27$2c$20$27RI$27$2c$20$27SC$27$2c$20$27SD$27$2c$20$27TN$27$2c$20$27TX$27$2c$20$27UT$27$2c$20$27VA$27$2c$20$27VI$27$2c$20$27VT$27$2c$20$27WA$27$2c$20$27WI$27$2c$20$27WV$27$2c$20$27WY$27$5d$29Li1E1C7mutable7alignedEx766PDCategoricalDtype$28$5b$27AK$27$2c$20$27AL$27$2c$20$27AR$27$2c$20$27AZ$27$2c$20$27CA$27$2c$20$27CO$27$2c$20$27CT$27$2c$20$27DC$27$2c$20$27DE$27$2c$20$27FL$27$2c$2"
```

**Comment by stuartarchibald** [comment] 2019-03-18 09:42
Thanks for the report. I'm fairly sure that the problem you are seeing is a known one and it is due to a bug in LLVM 7 itself, basically, really long labels (>1024 chars) fail to parse correctly, see #3669 for a duplicate issue.

**Comment by ehsantn** [comment] 2019-03-18 11:59
I thought that issue was resolved in llvmlite dev at least (#3669 is closed).

**Comment by stuartarchibald** [comment] 2019-03-18 12:05
The issue in #3669 (and many others) was giant `if..endif` chains as labels, which was relatively easy to hit with a few nested conditions, it was fixed (we stopped generating such large labels in such cases as their use was limited). The issue above is the same problem, but with what seems like a long variable? name in a label. This probably needs fixing in two places, 1. Numba/llvmlite source, 2. LLVM.

**Comment by stuartarchibald** [comment] 2019-03-18 12:19
@ehsantn think I've found the root cause in LLVM: https://reviews.llvm.org/D41296

Here's a work around... put this somewhere in the init sequence (2048 is just a larger number, you may need to make it bigger!):
```python
from llvmlite import binding
binding.set_option("tmp", "-non-global-value-max-name-size=2048")
```

**Comment by ehsantn** [comment] 2019-03-18 12:57
Thanks @stuartarchibald . This resolves the issue. There is no large variable name I believe. Can this issue be solved by a relabeling pass permanently?

**Comment by stuartarchibald** [comment] 2019-03-18 13:10
No problem. Expect something similar to https://github.com/numba/llvmlite/pull/454 is needed. Though also wonder if it's worth patching LLVM to be on the safe side.

**Comment by stuartarchibald** [comment] 2019-05-15 07:39
This is now fixed in the latest `llvmlite` builds on the Numba channel.

**Closed by stuartarchibald** 2019-05-15 07:39 UTC
Labels: bug, duplicate, llvm

**Comment by toddrme2178** [comment] 2019-07-23 03:16
@stuartarchibald  Is there a reason `-non-global-value-max-name-size` can't be used instead of patching LLVM?  Patching LLVM makes numba much harder to package since you can't use the system LLVM install anymore.

**Comment by stuartarchibald** [comment] 2019-07-23 08:09
> @stuartarchibald Is there a reason `-non-global-value-max-name-size` can't be used instead of patching LLVM?

Yes, essentially it boils down to "To what value would that flag be set?" and a couple of technical reasons. In the case of autogenerated label names it's not predictable what a label would look like as it is a function of user code. Before adding this patch some effort was put in to reduce/shorten label names at the site of code generation but we concluded it was too risky to ship as we couldn't absolutely guarantee the fix.

> Patching LLVM makes numba much harder to package since you can't use the system LLVM install anymore.

This is unfortunate, however historically the Numba stack has patched LLVM for a variety of reasons, including bugs that corrupt memory, addition of performance libraries (SVML), back porting critical fixes etc. This presents a good reason to build your own with the patches to fix problems/use the llvmdev conda packages https://anaconda.org/numba/llvmdev which contain fully tested LLVM builds.

**Comment by seibert** [comment] 2019-07-23 13:26
Similarly, Julia has an even longer stack of patches to fix things for usage of LLVM in their JIT.  This problem and the tendency (not as bad as it used to be) for the APIs to churn between releases is why we statically link to LLVM in the first place.

We probably ought to consider having the llvmlite source build have a self-contained script to build LLVM outside of conda-build for platforms where we haven't posted wheels.

**Comment by stuartarchibald** [comment] 2019-07-23 13:42
> We probably ought to consider having the llvmlite source build have a self-contained script to build LLVM outside of conda-build for platforms where we haven't posted wheels.

I agree, this would also help when doing development work with LLVM where having a "dirty" conda build currently presents the best solution to get a mostly-working build on which to then hack/try fixes, https://github.com/numba/llvmlite/issues/501 tracks.

**Comment by toddrjen** [comment] 2019-07-23 14:38
> > @stuartarchibald Is there a reason `-non-global-value-max-name-size` can't be used instead of patching LLVM?
> 
> Yes, essentially it boils down to "To what value would that flag be set?" and a couple of technical reasons. In the case of autogenerated label names it's not predictable what a label would look like as it is a function of user code. Before adding this patch some effort was put in to reduce/shorten label names at the site of code generation but we concluded it was too risky to ship as we couldn't absolutely guarantee the fix.

It appears the limit is an unsigned int, so uint32 at the smallest.  So what about setting it to the largest possible uin32 value, 4,294,967,295 (or something in that ballpark)?  Would an identifier plausibly take up 4 GB of memory?

> > Patching LLVM makes numba much harder to package since you can't use the system LLVM install anymore.
> 
> This is unfortunate, however historically the Numba stack has patched LLVM for a variety of reasons, including bugs that corrupt memory, addition of performance libraries (SVML), back porting critical fixes etc. This presents a good reason to build your own with the patches to fix problems/use the llvmdev conda packages https://anaconda.org/numba/llvmdev which contain fully tested LLVM builds.

I thought that the project was trying to move away from that to make it as accessible as possible to as large an audience as possible.  There are lots of other projects providing fully tested LLVM builds.

**Comment by toddrme2178** [comment] 2019-07-23 14:41
@stuartarchibald  

> Yes, essentially it boils down to "To what value would that flag be set?" and a couple of technical reasons. In the case of autogenerated label names it's not predictable what a label would look like as it is a function of user code. Before adding this patch some effort was put in to reduce/shorten label names at the site of code generation but we concluded it was too risky to ship as we couldn't absolutely guarantee the fix.

It appears the limit is an unsigned int, so uint32 at the smallest.  So what about setting it to the largest possible uin32 value, 4,294,967,295 (or something in that ballpark)?  Would an identifier plausibly take up 4 GB of memory?

> This is unfortunate, however historically the Numba stack has patched LLVM for a variety of reasons, including bugs that corrupt memory, addition of performance libraries (SVML), back porting critical fixes etc. This presents a good reason to build your own with the patches to fix problems/use the llvmdev conda packages https://anaconda.org/numba/llvmdev which contain fully tested LLVM builds.

I thought that the project was trying to move away from that to make it as accessible as possible to as large an audience as possible.  There are lots of other projects providing fully tested LLVM builds, including backporting fixes to bugs.  But this isn't really a bug, it is a fix for a bug with a workaround provided for people who depended on the old behavior.

**Comment by seibert** [comment] 2019-07-23 15:27
We try to minimize our dependency on patches, but I suspect it will never go away if we want things to work for users.  Patches aside, the API churn means that the LLVM version present on the user system is probably not the right one, or was built with some flag combination that inadvertently affects us.  A lot of our paranoia on this came from the LLVM 3.x era, but it seems even now as we start to consider relaxing our stance, some issue will arise.

**Comment by toddrme2178** [comment] 2019-07-26 14:58
@seibert I can understand that patches are sometimes needed.  I am just not clear why it is needed in this case.  Wouldn't setting the limit to the maximum possible value be reasonable, considering a label that takes 4 gb of memory would be a serious problem for numba anyway?

**Comment by seibert** [comment] 2019-07-26 16:45
I'm not opposed to dropping the this patch and setting the limit higher, since it seems to have no impact on memory usage, and we have more time to test things now.
