### ISSUE TITLE
not helping for the np.argsort() 

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4217] opened 2019-06-24 06:36 UTC
I want to find the most efficient approach to calculate the Spearman's rank correlation coefficient
usually use  scipy.stats.spearmanr to do the job 
but  scipy.stats.spearmanr is slow , so I write the function by numpy and numba again 

```
@jit(nopython = True)
def rankIC(targetValue,out):

	n = len(targetValue)  	#suppose the length of targetValue and out is the same 
	targetRank = np.argsort(np.argsort(targetValue)) + 1
	outRank = np.argsort(np.argsort(out)) + 1
	d_sum = np.sum((targetRank - outRank) ** 2)
	rho_target_out = 1 - (6*d_sum / (n * (n*n -1)))
	
	return rho_target_out
```

```
v1 = np.random.randn(1000)
v2 = np.random.rand(1000)

%timeit scipy.stats.spearmanr(v1,v2)
#737 µs ± 14.4 µs per loop
%timeit rankIC(v1,v2)
#290 µs ± 3.59 µs per loop 
%timeit rankIC.py_func(v1,v2)
#231 µs ± 3.67 µs per loop
```

So numpy and numba is really faster than scipy.stats.spearmanr, but why jit cannot speed up the rankIC, and actually slow down the rankIC 
How can I fix the problem , thank you so much .

**Comment by stuartarchibald** [comment] 2019-06-24 10:41
Thanks for the report. The documentation http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#other-methods notes:

> Warning
>
> Sorting may be slightly slower than Numpy’s implementation.

which is likely the cause of what you are seeing.

**Comment by stuartarchibald** [comment] 2019-09-11 14:51
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:51 UTC
Labels: no action required
