### ISSUE TITLE
'cannot import name '_typeconv' from 'numba.typeconv'

### ISSUE THREAD

**Issue by richesh09** [numba/numba#4732] opened 2019-10-22 13:42 UTC
ImportError                               Traceback (most recent call last)
G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typeconv\typeconv.py in <module>
      5     # Numba, if it fails to import, provide some feedback
----> 6     from . import _typeconv
      7 except ImportError as e:

ImportError: cannot import name '_typeconv' from 'numba.typeconv' (G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typeconv\__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-15-b0831a92e484> in <module>
----> 1 from numba import vectorize

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\__init__.py in <module>
     16 
     17 # Re-export typeof
---> 18 from .special import typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init
     19 
     20 # Re-export error classes

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\special.py in <module>
      1 from __future__ import print_function, division, absolute_import
      2 
----> 3 from .typing.typeof import typeof
      4 import numpy as np
      5 

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typing\__init__.py in <module>
      1 from __future__ import absolute_import
----> 2 from .context import BaseContext, Context
      3 from .templates import (signature, make_concrete_template, Signature,
      4                         fold_arguments)

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typing\context.py in <module>
     10 import numba
     11 from numba import types, errors
---> 12 from numba.typeconv import Conversion, rules
     13 from . import templates
     14 from .typeof import typeof, Purpose

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typeconv\rules.py in <module>
      1 from __future__ import print_function, absolute_import
      2 import itertools
----> 3 from .typeconv import TypeManager, TypeCastingRules
      4 from numba import types
      5 

G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typeconv\typeconv.py in <module>
     14            "development:\n%s\nThe original error was: '%s'") % \
     15            (url, reportme, str(e))
---> 16     raise ImportError(msg)
     17 
     18 from . import castgraph, Conversion

ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.typeconv' (G:\Anaconda_520\envs\advenioDeepLearning\lib\site-packages\numba\typeconv\__init__.py)'

**Comment by stuartarchibald** [comment] 2019-10-23 20:35
Thanks for the report. To help diagnose it, please could you describe how you installed Numba and which OS you are using, thanks.

**Comment by jjbuck** [comment] 2019-10-30 21:09
I'm having the same issue. 

```
Traceback (most recent call last):
File "/opt/amazon/lib/python3.6/site-packages/numba/typeconv/typeconv.py", line 6, in <module>
from . import _typeconv
portError: cannot import name '_typeconv'
```

I'm installing numba as follows in a Docker image.

```
RUN wget https://bootstrap.pypa.io/get-pip.py && python3.6 get-pip.py && \
    python3.6 -m pip install numpy scipy torchvision torch pandas flask gevent gunicorn numba llvmlite
```

**Comment by jjbuck** [comment] 2019-10-30 23:47
Evidently the issue goes away if I explicitly set numba==0.45.0.

**Comment by stuartarchibald** [comment] 2019-10-31 08:40
@jjbuck thanks for the report. What was being installed before you explicitly set `numba==0.45.0` ?

**Comment by sklam** [comment] 2019-10-31 15:00
@jjbuck, I tried using the docker image from https://github.com/aws/sagemaker-pytorch-container/tree/master/docker/1.1.0 and I can't reproduce the problem. It also doesn't have `/lib/python3.6/` in the image.  I think you might have multiple installation of python.

**Comment by TangeniThePyGuru** [comment] 2019-12-21 20:09
I created a symbolic link of numba for python 2 into an environment that makes use of python 3,
so i fixed this by removing the symbolic link i created and recreated a new one:

cd ~/<virtual environment name>/lib/python3.6/site-packages/;  ln -sf /usr/lib/python3/dist-packages/numba numba

**Comment by stuartarchibald** [comment] 2019-12-31 14:46
Closing as this cannot be reproduced. As the issue most often comes from having a slightly mixed up environment (often one python version importing a Numba package for a different python version) this is now added https://github.com/numba/numba/pull/4768 to help debug.

**Closed by stuartarchibald** 2019-12-31 14:46 UTC
Labels: needtriage

**Comment by perfumescent** [comment] 2020-04-18 15:56
yeah I met this problem too. Resetting numba to version 0.45.0 works.

**Comment by advancedwebdeveloper** [comment] 2020-12-10 10:08
I am able to reproduce [this](https://github.com/numba/numba/issues/6559) on  riscv64-unknown-linux-gnu

**Comment by jppgks** [comment] 2022-03-16 09:30
For future reference, I ran into this when importing numba while in the numba source directory. Moving out of the numba repository root worked for me 🙃
