### ISSUE TITLE
Segmentation fault with cffi external module and njit parallel=True

### ISSUE THREAD

**Issue by dimitar-petrov** [numba/numba#3961] opened 2019-04-09 21:26 UTC
When calling external cffi compiled extension from numba parallel loop the following exception is received:

```
tests/test_concurrent.py::test_concurrent_noreturn At line 186 of file ./src/nufft1df90.f
Fortran runtime error: Attempting to allocate already allocated variable 'fw'
```

There is an extension module that is simulating the problem.

Bellow is a bash snipped that will pull/build the extension and run the three unit tests. First one that is without parallel loop is passing but the next two are failing with the error mentioned above.

```
mkdir testenv
cd testenv
python -m venv .env
source .env/bin/activate

pip install -e git+https://github.com/finxploit/pybind.git#egg=pybind
cd .env/src/pybind

pip install pytest

pytest -svv ./tests/test_concurrent.py -k noconcurrent_return
pytest -svv ./tests/test_concurrent.py -k concurrent_noreturn
pytest -svv ./tests/test_concurrent.py -k concurrent_return
```

@stuartarchibald, as discussed

**Comment by stuartarchibald** [comment] 2019-04-10 12:22
Thanks for producing this @dimitar-petrov I'll look into it.

**Comment by stuartarchibald** [comment] 2019-04-11 10:25
As noted [on IRC](https://gitter.im/numba/numba?at=5cadf312016a930a4596f19b) I can reproduce what you are seeing, but also have concerns over the Fortran source in that there's a lot of out of bounds access and type mismatches.

To do a basic check that there's not something fundamentally strange going on I wrote some fortran, C and python to check that:
 * Calling a Fortran function, which does local allocation, located in a DSO from C both inside and outside of OpenMP (using this to cheaply provide a thread pool) works fine.
 * Calling the same Fortran function in the DSO from Numba in both a serial and a parallel context works fine.

Code is here: https://gist.github.com/stuartarchibald/50f68f598e3fe0fcc9799c2cde28768d

**Comment by stuartarchibald** [comment] 2019-04-12 08:29
@dimitar-petrov Two more things.
1. I note that the code sometimes produces the:
   > Fortran runtime error: Attempting to allocate already allocated variable 'fw'

   error, but sometimes (perhaps 1/8 times) it segfaults, I'm thinking that everything observed so far  may be entirely down to corruption.
2. I spoke with @anton-malakhov yesterday as the threading backend was something we both worked on and he also could not think of anything specific that would prevent this from working, but suggested that if in doubt preallocating memory outside the parallel regions is often the safe option.

**Comment by dimitar-petrov** [comment] 2019-04-12 15:07
@stuartarchibald, thanks for the detailed explanation.

**Comment by stuartarchibald** [comment] 2019-04-18 21:59
@dimitar-petrov no problem, thanks for using Numba.

Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-04-18 21:59 UTC
Labels: question
