### ISSUE TITLE
"CUDA driver libraries are found but error occurred during load" when used with nvidia-docker

### ISSUE THREAD

**Issue by d53dave** [numba/numba#3396] opened 2018-10-10 13:12 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Dear Numba team,

first of all: great work on this software. Thank you!

I've run into an issue when running Numba inside docker with nvidia-docker. It seems something goes wrong in Numba when looking for `libcuda.so`, resulting in error when running kernels:

```
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

Possible CUDA driver libraries are found but error occurred during load:
libcuda.so: cannot open shared object file: No such file or directory
libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib/libcuda.so: cannot open shared object file: No such file or directory
/usr/lib/libcuda.so.1: cannot open shared object file: No such file or directory
libnvidia-fatbinaryloader.so.410.48: cannot open shared object file: No such file or directory
libnvidia-fatbinaryloader.so.410.48: cannot open shared object file: No such file or directory`
```

Suspecting that the library is missing or misplaced, I looked for it:

```bash
$ find / -type f -iname "libcuda.so*"
/usr/lib64/libcuda.so.410.48
```

So it's there all right, and I therefore thought that Numba is not looking into `/usr/lib64`.

Adding `/usr/lib64/` to `LD_LIBRARY_PATH` seems to be fixing the issue for me but I'm not aware of how Numba exactly tries to load the driver. The documentation doesn't mention anything about it apart from a release note reading `PR #3216: Fix libcuda.so loading in some container setup`. In my case, I was building on [frolvlad/alpine-miniconda3](https://hub.docker.com/r/frolvlad/alpine-miniconda3/), and `LD_LIBRARY_PATH` was empty.

I'm not sure how much support you want to give to this usecase (i.e. docker with nvidia-docker), but seeing that one of the selling points of Numba is portable code, this might be something to take into consideration, at least as a section in the documentation.

After spending quite some time with making a project work that does run containerized Numba with a guest-only `cudatoolkit` on a container that is as small as possible, I'd be willing to contribute documentation if you so desire. Let me know.

## Reproducer

Start container: 

```bash
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility --rm -it  frolvlad/alpine-miniconda3 /bin/sh
```

Install numba and cudatoolkit:

```bash
conda create -n numbaenv python=3.7 cudatoolkit=8.0 numba=0.40.0
source activate numbaenv
python
```

It's not even necessary to run a kernel to reproduce the issue:

```python
>>> import numba
>>> from numba import cuda
>>> for device in numba.cuda.gpus: print(device)
```

**Comment by stuartarchibald** [comment] 2018-10-11 11:39
Thanks for the report. Numba looks for CUDA drivers in `/usr/lib` and `/usr/lib64` on linux:
https://github.com/numba/numba/blob/61a13a67ff3ada26def914750c4fa6f78c2af8cf/numba/cuda/cudadrv/driver.py#L104

I think the issue here is that it looks for the common sonames of `libcuda.so` and `libcuda.so.1`, whereas the container described has the, presumably, same library with a soname of `libcuda.so.410.48`. A method for specifying the CUDA driver location in this event is to use the `NUMBAPRO_CUDA_DRIVER` environment variable, perhaps try:
```
export NUMBAPRO_CUDA_DRIVER=/usr/lib64/libcuda.so.410.48
```
bit more info here: http://numba.pydata.org/numba-doc/dev/user/installing.html?highlight=numbapro_cuda_driver#installing-using-pip-on-x86-x86-64-platforms

**Comment by d53dave** [comment] 2018-10-11 11:44
Thanks for your response, Stuart.

The thing is that adding `/usr/lib64` to `LD_LIBRARY_PATH` made Numba pick up the library with the non-standard soname, which is weird. Without that, it fails to load it. Just to be clear: it's working now, with only the `LD_LIBRARY_PATH`, and no value in `NUMBAPRO_CUDA_DRIVER`.

**Comment by stuartarchibald** [comment] 2018-10-11 11:57
No problem. That's a bit puzzling, the driver is bound via `ctypes.CDLL` which requires a fully qualified path to the driver DSO as part of the `dlopen()`. I wouldn't have thought that adding the dir to `LD_LIBRARY_PATH` would have made much difference as it still wouldn't provide the specificity required by the binding code, unless of course the addition of this somehow permits it to find the DSO on the host. What does this give you?
```
In [4]: from numba.cuda.cudadrv.driver import driver

In [5]: driver.lib
Out[5]: <CDLL 'libcuda.so', handle 5644d6f4b760 at 7f226dc1d450>
```
for me, it evidently finds `libcuda.so`, I'm curious if for you it is `libcuda.so.410.48`.

Thanks.

**Comment by d53dave** [comment] 2018-10-11 12:32
Here's the output with `unset LD_LIBRARY_PATH`:

```
Python 3.7.0 | packaged by conda-forge | (default, Sep 30 2018, 14:56:18) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba.cuda.cudadrv.driver import driver
>>> driver.lib
Traceback (most recent call last):
  File "/opt/conda/envs/csaopt-worker/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 262, in __getattr__
    proto = API_PROTOTYPES[fname]
KeyError: 'lib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/csaopt-worker/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 264, in __getattr__
    raise AttributeError(fname)
AttributeError: lib
```

And here it is with `export LD_LIBRARY_PATH=/usr/lib64/`:

```
Python 3.7.0 | packaged by conda-forge | (default, Sep 30 2018, 14:56:18) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba.cuda.cudadrv.driver import driver
>>> driver.lib
<CDLL 'libcuda.so', handle 1769570 at 0x7f3f0ed21470>
```

After double-checking, nvidia-cuda does put the necessary links (i.e. `libcuda.so` and `libcuda.so.1`) into `/usr/lib64/`, but Numba doesn't seem to be looking there:

```bash
/opt/csaopt-worker $ ls -alh /usr/lib64/
total 103448
drwxr-xr-x    2 root     root        4.0K Oct 11 12:25 .
drwxr-xr-x    1 root     root        4.0K Oct 11 12:25 ..
lrwxrwxrwx    1 root     root          12 Oct 11 12:25 libcuda.so -> libcuda.so.1
lrwxrwxrwx    1 root     root          17 Oct 11 12:25 libcuda.so.1 -> libcuda.so.410.48
-rw-r--r--    1 root     root       14.9M Sep  6 11:39 libcuda.so.410.48
lrwxrwxrwx    1 root     root          23 Oct 11 12:25 libnvidia-cfg.so.1 -> libnvidia-cfg.so.410.48
-rw-r--r--    1 root     root      190.4K Sep  6 11:17 libnvidia-cfg.so.410.48
-rw-r--r--    1 root     root       45.6M Sep  6 11:59 libnvidia-compiler.so.410.48
-rw-r--r--    1 root     root      286.0K Sep  6 11:16 libnvidia-fatbinaryloader.so.410.48
lrwxrwxrwx    1 root     root          22 Oct 11 12:25 libnvidia-ml.so.1 -> libnvidia-ml.so.410.48
-rw-r--r--    1 root     root        1.3M Sep  6 11:23 libnvidia-ml.so.410.48
lrwxrwxrwx    1 root     root          26 Oct 11 12:25 libnvidia-opencl.so.1 -> libnvidia-opencl.so.410.48
-rw-r--r--    1 root     root       27.1M Sep  6 11:39 libnvidia-opencl.so.410.48
lrwxrwxrwx    1 root     root          34 Oct 11 12:25 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.410.48
-rw-r--r--    1 root     root       11.6M Sep  6 11:28 libnvidia-ptxjitcompiler.so.410.48
```

**Comment by stuartarchibald** [comment] 2018-10-11 13:18
Thanks. I think I understand what's going on now have done some `strace`ing and wandering around in ctypes code. I was mistaken about the paths going to `CDLL`, this is what happens:

On Linux, when Numba tries to bind to the CUDA driver, it by default tries to load the following with`CDLL`, breaking on successful load:
```
['libcuda.so', 'libcuda.so.1', '/usr/lib/libcuda.so', '/usr/lib/libcuda.so.1', '/usr/lib64/libcuda.so', '/usr/lib64/libcuda.so.1']
```
Note the first two are just library names without a path. In the case of passing just a library name to `CDLL` it tries to find a library that matches using `ld` and its default search methods (this instigated by a `dlopen` call inside ctypes itself).

I think in your case, `/usr/lib64` was not originally available for `ld` to search and by adding it to `LD_LIBRARY_PATH` it becomes available and therefore when `CDLL` now looks for `libcuda.so`, `ld` finds it passes it to `dlopen`, ctypes binds to it, Numba is happy.

**Comment by stuartarchibald** [comment] 2018-10-11 13:46
You could also just try and `ldd /usr/lib64/libcuda.so` and see if all the dependencies are resolved in the case of no `LD_LIBRARY_PATH` being set. That'd be a clear indication as to whether `CDLL` is going to succeed.

**Comment by d53dave** [comment] 2018-10-11 15:12
I'll try it out tonight and report back.

**Comment by stuartarchibald** [comment] 2018-10-12 16:18
@d53dave Great, thanks, please do let us know how you get on, it'd be good to get to the bottom of this!

**Comment by d53dave** [comment] 2018-10-12 20:05
I've created `issue3396.py` and ran strace with the following full output (while `LD_LIBRARY_PATH` is set):

```bash
/opt/csaopt-worker $ strace -fe open python issue3396.py 2>&1
strace: Process 33 attached
[pid    33] open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
[pid    33] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=33, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
Getting driver
<CDLL 'libcuda.so', handle 1a07340 at 0x7fddea1a4080>
+++ exited with 0 +++
```

Without `LD_LIBRARY_PATH` the call results in an error (same as before). It's weird that strace doesn't spit out any library loads.

The output of `ldd` might be a bit more interesting:
No `LD_LIBRARY_PATH`:

```bash
/opt/csaopt-worker $ ldd /usr/lib64/libcuda.so
        ldd (0x7f2110354000)
        libm.so.6 => ldd (0x7f2110354000)
        libc.so.6 => ldd (0x7f2110354000)
        libdl.so.2 => ldd (0x7f2110354000)
        libpthread.so.0 => ldd (0x7f2110354000)
        librt.so.1 => ldd (0x7f2110354000)
Error loading shared library libnvidia-fatbinaryloader.so.410.48: No such file or directory (needed by /usr/lib64/libcuda.so)
Error relocating /usr/lib64/libcuda.so: fatBinaryCtl_Compile: symbol not found
Error relocating /usr/lib64/libcuda.so: fatBinaryCtl: symbol not found
Error relocating /usr/lib64/libcuda.so: backtrace: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_section_contents: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_symbol_shndx: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Free_Fatbinary: symbol not found
Error relocating /usr/lib64/libcuda.so: fatBinaryCtl_Delete: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_symbol_name: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Start_Reading_Library: symbol not found
Error relocating /usr/lib64/libcuda.so: elf_end: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Finish: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_string_at_offset: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Finish_Reading_Library: symbol not found
Error relocating /usr/lib64/libcuda.so: fatBinaryCtl_PickCandidate: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Next_Library_Member: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Delete: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_named_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_shnum: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_section_name: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_file_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_typed_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: gpucompRestoreLogLine: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Load_Host_Object: symbol not found
Error relocating /usr/lib64/libcuda.so: __strtod_internal: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_shnum: symbol not found
Error relocating /usr/lib64/libcuda.so: gpuInfoRunsOn: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_string_at_offset: symbol not found
Error relocating /usr/lib64/libcuda.so: elf_size: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_typed_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_file_header: symbol not found
Error relocating /usr/lib64/libcuda.so: elf32_named_section_header: symbol not found
Error relocating /usr/lib64/libcuda.so: gpucompSetLogLine: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Free_Host_Object: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_section_name: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Get_FatBinary_From_Object: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Start: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_symbol_shndx: symbol not found
Error relocating /usr/lib64/libcuda.so: elfLink_Add_Cubin: symbol not found
Error relocating /usr/lib64/libcuda.so: fatBinaryCtl_Create: symbol not found
Error relocating /usr/lib64/libcuda.so: elf_is_64bit: symbol not found
Error relocating /usr/lib64/libcuda.so: elf64_symbol_name: symbol not found
```

With `LD_LIBRARY_PATH`:

```bash
/opt/csaopt-worker $ ldd /usr/lib64/libcuda.so
        ldd (0x7f043c5fe000)
        libm.so.6 => ldd (0x7f043c5fe000)
        libc.so.6 => ldd (0x7f043c5fe000)
        libdl.so.2 => ldd (0x7f043c5fe000)
        libpthread.so.0 => ldd (0x7f043c5fe000)
        librt.so.1 => ldd (0x7f043c5fe000)
        libnvidia-fatbinaryloader.so.410.48 => /usr/lib64/libnvidia-fatbinaryloader.so.410.48 (0x7f043b2bb000)
Error relocating /usr/lib64/libnvidia-fatbinaryloader.so.410.48: __strtod_internal: symbol not found
Error relocating /usr/lib64/libcuda.so: backtrace: symbol not found
Error relocating /usr/lib64/libcuda.so: __strtod_internal: symbol not found
```

I also tried it with `LD_DEBUG=libs` but the output is quite long, so I won't paste it. I uploaded two files: 

[ld_path_set.txt](https://github.com/numba/numba/files/2474399/ld_path_set.txt) 
[ld_path_unset.txt](https://github.com/numba/numba/files/2474400/ld_path_unset.txt)

> Were I to guess I'd say that dlopen succeeds in opening /usr/lib64/libcuda.so but then as it tries to chainload the dependencies for libcuda.so it can't find libnvidia-fatbinaryloader.so.* because /usr/lib64 is not on a path searched by ld.

From the output of `ldd`, it sure looks like that would case, but I don't see any indication of any successfull loads with `dlopen` int the `LD_DEBUG=libs` output. The search definitely doesn't continue to `dldir = ['/usr/lib', '/usr/lib64']`.

By the way, I had to run docker with the `--privileged` flag, otherwise strace errors out with `strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted`.

**Comment by stuartarchibald** [comment] 2018-10-15 11:49
Thanks for this. I think this confirms my suspicions, that it's the loading of the dependencies of `libcuda.so` that prevents binding to `libcuda.so.1` in the case when `LD_LIBRARY_PATH` is not set to include the location of the dependencies. The output from `ldd` demonstrates this nicely.

Also, looking at the `LD_DEBUG` output... In the case of `LD_LIBRARY_PATH` being appropriately set, this shows `libcuda.so` being found on the `LD_LIBRARY_PATH` and then `ld` looking for `libnvidia-fatbinaryloader.so.410.48` and it finding it on `LD_LIBRARY_PATH`, calling it's DSO initilizer successfully and then subsequently calling the same for `libcuda.so`, hence the binding succeeds.
```
        49:     find library=libcuda.so [0]; searching
        49:      search path=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../..              (RPATH from file /opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so)
        49:       trying file=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../../libcuda.so
        49:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        49:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libcuda.so
        49:      search path=/usr/lib64         (LD_LIBRARY_PATH)
        49:       trying file=/usr/lib64/libcuda.so
        49:
        49:     find library=libnvidia-fatbinaryloader.so.410.48 [0]; searching
        49:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        49:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libnvidia-fatbinaryloader.so.410.48
        49:      search path=/usr/lib64         (LD_LIBRARY_PATH)
        49:       trying file=/usr/lib64/libnvidia-fatbinaryloader.so.410.48
        49:
        49:
        49:     calling init: /usr/lib64/libnvidia-fatbinaryloader.so.410.48
        49:
        49:
        49:     calling init: /usr/lib64/libcuda.so
```
the equivalent section in the case of no `LD_LIBRARY_PATH` being set is:
```
        45:     find library=libcuda.so [0]; searching
        45:      search path=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../..              (RPATH from file /opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so)
        45:       trying file=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../../libcuda.so
        45:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        45:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libcuda.so
        45:      search cache=/usr/glibc-compat/etc/ld.so.cache
        45:      search path=/usr/glibc-compat/lib              (system search path)
        45:       trying file=/usr/glibc-compat/lib/libcuda.so
        45:
        45:     find library=libcuda.so.1 [0]; searching
        45:      search path=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../..              (RPATH from file /opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so)
        45:       trying file=/opt/conda/envs/csaopt-worker/lib/python3.7/lib-dynload/../../libcuda.so.1
        45:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        45:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libcuda.so.1
        45:      search cache=/usr/glibc-compat/etc/ld.so.cache
        45:      search path=/usr/glibc-compat/lib              (system search path)
        45:       trying file=/usr/glibc-compat/lib/libcuda.so.1
        45:
        45:     find library=libnvidia-fatbinaryloader.so.410.48 [0]; searching
        45:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        45:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libnvidia-fatbinaryloader.so.410.48
        45:      search cache=/usr/glibc-compat/etc/ld.so.cache
        45:      search path=/usr/glibc-compat/lib              (system search path)
        45:       trying file=/usr/glibc-compat/lib/libnvidia-fatbinaryloader.so.410.48
        45:
        45:     find library=libnvidia-fatbinaryloader.so.410.48 [0]; searching
        45:      search path=/opt/conda/envs/csaopt-worker/bin/../lib           (RPATH from file python)
        45:       trying file=/opt/conda/envs/csaopt-worker/bin/../lib/libnvidia-fatbinaryloader.so.410.48
        45:      search cache=/usr/glibc-compat/etc/ld.so.cache
        45:      search path=/usr/glibc-compat/lib              (system search path)
        45:       trying file=/usr/glibc-compat/lib/libnvidia-fatbinaryloader.so.410.48
```
which shows `ld` finding `libcuda.so`, realising it's a symlink and then finding `libcuda.so.1`, then looking up the dependencies of that and trying to find `libnvidia-fatbinaryloader.so.410.48`, which it cannot, hence it can't load `libcuda.so`.

Finally, the `strace` output is a bit strange, might be container/privilege related as noted. However I don't think it would add anything further.

I guess the "fix" is to make sure `ld` can see `/usr/lib64` either via `LD_LIBRARY_PATH` or `/etc/ld.conf.so` or whatever suits your system?

**Comment by d53dave** [comment] 2018-10-15 12:33
> I guess the "fix" is to make sure ld can see /usr/lib64 either via LD_LIBRARY_PATH or /etc/ld.conf.so or whatever suits your system? 

Works on my machine 😂. 
Feel free to close this if it's a "won't fix", but it might be a good idea to have a short paragraph on this issue somewhere in the docs.

**Comment by stuartarchibald** [comment] 2018-10-15 13:28
hmmm, two thoughts...
* Perhaps the consistent thing to do for future releases is to look for the CUDA libraries by name only such that solely `ld` performs the search resolution. In this way, if you've got a full path `/usr/lib64/libcuda.so`, and `/usr/lib64` is on `ld`'s search path it'll find the library based on name alone and chain load the dependencies (assuming they are somewhere it can locate, else it'll just fail). If however `/usr/lib64` is not on the path it won't find the library at all. This prevents the half working case you've experienced where `dlopen` is called on a baked in specified library path which then invoked `ld`, but `ld` cannot load its dependencies and requires a load of debug to figure out what the problem is because it *looks* like it ought to work.
* Another option is to leave the code as is and in the case where we can "see" a library on a specified path but cannot `dlopen` it, suggest that it's probably a dependency problem and get some output about it onto the user's screen.

I'm not sure if either of these options will break anything else CUDA wise... ping @sklam @seibert.

**Comment by stuartarchibald** [comment] 2020-09-14 17:17
https://github.com/numba/numba/pull/4096 implemented some of the suggestions in here. Closing as this seems to be an edge case and the discussion is searchable from search engines which should provide a good set of hints if anyone else gets stuck with this problem.

**Closed by stuartarchibald** 2020-09-14 17:17 UTC
Labels: CUDA
