### ISSUE TITLE
Support string datatype declaration for numpy array creation

### ISSUE THREAD

**Issue by mha-py** [numba/numba#6258] opened 2020-09-20 12:51 UTC
Hey!

When you have code like
```python
arr = np.zeros((N, M), dtype='uint8')
```
you cant just put the jit decorator in front of the function because numba doesnt recognize the string declaration. What is working is `from numba.types import bytes` and use that type instead. Problem is, that this type declaration is only working with numba, not without. Means that numpy throws an error when there is no jit decorator anymore.
So i guess it would be cool if numba would recoginze string declarations of data type!

**Comment by gmarkall** [comment] 2020-09-21 06:10
You can use the `np.uint8` dtype (and other dtypes in the `np` module in general) to keep the code working with and without the decorator, e.g.:

```python
from numba import njit
import numpy as np

@njit
def make_zeros_numba():
    return np.zeros(1, dtype=np.uint8)

def make_zeros_python():
    return np.zeros(1, dtype=np.uint8)

make_zeros_numba()
make_zeros_python()
```

compiles successfully.

**Comment by gmarkall** [comment] 2020-09-21 06:12
Additionally, marking as a feature request for support for strings for the dtype name.

**Comment by esc** [comment] 2020-09-21 08:55
@mha-py thank your for asking about this. I will close this as it is a duplicate of (the long standing issue) #2201.

**Closed** 2020-09-21 08:55 UTC
Labels: duplicate, feature_request, no action required, question
