### ISSUE TITLE
numba.errors.LoweringError

### ISSUE THREAD

**Issue by root-11** [numba/numba#3427] opened 2018-10-21 16:06 UTC
Numba asked me to submit a bugreport. I apologize in advance if it's a duplicate to somewhere else.
Here is the source code that triggered the error with the test suite included. 
(GPL v3) https://github.com/root-11/scratches/blob/master/numba-tsp.py

OS/env: I'm running windows10, numba 0.40.0 and python 3.6 installed using Conda.

```
D:\bin\anaconda3\envs\test_numba2\python.exe D:/test_numba/tsp.py
Traceback (most recent call last):
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\errors.py", line 599, in new_error_context
    yield
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\pylowering.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\pylowering.py", line 163, in lower_assign
    return self.lower_yield(value)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\pylowering.py", line 186, in lower_yield
    yp = self.generator_info.yield_points[inst.index]
AttributeError: 'NoneType' object has no attribute 'yield_points'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/test_numba/tsp.py", line 241, in <module>
    p = Points(10)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 835, in _compile_bytecode
    return self._compile_core()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 822, in _compile_core
    res = pm.run(self.status)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 244, in run
    stage()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 670, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 646, in _backend
    lowered = lowerfn()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 619, in backend_object_mode
    self.flags)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\compiler.py", line 1049, in py_lowering_stage
    lower.lower()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "D:\bin\anaconda3\envs\test_numba2\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\errors.py", line 607, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "D:\bin\anaconda3\envs\test_numba2\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'

File "tsp.py", line 48:
def Points(n, seed=123, width=999, height=666):
    <source elided>
        XYZpoint(x=random.randint(1, width), y=random.randint(1, height), z=0)
        for _ in range(n)
        ^

[1] During: lowering "$4.16.51 = yield $4.15" at D:/test_numba/tsp.py (48)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!


Process finished with exit code 1



```

**Comment by stuartarchibald** [comment] 2018-10-22 17:42
Thanks for the report. This is a known unsupported feature and a not particularly helpful error message! Numba does not support generator comprehension which is the root cause, a few more can be found here:
https://github.com/numba/numba/search?q=has+no+attribute+%27yield_points%27&type=Issues

Will try and at least improve the error message for the next release.

**Comment by stuartarchibald** [comment] 2019-09-11 13:52
Fixed by https://github.com/numba/numba/pull/4282

**Closed by stuartarchibald** 2019-09-11 13:52 UTC
Labels: bug, duplicate
