### ISSUE TITLE
Getting ValueError: cannot compute fingerprint of empty list with a list of tuples

### ISSUE THREAD

**Issue by REIS0** [numba/numba#4280] opened 2019-07-05 22:01 UTC
Getting this after trying to use numba to optimize a loop in another function, at first it was conflicting with the zip function and after some tests i've seen that the main cause is when it tries to loop with one empty list.
I'm using python 2.7 in this code.
```
def for2(swap_in_set,swap_out_set, n, reference_C, reference_occ):
    # copy the references and perform swaps
    C = copy.copy(reference_C)
    occ = list(reference_occ)
      
    # for swap_out, swap_in in zip(swap_out_set, swap_in_set):
    #     C[swap_out, :] = reference_C[swap_in, :]
    #     C[swap_in, :]  = reference_C[swap_out, :] # may be unnecessary
    #     occ[swap_out]  = reference_occ[swap_in]
    #     occ[swap_in] = reference_occ[swap_out]
    swap_list2 = zip(swap_out_set, swap_in_set)
    print "swap_list2: ", swap_list2
    for1(swap_in_set, swap_out_set, C, occ, reference_C, reference_C, swap_list2)
            
    # get the condition
    new_cond = cond_num(C)       
    return (new_cond, C, occ) 

@numba.njit(parallel=True)
def for1(swap_in_set, swap_out_set, C, occ, reference_C, reference_occ, swap_list):
    for swap_out, swap_in in numba.prange(swap_list):
        C[swap_out, :] = reference_C[swap_in, :]
        C[swap_in, :]  = reference_C[swap_out, :] # may be unnecessary
        occ[swap_out]  = reference_occ[swap_in]
        occ[swap_in] = reference_occ[swap_out]
```

here the error 

```
Level 0 / 4
swap_list2:  []
Traceback (most recent call last):
  File "numbaTest.py", line 130, in <module>
    main()
  File "numbaTest.py", line 90, in main
    Cs_occs = pool1.map(partial(for2, swap_out_set=swap_out_set, n=n, reference_C=reference_C, reference_occ=reference_occ), swap_list)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: cannot compute fingerprint of empty list
```

**Comment by stuartarchibald** [comment] 2019-07-08 08:23
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

In general the use of empty lists can lead to scenarios where it is not possible to infer the concrete data type of the list, I expect what you are seeing is a variant of this problem, example:
```python
import numba

@numba.njit
def foo(a):
    return a.append(1)

foo([])
```
the new "typed list" is intended to replace the current list implementation and it will make these problems less prevalent, deprecation/replacement schedule: http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types xref: https://github.com/numba/numba/pull/4151


Thanks.

**Comment by REIS0** [comment] 2019-07-08 21:09
Thanks for the response, i'm still learning how to properly report bugs and issues so this link now is my one best friends.
Yes, the example you provided gave the same error so i'll be anxiously waiting for the new typed list in numba!

After all here's an example how to reproduce the error with code.
```
import numba
import copy

reference_C = [[1,2,3],[1,2,3]]
reference_occ = [[1,2,3],[1,2,3]]
n = 0
swap_in_set = ()
swap_out_set = ()

def for2(swap_in_set,swap_out_set, n, reference_C, reference_occ):
    # copy the references and perform swaps
    C = copy.copy(reference_C)
    occ = list(reference_occ)
      
    # for swap_out, swap_in in zip(swap_out_set, swap_in_set):
    #     C[swap_out, :] = reference_C[swap_in, :]
    #     C[swap_in, :]  = reference_C[swap_out, :] # may be unnecessary
    #     occ[swap_out]  = reference_occ[swap_in]
    #     occ[swap_in] = reference_occ[swap_out]
    swap_list2 = zip(swap_out_set, swap_in_set)
    print "swap_list2: ", swap_list2
    for1(swap_in_set, swap_out_set, C, occ, reference_C, reference_C, swap_list2)
            
    # get the condition
    new_cond = cond_num(C)       
    return (new_cond, C, occ) 

@numba.njit(parallel=True)
def for1(swap_in_set, swap_out_set, C, occ, reference_C, reference_occ, swap_list):
    for swap_out, swap_in in numba.prange(swap_list):
        C[swap_out, :] = reference_C[swap_in, :]
        C[swap_in, :]  = reference_C[swap_out, :] # may be unnecessary
        occ[swap_out]  = reference_occ[swap_in]
        occ[swap_in] = reference_occ[swap_out]

@numba.njit(parallel=True)
def cond_num(matriz):
    sum = 0
    for i in numba.prange(len(matriz)):
        j = i
        sum = sum + matriz[i][j]
    return sum

for2(swap_in_set, swap_out_set, n, reference_C, reference_occ)
```

**Comment by stuartarchibald** [comment] 2019-07-09 08:54
@REIS0 No problem, thanks for reporting issues, it's very helpful as it lets us know what is broken and what things are causing issues for users. The next release will be out within a week or so I expect at which point feedback on the typed list implementation will be welcomed.

Also, RE the code above, `numba.prange()` is synonymous to `range`, so will not accept a zip.

**Comment by stuartarchibald** [comment] 2019-09-11 14:52
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:52 UTC
Labels: no action required

**Comment by Peter230655** [comment] 2023-07-28 13:53
When I run the program below, I get this errror:

ValueError: cannot compute fingerprint of empty list

I use number version 0.57.0

Any help will be greatly appreciated.  
# Tower of Hanoi

n = 25  # Number of rings

start = time.time()

@njit
def hanoi(n, source, helper, target):
    global k
    
    k += 1    # number of iterations through hanoi
    if n > 0:
# move tower of size n-1 from source to helper
        hanoi(n - 1, source, target, helper)
# move disk from source to target
        if source:
            target.append(source.pop())
# move tower of size n-1 from helper to target
        hanoi(n - 1, helper, source, target)
    

def kurve(x, a, b):   # curve to fit the running times
    return a * np.exp(b * x)

laufzeiten = []
iterations = []
for i in range(n):
    anfang = time.time()
    source = list(reversed(range(1, i+2)))
    print(len(source))
    target = []
    helper = []
    k = 0       # counts the number of iterations = how often hanoi is called
    hanoi(len(source), source, helper, target)
    laufzeiten.append(time.time() - anfang)
    iterations.append(k)

popt, _ = curve_fit(kurve, np.array(range(1, n+1)), np.array(laufzeiten))

fig, ax = plt.subplots(figsize=(12,8))
ax.plot(range(1, n+1), kurve(np.array(range(1, n+1)), popt[0], popt[1]), color='blue', label='Curve to fit running time')
ax.scatter(range(1, n+1), laufzeiten, marker='s', color='green', label='Running time in sec')
ax.tick_params(axis='y', labelcolor='blue')
ax.set_xlabel('Number of pieces in the tower', fontsize=15)
ax.set_ylabel('Running time on iPad in sec', fontsize=15, color='blue')
ax.legend()

ax1 = ax.twinx()
ax1.scatter(range(1, n+1), iterations, marker='>', color='red', label='Iterationen')
ax1.tick_params(labelcolor='red')
ax1.set_ylabel('Number of moves of pieces', fontsize=15, color='red')
fig.tight_layout()
ax1.legend(loc='center left')

print('Curve_fit estimates are a = {:.9f} and b = {:.4f}'.format(popt[0], popt[1]))
print('Target post filled, only for last n: ',target)
print('\n')
print('it took {:.3f} sec to run the program'.format(time.time() - start))

**Comment by Peter230655** [comment] 2023-07-28 14:00
When I run the program below, I getr this error:
_ValueError: cannot compute fingerprint of empty list_
I use numba version 0.57.0

Thanks a lot for any help!
'''
# Tower of Hanoi

n = 25  # Number of rings

start = time.time()

@njit
def hanoi(n, source, helper, target):
    global k
    
    k += 1    # number of iterations through hanoi
    if n > 0:
# move tower of size n-1 from source to helper
        hanoi(n - 1, source, target, helper)
# move disk from source to target
        if source:
            target.append(source.pop())
# move tower of size n-1 from helper to target
        hanoi(n - 1, helper, source, target)
    

def kurve(x, a, b):   # curve to fit the running times
    return a * np.exp(b * x)

laufzeiten = []
iterations = []
for i in range(n):
    anfang = time.time()
    source = list(reversed(range(1, i+2)))
    print(len(source))
    target = []
    helper = []
    k = 0       # counts the number of iterations = how often hanoi is called
    hanoi(len(source), source, helper, target)
    laufzeiten.append(time.time() - anfang)
    iterations.append(k)

popt, _ = curve_fit(kurve, np.array(range(1, n+1)), np.array(laufzeiten))

fig, ax = plt.subplots(figsize=(12,8))
ax.plot(range(1, n+1), kurve(np.array(range(1, n+1)), popt[0], popt[1]), color='blue', label='Curve to fit running time')
ax.scatter(range(1, n+1), laufzeiten, marker='s', color='green', label='Running time in sec')
ax.tick_params(axis='y', labelcolor='blue')
ax.set_xlabel('Number of pieces in the tower', fontsize=15)
ax.set_ylabel('Running time on iPad in sec', fontsize=15, color='blue')
ax.legend()

ax1 = ax.twinx()
ax1.scatter(range(1, n+1), iterations, marker='>', color='red', label='Iterationen')
ax1.tick_params(labelcolor='red')
ax1.set_ylabel('Number of moves of pieces', fontsize=15, color='red')
fig.tight_layout()
ax1.legend(loc='center left')

print('Curve_fit estimates are a = {:.9f} and b = {:.4f}'.format(popt[0], popt[1]))
print('Target post filled, only for last n: ',target)
print('\n')
print('it took {:.3f} sec to run the program'.format(time.time() - start))
'''

**Comment by Peter230655** [comment] 2023-07-28 14:04
When I try to run the program below, I get this error:
ValueError: cannot compute fingerprint of empty list
I use numba version 0.57.0

Any help is greatly appreciated!
```
# Tower of Hanoi

n = 25  # Number of rings

start = time.time()

@njit
def hanoi(n, source, helper, target):
    global k
    
    k += 1    # number of iterations through hanoi
    if n > 0:
# move tower of size n-1 from source to helper
        hanoi(n - 1, source, target, helper)
# move disk from source to target
        if source:
            target.append(source.pop())
# move tower of size n-1 from helper to target
        hanoi(n - 1, helper, source, target)
    

def kurve(x, a, b):   # curve to fit the running times
    return a * np.exp(b * x)

laufzeiten = []
iterations = []
for i in range(n):
    anfang = time.time()
    source = list(reversed(range(1, i+2)))
    print(len(source))
    target = []
    helper = []
    k = 0       # counts the number of iterations = how often hanoi is called
    hanoi(len(source), source, helper, target)
    laufzeiten.append(time.time() - anfang)
    iterations.append(k)

popt, _ = curve_fit(kurve, np.array(range(1, n+1)), np.array(laufzeiten))

fig, ax = plt.subplots(figsize=(12,8))
ax.plot(range(1, n+1), kurve(np.array(range(1, n+1)), popt[0], popt[1]), color='blue', label='Curve to fit running time')
ax.scatter(range(1, n+1), laufzeiten, marker='s', color='green', label='Running time in sec')
ax.tick_params(axis='y', labelcolor='blue')
ax.set_xlabel('Number of pieces in the tower', fontsize=15)
ax.set_ylabel('Running time on iPad in sec', fontsize=15, color='blue')
ax.legend()

ax1 = ax.twinx()
ax1.scatter(range(1, n+1), iterations, marker='>', color='red', label='Iterationen')
ax1.tick_params(labelcolor='red')
ax1.set_ylabel('Number of moves of pieces', fontsize=15, color='red')
fig.tight_layout()
ax1.legend(loc='center left')

print('Curve_fit estimates are a = {:.9f} and b = {:.4f}'.format(popt[0], popt[1]))
print('Target post filled, only for last n: ',target)
print('\n')
print('it took {:.3f} sec to run the program'.format(time.time() - start))
```
