### ISSUE TITLE
Jupyter Notebook Kernel dies when importing njit on Apple M1

### ISSUE THREAD

**Issue by stnatter** [numba/numba#6650] opened 2021-01-19 09:12 UTC
## Reporting a bug

- [x ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello. Importing njit kills the Notebook Kernel.

Installed miniforge along with `Python=3.8.5` on my shiny new Apple M1 MBP. All packages where installed from the conda-forge channel:
NumPy 1.19.5
Numba 0.52
Notebook 6.2.0

In order to get Notebooks working I did this fix:
https://towardsdatascience.com/how-to-run-jupyter-notebooks-on-an-apple-m1-mac-ac3a8bf39c6c

When doing the following the Notebook Kernel dies:
`from numba import njit`

Using ipython shell I get the following:
```
In [1]: import numpy as np

In [2]: from numba import njit
zsh: bus error  ipython
```

**Comment by stuartarchibald** [comment] 2021-01-19 09:27
Thanks for the report. Does running the same two import lines at the python prompt in a shell lead to the same behaviour?

**Comment by stnatter** [comment] 2021-01-19 09:30
```
(base) steffen@Steffens-MBP ~ % python
Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:18:46) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import njit
zsh: bus error  python
(base) steffen@Steffens-MBP ~ % python
Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:18:46) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import prange
zsh: segmentation fault  python
```

**Comment by stuartarchibald** [comment] 2021-01-19 09:36
Thanks @stnatter. If you do `import numpy as np; np.zeros((5,))` does that work? (Just trying to work out where the problem is). Thanks!

**Comment by stnatter** [comment] 2021-01-19 09:41
Yes that does work.
```
>>> import numpy as np
>>> np.zeros((5,))
array([0., 0., 0., 0., 0.])
```
No problem Stuart. Happy to help to resolve this to the best of my abilities.

**Comment by stuartarchibald** [comment] 2021-01-19 09:57
Thanks @stnatter. It looks like it's not a problem loading libraries or executing binaries, which points to perhaps there being something strange about the Numba build.

**Comment by stuartarchibald** [comment] 2021-01-19 10:00
@stnatter are you able to access/use https://gitter.im/numba/numba, it might be easier to discuss in real time and then post the findings here at the end? If not, can carry on here.

**Comment by stnatter** [comment] 2021-01-19 10:15
Can but not really online now. Am UTC+8h. family time now. online later on possibly.

**Comment by stuartarchibald** [comment] 2021-01-19 10:50
> Can but not really online now. Am UTC+8h. family time now. online later on possibly.

Great, thanks, hope to resolve this on there as/when you have time.

**Comment by stuartarchibald** [comment] 2021-01-19 23:29
Resolved in [gitter.im/numba/numba](gitter.im/numba/numba), thanks for assisting @stnatter. For anyone else encountering this problem, Python 3.8.5 (h05baefb_9_cpython ) seems to be problematic, whereas 3.8.6 (3.8.6-h12cc5a1_4_cpython) seems ok.

xref: https://gitter.im/numba/numba?at=600768d5cae490555f55c86f

**Closed by stuartarchibald** 2021-01-19 23:29 UTC
Labels: ISA: ARM, needtriage
