### ISSUE TITLE
Issue with CFFI `from_buffer`, reference to buffer data deleted too early

### ISSUE THREAD

**Issue by garth-wells** [numba/numba#4036] opened 2019-04-29 22:00 UTC
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The below demonstrates an issue when declaring a NumPy array inside a Numba function that passes the array to a CFFI function, using `ffi.from_buffer`. Is the NumPy array is declared outside of the Numba function and passes to the Nunba function, the output is as expected.

At the end is the observed output and the expected output.

I'm using the latest Numba (0.43.1) and cffi (1.12.3) releases.

```python
import numba
import numba.cffi_support
import numpy as np
from cffi import FFI


ffibuilder = FFI()
ffibuilder.cdef("""
    int print_array(int32_t n, const int32_t* data);
""")
ffibuilder.set_source("_test_cffi",
                      """
    int print_array(int32_t n, const int32_t* data)
    {
        for (int i = 0; i < n; ++i)
          printf("val: %d\\n", data[i]);
        return 0;
    }
""")
ffibuilder.compile()
from _test_cffi import ffi, lib
import _test_cffi

numba.cffi_support.register_module(_test_cffi)
print_array = lib.print_array

@numba.jit(nopython=True)
def printer0(n):
    data = np.ones(n, dtype=np.int32)
    print_array(n, ffi.from_buffer(data))

@numba.jit(nopython=True)
def printer1(data):
    print_array(len(data), ffi.from_buffer(data))

printer0(5)
print("----------")
data0 = np.ones(5, dtype=np.int32)
printer1(data0)
```

The output should be all '1', but is: 
```
-555819298
-555819298
-555819298
-555819298
-555819298
----------
1
1
1
1
1
```

**Comment by stuartarchibald** [comment] 2019-04-30 10:49
Thanks for the report. I think that this is due to calling the `cffi` bound function on "deleted" data. Simplifying `printer0` as follows:
```python
def printer0(n):
    dt = dtype=np.int32
    data = np.ones(n, dt)
    buf = ffi.from_buffer(data)
    # data is considered dead here, as there's no further reference to it, so it's reference is deleted
    print_array(n, buf)
```
if the Numba IR is looked at (set env var `NUMBA_DEBUG_FRONTEND=1`):
```
-------------------------------IR DUMP: printer0--------------------------------
label 0:
    n = arg(0, name=n)                       ['n']
    $0.1 = global(np: <module 'numpy' from '<pypath>/site-packages/numpy/__init__.py'>) ['$0.1']
    $0.2 = getattr(value=$0.1, attr=ones)    ['$0.1', '$0.2']
    del $0.1                                 []
    $0.4 = global(np: <module 'numpy' from '<pypath>/site-packages/numpy/__init__.py'>) ['$0.4']
    $0.5 = getattr(value=$0.4, attr=int32)   ['$0.4', '$0.5']
    del $0.4                                 []
    $0.7 = call $0.2(n, func=$0.2, args=[Var(n, issue4036.py (33))], kws=[('dtype', Var($0.5, issue4036.py (33)))], vararg=None) ['$0.2', '$0.5', '$0.7', 'n']
    del $0.5                                 []
    del $0.2                                 []
    data = $0.7                              ['$0.7', 'data']
    del $0.7                                 []
    $0.8 = global(print_array: <built-in method print_array of CompiledLib object at 0x7f4262524688>) ['$0.8']
    $0.10 = global(ffi: <CompiledFFI object at 0x7f424a3d2a40>) ['$0.10']
    $0.11 = getattr(value=$0.10, attr=from_buffer) ['$0.10', '$0.11']
    del $0.10                                []
    $0.13 = call $0.11(data, func=$0.11, args=[Var(data, issue4036.py (33))], kws=(), vararg=None) ['$0.11', '$0.13', 'data']
    del data                                 []  

    # ^------------- data is considered dead, delete it.

    del $0.11                                []
    $0.14 = call $0.8(n, $0.13, func=$0.8, args=[Var(n, issue4036.py (33)), Var($0.13, issue4036.py (34))], kws=(), vararg=None) ['$0.13', '$0.14', '$0.8', 'n'] 

    # ^------------- now make a call to `print_array` with the data that is deleted, prints nonsense

    del n                                    []
    del $0.8                                 []
    del $0.14                                []
    del $0.13                                []
    $const0.15 = const(NoneType, None)       ['$const0.15']
    $0.16 = cast(value=$const0.15)           ['$0.16', '$const0.15']
    del $const0.15                           []
    return $0.16                             ['$0.16']
```
more evidence for this being the issue is found in this "fix" where a `sink` function is used to keep references alive:
```python
import numba
import numba.cffi_support
import numpy as np
from cffi import FFI


ffibuilder = FFI()
ffibuilder.cdef("""
    int print_array(int32_t n, const int32_t* data);
""")
ffibuilder.set_source("_test_cffi",
                      """
    int print_array(int32_t n, const int32_t* data)
    {
        for (int i = 0; i < n; ++i)
          printf("val: %d\\n", data[i]);
        return 0;
    }
""")
ffibuilder.compile()
from _test_cffi import ffi, lib
import _test_cffi

numba.cffi_support.register_module(_test_cffi)
print_array = lib.print_array

@numba.njit
def sink(*args):
    pass

@numba.jit(nopython=True)
def printer0(n):
    data = np.ones(n, dtype=np.int32)
    print_array(n, ffi.from_buffer(data))
    sink(data)

printer0(5)
```
The Numba source itself has the same problem with this similar workaround: https://github.com/numba/numba/blob/e8ac4951affacd25c63ba2c18d62a3f12ed7e0ba/numba/targets/linalg.py#L771-L774

**Comment by jhale** [comment] 2019-04-30 10:54
@stuartarchibald Thanks for your help! I also found the same root issue whilst debugging this with @garth-wells this morning. New MWE:

`import numba
import numba.cffi_support
import numpy as np
from cffi import FFI


ffibuilder = FFI()
ffibuilder.set_source("_test_cffi",
                      """
    void print_array(int64_t n, double* data)
    {
        printf("%p\\n", (void *) &data);
        for (int i = 0; i < n; ++i)
          printf("val: %f\\n", data[i]);
    }
    """)
ffibuilder.cdef("""
    void print_array(int64_t n, double* data);
""")
ffibuilder.compile()
from _test_cffi import ffi, lib
import _test_cffi

numba.cffi_support.register_module(_test_cffi)
print_array = lib.print_array

@numba.jit(nopython=True)
def printer_without_return(n):
    data = np.ones(n, dtype=np.float64)
    p1 = ffi.from_buffer(data)
    print_array(n, p1)
    
@numba.jit(nopython=True)
def printer_with_return(n):
    data = np.ones(n, dtype=np.float64)
    p1 = ffi.from_buffer(data)
    print_array(n, p1)
    return data

printer_without_return(5)
printer_without_return.inspect_types()
print("----------")
printer_with_return(5)
printer_with_return.inspect_types()
`

**Comment by stuartarchibald** [comment] 2019-04-30 11:01
@jhale no problem and good job debugging it :)  If using a function to keep stuff alive is an ok workaround for now then I suggest it is used, Numba CFA needs it but LLVM will optimise it away, it's just a bit quirky. Long term we could perhaps look to extend analysis to handle these cases better.

**Comment by jhale** [comment] 2019-04-30 11:03
Thanks @stuartarchibald. We'll use the workaround. At least this will be hoovered up by Google and people can find the hack now.

**Comment by garth-wells** [comment] 2019-04-30 11:17
Something that also works is
```python
@numba.jit(nopython=True)
def printer0(n):
    data = np.ones(n, dtype=np.int32)
    print_array(n, data.ctypes)
```
rather than
```python
@numba.jit(nopython=True)
def printer0(n):
    data = np.ones(n, dtype=np.int32)
    print_array(n, ffi.from_buffer(data))
```

**Comment by stuartarchibald** [comment] 2019-04-30 11:23
@garth-wells I think you may need to be careful with using `.ctypes` too, the functions in https://github.com/numba/numba/blob/e8ac4951affacd25c63ba2c18d62a3f12ed7e0ba/numba/targets/linalg.py use ctypes bindings but also need calls to sink functions to defeat liveness analysis. At least now it's clear what the problem is in the presented use cases and it's relatively clear what to look for in the IR.

**Comment by stuartarchibald** [comment] 2019-09-11 14:50
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:50 UTC
Labels: no action required
