### ISSUE TITLE
cannot determine Numba type of <class 'function'>

### ISSUE THREAD

**Issue by Quintell** [numba/numba#4642] opened 2019-10-01 11:23 UTC
I am trying to run a function in parallel mode.
It is iterating over elements from a list and performing some operations. Since the elements and operations are independent of each other, the operations can be done in parallel, however when i go to compile it(i am using spyder btw) using @njit(parallel= True), I am getting an error saying that 'cannot determine Numba type of <class 'function'>'

The loop which is doing the iteration has functions like:
1. Addition
2. Division and Multiplication
3. np.cross(cross product)
4. np. array
5. Calling functions that are defined earlier(outside @njit)

The error dump is pasted below:
```
runfile('C:/Users/Arghyadeep/Desktop/p1.py', wdir='C:/Users/Arghyadeep/Desktop')
Traceback (most recent call last):

  File "<ipython-input-38-1f08c1876264>", line 1, in <module>
    runfile('C:/Users/Arghyadeep/Desktop/p1.py', wdir='C:/Users/Arghyadeep/Desktop')

  File "C:\Users\Arghyadeep\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Arghyadeep\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Arghyadeep/Desktop/p1.py", line 73, in <module>
    parallelBoris(10)

  File "C:\Users\Arghyadeep\Anaconda3\lib\site-packages\numba\dispatcher.py", line 376, in _compile_for_args
    error_rewrite(e, 'typing')

  File "C:\Users\Arghyadeep\Anaconda3\lib\site-packages\numba\dispatcher.py", line 343, in error_rewrite
    reraise(type(e), e, None)

  File "C:\Users\Arghyadeep\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)

TypingError: cannot determine Numba type of <class 'function'>
```

**Comment by esc** [comment] 2019-10-01 13:07
@Quintell thanks for reporting this on the Numba issue tracker. I will reformat your post using syntax highlighting. For future posts, please consider reading https://help.github.com/en/categories/writing-on-github . thanks!

**Comment by esc** [comment] 2019-10-01 13:09
@Quintell I looked at the backtrace and unfortunately I am unable to diagnose the source of the error. Would it be possible to post either the code you are working with or a minimal reproducer of the issue that you are encountering. For more information about creating such a reproducer, please see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by stuartarchibald** [comment] 2019-10-01 13:13
Did you do something like:
```pycon
In [1]: from numba import njit                                                                                                  

In [2]: def foo(x): 
   ...:     return x + 1 
   ...:                                                                                                                         

In [3]: @njit 
   ...: def call_foo(y): 
   ...:     return foo(y) 
   ...:                                                                                                                         

In [4]: call_foo(10)                

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'foo': cannot determine Numba type of <class 'function'>

File "<ipython-input-3-8c790192a815>", line 3:
def call_foo(y):
    return foo(y)
    ^                                                                                            
```
the root cause of which is that the functions *called* by `@jit` decorated functions also need to be `@jit` decorated. i.e.
```pycon
In [1]: from numba import njit                                                                                                  

In [2]: @njit 
   ...: def foo(x): 
   ...:     return x + 1 
   ...:                                                                                                                         

In [3]: @njit 
   ...: def call_foo(y): 
   ...:     return foo(y) 
   ...:                                                                                                                         

In [4]: call_foo(10)                                                                                                            
Out[4]: 11
```

**Comment by Quintell** [comment] 2019-10-03 07:10
@esc  and @stuartarchibald Thank you for your help. The problem was what @stuartarchibald  mentioned. I decorated all the functions with **@jit** and then it compiled fine. There was a problem with **@njit** and i have yet to figure it out.
My next issue is **'file handling'**. File handling is not supported in numba, and I need to get some output saved from the loop that is decorated with **@jit** what are my options.??
Thanking you in advance

**Comment by esc** [comment] 2019-10-03 07:38
@Quintell there are two options that I can see. One is, that you use an object mode block (https://numba.pydata.org/numba-doc/latest/user/withobjmode.html)  to write to a file during a loop in an `njit`ed function. The other is that you accumulate your output while executing your `njit` function, for example in a typed dictionary or list (https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#typed-list) and return that from the function. Then, from your original calling function write the returned output dict or list to a file.

**Comment by Quintell** [comment] 2019-10-03 07:44
@esc  Okay I shall try that

**Comment by stuartarchibald** [comment] 2019-10-04 09:49
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-10-04 09:49 UTC
Labels: no action required
