### ISSUE TITLE
Split inside a list comprehension NotImplementedError

### ISSUE THREAD

**Issue by asjir** [numba/numba#4312] opened 2019-07-12 12:02 UTC
I get NotImplementedError with the following code: 
(it obviously runs when iterating instead of using a list comprehension)

```python
@jit
def hmm(ss):
    res = [s.split(' ') for s in ss]
    return res
```

e.g. run on
```python
ss = ['aws',  'big data']
```

### Traceback

<details>

```python-traceback
NotImplementedError                       Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    490     try:
--> 491         yield
    492     except NumbaError as e:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/objmode.py in lower_inst(self, inst)
     64         if isinstance(inst, ir.Assign):
---> 65             value = self.lower_assign(inst)
     66             self.storevar(value, inst.target.name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/objmode.py in lower_assign(self, inst)
    158         elif isinstance(value, ir.Expr):
--> 159             return self.lower_expr(value)
    160         elif isinstance(value, ir.Global):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/objmode.py in lower_expr(self, expr)
    372         else:
--> 373             raise NotImplementedError(expr)
    374 

NotImplementedError: make_function(name=$const0.2, code=<code object <listcomp> at 0x7f35d7c5c660, file "/home/ec2-user/SageMaker/funs/helper_functions.py", line 94>, closure=None, defaults=None)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-5-b9244bd6d598> in <module>()
----> 1 sort(ss)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    358                     e.patch_message(''.join(e.args) + help_msg)
    359             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 360             raise e
    361 
    362     def inspect_llvm(self, signature=None):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    309                 argtypes.append(self.typeof_pyval(a))
    310         try:
--> 311             return self.compile(tuple(argtypes))
    312         except errors.TypingError as e:
    313             # Intercept typing error that may be due to an argument

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    616 
    617                 self._cache_misses[sig] += 1
--> 618                 cres = self._compiler.compile(args, return_type)
    619                 self.add_overload(cres)
    620                 self._cache.save_overload(sig, cres)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    869     pipeline = pipeline_class(typingctx, targetctx, library,
    870                               args, return_type, flags, locals)
--> 871     return pipeline.compile_extra(func)
    872 
    873 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    363         self.lifted = ()
    364         self.lifted_from = None
--> 365         return self._compile_bytecode()
    366 
    367     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    800         """
    801         assert self.func_ir is None
--> 802         return self._compile_core()
    803 
    804     def _compile_ir(self):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    787         self.define_pipelines(pm)
    788         pm.finalize()
--> 789         res = pm.run(self.status)
    790         if res is not None:
    791             # Early pipeline completion

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    249                     # No more fallback pipelines?
    250                     if is_final_pipeline:
--> 251                         raise patched_exception
    252                     # Go to next fallback pipeline
    253                     else:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    241                 try:
    242                     event(stage_name)
--> 243                     stage()
    244                 except _EarlyPipelineCompletion as e:
    245                     return e.result

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    648         """
    649         lowerfn = self.backend_object_mode
--> 650         self._backend(lowerfn, objectmode=True)
    651 
    652         # Warn if compiled function in object mode and force_pyobject not set

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    624             self.library.enable_object_caching()
    625 
--> 626         lowered = lowerfn()
    627         signature = typing.signature(self.return_type, *self.args)
    628         self.cr = compile_result(

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in backend_object_mode(self)
    597                                      self.library,
    598                                      self.func_ir,
--> 599                                      self.flags)
    600 
    601     def backend_nopython_mode(self):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
   1014         )
   1015     lower = objmode.PyLower(targetctx, library, fndesc, interp)
-> 1016     lower.lower()
   1017     if not flags.no_cpython_wrapper:
   1018         lower.create_cpython_wrapper()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    133         if self.generator_info is None:
    134             self.genlower = None
--> 135             self.lower_normal_function(self.fndesc)
    136         else:
    137             self.genlower = self.GeneratorLower(self)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    174         # Init argument values
    175         self.extract_function_arguments()
--> 176         entry_block_tail = self.lower_function_body()
    177 
    178         # Close tail of entry block

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    199             bb = self.blkmap[offset]
    200             self.builder.position_at_end(bb)
--> 201             self.lower_block(block)
    202 
    203         self.post_lower()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    214             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 
    218     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    497         from numba import config
    498         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 499         six.reraise(type(newerr), newerr, tb)
    500 
    501 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed at object (object mode backend)
make_function(name=$const0.2, code=<code object <listcomp> at 0x7f35d7c5c660, file "/home/ec2-user/SageMaker/funs/helper_functions.py", line 94>, closure=None, defaults=None)

File "funs/helper_functions.py", line 94:
def sort(ss):
    res = [' '.join(sorted(s.split(' '))) for s in ss]
    ^
[1] During: lowering "$0.3 = make_function(name=$const0.2, code=<code object <listcomp> at 0x7f35d7c5c660, file "/home/ec2-user/SageMaker/funs/helper_functions.py", line 94>, closure=None, defaults=None)" at /home/ec2-user/SageMaker/funs/helper_functions.py (94)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If you need help writing a minimal reproducer please see:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
</details>

**Comment by stuartarchibald** [comment] 2019-07-12 15:42
Thanks for the report. I cannot reproduce this on Numba 0.44.1 (latest released version), which version are you using?

**Comment by stuartarchibald** [comment] 2020-09-10 19:56
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-10 19:56 UTC
Labels: needtriage
