### ISSUE TITLE
Numpy.dot o

### ISSUE THREAD

**Issue by drlagos** [numba/numba#2944] opened 2018-05-04 10:07 UTC
Problem: numpy dot is throwing an exception, but the docs say it is supported.

Numba version: 0.38.0

Minimal Example:

```
import numpy as np
from numba import jit

@jit(nopython=True)
def matmul2(size: int):
    a = np.random.random((size, size))
    b = np.random.random((size, size))
    return a.dot(b)
```

Expected: Should work
Actual Result: Exception

```
Traceback (most recent call last):
  File "test.py", line 209, in <module>
    matmul2(1000)
  File "C:\Program Files\Python36\Lib\site-packages\numba\dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "C:\Program Files\Python36\Lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'dot' of type array(float64, 2d, C)

File "test.py", line 204:
def matmul2(size: int):
    <source elided>
    b = np.random.random((size, size))
    return a.dot(b)
    ^

[1] During: typing of get attribute at test.py (204)

File "test.py", line 204:
def matmul2(size: int):
    <source elided>
    b = np.random.random((size, size))
    return a.dot(b)
    ^
```

**Comment by drlagos** [comment] 2018-05-04 10:09
If instead I use np.dot(a, b) I get a different error:

`scipy 0.16+ is required for linear algebra`

But the dot operator should give the same result

**Comment by stuartarchibald** [comment] 2018-05-04 10:47
Thanks for the report. This is because `numpy.ndarray.dot` is not yet supported, hence:
```
Unknown attribute 'dot' of type array(float64, 2d, C)
```
whereas `np.dot` is supported but needs `SciPy` to be installed to provide the necessary BLAS routines as noted in https://github.com/numba/numba/issues/2944#issuecomment-386558108. See http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#linear-algebra for supported linear algebra routines.

As this was a quick fix, it's done here: https://github.com/numba/numba/pull/2946

**Comment by drlagos** [comment] 2018-05-04 11:44
Ok, makes sense, though it would be nice if the documentation made clear that the method call style is not supported yet (I at least didn't realize a.dot(b) was any different from np.dot(a, b)).

Glad to see there is a fix just waiting to be merged :)

**Comment by stuartarchibald** [comment] 2018-05-04 12:03
I think this is in the documentation? The supported methods on the NumPy array type are declared here: http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#calculation and here: http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#other-methods

With Numba 0.38 you should have got an error with a help message like this, with reference to those links:
```python
Unknown attribute 'dot' of type array(float64, 2d, C)

File "issue2944.py", line 6:
def matmul2(a, b):
    return a.dot(b)
    ^

[1] During: typing of get attribute at issue2944.py (6)

File "issue2944.py", line 6:
def matmul2(a, b):
    return a.dot(b)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
Did that not happen? If so, I'd really like to know about it because it should have appeared! If it did happen, is there something you feel that could be done to improve usability?

 Thanks.

**Comment by drlagos** [comment] 2018-05-04 12:14
No, that did appear, I excluded it from my bug report up there to make it shorter. 

The problem is that while the message is helpful, it just says "it is caused by an unsupported feature" which is correct, but the unsupported feature happens to be a trivial method call that should map to np.dot(), which is fully supported and hence the situation is confusing.

I'm sure people intimately familiar with numpy will understand that numpy.dot and numpy.ndarray.dot are different things but I didn't and my colleagues were quite surprised as well. If your quick fix is not accepted, a little snipped saying "the method call form of numpy operations is not supported" would be quite helpful in the documentation.

**Comment by stuartarchibald** [comment] 2018-05-04 12:26
This is really helpful feedback, thanks. It's got me thinking about whether it is possible to infer from the error context more about the problem and actually detect that e.g.
 * it is a `ndarray`
 * it is a method call on an `ndarray`, and then point explicitly to documentation for that
 * the problem is the method `dot` and highlight that more.

I'll work on the patch that fixes this until it is accepted, this method should work!!! :)

**Comment by drlagos** [comment] 2018-05-04 12:39
Great! Should I close this issue?

**Comment by stuartarchibald** [comment] 2018-05-04 12:42
No problem. The merge of https://github.com/numba/numba/pull/2946 will automatically close it.

**Closed** 2018-05-04 14:15 UTC
