### ISSUE TITLE
numba list type undecided

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#3870] opened 2019-03-15 10:20 UTC
I try to use list  to get results from numba jist function but I have below error.

```

 def Search(compare_desc , USER , _desc , _names): ### LIST
    tupZ = [['lucky', 18.265, 100, 0.1]]

    for x in range(_names.shape[0]):
        dist = np.sum(np.square(compare_desc - _desc[x]))
        

        if dist < 1.00:
            tmp_tup = [x, float(dist), x, sim]
            tupZ = tupZ.append(tmp_tup)
return tupz

```

it says : 

Failed in nopython mode pipeline (step: nopython frontend)
Undecided type $84.9 := <undecided>
[1] During: resolving caller type: $84.9
[2] During: typing of call at /-RemoteCamMultidb.py (111)

<source elided>
            tupZ = tupZ.append(tmp_tup)
            ^

how can I use list and append new list in jit

**Comment by stuartarchibald** [comment] 2019-03-15 11:04
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

**Comment by stuartarchibald** [comment] 2019-03-15 11:15
Here's an example of something that might help...
```python
from numba import njit
import numpy as np

@njit
def Search(compare_desc , USER , _desc , _names): ### LIST
    tupZ = [('lucky', 18.265, 100, 0.1)]

    for x in range(_names.shape[0]):
        dist = np.sum(np.square(compare_desc - _desc[x]))

        if dist < 1.00:
            a_string = 'somename'
            a_float = 1.23
            an_int = x
            small_float = 0.2
            tupZ.append((a_string, a_float, an_int, small_float))

    return tupZ

compare_desc = np.zeros(10,)
desc = np.zeros(10,)
names = np.zeros(10,)

res = Search(compare_desc, 'foo', desc, names)
print(res)
```

**Comment by MyraBaba** [comment] 2019-03-15 11:39
above example gave below error:

`  raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in nopython mode pipeline (step: nopython mode backend)
LLVM IR parsing error
<string>:199:110: error: invalid use of function-local name
  %"extracted.f0" = extractvalue {{i8*, i64, i32, i8*, i8*}, double, i64, double} {{i8*, i64, i32, i8*, i8*} %".61", double 0x403243d70a3d70a4, i64 100, double 0x3fb999999999999a}, 0
                  `

**Comment by stuartarchibald** [comment] 2019-03-15 11:43
Which version of Numba and llvmlite do you have? The above worked for me with conda packages of version 0.43 and 0.28 respectively.

**Comment by MyraBaba** [comment] 2019-03-15 11:45
0.42.0    0.27.0
I will update numba now.

and let you know...

**Comment by MyraBaba** [comment] 2019-03-15 12:15
your example worked perfectly.

but program gave error again which is none sense :(

Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of BoundFunction(list.append for list((unicode_type, float64, int64, float64))) with parameters (([unichr x 35], float32, int64, float32))
 * parameterized
[1] During: resolving callee type: BoundFunction(list.append for list((unicode_type, float64, int64, float64)))
[2] During: typing of call at /-RemoteCamMultidb.py (140)


File "_mqt_production-RemoteCamMultidb.py", line 140:
def SearchPeople_2(compare_desc, USER, people_desc, people_names):
    <source elided>
            small_float = sim
            tupZ.append((a_string, a_float, an_int, small_float))

**Comment by stuartarchibald** [comment] 2019-03-15 12:24
It's really hard to work out what the problem is without being able to see the code and input that produced it, please provide a working sample code that produces this error.

Without this, I'd guess that the problem is described here:
```
Invalid use of BoundFunction(list.append for list((unicode_type, float64, int64, float64))) with parameters (([unichr x 35], float32, int64, float32))
```
the code is doing a `list.append` with an argument of type `([unichr x 35], float32, int64, float32)` but the list was originally used with a type `(unicode_type, float64, int64, float64)`.

**Comment by stuartarchibald** [comment] 2019-03-15 12:24
If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by MyraBaba** [comment] 2019-03-15 13:15
here the minimal example : 

```
`from numba import njit
import numpy as np
import numba
import llvmlite

print(numba.__version__ , "  " , llvmlite.__version__)

@njit
def Search(compare_desc , USER , _desc , _names): ### LIST
    tupZ = [('lucşky', 18.265, 100, 0.1)]

    for x in range(_names.shape[0]):
        dist = np.sum(np.square(compare_desc - _desc[x]))

        if dist < 1.00:
            a_string = names[x]
            a_float = 1.23
            an_int = x
            small_float = 0.2
            tupZ.append((a_string, a_float, an_int, small_float))

    return tupZ

compare_desc = np.zeros(10,)
desc = np.zeros(10,)
#names = np.zeros(10,)
names = np.asarray(['testtste','julis' , 'mnerty' , 'tired' , 'really'])

res = Search(compare_desc, 'foo', desc, names)
print(res)`
```

**Comment by stuartarchibald** [comment] 2019-03-15 13:28
Thanks. The issue is that storing the `names` as a NumPy array of strings and then accessing each element means each element of the array is considered as different length of unicode characters as a type, which is a) really hard to deal with and b) not compatible with the unicode_type `'lucsky'` in the original list definition:

This works:

```python
from numba import njit
import numpy as np
import numba
import llvmlite

print(numba.__version__ , "  " , llvmlite.__version__)

@njit
def Search(compare_desc , USER , _desc , _names): ### LIST
    tupZ = [('lucşky', 18.265, 100, 0.1)]

    for x in range(len(_names)): # switch this to use the tuple length
        dist = np.sum(np.square(compare_desc - _desc[x]))

        if dist < 1.00:
            a_string = names[x]
            a_float = 1.23
            an_int = x
            small_float = 0.2
            tupZ.append((a_string, a_float, an_int, small_float))

    return tupZ

compare_desc = np.zeros(10,)
desc = np.zeros(10,)
#names = np.zeros(10,)
names = ('testtste','julis' , 'mnerty' , 'tired' , 'really') # make this a tuple of unicode strings

res = Search(compare_desc, 'foo', desc, names)
print(res)

```

**Comment by stuartarchibald** [comment] 2019-03-21 15:48
Assuming resolved. Closing.

**Closed by stuartarchibald** 2019-03-21 15:48 UTC
Labels: no action required
