### ISSUE TITLE
numba.tests() reports many failures on osx-32

### ISSUE THREAD

**Issue by cournape** [numba/numba#332] opened 2013-08-20 10:31 UTC
I am seeing a lot of errors in the test suite on osx-32. My environment:

  - llvm 3.2
  - llvmmath 0.1.1
  - mac os x 10.6

I don't see those failures in the same environment on osx-64 (or other platforms).

```
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_raise                                                 FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_recursion                                             FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_redefine                                              SUCCESS
[localhost:2223] out: numba.tests.test_reporting                                             SUCCESS
[localhost:2223] out: numba.tests.test_rshift                                                FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_slicing                                               FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_strings                                               FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_struct                                                FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_sum                                                   FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: s--------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_tuple                                                 FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_types                                                 FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_unbound_variables                                     FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_unpacking                                             FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_unsigned_arith                                        FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_while                                                 FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.test_withpython                                            FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_array_expressions                         FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_array_math                                FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_broadcasting                              FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: test (__main__)
[localhost:2223] out: Doctest: __main__.test ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_slicing                                   FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: test_slicing (__main__)
[localhost:2223] out: Doctest: __main__.test_slicing ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_slicing2                                  FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.array_exprs.test_vmdot                                     FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_abs                                  FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: __main__ ()
[localhost:2223] out: Doctest: __main__ ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_chr                                  FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_complex                              FAILED:
[localhost:2223] out:                                                                          SIGBUS
[localhost:2223] out: __main__ ()
[localhost:2223] out: Doctest: __main__ ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_enumerate                            FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: convert_target_enumerate (__main__.__test__)
[localhost:2223] out: Doctest: __main__.__test__.convert_target_enumerate ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_float                                FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: __main__ ()
[localhost:2223] out: Doctest: __main__ ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_int                                  FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: __main__ ()
[localhost:2223] out: Doctest: __main__ ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_minmax                               FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: max1 (__main__.__test__)
[localhost:2223] out: Doctest: __main__.__test__.max1 ... --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_ord                                  FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: --------------------------------------------------------------------------------
[localhost:2223] out: numba.tests.builtins.test_builtin_pow                                  FAILED:
[localhost:2223] out:                                                                         SIGSEGV
[localhost:2223] out: __main__ ()
```

**Comment by pitrou** [comment] 2015-05-26 14:30
Sorry that this report didn't see any answer. In any case, the issue is outdated, so I'm closing.

**Closed by pitrou** 2015-05-26 14:30 UTC
