### ISSUE TITLE
Memory leak !!! Please give me a hand

### ISSUE THREAD

**Issue by John-Farseer** [numba/numba#6190] opened 2020-08-30 15:32 UTC
```
@jit(nopython=True)  
def itertools_combinations(pool, r):
    n = len(pool)
    indices = list(range(r))
    empty = not(n and (0 < r <= n))

    if not empty:
        result = [pool[i] for i in indices]
        yield result

    while not empty:
        i = r - 1
        while i >= 0 and indices[i] == i + n - r:
            i -= 1
        if i < 0:
            empty = True
        else:
            indices[i] += 1
            for j in range(i+1, r):
                indices[j] = indices[j-1] + 1

            result = [pool[i] for i in indices]
            yield result
```
### the above function _itertools_combinations( , )_ is the same as itertools.combinations( , ), and will be used in the following function _corr_feature_map_.

```
@jit(nopython=True)
def corr_feature_map(input_single, kernel_size, strides):
    row_width = input_single.shape[0]
    column_width = input_single.shape[1]
    column_slices = int((column_width-kernel_size)/strides)
    
    iteration = list(itertools_combinations(np.arange(row_width), 2))  # https://www.e-learn.cn/topic/3707881
    feature_map = []
    for i,j in iteration:
        corr_list = []
        for k in range(column_slices+1):
            data_1 = input_single[i, k*strides:k*strides+kernel_size]
            data_2 = input_single[j, k*strides:k*strides+kernel_size]
            if np.max(data_1)==np.min(data_1) or np.max(data_2)==np.min(data_2): 
                corr_coef = 0
            else:
                corr_coef = np.corrcoef(data_1, data_2)[0, 1]
            corr_list.append(corr_coef)
        feature_map.append(corr_list)
   
    return feature_map
```
### The point is that if I use @jit(nopython=True) to accelerate the function, the result is that the running speed is very fast, but the memory footprint increases significantly; if I don’t use @jit(nopython=True), the speed is much slower, but the memory Occupy is much less, there is a contradiction between speed and memory usage, I guess it should be a memory leak problem. Please help me, thank you! ! !

**Comment by gmarkall** [comment] 2020-08-31 06:52
The memory footprint will be larger when you use Numba because it has to import a fair amount of library code including LLVM. For example, if I use `pmap` to view the memory usage after starting the Python interpreter, I get:

```
$ sudo pmap <python pid>
...
 total            26892K
```

After running `import numba`, the output is:

```
$ sudo pmap <python pid>
...
 total           331148K
```

Just seeing an increase in memory footprint doesn't indicate a memory leak. Do you find that memory usage grows over time? If so, could you post a self-contained executable code listing that can be use to reproduce the problem please?

**Comment by John-Farseer** [comment] 2020-08-31 12:13
### Firstly, thank you very much for your kind reply!
### Secondly, each time I use the _corr_feature_map_ function(accelerated by @jit(nopython=True)), the memory usage will increase once.
### Thirdly, we can have a trial as the following:
```
X_train = np.random.randn(100, 19, 30)
X_train

def try_try(inputs):
    for i in range(inputs.shape[0]):
        input_single = inputs[i]
        feature_map = corr_feature_map(input_single, 10, 10)
        
try_try(X_train)
```
### As you can see, _try_try_ function only call the _corr_feature_map_ function, and did not return any global variables, but my memory  useage increased by about 3MB when I run the above codes once. In my project, X_train's size is like (70000, 19, 30), so it stongly increases my memory useage. So sad!

**Comment by John-Farseer** [comment] 2020-08-31 12:17
@gmarkall 
### Firstly, thank you very much for your kind reply!
### Secondly, each time I use the corr_feature_map function(accelerated by @jit(nopython=True)), the memory usage will increase once.
### Thirdly, we can have a trial as the following:
```
X_train = np.random.randn(100, 19, 30)
X_train

def try_try(inputs):
    for i in range(inputs.shape[0]):
        input_single = inputs[i]
        feature_map = corr_feature_map(input_single, 10, 10)
  
try_try(X_train)
```
### As you can see, try_try function only call the corr_feature_map function, and did not return any global variables, but my memory useage increased by about 3MB when I run the above codes once. In my project, X_train's size is like (70000, 19, 30), so it stongly increases my memory useage. So sad!

**Comment by sklam** [comment] 2020-08-31 19:45
I can confirm that the problem is coming from the generator (`itertools_combinations`). I modify the function to make it return a `list` directly and the problem leak goes away:

```python

@njit
def itertools_combinations_to_list(pool, r):
    out = []
    n = len(pool)
    indices = list(range(r))
    empty = not (n and (0 < r <= n))

    if not empty:
        result = [pool[i] for i in indices]
        out.append(result)

    while not empty:
        i = r - 1
        while i >= 0 and indices[i] == i + n - r:
            i -= 1
        if i < 0:
            empty = True
        else:
            indices[i] += 1
            for j in range(i + 1, r):
                indices[j] = indices[j - 1] + 1

            result = [pool[i] for i in indices]
            out.append(result)
    return out
```

<details>
<summary>modified code to suppress leak in generator</summary>

```python
from numba import njit
from numba.core.runtime.nrt import rtsys
import numpy as np


@njit
def itertools_combinations(pool, r):
    n = len(pool)
    indices = list(range(r))
    empty = not (n and (0 < r <= n))

    if not empty:
        result = [pool[i] for i in indices]
        yield result

    while not empty:
        i = r - 1
        while i >= 0 and indices[i] == i + n - r:
            i -= 1
        if i < 0:
            empty = True
        else:
            indices[i] += 1
            for j in range(i + 1, r):
                indices[j] = indices[j - 1] + 1

            result = [pool[i] for i in indices]
            yield result


@njit
def itertools_combinations_to_list(pool, r):
    out = []
    n = len(pool)
    indices = list(range(r))
    empty = not (n and (0 < r <= n))

    if not empty:
        result = [pool[i] for i in indices]
        out.append(result)

    while not empty:
        i = r - 1
        while i >= 0 and indices[i] == i + n - r:
            i -= 1
        if i < 0:
            empty = True
        else:
            indices[i] += 1
            for j in range(i + 1, r):
                indices[j] = indices[j - 1] + 1

            result = [pool[i] for i in indices]
            out.append(result)
    return out

@njit
def corr_feature_map(input_single, kernel_size, strides):
    row_width = input_single.shape[0]
    column_width = input_single.shape[1]
    column_slices = int((column_width - kernel_size) / strides)

    iteration = itertools_combinations(np.arange(row_width), 2)
      # https://www.e-learn.cn/topic/3707881
    feature_map = []
    for i, j in iteration:
        corr_list = []
        for k in range(column_slices + 1):
            data_1 = input_single[i, k * strides : k * strides + kernel_size]
            data_2 = input_single[j, k * strides : k * strides + kernel_size]
            if np.max(data_1) == np.min(data_1) or np.max(data_2) == np.min(data_2):
                corr_coef = 0
            else:
                corr_coef = np.corrcoef(data_1, data_2)[0, 1]
            corr_list.append(corr_coef)
        feature_map.append(corr_list)

    return feature_map


np.random.seed(0)
X_train = np.random.randn(100, 19, 30)


def try_try(inputs):
    for i in range(inputs.shape[0]):
        input_single = inputs[i]
        feature_map = corr_feature_map(input_single, 10, 10)
        stats = rtsys.get_allocation_stats()
        print(stats.alloc - stats.free)

try_try(X_train)
```
</details>

**Comment by John-Farseer** [comment] 2020-09-01 03:02
@sklam 
### So nice! It works! Thanks for your professional and enthusiastic answer.
### The story is that, _itertools.combinations( , )_ function is not supported by ```@njit``` so I copied the codes from [https://www.e-learn.cn/topic/3707881](url) to achieve the same effect. I conjectured that _itertools_combinations( , )_ is not very complicated, so I never thought that the problem was here. Even I have noticed that I don’t understand the role of ```yield``` in _itertools_combinations( , )_, but I didn't diagnose it. I feel sorry for my unprofessionalism and carelessness, Hahahaha.
### Thanks again!

**Comment by stuartarchibald** [comment] 2020-09-01 09:13
Is this related/same root cause as the numerous "generators leak" tickets? Either leaking objects or the LLVM compiled code immortality issue?

**Comment by gmarkall** [comment] 2020-09-01 15:11
Generator leak-related issues: #5350 #3451 #1278 #1807 #5427.

Closing this issue as a duplicate.

**Closed by gmarkall** 2020-09-01 15:11 UTC
Labels: bug - memory leak
