### ISSUE TITLE
Error with  Moran_Local()

### ISSUE THREAD

**Issue by niteshshah12** [numba/numba#6842] opened 2021-03-18 17:11 UTC
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Operands must be the same type, got (i64, i32)

File "C:\Users\nshah12\Anaconda3\lib\site-packages\esda\crand.py", line 61:
def vec_permutations(max_card: int, n: int, k_replications: int, seed: int):
    <source elided>
    np.random.seed(seed)
    result = np.empty((k_replications, max_card), dtype=np.int64)
    ^

[1] During: lowering "$0.14 = call $0.7($0.10, func=$0.7, args=[Var($0.10, C:\Users\nshah12\Anaconda3\lib\site-packages\esda\crand.py (61))], kws=[('dtype', Var($0.12, C:\Users\nshah12\Anaconda3\lib\site-packages\esda\crand.py (61)))], vararg=None)" at C:\Users\nshah12\Anaconda3\lib\site-packages\esda\crand.py (61)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by esc** [comment] 2021-03-18 17:44
@niteshshah12 thank you for submitting this to the issue tracker. Numba version 0.53.0 has recently been released, I would suggest to first try updating to that version to be sure.

**Comment by stuartarchibald** [comment] 2021-03-19 17:55
This was reported previously and resolved here: https://github.com/numba/numba/issues/6059#issuecomment-667930911, essentially, the root cause of the problem in Numba has been fixed and updating to the latest Numba (0.53) should permit it to work fine. Am going to close this as a duplicate, if updating doesn't fix it please do reopen with any new information. Many Thanks!

**Closed by stuartarchibald** 2021-03-19 17:55 UTC
Labels: needtriage
