### ISSUE TITLE
Internal Type Detection Failure?

### ISSUE THREAD

**Issue by TNonet** [numba/numba#4704] opened 2019-10-15 02:31 UTC
Python: 3.7.3
Numba: 0.44.1 and 0.45.1
Numpy: 1.16.1

```python
from numba import jit
import numpy as np
@jit(nopython=True)
def test1(m, k):
    np.zeros((m, k))

```
Tests
```python
test1(10,10) # runs fine
test1(np.uint64(10), np.uint64(10)) # runs fine
```
```python-traceback
test1(np.uint32(10), np.uint32(10)) # throws nasty error
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/numba/errors.py", line 661, in new_error_context
    yield
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 459, in lower_assign
    return self.lower_expr(ty, value)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 918, in lower_expr
    res = self.lower_call(resty, expr)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 711, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 890, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "//anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1132, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "//anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1157, in wrapper
    return fn(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 3373, in numpy_zeros_nd
    ary = _empty_nd_impl(context, builder, arrtype, shapes)
  File "//anaconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 3260, in _empty_nd_impl
    arrlen = builder.mul(arrlen, s)
  File "//anaconda3/lib/python3.7/site-packages/llvmlite/ir/builder.py", line 24, in wrapped
    % (lhs.type, rhs.type))
ValueError: Operands must be the same type, got (i64, i32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
    raise e
  File "//anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "//anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 747, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 674, in backend_nopython_mode
    self.metadata)
  File "//anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1124, in native_lowering_stage
    lower.lower()
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "//anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "//anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "//anaconda3/lib/python3.7/site-packages/numba/errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "//anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Operands must be the same type, got (i64, i32)

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

[1] During: lowering "$0.6 = call $0.2($0.5, func=$0.2, args=[Var($0.5, <stdin> (3))], kws=(), vararg=None)" at <stdin> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
This error just started popping up for me.
Similar errors happen with:
zeros
ones
empty

**Comment by stuartarchibald** [comment] 2019-10-15 11:28
Thanks for the report. This is a known issue, there's a stalled but present WIP PR to create a patch to fix this here: https://github.com/numba/numba/pull/3505

The problem is that at present the allocator routines, e.g. zeros, only accept machine size signed integers as arguments.

**Comment by stuartarchibald** [comment] 2019-10-15 11:28
Duplicate of https://github.com/numba/numba/issues/2758 closing.

**Closed by stuartarchibald** 2019-10-15 11:28 UTC
Labels: bug, duplicate
