### ISSUE TITLE
ParallelAccelerator sequential lowering typemap out of sync with IR

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3161] opened 2018-07-25 17:26 UTC
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Caching should in principle work for ParallelAccelerator optimized functions without a threading backend.  However, it fails as shown by the following example. I'm on master ff1eaec52b659ee30e1fa0ff4920d06c60cb99c8.

```python
import numba
import numpy as np

numba.parfor.sequential_parfor_lowering = True

@numba.njit(parallel=True, cache=True)
def calc_pi(n):
    x = 2*np.random.ranf(n)-1
    y = 2*np.random.ranf(n)-1
    return 4*np.sum(x**2+y**2<1)/n

calc_pi(100)
```

```
Traceback (most recent call last):
  File "examples/pi.py", line 17, in <module>
    calc_pi(100)
  File "/home/etotoni/pse-hpc/python/numba/numba/dispatcher.py", line 368, in _compile_for_args
    raise e
  File "/home/etotoni/pse-hpc/python/numba/numba/dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/etotoni/pse-hpc/python/numba/numba/dispatcher.py", line 655, in compile
    self._cache.save_overload(sig, cres)
  File "/home/etotoni/pse-hpc/python/numba/numba/caching.py", line 665, in save_overload
    self._save_overload(sig, data)
  File "/home/etotoni/pse-hpc/python/numba/numba/caching.py", line 674, in _save_overload
    data = self._impl.reduce(data)
  File "/home/etotoni/pse-hpc/python/numba/numba/caching.py", line 400, in reduce
    return cres._reduce()
  File "/home/etotoni/pse-hpc/python/numba/numba/compiler.py", line 89, in _reduce
    typeann = str(self.type_annotation)
  File "/home/etotoni/pse-hpc/python/numba/numba/annotations/type_annotations.py", line 272, in __str__
    return self.annotate()
  File "/home/etotoni/pse-hpc/python/numba/numba/annotations/type_annotations.py", line 116, in annotate
    groupedinst = self.prepare_annotations()
  File "/home/etotoni/pse-hpc/python/numba/numba/annotations/type_annotations.py", line 100, in prepare_annotations
    atype = self.typemap[inst.target.name]
KeyError: '$0.9'
```

**Comment by sklam** [comment] 2018-07-27 16:58
Note: to reproduce this, the line at https://github.com/numba/numba/blob/ff1eaec52b659ee30e1fa0ff4920d06c60cb99c8/numba/decorators.py?utf8=%E2%9C%93#L147 must be commented out.

**Comment by sklam** [comment] 2018-07-27 17:15
The issue is not really related to caching but an issue with the type annotation info not matching the IR.  Alternatively reproducer:

```python
import numba
import numpy as np

numba.parfor.sequential_parfor_lowering = True

@numba.njit(parallel=True)
def calc_pi(n):
    x = 2*np.random.ranf(n)-1
    y = 2*np.random.ranf(n)-1
    return 4*np.sum(x**2+y**2<1)/n

calc_pi(100)
calc_pi.inspect_types()  <---- will fail here.
```
Outputs:

```
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "chk3161.py", line 13, in <module>
    calc_pi.inspect_types()
  File "/Users/siu/dev/numba/numba/dispatcher.py", line 402, in inspect_types
    print(res.type_annotation, file=file)
  File "/Users/siu/dev/numba/numba/annotations/type_annotations.py", line 272, in __str__
    return self.annotate()
  File "/Users/siu/dev/numba/numba/annotations/type_annotations.py", line 116, in annotate
    groupedinst = self.prepare_annotations()
  File "/Users/siu/dev/numba/numba/annotations/type_annotations.py", line 100, in prepare_annotations
    atype = self.typemap[inst.target.name]
KeyError: '$0.9'
```

The `typemap` is not in-sync with the IR.  It's likely that the parfor transformations didn't update the `typemap` properly.

**Comment by ehsantn** [comment] 2018-07-27 22:56
I think it's because we remove dead variables but don't delete the `typemap` entry.

**Comment by njriasan** [comment] 2022-01-05 04:37
@ehsantn The example in this issue works as of 0.54.1. Can we close this issue?

**Comment by ehsantn** [comment] 2022-01-05 14:52
Yes, we can close this.

**Comment by stuartarchibald** [comment] 2022-01-05 14:55
Thanks, closing.

**Closed by stuartarchibald** 2022-01-05 14:55 UTC
Labels: bug, ParallelAccelerator
