### ISSUE TITLE
Error raised when using functools.reduce() together with operator.mul, and setting nopython=True

### ISSUE THREAD

**Issue by leockl** [numba/numba#5380] opened 2020-03-12 03:49 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Numba documentation [here](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html) says it supports `functools.reduce()` and `operator.mul()`. But when I used them together, I get an error.

My code:
```
import numpy as np
from itertools import product
from functools import reduce
from operator import mul
from numba import jit, prange

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(lst)
n = 2
flat = np.ravel(arr).tolist()
gen = np.array([list(a) for a in product(flat, repeat=n)])

@jit(nopython=True, parallel=True)
def mtp(gen):
    nrows_gen = len(gen)
    results = np.empty(nrows_gen)
    for i in prange(nrows_gen):
        results[i] = reduce(mul, gen[i], 1)   # multiplying inner array elements
    return results
mtp(gen)
```
The error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-83-6b6c51c7b346> in <module>
     13         results[i] = reduce(mul, gen[i], 1)
     14     return results
---> 15 mtp(gen)

~\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    418                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    419             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 420             raise e
    421 
    422     def inspect_llvm(self, signature=None):

~\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    351                 argtypes.append(self.typeof_pyval(a))
    352         try:
--> 353             return self.compile(tuple(argtypes))
    354         except errors.ForceLiteralArg as e:
    355             # Received request for compiler re-entry with the list of arguments

~\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    766             self._cache_misses[sig] += 1
    767             try:
--> 768                 cres = self._compiler.compile(args, return_type)
    769             except errors.ForceLiteralArg as e:
    770                 def folded(args, kws):

~\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     75 
     76     def compile(self, args, return_type):
---> 77         status, retval = self._compile_cached(args, return_type)
     78         if status:
     79             return retval

~\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_cached(self, args, return_type)
     89 
     90         try:
---> 91             retval = self._compile_core(args, return_type)
     92         except errors.TypingError as e:
     93             self._failed_cache[key] = e

~\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_core(self, args, return_type)
    107                                       args=args, return_type=return_type,
    108                                       flags=flags, locals=self.locals,
--> 109                                       pipeline_class=self.pipeline_class)
    110         # Check typing error if object mode is used
    111         if cres.typing_error is not None and not flags.enable_pyobject:

~\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    549     pipeline = pipeline_class(typingctx, targetctx, library,
    550                               args, return_type, flags, locals)
--> 551     return pipeline.compile_extra(func)
    552 
    553 

~\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    329         self.state.lifted = ()
    330         self.state.lifted_from = None
--> 331         return self._compile_bytecode()
    332 
    333     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~\Anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    391         """
    392         assert self.state.func_ir is None
--> 393         return self._compile_core()
    394 
    395     def _compile_ir(self):

~\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    371                 self.state.status.fail_reason = e
    372                 if is_final_pipeline:
--> 373                     raise e
    374         else:
    375             raise CompilerError("All available pipelines exhausted")

~\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    362             res = None
    363             try:
--> 364                 pm.run(self.state)
    365                 if self.state.cr is not None:
    366                     break

~\Anaconda3\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    345                     (self.pipeline_name, pass_desc)
    346                 patched_exception = self._patch_error(msg, e)
--> 347                 raise patched_exception
    348 
    349     def dependency_analysis(self):

~\Anaconda3\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    336                 pass_inst = _pass_registry.get(pss).pass_inst
    337                 if isinstance(pass_inst, CompilerPass):
--> 338                     self._runPass(idx, pass_inst, state)
    339                 else:
    340                     raise BaseException("Legacy pass in use")

~\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\Anaconda3\lib\site-packages\numba\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    300             mutated |= check(pss.run_initialization, internal_state)
    301         with SimpleTimer() as pass_time:
--> 302             mutated |= check(pss.run_pass, internal_state)
    303         with SimpleTimer() as finalize_time:
    304             mutated |= check(pss.run_finalizer, internal_state)

~\Anaconda3\lib\site-packages\numba\compiler_machinery.py in check(func, compiler_state)
    273 
    274         def check(func, compiler_state):
--> 275             mangled = func(compiler_state)
    276             if mangled not in (True, False):
    277                 msg = ("CompilerPass implementations should return True/False. "

~\Anaconda3\lib\site-packages\numba\typed_passes.py in run_pass(self, state)
    267                                          state.flags,
    268                                          state.parfor_diagnostics)
--> 269         parfor_pass.run()
    270 
    271         # check the parfor pass worked and warn if it didn't

~\Anaconda3\lib\site-packages\numba\parfor.py in run(self)
   1509             self._convert_numpy(self.func_ir.blocks)
   1510         if self.options.reduction:
-> 1511             self._convert_reduce(self.func_ir.blocks)
   1512         if self.options.prange:
   1513            self._convert_loop(self.func_ir.blocks)

~\Anaconda3\lib\site-packages\numba\parfor.py in _convert_reduce(self, blocks)
   1668                         # reduce function with generic function
   1669                         parfor = guard(self._reduce_to_parfor, equiv_set, lhs,
-> 1670                                        expr.args, loc)
   1671                     if parfor:
   1672                         instr = parfor

~\Anaconda3\lib\site-packages\numba\ir_utils.py in guard(func, *args, **kwargs)
   1435     """
   1436     try:
-> 1437         return func(*args, **kwargs)
   1438     except GuardException:
   1439         return None

~\Anaconda3\lib\site-packages\numba\parfor.py in _reduce_to_parfor(self, equiv_set, lhs, args, loc)
   2497         body_label = next_label()
   2498         index_var, loop_body = self._mk_reduction_body(call_name,
-> 2499                                 scope, loc, index_vars, in_arr, acc_var)
   2500         if mask_indices:
   2501             index_var = mask_index[0]

~\Anaconda3\lib\site-packages\numba\parfor.py in _mk_reduction_body(self, call_name, scope, loc, index_vars, in_arr, acc_var)
   2433         from numba.inline_closurecall import check_reduce_func
   2434         reduce_func = get_definition(self.func_ir, call_name)
-> 2435         fcode = check_reduce_func(self.func_ir, reduce_func)
   2436 
   2437         arr_typ = self.typemap[in_arr.name]

~\Anaconda3\lib\site-packages\numba\inline_closurecall.py in check_reduce_func(func_ir, func_var)
    245         if not isinstance(reduce_func.value,
    246                           numba.targets.registry.CPUDispatcher):
--> 247             raise ValueError("Invalid reduction function")
    248         # pull out the python function for inlining
    249         reduce_func = reduce_func.value.py_func

ValueError: Failed in nopython mode pipeline (step: convert to parfors)
Invalid reduction function
```
When I removed `nopython=True` and just use `@jit(parallel=True)`, the code did run and given me the results **but it also** gave me this error below about object mode fall-back behavior to be deprecated. Would prefer to use `@jit(nopython=True, parallel=True)` so that these errors doesn't show up.
```
C:\Users\HP\Anaconda3\lib\site-packages\numba\object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "<ipython-input-56-fc2a50a0b413>", line 11:
    def mtp(gen):
        <source elided>
        results = np.empty(nrows_gen)
        for i in prange(nrows_gen):
        ^

  state.func_ir.loc))
```
Please assists, many thanks!

**Comment by esc** [comment] 2020-03-12 11:25
@leockl thanks for reporting this to the Numba issue tracker. I have labelled the issue as needing triage for the time being.

**Comment by leockl** [comment] 2020-03-12 13:38
@esc thank you for the update.

**Comment by stuartarchibald** [comment] 2020-03-12 18:01
I answered this here: https://gitter.im/numba/numba?at=5e6a0fcc145f4d695637df9b. A copy of which is:

Use of reduce requires some slightly unusual "spelling", there's an issue about this somewhere IIRC. Anyway, this:
```python
import numpy as np
from itertools import product
from functools import reduce
from operator import mul
from numba import njit, prange

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(lst)
n = 3
flat = np.ravel(arr).tolist()
gen = np.array([list(a) for a in product(flat, repeat=n)])

@njit
def mul_wrapper(x, y):
    return mul(x, y)

@njit
def mtp(gen):
    results = np.empty(gen.shape[0])
    for i in prange(gen.shape[0]):
        results[i] = reduce(mul_wrapper, gen[i], None)
    return results

print(mtp(gen))
```
should work, note that the reduce function takes a dispatcher. It's also possible to do this:
```python
@njit
def mtp(gen):
    results = np.empty(gen.shape[0])
    def op(x, y):
        return mul(x, y)
    for i in prange(gen.shape[0]):
        results[i] = reduce(op, gen[i], None)
    return results
```
because there's a bit of magic inside Numba that spots closures that will escape functions and compiles them.

The parallel target might be able to support what you want but is also going to be more constrained.

**Comment by esc** [comment] 2020-03-12 18:34
@leockl let us know if the above answer solves your issue and if we can close this.

**Comment by leockl** [comment] 2020-03-13 01:07
Hi @esc, thank you for the swift response. If I change `@jit` to `@jit(nopython=True, parallel=True)` in your code, it gives an error:

`The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.` 

Is parallelization not possible with @jit here even though the idea of my code was to loop parallelize the multiplication of the inner array elements?

**Comment by stuartarchibald** [comment] 2020-03-16 10:49
@leockl any chance you have a reproduces for `np.prod` being slower than `reduce` with `operator.mul`, thanks.

**Comment by stuartarchibald** [comment] 2020-09-02 10:29
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Closed by stuartarchibald** 2020-09-02 10:29 UTC
Labels: more info needed
