### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords)

### ISSUE THREAD

**Issue by chriscay** [numba/numba#4681] opened 2019-10-09 13:54 UTC
```
UMAP(a=None, angular_rp_forest=False, b=None, init='spectral',
   learning_rate=1.0, local_connectivity=1, metric='correlation',
   metric_kwds=None, min_dist=0.3, n_components=2, n_epochs=None,
   n_neighbors=30, negative_sample_rate=5, random_state=None,
   repulsion_strength=1.0, set_op_mix_ratio=1.0, spread=1.0,
   target_metric='categorical', target_metric_kwds=None,
   target_n_neighbors=-1, target_weight=0.5, transform_queue_size=4.0,
   transform_seed=42, verbose=True)
Construct fuzzy simplicial set
Wed Oct  9 15:49:38 2019 Finding Nearest Neighbors
Wed Oct  9 15:49:39 2019 Finished Nearest Neighbor Search
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  UnsupportedParforsError: Failed in nopython mode pipeline (step: nopython mode backend)
The 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.
[1] During: lowering "id=3[LoopNest(index_variable = parfor_index.171, range = (0, $0.13, 1))]{362: <ir.Block at C:\Users\cayrou\AppData\Local\CONTIN~1\MINICO~1\lib\site-packages\umap\umap_.py (330)>}Var(parfor_index.171, C:\Users\cayrou\AppData\Local\CONTIN~1\MINICO~1\lib\site-packages\umap\umap_.py (330))" at C:\Users\cayrou\AppData\Local\CONTIN~1\MINICO~1\lib\site-packages\umap\umap_.py (330)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new
```

**Comment by seibert** [comment] 2019-10-09 13:55
Are you using Python 2.7 or 32-bit Python?

**Comment by esc** [comment] 2019-11-05 11:52
The root cause is probably the same as: https://github.com/numba/numba/issues/4778 i.e. using Python 2.7 and/or 32-bit architecture. I will close this issue now, feel free to- re-open in case the issue persists on non-python-2.7 or non-32-bit.

**Closed by esc** 2019-11-05 11:52 UTC
Labels: needtriage
