### ISSUE TITLE
exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by jlbmdm** [numba/numba#3968] opened 2019-04-12 13:14 UTC
- [x ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

After running several times the same code (with minimal variations) I got non consistent numba behabiour when calling a function with @jit decorator: some times it runs ok and others crashes with different error messages, like:
> exception: access violation reading 0xFFFFFFFFFFFFFFFF

(see complete callback below; it can show different memry addresses)

> Assertion failed: Val && "isa<> used on a null pointer", file c:\ci\llvmdev_1546569470211\work\include\llvm\support\casting.h, line 106

> Sometimes it crashes without any message and shows a Windows-10 window reporting "python.exe error"

The code that crashes is a simple call to a function when it is used inside a module with other calls to jit functions that work properly. The function calls that crash can be as simple as:

```python
@numba.jit(nopython=True)
def myFunction1(arg1):
    resp1 = arg1 * 2
    return resp1

@numba.jit(nopython=True)
def myFunction2(miArg):
    resp2 = miArg * 2
    return resp2

arg1 = numba.int8(5)
print('Loading numba 1')
newValue1 = myFunction1(arg1)
print('ok1', newValue1)
print('Loading numba 2')
newValue2 = myFunction2(arg1)
print('ok2', newValue2)
```

Sometimes myFunction1() runs ok and myFunction2() crashes and others both crashes. A few times (maily after rebooting PC) both functions run ok. Is there something wron in my code? Is it a numba error? Is it related to python version?

My system: Windows 10, Anaconda3 64 bits (also in 32 bit version in other PC) python 3.7.3:
>__Hardware Information__
Machine                                       : AMD64
CPU Name                                      : skylake
CPU count                                     : 4
CPU Features                                  :
adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase invpcid lzcnt
mmx movbe pclmul popcnt prfchw rdrnd rdseed rtm sahf sgx sse sse2 sse3 sse4.1
sse4.2 ssse3 xsave xsavec xsaveopt xsaves
__OS Information__
Platform                                      : Windows-10-10.0.16299-SP0
Release                                       : 10
System Name                                   : Windows
Version                                       : 10.0.16299
OS specific info                              : 1010.0.16299SP0Multiprocessor Free
__Python Information__
Python Compiler                               : MSC v.1915 64 bit (AMD64)
Python Implementation                         : CPython
Python Version                                : 3.7.3
Python Locale                                 : es_ES cp1252
__LLVM information__
LLVM version                                  : 7.0.0
__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:
HSA is not currently supported on this platform (win32).
:

Callback error:
>Loading numba 1
Traceback (most recent call last):
  File "C:\myDir\myApp.py", line 569, in myFunc
    newValue1 = myFunction1(arg1)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 369, in _compile_for_args
    raise e
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 244, in run
    stage()
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 731, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 681, in _backend
    lowered = lowerfn()
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 668, in backend_nopython_mode
    self.metadata)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 1065, in native_lowering_stage
    lower.create_cpython_wrapper(flags.release_gil)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\lowering.py", line 271, in create_cpython_wrapper
    release_gil=release_gil)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\targets\cpu.py", line 150, in create_cpython_wrapper
    library.add_ir_module(wrapper_module)
  File "C:\Anaconda\anaconda3\Lib\site-packages\numba\targets\codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "C:\Anaconda\anaconda3\Lib\site-packages\llvmlite\binding\module.py", line 22, in parse_assembly
    ffi.lib.LLVMPY_ParseAssembly(context, strbuf, errmsg),
  File "C:\Anaconda\anaconda3\Lib\site-packages\llvmlite\binding\ffi.py", line 108, in __call__
    return self._cfn(*args, **kwargs)
OSError: Failed in nopython mode pipeline (step: nopython mode backend)
exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by stuartarchibald** [comment] 2019-04-12 13:31
Thanks for the report. I've tried to reproduce this but cannot. Please could you paste the entire output of `numba -s` (removing anything you don't want to shared beforehand), thanks.

**Comment by jlbmdm** [comment] 2019-04-12 15:48
This my complete numba -s output:

>(base) C:\>numba -s
System info:
--------------------------------------------------------------------------------
>__Time Stamp__
2019-04-12 12:26:17.190765

>__Hardware Information__
Machine                                       : AMD64
CPU Name                                      : skylake
CPU count                                     : 4
CPU Features                                  :
adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase invpcid lzcnt
mmx movbe pclmul popcnt prfchw rdrnd rdseed rtm sahf sgx sse sse2 sse3 sse4.1
sse4.2 ssse3 xsave xsavec xsaveopt xsaves

>__OS Information__
Platform                                      : Windows-10-10.0.16299-SP0
Release                                       : 10
System Name                                   : Windows
Version                                       : 10.0.16299
OS specific info                              : 1010.0.16299SP0Multiprocessor Free

>__Python Information__
Python Compiler                               : MSC v.1915 64 bit (AMD64)
Python Implementation                         : CPython
Python Version                                : 3.7.3
Python Locale                                 : es_ES cp1252

>__LLVM information__
LLVM version                                  : 7.0.0

>__CUDA Information__
CUDA driver library cannot be found or no CUDA enabled devices are present.
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

>__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:

>HSA is not currently supported on this platform (win32).
:

>__SVML Information__
SVML state, config.USING_SVML                 : True
SVML library found and loaded                 : True
llvmlite using SVML patched LLVM              : True
SVML operational                              : True

>__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : True
Workqueue Threading layer available           : True

>__Numba Environment Variable Information__
None set.

> __Conda Information__
WARNING: The conda.compat module is deprecated and will be removed in a future release.
conda_build_version                           : 3.17.8
conda_env_version                             : 4.6.11
platform                                      : win-64
python_version                                : 3.7.3.final.0
root_writable                                 : True
WARNING: The conda.compat module is deprecated and will be removed in a future release.

> __Current Conda Env__
> _ipyw_jlab_nb_ext_conf    0.1.0                    py37_0

> alabaster                 0.7.12                   py37_0
> anaconda                  2019.03                  py37_0
> anaconda-client           1.7.2                    py37_0
> anaconda-navigator        1.9.7                    py37_0
> anaconda-project          0.8.2                    py37_0
> asn1crypto                0.24.0                   py37_0
> astroid                   2.2.5                    py37_0
> astropy                   3.1.2            py37he774522_0
> atomicwrites              1.3.0                    py37_1
> attrs                     19.1.0                   py37_1
> babel                     2.6.0                    py37_0
> backcall                  0.1.0                    py37_0
> backports                 1.0                      py37_1
> backports.os              0.1.1                    py37_0
> backports.shutil_get_terminal_size 1.0.0                    py37_2
> beautifulsoup4            4.7.1                    py37_1
> bitarray                  0.8.3            py37hfa6e2cd_0
> bkcharts                  0.2                      py37_0
> blas                      1.0                         mkl
> bleach                    3.1.0                    py37_0
> blosc                     1.15.0               h7bd577a_0
> bokeh                     1.0.4                    py37_0
> boto                      2.49.0                   py37_0
> bottleneck                1.2.1            py37h452e1ab_1
> bzip2                     1.0.6                hfa6e2cd_5
> ca-certificates           2019.1.23                     0
> certifi                   2019.3.9                 py37_0
> cffi                      1.12.2           py37h7a1dbc1_1
> chardet                   3.0.4                    py37_1
> click                     7.0                      py37_0
> cloudpickle               0.8.0                    py37_0
> clyent                    1.2.2                    py37_1
> colorama                  0.4.1                    py37_0
> comtypes                  1.1.7                    py37_0
> conda                     4.6.11                   py37_0
> conda-build               3.17.8                   py37_0
> conda-env                 2.6.0                         1
> conda-verify              3.1.1                    py37_0
> console_shortcut          0.1.1                         3
> contextlib2               0.5.5                    py37_0
> cryptography              2.6.1            py37h7a1dbc1_0
> curl                      7.64.0               h2a8f88b_2
> cycler                    0.10.0                   py37_0
> cython                    0.29.6           py37ha925a31_0
> cytoolz                   0.9.0.1          py37hfa6e2cd_1
> dask                      1.1.4                    py37_1
> dask-core                 1.1.4                    py37_1
> dbfread                   2.0.7                    py37_0
> decorator                 4.4.0                    py37_1
> defusedxml                0.5.0                    py37_1
> distributed               1.26.0                   py37_1
> docutils                  0.14                     py37_0
> entrypoints               0.3                      py37_0
> et_xmlfile                1.0.1                    py37_0
> expat                     2.2.5                he025d50_0
> fastcache                 1.0.2            py37hfa6e2cd_2
> filelock                  3.0.10                   py37_0
> flask                     1.0.2                    py37_1
> freetype                  2.9.1                ha9979f8_1
> freexl                    1.0.5                hfa6e2cd_0
> future                    0.17.1                   py37_0
> gdal                      2.3.3            py37hdf43c64_0
> geos                      3.7.1                h33f27b4_0
> get_terminal_size         1.0.0                h38e98db_0
> gevent                    1.4.0            py37he774522_0
> glob2                     0.6                      py37_1
> greenlet                  0.4.15           py37hfa6e2cd_0
> h5py                      2.9.0            py37h5e291fa_0
> hdf4                      4.2.13               h712560f_2
> hdf5                      1.10.4               h7ebc959_0
> heapdict                  1.0.0                    py37_2
> html5lib                  1.0.1                    py37_0
> icc_rt                    2019.0.0             h0cc432a_1
> icu                       58.2                 ha66f8fd_1
> idna                      2.8                      py37_0
> imageio                   2.5.0                    py37_0
> imagesize                 1.1.0                    py37_0
> importlib_metadata        0.8                      py37_0
> intel-openmp              2019.3                      203
> ipykernel                 5.1.0            py37h39e3cac_0
> ipython                   7.4.0            py37h39e3cac_0
> ipython_genutils          0.2.0                    py37_0
> ipywidgets                7.4.2                    py37_0
> isort                     4.3.16                   py37_0
> itsdangerous              1.1.0                    py37_0
> jdcal                     1.4                      py37_0
> jedi                      0.13.3                   py37_0
> jinja2                    2.10                     py37_0
> jpeg                      9b                   hb83a4c4_2
> jsonschema                3.0.1                    py37_0
> jupyter                   1.0.0                    py37_7
> jupyter_client            5.2.4                    py37_0
> jupyter_console           6.0.0                    py37_0
> jupyter_core              4.4.0                    py37_0
> jupyterlab                0.35.4           py37hf63ae98_0
> jupyterlab_server         0.2.0                    py37_0
> kealib                    1.4.7                h07cbb95_6
> keyring                   18.0.0                   py37_0
> kiwisolver                1.0.1            py37h6538335_0
> krb5                      1.16.1               hc04afaa_7
> lazy-object-proxy         1.3.1            py37hfa6e2cd_2
> libarchive                3.3.3                h0643e63_5
> libboost                  1.67.0               hd9e427e_4
> libcurl                   7.64.0               h2a8f88b_2
> libgdal                   2.3.3                h10f50ba_0
> libiconv                  1.15                 h1df5818_7
> libkml                    1.3.0                he5f2a48_4
> liblief                   0.9.0                ha925a31_2
> libnetcdf                 4.6.1                h411e497_2
> libpng                    1.6.36               h2a8f88b_0
> libpq                     11.2                 h3235a2c_0
> libsodium                 1.0.16               h9d3ae62_0
> libspatialite             4.3.0a              hc36aec2_19
> libssh2                   1.8.0                h7a1dbc1_4
> libtiff                   4.0.10               hb898794_2
> libxml2                   2.9.9                h464c3ec_0
> libxslt                   1.1.33               h579f668_0
> llvmlite                  0.28.0           py37ha925a31_0
> locket                    0.2.0                    py37_1
> lxml                      4.3.2            py37h1350720_0
> lz4-c                     1.8.1.2              h2fa13f4_0
> lzo                       2.10                 h6df0209_2
> m2w64-gcc-libgfortran     5.3.0                         6
> m2w64-gcc-libs            5.3.0                         7
> m2w64-gcc-libs-core       5.3.0                         7
> m2w64-gmp                 6.1.0                         2
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2
> markupsafe                1.1.1            py37he774522_0
> matplotlib                3.0.3            py37hc8f65d3_0
> mccabe                    0.6.1                    py37_1
> menuinst                  1.4.16           py37he774522_0
> mistune                   0.8.4            py37he774522_0
> mkl                       2019.3                      203
> mkl-service               1.1.2            py37hb782905_5
> mkl_fft                   1.0.10           py37h14836fe_0
> mkl_random                1.0.2            py37h343c172_0
> more-itertools            6.0.0                    py37_0
> mpmath                    1.1.0                    py37_0
> msgpack-python            0.6.1            py37h74a9793_1
> msys2-conda-epoch         20160418                      1
> multipledispatch          0.6.0                    py37_0
> navigator-updater         0.2.1                    py37_0
> nbconvert                 5.4.1                    py37_3
> nbformat                  4.4.0                    py37_0
> networkx                  2.2                      py37_1
> nltk                      3.4                      py37_1
> nose                      1.3.7                    py37_2
> notebook                  5.7.8                    py37_0
> numba                     0.43.1           py37hf9181ef_0
> numexpr                   2.6.9            py37hdce8814_0
> numpy                     1.16.2           py37h19fb1c0_0
> numpy-base                1.16.2           py37hc3f5095_0
> numpydoc                  0.8.0                    py37_0
> olefile                   0.46                     py37_0
> openpyxl                  2.6.1                    py37_1
> openssl                   1.1.1b               he774522_1
> packaging                 19.0                     py37_0
> pandas                    0.24.2           py37ha925a31_0
> pandoc                    2.2.3.2                       0
> pandocfilters             1.4.2                    py37_1
> parso                     0.3.4                    py37_0
> partd                     0.3.10                   py37_1
> path.py                   11.5.0                   py37_0
> pathlib2                  2.3.3                    py37_0
> patsy                     0.5.1                    py37_0
> pcre                      8.43                 ha925a31_0
> pep8                      1.7.1                    py37_0
> pickleshare               0.7.5                    py37_0
> pillow                    5.4.1            py37hdc69c19_0
> pip                       19.0.3                   py37_0
> pkginfo                   1.5.0.1                  py37_0
> pluggy                    0.9.0                    py37_0
> ply                       3.11                     py37_0
> powershell_shortcut       0.0.1                         2
> proj4                     5.2.0                ha925a31_1
> prometheus_client         0.6.0                    py37_0
> prompt_toolkit            2.0.9                    py37_0
> psutil                    5.6.1            py37he774522_0
> py                        1.8.0                    py37_0
> py-lief                   0.9.0            py37ha925a31_2
> pycodestyle               2.5.0                    py37_0
> pycosat                   0.6.3            py37hfa6e2cd_0
> pycparser                 2.19                     py37_0
> pycrypto                  2.6.1            py37hfa6e2cd_9
> pycurl                    7.43.0.2         py37h7a1dbc1_0
> pyflakes                  2.1.1                    py37_0
> pygments                  2.3.1                    py37_0
> pylint                    2.3.1                    py37_0
> pyodbc                    4.0.26           py37ha925a31_0
> pyopenssl                 19.0.0                   py37_0
> pyparsing                 2.3.1                    py37_0
> pyqt                      5.9.2            py37h6538335_2
> pyreadline                2.1                      py37_1
> pyrsistent                0.14.11          py37he774522_0
> pysocks                   1.6.8                    py37_0
> pytables                  3.5.1            py37h1da0976_0
> pytest                    4.3.1                    py37_0
> pytest-arraydiff          0.3              py37h39e3cac_0
> pytest-astropy            0.5.0                    py37_0
> pytest-doctestplus        0.3.0                    py37_0
> pytest-openfiles          0.3.2                    py37_0
> pytest-remotedata         0.3.1                    py37_0
> python                    3.7.3                h8c8aaf0_0
> python-dateutil           2.8.0                    py37_0
> python-libarchive-c       2.8                      py37_6
> pytz                      2018.9                   py37_0
> pywavelets                1.0.2            py37h8c2d366_0
> pywin32                   223              py37hfa6e2cd_1
> pywinpty                  0.5.5                 py37_1000
> pyyaml                    5.1              py37he774522_0
> pyzmq                     18.0.0           py37ha925a31_0
> qt                        5.9.7            vc14h73c81de_0
> qtawesome                 0.5.7                    py37_1
> qtconsole                 4.4.3                    py37_0
> qtpy                      1.7.0                    py37_1
> requests                  2.21.0                   py37_0
> rope                      0.12.0                   py37_0
> ruamel_yaml               0.15.46          py37hfa6e2cd_0
> scikit-image              0.14.2           py37ha925a31_0
> scikit-learn              0.20.3           py37h343c172_0
> scipy                     1.2.1            py37h29ff71c_0
> seaborn                   0.9.0                    py37_0
> send2trash                1.5.0                    py37_0
> setuptools                40.8.0                   py37_0
> simplegeneric             0.8.1                    py37_2
> singledispatch            3.4.0.3                  py37_0
> sip                       4.19.8           py37h6538335_0
> six                       1.12.0                   py37_0
> snappy                    1.1.7                h777316e_3
> snowballstemmer           1.2.1                    py37_0
> sortedcollections         1.1.2                    py37_0
> sortedcontainers          2.1.0                    py37_0
> soupsieve                 1.8                      py37_0
> sphinx                    1.8.5                    py37_0
> sphinxcontrib             1.0                      py37_1
> sphinxcontrib-websupport  1.1.0                    py37_1
> spyder                    3.3.3                    py37_0
> spyder-kernels            0.4.2                    py37_0
> sqlalchemy                1.3.1            py37he774522_0
> sqlite                    3.27.2               he774522_0
> statsmodels               0.9.0            py37h452e1ab_0
> sympy                     1.3                      py37_0
> tblib                     1.3.2                    py37_0
> terminado                 0.8.1                    py37_1
> testpath                  0.4.2                    py37_0
> tk                        8.6.8                hfa6e2cd_0
> toolz                     0.9.0                    py37_0
> tornado                   6.0.2            py37he774522_0
> tqdm                      4.31.1                   py37_1
> traitlets                 4.3.2                    py37_0
> unicodecsv                0.14.1                   py37_0
> urllib3                   1.24.1                   py37_0
> vc                        14.1                 h0510ff6_4
> vs2015_runtime            14.15.26706          h3a45250_0
> wcwidth                   0.1.7                    py37_0
> webencodings              0.5.1                    py37_1
> werkzeug                  0.14.1                   py37_0
> wheel                     0.33.1                   py37_0
> widgetsnbextension        3.4.2                    py37_0
> win_inet_pton             1.1.0                    py37_0
> win_unicode_console       0.5                      py37_0
> wincertstore              0.2                      py37_0
> winpty                    0.4.3                         4
> wrapt                     1.11.1           py37he774522_0
> xerces-c                  3.2.2                ha925a31_0
> xlrd                      1.2.0                    py37_0
> xlsxwriter                1.1.5                    py37_0
> xlwings                   0.15.4                   py37_0
> xlwt                      1.3.0                    py37_0
> xz                        5.2.4                h2fa13f4_4
> yaml                      0.1.7                hc54c509_2
> zeromq                    4.3.1                h33f27b4_3
> zict                      0.1.4                    py37_0
> zipp                      0.3.3                    py37_1
> zlib                      1.2.11               h62dcd97_3
> zstd                      1.3.7                h508b16e_0

>--------------------------------------------------------------------------------
>If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

>=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

**Comment by jlbmdm** [comment] 2019-04-15 12:18
Another error message after some changes:
> 
> While deleting: void %
> An asserting value handle still pointed to this value!
> UNREACHABLE executed at c:\ci\llvmdev_1546569470211\work\lib\ir\value.cpp:887!

In this case, while running in Eclipse, and the app apparently continues running several minutes (without any progress) until it crashes without any aditional message. This same version of the app running outside Eclipse crashes at the same point but without message at Prompt (cmd) and with a emergent window telling that Python stopped running.

**Comment by stuartarchibald** [comment] 2019-04-15 12:31
Thanks for the additional information. Couple of questions:

1. Does this code run ok on another machine?
2. If you don't use Numba JIT (either by setting the [`NUMBA_DISABLE_JIT`](http://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_JIT) environment variable, or by just removing the `@jit` decorators) does the code work?

I'm asking the above because if crash locations move about after minor changes it can often be a sign of corruption.

**Comment by jlbmdm** [comment] 2019-04-15 20:48
Before asking, I had removed the @jit decorators of functions that crashed and all of them run ok without numba. But after your comment I've also removed @jit decorator of all functions and I've found out that one of them has an error in array dimension, and after correcting it, it looks like to work fine (tomorrow I'll confirm this point).
Is it expected this to happend?

**Comment by seibert** [comment] 2019-04-15 20:57
Numba-compiled code behaves similar to C and FORTRAN, and doesn't automatically do bounds checking.  (We may introduce that as an option in the future, though it will lower performance when turned on.)

**Comment by jlbmdm** [comment] 2019-04-15 21:01
I mean that the error wasn't in the function that crashed but in other one that still had not been executed (so, as far as I undertood, it's still not expected to be compiled).

**Comment by stuartarchibald** [comment] 2019-04-16 09:46
Please could you share a piece of code that actually triggers the problem you are seeing? Or does the sample in the [original post](https://github.com/numba/numba/issues/3968#issue-432560495) consistently fail and that is a minimal working reproducer already? Thanks.

**Comment by jlbmdm** [comment] 2019-04-16 13:18
I've generated this code that triggers the random output.

There is an error inside a function 1 with @jit but this function runs ok without giving any error mesagge (that mislead my debugging) and the error shows up (sometimes) in a call to another @jit function 2.
In the example below, that function 2 uses the array that is not well managed in function1, although I've also got errors in a function 2 not related to variables of function 1, i.e. with just a line like a = b * 2, like in the example with wich I started this issue.

Code:
```
import numpy as np
import numba

@numba.jit(nopython=True)
def myFunction1(myArg1):
    myArg1[10] = 5 #Not correct but doens't crash
    #print(myArg1)
    return myArg1

@numba.jit(nopython=True)
def myFunction2(miArg2):
    #print(miArg2)
    return True

if __name__ == '__main__':
    myArray = np.zeros(5, dtype = np.int32)
    print('Loading numba 1')
    newArray = myFunction1(myArray)
    print('ok1:', newArray)
    
    print('Loading numba 2')
    ok = myFunction2(newArray)
    print('ok2:', ok)
```
After runing this code with or without removing the comment <#> to print() line inside myFunction1() and myFunction2() it can generate this outputs:

> Loading numba 1
> ok1: [0 0 0 0 0]
> Loading numba 2
> ok2: True

of

> Loading numba 1
> ok1: [0 0 0 0 0]
> Loading numba 2
> Inside function2: [0 0 0 0 0]
> ok2: True

or:

> Loading numba 1
> Inside function1: [0 0 0 0 0]
> ok1: [0 0 0 0 0]
> Loading numba 2
> Inside function2: [0 0 0 0 0]
> ok2: True

And **sometimes** crashes with this output:

> Loading numba 1
> Inside function1: [0 0 0 0 0]
> ok1: [0 0 0 0 0]
> Loading numba 2
> Traceback (most recent call last):
>   File "C:\_ws\example\tryNumba.py", line 29, in <module>
>     ok = myFunction2(newArray)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 369, in _compile_for_args
>     raise e
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 326, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 658, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\dispatcher.py", line 82, in compile
>     pipeline_class=self.pipeline_class)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 941, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 372, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 872, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 859, in _compile_core
>     res = pm.run(self.status)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 253, in run
>     raise patched_exception
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 244, in run
>     stage()
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 731, in stage_nopython_backend
>     self._backend(lowerfn, objectmode=False)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 681, in _backend
>     lowered = lowerfn()
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 668, in backend_nopython_mode
>     self.metadata)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\compiler.py", line 1063, in native_lowering_stage
>     lower.lower()
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\lowering.py", line 202, in lower
>     self.library.add_ir_module(self.module)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\numba\targets\codegen.py", line 185, in add_ir_module
>     ll_module = ll.parse_assembly(ir)
>   File "C:\Anaconda\anaconda3\Lib\site-packages\llvmlite\binding\module.py", line 22, in parse_assembly
>     ffi.lib.LLVMPY_ParseAssembly(context, strbuf, errmsg),
>   File "C:\Anaconda\anaconda3\Lib\site-packages\llvmlite\binding\ffi.py", line 108, in __call__
>     return self._cfn(*args, **kwargs)
> OSError: Failed in nopython mode pipeline (step: nopython mode backend)
> exception: access violation reading 0x0000000000000015

**Comment by stuartarchibald** [comment] 2019-04-16 13:34
@jlbmdm thanks. I think I know what's going on now. Numba is a JIT compiler, it compiles stuff only when it has to "Just In Time" for execution. I've copied your code below and written comments on it to try and explain what I think the problem is, essentially an invalid write sometimes corrupts LLVM (the compiler backend) itself...

```python
import numpy as np
import numba

@numba.jit(nopython=True)
def myFunction1(myArg1):
    # This may not "crash" but it is writing over some random part of memory
    myArg1[10] = 5 #Not correct but doens't crash
    #print(myArg1)
    return myArg1

@numba.jit(nopython=True)
def myFunction2(miArg2):
    #print(miArg2)
    return True

if __name__ == '__main__':
    myArray = np.zeros(5, dtype = np.int32)
    print('Loading numba 1')
    # Here, myFunction1 has not actually been compiled or run
    newArray = myFunction1(myArray)
    # Here, myFunction1 has been compiled for the myArray type and executed, it has however written over some random memory
    print('ok1:', newArray)
    
    # Here, myFunction2 has not been compiled or run, however I suspect some part of the compiler (LLVM) has been overwritten by the bad write above
    print('Loading numba 2')
    ok = myFunction2(newArray)
    # Here, myFunction2 has been been compiled if the bad write above hasn't written over an essential part of the compiler!
    print('ok2:', ok)
```

**Comment by jlbmdm** [comment] 2019-04-16 15:07
Yes, it looks like it writes over some random memory but the consecuences only show up later at some random moment when the app reads that memory position (or never).

It would be great that numba prevent for writting in wrong memory adresses.

**Comment by stuartarchibald** [comment] 2019-04-16 16:59
> Yes, it looks like it writes over some random memory but the consecuences only show up later at some random moment when the app reads that memory position (or never).

I think that is basically the problem.

> It would be great that numba prevent for writting in wrong memory adresses.

Indeed, there is a `boundcheck` flag in the target options, I've opened https://github.com/numba/numba/issues/3982 to track whether it does what is expected.

**Comment by stuartarchibald** [comment] 2019-04-18 21:58
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-04-18 21:58 UTC
Labels: no action required
