### ISSUE TITLE
with.. as construct breaks bytecode analysis and leads to an uncontrolled failure

### ISSUE THREAD

**Issue by Sequential-circuits** [numba/numba#6679] opened 2021-02-02 16:19 UTC
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
'try' block not supported until python3.7 or later

**Comment by esc** [comment] 2021-02-02 16:22
@Sequential-circuits thank you for submitting this. Please could you say which version of Python you are using? It seems like your Python may be to old to compile the code in question.

**Comment by Sequential-circuits** [comment] 2021-02-02 17:24
I've updated to 3.8 and now getting this
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/numba/core/ir.py", line 267, in get
    return self._con[name]
KeyError: '$2114setup_with.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/numba/core/ir.py", line 1099, in get_exact
    return self.localvars.get(name)
  File "/venv/lib/python3.8/site-packages/numba/core/ir.py", line 269, in get
    raise NotDefinedError(name)
numba.core.errors.NotDefinedError: The compiler failed to analyze the bytecode. Variable '$2114setup_with.1' is not defined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/numba/core/ir.py", line 267, in get
    return self._con[name]
KeyError: '$2114setup_with.1'

**Comment by esc** [comment] 2021-02-02 17:33
@Sequential-circuits thank you for updating this issue. I have never seen such an error before. In order to debug it, please submit a self-contained reproducer. I.e. a short, runnable snippet of code including imports that exhibits this failure when run. Thank you.

**Comment by stuartarchibald** [comment] 2021-02-02 17:48
@esc This sort of thing will do it, it's the `with... as` construct.
```python
from numba import njit
import numpy as np

@njit
def foo():
    with open('aaa') as f:
        pass

foo()
```

@Sequential-circuits Numba cannot compile everything, it's really good at loops, math/numerical  code and NumPy. If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics. This might help you decide if Numba is a good fit for your use case.

**Comment by Sequential-circuits** [comment] 2021-02-02 20:56
The code is long and my motivation to remove it to its bare minimum very small. Feel free to drop me an email to alcosta@tekntrash.com and I will send it complete

**Comment by Sequential-circuits** [comment] 2021-02-02 21:04
Yeah, but being unable to compile something does not mean throwing an error. At most, it should just ignore the code. My 5 cents :)

**Comment by stuartarchibald** [comment] 2021-02-02 21:43
> Yeah, but being unable to compile something does not mean throwing an error. At most, it should just ignore the code. My 5 cents :)

Whilst there's an understandable convenience aspect to this, feedback from Numba users suggests it manifests as a reasonably challenging experience. A user may write code that compiles fine and runs fast, then they may inadvertently edit it to something that cannot be compiled and it just executes slowly instead. Numba actually has a [version of this mode](https://numba.readthedocs.io/en/stable/user/5minguide.html#what-is-nopython-mode), it has caused so many problems due to erratic performance (and various other internal issues) that it is rarely/never recommended and will eventually be replaced by an explicit opt-in for the behaviour.

Also, I'm also fairly sure that it's a common failure mode for a compiler that cannot compile something to raise an exception. In the case above it's an ICE (Internal Compiler Error) that should not have occurred. Marking this as a bug, immediate fix is to catch the condition and provide a more suitable error message. Thanks for reporting it.

**Comment by Sequential-circuits** [comment] 2021-02-02 22:03
In all honesty, all I wanted from this software was the ability to run the code on the GPU instead of the CPU. I thought it'd be something like CUDA.

Or, at worst, to read barcodes on the GPU

**Comment by stuartarchibald** [comment] 2021-02-02 22:58
> In all honesty, all I wanted from this software was the ability to run the code on the GPU instead of the CPU. I thought it'd be something like CUDA.
> 
> Or, at worst, to read barcodes on the GPU

You can potentially do that :) Numba has a [CUDA target](https://numba.readthedocs.io/en/stable/cuda/index.html), I would suggest watching a couple of tutorials on it and then direction questions about how to do specific things with it to [Numba's discourse forum](https://numba.discourse.group/), chances are someone will jump in to help.

**Comment by stuartarchibald** [comment] 2021-02-03 10:42
https://github.com/numba/numba/pull/6681 makes it so that:
```python
from numba import njit

@njit
def foo():
    with open('aaa') as f:
        pass
```
does:
```
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
The 'with (context manager) as (variable):' construct is not supported.
```

**Closed** 2021-04-09 23:09 UTC
Labels: bug - ice
