### ISSUE TITLE
Numba/numpy report different results for SUM(x - MEAN(x))

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5288] opened 2020-02-20 15:44 UTC
I was working on the `np.var` implementation and one of the tests keept failing. Investigating the cause I stumbled across this oddity:

```python
import numpy as np
from numba import njit

def pyfunc(arr):
    tmp1 = np.divide(arr, arr.size)
    mean = np.sum(tmp1)
    deviations = np.subtract(arr, mean)
    return np.sum(deviations)

cfunc = njit(pyfunc)

arr = (np.arange(10) + 2**60).astype('int64')

print('Numpy result: ', pyfunc(arr))
print('Numba result: ', cfunc(arr))
```

Output:
```
Numpy result:  0.0
Numba result:  1280.0
```

The difference grows linearly with array size.

I would chalk this up as a ULP issue but having `SUM(x - MEAN(n)) != 0` is terrible... What is numpy doing to make this work?

**Comment by seibert** [comment] 2020-02-20 15:55
This may be related to this, which we didn't get a chance to finish: https://github.com/numba/numba/pull/3046

**Comment by seibert** [comment] 2020-02-20 15:56
(It is continually the 5th most important thing on Stuart's todo list.)

**Comment by ARF1** [comment] 2020-02-20 16:36
@seibert Thanks for the link. This being a bit of an edge-case I can understand why it was not really a top-priority. Any objections to me closing this issue, since this is already known?

**Comment by stuartarchibald** [comment] 2020-02-20 17:08
Demo:
```python
from numba import njit

N = 3

@njit
def pairwise(x):
    # Alg from https://en.wikipedia.org/wiki/Pairwise_summation#The_algorithm
    n = len(x)
    if n < N:
        s = x[0]
        for i in range(1, n):
            s = s + x[i]
    else:
        m = int(np.floor(n / 2))
        s = pairwise(x[0:m]) + pairwise(x[m:])
    return s


@njit
def nb_func(arr):
    tmp1 = np.divide(arr, arr.size)
    print(tmp1)
    mean = pairwise(tmp1)
    print(mean)
    deviations = np.subtract(arr, mean)
    print(deviations)
    return pairwise(deviations)


def pyfunc(arr):
    tmp1 = np.divide(arr, arr.size)
    print(tmp1)
    mean = np.sum(tmp1)
    print(mean)
    deviations = np.subtract(arr, mean)
    print(deviations)
    return np.sum(deviations)

import numpy as np
np.set_printoptions(precision=16)
arr = (np.arange(10) + 2**60).astype('int64')

print('Numba result: ', nb_func(arr))
print('NumPy result: ', pyfunc(arr))


```
produces:
```
[1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17]
1.152921504606847e+18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Numba result:  0.0
[1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17 1.152921504606847e+17 1.152921504606847e+17
 1.152921504606847e+17]
1.152921504606847e+18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
NumPy result:  0.0
```

**Comment by stuartarchibald** [comment] 2020-02-20 17:12
Closing as duplicate of https://github.com/numba/numba/issues/4419 (same root cause), thanks.

**Closed by stuartarchibald** 2020-02-20 17:12 UTC
Labels: bug, duplicate

**Comment by ARF1** [comment] 2020-02-20 20:19
@stuartarchibald Thanks for the demo. I was wondering how numpy would manage to implement this looping structure when an `axis` parameter was provided. The complexity of implementing this seemed forbidding to  me. - Turns out, numpy itself does not consistently use the pairwise algorithm either and suffers the same imprecision under some circumstances:

```python
import numpy as np

arr = (np.arange(10) + 2**60).astype('int64')
tmp1 = np.divide(arr, arr.size)
tmp2 = np.sum(tmp1)
tmp3 = np.subtract(arr, tmp2)
print('Numpy 1d: ', tmp3)

arr = np.stack([arr, arr])

tmp1 = np.divide(arr, arr.shape[0])
tmp2 = np.sum(tmp1, axis=0)
tmp3 = np.subtract(arr, tmp2)
print('Numpy 2d axis 0: ', tmp3)

tmp1 = np.divide(arr, arr.shape[1])
tmp2 = np.sum(tmp1, axis=1)
tmp3 = np.subtract(arr, np.expand_dims(tmp2, 1))
print('Numpy 2d axis 1: ', tmp3)

arr = np.copy(arr.T, order='C')

tmp1 = np.divide(arr, arr.shape[0])
tmp2 = np.sum(tmp1, axis=0)
tmp3 = np.subtract(arr, tmp2)
print('Numpy 2d transposed axis 0: ', tmp3)

tmp1 = np.divide(arr, arr.shape[1])
tmp2 = np.sum(tmp1, axis=1)
tmp3 = np.subtract(arr, np.expand_dims(tmp2, 1))
print('Numpy 2d transposed axis 1: ', tmp3)
```

Output:
```
Numpy 1d:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Numpy 2d axis 0:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Numpy 2d axis 1:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Numpy 2d transposed axis 0:  [[128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]
 [128. 128.]]
Numpy 2d transposed axis 1:  [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
```

I believe the reason that only a single case is affected is because numpy does some nifty things with the axis to ensure the optimal iteration order if possible without copies.
