### ISSUE TITLE
methods significantly slower than functions

### ISSUE THREAD

**Issue by wkerzendorf** [numba/numba#4055] opened 2019-05-06 14:12 UTC
We have a small `jitclass` that is instantiated millions of times and run through a montecarlo simulation. If we define the function `get_doppler_factor(r, mu, time_of_explosion)` outside as an individual function rather than as a method (see below) the code gets significantly faster. 

```python
@jitclass(rpacket_spec)
class RPacket(object):
    def __init__(self, r, mu, nu, energy):
        self.r = r
        self.mu = mu
        self.nu = nu
        self.energy = energy
        self.current_shell_id = 0
        self.status = PacketStatus.IN_PROCESS

    def get_doppler_factor(self, time_explosion):
        beta = (self.r / time_explosion) / C_SPEED_OF_LIGHT
        return 1.0 - self.mu * beta
```

**Comment by seibert** [comment] 2019-05-07 17:15
Just to be clear, are you benchmarking the performance of calling `get_doppler_factor()` from the Python interpreter, or from another nopython function?

**Comment by wkerzendorf** [comment] 2019-05-09 16:26
@seibert - thanks for taking a look at that. The full code is here (https://github.com/tardis-sn/tardis/blob/numba_montecarlo/tardis/montecarlo/montecarlo_numba/rpacket.py) - TARDIS is an open source scientific code and relatively easy to setup - I'm happy to share my testing files - if that helps.

**Comment by luk-f-a** [comment] 2019-05-19 18:31
@seibert , I have a small reproducer if you're interested. I was working on a sparse matrix class when I saw this issue and checked whether I could see the same, and I found a 50% difference.

**Comment by stuartarchibald** [comment] 2019-05-20 09:55
@luk-f-a if you have a small reproducer that you can share that'd be great, thanks.

**Comment by luk-f-a** [comment] 2019-05-20 11:39
@stuartarchibald, here it is

```python
import numba as nb
import numpy as np
from numba import njit, jitclass


@jitclass([('vals', nb.float64[:,:])])
class Arr:
    def __init__(self, b):
        self.vals = b
        
    def ldot(self, v):
        return v@self.vals

@njit
def loop_class(vect, my_arr):
    for _ in range(1000000):
        vect = my_arr.ldot(vect)
    return arr

v = np.ones(5)
arr = np.eye(5)
my_arr = Arr(b)

loop_class(v, my_arr)

@njit
def mult(vect, arr):
    return vect@arr

@njit
def loop_func(vect, arr):
    for _ in range(1000000): 
        vect = mult(vect, arr)
    return vect

loop_func(v, arr)

@njit
def loop_mixed(vect, my_arr):
    for _ in range(1000000):
        vect = vect@my_arr.vals
    return arr    

loop_mixed(v, my_arr)

print('class method')
%time loop_class(v, my_arr)
print('function')
%time loop_func(v, arr)
print('mixed - function over instance variable')
%time loop_mixed(v, my_arr)
```
returns

```
class method
CPU times: user 285 ms, sys: 3.98 ms, total: 289 ms
Wall time: 288 ms
function
CPU times: user 186 ms, sys: 8 µs, total: 186 ms
Wall time: 185 ms
mixed - function over instance variable
CPU times: user 251 ms, sys: 0 ns, total: 251 ms
Wall time: 250 ms
```

**Comment by wkerzendorf** [comment] 2019-06-04 15:03
@stuartarchibald @seibert any idea on this issue - should we just avoid methods for now?

**Comment by sklam** [comment] 2019-06-04 19:42
It didn't inline the method.  I thought this is fixed.  Let me check.

**Comment by sklam** [comment] 2019-06-04 19:59
The dependent function is linked properly for inlining.  LLVM decided to not inline the method.  But even increasing the inlining threshold so the method is inlined, the perf didn't improve.  I will need to check the LLVM IR to know why.

**Comment by wkerzendorf** [comment] 2019-06-05 06:05
thanks for looking into this!

**Comment by sklam** [comment] 2019-06-05 15:54
OK, so there is no problem with inlining or LLVM optimization.  The actual problem comes from whether the compiler knows layout of the array.  In the jitclass, `vals` is declared to be of type `nb.float64[:,:]`, which is an array of known layout.  Changing that to `nb.float64[:,::1]` will indicate that `vals` is C-contiguous.  In bare `njit` usage, the argument type is inferred by actual argument value.  So, it knows that the array is C-contiguous.

**Comment by luk-f-a** [comment] 2019-06-05 16:46
@sklam thanks a lot! It's easy to forget how much njit can do automatically once it knows the actual inputs.
 @wkerzendorf , does this help you? My example had arrays but your example does not seem to include arrays in the jitclass. You might need to make a minimalistic example for devs to triage.

**Comment by stuartarchibald** [comment] 2019-09-11 14:50
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-09-11 14:50 UTC
Labels: jitclass, no action required
