### ISSUE TITLE
guvectorize returns different output after upgrading to Numpy 1.20

### ISSUE THREAD

**Issue by RutgerK** [numba/numba#6864] opened 2021-03-25 11:12 UTC
After upgrading from Numpy 1.19.5 to Numpy 1.20.1 a Numba function I wrote using `guvectorize` suddenly returned different results. 

The issue appeared to be related to a mismatch between the datatype of the output array, and the signature of the function. **So at it's core, the bug is in the code I wrote**. But I'm posting it here anyway because I'm not sure if the change in behavior between the Numpy versions is intentional.

I provide a Numpy array initialized with zeros to the Numba function. The result is correct for elements in the output that are explicitly modified, but unmodified elements are returned as semi-random values. The wrong (unmodified) output values resemble what I would expect when initializing an array with `np.empty(...`.

The solution is (of course) to make sure the datatype of the output array matches that of the signature. Both changing the signature to `int8[:]`, or the output array to `np.uint8` would work in this case.

A toy example replicating the behavior is shown below. Notice the `np.int8` output array versus `uint8[:]` in the signature:
```python
import numba
import numpy as np

@numba.guvectorize(["void(float64[:], uint8[:])"], "(n)->(n)", nopython=True)
def func(x, out):
    
    for i in range(x.size):
        # set every fourth element to 1
        if i % 4 == 0:
            out[i] = 1

x = np.random.rand(150,150)
out = np.zeros_like(x, dtype=np.int8)

func(x, out)
```
With Numba 0.52 or 0.53 in combination with **Numpy 1.20.1**, this is the result:
```python
array([[  1,  49,  29, ...,  96,   1,   2],
       [  1,   0, -80, ..., -38,   1,  97],
       [  1,   2,   0, ...,   0,   1,   0],
       ...,
       [  1,  -1,  -1, ...,   0,   1,   0],
       [  1,   0,   0, ...,   0,   1,   0],
       [  1,   0,   0, ..., -34,   1,  97]], dtype=int8)
```

And with Numba 0.52 or 0.53 in combination with **Numpy 1.19.5**, this is the result:
```python
array([[1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0]], dtype=int8)
```

When using the new dynamic typing in Numba 0.53 it always works correctly, regardless whether the output array is `np.uint8` or `np.int8`. That's expected of course since it's impossible to provide the incorrect signature. 

This issue can be closed straight away if the behavior described above is as intended.

**Comment by hadia206** [comment] 2021-03-26 19:00
thanks @RutgerK for submitting this issue and bringing it to our attention. I was able to reproduce it and saw the same results you mentioned.
In addition, I changed the data type in both signature decorator `uint8[:]` and `dtype=int8` in `out` array. The behavior between np1.19.5 and np1.20.1 is the same in all cases (`int8[:]` with `dtype=int8`, `uint8[:]` with `dtype=uint8`, and `int8[:]` with `dtype=uint8`) except for the one you mentioned (`uint8[:]` and `dtype=int8`) where it gives random numbers.
Looking at `guvectorize` code it's simply providing the kernel to Numpy. So this issue is probably because of something new Numpy is doing with type handling with the output array. When type mismatch, np1.19.5 will cast the given output array to match the type and hence the given values will be available. It looks like with np1.20, it provides an uninitialized output array instead and that's why we see random values in the array instead.
The solution for now as you mentioned is to make sure the types match for output array and that of the signature.

**Comment by sklam** [comment] 2021-03-26 19:11
My question would be if this is an accidental change in NumPy 1.20. Would this break inplace operations `ufunc(inp, out=inp)`?

**Comment by sklam** [comment] 2021-03-31 17:38
Looks like numba can set the flags after this line https://github.com/numba/numba/blob/7e8538140ce3f8d01a5273a39233b5481d8b20b1/numba/np/ufunc/_internal.c#L227-L229

We can follow the [matmul flag set code in numpy](https://github.com/numpy/numpy/blob/a115369c630fd373acbb80464a0122722a521185/numpy/core/src/umath/ufunc_object.c#L345-L348).

**Comment by dmbelov** [comment] 2021-05-08 22:50
I have a related question:
I am frequently using generalized universal functions that modify inputs in-place.  Here is a simplistic example
```python
import numba
import numpy as np

@numba.guvectorize(["void(f8[:], f8[:])"], "(t),()", nopython=True)
def replace_2nd(x_t, y_1):
    for t in range(0, x_t.size, 2):
            x_t[t] = y_1[0]

x_t = np.zeros(5)
replace_2nd(x_t, 2)
```
This code works as expected.  However I do not understand if this fact is **reliable**?
1. If I were to write this function in C myself, I would set op_flag corresponding to 0-th input as reawrite:  `ufunc->op_flags[0] |= NPY_ITER_READWRITE | NPY_ITER_UPDATEIFCOPY;`.   I do not see that such READWRITE flag is set in Numba.
2. On the other hand Numba contains an example `numba/tests/test_num_threads.py` function `_test_set_num_threads_basic_guvectorize`  that explicitly writes to the input array.

I am confused. Could you please comment how reliable is the code written in Numba that updates input arrays  in-place?

**Comment by seberg** [comment] 2021-05-09 00:30
There are two things that could cause it to break, I think:

1. If the input has a different dtype (including byte order!)
2. If you have nothing marked for writing, overlap detection cannot work (this is tricky for normal ufuncs, they sometimes currently assume that all inputs are read-only here, unlike gufuncs).  In other words, you don't get overlap detection.

**Comment by gmarkall** [comment] 2022-01-06 21:47
Adding this to the 0.56RC milestone so we can try to look at it in time for the next release following 0.55. It is referenced on #6182 (which I think needs closing) but we still need to resolve this issue.

**Comment by apmasell** [comment] 2022-06-03 19:12
I've created an implementation, but I had some confusion. The default `op_flags` don't set `NPY_ITER_ALLOCATE`, but it behaves as if `NPY_ITER_ALLOCATE` unless `NPY_ITER_COPY` or `NPY_ITER_UPDATEIFCOPY` are set. That is very confusing behaviour and it's not clear that these flags aren't independent.

**Closed** 2022-06-24 22:16 UTC
Labels: numpy, discussion
