### ISSUE TITLE
`vectorize` with `parallel` target and OpenMP deprecation warnings

### ISSUE THREAD

**Issue by tasansal** [numba/numba#8434] opened 2022-09-11 00:24 UTC
Hi, 

I am using the latest available version of `numba` on `conda-forge` which is 0.55.2.

Once we even import our module, we get these deprecation warnings shown:
```shell
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
```

The below code reproduces the issue. It is a much-simplified version of our here: https://github.com/TGSAI/mdio-python/blob/main/src/mdio/segy/ibm_float.py
(Note: the nested `jit` and `vectorize` are so we can disable JIT and get test coverage on the single function. When we disable JIT, the `@vectorize` decorator ignores it, so we had to make a wrapper.)
```python
import numba as nb
import numpy as np


@nb.njit
def my_func_single(val):
    return val * 2


@nb.vectorize("uint32(uint32)", target="parallel")
def my_func(array):
    return my_func_single(array)


if __name__ == "__main__":
    vals = np.arange(5, dtype='uint32')
    result = my_func(vals)
    print(vals)
    print(result)
```

**Comment by tasansal** [comment] 2022-09-11 00:39
After some more simplification and testing, I realized we don't even need the nested `jit` and `vectorize`. I get the warning even with the following code:

```python
import numba as nb
import numpy as np


@nb.vectorize("uint32(uint32)", target="parallel")
def my_func_veconly(val):
    return val * 2


if __name__ == "__main__":
    vals = np.arange(5, dtype='uint32')
    result = my_func_veconly(vals)
    print(vals)
    print(result)
```

The only way to get around it is to remove the `parallel` target. However, we would like to use that. Any ideas?

**Comment by guilhermeleobas** [comment] 2022-09-12 17:02
Hi @tasansal, thanks for reporting this issue.

This is a duplicate of https://github.com/numba/numba/issues/5275. There's a work in progress for this in https://github.com/numba/numba/pull/7705

**Closed** 2022-09-12 18:03 UTC
Labels: duplicate, threading

**Comment by stuartarchibald** [comment] 2022-09-13 09:17
@tasansal the deprecation warning is coming from the OpenMP library itself and is about Numba's internal use of a deprecated OpenMP API to permit "nesting" of parallel regions, it shouldn't impact your code and is something for Numba to fix/update.

**Comment by tasansal** [comment] 2022-09-13 13:25
@guilhermeleobas @stuartarchibald Thanks for the update, sorry didn't see #5275 before opening this.

**Comment by stuartarchibald** [comment] 2022-09-13 13:36
> @guilhermeleobas @stuartarchibald Thanks for the update, sorry didn't see #5275 before opening this.

@tasansal No worries, many thanks for reporting it, it's a reminder that it still needs fixing!
