### ISSUE TITLE
Support list[any numba type]

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#2828] opened 2018-03-18 14:05 UTC
It would be useful to allow `list` to hold any Numba-supported type, in particular, other lists and Numpy arrays.

**Comment by stuartarchibald** [comment] 2018-03-19 10:39
Thanks for the request, this is definitely something that needs work! I am going to close this ticket though as it is a duplicate of https://github.com/numba/numba/issues/2560 (but will add to that ticket the common vocabulary as `memory-managed object` assumes familiarity with Numba internals).

**Closed by stuartarchibald** 2018-03-19 10:39 UTC
