### ISSUE TITLE
NotImplementedError/LoweringError when using jit on a function containing an inner function

### ISSUE THREAD

**Issue by gitavi** [numba/numba#2866] opened 2018-03-31 10:34 UTC
The [docs](http://numba.pydata.org/numba-doc/dev/reference/pysupported.html#inner-function-and-closure) suggest that the following should be fine (unless I'm interpreting it wrong of course):
```
from numba import jit

@jit
def foo():
    def bar():
        pass
    pass

foo()
```
but it's producing this error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    258     try:
--> 259         yield
    260     except NumbaError as e:

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_inst(self, inst)
     64         if isinstance(inst, ir.Assign):
---> 65             value = self.lower_assign(inst)
     66             self.storevar(value, inst.target.name)

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_assign(self, inst)
    158         elif isinstance(value, ir.Expr):
--> 159             return self.lower_expr(value)
    160         elif isinstance(value, ir.Global):

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_expr(self, expr)
    372         else:
--> 373             raise NotImplementedError(expr)
    374 

NotImplementedError: make_function(name=$const0.2, code=<code object bar at 0x7f335877fed0, file "<ipython-input-8-3fbbde7cf73c>", line 5>, closure=None, defaults=None)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-8-3fbbde7cf73c> in <module>()
      7     pass
      8 
----> 9 foo()

~/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    305                 argtypes.append(self.typeof_pyval(a))
    306         try:
--> 307             return self.compile(tuple(argtypes))
    308         except errors.TypingError as e:
    309             # Intercept typing error that may be due to an argument

~/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    577 
    578                 self._cache_misses[sig] += 1
--> 579                 cres = self._compiler.compile(args, return_type)
    580                 self.add_overload(cres)
    581                 self._cache.save_overload(sig, cres)

~/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     78                                       impl,
     79                                       args=args, return_type=return_type,
---> 80                                       flags=flags, locals=self.locals)
     81         # Check typing error if object mode is used
     82         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    777     pipeline = Pipeline(typingctx, targetctx, library,
    778                         args, return_type, flags, locals)
--> 779     return pipeline.compile_extra(func)
    780 
    781 

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    360         self.lifted = ()
    361         self.lifted_from = None
--> 362         return self._compile_bytecode()
    363 
    364     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    736         """
    737         assert self.func_ir is None
--> 738         return self._compile_core()
    739 
    740     def _compile_ir(self):

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    723 
    724         pm.finalize()
--> 725         res = pm.run(self.status)
    726         if res is not None:
    727             # Early pipeline completion

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    246                     # No more fallback pipelines?
    247                     if is_final_pipeline:
--> 248                         raise patched_exception
    249                     # Go to next fallback pipeline
    250                     else:

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    238                 try:
    239                     event(stage_name)
--> 240                     stage()
    241                 except _EarlyPipelineCompletion as e:
    242                     return e.result

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    634         """
    635         lowerfn = self.backend_object_mode
--> 636         self._backend(lowerfn, objectmode=True)
    637 
    638         # Warn if compiled function in object mode and force_pyobject not set

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    611             self.library.enable_object_caching()
    612 
--> 613         lowered = lowerfn()
    614         signature = typing.signature(self.return_type, *self.args)
    615         self.cr = compile_result(typing_context=self.typingctx,

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in backend_object_mode(self)
    585                                      self.library,
    586                                      self.func_ir,
--> 587                                      self.flags)
    588 
    589     def backend_nopython_mode(self):

~/anaconda3/lib/python3.6/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
    920     fndesc = funcdesc.PythonFunctionDescriptor.from_object_mode_function(interp)
    921     lower = objmode.PyLower(targetctx, library, fndesc, interp)
--> 922     lower.lower()
    923     if not flags.no_cpython_wrapper:
    924         lower.create_cpython_wrapper()

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    133         if self.generator_info is None:
    134             self.genlower = None
--> 135             self.lower_normal_function(self.fndesc)
    136         else:
    137             self.genlower = self.GeneratorLower(self)

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    174         # Init argument values
    175         self.extract_function_arguments()
--> 176         entry_block_tail = self.lower_function_body()
    177 
    178         # Close tail of entry block

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    199             bb = self.blkmap[offset]
    200             self.builder.position_at_end(bb)
--> 201             self.lower_block(block)
    202 
    203         self.post_lower()

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    214             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 
    218     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    263     except Exception as e:
    264         newerr = errcls(e).add_context(_format_msg(fmt_, args, kwargs))
--> 265         six.reraise(type(newerr), newerr, sys.exc_info()[2])
    266 
    267 

~/anaconda3/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

~/anaconda3/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    257 
    258     try:
--> 259         yield
    260     except NumbaError as e:
    261         e.add_context(_format_msg(fmt_, args, kwargs))

~/anaconda3/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    214             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 
    218     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_inst(self, inst)
     63     def lower_inst(self, inst):
     64         if isinstance(inst, ir.Assign):
---> 65             value = self.lower_assign(inst)
     66             self.storevar(value, inst.target.name)
     67 

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_assign(self, inst)
    157             return val
    158         elif isinstance(value, ir.Expr):
--> 159             return self.lower_expr(value)
    160         elif isinstance(value, ir.Global):
    161             return self.lower_global(value.name, value.value)

~/anaconda3/lib/python3.6/site-packages/numba/objmode.py in lower_expr(self, expr)
    371 
    372         else:
--> 373             raise NotImplementedError(expr)
    374 
    375     def lower_const(self, const):

LoweringError: Failed at object (object mode backend)
make_function(name=$const0.2, code=<code object bar at 0x7f335877fed0, file "<ipython-input-8-3fbbde7cf73c>", line 5>, closure=None, defaults=None)
File "<ipython-input-8-3fbbde7cf73c>", line 5
[1] During: lowering "$0.3 = make_function(name=$const0.2, code=<code object bar at 0x7f335877fed0, file "<ipython-input-8-3fbbde7cf73c>", line 5>, closure=None, defaults=None)" at <ipython-input-8-3fbbde7cf73c> (5)
```
I'm using Python 3.6.5 and numba 0.37.0.

**Comment by stuartarchibald** [comment] 2018-03-31 11:29
Thanks for the report. I think the issue is that an inner function is declared but not used, which is not a known pattern to the closure inlining pass. If you make use of the inner function, it should be fine?

**Comment by stuartarchibald** [comment] 2019-07-18 10:02
Closing this as it is now correctly caught with the error message:
```
numba.errors.UnsupportedError: Failed in object mode pipeline (step: ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context: bar (op code: make_function not supported). If the feature is explicitly supported it is likely that the result of the expression (bar) is being used in an unsupported manner.
```

**Closed by stuartarchibald** 2019-07-18 10:02 UTC
Labels: bug
