### ISSUE TITLE
Numba CUDA kernels fail when passing 0-size cupy arrays

### ISSUE THREAD

**Issue by RemiLehe** [numba/numba#4140] opened 2019-06-03 23:15 UTC
## Reporting a bug

- [x] I am using the latest released version of Numba
- [x] I have included below a minimal working reproducer

When passing a `cupy` array of size 0 to a Numba-CUDA kernel, the kernel launch fails with
```
 Call to cuPointerGetAttribute results in CUDA_ERROR_INVALID_VALUE
```

Here is a minimal example:
```python
import cupy
from numba import cuda

@cuda.jit
def fill_with_zeros(x, N):
    i = cuda.grid(1)
    if i < N:
        x[i] = 0

def get_array_filled_with_zeros(N):
    x = cupy.ones(N)
    assert N<128  # kernel is launched with 128 threads
    fill_with_zeros[1,128](x, N)
    return x

if __name__ == '__main__':
    get_array_filled_with_zeros(10) # Passes
    get_array_filled_with_zeros(1)  # Passes
    get_array_filled_with_zeros(0)  # Fails
```

**Comment by leofang** [comment] 2019-06-04 04:14
This is not a bug of Numba. Rather, this is due to a known behavior of CuPy, see cupy/cupy/issues/2104. In short, if you allocate a 0-size array in CuPy like you did:
```python
x = cupy.ones(0)
```
the pointer to the underlying GPU memory is `NULL`:
```python
>>> x.data.ptr
0
>>> x.__cuda_array_interface__['data'][0]
0
```
and dereferencing it using `cuPointerGetAttribute` then leads to error. It may not be the best behavior we can hope for, but I'd suggest moving the discussion to the linked issue.

**Comment by esc** [comment] 2019-06-04 08:26
@RemiLehe thanks for using Numba and reporting this issue! @leofang thanks for looking into this and commenting on this with a resolution. Since this is a CuPy issue I will close this ticket. Please feel free to re-open in case it does turn out to involve Numba.

**Comment by RemiLehe** [comment] 2019-06-04 20:03
@leofang @esc Thanks a lot for letting me know about the corresponding `cupy` issue! I agree that discussion belongs there.

**Comment by leofang** [comment] 2019-06-13 16:38
@esc @RemiLehe after working on supporting `__cuda_array_interface__` for mpi4py, I believe this is an issue on the Numba side, see #4175. Sorry that I didn't think this carefully earlier.

**Comment by stuartarchibald** [comment] 2019-09-25 08:04
reopened on request: https://github.com/numba/numba/issues/4175#issuecomment-534826817

**Closed** 2019-10-01 08:12 UTC
Labels: no action required
