### ISSUE TITLE
No way to convert strings to numbers not in object mode

### ISSUE THREAD

**Issue by 1e-to** [numba/numba#5190] opened 2020-02-03 13:15 UTC
Hi, in object mode, data can be converted from strings to numbers.
```python
b = np.array(['4', '5', '0', '1'])

@numba.jit
def test(b):
    for i in range(len(b)):
        print(int(b[i]))

test(b)
```
Output:
> 4
> 5
> 0
> 1

But when we try to use njit, an error occurs, can we do something about this?

**Comment by esc** [comment] 2020-02-03 13:28
@1e-to thanks for looking into this. Could you check if this might be a duplicate of #4758

**Comment by stuartarchibald** [comment] 2021-12-16 16:12
Closing as a dupliacte of #4758

**Closed by stuartarchibald** 2021-12-16 16:12 UTC
Labels: duplicate, feature_request
