### ISSUE TITLE
Return a `np.float32` and not a `float`

### ISSUE THREAD

**Issue by paugier** [numba/numba#4545] opened 2019-09-10 10:17 UTC
Hi Numba developers!

I found this issue while working on [Transonic](https://transonic.readthedocs.io).

This code works fine without the `@njit`. It compiles with `@njit` but there is a type problem: Numba returns a Python `float` and not `np.float32` or `np.float64` objects.

```python

import numpy as np

from numba import njit

@njit
def mysum(arr):
    result = arr.dtype.type(0)
    print("type(result)", type(result))
    for i in range(arr.shape[0]):
        result += arr[i]
    return result

def test(dtype):
    data = np.ones(100, dtype=dtype)
    result = mysum(data)
    print("type(result)", type(result))
    assert np.allclose(result, 100.0)
    assert result.dtype == dtype

test(np.float32)
test(np.float64)
```

**Comment by esc** [comment] 2019-09-10 11:45
@paugier thanks for reporting this and helping to improve Numba! It does look like a bit of a bug but will probably need some more triage. Is there a specific use-case you have that is blocking this or where you need a workaround?

**Comment by stuartarchibald** [comment] 2020-09-11 07:50
This is know behaviour and a duplicate of feature request https://github.com/numba/numba/issues/5990. Closing.

**Closed by stuartarchibald** 2020-09-11 07:50 UTC
Labels: needtriage
