### ISSUE TITLE
Windows: float % float generates a call to NULL

### ISSUE THREAD

**Issue by eltjpm** [numba/numba#379] opened 2013-12-20 16:03 UTC
```python
from numba import jit, float_

@jit(argtypes=(float_, float_))
def foo(x, y):
    return x % y

print foo(2, 1.5)
```
This crashes on Windows, because it generates `frem float` instruction. LLVM lowers it into a call to `fmodf`, which is not present in Windows CRT (as of VC10, at least). Somehow JIT doesn't report this as an error, and just leaves a call to NULL. This was reported on llvm-dev, but I haven't seen any follow-up: https://groups.google.com/forum/#!topic/llvm-dev/kPzAz91ygGo
We need to either fix this in lowering, or avoid generating `frem`.

Same for arrays:
```python
@jit(argtypes=(float_[:], float_[:]))
def foo2(x, y):
    return x % y

print foo2(np.array([2], dtype=np.float32), np.array([1.5], dtype=np.float32))
```

**Comment by pitrou** [comment] 2016-01-13 17:41
I cannot reproduce this issue (the bug was probably fixed long ago), closing.

**Closed by pitrou** 2016-01-13 17:41 UTC
