### ISSUE TITLE
cannot work for view_as_windows

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4120] opened 2019-05-25 11:04 UTC
I want to find the most efficient way to calculate the moving correlation. Three approach presented:

```
from skimage.util import view_as_windows
```

```
@jit(nopython=True)
def correlation1_jit(x1,x2,d):
	n = len(x1)
	ret = np.zeros(n)
	for i in np.arange(n-d+1):
	    xx1_i = x1[i:(i+d)]
	    xx2_i = x2[i:(i+d)]
	    #ret[i] = np.correlate(xx1_i,xx2_i)[0]
	    ret[i] = np.corrcoef(xx1_i,xx2_i)[0][1]
	return ret
#2.65 ms ± 17.5 µs per loop
thanks for upgrade to numba '0.43.1'
```

```
def correlation2(x1,x2,d):
	s1 = pd.Series(x1)
	s2 = pd.Series(x2)
	return s1.rolling(d).corr(s2)
#3.35 ms ± 63.3 µs per loop
```

```
def correlation3(x1,x2,d):

	m1 = view_as_windows(x1,d)
	m2 = view_as_windows(x2,d)

	m1_ = m1 - m1.mean(1,keepdims=True)	#must keep the same dim to broadcast
	m2_ = m2 - m2.mean(1,keepdims=True)

	ssm1 = (m1_**2).sum(1)
	ssm2 = (m2_**2).sum(1)
	ssm = (m1_*m2_).sum(1)

	return ssm/np.sqrt(ssm1*ssm2)
#346 µs ± 26.2 µs per loop
even faster than correlation1_jit
```

But I want to speed up with jit 

```
@jit(nopython=True)
def correlation3_jit(x1,x2,d):

	m1 = view_as_windows(x1,d)
	m2 = view_as_windows(x2,d)

	m1_ = m1 - m1.mean(1,keepdims=True)	#must keep the same dim to broadcast
	m2_ = m2 - m2.mean(1,keepdims=True)

	ssm1 = (m1_**2).sum(1)
	ssm2 = (m2_**2).sum(1)
	ssm = (m1_*m2_).sum(1)

	return ssm/np.sqrt(ssm1*ssm2)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'view_as_windows': cannot determine Numba type of <class 'function'>

File "<ipython-input-26-25f9ea82a063>", line 17:
def correlation3_jit(x1,x2,d):
    <source elided>

	m1 = view_as_windows(x1,d)
 ^
```

How can I fix this problem. Thank you :)

**Comment by stuartarchibald** [comment] 2019-05-28 09:38
Thanks for the report. The issue is that your code uses functionality from `skimage` which is not supported by Numba. The error message that was produced should have had two URLs in it pointing to what is supported by Numba, did they not appear?

**Comment by stuartarchibald** [comment] 2019-06-10 12:20
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Closed by stuartarchibald** 2019-06-10 12:20 UTC
Labels: no action required
